### ISSUE TITLE
Publishing a Python function fails in an environment that requires a HTTP proxy

### ISSUE THREAD

**Issue by matlec** [Azure/azure-functions-core-tools#1000]
Corporate policy requires us to use an HTTP proxy to connect to the internet. We were following [this tutorial](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python) to create a Python function and everything worked fine until we added a dependency to the `requirements.txt` file which was unavailable in the target environment and needed to built. So we added the `--build-native-deps` argument to the invocation of `func azure functionapp publish <app_name>`. However, command invocation fails during `pip install` with `Failed to establish a new connection: [Errno 111] Connection refused`. The reason for this is that the docker container has no knowledge of the HTTP proxy and tries to pull the python packages directly from the pip repository.

We solved this problem by passing the HTTP_PROXY and HTTPS_PROXY environment variables defined in the host system to the container. We did this by replacing the [following code](https://github.com/Azure/azure-functions-core-tools/blob/b2157d366244c7a72f208261ba8d3c5acbda8f81/src/Azure.Functions.Cli/Helpers/DockerHelpers.cs#L28) with `(var output, _) = await RunDockerCommand($"run -e HTTP_PROXY -e HTTPS_PROXY -e http_proxy -e https_proxy --rm -d {image}");`. Passing `HTTP_PROXY` and `HTTPS_PROXY` from the host as lower-case `http_proxy` and `https_proxy` variables to the container is additionally required in order to let the subsequent invocation of `apt-get install` succeed (`apt-get` uses lower-case).

**Comment by ankitkumarr** [comment]
Closing this for now. Please feel free to reopen this issue if configuring Docker client doesn't work for your scenario.
