### ISSUE TITLE
Add README.md to npm package

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-core-tools#1005]
It would be great to have a README with the [npm package](https://github.com/Azure/azure-functions-core-tools/tree/dev/src/Azure.Functions.Cli/npm) so that it shows up in [npm](https://www.npmjs.com/package/azure-functions-core-tools). (Maybe even as easy as a link to core tools documentation.)

![image](https://user-images.githubusercontent.com/8888531/51869067-60a86200-2304-11e9-984b-8c7ac1fdfa0c.png)

**Comment by ankitkumarr** [comment]
Looks like @ahmelsayed fixed this :)
![capturea](https://user-images.githubusercontent.com/16520682/52094136-d0238900-2572-11e9-8e6b-9b2f06e54e90.PNG)
Closing this issue
