### ISSUE TITLE
Cannot launch multiple func.exe's on different ports locally

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-core-tools#1006]
I've got a solution with multiple Function **apps** in it (so I can deploy each to a separate function app and scale each independently in Azure)

To test the interoperability of these locally, I configure each's Debug settings using the `-port` switch:

!["default" function app, expected port 7071 gets used](https://user-images.githubusercontent.com/20270743/51768188-76afeb80-2094-11e9-91fc-6db265442a41.png)
("default" function app, expected port 7071 gets used)

![image](https://user-images.githubusercontent.com/20270743/51768220-90e9c980-2094-11e9-99cd-683981f5a1fe.png)
second app, use port 7072

![image](https://user-images.githubusercontent.com/20270743/51768238-9f37e580-2094-11e9-91c4-f35463391d43.png)
third app, use 7073

I then configure the Solution to launch all 3 apps at the same time when I debug
![image](https://user-images.githubusercontent.com/20270743/51768286-bb3b8700-2094-11e9-8a37-f0a1ae0af9f2.png)

Then I click 'Start' in Visual Studio. When all 3 apps fire up, the two apps with the `-port` flag specified error out saying it's an unknown argument and the one without a port specifier works as expected
![image](https://user-images.githubusercontent.com/20270743/51768599-9bf12980-2095-11e9-8f54-c3456ae925cc.png)

this despite `func -h` showing `-port` as a valid flag
~~~
C:\Users\***> func -h

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.3.199 Commit hash: fdf734b09806be822e7d946fe17928b419d8a289)
Function Runtime Version: 2.0.12246.0
Usage: func [context] [context] <action> [-/--options]

Contexts:
azure       Commands to log in to Azure and manage resources
durable     Commands for working with Durable Functions
extensions  Commands for installing extensions
function    Commands for creating and running functions locally
host        Commands for running the Functions host locally
settings    Commands for managing environment settings for the local Functions host
templates   Commands for listing available function templates

Actions:
start   Launches the functions runtime host
    --port [-p]        Local port to listen on. Default: 7071
~~~

#### Investigative information
- Function App version (1.0 or 2.0): v2
- CLI Version: 2.0.16
- Function runtime version: 2.0.12265

#### Expected behavior
I expect the `-port` flag to be passed as an argument to func.exe as I've set it to be in the Project settings of the Function App in Visual Studio 2017, then the func host to spin up on that port & host the Function(s) in the specified Function App at that endpoint.

#### Actual behavior
Upon launch from Visual Studio the func host complains that `-port` is not a valid argument

#### Known workarounds
changing to `-p` also fails in the same manner (unrecognized argument)
opening a command prompt, changing to the Function's directory and manually executing `func start -p <port>` works as expected, however to debug I now have to go in to VS and use Attach Process which is not desirable.

**Comment by brandonh-msft** [comment]
I see now that I was erroneously using `-port` instead of double-dash. That said, I did try `-p` (in the known workarounds area of my initial post) which also failed.

**Comment by brandonh-msft** [comment]
so `-p` doesn't work, despite the arg being shown as possible:
![image](https://user-images.githubusercontent.com/20270743/51950183-41810180-23e4-11e9-8204-c45c89dea4de.png)

but fixing my arg to `--port` *did* work. Additionally, in case it wasn't clear in my original post, changing my args to `start -p 7072` worked (even though just `-p 7072` didn't)

**Comment by ahmelsayed** [comment]
oh, sorry I think I skipped part of the issue. 
When you add a command there, you take over all the command line. I think it make sense to only take over after the `start` action though that will be a breaking change to the tooling.

**Comment by brandonh-msft** [comment]
how does that explain `--port xxxx` working? yes, using `start --port` or `start -p` worked, but also `--port` works where `-p` doesn't. 😕

**Comment by ahmedelnably** [comment]
Closing as stale, please open a new issue if you are still facing the same error
