### ISSUE TITLE
Running func publish and host id

### ISSUE THREAD

**Issue by altmnt** [Azure/azure-functions-core-tools#1012]
When I run `func azure functionapp publish myapp` it deploys my function app for Linux which is triggered by storage blobs. My problem is that runtime v2 does not support setting HostId in host.json. 
After publishing I get new HostID and all the receipts from my previous deploy are disregarded by new deployment and function starts triggerring for every blob in the storage. Any ideas how to change it?

**Comment by JohnReeson** [comment]
See more details in [SO](https://stackoverflow.com/questions/54458216).

**Comment by altmnt** [comment]
[Raised issue in Azure functions github](https://github.com/Azure/Azure-Functions/issues/1119)

**Comment by altmnt** [comment]
@mathewc Host Id is being changed automatically over the time. Without even doing publish. I see that my function run several times today. all receipts are with the new IDs.

**Comment by altmnt** [comment]
I can confirm that this is a Linux runtime issue. Windows runtime works as expected (HostID = App name).

**Comment by derekrprice** [comment]
I've encountered the same problem and I cannot set environment variables with colons (":") in the name from a Kubernetes deployment file.  Is there another work-around?

**Comment by ahmelsayed** [comment]
it has to be [`AzureFunctionsWebHost__hostid`](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Config/ConfigurationSectionNames.cs#L13)

**Comment by derekrprice** [comment]
That worked, thanks!

**Comment by ahmedelnably** [comment]
Closing as resolved
