### ISSUE TITLE
Proxies Not Supported by the CLI

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-functions-core-tools#102]
Azure Functions now has "Proxies" controlled by proxy.json.  This functionality is not yet mirrored in the azure-functions-cli. 

As a result its not possible to do local development with proxies.

**Comment by ahmelsayed** [comment]
@safihamid have you guys given local development any thoughts?
To get it added to the CLI you'll need to ship the proxies project as a nuget package and be able to use HttpSelfHostServer for a hosting server. Much like [WebJobs.Script.WebHost](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/packages.config#L63)

**Comment by safihamid** [comment]
We will look into this but will probably take us sometime to have a fix for it.

**Comment by safihamid** [comment]
This is already working.
