### ISSUE TITLE
Remove venv dependency for Python

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1023]
Here's a brain dump from our discussion: 

- The user shouldn't need to have a virtual environment anymore since the worker and system dependencies are packaged into a nuget. 
- Basically, they should be able to publish an app with a blank requirements file and the app should just work. 
- Keep in mind not to run a `pip freeze` since that has the potential to load up the requirements file with everything on the user's system

**Comment by ankitkumarr** [comment]
@asavaritayal, looks like we don't have the worker (and its dependencies) being packaged as a nuget package yet. So, maybe I should hold on until then.

**Comment by asavaritayal** [comment]
I believe @maiqbal11 is yet to close the PR but the work is done.

**Comment by maiqbal11** [comment]
@asavaritayal @ankitkumarr, I had received feedback from @ahmelsayed and @elprans on the PR but we haven't closed on it: https://github.com/Azure/azure-functions-python-worker/pull/311#discussion_r253232465

**Comment by maiqbal11** [comment]
Created a new PR for generating platform specific worker run environments: https://github.com/Azure/azure-functions-python-worker/pull/329

**Comment by fabiocav** [comment]
Moving to sprint 44 for validation.

**Comment by dirkesquire** [comment]
This looks great. And I assume that if we put something in to the requirements file (i.e. into requirements.txt) they will get installed automatically as well. This will be ideal.
