### ISSUE TITLE
Error calling sync triggers (BadRequest)

### ISSUE THREAD

**Issue by dajor** [Azure/azure-functions-core-tools#1025]
I just make a update today to the latest version because I had some issue with azure-cosmos. But now I am getting even with a empty project 

**Error calling sync triggers (BadRequest).**
 **__init__.py** 
import logging

import azure.functions as func

def main(myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")
 **function.json** 
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "myblob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "transferin/{name}",
      "connection": "sausstoraget_STORAGE"
    }
  ]
}

**Comment by ankitkumarr** [comment]
Thanks for reporting this. I believe there was a short outage (resolved now) when you opened the issue. It should be fixed now. I am closing the issue, but please re-open if you see this problem again.
