### ISSUE TITLE
Portal Log Streaming doesn't work well for Linux Consumption

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-core-tools#1026]
In Linux Consumption, there is no shared file system, so our Portal log streaming doesn't work well when there are multiple scaled out instances. In such cases, the portal will only be showing logs from 1 of the instances (the one it is connected to). Currently, the experience relies on log file polling, to simulate Kudu log streaming. The problem is that only log files from a single instance are polled - there is no shared file system. This means that executions happening on other instances aren't shown in the stream.

We need a new design that gets logs working consistently in the portal for Linux Consumption.

**Comment by ahmedelnably** [comment]
Closing the loop here, we have chosen option #1.
Though it is available right now in the portal, we will track the core tools experience in a separate issue
