### ISSUE TITLE
func cli should auto install extensions specified in function.json

### ISSUE THREAD

**Issue by SteveL-MSFT** [Azure/azure-functions-core-tools#1027]
Was testing a PowerShell v2 function with Storage Queue output binding.  Followed the examples for host.json to set it up.  Published successfully, but didn't work.  The portal had a less than helpful error that the queue extension was not there (or something like that).  Did a search on the web to eventually find out I needed to run `func extension install queues`.  Since my function.json specified I was using queue output binding, it should have auto-installed (or prompted) rather than having me search for this since it was not obvious when it failed.

**Comment by ahmelsayed** [comment]
@ankitkumarr before any build step we should always restore all the extensions like `func extension install` does.

**Comment by ankitkumarr** [comment]
@ahmelsayed, I will add a step before initiating publish, to install all extensions present. But, I thought we do install the specific extension when we deploy a template during `func new`.
