### ISSUE TITLE
az webapp deployment source config command fails when trying to add an external repository using a url that isn't one of certain hostnames

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-functions-core-tools#1028]
If I try to use the Azure CLI command az webapp deployment source config to add an external repository using a url that doesn't use a hostname such as GitHub.com, Bitbucket.org, dev.azure.com (or technically onedrive.com or dropbox.com), it fails with error indicating that the repo-url has an invalid value.

For example, I am trying to add a GitLab external repository via the following command:
az webapp deployment source config --repo-url https://gitlab.com/myfakeaccount/myfakeproj.git --branch master --repository-type externalgit --name myfakeappservice --resource-group myresourcegroup --subscription myfakesubid

This fails with the following error:
The parameter https://gitlab.com/myfakeaccount/myfakeproj.git has an invalid value.

If I add the external repository using the same url via the portal, it succeeds. So it would seem that adding the url via CLI should be allowed, but is presumably failing because CLI validates against a list of specific repo hostnames.

If I then use the cli to get the repository info, it returns the repoUrl as expected. Eg:
az webapp deployment source show --name myfakeappservice --resource-group myresourcegroup --subscription myfakesubid

So the issue appears to be specific just to adding the repoUrl.

**Comment by ankitkumarr** [comment]
Hi @gabesmsft, this is the repository for Azure Functions CLI for local development (`func`). For Azure CLI (`az`) (Azure management operations), please move the issue to the [Azure CLI repository](https://github.com/Azure/azure-cli).

Thanks!

**Comment by gabesmsft** [comment]
This issue was moved to gabesmsft/fakeplaceholder#1
