### ISSUE TITLE
[packapp] Don't fail when developing on a compatible Linux platform

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1030]
Currently, if you're developing on a 64-bit Linux machine and using packages that don't support pre-built wheels, you'll receive the following error: 

```
There was an error restoring dependencies.ERROR: cannot install <package name - version> dependency: binary dependencies without wheels are not supported.  Use --build-native-deps
The terminal process terminated with exit code: 1
```

`--build-native-deps` shouldn't be required since we can build the right wheels on the development platform itself.

**Comment by asavaritayal** [comment]
@elprans can you look into this?

**Comment by elprans** [comment]
@asavaritayal Being on a 64-bit linux machine does not guarantee that the resulting binary would be compatible.  It is the reason why manylinux exits.  The only way to guarantee maximum wheel compatibility is to build it in a compatible docker container.

**Comment by asavaritayal** [comment]
@elprans got it, thanks for providing that context. 

Reading up a little [more](https://github.com/pypa/manylinux), it looks like the only way to ensure Linux platform compatibility would be to build in a very specific distro or many-linux based docker container. 

/cc @ankitkumarr as FYI
