### ISSUE TITLE
System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by dsartain18** [Azure/azure-functions-core-tools#1034]
When I run this command in git bash for Windows, which I do almost anything git or repo related in, it gives me this error and then gives a new command prompt.

When I run this in PowerShell it then gives me an option to select from dotnet, node, etc.

Is there any way you can work on how this displays in git bash?

![gitbashinvalidhandle](https://user-images.githubusercontent.com/15874631/52544937-92e0a780-2d79-11e9-8787-c8cb9e688934.PNG)

**Comment by ahmelsayed** [comment]
It must be because of the console APIs. is this mintty? 

the only work around would be to specify all the options on the command line itslef, for example `func init . --worker-runtime <python/dotnet/node>`

**Comment by dsartain18** [comment]
Ah, ok. Thanks!

**Comment by ahmelsayed** [comment]
I think we should still fix it though :)
