### ISSUE TITLE
Add TypeScript option for func init and func new

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-core-tools#1037]
We want to add the ability to `func init` a TypeScript template with a pre-populated package.json that contains npm scripts. We also want to be able to `func new` TypeScript templates from the templates feed.

@mhoeger to provide templates through feed [see here](https://github.com/Azure/azure-functions-templates/issues/804)

@ColbyTresness to provide more details on how the user should be prompted.

**Comment by asavaritayal** [comment]
We use `func init` for stack level selection. I think TypeScript should be a `func new` level selection.

**Comment by ColbyTresness** [comment]
You actually need it at the function app level since we opt you into a different folder structure. agreed its a bit different and we've thought a bunch about the different ways to do this, but doing it at the func new level isn't sufficient.

**Comment by fabiocav** [comment]
Assigning this to the current sprint, but this will take a lower priority than some of the other issues @ankitkumarr is working on and will need to be tracked as a stretch goal for this sprint.

**Comment by ColbyTresness** [comment]
Behavior:
func init allows the user to specify TS as an option, if selected provides the user with tsconfig and package.json files
if a .tsconfig is present, func new opts to use the ts templates rather than the js ones
other func commands remain the same.
