### ISSUE TITLE
OGF Tests for Python 

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-core-tools#1040]
Need to add tests that step through the user experience of creating Python functions. The following scenarios should be covered at a minimum:

1. Basic HttpTrigger creation with appropriate response upon invocation
2. Queue triggered function (testing extensions)
3. ~~Third party library inclusion and usage~~ (should be covered on this as we import functions library)
4. Publish using standard path (not bundled via PyInstaller)

**Comment by maiqbal11** [comment]
\cc @asavaritayal, feel free to add to this list. Hoping to get these into the docs for the next release.

**Comment by asavaritayal** [comment]
@maiqbal11 If there's no more required here, should we go ahead and close this?

**Comment by maiqbal11** [comment]
Yup, I'll close this out.
