### ISSUE TITLE
Publish action setting WEBSITE_RUN_FROM_ZIP instead of WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by hannesne** [Azure/azure-functions-core-tools#1041]
When I use the `func azure functionapp publish {myappname}` command on a Java app, the code is deployed to a function app by uploading the zip to storage, and setting WEBSITE_RUN_FROM_ZIP application setting to that url. This is incorrect, the application setting whould be WEBSITE_RUN_FROM_PACKAGE. Subsequent deploys using other methods set the WEBSITE_RUN_FROM_PACKAGE, which gets ignored while the older WEBSITE_RUN_FROM_ZIP setting is there.

**Comment by ankitkumarr** [comment]
This was closed by https://github.com/Azure/azure-functions-core-tools/pull/1008.
It should be available in the next release. 

Closing the issue, please reopen if you continue to see issues after the release.
