### ISSUE TITLE
func azure functionapp publish doesn't work for Java functions

### ISSUE THREAD

**Issue by hannesne** [Azure/azure-functions-core-tools#1042]
func azure functionapp publish {appname} doesn't work for Java functions, as it just zip up the entire current working directory. It should package up the target\azure-functions\{appname} directory.

**Comment by ahmedelnably** [comment]
Please use the Azure Functions maven tools to deploy Java Functions

**Comment by hannesne** [comment]
The CLI should give a warning or error in this scenario.
