### ISSUE TITLE
Document how to build a function project and provide a `publish-zip` command line.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-core-tools#1046]
currently `publish` tries to detect the app language, and based on that it does something different depending on the framework. 

I think it'll be more consistent to document how to create the zip archive for your function separately and then add a `publish-zip` command that takes in a zip file and knows how to upload it to azure and what to set there. This should reduce the confusion about how to build and prepare the zip file, and make the cli only relevant in how to upload it to azure.

**Comment by ahmedelnably** [comment]
Closed as duplicate
