### ISSUE TITLE
Function ({FunctionName}) Error: The function type name '{Namespace}.{FunctionName}' is invalid.

### ISSUE THREAD

**Issue by mamichae** [Azure/azure-functions-core-tools#1059]
getting this error when publishing azure function.

**Comment by ankitkumarr** [comment]
@mamichae, a couple of questions to help us investigate-

1. When/Where do you see this error? Is it during publishing from the CLI or after publishing in the portal?
2. What language are you using (dotnet, python, node)?
3. Any logs and/or reproduction steps will help us investigate.

**Comment by mamichae** [comment]
1. publishing in visual studio. Build -> Publish
2. .Net Core
3. Repro steps
- Create new Azure function solution (New Project -> Azure Functions OK -> Azure Functions v2, Timer trigger -> OK)
- Publish to azure function (Build -> Publish -> Import profile -> Publish
- Go to function app in azure portal -> click the function -> red error box appears on top right corner saying: 
Function (Function1) Error: The function type name 'FunctionApp1.Function1' is invalid.
Session Id: 9166181825004857b90271d0f26ccc34

Timestamp: 2019-02-21T20:19:33.901Z

**Comment by mamichae** [comment]
also the function app is in azure stack

**Comment by daanl** [comment]
Same here

**Comment by EugeneFoo** [comment]
same, what's going on with Azure Publish in VS Mac.

**Comment by danbete** [comment]
worked for me:
in the .csproj file try that
remove ItemGroup items if you not using the packages im using..
i'm keeping them here for referance... (so edit this - **don't just copy past**)
hope it will help someone..

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
    <UseNETCoreGenerator>true</UseNETCoreGenerator>
    <EnableMSDeployAppOffline>true</EnableMSDeployAppOffline>

  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="10.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by ahmelsayed** [comment]
`Function ({FunctionName}) Error: ....` are server side errors, not core tools related.
