### ISSUE TITLE
Publish Azure Function is Failing with error restoring dependencies

### ISSUE THREAD

**Issue by abhinavbom** [Azure/azure-functions-core-tools#1063]
Publishing Azure Function through VS code is resulting into this error: 

> There was an error restoring dependencies.ERROR: cannot install yara-python-3.8.1 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish

When I test the app locally, it works perfectly fine. I tried a bunch of solutions mentioned for similar issue but unable to resolve it. 

Here are my requirements:

asn1crypto==0.24.0
azure-common==1.1.17
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b3
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.5
forked-path==0.2.3
grpcio==1.14.2
grpcio-tools==1.14.2
idna==2.8
protobuf==3.6.1
pycparser==2.19
pymongo==3.7.2
python-dateutil==2.7.5
python-magic==0.4.15
requests==2.21.0
six==1.12.0
urllib3==1.24.1
yara-python==3.8.1

**Comment by ahmelsayed** [comment]
did you try `--build-native-deps` as the error is suggesting?

**Comment by abhinavbom** [comment]
@ahmelsayed  Thanks for responding. 
The error suggested to use this command: 

> func azure functionapp publish <app_name> --build-native-deps --no-bundler


If I drop --no-bundler, things work for me. I am not sure what difference it is making. 
Closing the current issue for now.
