### ISSUE TITLE
Some binding type not in BindingPackageMap

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-core-tools#1075]
https://github.com/Azure/azure-functions-core-tools/blob/7aee2debd23872ea5bd52b220611d2bb1a64b982/src/Azure.Functions.Cli/Common/Constants.cs#L84

type like table, twilioSms, signalRConnectionInfo and signalR are not in `BindingPackageMap` hence `func extensions install` doesn't install extensions as expected.

**Comment by soninaren** [comment]
`signalRConnectionInfo` and `signalR` have to the binding map in this PR. 
https://github.com/Azure/azure-functions-core-tools/pull/1091

Will add twilioSms
