### ISSUE TITLE
Deploy via WEBSITE_RUN_FROM_PACKAGE=1 for non-Linux

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1086]
Today the default is to deploy via Run from Package, but the "URL" method.  We know from data that you get better cold start on Windows if you do the run from package = 1 approach.  We should change the default in the CLI so that if deploying to a Windows plan, set the app setting for `WEBSITE_RUN_FROM_PACKAGE=1` and then do a zip deploy.

You can mirror this today but updating the app setting to `WEBSITE_RUN_FROM_PACKAGE=1` and then running the command `func azure functionapp publish <appName> --nozip` - but it's a bit counter-intuitive.

https://github.com/Azure/azure-functions-core-tools/blob/e58a6fe5afd37640329c0f2f61b9d83271de84c1/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L291-L298

**Comment by mhoeger** [comment]
@jeffhollan - do we want to support users doing Run from Package via URL? Or should we just replace the default deploy logic like below?

Roughly:
```c#
 if ((functionApp.IsLinux && functionApp.IsDynamic) || RunFromZipDeploy) 
 { 
     await PublishZipDeploy(functionApp, await zipStreamFactory()); 
     await UpdateAppSetting("WEBSITE_RUN_FROM_PACKAGE", "1");
 } 
 else 
 { 
     await PublishZipDeploy(functionApp, zipStreamFactory); 
 } 
```

**Comment by mhoeger** [comment]
Updated logic:
 - If Consumption and Linux: publish run from package = sas
 - If Dedicated Linux or "--no-zip": publish zip deploy
 - Otherwise, publish run from package = 1 and zip deploy
