### ISSUE TITLE
Cannot publish Python 3.6 function app with 3.7 system Python

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-functions-core-tools#1087]
Unable to publish a strictly Python 3.6 app when the system Python is 3.7 or higher

Note: workaround exists

#### Investigative information

- Core Tools version: 2.4.401
- Virtual Env: 3.6.8
- System Python: 3.7.2

#### Repro steps

- Install Python 3.7 as your system Python (`brew install python` via Homebrew on Mac will do)
- Create a Python 3.6 virtualenv for your function app and activate it
- Try to publish your function app via `func azure functionapp publish`

Observe error:
```Unable to connect to Azure. Make sure you have the `az` CLI or `Az.Accounts` PowerShell module installed and logged in and try again```

- Deactivate virtual env / use system Python (3.7) and try to publish with the same command again:
Observe an error stating that certain 3.6 only packages (such as tensorflow at time of writing) cannot be found.

#### Expected behavior

The app is published from my virtual environment.

#### Actual behavior

App publishing errors out.
Azure CLI is not install within the Python 3.6 virtual env and therefore cannot be found / used.

#### Known workarounds

Use Dockerized build method (`--build-native-deps`) from the global system python (3.7) with `az` command installed:
```
func azure functionapp publish tfserverless --build-native-deps
```

#### Proposed solution
Remove dependency on Azure CLI from Functions Core Tools

**Comment by ahmelsayed** [comment]
why is azure-cli not found while in the venv? are you installing it using pip?

**Comment by asavaritayal** [comment]
Closing as this seems specific to pyenv and should be tracked in the Azure CLI backlog. @qubitron to follow up with the az CLI folks.
