### ISSUE TITLE
PyInstaller module cannot be found while deploying with --build-native-deps flag

### ISSUE THREAD

**Issue by vakarpus** [Azure/azure-functions-core-tools#1092]
Error log here (full log - https://pastebin.com/cCQst6GH):

	Successfully installed azure-functions-1.0.0a5 azure-functions-worker-1.0.0a6 grpcio-1.14.2 grpcio-tools-1.14.2 numpy-1.16.2 protobuf-3.6.1 scikit-learn-0.20.3 scipy-1.2.1 six-1.12.0 sklearn-0.0
	You are using pip version 18.1, however version 19.0.3 is available.
	You should consider upgrading via the 'pip install --upgrade pip' command.
	Collecting pyinstaller==3.4
	  Downloading https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz (3.5MB)
	
	    0% |                                | 10kB 912kB/s eta 0:00:04
	    0% |▏                               | 20kB 1.2MB/s eta 0:00:04
	
	    99% |███████████████████████████████▉| 3.5MB 16.8MB/s eta 0:00:01
	    99% |████████████████████████████████| 3.5MB 17.1MB/s eta 0:00:01
	    100% |████████████████████████████████| 3.5MB 7.3MB/s 
	  Installing build dependencies ... done
	  Getting requirements to build wheel ... error
	  Complete output from command /root/.pyenv/versions/3.6.8/bin/python3.6 /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkrtevdgi:
	  Traceback (most recent call last):
	    File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
	      main()
	    File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
	      json_out['return_val'] = hook(**hook_input['kwargs'])
	    File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
	      return hook(config_settings)
	    File "/tmp/pip-build-env-s2ml3l1m/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
	      return self._get_build_requires(config_settings, requirements=['wheel'])
	    File "/tmp/pip-build-env-s2ml3l1m/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
	      self.run_setup()
	    File "/tmp/pip-build-env-s2ml3l1m/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 126, in run_setup
	      exec(compile(code, __file__, 'exec'), locals())
	    File "setup.py", line 20, in <module>
	      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
	  ModuleNotFoundError: No module named 'PyInstaller'
	  
	  ----------------------------------------
	Command "/root/.pyenv/versions/3.6.8/bin/python3.6 /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkrtevdgi" failed with error code 1 in /tmp/pip-install-wh94ba86/pyinstaller

**Comment by vakarpus** [comment]
PyInstaller installed locally though.

**Comment by ankitkumarr** [comment]
@vakarpus you can mitigate the issue using `--no-bundler` while publishing. For info about this flag checkout [this](https://aka.ms/func-python-publish) page. 

I will take a look at why this is failing. But, we are thinking of moving away from `Pyinstaller` very soon.

**Comment by vakarpus** [comment]
@ankitkumarr Looks like this flag is working for me. Can you quickly explain what exactly it's doing? Thanks!

(.env) []15:35:11 vakarpus@Vadims-MacBook-Pro:~/MyFunctionProj$  $ func azure functionapp publish vadim-pyfunc --build-native-deps --no-bundler
Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0'..done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0'..done
Running 'docker exec -t 2cca08 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp /var/folders/cn/xqlj9myj2gzb254449cw5mxc0000gn/T/tmpV7GcMjtmp/. 2cca08:/home/site/wwwroot'..done
Running 'docker cp /var/folders/cn/xqlj9myj2gzb254449cw5mxc0000gn/T/tmpCATUwX.tmp 2cca08:python_docker_build.sh'..done
Running 'docker cp /var/folders/cn/xqlj9myj2gzb254449cw5mxc0000gn/T/tmpK8Wvhr.tmp 2cca08:python_bundle_script.py'..done
Running 'docker exec -t 2cca08 chmod +x /python_docker_build.sh'..done
Running 'docker exec -t 2cca08 chmod +x /python_bundle_script.py'..done
Running 'docker exec -t 2cca08 /python_docker_build.sh'...............................................................................done
Running 'docker cp 2cca08:/app.zip /var/folders/cn/xqlj9myj2gzb254449cw5mxc0000gn/T/vhesiltp.lt1'...done
Running 'docker kill 2cca08'..done
Preparing archive...
Uploading 160.07 MB [#############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
....

**Comment by ankitkumarr** [comment]
@vakarpus, during a general publish using `--build-native-deps`, we try to use Pyinstaller to bundle all the custom dependencies specified in your `requirements.txt` together with our runner (worker). We started to do this in an effort to improve startup performance that you get after publishing to Azure Functions. Although, this process has been flaky and we are planning on moving away from it.

`--no-bundler` flag bypasses that bundling process. So, we do not use Pyinstaller or any such module to do temporary optimizations. The caveat is that you may experience slight linger delay (cold start) when hitting your API end-point.

**Comment by vakarpus** [comment]
Got it! Thanks for the explanation.

**Comment by lutherspacep** [comment]
How would you work around this using an azure pipeline?

**Comment by ankitkumarr** [comment]
@lutherspacep, we do not use Pyinstaller anymore for our publishing pipeline. You shouldn't see this in the last few versions of the `azure-functions-core-tools`. What problem are you facing to work around for?
