### ISSUE TITLE
Publishing Python function app fails

### ISSUE THREAD

**Issue by raghavan20** [Azure/azure-functions-core-tools#1101]
I have looked at https://github.com/Azure/azure-functions-core-tools/issues/822 and the debug logs does not have the same symptom as the issue I have encountered. I am new to Azure Functions, as I understand that developing Azure functions on Mac/Linux is a preview feature and the below error may not occur if I try the same from a Windows machine.

**Reference followed:** 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python#deploy-the-function-app-project-to-azure

**Steps:**
1. `az functionapp create --resource-group rg --os-type Linux --consumption-plan-location eastasia --runtime python --name app2 --storage-account rgsa`
2. CLI_DEBUG=1 func azure functionapp publish app2

**Extra information:**
I hold two subscriptions and I have set my corporate subscription as the active one using command `az account set --subscription <corporate-sub-id>`

**Logs:**
```
> az account get-access-token --query "accessToken" --output json
Request:
Method: GET, RequestUri: 'https://management.azure.com/subscriptions?api-version=2018-09-01', Version: 2.0, Content: <null>, Headers:
{
  Authorization: Bearer
  User-Agent: functions-cli/2.0
  Accept: application/json
  x-ms-request-id: 613b7f81-4c39-4116-8e99-95710a84af01
}

Response:
StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  WWW-Authenticate: Bearer authorization_uri="https://login.windows.net/", error="invalid_token", error_description="The authorization header is missing access token."
  x-ms-failure-cause: gateway
  x-ms-request-id: 302a3505-859b-4529-9449-c90062cfa613
  x-ms-correlation-request-id: 302a3505-859b-4529-9449-c90062cfa613
  x-ms-routing-request-id: SOUTHINDIA:20190305T050005Z:302a3505-859b-4529-9449-c90062cfa613
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Date: Tue, 05 Mar 2019 05:00:05 GMT
  Connection: close
  Content-Type: application/json; charset=utf-8
  Expires: -1
  Content-Length: 144
}
{"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}


...
```

**Comment by horihiro** [comment]
I'm facing similar issue now, so I can't deploy to my python function with app service plan created by Azure CLI.
On the other hand, I can deploy to the python function using app service plan created from Azure Portal.

What's the difference?

**Comment by horihiro** [comment]
This issue for me is resolved by  using Azure CLI 2.0.60 when creating Function App.

Using 2.0.59 and before, invalid container image name is set.

**Comment by raghavan20** [comment]
I have installed `2.0.60` of `azure-cli` by running `curl -L https://aka.ms/InstallAzureCli | bash`. I deleted the old app instance from my resource group and created a new one using a similar command as below

`az functionapp create --resource-group my-rg --os-type linux --consumption-plan-location eastasia --runtime python --name myapp --storage-account my-rg-sa`

on 

`func azure functionapp publish myapp` 

i get

`Response status code does not indicate success: 401 (Unauthorized).`

**Comment by horihiro** [comment]
Hmm,

I'm not sure that the reasons why you got an 401 error using 2.0.60.

In mycase, the container name, which can be found in [Resource Explorer](https://resources.azure.com), is set to `DOCKER|mcr.microsoft.com/azure-functions/python:2.0` as following when Function App is createted by `az functionapp create` using 2.0.60.

![image](https://user-images.githubusercontent.com/4566555/54730155-ada10a00-4bca-11e9-895c-bfef89ee6fce.png)

But using 2.0.59 or before, the container name is invalid as following.

![image](https://user-images.githubusercontent.com/4566555/54730240-33bd5080-4bcb-11e9-93ca-777c2a0e7483.png)
Then I got same error (401).

**Comment by tomconte** [comment]
I have a similar issues on a fresh installation on Ubuntu 18.04.

`func azure functionapp publish rslpyfunc`

Something seems wrong with retrieving the access token:

```
> az account get-access-token --query "accessToken" --output json
Request:
Method: GET, RequestUri: 'https://management.azure.com/subscriptions?api-version=2018-09-01', Version: 2.0, Content: <null>, Headers:
{
  Authorization: Bearer
  User-Agent: functions-core-tools/2.5.553
  Accept: application/json
  x-ms-request-id: a5732bbb-fddd-4138-b3ee-381af997a143
}

Response:
StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  WWW-Authenticate: Bearer authorization_uri="https://login.windows.net/", error="invalid_token", error_description="The authorization header is missing access token."
  x-ms-failure-cause: gateway
  x-ms-request-id: b8e7665b-df27-4ac3-8f1b-4abb788396b7
  x-ms-correlation-request-id: b8e7665b-df27-4ac3-8f1b-4abb788396b7
  x-ms-routing-request-id: UKSOUTH:20190405T111042Z:b8e7665b-df27-4ac3-8f1b-4abb788396b7
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Date: Fri, 05 Apr 2019 11:10:41 GMT
  Connection: close
  Content-Type: application/json; charset=utf-8
  Expires: -1
  Content-Length: 144
}
{"error":{"code":"AuthenticationFailedMissingToken","message":"Authentication failed. The 'Authorization' header is missing the access token."}}
```

Stack trace:

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 219
   at Azure.Functions.Cli.Helpers.AzureHelper.GetFunctionApp(String name, String accessToken) in C:\azure-functions-cli\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 23
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in C:\azure-functions-cli\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 116
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in C:\azure-functions-cli\src\Azure.Functions.Cli\ConsoleApp.cs:line 54
```

The DOCKER image seems fine in my case:

`"value": "DOCKER|mcr.microsoft.com/azure-functions/python:2.0"`

But I don't see how this can be related to the issue? It seems `func` has an issue retrieving the access token from `az` or something.

**Comment by tomconte** [comment]
I was able to work around the problem like this:

```
T=$(az account get-access-token | jq .accessToken)
func azure functionapp publish rslpyfunc --access-token $T
```

I think there is something wrong in the `GetAccessToken()` process.

**Comment by akshaybabloo** [comment]
This is happening to me too. I think python is freezing, but running `az account get-access-token` I am able to get the token though

**Comment by ferantivero** [comment]
@tomconte is for me the valid workaround because updating `az` CLI did not fixed it.

```
azure-cli                                 2.0.72
...
Python (Linux) 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

Azure Function Core Tools version `2.7.1575 Commit hash: b7750e771a4e56352c767dfa16413ec9c79b72ba`

**Comment by ahmedelnably** [comment]
Are you still seeing the issue with the latest version of the core tools and Az CLI?

**Comment by ferantivero** [comment]
@ahmedelnably my env is gone. I wont be able to answer this.
