### ISSUE TITLE
Create / update CLI command to include extension bundle as a part of zip deployment package

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-core-tools#1107]

**Comment by mattchenderson** [comment]
Note that this is critical for linux consumption publishing

**Comment by mattchenderson** [comment]
@ankitkumarr mentioned that this could create an issue for Python functions which will do the package creation as a separate step from publishing.

**Comment by soninaren** [comment]
@mattchenderson, @ankitkumarr  is the package creation step for python through CLI?

**Comment by soninaren** [comment]
closing this as it is not needed anymore.
