### ISSUE TITLE
python: autoreconf not available during build

### ISSUE THREAD

**Issue by peterthomassen** [Azure/azure-functions-core-tools#1111]
My `requirements.txt` contains `pyjq==2.3.1` which has to be compiled. I therefore added `--build-native-deps` to the `publish` command.

This results in:

    error: [Errno 2] No such file or directory: 'autoreconf': 'autoreconf'

... and the publish operation fails.

Adding `--no-bundler` does not help.

**Comment by ahmelsayed** [comment]
try adding `--additional-packages "dh-autoreconf "`
