### ISSUE TITLE
System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by malinru** [Azure/azure-functions-core-tools#1122]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`
```
------------------------F5 ->dotnet.exe-------------------------- 

Hosting environment: Production
Content root path: C:\Users\mastor\source\repos\FunctionApp01\FunctionApp01\bi
n\Debug\netstandard2.0
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[2019/03/13 9:24:44] Reading host configuration file 'C:\Users\mastor\source\r
epos\FunctionApp01\FunctionApp01\bin\Debug\netstandard2.0\host.json'
[2019/03/13 9:24:44] Host configuration file read:
[2019/03/13 9:24:44] {
[2019/03/13 9:24:44]   "logger": {
[2019/03/13 9:24:44]     "defaultLevel": "None"
[2019/03/13 9:24:44]   }
[2019/03/13 9:24:44] }
[2019/03/13 9:24:44] Starting Host (HostId=PC-175013438, InstanceId=28f
657ac-7b21-41fe-a7a6-6d0c267b765a, Version=2.0.11651.0, ProcessId=10992, AppDoma
inId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVers
ion=)
[2019/03/13 9:24:45] A ScriptHost error has occurred
[2019/03/13 9:24:45] System.Private.CoreLib: Could not load file or assembly 'Mi
crosoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, Publi
cKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception
from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assemb
ly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral,
 PublicKeyToken=adb9793829ddae60'.
[2019/03/13 9:24:45] Stopping Host
Function host is not running.
Press any to continue...

**Comment by degeb** [comment]
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by degeb** [comment]
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by degeb** [comment]
"<"Project Sdk="Microsoft.NET.Sdk"">"
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by degeb** [comment]
"<Project Sdk="Microsoft.NET.Sdk">
  "<PropertyGroup>
    "<TargetFramework>netstandard2.0</TargetFramework>
    "<AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by degeb** [comment]
<code>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
</code>

**Comment by degeb** [comment]
```
'<'Project Sdk="Microsoft.NET.Sdk"'>'
  '<'PropertyGroup'>'
    '<'TargetFramework'>'netstandard2.0'<'/TargetFramework'>'
    '<'AzureFunctionsVersion'>'v2'<'/AzureFunctionsVersion'>'
  '<'/PropertyGroup'>'
  '<'ItemGroup'>'
    '<'PackageReference Include="CsvHelper" Version="12.1.2" /'>'
    '<'PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" /'>'
    '<'PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" /'>'
    '<'PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" /'>'
    '<'PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" /'>'
    '<'PackageReference Include="System.Data.SqlClient" Version="4.6.0" /'>'
  '<'/ItemGroup'>'
  '<'ItemGroup'>'
    '<'None Update="host.json"'>'
      '<'CopyToOutputDirectory'>'PreserveNewest'<'/CopyToOutputDirectory'>'
    '<'/None'>'
    '<'None Update="local.settings.json"'>'
      '<'CopyToOutputDirectory'>'PreserveNewest'<'/CopyToOutputDirectory'>'
      '<'CopyToPublishDirectory'>'Never'<'/CopyToPublishDirectory'>'
    '<'/None'>'
  '<'/ItemGroup'>'
'<'/Project'>'
```

**Comment by degeb** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="12.1.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by ahmedelnably** [comment]
Closing as stale, please upgrade to the new version and open a new issue if the error persists
