### ISSUE TITLE
Error while publishing azure python function app

### ISSUE THREAD

**Issue by shashank-lothe** [Azure/azure-functions-core-tools#1123]
Hi,

I am publishing my functionapp using this command:
func azure functionapp publish MyTechmFunctionApp --build-native-deps --no-bundler --force

I am getting following error while publishing:
Error running docker exec -t 3efd52d7016a63aee7784bb7249f3460caa245e8e0bc0ba90ee625783d21ccbb /python_docker_build.sh.
output: Collecting azure-functions==1.0.0b3 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f332c3ac8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-functions/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f332c3e48>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-functions/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f332c39e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-functions/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f332c3ba8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-functions/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1f332d52e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-functions/
  Could not find a version that satisfies the requirement azure-functions==1.0.0b3 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for azure-functions==1.0.0b3 (from -r requirements.txt (line 1))

Though I am getting above error, the function is still getting published but It is not responding to http/blob trigger. What could be the problem?

Thanks and regards,
Shashank

**Comment by ahmedelnably** [comment]
We have added support for remote build, please upgrade to the latest version and open a new issue if the error persists
