### ISSUE TITLE
Error calling sync triggers (BadRequest). Python runtime on Linux 

### ISSUE THREAD

**Issue by panakouris** [Azure/azure-functions-core-tools#1130]
Our deployed function apps stopped working. Deployment is not possible as during the publishing of the app I get the following error:

```
Preparing archive...
Uploading 76.08 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). 
```

We had the same issues a month ago and it's also posted in issue #996. The selected region for our app is eastus. Worth mentioning that deployment in westeurope is working at the moment.

**Comment by bigdatamoore** [comment]
We are having the same issue today as well.  Westus deployments are working Eastus are not working.

**Comment by craigeddy** [comment]
Same issue here. I've seen others mention "switching to an AppService plan" fixes things, but I'm not sure how to do so

**Comment by balag0** [comment]
We are currently having an issue in East US. 
West US and West Europe are mitigated and should be back to normal now.
We expect to have East US back up soon. Until then please use any of the other regions to deploy your app.

@craigeddy  Here is some info on the AppService plan option - https://blogs.msdn.microsoft.com/appserviceteam/2017/11/15/functions-on-linux-preview/
This is a completely different sku and you might have to change how you deploy code.
I would recommend you try any of the other regions if possible until we resolve the issue in East US.

**Comment by ericdrobinson** [comment]
>I would recommend you try any of the other regions if possible until we resolve the issue in East US.

Is this something we can change easily in the dashboard or does it require setting up an all new app?

**Comment by JK87iab** [comment]
Getting the same error today. Deploying West europe.
`Error calling sync triggers (BadRequest).
`

**Comment by tomconte** [comment]
Same error right now. West Europe.

**Comment by bigdatamoore** [comment]
It;s working in eastus at the moment, but now it is failing in westus.  Here's the error:

```
Preparing archive...

Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
func : Error calling sync triggers (BadRequest).
At line:1 char:1
+ func azure functionapp publish dsmlrecommender-dev-westus-functions - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error calling s...s (BadRequest).:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by balag0** [comment]
@bigdatamoore We are working on mitigating the issue in West US and should be back up soon.
West Europe has already been mitigated.
Please use any of the other regions until this is resolved.

**Comment by j08lue** [comment]
@balag0 Any idea on when these failures we have been experiencing for months will stop? And please don't just say "when Python Functions for Linux goes GA". 😉

**Comment by balag0** [comment]
The issue in West US is mitigated now. Please try again and let us know if you are still seeing issues.

**Comment by balag0** [comment]
@j08lue We apologize for the recurring issues. The underlying platform used to host Linux Python Functions is also under preview and still maturing. We are continuously working on improving both the hosting platform and Linux Azure Functions.

**Comment by JK87iab** [comment]
Same issue in West europe right now

**Comment by huier23** [comment]
I have this issue in East Asia.

Preparing archive...
Uploading 63.08 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Response status code does not indicate success: 400 (Bad Request).

**Comment by eppe2000** [comment]
I have the same issue in the West Europe region.

```
Uploading 107.69 MB [#############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest).
```

**Comment by contraPat** [comment]
Same issue here :

Preparing archive...
Uploading 56.07 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest).`

**Comment by contraPat** [comment]
> Same issue here :
> 
> Preparing archive...
> Uploading 56.07 MB [##############################################################################]
> Upload completed successfully.
> Deployment completed successfully.
> Syncing triggers...
> Syncing triggers...
> Syncing triggers...
> Syncing triggers...
> Syncing triggers...
> Syncing triggers...
> Error calling sync triggers (BadRequest).`

I deleted my app and created it in a new region (was West Europe and now is US East) and the deployment was successful... this might not work next time the 'issue' affects a different region as it seems to be travelling around... to keep deleting a recreating apps until a deployment goes through is not the solution ...

**Comment by wasuaje** [comment]
Same Error in west west europe now
Preparing archive...
Uploading 74.56 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest).

**Comment by balag0** [comment]
West Europe should also be mitigated now.

**Comment by crgarcia12** [comment]
Same error in western Europe

 func azure functionapp publish worker-functions-eu-app --build-native-deps
Getting site publishing info...
Running 'docker pull mcr.microsoft.com/azure-functions/python:2.0.12309'............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done
Running 'docker run --rm -d mcr.microsoft.com/azure-functions/python:2.0.12309'...done
Running 'docker exec -t e706d6 mkdir -p /home/site/wwwroot/'..done
Running 'docker cp "C:\Users\crgar\AppData\Local\Temp\u1uwssk3.xjw/." e706d6:"/home/site/wwwroot"'...done
Running 'docker cp "C:\Users\crgar\AppData\Local\Temp\tmpFF8.tmp" e706d6:"python_docker_build.sh"'..done
Running 'docker cp "C:\Users\crgar\AppData\Local\Temp\tmp1037.tmp" e706d6:"python_bundle_script.py"'..done
Running 'docker exec -t e706d6 chmod +x /python_docker_build.sh'..done
Running 'docker exec -t e706d6 chmod +x /python_bundle_script.py'..done
Running 'docker exec -t e706d6 /python_docker_build.sh'......................................................................................................................................................done
Running 'docker cp e706d6:/app.zip C:\Users\crgar\AppData\Local\Temp\immyajh0.10n'...done
Running 'docker kill e706d6'...done
Preparing archive...
Uploading 62.99 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Response status code does not indicate success: 400 (Bad Request).

**Comment by eppe2000** [comment]
> West Europe should also be mitigated now.

It seems to work for me now.

**Comment by wasuaje** [comment]
Still Having issues in west Europe!!!!!

Preparing archive...
Uploading 74.56 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest).

**Comment by wasuaje** [comment]
The issue persists
In West Europe
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest).

**Comment by wasuaje** [comment]
The issue persists
In West Europe
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest).

Fixing this anytime soon?

**Comment by balag0** [comment]
Please open a new issue and provide details on your site and approx timestamp.

**Comment by balag0** [comment]
Locking this thread since the original issue was resolved and it is difficult to track multiple different issues with the same thread.
Please open a new issue if you are still seeing issues. 

There is also some improvement needed here since different types of issues manifest as same error on the client side. With a more descriptive errors it would be easy to differentiate between different class of issues/bugs.
Tracked as https://github.com/Azure/Azure-Functions/issues/1170

Thanks
