### ISSUE TITLE
Expose template files and content as a command

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-core-tools#1134]
This allows other tools to resolve information from a bundle without rewriting this logic.

**Comment by soninaren** [comment]
@ankitkumarr assigning this one to you. We need a command to exposed the templates that we get from extension bundle to external tools. You can leverage the `ExtensionBundleContentProvider` used in the PR.
https://github.com/Azure/azure-functions-core-tools/pull/1193

**Comment by soninaren** [comment]
Going to close this one as it is not needed anymore.
