### ISSUE TITLE
Failure to install cryptography wheels for Python 3.6

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1150]
Since the Azure SDK takes a dependency on Cryptography which is a native package, publishing a Python Function App fails asking the user to publish using `--build-native-deps`. 

This shouldn't be the case since Cryptography does provide version 3.6 compatible wheels, see here - https://github.com/pyca/cryptography/issues/4382

/cc @maiqbal11 @elprans

**Comment by ankitkumarr** [comment]
@asavaritayal, I looked into this. Cryptography provides whl for python 34 abi3.  Looks like we do something similar to `pip download --platform manylinux1_x86_64 --python-version 36 --abi cp36m`. There's two issues here-

1. `pip download` seems to specifically look for `36` version file even though the `34` file seems to be supported for 3.4+.
2. I don't know much about Python abis. According to https://github.com/pypa/pip/issues/6070`, `abi3` is compatible `cp36m`, but pip does not know so.

We can get around 2 by doing `pip download` twice with `--abi abi3` and `--abi cp<version>m`. But, I am not sure if we can do anything about 1. Given that we need to specify the python version and I don't think there's a way of knowing in advance which version file (`34` here) we need to download.

**Comment by asavaritayal** [comment]
Adding @zooba and @1st1 to see if they have a recommendation on this one.

**Comment by zooba** [comment]
Nope, this looks like a pip limitation that requires their issue 6070 to be fixed. I just experimented with a few variations and none will choose the cryptography wheel unless you specify `--python-version 34`.

I don't have a recommendation right now other than to engage the projects and see what help we can provide. I'll ping both of them.

As a workaround, you could do this (tested separately but these commands need checking):
```
pip download --platform manylinux1_x86_64 --python-version 34 --abi abi3 cryptography --dest wheelhouse
mv wheelhouse/cryptography-2.6.1-cp34-abi3-manylinux1_x86_64.whl wheelhouse/cryptography-2.6.1-cp36.cp37-abi3.cp36m.cp37m-manylinux1_x86_64.whl
pip download --platform manylinux1_x86_64 --python-version 36 --abi cp36m --find-links wheelhouse -r requirements.txt
```

Renaming the cryptography wheel to include the ABI that you're going to download for in the name (dot separators let you specify multiple compatible versions) and using --find-links will avoid trying to download it again, though it will copy the wheel from `wheelhouse` to wherever the output of the second command is going.

**Comment by ankitkumarr** [comment]
Thanks @zooba for the workaround and pinging the projects.

This issue comes up when we try and download wheels from user's `requirements.txt`. Even with that workaround, we would have to specify  `--python-version 34`. The problem is- we would not know which version to specify for a given package from `requirements.txt` as I assume this problem is not exclusive to `cryptography`.

Unless, you are aware of a way to figure out which wheel version would satisfy a given python version. So, figuring out that we need `cp34` wheel for cryptography if we want to download the wheel for version `36`?

**Comment by zooba** [comment]
Nope, no way to figure that out. Which is why I said a temporary workaround is to special case cryptography (and presumably any others that we hear about).

**Comment by ahmedelnably** [comment]
Blocked on pip getting updated

**Comment by kshyju** [comment]
@vrdmr Is this still a valid issue? Can you advice what the action item here should be?
