### ISSUE TITLE
Linux: Unable to access <app>.scm.azurewebsites.net, Service Unavailable

### ISSUE THREAD

**Issue by ElanHasson** [Azure/azure-functions-core-tools#1173]
The same happened to me. I also deleted and redeployed apps with the same name multiple times.

I just created a new linux/consumption function app and got the following while attempting to deploy from VS2019:
The attempt to publish the ZIP file through https://bddev.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code ServiceUnavailable.

I created the function app via the publish wizard. 

The same happened when I created a Linux/consumption function app via the Azure Portal directly. Azure Support was able to reproduce (see SR # 119040321001449) and directed me to make an issue here.

Note: I initially commented on https://github.com/projectkudu/kudu/issues/2804.

**Comment by balag0** [comment]
I see the app was created with an explicit server farm. For (linux) consumption apps the serverfarm should have been empty when created through the portal. 

There shouldn't have been an option to specify a server farm / app service plan in the portal. Are you seeing something else when you create a consumption linux function app using the portal?

![image](https://user-images.githubusercontent.com/28721598/55520124-b4e6ff80-562f-11e9-9eb7-145bafedbde1.png)

**Comment by ElanHasson** [comment]
Mine looks like yours in the portal.

You may be looking at the one created from Visual studio publish tool. I made a few :)

**Comment by balag0** [comment]
Thanks. I am looking at the site named bddev. If you were creating a linux consumption function app (based on the screenshot) those sites do not have scm sites (and do not support zip deploy)
Only way to deploy to linux consumption apps is using Run-From-Package. Instructions here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux#deploy-the-function-app-project-to-azure

I can see the documentation is not clear about this. I opened an issue to fix the docs. - https://github.com/MicrosoftDocs/azure-docs/issues/28809

For the site bddev , the site create request included an explicit app service plan. For consumption apps this property should have been empty and this is what i am seeing too when i tried to create a site from the portal. In fact from the above screen shot you can see there is no option to even select an app service plan. so i am trying to understand what was different in your create workflow to see if there is may be a bug somewhere.

**Comment by ElanHasson** [comment]
I'm a bit confused-- making a linux function app from VS2019 results in the same issue.
When you goto the portal and click on the Function app settings link, do you get errors?
![image](https://user-images.githubusercontent.com/234704/55602034-a54fdf80-5731-11e9-820b-316ec666495b.png)

**Comment by ElanHasson** [comment]
As for the Run as Package, are you referring to https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package ? 

I'll give it a shot.

**Comment by balag0** [comment]
@ElanHasson I am not seeing any errors with the apps i tested with earlier. for this particular app, some how the app has gotten into an inconsistent state which i couldn't repro myself, hence my earlier questions on your create flow :) 
I would expect this app to be broken since it is in an inconsistent state. Are you seeing this consistent across different apps? Also could you try choosing a different region to see if that make a difference.

Yes, that is the high level description of how Run-From-Package works.

You can use Functions core tools ( https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli-linux#deploy-the-function-app-project-to-azure) or 
VS code ( https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code ) to publish the app.

Both the tools also support creating new function apps. Let us know if you have any other questions.

**Comment by ElanHasson** [comment]
Thanks-- I tried in US East and wasn't even able to do so. You can see the JSON response from the request in the SR ticket.

I'll try again later this weekend.

The folks at Azure Support were able to reproduce.

**Comment by balag0** [comment]
I was able to locate the bug and the fix should be deployed with the next release. Let me know if you are having trouble deploying with functions core tools / vs code.

**Comment by ElanHasson** [comment]
Thanks. When is the next release?

**Comment by balag0** [comment]
It should be complete in another week. I will update this thread once it is complete.
Were you able to use Run-From-Package to deploy?

**Comment by fabiocav** [comment]
Closing this as resolved. Please let us know if you continue to see this issue.
