### ISSUE TITLE
Provide a way for Kubernetes users to associate secrets to functions using environment variables or volume mount

### ISSUE THREAD

**Issue by markito** [Azure/azure-functions-core-tools#1178]
As a user I'd like to map my environment variable in the function to a Kubernetes secrets so that sensitive information is not baked into the container image or is hardcoded into the function code.   

This issue expands on https://github.com/Azure/azure-functions-core-tools/issues/751.

**Comment by markito** [comment]
Environment:
Kubernetes 1.12
minikube version: v1.0.0
func version 2.5.553

**Comment by SpicySyntax** [comment]
+1 this would be very useful
