### ISSUE TITLE
Functions whitelist gets confused by multiple functions in one class

### ISSUE THREAD

**Issue by tdwright** [Azure/azure-functions-core-tools#1183]
A pattern we use for timer-triggered functions it to also provide a HTTP-triggered entry point. We tend to make both entry points pretty lightweight and point to a common private method that contains the business logic.

Since both these entry points are in the same class, the functions host seems to get a bit confused if we whitelist only the triggered version.

One minor symptom of this is that the startup sequence will declare `N functions loaded` and then `Generating N job function(s)`, but will then print `Found the following functions:` followed by _N+1_ function names. This symptom appears to occur regardless of the types of functions that are whitelisted or not - all that matters is that they are both contained in the same class.

A more problematic symptom rears its head when a timer-triggered function is present in a class alongside a whitelisted HTTP-triggered function. When the timer-triggered function _would_ have fired, we instead see errors about uninitialised immutable arrays in code belonging to the functions runtime. (Speficially the `GetMetadataFromCollection` method in `FunctionsInstanceLogger.cs`)

> System.Collections.Immutable: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.

Whitelisting the timer-triggered function eliminates this error. So does removing any of it's class-mates from the whitelist.

Not a massive problem given that whitelisting isn't a feature designed to be used in prod environments, but it does make debugging that little bit more frustrating.

**Comment by m1nkeh** [comment]
yep, same here!

**Comment by mathewc** [comment]
Do you have a simple repro you can share with us that demonstrates the problem? E.g. a small repo you can point us to with a set of functions that show the issue.

**Comment by edag94** [comment]
I was seeing these same symptoms in my project, without using the whitelisting feature. The issue was due to forgetting the [FunctionName(nameof(MyActivity))] attribute on top of the Activity function. This may not solve the issue you are facing, but it would be worth validating that you aren't missing any FunctionName attributes on your functions

**Comment by rasmuschristensen** [comment]
Same here, ServiceBusTrigger and a HttpTrigger in the same class, causes the issue

**Comment by ahmedelnably** [comment]
Closing this, if you have a repro that we can test with please reopen the issue
