### ISSUE TITLE
Do not ignore appsettings.json

### ISSUE THREAD

**Issue by ielcoro** [Azure/azure-functions-core-tools#1185]
Sinces this commit (https://github.com/Azure/azure-functions-core-tools/commit/14e394dc8d1b9ee9ca93a27fab420c9ad49ee41f) azure functions core tools is excluding "appsettings.json" from published output, for example, when publishing via func azure functionapp publish. Cause it only ignores this file on publish, the issue did not reproduce locally, and all of our tests failed to catch it until we hit production.

Why we use appsettings.json? Well, because of reasons. We know Azure Functions promotes the usage of App Service Settings, however we have apps migrated from ASP.NET Core applications to functions runtime, and to ease those migrations, we setup a configuration class on function startup and read the settings from there, we even handle per-environment settings like in ASP.NET Core with environment suffixes (appsettings.production.json, appsettings.staging.json...).

Also ignoring only appsettings.json is half-baked,as any other file pattern like (appsettings.production.json) surpases the filter and deploys to production, resulting in a half configured system.

 So we please please request to remove "appsettings.json" from the filter in FileSystemHelpers.GetLocalFiles, or at least to make it overridable via gitignore patterns:

https://github.com/Azure/azure-functions-core-tools/blob/f956b3c0b7c51032988e412c973559dbf71463b3/src/Azure.Functions.Cli/Common/FileSystemHelpers.cs#L120

**Comment by ahmelsayed** [comment]
> Cause it only ignores this file on publish, the issue did not reproduce locally, and all of our tests failed to catch it until we hit production.

> Also ignoring only appsettings.json is half-baked,as any other file pattern like (appsettings.production.json) surpases the filter and deploys to production, resulting in a half configured system.

Sorry about that. And that's true, though I actually think the `appsettings.json` in that list was what `local.settings.json` used to be called before I renamed it to avoid ASP.NET config files confusion.

**Comment by ahmelsayed** [comment]
Closed by @ielcoro in https://github.com/Azure/azure-functions-core-tools/pull/1186
