### ISSUE TITLE
[Python] requirements.txt empty on new projects

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-core-tools#1194]
_originally filed by @jeffhollan in https://github.com/Microsoft/vscode-azurefunctions/issues/1178_

Realize this may be on another repo or the template feed - tried to poke around and couldn't figure out where it's pulled from, but today the project template for python results in a `requirements.txt` file that is empty.  This seems a bit strange to me as the project has `import azure.functions as func` which my VS Code instance can't give me nice intellisense for unless I have `azure-functions` as one of the pip packages to install.

Seems we should have the default project template include `azure-functions` as a single package to import by default.

**Comment by ankitkumarr** [comment]
We recently made a change to tie `azure-functions` (pip package) with `azure-functions-core-tools`. So, it is expected that the users will get a blank `requirements.txt`. 

Having `azure-functions` in `requirements.txt` may result in users installing that package when they don't need to. @jeffhollan, would you suggest that we have users install `azure-functions` just for intellisense? 

This may be overkilling, but @EricJizbaMSFT, is it possible to create a project level `PYTHONPATH` for each Python app, where we add to that variable the location of the `azure-functions` inside the installed `azure-functions-core-tools`? I think that should enable intellisense.

**Comment by jeffhollan** [comment]
I’m not sure. For me personally it helps as I don’t know all the API surface for the function library. But fine if we wait and get feedback before we include it always. It would be nice if there was a way to get the autocomplete still.

**Comment by ankitkumarr** [comment]
I am with you that we definitely want features like auto-completion. I think we overlooked this part when we decided to bind the worker. Thank you for bringing this up. I will take a look at what we can do.

**Comment by asavaritayal** [comment]
/cc @maiqbal11 

Want to echo the above that we absolutely want to have auto-complete and intellisense enabled for the user from the very beginning. We've received enough feedback to prove that this is valuable. 

> This may be overkilling, but @EricJizbaMSFT, is it possible to create a project level PYTHONPATH for each Python app, where we add to that variable the location of the azure-functions inside the installed azure-functions-core-tools? I think that should enable intellisense.

@ankitkumarr why do we need a project level PYTHON_PATH for this? Trying to understand if we can just use the current PYTHON_PATH whether it points to global python or a venv.

**Comment by maiqbal11** [comment]
If you inspect the `sys.path` for the Python functions run via core-tools, you'll see that there is a reference to a `deps` folder where the the `azure-functions` package is located. Does VSCode pull its intellisense info from the same path locations as the running Python function or from others configured statically?

**Comment by ankitkumarr** [comment]
When you do `func host start`, core-tools adds the `deps` folder (which contains the `azure-functions` dependencies) to the PYTHONPATH only for the time it runs. So, anytime when `func host start` is not running, VS Code probably has no knowledge of where `azure-functions` is located. 

I was wondering if VS Code can update user's PYTHONPATH environment variable as well, making the detection of `deps/azure-functions` possible.

**Comment by anirudhgarg** [comment]
@asavaritayal to follow up with VS Code to see if they can add this path their environment variable so that the intellisense will work.
