### ISSUE TITLE
func init AzureFunctionsVersion

### ISSUE THREAD

**Issue by dszyrowski** [Azure/azure-functions-core-tools#1198]
Sorry if there is an existing issue open for this, I thought I saw one previously but now I can't find it. 

I am new to function apps and when creating a new .net app with "func init" I am having some issues with the AzureFunctionsVersion being left blank. Is there any way to specify V2 in my fun init command?

**Comment by ahmedelnably** [comment]
If you are using v2.x of the tools, the tools will create a v2 function when you do func init

**Comment by dszyrowski** [comment]
When I run func -version I get this:
2.5.553

But when I run func init my .csproj file looks like this:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion></AzureFunctionsVersion>
    <RootNamespace>function_test</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`
