### ISSUE TITLE
Publishing App sometimes results in 400 error

### ISSUE THREAD

**Issue by ccwilkins** [Azure/azure-functions-core-tools#1204]
Using the latest core tools (2.5.553) when deploying my app I sometimes get the following error:

```
Method: GET, RequestUri: 'https://management.azure.com/subscriptions/{removedForPrivacy}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/sites/{appName}/hostruntime/admin/functions?api-version=2015-08-01',
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent
{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}
```

If I try deploying again it works fine. The issue is sporadic. All of the POST, PUT calls above this call are successful.

Node App
Using App Service Plan

**Comment by ahmedelnably** [comment]
Can you please provide your app name, and a time frame so we can investigate that more
If you don't want to share your function name publicly please use the following steps: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by ccwilkins** [comment]
Id=5d033d7c-fb4b-40f2-a3c0-fcc86d339c79
2019-04-17 01:10:37.511
US-East-2

Time the application had problems deploying was April 16 around 4:30 pm EST.

**Comment by ccwilkins** [comment]
Just wanted to check in about this as it is plaguing/breaking our deployments. Any help here would be much appreciated. Please let me know if you need any additional information.

**Comment by ccwilkins** [comment]
Please note this is still happening using the latest toolset: 2.7.1158

**Comment by ahmelsayed** [comment]
sorry for the delay in getting to this. @ccwilkins are you still seeing this? if so, can you share similar invocation ID you have above but for a recent invocation?
