### ISSUE TITLE
Developing functions locally using bindings pointing to the Cosmos Emulator

### ISSUE THREAD

**Issue by khowling** [Azure/azure-functions-core-tools#1209]
I'd like a off-line functions developer experience using bindings against the cosmos emulator.  but getting a error when executing the function: 

System.Private.CoreLib: Exception while executing function: Functions.orders. System.Net.Http: The SSL connection could not be established, see inner exception. System.Private.CoreLib: The remote certificate is invalid according to the validation procedure.

Is this supported? if so, how do I fix the error

Thanks for any help

**Comment by ahmedelnably** [comment]
Please use the following doc to know how to export the certificate to use with Cosmos DB emulator

https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator-export-ssl-certificates#how-to-export-the-azure-cosmos-db-ssl-certificate

**Comment by khowling** [comment]
Thanks @ahmedelnably , I've exported the cert into a file as per your link, what do I do now?
