### ISSUE TITLE
Auto-resolve Python versions when running locally

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1229]
**Scenario**

1. If a user has multiple versions of Python in their local environment, each version is referenced by a different path. e.g. `/usr/local/bin/python` resolves to version 2 and `/usr/local/bin/python3` resolves to version 3. 

2. If a single version is present, the default path refers to that version. e.g. `/usr/local/bin/python` will resolve to version 3.

Core Tools should identify which path version 3.6 is present on and set it up accordingly to be used with the runtime. 

**Scratch**

Per the wiki here - https://github.com/Azure/azure-functions-host/wiki/Authoring-&-Testing-Language-Extensions, we should be able to use the `languageWorkers:python:defaultExecutablePath` environment variable to declare the correct alias.

On `func init`, and `func host start` the following workflow must apply: 

1. If `python3 --version == python3.6.*`
        use python3
2. Elif `python --version == python3.6.*`
        use python
3. Else throw an error

**Comment by ankitkumarr** [comment]
While we implement and release this, a workaround is to manually create and set this environment variable `languageWorkers:python:defaultExecutablePath` to `python3`.
