### ISSUE TITLE
Different color for custom logs from Function 

### ISSUE THREAD

**Issue by yochay** [Azure/azure-functions-core-tools#125]
Find a way to differentiate between custom log (from my code as user) vs. the logs from the host. Either provided color coding or flag to control which logs i see

unction started (Id=7b9f8399-5795-40c1-b5ca-67a5380b53df)
JavaScript HTTP trigger function processed a request.
Function completed (Success, Id=7b9f8399-5795-40c1-b5ca-67a5380b53df)
Executed 'Functions.TriggerFunc' (Succeeded, Id=7b9f8399-5795-40c1-b5ca-67a5380b53df)
Executing 'Functions.Func1' (Reason='New queue message detected on 'funcchainoutqueue1'.', Id=3b3cb064-1109-44b8-980c-dd9d86e62deb)
Function started (Id=3b3cb064-1109-44b8-980c-dd9d86e62deb)
**JavaScript Func 1 received --> Q Item =  { input: '42' }**
Function completed (Success, Id=3b3cb064-1109-44b8-980c-dd9d86e62deb)
Executed 'Functions.Func1' (Succeeded, Id=3b3cb064-1109-44b8-980c-dd9d86e62deb)
Executing 'Functions.Func2' (Reason='New queue message detected on 'funcchainoutqueue2'.', Id=7c884db0-6ac2-4797-b5e2-f2ad88e9f4c2)
Function started (Id=7c884db0-6ac2-4797-b5e2-f2ad88e9f4c2)
**JavaScript Func 2 received --> Q Item =  { input: '42', func1: 'new string from Function 1' }**
Function completed (Success, Id=7c884db0-6ac2-4797-b5e2-f2ad88e9f4c2)
Executed 'Functions.Func2' (Succeeded, Id=7c884db0-6ac2-4797-b5e2-f2ad88e9f4c2)
Executing 'Functions.Func3' (Reason='New queue message detected on 'funcchainoutqueue3'.', Id=16833e2a-ab17-4778-9dbd-51b90140c990)
Function started (Id=16833e2a-ab17-4778-9dbd-51b90140c990)
**JavaScript Func 3 received --> Q Item =  { input: '42',
  func1: 'new string from Function 1',
  func2: 'new string from Function 2' }
JavaScript Func 3 completed  { input: '42',
  func1: 'new string from Function 1',
  func2: 'new string from Function 2',
  func3: 'new string from Function 3' }**
Function completed (Success, Id=16833e2a-ab17-4778-9dbd-51b90140c990)
Executed 'Functions.Func3' (Succeeded, Id=16833e2a-ab17-4778-9dbd-51b90140c990)

**Comment by lindydonna** [comment]
The best way to solve this would be with a custom ILogger implementation. Moving to backlog for now

**Comment by wpitallo** [comment]
And for JavaScript?

**Comment by ahmedelnably** [comment]
This is highly unlikely to be done, logs comes from the host.
