### ISSUE TITLE
Generate a MSI installer for Windows

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-core-tools#1250]

**Comment by ahmedelnably** [comment]
Changing to P1, as we need to do this by EOY

**Comment by ahmedelnably** [comment]
This should only support v3 of the tools

**Comment by fabiocav** [comment]
@dariagrigoriu moving this to sprint 68, but still aiming to have this done by EOM

**Comment by fabiocav** [comment]
Targeting first half of sprint 70. 

@dariagrigoriu @anthonychu we can share what exists now for validation while the last remaining issues are addressed.

**Comment by kashimiz** [comment]
Addressed by #1846.

**Comment by pragnagopa** [comment]
Closing as completed.
