### ISSUE TITLE
Status: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-functions-core-tools#1255]
I have a python function app that takes in documents like excel spreadsheets or csv data coded in base64 as a part of the body in a POST call to the function app. Works great in VS Code, but once deployed to Azure I get the error (Status: 413 Request Entity Too Large) for a simple 300kb test case with following additional info:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Payload Too Large</pre>
</body>
</html>

Is there a parameter that I can set somewhere to change this limit to allow larger payloads?
Thanks,
Greg

**Comment by ahmedelnably** [comment]
Being tracked in an internal thread

The UI may have different limits on payload size. 
Please use curl or some other http client if you want to post large content

**Comment by docgregt** [comment]
Hi,
Thanks, I found out from MS support that the payload size is limited in the UI pretty much making the UI useless. We verified using Postman that it works fine. You can close this post.

Gregory Turner
Chief Architect
________________________________________
i4 Insight, Inc.

cell: +1.720.335.1744
greg.turner@i4-insight.com<mailto:greg.turner@i4-insight.com>

A member of the Lloyd’s Register Group
