### ISSUE TITLE
[Python] Publish as a SquashFS package

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1264]
/cc @ahmelsayed 

Starting an issue to track the Core Tools update required to support SquashFS.

**Comment by asavaritayal** [comment]
@anirudhgarg @fabiocav  This needs to be incorporated into the server-side build as well.

**Comment by ahmelsayed** [comment]
closed in 5c49d669ebe8eed66cd933bf0a5b9d6a9530a100 and cd9bfca26f9c7fe06ce245f5bf69bc6486a685dd
