### ISSUE TITLE
func azure functionapp publish or func pack fails if...

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1277]
... `python` points to python 2.7. This is because we run `python packapp`. We should be running `python3` on cases where `python` refers to 2.7. Or, we should make packapp Python 2.7 compatible.

@asavaritayal, fyi!

**Comment by ahmelsayed** [comment]
yeah I saw that too. It's not a regression since it's a scenario that never worked before in the first place, but it would be nice to resolve python in that scenario as well or display a better error message
