### ISSUE TITLE
Warn on publish to linux if custom container is setup

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1278]
Had a CRI today where a user was trying to do a func publish for a Python app, but they'd configured their app to run on a custom container.  The CLI didn't error and likely did publish the bits, but the app never honored them as it had a custom container set.  Ideally the CLI could warn or even block this and say something like "This app is configured to run from custom container.  To update the app, you need to update the container image and push it to the registry." or something

**Comment by ahmelsayed** [comment]
If you're using a custom image the cli should print out this message 

https://github.com/Azure/azure-functions-core-tools/blob/cfde63b40651ad7c49f7368d62a90fa5c8f24b89/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L237-L240


Did it not print that for them? do you have their publish output logs?

**Comment by ahmedelnably** [comment]
@jeffhollan ping :)
