### ISSUE TITLE
Allow a way to append metadata with scaler thresholds

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1293]
For example if I have a queue triggered function and want to do `func kubernetes deploy` ideally some way to set the `queueLength` metadata in the scaledobject that will drive scale.  Maybe a `--set metadata.queueLength=40` or something?

**Comment by ahmelsayed** [comment]
if you set it in your function.json like this it'll work:

```json
{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "js-queue-items",
      "connection": "",
      "queueLength": "40"
    }
  ]
}
```

But it's probably not ideal because it's not really meaningful for most scenarios, right?

**Comment by jeffhollan** [comment]
I think that is fine for now actually. We could improve in future but at least it’s feasible and documentable
