### ISSUE TITLE
func settings add FUNCTIONS_WORKER_RUNTIME results in base64 value in local.settings.json

### ISSUE THREAD

**Issue by cravecode** [Azure/azure-functions-core-tools#1296]
When running my Function 2.x via Visual Studio 2017 debugger, I get the following error:
```
your worker runtime is not set. As of 2.0.1-beta.26 a worker runtime setting is required.
Please run `func settings add FUNCTIONS_WORKER_RUNTIME <option>` or add FUNCTIONS_WORKER_RUNTIME to your local.settings.json
Available options: dotnet, node, python, powershell

Azure Functions Core Tools (2.6.1080 Commit hash: 509d59b7eb6fbfb89f70ce96ad22e00f8f7bafdd)
Function Runtime Version: 2.0.12427.0
``` 
![func-error](https://user-images.githubusercontent.com/169682/57421021-1b83ae00-71d8-11e9-96a5-745b81b665d2.PNG)

My `local.settings.json`
contains:
```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    ...
  }
}
```

After running `func settings add FUNCTIONS_WORKER_RUNTIME dotnet`, my `local.settings.json` file is updated with:
```
{
  "IsEncrypted": true,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "CfDJ8ErM1zH5dZNPtUsIMwXbKMwZDVJWS0k7o3UXKKV4VU9WDr22is1ZMFb0RTAmDuvRyD3fCMqwDf+yVminS003xDa3BYASIYtDHrJy6NpE3T11PlRDLNvK7SvUQbu7FJeoHA==",
    ...
  },
  "ConnectionStrings": {}
}
```

I had to do the same thing for `"AzureWebJobsStorage":  "UseDevelopmentStorage=true"` which also resulted in a base64 value. 

These Base64 values are the only way I can get the settings to be recognized when running the function locally, not a simple string value. Why does this require a Base64 value?

**Comment by bgelens** [comment]
change `IsEncrypted` to `false` and use the ide to add / change values

**Comment by cravecode** [comment]
@bgelens thanks for the quick response!
That's what I originally did but the config wasn't being applied as I was getting the `your worker runtime is not set` message.

**Comment by bgelens** [comment]
hmm, I have not experienced this. Once you set IsEncrypted to false, did you also update the `FUNCTIONS_WORKER_RUNTIME` back to plain text `dotnet`?

**Comment by cravecode** [comment]
I created a new project and couldn't reproduce the issue in the new project. I'm not sure what was going but it appears to be specific to my environment.
