### ISSUE TITLE
Logging written to the ILogger does not appear in the CLI

### ISSUE THREAD

**Issue by channeladam** [Azure/azure-functions-core-tools#130]
Logging written to the ILogger does not appear in the CLI

**Comment by justinyoo** [comment]
Seems that it's still not fixed. Guess this pass `null`, instead of `ILogger` instance.

https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Helpers/ScriptHostHelpers.cs#L24

@lindydonna Would you mind providing a rough timeline for this?

**Comment by pauldalyii** [comment]
I am running 1.0.2 and am still not seeing logs written to the CLI.   Is this working for others yet?  I'm running VS 15.3.1.

**Comment by SteveALee** [comment]
Just in case it is at all related I regularly find the logging on Azure just stops, requiring a restart. I'm using javascript.

**Comment by alabaki** [comment]
Any news on this issue?

**Comment by brentnewbury** [comment]
I'm getting a similar issue, no log entries for `Microsoft.Extensions.Logging.ILogger` are being output to the CLI nor the Portal.

**Comment by slawlor** [comment]
Also experiencing this issue recently. I've been forced to revert to the TraceWriter until it's fixed

**Comment by hoshauch** [comment]
We have the same problem, no log are shown in the azure-portal.

**Comment by MrGlenThomas** [comment]
I am using CLI 1.0.9 and it still does not work.

**Comment by roryprimrose** [comment]
If I use TraceWriter, the entries are displayed in the console when debugging in VS2017. If I switch to ILogger, nothing is rendered to the console.

**Comment by johnib** [comment]
same for me as @roryprimrose says.

**Comment by roryprimrose** [comment]
I'm now using an Autofac module to create ILogger<T> instances using the LogFactory from an Azure functions context. 

This doesn't log any messages to the console when debugging locally. Similarly, it also doesn't log to the log in the Azure portal. It does however log entries to Application Insights although it is difficult to get access to this data. The only way I've been able to do it so far is to run AI analysis queries over log data. I haven't been able to figure out a nice way of getting to the log data from the Azure portal itself.

**Comment by MrGlenThomas** [comment]
@roryprimrose How do you access the logger factory from the azure function context? If I add an ILoggerFactory parameter my function fails to run with a binding error. Only a parameter type of ILogger resolves an instance from the function host.

**Comment by Mike-EEE** [comment]
Using `1.0.12`... does the `ILogger` work at all?  Is the guidance/expectation to use `TraceWriter` instead?

**Comment by roryprimrose** [comment]
@MrGlenThomas Sorry, took me a little while to get back to this. I've just posted about doing dependency injection with ```ILogger``` and ```ILogger<T>``` in Azure Functions. See https://www.neovolve.com/2018/04/05/dependency-injection-and-ilogger-in-azure-functions/

**Comment by paulbatum** [comment]
As far as I can tell this bug is fixed when running against functions V2 (beta). Still annoying for it to be busted for V1 though.

**Comment by brettsam** [comment]
The fix for this is now merged in #437 and will be a part of the next CLI release.

**Comment by tourili** [comment]
Hi @brettsam, sorry but I am getting confused here
Logs written to ILogger on azure webjob are not present on the azure portal dashboard, but I can see them on the console when adding console provider (.AddConsole()).
If I use TraceWriter I can see them written in the dashboard, but would like to use ILogger 
Is this fixed or still pending?

**Comment by brettsam** [comment]
What version of the CLI are you using? 1.0.12 should have this fixed.

**Comment by tourili** [comment]
I'm looking right on azure portal https://<web_app>/azurejobs/#/jobs/continuous/<webjob_name>. I'm not using CLI localy

**Comment by brettsam** [comment]
Oh sorry -- this issue is explicitly for the Functions CLI. I misread your comment. I've created a new issue here that we can follow-up on: https://github.com/Azure/azure-webjobs-sdk/issues/1716

**Comment by DocGreenRob** [comment]
I was able to use the `ILogger` from the `Microsoft.Extensions.Logging` library in my Azure Function project.  However, when trying to do the same in my unittest project, which is using `Moq` I am unable to use it.

![image](https://user-images.githubusercontent.com/7489324/44486783-66897100-a609-11e8-9b7a-8f0990d36f61.png)


then, if I try `Ctrl + .` I get:
![image](https://user-images.githubusercontent.com/7489324/44486813-7bfe9b00-a609-11e8-89d7-36444b97f560.png)

What am I doing wrong?

**Comment by paulbatum** [comment]
I think either your unit test project is missing a reference to `Microsoft.Extensions.Logging`, or its hitting a naming conflict and you should try `Microsoft.Extensions.Logging.ILogger`.
