### ISSUE TITLE
rpm packages are out of date

### ISSUE THREAD

**Issue by yeroc** [Azure/azure-functions-core-tools#1307]
Under #368 (resolved) the installation of azure-functions-core-tools was made available via a simple:
```
sudo yum install azure-functions-core-tools
```
once the Microsoft yum repository is enabled via:
```
sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
```
However, I discovered the version in the repository is pretty old (2.0.1_beta 25)!  Can we ensure current releases are deployed?

**Comment by ahmedelnably** [comment]
@yeroc we no longer update the rpm repo with the latest versions of the core tools, please use any of the currently supported installation techniques mentioned in the readme

#368 was resolved because most of the work is done, not all of the proposed experiences
