### ISSUE TITLE
Support for --cors-credentials in the local.settings.json file

### ISSUE THREAD

**Issue by Tioga060** [Azure/azure-functions-core-tools#1309]
Currently, If I want to run the debugger with `--cors-credentials`, I have to pass it into the debug arguments. It would be nice to be able to specify `--cors-credentials` somehow in the local.settings.json file instead, since I'm already adjusting some my cors settings with the "CORS" parameter anyways.

**Comment by ahmelsayed** [comment]
You should be able to set [`CORSCredentials`](https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/Common/HostStartSettings.cs#L13-L14) to true there.

**Comment by Tioga060** [comment]
Ah, thank you. Added a documentation request here: https://github.com/MicrosoftDocs/azure-docs/issues/31524
