### ISSUE TITLE
Add README.md to npm during publish

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1312]
During publish to npm, we manually add README to the npm repository.

This has caused us to miss adding the file during multiple releases, as we didn't automate this process, or document it.

We should use something like `prepublishOnly` hook in `package.json` to auto copy README from the base repository and add it to `.gitignore`.

**Comment by bnb** [comment]
+1. I thought I'd already created an issue for this but just came to check on it and discovered this one. Thank you for the issue @ankitkumarr 🙏
