### ISSUE TITLE
"Error calling sync triggers (Unauthorized)" in West Europe

### ISSUE THREAD

**Issue by timlod** [Azure/azure-functions-core-tools#1318]
Hello,

```
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (Unauthorized).
```

I get this error when publishing my function to West Europe using the functions core tools.
I publish to a Linux consumption plan from an Azure DSVM, the function is a ServiceBusTopicTrigger that writes to CosmosDB (all in west europe).
I then did the same deployment to East US and it worked (and ran), so I assume there's something with the region that makes it fail.

**Comment by zecloud** [comment]
Almost the same message in West Europe too a deployment in Python

```
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
The SSL connection could not be established, see inner exception.
```

**Comment by ankitkumarr** [comment]
@timlod and @zecloud, are you still seeing issues? If so, would you mind setting an environment variable `CLI_DEBUG=1`, and sharing the publish output (the last part during "syncing triggers")?

**Comment by zecloud** [comment]
My latest deployment has worked with no errors.
 All seems to work correctly but I can't see the triggers on the portal now.

**Comment by timlod** [comment]
Sorry for the late reply, I was on holiday.
Deployment worked a week after I had the issue.
Thanks for fixing!
