### ISSUE TITLE
AzureFunctionsTools cannot locate .NET Framework v4.7.1

### ISSUE THREAD

**Issue by vijayrkn** [Azure/azure-functions-core-tools#1319]
When trying to run an app in visual studio 2017, I receive a popup saying  that ".NET Framework version needs to be 4.7.1" (or some variation). However,  due to the .NET Framework being naturally installed at v4.7.2 on the computer  you cannot install v4.7.1 so the cli func.exe is not runnable.

**Comment by ahmelsayed** [comment]
v1 used to have a hard dependency on [4.7.1](https://github.com/Azure/azure-functions-core-tools/blob/v1.x/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj#L13), i.e not 4.7. Though I'd expect it to work fine with 4.7.2 only installed. I'm not sure why it wouldn't work. 

Do you see that error coming from `func.exe` itself, or from some other place in VS?

**Comment by vijayrkn** [comment]
@ahmelsayed - I had created this issue on behalf of another customer issue that came to the tooling side. Unfortunately it is an internal issue. I will add you to the issue so that you could probably get more details on it.

**Comment by vijayrkn** [comment]
This is the internal issue - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797076

**Comment by ahmedelnably** [comment]
Closing as stale
