### ISSUE TITLE
func azure functionapp publish no longer works with javascript functionapp

### ISSUE THREAD

**Issue by zacktayl** [Azure/azure-functions-core-tools#1326]
**Current Settings:**
* FUNCTIONS_EXTENSION_VERSION: ~2
* FUNCTIONS_WORKER_RUNTIME: node
* WEBSITE_NODE_DEFAULT_VERSION: 8.11.1
* WEBSITE_RUN_FROM_PACKAGE: 1

**Steps to reproduce:**
1. Setup a JS Azure functionapp
2. Change a javascript file in the app locally
3. Deploy the change to the functionapp using the cli: `func azure functionapp publish project_name`
3. Open the functionapp in the portal
Issue -> The javascript file is not updated

**Other Notes**
1. I have tried the above process on two separate JS function apps with the same results. 
2. I also followed the advice from [this post](https://github.com/Azure/azure-functions-core-tools/issues/1212#issuecomment-485517447) and ensured the AzureWebJobsStorage property is correct.
3. I was using a slightly old version of the `func cli` so I upgraded to version 2.7.1158. Same results.

**Comment by ankitkumarr** [comment]
@zacktayl, what platform and plan do you have your function app on? (Linux Consumption, Windows Consumption, Linux App Service, Windows App Service)

**Comment by zacktayl** [comment]
Hey @ankitkumarr! The function app is running on the consumption plan and I'm almost positive it is using the Windows platform. I've tried to determine which consumption plan I'm using but I don't see any obvious indication if its Windows or Linux using Azure online.

**Comment by ankitkumarr** [comment]
@zacktayl, I wasn't able to reproduce this issue. Would you mind sharing you function app name, and I can check what's going on? If you want to share it privately, you can do it following these steps https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately.

**Comment by zacktayl** [comment]
So this seems to have resolved itself on Friday (05/24). I created a new function app to test deploying to and that worked. After that, I tried deploying to my function app that was having problems and everything was working. Really odd.
