### ISSUE TITLE
Handle Python versioning

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1327]
**Scenario**
Currently, users with a Python version different than 3.6.x are blocked from creating and publishing Function Apps. We want to tweak the command line experience to unlock this scenario and surface a discoverable warning in the console during `func init`, `func start` and `func publish`.

**Comment by ankitkumarr** [comment]
Blocked on https://github.com/Azure/azure-functions-python-worker/issues/450
