### ISSUE TITLE
Local dev environment - way to launch only specific functions from command line

### ISSUE THREAD

**Issue by jtlz2** [Azure/azure-functions-core-tools#1331]
Github question refers - https://stackoverflow.com/questions/56217001/azure-functions-how-do-i-launch-only-a-specific-function-in-local-dev-environme

As suggested there by @ahmelsayed, it would be amazing to be able to start the local host from the command line with only a subset of the available functions, i.e.

`func host start`

->

`func host start --functions <list of functions>`

@ahmelsayed Perhaps you can assist with this feature request?

Huge thanks!

**Comment by ahmelsayed** [comment]
thanks @jtlz2 I think it should be a simple change here. I'll take care of it.
