### ISSUE TITLE
npm install also works on macOS (and probably Linux?)

### ISSUE THREAD

**Issue by bnb** [Azure/azure-functions-core-tools#1333]
Currently `npm install` is listed only as an install option for Windows currently.

As far as I can tell, `npm i azure-functions-core-tools -g` installs a fully working v2 version of the `func` CLI for macOS.

If this is indeed a cross-platform install option, perhaps it coudld be split out as such 😊

**Comment by slowik21861** [comment]
There is an error during macOS install
[2019-05-25T05_46_52_738Z-debug.log](https://github.com/Azure/azure-functions-core-tools/files/3219162/2019-05-25T05_46_52_738Z-debug.log)

**Comment by ahmelsayed** [comment]
There is a note 

> NOTE: npm can be used on all platforms. On unix platforms, you may need to specify --unsafe-perm if you are running npm with sudo. That's due to npm behavior of post install script.
