### ISSUE TITLE
Log streaming for Python - Open Browser

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#1334]
On `func azure functionapp logstream <app_name>`, launch the **Live Metrics Stream** view in the browser.

**Comment by ahmedelnably** [comment]
I would rather not to change the current behavior
a more realistic approach would be 
`func azure functionapp logstream --browser`
or
`az functionapp monitoring logstream --browser` or something like that

I would prefer to wait until we have a consumable API to support the streaming from command line and not change the behavior

**Comment by asavaritayal** [comment]
From the other thread, it looks like the API is not scheduled to arrive for another 6-7 months. In the meantime, we need a debugging story for Python (tracked as part of the Day 1 reviews). Constructing the URL and using it to launch the browser seems to be the cheapest solution here. Open to other options/suggestions on how we can make the Python users successful at GA.
