### ISSUE TITLE
Add --debug to the commands

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-core-tools#1336]
right now to get more verbose output from the commands, you will need to set the env variable CLI_DEBUG=1 which enables it for all commands, it would be better if we give the user the option to have --debug mode for only a single command on demand

**Comment by ahmelsayed** [comment]
After needing it a bunch of times, I was wrong. I agree now that this would be a useful addition

**Comment by jeffhollan** [comment]
Came up while trying to debug the core tools today - I think we should consider this for better troubleshooting - including adding a section to core tools doc on how you can get more verbose logs when diagnosing a CLI command

// @apawast
