### ISSUE TITLE
Freezes at getting accessToken

### ISSUE THREAD

**Issue by akshaybabloo** [Azure/azure-functions-core-tools#1339]
For some reason, on Windows, the function tools freeze at

```bash
> cmd /c az account get-access-token --query "accessToken" --output json
```

when I try to do

```bash
func azure functionapp publish neucube-instance-function --build-native-deps --publish-local-settings
```

The only way to get over this is to `end task` the current session and do this in a new command prompt session.

![Annotation 2019-05-24 110829](https://user-images.githubusercontent.com/7360286/58292122-4d218980-7e14-11e9-910d-64ee4d74e5e8.jpg)

**Update:**

> The only way to get over this is to `end task` the current session and do this in a new command prompt session.

Sometimes even this doesn't work

**Comment by ankitkumarr** [comment]
Can you try running `az account get-access-token --query "accessToken" --output json` in a command prompt window? Do you see a similar freeze?

**Comment by akshaybabloo** [comment]
No, I don't, that seems to be working fine.

**Comment by ankitkumarr** [comment]
@akshaybabloo, what version of core-tools are you on (`func --version`)?

**Comment by akshaybabloo** [comment]
I am on version `2.7.1158`

**Comment by ahmelsayed** [comment]
What do you get if you run `cmd /c az account get-access-token --query "accessToken" --output json` from the same shell as your python venv?

If that works, can you check the process tree for `func.exe` and see if `cmd.exe` or `python.exe` is still around after that `> cmd /c ....` line is printed from the core-tools

**Comment by akshaybabloo** [comment]
`cmd /c az account get-access-token --query "accessToken" --output json` works.

Yes, those are still around and using up to 30% of the resources but no output

**Comment by ahmelsayed** [comment]
I'm not sure what's different about your machine since I can't repro it. If running the get access token command works just fine, you can try running it like this instead 

```
az account get-access-token --query "accessToken" --output json | func azure functionapp publish neucube-instance-function --build-native-deps --publish-local-settings --access-token-stdin
```

**Comment by akshaybabloo** [comment]
I will try that on Tuesday and let you know

**Comment by akshaybabloo** [comment]
I haven't tried this yet. I am using VS code to do this. I will give it a try soon
