### ISSUE TITLE
Gather Telemetry on usage

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1360]
Work-items (to be updated) -- 

- Add all the **infrastructure** code (https://github.com/Azure/azure-functions-core-tools/issues/1535)
- Opt out by default for **VS Extension** (https://github.com/Azure/azure-functions-core-tools/issues/1574)
- Opt in for **VS Extension** where we can collect
- Update all distributing channels to add information on opt-out (PRs - https://github.com/Azure/azure-functions-core-tools/pull/1555, https://github.com/Azure/homebrew-functions/pull/15, https://github.com/ahmelsayed/publish-script/pull/1)

**Comment by ankitkumarr** [comment]
Adding to Sprint 52 for scoping out the work and pipeline.

**Comment by fabiocav** [comment]
This will be an epic tracking the issues we'll be creating for this feature.

**Comment by ahmedelnably** [comment]
Closing this as the work to gather telemetry has been done
