### ISSUE TITLE
Merge the PR 789

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-functions-core-tools#1371]
Hi,

Could you verify and merge the PR 789 (https://stackoverflow.com/questions/56466144/how-to-create-an-azure-function-and-configure-it-with-azure-active-directory-onl/56501183#56501183)?

I created a question on stackoverflow available here:
https://stackoverflow.com/questions/56466144/how-to-create-an-azure-function-and-configure-it-with-azure-active-directory-onl/56501183#56501183

I would like to test the authentication locally (and in my tests on VSTS too). The PR seems to resolve my expectations.

Thanks for your help

**Comment by ahmedelnably** [comment]
The proper integration with easy auth feature is still in the works, once we have the work done we will merge this PR.

Closing this issue, please follow the PR as we will provide the updates there as we make progress
