### ISSUE TITLE
Show proper error messages when packapp fails to download pip dependencies

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1372]
When publishing without `--build-native-deps`, often times packapp shows a generic failure error if requirements.txt fails. 

It would be nice to show the actual error to the users when a failure occurs.

**Comment by ankitkumarr** [comment]
Currently if docker is not running, we also just fail with generic permissions issue. We should show the right error message there as well. This error message fix can also come as part of this issue.

**Comment by ahmedelnably** [comment]
Changing the priority:
For all error message enhancements a P2 is more appropriate
