### ISSUE TITLE
No known way to deploy Azure Function Http App to AKS and allow HTTPS

### ISSUE THREAD

**Issue by SpicySyntax** [Azure/azure-functions-core-tools#1373]
I am unaware of a way to deploy an azure function HTTP trigger to AKS and enable HTTPS.

Maybe there is a lack of understanding on my part, but I could not find any examples or references in the documentation or anywhere else. (This is the closest thing to a solution I have found [using ingress controller](https://docs.microsoft.com/en-us/azure/aks/ingress-tls))

Is there currently a way to do this using azure-function-core-tools?

Thanks

**Comment by ahmedelnably** [comment]
cc/ @jeffhollan 

I believe this is an AKS configuration question, Azure Functions Core Tools doesn't provide management functionality to AKS clusters
