### ISSUE TITLE
Investigate adding `func` CLI to Cloud Shell

### ISSUE THREAD

**Issue by joeyaiello** [Azure/azure-functions-core-tools#1376]
Just making a placeholder for myself to look into this

**Comment by ahmedelnably** [comment]
Update, we are already in the process of trying this out, we don't have an ETA right now but should be early Q1FY20

**Comment by ankitkumarr** [comment]
@ahmedelnably tested and it's in PR in cloud shell.

**Comment by LeastOne** [comment]
> @ahmedelnably tested and it's in PR in cloud shell.

Awesome! Can you clarify what "in PR in cloud shell" means?

**Comment by ahmedelnably** [comment]
There is a PR opened for it in the cloud shell repo :)
unfortunately I can't share the PR
