### ISSUE TITLE
`func host start` false triggers

### ISSUE THREAD

**Issue by abhilash1in** [Azure/azure-functions-core-tools#1380]
I have a function that has a Blob Storage trigger/binding. When I select `Attach to Python Functions` option in VS Code debugger, it said `Executing task: .env\Scripts\activate && func host start <` and my local function was automatically triggered with the last uploaded file in the provided blob storage container path (`dropzone/files/{name}`)

Expectation: local function starts and will be invoked only for new/updated files in my blob storage container path provided.

I'm quite sure that I did not add/modify any files to my container when the function was running. The function was automatically triggered with information of the last file uploaded to the provided blob storage container path.

Unfortunately, this only happened a couple of times and I do not have the logs for it. Most of the times, the observed behavior was same as the expectation mentioned above.

**Comment by abhilash1in** [comment]
If this is an expected behavior, is this documented any where? I couldn't find anything about this.

**Comment by abhilash1in** [comment]
Similar to - https://stackoverflow.com/questions/52836451/azure-function-app-run-single-azure-function-locally-to-debug

**Comment by abhilash1in** [comment]
Same thing happened with a C# function. 

```
[6/13/2019 3:48:06 AM] Executing 'data_hasher' (Reason='New blob detected: dropzone/files/myfile.txt', Id=1d9c0980-19cf-4c6e-84ce-4970531cb37c)
[6/13/2019 3:48:06 AM] C# Blob trigger function Processed blob
 Name:myfile.txt 
 Size: 5793292 Bytes
[6/13/2019 3:48:06 AM] Executed 'data_hasher' (Succeeded, Id=1d9c0980-19cf-4c6e-84ce-4970531cb37c)
```

**Comment by ahmelsayed** [comment]
That's the expected behavior. BlobTrigger maintains state in your `AzureWebJobsStorage` about where it started and what is pending processing. If you want the behavior you're describing, you'll need to clear the `azure-webjobs-host` container on that storage account between restarts.
