### ISSUE TITLE
Failed deployment to Azure Kubernetes Cluster

### ISSUE THREAD

**Issue by SpicySyntax** [Azure/azure-functions-core-tools#1386]
### Kubectl:
Client Version: v1.14.0, Platform:"windows/amd64"
Server Version: v1.13.5, Platform:"linux/amd64"

## Issue Description

I have been deploying my Azure Functions to Azure Kubernetes Service regularly for a few months, but starting today my deployments via azure function core tools have started failing.

E.G
```bash
func deploy --platform kubernetes --name crack-detection --registry nickjpurcell --min 3 --max 4
```
Yields: 
```
Building Docker image...
Running 'docker build -t nickjpurcell/crackdetection d:\git_projects\ObjectDetectionAPI\ObjectDetectionFunctions'...................................done
Pushing function image to registry...
Running 'docker push nickjpurcell/crackdetection'....done
Error running kubectl create ns azure-functions.
output: Error from server (AlreadyExists): namespaces "azure-functions" already exists
```

This is blocking my deployments and I can't find a way around it.

**Comment by ahmelsayed** [comment]
Please try 

```
func kubernetes deploy --name crack-detection --registry nickjpurcell --min-replicas 3 --max-replicas 4
```

instead, which will be replacing `func deploy --platform kubernetes`

**Comment by SpicySyntax** [comment]
@ahmelsayed I ended up switching to Helm for my deployments. Are there any plans to integrate helm deployments with azure functions core tools kubernetes deployments?

**Comment by ahmelsayed** [comment]
yep, tracked by https://github.com/Azure/azure-functions-core-tools/issues/754 

It's a bit tricky today since the Deployment object changes depending on whether you have http functions or not, and that's done in the core-tools by parsing your functions and generating the right artifacts every time. It'll be hard to emulate that in helm, so I need to think of another way.
