### ISSUE TITLE
No such file or directory on macOS

### ISSUE THREAD

**Issue by miguelzakharia** [Azure/azure-functions-core-tools#1403]
Tools version: 2.7.1373
OS: macOS

I keep getting an error that states "No such file or directory" when I try to run `func init` or `func start`. With `init` I'm asked to select a worker runtime and then immediately see the error message after I do that. With `start` the message shows up immediately. This is not a problem when I run it in Ubuntu.

I have traced the issue to line 16 in `src/Azure.Functions.Cli/Common/CommandChecker.cs`. If I change `bash` to `/bin/bash` the error goes away. 

I can create a PR for this change, but since tests don't work with Core yet according to `Contributing.md`, I'm not confident this change will not break something else.

**Comment by ahmedelnably** [comment]
The information in `contributing.md` is stale, we will update it with the correct information.

In the meanwhile we are happy for you to contribute a PR to fix this issue
