### ISSUE TITLE
Provide more informative error messages for incorrect requirements.txt ent

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-functions-core-tools#1413]
Suppose you create a Python Azure Function and have an incorrect entry in requirements.txt, like you added the "logging" library which is unnecessary.
When you try to publish the function with:
func azure functionapp publish functionname
The error message returned to the command line should reference the specific requirements.txt entry that had a problem, and not fail with a generic "exit code 1".

**Comment by ankitkumarr** [comment]
Dup of https://github.com/Azure/azure-functions-core-tools/issues/1372

This was closed by https://github.com/Azure/azure-functions-core-tools/pull/1379
