### ISSUE TITLE
Installation instructions for 'other' Linux versions missing key details

### ISSUE THREAD

**Issue by sfabijanski** [Azure/azure-functions-core-tools#1416]
Installation of the azure core tools cli was a requirement to get the Azure Functions extension working in VS Code on my Fedora 30 workstation. I tried following the instructions for installation [here](https://github.com/Azure/azure-functions-core-tools#other-linux-distributions)). However, some key requirements (like the requirement for the .Net SDK and needing to build the app from the zipped download--rather than unzip and run) were missing from the instructions. 

I muddled my way through some of this and eventually got it to work. I created a gist to describe the process. This should work for more recent versions of Fedora. I wasn't sure how best to communicate the process so I'm including the link to my gist: https://gist.github.com/sfabijanski/2d2bda86853771e720fc370fd9586362

**Comment by ahmedelnably** [comment]
you shouldn't need to build the core tools if you download the build zip
**Azure.Functions.Cli.linux-x64.<version>.zip**
