### ISSUE TITLE
Detect & Block - Storage Emulator when -i flag set

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-functions-core-tools#1418]
The func tools should detect and block when settings in the local.settings.json are set to default values or settings such as the storage emulator and not allow the deployment.

I ended up having to kill the function app and redeploy to undo the issues this accidental mishap caused.

Really, it should do this for all settings files as a validation step.

**Comment by priyaananthasankar** [comment]
cc: @ankitkumarr  - this is pretty easy detection for func core tools to do and stop invalid deployments.

**Comment by ankitkumarr** [comment]
@drcrook1, `local.settings.json` settings, by default, are not propagated to the Function App in Azure. If you did explicitly use `--publish-local-settings` or `-i` (as the issue title suggests), I am not sure if we should add an additional detection or blocking validation. 

General practice is that you should not need to update your Function App settings with `local.settings.json` every time. It is meant for local development only. Ideally, you would always want to publish without `-i`, and if you needed to forcefully update your Application Settings in Azure using the `local.settings.json`, then we you want to use that flag. 
IMO, the flag should not be part of the typical workflow in most cases.
