### ISSUE TITLE
Should Functions Core Tools run in the Azure Cloud Shell?

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#142]
It's pretty nifty that you can now run Azure CLI in the [Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/cloud-shell/overview) in the Azure portal without having to download and install the CLI or login.  
Would there be any benefit to also let customers use Functions Core Tools in Cloud Shell?  
I realize that it's the opposite of local development--but it may be an easy way to let users try out our Core Tools in a low-friction way. There may also be future integration with docs.microsoft.com that lets you run command snippets in Cloud Shell.

**Comment by SyntaxC4** [comment]
@lindydonna @brendandburns Would this be possible?

**Comment by ahmelsayed** [comment]
It won't be possible today as we're still windows only and Cloud Shell is running linux. once this https://github.com/Azure/azure-functions-cli/issues/13 is in, we can look at this.

**Comment by ahmedelnably** [comment]
@TechnologyAnimal We will be looking into this

**Comment by ankitkumarr** [comment]
Coming soon! Thanks to @ahmedelnably
