### ISSUE TITLE
Enable SSH in a --docker project

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#1420]
To be able to connect to a container from Kudu, it seems that you need to have SSH enabled in your container. However, we don't provide an help with this in the generated dockerfile. 

Is it possible to create add an `sshd_config` file and the SSH config steps in the generated dockerfile, as shown in [this article](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#enable-ssh-connections) (assuming it's not a security issue. We could also comment out the SSH stuff in the dockerfile so that SSH isn't enabled by default, but the config commands are there.

**Comment by ahmedelnably** [comment]
@ahmelsayed do we expect customers to look at the generated docker file to find that information?

**Comment by ahmelsayed** [comment]
We have `-appservice` flavors of all the images that include that by default. We can have a comment 

```dockerfile
# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:2.0-appservice 
FROM mcr.microsoft.com/azure-functions/dotnet:2.0
...
```

**Comment by ggailey777** [comment]
@ahmelsayed that would be awesomely useful for the custom container tutorial, instead of having them add in the SSH stuff into the Core Tools generated --docker project.

**Comment by ggailey777** [comment]
I've added this to the custom container tutorial: https://github.com/MicrosoftDocs/azure-docs-pr/pull/89761
