### ISSUE TITLE
Add runtime version selection into the create flow

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-core-tools#1428]
Update CLI to add ability to pick a runtime version for a given language. For example,

- Prompt user to select a version from a list of supported runtimes.

cc @ahmedelnably  - If there is a spec for this, please share

**Comment by ahmedelnably** [comment]
@pragnagopa There is no spec for this.
What is the target language here?

**Comment by pragnagopa** [comment]
This is tracking item to update the create flow in CLI that allows user to pick a runtime version for any language. Soon, we have multiple versions for Python similar to Node

**Comment by pragnagopa** [comment]
This should include bitness selection.

**Comment by ankitkumarr** [comment]
@pragnagopa, as we discussed briefly earlier this week, we shouldn't need this work-item anymore?

**Comment by pragnagopa** [comment]
@Francisco-Gamino / @eamonoreilly -  We do need tooling udpates to select version and bitness selection in az powershell create flow.  Can you please move this to the right repo?

**Comment by Francisco-Gamino** [comment]
Hi @pragnagopa,

We do not need this for PowerShell. The scenario for Managed Dependencies is to always fetch the latest ```Az``` major version at function app and generate ```requirements.psd1``` with this major version.

This is the PR which enables this scenario: https://github.com/Azure/azure-functions-host/pull/4782

cc: @eamonoreilly

**Comment by pragnagopa** [comment]
cc @divyagandhii 
@Francisco-Gamino  - can you please link tracking item for this issue on az powershell function app flow?
 @ankitkumarr  - is there a tracking item on az cli repo for this issue?

**Comment by pragnagopa** [comment]
Linux create flow: https://github.com/Azure/azure-cli/issues/10541
@ankitkumarr  - please create workitme for windows if needed.

**Comment by Francisco-Gamino** [comment]
@pragnagopa: I've created a work item (```New-AzFunctionApp``` needs to have a parameter to specify the runtime version) to track this.

https://github.com/Azure/azure-powershell/issues/10051

**Comment by ahmedelnably** [comment]
Here is the CLI one
https://github.com/Azure/azure-cli/issues/10549

**Comment by pragnagopa** [comment]
closing this issue as we now have work items on az cli and az powershell
