### ISSUE TITLE
Value for the --dotnet-cli-params Argument Appears to Require a Leading Space

### ISSUE THREAD

**Issue by whitestock** [Azure/azure-functions-core-tools#1431]
**This Does Not Work**
``
func azure functionapp publish MyApp --publish-local-settings --overwrite-settings -y --nozip --dotnet-cli-params "-c Release -r win-x64 -f netcoreapp2.2"
``

**This Works**
``
func azure functionapp publish MyApp --publish-local-settings --overwrite-settings -y --nozip --dotnet-cli-params " -c Release -r win-x64 -f netcoreapp2.2"
``

The only difference between the two commands is that in the one that works, the first character of the value for the --dotnet-cli-param argument is a space. I'm not sure if this is intentional or a limitation of the FluentCommandLineParser. Either way it seems to violate command line intuition that has been built up over decades. **As such please remove the "leading space" requirement.** 

I've provided a screenshot to assist with reproducing the issue. It shows the execution of both commands and shows applicable version numbers for PowerShell and Azure Functions CLI.

![image](https://user-images.githubusercontent.com/16354480/60775549-02fd1a80-a0d9-11e9-8980-f642aedb65cb.png)

**Comment by ahmedelnably** [comment]
Thanks @whitestock for reporting this, I agree with you that it is not intuitive, and the publish command should insert the white space automatically.
Bonus: if there is already a whitespace we should not add an extra one

**Comment by ahmelsayed** [comment]
You need to pass an [end-of-options](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) param after `--dotnet-cli-params`. so something like 

```bash
func .... --dotnet-cli-params -- "-c Release -r win-x64 -f netcoreapp2.2"
```
