### ISSUE TITLE
issue with versioning for release on npm

### ISSUE THREAD

**Issue by bigdatamoore** [Azure/azure-functions-core-tools#1446]
@soninaren

The latest version of this on npm is 2.7.1468
https://www.npmjs.com/package/azure-functions-core-tools/v/2.7.1468

however in the releases it has the version as 2.7.1471
https://github.com/Azure/azure-functions-core-tools/releases/tag/2.7.1471

I believe these are the same, or should be the same?

**Comment by soninaren** [comment]
@bigdatamoore they are actually different. We missed adding release for `2.7.1468` to the repository and release for `2.7.1471` is still on going. We generally push to npm after the release is fully verified in all the key environments. `2.7.1471` should be published to npm in a couple of days.

cc:@pragnagopa

**Comment by soninaren** [comment]
@bigdatamoore thanks for bringing this to our attention. Have added release for https://github.com/Azure/azure-functions-core-tools/releases/tag/2.7.1468

cc: @ahmelsayed
