### ISSUE TITLE
ImportError: cannot import name 'cygrpc'

### ISSUE THREAD

**Issue by johnlop** [Azure/azure-functions-core-tools#1456]
func --version: 2.7.1480
Windows: 10
Region: EastUS

I am experimenting with Python Azure Functions and have issues running it on my machine in the first place. When I run my code in debug through VSCode, it starts normally but then throws the following exception:

```
Exception has occurred: ImportError
cannot import name 'cygrpc'
  File "c:\users\xxx\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\grpc\__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
  File "c:\users\xxx\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\dispatcher.py", line 14, in <module>
    import grpc
  File "c:\users\xxx\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure\functions_worker\main.py", line 7, in <module>
    from . import dispatcher
  File "c:\users\xxx\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 1, in <module>
    from azure.functions_worker import main
```

Here is the beginning of the terminal output if it helps:

> Azure Functions Core Tools (2.7.1480 Commit hash: 8c6876cebeeca3dd6a1b895bd0e21acba4af8053)
> Function Runtime Version: 2.0.12555.0
> .NET Setting FUNCTIONS_WORKER_RUNTIME = python
> .NET Setting FUNCTIONS_EXTENSION_VERSION = ~2
> .NET Setting WEBSITE_NODE_DEFAULT_VERSION = 10.14.1
> Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32

I'm using a virtual environment with Python 3.6.8 and my code could't be more basic:

```
import logging
import azure.functions as func

def main(myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")
```

Any idea what the issue is?
Thanks.

**Comment by johnlop** [comment]
I'm closing this issue since I decided to abandon Python functions and won't be able to provide any more information.

**Comment by ankitkumarr** [comment]
@johnlop, sorry to see you leave. Apologies that it took us a couple of days to get back to you.
If there's a way we could have helped your scenario, definitely let us know.

As for the actual issue, I am unable to get a quick repro, but I would need a follow-up or two to understand what's going on in your case. I will leave this closed - as from your last response, you would be unable to provide any info.

**Comment by kajwanr** [comment]
@ankitkumarr , I am running into the exact same issue. 
Should I open a new issue?

**Comment by ankitkumarr** [comment]
@kajwanr, that would be great if you could do that with any relevant information.
Additionally, could you please also share in that issue, the contents of -
`...\azure-functions-core-tools\bin\workers\python\deps\grpc\_cython`.

Thanks!

**Comment by vbrodsky** [comment]
I have the same issue too...
the contents of _...\azure-functions-core-tools\bin\workers\python\deps\grpc\_cython_

_credentials
_cygrpc
 __pycache__
cygrpc.cp36-win_amd64.pyd (why amd? I am running Intel)
__init__.py

**Comment by ankitkumarr** [comment]
Would you mind checking if you are on a 32 bit Python 3.6?

Currently we only support 64 bit Python 3.6

**Comment by vbrodsky** [comment]
I am oops... let me re-install

**Comment by vbrodsky** [comment]
Thx for the quick reply, that was it.

First step taken!

**Comment by ankitkumarr** [comment]
No worries!

@kulkarnisonia16 / @jeffhollan, we should document this :)
