### ISSUE TITLE
better error message if the CLI sees nested values in local.settings.json

### ISSUE THREAD

**Issue by alemag1986** [Azure/azure-functions-core-tools#1473]
Hey guys, 

I'm still having issues *debugging locally* with the local.settings.json and AzureWebJobsStorage - I'm not sure if that one is the real issue or the error is a different one but the exception is not right. 

I'm running VS 2017 Enterprise Edition version 15.3.2
I have the last versions of Azure Functions CLI (and tried with the 2 latest: 1.0.11075.0, 1.0.11015.0)

This is how my local.setting.json looks like
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsDashboard": "<changed by alemag>",
    "AzureWebJobsStorage": "<changed by alemag>", 
    "commservicetopic": "<changed by alemag>",
    "EmailProvider": "<changed by alemag>",
    "SparkPostClientId": "<changed by alemag>",
    "SMSProvider": "<changed by alemag>",
    "ClickSendClientId": "<changed by alemag>",
    "ClickSendKey": "<changed by alemag>",
    "PushProvider": "<changed by alemag>",
    "MSNotificationHub": {
      "HubName": "<changed by alemag>",
      "ConnectionString": "<changed by alemag>"
    }
  }
}
```
*values are not encrypted

And this is how function.json looks like:
```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "commservicetopic",
      "topicName": "commservicetopic",
      "subscriptionName": "PushSub",
      "accessRights": "listen",
      "name": "message"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\CommService.dll",
  "entryPoint": "CommService.MobilePush.Run"
}
```

<img width="695" alt="ticket github" src="https://user-images.githubusercontent.com/1192674/29699546-44688038-8923-11e7-9948-d3040c4f3ad5.PNG">

Things that I tried:
- remove the Azure.Functions folder from C:\User\<username>\AppData\Local\.....
- run it from the command line as well as VS... no luck. 
- put the local.setting.json in every possible debug/release/bin folder nothing. 
- adding an applicationsettings.json and the Azure-Cli detected the 2 files and warned that application settings file will be ignored and local.setting.json was going to be used. 

The function is triggered by a Service Bus  (commservicetopic from local.settings.json key-values pairs). 

Function is working perfectly fine in Azure Cloud with same endpoints for AzureWebJobsStorage and ServiceBus.

I was able to debug the function back in VS 2017 Preview 15.3. 

Thanks!

**Comment by Patrickkk** [comment]
> Since settings.json does not support nested JSON, can you please describe the recommended alternative to storing nested JSON in configuration?

what i do now is use an additional local configuration file loading the configuration myself (combined with DI)
```        private IConfigurationRoot GetConfiguration()
        {
            var binDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var rootDirectory = Path.GetFullPath(Path.Combine(binDirectory, ".."));

            return new ConfigurationBuilder()
             .SetBasePath(rootDirectory)
             .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
             .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
             .AddEnvironmentVariables()
             .Build();
        }```

**Comment by jnhaffey** [comment]
Also found out that arrays are not supported

```
...
    "MonthlyIntervals": [3, 6, 12, 18, 24]
...
```

**Comment by aliarias** [comment]
Any updates on this?

**Comment by ahmedelnably** [comment]
Closing this as obselete
