### ISSUE TITLE
Unexplanable Access is denied Error

### ISSUE THREAD

**Issue by sschaumu** [Azure/azure-functions-core-tools#1479]
I understand that this issue is environmental. However, Access is denied messages need more verbose reasons.

I have been successfully publishing with the func cli for quite some time, then suddenly (after installing SQL express not sure if that caused the issue) func operations present "Access Is Denied" in red. 

When executing func new once you go through the questions and it attempts to create the function I am presented with access is denied - permissions are fine in the local directory, when I attempt to publish an access is denied is presented even with a non existent functionapp name, executing func azure functionapp list-functions xyz - Access is denied is presented (in the previous 2 cases Azure hasn't been accessed)

I believe the issue is related to whatever func is accessing locally however there is no way to determine what the deeper issue is. 

I have npm removed, updated the azure cli and reinstalled with no luck. If anyone has ideas as to the cause it would be great to resolve this. Additionally if a way of being able to determine the deeper issue could be added that would be fantastic as well.

**Comment by DrakeLambert** [comment]
@sschaumu Were you able to resolve this issue? I get `Access is denied` after running:
```bash
> func init
Select a worker runtime: dotnet
Access is denied
```
