### ISSUE TITLE
Azure CLI should work offline

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-functions-core-tools#148]
There's an issue right now with the CLI in that if I'm disconnected from the Internet then I can't create a new function. `func init` works as expected regardless of network connectivity. However, `func new` fails because it's unable to fetch the templates. 

In my discussion with @christopheranderson , he suggested that the initial decision was not to pull the templates to reduce the installation size. However, I believe that the small hit in size would totally be outweighted by the benefit of being able to run locally without any external network dependencies. The `dotnet` CLI already does this and they also pull the new templates every time there's an update.

My recommendation would be to pull the templates at install time and store them somewhere along with a calculated hash. Then, every time a user invokes `func new` we should check the local hash against a remote one for updates and pull the updated version down, only if the user is connected to the internet. If not, silently fail and continue as normal.  

![2017-06-02_09-49-35](https://cloud.githubusercontent.com/assets/4126750/26718442/f7eb04a6-4778-11e7-8b78-4e9007161f5f.png)

**Comment by cmatskas** [comment]
Hi all, could we please bump this up the backlog? It's a major issue not being able to work offline, especially for local dev

**Comment by cmatskas** [comment]
Picking this up again.. Any updates? If this is not too big, I'd be happy to take it on and contribute with the appropriate guidance... Thoughts?

**Comment by christopheranderson** [comment]
It's not likely to get done in the next few sprints given the other work on the plate.

Do you have any thoughts on how you'd like to implement it?

**Comment by cmatskas** [comment]
No preference. I’d need to see how the current solution is implemented and then come up with an offline version. At this stage I’m happy to take some direction and guidance...thx

**Comment by ahmelsayed** [comment]
This has been fixed for a while. The CLI ships with all templates: https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/StaticResources/templates.json.template
