### ISSUE TITLE
Zip files packaged in Linux (or mac) do not have proper permissions in files

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1484]
This causes Linux Elastic Premium payloads created in Macs to fail. Note, the zip file create then gets mounted by `fuse-zip` on the server. So, it's not trivial to add those read-only permissions on the server side after retrieving the contents.

See https://github.com/dotnet/corefx/issues/10223 for more info.

cc: @alexkarcher-msft @jeffhollan

**Comment by jeffhollan** [comment]
There was a related issue where if you had a file with u+x permissions it was losing those permissions during publish from mac.  Confirming that this work item will address that as well?

**Comment by ankitkumarr** [comment]
Yes @jeffhollan, it should take care of that as well.
