### ISSUE TITLE
Support csx in the dockerfile

### ISSUE THREAD

**Issue by guojian83** [Azure/azure-functions-core-tools#1487]
When the function is created in csx mode, the docker file is generated only for the modern csharp function.
The docker build fails at the dotnet publish step because a csx function may not have a csproj file.
```
func init --csx --docker
```

The proposal is to generate a different dockerfile for csx mode by removing the build step from the docker file just like other runtimes. Please see the proposed dockerfile as below:
```
FROM mcr.microsoft.com/azure-functions/dotnet:2.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY . /home/site/wwwroot
```
Having said that, it's not just the problem of docker build. As a scripting language mode, it does need to copy everything to the docker image instead of just the output of dotnet publish. This is the same approach as the other runtimes. It also covers the scenario when a csproj file has been added for extension purpose. 

Regards,
Jian

**Comment by ahmelsayed** [comment]
Closed in #1488
