### ISSUE TITLE
When using extension bundle, we shouldn't need dotnet

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1506]
`func new` with triggers that need extensions fail if you do not have `dotnet`, even if extension bundle is configured. This shouldn't be the case

**Comment by ankitkumarr** [comment]
cc: @soninaren

**Comment by soninaren** [comment]
I thought we did this already

**Comment by ankitkumarr** [comment]
Must have been slipped, as we usually don't encounter this use case ourselves.

https://github.com/Azure/azure-functions-core-tools/blob/aa40c1c8afefc844f8736dbbcf901da6b5459755/src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs#L148-L154

https://github.com/Azure/azure-functions-core-tools/blob/aa40c1c8afefc844f8736dbbcf901da6b5459755/src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs#L75-L81

**Comment by fabiocav** [comment]
@soninaren this is one of our P1s. Is this something we can assign to 58?

**Comment by soninaren** [comment]
yes, I will take this one.

**Comment by soninaren** [comment]
addressed in #1565
