### ISSUE TITLE
Output a request ID when synctriggers fails

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-core-tools#1509]
Sometimes the synctriggers step after deploying a package will fail. The core tools will output the status code but there is no identifying information for the request. We need to output some type of request ID so we can correlate with system logs. Ideally it would be the Activity ID.

**Comment by ankitkumarr** [comment]
If you use `CLI_DEBUG=1`, it will output the entire request and response payload. The response payload includes 
`x-ms-request-id`
`x-ms-correlation-request-id`
`x-ms-routing-request-id`

**Comment by paulbatum** [comment]
Customers will generally just paste the output they got without digging around for debug flags. So my suggestion is we output this information if there is a failure regardless of whether the use specified a debug flag.

**Comment by ankitkumarr** [comment]
I think that makes sense.
