### ISSUE TITLE
"Access is denied" Error After func init > dotnet

### ISSUE THREAD

**Issue by DrakeLambert** [Azure/azure-functions-core-tools#1521]
## Action

In empty directory, I run `func init` then choose `dotnet`.

## Expected Result

Function init files are generated

## Actual Result

I get the following output:

![image](https://user-images.githubusercontent.com/17054016/63538972-a31ecf80-c4de-11e9-89bd-ebc716ef2992.png)

## My Environment

OS: windows 10
azure-functions-core-tools version: 2.7.1575
dotnet version: 2.2.401

**Comment by ahmedelnably** [comment]
@DrakeLambert Please SET CLI_DEBUG=1 and rerun the command (in an empty folder) that will get us more information to investigate

**Comment by ahmelsayed** [comment]
what do you get if you run `where dotnet`? 

That code path is just running 

```csharp
var processStartInfo = new ProcessStartInfo
{
    FileName = "where",
    Arguments = "dotnet",
    RedirectStandardError = true,
    RedirectStandardOutput = true,
    CreateNoWindow = true
};
var process = Process.Start(processStartInfo);
```

**Comment by DrakeLambert** [comment]
@ahmelsayed `where` is not in my PATH. I am using powershell core. By default `where` is an alias for `Where-Object`.

**Comment by DrakeLambert** [comment]
@ahmelsayed I determined that this issue was caused by anti-virus software. Thank you for your help!
