### ISSUE TITLE
Error "Could not convert string to boolean: Deployment Underway" when publishing Python functionapp

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-functions-core-tools#1531]
I have created a Function App for Python, using an existing Linux app service plan S1 (all in Australia East region), and published the function app multiple times using Azure CLI. It worked fine until it stopped.

Now when I'm trying to publish a Function App (using command "func azure functionapp publish myfunctionapp --build remote"), the error is:
Could not convert string to boolean: Deployment Underway. Path 'msg', line 1, position 43.

I checked the code of my functions, they don't even have any 'msg' in them. Looks like an Azure bug?

**Comment by bukarev** [comment]
Just tried to publish a brand new function group with the only function (stub for HttpTrigger) using remote build option, and it failed with the same error.
Publishing with the option --build-native-deps worked, so it must be a bug with remote build on Azure side.

**Comment by ankitkumarr** [comment]
@bukarev, what version of `azure-functions-core-tools` are you on? There was a recent update and the new version (2.7.1585) should fix this issue.

**Comment by bukarev** [comment]
Hi @ankitkumarr I'm on 2.7.1575, but somehow when I try to upgrade it (I'm on Ubuntu 18.04.3 LTS), this is the latest version that I can get; i.e. no 1585.

**Comment by ankitkumarr** [comment]
Oh you are using `apt`. Sorry, that one's on me. I didn't get a chance to update it in apt yet. I will do it tomorrow if you wouldn't mind waiting.

**Comment by ankitkumarr** [comment]
@bukarev, we have released it to apt as well. You should be able to update core-tools now

**Comment by bukarev** [comment]
@ankitkumarr I updated the tools and it's of version 1585 now. However, My Function App stopped working. In the app I'm using an extra Python module requests, and it looks like the --build remote option doesn't attach that module anymore:
`2019-09-06T05:44:32.759689088Z: [INFO]  Exception: ModuleNotFoundError: No module named 'requests'
2019-09-06T05:44:32.759708889Z: [INFO]  Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 239, in _handle__function_load_request
2019-09-06T05:44:32.759741990Z: [INFO]      func_request.metadata.entry_point)
2019-09-06T05:44:32.759752590Z: [INFO]    File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/loader.py", line 66, in load_function
2019-09-06T05:44:32.759760990Z: [INFO]      mod = importlib.import_module(fullmodname)
2019-09-06T05:44:32.759769190Z: [INFO]    File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
2019-09-06T05:44:32.759777490Z: [INFO]      return _bootstrap._gcd_import(name[level:], package, level)
2019-09-06T05:44:32.759785390Z: [INFO]    File "/home/site/wwwroot/iotDecreaseResource/__init__.py", line 3, in <module>
2019-09-06T05:44:32.759793991Z: [INFO]      import requests`

It used to work fine before tools upgrade.
I can't use --build-native-deps option now, too, as it gives me the error "Response status code does not indicate success: 401 (Unauthorized)."

Any ideas how to fix that?

**Comment by ankitkumarr** [comment]
Would you be able to share your functionapp name?

**Comment by bukarev** [comment]
@ankitkumarr dds-rb-fun-002

**Comment by bukarev** [comment]
I have rolled back to the previous version of azure-functions-core-tools; I had to delete my function app in the cloud and redeploy it; it works fine now.
If you still need to have a guinea pig function app to find what went wrong I am happy to create a cloned copy of that function app.

**Comment by ankitkumarr** [comment]
@bukarev, no worries. We are aware of a bug on the platform that is affecting some of the Function Apps on Linux App Service plan when deploying using "Run From Package". This is the deployment method the new `azure-functions-core-tools` uses by default.

It is very likely that you were hitting that issue. The fix is being rolled out on the platform and should be available in all regions early next week.

**Comment by ankitkumarr** [comment]
I will post here once the deployment is complete and close this issue.

**Comment by MishalValiyakath** [comment]
> I will post here once the deployment is complete and close this issue.

@ankitkumarr I was using 2.7.1585 from the starting to deploy a python function in Linux based function app. It was working fine the last time I checked (couple of days ago). I am getting the same error mentioned by OP here. This will be resolved by a new version of npm package or by platform side?

**Comment by fabiocav** [comment]
The deployment is now complete. Can you please re-validate?

**Comment by ssthind** [comment]
Hi all, i am facing the same issue "Could not convert string to boolean: Deployment Underway. Path 'msg', line 1, position 43."

i was also trying remote deployment of python app on App service plan. But was pushing the code from windows10 platform which only install version 2.7.1575 of azure-functions-core-tools. (although it showed me some popup that v 2.7.16xx is available but not able to install). 
For me the issue still persists.

**Comment by ankitkumarr** [comment]
@ssthind, you would need to update update your azure-functions-core-tools. How did you install azure-functions-core-tools (npm or chocolaty for windows)

**Comment by bukarev** [comment]
Build seems to be going well now, thanks!
