### ISSUE TITLE
Allow Python 3.7 to perform func host start

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1534]
Currently we block users with Python 3.7 to run `func host start`. This is because the Python worker binaries that comes with core-tools is compatible with Python 3.6 only.

But, we have a work item to add Python 3.7 worker binaries with core-tools. As soon as that's in, we should not block users to perform `func host start` with Python 3.7.

**Comment by kulkarnisonia16** [comment]
@ankitkumarr - allow publishing local 3.6 Python to 3.7 Azure app and local 3.7 Python to 3.6 Azure app as part of this.

**Comment by fabiocav** [comment]
@kulkarnisonia16 this is still blocked, so we're not assigning to sprint 59

**Comment by fabiocav** [comment]
Adding this to sprint 60 as tentative. We're still blocked and this is currently at risk
