### ISSUE TITLE
Error in azure functions for python deployment on azure (Error : Response status code does not indicate success: 400 (Bad Request)

### ISSUE THREAD

**Issue by Godase** [Azure/azure-functions-core-tools#1540]
I created the basic **python azure function HttpTrigger functions**. After creating this function I published it on local and it's working fine. But whenever I am trying to deploy it on azure, then I got the below error.

**Please check the Below Error:-**

```
Getting site publishing info...
Creating archive for current directory...
Directory .python_packages already in sync with requirements.txt. Skipping restoring dependencies...
Uploading 4.28 KB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Response status code does not indicate success: 400 (Bad Request).
```

**Please check the below code that i have used:-**
```
import logging
import azure.functions as func

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    return func.HttpResponse(f"Hello!", status_code=200)
```

Is there any way to resolved the above error? Please let me know if any other option to solve the above issue.

**I have used Python 3.6.8**
**Azure Function location ;- West Europe**

**Comment by ahmedelnably** [comment]
Can you please provide the functionapp name to investigate further?
Also can you set CLI_DEBUG=1 and rerun the command to get more debug information
