### ISSUE TITLE
Release Azure Function CLI as nuget.org package instead of download from functionscdn.azureedge.net

### ISSUE THREAD

**Issue by mehulchandroliya** [Azure/azure-functions-core-tools#1549]
**Problem Statement:**
Release Azure Function CLI  not able to download from functionscdn.azureedge.net because many enterprises have a proxy setup which will not allow downloading package but can download update feed from the channel.
 
**Solution:**
Release Azure Function CLI as nuget.org package instead of download from functionscdn.azureedge.net because many enterprises have proxy setup which is open for NuGet through Nexus. #

**Comment by fabiocav** [comment]
We have plans to release the CLI as a .NET Core Global Tool, which would address your requirements. You can use #760 to track.
