### ISSUE TITLE
Make remote build default for Python

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-core-tools#1556]

**Comment by ahmedelnably** [comment]
For all languages?

**Comment by ankitkumarr** [comment]
I wonder if part of this work item, we should also add an output when people use `--build-native-deps` to tell them now they can use `--build remote` if they want (as we have been advising people to do `--build-native-deps`.

Or that can come later once we have success making this as the default. Just thinking out loud.

**Comment by ahmedelnably** [comment]
PR Merged, closing issue
