### ISSUE TITLE
Make changes for KEDA 1.0

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1559]
- Remove osiris for HTTP functions (not sure if we need this anymore)
- Generate new specs (auth parameter, api version, etc)
- Sure there are some more

**Comment by jeffhollan** [comment]
Creating now to track, but all breaking changes aren't in KEDA yet so can't do all of these now. Could start on Osiris removal

**Comment by tomkerkhove** [comment]
Just curious - Why are we removing Osiris for HTTP functions? I thought KEDA was relying on Osiris for that?

**Comment by jeffhollan** [comment]
I think the rational was Osiris is not 1.0, KEDA is.  We didn't want to mix and match a preview thing with a 1.0 thing - especially since I don't know what the development and investment roadmap for Osiris is moving forward.  Instead I would guess we just set up generic service for now.  We do have plans and funded work in next few months to make the HTTP + HTTP Scale (0 -> n) better though.  So more point in time

**Comment by ahmedelnably** [comment]
@jeffhollan and @ahmelsayed this should now be closed ... right?
