### ISSUE TITLE
Cannot access a disposed object. Object name: 'IServiceProvider' On Windows after .netcore 3 upgrade. 

### ISSUE THREAD

**Issue by NickMSW** [Azure/azure-functions-core-tools#1570]
I just recently upgraded my machine to .net core 3. After the upgrade, my functions are no longer able to run:

```
Azure Functions Core Tools (2.7.1585 Commit hash: 9a2b7239b937148e3b76e6f7999798629a82134a)
Function Runtime Version: 2.0.12641.0
[9/25/2019 1:52:57 PM] Stopping host...
[9/25/2019 1:52:57 PM] Host shutdown completed.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 245
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 55
Application is shutting down...

dotnet --version
3.0.100

func --version
2.7.1585
```

**Comment by NickMSW** [comment]
Looks like it's a similar issue to #1062

**Comment by ahmelsayed** [comment]
I think for dotnet 3 you'll need to wait to use func v3. Dotnet runs in process, and I'm not sure loading a v3 function in a v2 process would work

**Comment by NickMSW** [comment]
The weird thing is that I never updated the version of dotnet that I was targeting within my function. My .csproj file still is showing my target version and framework:     <TargetFramework>netcoreapp2.2</TargetFramework>
<AzureFunctionsVersion>v2</AzureFunctionsVersion>

So I'm not sure why it's defaulting to use dotnet 3

**Comment by ahmedelnably** [comment]
Are you running this from VS?
Also can you share the output of `dotnet --info`

**Comment by NickMSW** [comment]
It started when running from VS but then I also tried directly from the command line. Both outputting the same error.
dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ahmedelnably** [comment]
cc/ @fabiocav & @ankitkumarr to comment

**Comment by pereiren** [comment]
> I think for dotnet 3 you'll need to wait to use func v3. Dotnet runs in process, and I'm not sure loading a v3 function in a v2 process would work

Hi Ahmed,

Is there any ETA for the v3 functions? I would love to use .NET Core 3.0 in Azure Functions 

Thanks

**Comment by Sigi-os** [comment]
was there a solution?  I have this issue after an upgrade also, but I did purposely move to from 2.2. to 3.0

**Comment by fabiocav** [comment]
@pereiren the announcement is here: https://github.com/Azure/app-service-announcements/issues/200

This will start rolling out very soon. Please watch that announcement for updates.
