### ISSUE TITLE
Cannot download Azure Functions Core Tools on Mac OSX

### ISSUE THREAD

**Issue by bhaidar** [Azure/azure-functions-core-tools#1571]
hi,
I am facing a download error problem when installing Azure Functions Core Tools. Here's the details:

```bash
==> Installing azure-functions-core-tools from azure/functions
==> Downloading https://functionscdn.azureedge.net/public/2.7.1633/Azure.Functions.Cli.osx-x64.2.7.1633.zip
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "azure-functions-core-tools"
Download failed: https://functionscdn.azureedge.net/public/2.7.1633/Azure.Functions.Cli.osx-x64.2.7.1633.zip
```

Thanks

**Comment by balag0** [comment]
Are you able to download the zip file directly from https://functionscdn.azureedge.net/public/2.7.1633/Azure.Functions.Cli.osx-x64.2.7.1633.zip just to rule out transient network issues.

**Comment by bhaidar** [comment]
@balag0 Yes I can. Actually only using brew on Mac OSx causes the issue above. I installed the tools using NPM and works fine.

**Comment by ahmedelnably** [comment]
Closing this as there is a workaround, please reopen if issue still exist in future versions
