### ISSUE TITLE
Support local build for Python 3.7

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1573]
We need to be able to build locally (using an appropriate Docker container) for Python 3.7 function apps.

This would mean core-tools using a different docker container for Python 3.7 apps when `--build-native-deps` and packapp doing the right thing when building locally.

cc: @kulkarnisonia16

**Comment by Hazhzeng** [comment]
Thanks for reminding @ankitkumarr
