### ISSUE TITLE
Telemetry - do not collect if running as part of VS

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#1574]
For VS extension, we package a specific version of core-tools `win.min`. In our build pipeline, we could drop a sentinel in that package such that we don't collect telemetry if that sentinel exists. Unless, VS extension specifically asks us to opt-in and collect usage.

**Comment by ankitkumarr** [comment]
This will likely be moved to the next Sprint as other items with higher priority are rolling in.

**Comment by ankitkumarr** [comment]
PRs:
- https://github.com/ahmelsayed/publish-script/pull/1
- https://github.com/Azure/azure-functions-core-tools/pull/1636
- https://github.com/Azure/homebrew-functions/pull/15
- https://github.com/Azure/azure-functions-core-tools/pull/1555

Once all above are merged, this can be closed.

**Comment by fabiocav** [comment]
Closing as resolved.
