### ISSUE TITLE
Azure functions failing to start func host start on local

### ISSUE THREAD

**Issue by devslb** [Azure/azure-functions-core-tools#1591]
Hi, 
I am trying to run simple Azure function in python on local windows 10 machine, with below
> npm -g list azure-functions-core-tools
`-- azure-functions-core-tools@2.7.1704
but it fails with below error:
PS > func host start
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)

Is there something I might be doing wrong or something wrong with azure functions core tools version? 

thank you for helping!

**Comment by ahmelsayed** [comment]
Which operating system are you using?

**Comment by devslb** [comment]
This error is coming for 32-bit windows version, I tried on 64-bit Windows and it works. 
does it mean the function core tools is not supported on 32-bit?

**Comment by ahmedelnably** [comment]
@devslb, can you please use choco to install the 32-bit version of the tools? NPM installs the 64-bit version of the tools and that may cause issues on 32-bit versions of Windows

**Comment by galgrunfeld-madtrix** [comment]
> @devslb, can you please use choco to install the 32-bit version of the tools? NPM installs the 64-bit version of the tools and that may cause issues on 32-bit versions of Windows

I'm running a 64-bit Windows installation, Node.js 64-bit as well and am still getting this error.

**Comment by devslb** [comment]
Thanks, ahmedelnably, it worked now after installing with choco
