### ISSUE TITLE
No templates matched the input template name: BlobTrigger.

### ISSUE THREAD

**Issue by mohsinonxrm** [Azure/azure-functions-core-tools#1594]
I've built the azure-functions-core-tools on Raspberry Pi 4 but when I try to create a new Azure Function using:
`
func new
`
it gives me the following error:
`
No templates matched the input template name: BlobTrigger.
Error creating function
`
which I think is referring to:
https://github.com/Azure/azure-functions-templates

and that isn't going to build on Raspberry Pi 4 (.NET Framework...)

so my question is, is there any Azure Functions Core Tools CLI build available for Raspberry Pi 4 ARM32?

**Comment by mohsinonxrm** [comment]
well, I've resolved this by building the templates and moving them to the raspberry pi 4B.
Anyway, onto the next issue
`Azure Functions Core Tools (2.7.1 Commit hash: N/A)
Function Runtime Version: 2.0.12763.0
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell]
Cannot access a disposed object.
Object name: 'IServiceProvider'.
Application is shutting down...
`

**Comment by ahmedelnably** [comment]
@mohsinonxrm  Can you please set env variable CLI_DEBUG to 1 and attach the logs. this will give us more information to debug that.

To answer your earlier question, We do not have an Azure Functions Core Tools CLI build available for Raspberry Pi 4 ARM32

**Comment by ahmelsayed** [comment]
We don't have an ARM build of the runtime or the cli

**Comment by mohsinonxrm** [comment]
@ahmedelnably , sure I'll do that and provide the debug information in a new issue.
