### ISSUE TITLE
Can't install / upgrade via homebrew due to SHA256 mismatch

### ISSUE THREAD

**Issue by pallymore** [Azure/azure-functions-core-tools#1604]
Hi - I'm trying to upgrade my existing installation with homebrew but I kept getting this SHA256 mismatch error. I've tried `brew cleanup -s` and `rm -rf ${brew --cache}` but it still doesn't work.

I've also tried to remove the existing installation and start fresh. 

My console output:

```
~ brew install azure/functions/azure-functions-core-tools
==> Installing azure-functions-core-tools from azure/functions
==> Downloading https://functionscdn.azureedge.net/public/2.7.1704/Azure.Functions.Cli.osx-x64.2.7.1704.zip
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 95cb70382edc50e2264de0b41839476618c946d18fd8067ed0933f685e50f89e
  Actual: 47d20c45c95b3986c54003a448bc866995c9cb540400d201612012fd7cba3f95
 Archive: /Users/yuruiology/Library/Caches/Homebrew/downloads/4223ef6c32b3475a53ab22fdeec592cc706c17423110807efb476c559a6a76f6--Azure.Functions.Cli.osx-x64.2.7.1704.zip
To retry an incomplete download, remove the file above.
```

MacOS Catalina 10.15 (19A583) 

Thanks!

**Comment by pallymore** [comment]
Also I'm using the latest version of homebrew 

```
~ brew --version
Homebrew 2.1.14
Homebrew/homebrew-core (git revision 5ce802; last commit 2019-10-16)
Homebrew/homebrew-cask (git revision dc39a; last commit 2019-10-16)
```

**Comment by karluiz** [comment]
+ 1
 Homebrew 2.1.14

**Comment by jstevenson81** [comment]
Any fix to this yet?  I'm stuck as well.  Same problem.  Same SHA's as above.  OSX Catalina latest version of Homebrew.

**Comment by jstevenson81** [comment]
Not that this is the best or even a solution, but I added the actual SHA to usr/local/Homebrew/Library/Taps/azure/homebrew-functions/Formula/azure-functions-core-tools.rb
and it updated properly.  So, in the event you need to DEV ON!! Just do that for the moment until they fix it.

**Comment by jstevenson81** [comment]
Actual SHA in tap:  47d20c45c95b3986c54003a448bc866995c9cb540400d201612012fd7cba3f95

**Comment by alrod** [comment]
should be fixed now

**Comment by johnpapa** [comment]
It seems fixed now ... what was the fix?
