### ISSUE TITLE
`func azure functionapp publish` needs a few seconds before finding my app

### ISSUE THREAD

**Issue by Erikvl87** [Azure/azure-functions-core-tools#1616]
I am automating the creation of an Azure Function App. That means I am executing the `az functionapp create <args>` command and when that is finished I'm executing `func azure functionapp publish <FunctionAppName>`.

On the first couple of publish attempts I will receive the following error:
`Can't find app with name "<FunctionAppName>"`

The 3rd of 4th attempt (10-20 seconds later) will eventually succeed.

The `az functionapp create` returns, among other properties, that the `state` is `running` so I am assuming it should be OK to start publishing. How and when can I safely assume I can start publishing a functionapp using the `func azure functionapp publish` command?

**Comment by ahmedelnably** [comment]
This is due to the time it takes to update the different caching mechanisms in ARM (Azure resource manager).

**Comment by Erikvl87** [comment]
Well yeah I figured it would have something to do with populating the changes / updating cache, but there must be a way to determine when I can start publishing, right? Or would your advice be to just include a 30 second `sleep`...? ;)

**Comment by ahmedelnably** [comment]
For now I would recommend to include a 30 second sleep
