### ISSUE TITLE
build local flag is ignored when publishing python apps

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-core-tools#1623]
Could be because remote build is default now and that takes precedence over the flags passed in the command.

func azure functionapp publish <APPNAME>--build-local

Getting site publishing info...

Remote build is a new feature added to function apps.

Your function app mediareport does not support remote build as it was created before August 1st, 2019.

**Please use '--build local',** '--build-native-deps' or manually enable remote build.

For more information, please visit https://aka.ms/remotebuild

**Comment by Hazhzeng** [comment]
This issue is addressed by https://github.com/Azure/azure-functions-core-tools/pull/1611.
Waiting for the next release.
