### ISSUE TITLE
.NET Core 3.0 & Functions v3 compliant?

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-functions-core-tools#1628]
Hi,

Is there a plan to support x64 .NET Core 3 V3 functions?  Via the templates in Visual Studio, I can currently only run 32bit functions.

Thanks!

**Comment by ahmedelnably** [comment]
@soninaren can you please help here?

**Comment by soninaren** [comment]
We do have v3-preview out for Visual Studio. Please refer to `Creating with Visual Studio 2019` section of the documentation below. https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm. New function app projects from Visual studio 16.4 Preview 3 should automatically target netcore30. For versions older than Visual Studio 16.4 Preview 3 you can simple change the target platform to netcore30 in the project file. We also have work in progress to support 32 and 64 bit development in visual studio.

**Comment by a-vishar** [comment]
@soninaren - Do you have an estimation of when you will support x64 V3 functions OOTB?

**Comment by soninaren** [comment]
@ColbyTresness , @vijayrkn do you know of the release date for x64 support?

**Comment by vijayrkn** [comment]
In 16.4

**Comment by a-vishar** [comment]
@vijayrkn 
In 16.4.0 - p5:

```
[16/11/2019 18:18:49] System.Private.CoreLib: Could not load file or assembly ':LAUNCHDLLNAME, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
Value cannot be null. (Parameter 'provider')
```

**Comment by ahmedelnably** [comment]
@soninaren can you please validate that this is now supported

**Comment by soninaren** [comment]
This is now supported. VS should download x64 bits automatically from 16.4.
