### ISSUE TITLE
"Error: The specified module could not be found." on Windows Server 2016

### ISSUE THREAD

**Issue by GuyThreepwood** [Azure/azure-functions-core-tools#163]
I'm trying to run some functions on my Window Server machine, but it fails with the following error:

```
func host start
...
Debugger listening on [::]:5858
cd module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Guy\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\x86\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Guy\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\edge\edge.js:54:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

The OS has been installed not 10 minutes prior to installing node/npm and installing azure functions cli via npm.
Just to make sure it isn't my code, I ran "func init" and "func host start" and am getting the same results.

Is this because I'm missing some dependency?

Edit:
I should add that I'm using version 1.0.0-beta.99

# Solution
I was indeed missing a depencendcy:
edge.js requires [Visual C++ Packages (VS 2013)](https://www.microsoft.com/en-us/download/details.aspx?id=40784) and be sure to install the **x86** version.
_I'm not sure if edge.js works with a newer version of the packages or not. Never tested it._

**Comment by GuyThreepwood** [comment]
Ok, I was being a little bit stupid.
I hit this error when I was already frustrated and just threw my hands up in the air.

Now with more distance I was able to dig more into this problem.
I was missing a simple dependency of edge.js: Visual C++ Packages, specifically, I installed the VS 2013 version.

I think it'd be nice to have this dependency listed in the Readme somewhere as it is not directly obvious (at least it wasn't for me)

Side note, I assumed "edge_nativeclr.node" was in reference to "Edge" the browser, which doesn't exist on Windows Server 2016, but it's in reference to: https://github.com/tjanczuk/edge

**Comment by lindydonna** [comment]
@GuyThreepwood Sorry for the frustration. The dependency should automatically have been included when you installed the CLI. I guess there was an optional Windows component that wasn't installed.

CC @ahmelsayed

**Comment by skycocker** [comment]
@GuyThreepwood can you elaborate a little more on how you solved the issue? 

I have installed this: https://www.microsoft.com/en-us/download/details.aspx?id=40784

And then the .NET core from visual studio installer, then downgraded node to 6.11.1, then reinstalled azure-functions-core-tools, but still I'm getting the same error you have pasted in your issue description. I would really like to get this over with already 🙄

**Comment by skycocker** [comment]
Oh, nevermind, I just found out on the issue list that the cli is x86, therefore I figured I should have installed the x86 version of the Visual C++ Redistributable Packages for Visual Studio 2013, link to which I left in my previous comment. Sorry for bothering you guys. 
Still, I consider it quite important to put it in some readme.

**Comment by GuyThreepwood** [comment]
@lindydonna Wasn't just frustrated with the cli, It just was the last drop that made me give up for the day.

@skycocker Great that you could get it to run! I'll edit my first post to include your link and a note that this requires the x86 version.
I wonder if there are others with the same issue.

Happy coding :)

**Comment by KaiWalter** [comment]
I got the same issue when running the WebJobs.Script.Host in a container - though I included the VC2013 x86 redist

```
FROM microsoft/dotnet-framework:4.6.2-windowsservercore

SHELL ["powershell", "-Command"]

ADD http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x86.exe C:\\vcredist_x86.exe

RUN .\vcredist_x86.exe /q ; Remove-Item vcredist_x86.exe


ADD https://github.com/Azure/azure-webjobs-sdk-script/releases/download/v1.0.11296/WebJobs.Script.Host.1.0.11296.zip C:\\Host.zip

RUN Expand-Archive C:\Host.zip ; Remove-Item Host.zip


COPY App.zip C:/App.zip

RUN Expand-Archive C:\App.zip ; Remove-Item App.zip


SHELL ["cmd", "/S", "/C"]
ENV AzureWebJobsScriptRoot='C:\App'
ENV APPINSIGHTS_INSTRUMENTATIONKEY='...'
ENV AzureWebJobsStorage="..."

WORKDIR App

CMD "C:\Host\Microsoft.Azure.WebJobs.Script.Host.exe"
```

(`App.zip` contains the build+published Function App)

This is the error output I get

```
Reading host configuration file 'C:\App\host.json'
Host configuration file read:
{
  "serviceBus": {
    "maxConcurrentCalls": 1,
    "prefetchCount": 0
  }
}
File change of type 'Created' detected for 'C:\App\Exit-Global-Storage-V1\function.json'
Host configuration has changed. Signaling restart
File change of type 'Changed' detected for 'C:\App\Exit-Global-Storage-V1\function.json'
Host configuration has changed. Signaling restart
File change of type 'Created' detected for 'C:\App\Exit-Global-Storage-V2\function.json'
Host configuration has changed. Signaling restart
File change of type 'Changed' detected for 'C:\App\Exit-Global-Storage-V2\function.json'
Host configuration has changed. Signaling restart
Loaded custom extension 'BotFrameworkConfiguration'
Loaded custom extension 'SendGridConfiguration'
Loaded custom extension 'EventGridExtensionConfig'
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Host\edge\x86\edge_nativeclr.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Host\edge\edge.js:54:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by horsdal** [comment]
Just as a data point I had the same error as the OP when doing `func run .` in my function app folder. Installing the 2013 x86 C++ redist solved it.

**Comment by ahmedelnably** [comment]
Closing as stale

**Comment by cgillum** [comment]
I ran into this issue on a new Windows 11 machine with VS 2022 using the Azure Functions Core Tools. For anyone else that runs into this issue, I can confirm that installing the old Visual Studio 2013 C++ Redistributable Package fixed the issue. Here is the download center link: https://www.microsoft.com/download/details.aspx?id=40784.

Make sure to choose the **x86** version, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/2704139/164118235-91f8ad2b-b7e5-4400-be2e-5c2dd4100964.png)

FYI @soninaren, @fabiocav
