### ISSUE TITLE
How to configure Win10 workstation to use functions runtime v2.0.12835?

### ISSUE THREAD

**Issue by t-l-k** [Azure/azure-functions-core-tools#1630]
I've the "latest" `azure-functions-core-tools@2.7.1724` installed in Windows 10 (as per NPM and NVM), I configure the launch settings for my functions projects in VS2019 like this:

`%ProgramW6432%\nodejs\node_modules\azure-functions-core-tools\bin\func.exe`

But as per the [releases page](https://github.com/Azure/azure-functions-core-tools/releases) this latest release references Azure Functions Runtime v2.0.12763 which is now obsolete (as it had a bug).

How do I get `func.exe` to run v2.0.12835 as found on the [host releases page](https://github.com/Azure/azure-functions-host/releases)?

I feel as this should be plainly obvious and documented _somewhere_, but can't I seem to find an answer.

Thanks!

**Comment by ankitkumarr** [comment]
@t-l-k, we will release `azure-functions-core-tools` with the new runtime later this week. The `2.0.12835` Azure Functions Runtime has not be rolled out to all Azure Functions environment in Azure. Once that is complete (mid-week), we should be releasing a version of `azure-functions-core-tools` as well.

**Comment by t-l-k** [comment]
That's unfortunate. Guess I'lI downgrade my tools the to earlier version 2.7.1704 targeting Azure Functions Runtime v2.0.12742 to see if that fixes my issues.

**Comment by ankitkumarr** [comment]
@t-l-k, out of curiosity, what issue were you seeing in that version? Perhaps I could figure out and suggest some sort of a work around.

**Comment by t-l-k** [comment]
Sure, we're experiencing a multitude of issues of the following flavour:

https://github.com/Azure/azure-functions-host/issues/4914 <-- my original issue, with a repro
https://github.com/Azure/azure-functions-host/issues/5074
https://github.com/Azure/azure-functions-host/issues/5034
https://github.com/Azure/azure-functions-host/issues/5060 <-- very concerning to me
https://github.com/Azure/azure-functions-host/issues/3792
https://github.com/Azure/azure-functions-host/issues/4989
https://github.com/Azure/azure-functions-host/issues/3399

I wanted to try my repro for dependency injection container problems on the very latest runtime to see if anything had been resolved about it. There has been a lot of problems/churn in this area as evidenced by those tickets above. 

I'm actively getting `DryIoc.ContainerException : Scope disposed{no name, Parent=disposed{no name, Parent=disposed{no name}}} is disposed and scoped instances are disposed and no longer available` issues in `func.exe` running `v2.0.12763`, hence my desire to upgrade it and experiment.

It may relate appears to "improper" use of **typed clients** - although @fabiocav has yet to reply to my concern https://github.com/Azure/azure-functions-host/issues/5060#issuecomment-546690765

**Comment by fabiocav** [comment]
@t-l-k  apologies for the delayed response on that issue. I’ve been unavailable for the past few days and unable to answer. The summary above is really helpful. Availability is still somewhat limited but I just wanted to provide an update. I’ll comment there ASAP.

Can you confirm once you have the ability to test on latest?

**Comment by t-l-k** [comment]
@ankitkumarr 

> @t-l-k, we will release `azure-functions-core-tools` with the new runtime later this week. The `2.0.12835` Azure Functions Runtime has not be rolled out to all Azure Functions environment in Azure. Once that is complete (mid-week), we should be releasing a version of `azure-functions-core-tools` as well.

I'm confused, I can see the core tools release on this repo for `v2.7.1812`, targetting functions runtime  `v2.0.12850`, but the package is not yet updated on NPM? I normally use NPM to manage this tool, is it not pushed automatically to NPM? _can it be pushed?_

**Comment by ankitkumarr** [comment]
We usually cut the release in Github, update our CDNs and what not and then release it to the package managers (such as NPM) after. So it can take some time for the package to be available in NPM after the release shows in Github.

It should be updated everywhere now. Apologies for the delay.
