### ISSUE TITLE
Bug running with latest NET Core SDK 3.1.100-Preview2-014569 - Version 2.2.0 was not found

### ISSUE THREAD

**Issue by MrDRamos** [Azure/azure-functions-core-tools#1647]
Installed the latest: NET Core SDK 3.1.100-Preview2-014569 and choco install azure-functions-core-tools ((Version 2.7.1846). Then when starting a Function-App you get an error:
   The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
Workaround: Edit version in file: C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\powershell\Microsoft.Azure.Functions.PowerShellWorker.runtimeconfig.json 
as follows: "version": "3.1.0-preview2.19525.6"

**Comment by ahmedelnably** [comment]
you will need to install the preview version of the tools as mentioned here
https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm
