### ISSUE TITLE
Getting Incompatible Node.js version message - ver 12.13 installed

### ISSUE THREAD

**Issue by pradeepsethi** [Azure/azure-functions-core-tools#1653]
Getting incompatible Node.js version message although I have version 12.13 installed which is LTS release. 
 
Error Message:
[error] Incompatible Node.js version. The version you are using is v12.13.0, but the runtime requires an LTS-covered major version (ex: 8.11.1 or 10.14.1). LTS-covered versions have an even major version number (8.x, 10.x, etc.) as per https://github.com/nodejs/Release#release-plan. For deployed code, change WEBSITE_NODE_DEFAULT_VERSION in App Settings. Locally, install or switch to a supported node version (make sure to quit and restart your code editor to pick up the changes).

**Comment by ahmedelnably** [comment]
cc/ @mhoeger

**Comment by SaqibS** [comment]
Blocked by this too

**Comment by mhoeger** [comment]
Note that this is being tracked here: https://github.com/Azure/azure-functions-nodejs-worker/issues/200

**Comment by ahmedelnably** [comment]
closing this as it is being tracked by Azure/azure-functions-nodejs-worker#200
