### ISSUE TITLE
Azure Functions Python error: Unhandled exception in function. Could not serialize original exception message.

### ISSUE THREAD

**Issue by emac11** [Azure/azure-functions-core-tools#1655]
I have developed several Azure Functions for Python before using VS Code without a problem, but my last one has a bug that I can't get around. It is an Http Trigger function, and when I try to test it, as soon as I send a request, I get this error: 

 Executed 'Functions.HttpTrigger' (Failed, Id=214972fd-ff68-4dec-8fdb-5b5d4ee7326f)
[11/5/2019 6:23:36 PM] System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger. System.Private.CoreLib: Result: Failure
Exception: Unhandled exception in function. Could not serialize original exception message.
Stack:   File "C:\Users\serverAdmin\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\deps\azure_functions_worker\dispatcher.py", line 310, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)

I have tried uninstalling and reinstalling the Azure Functions extension and the Azure Functions Core Tools in VS Code, but it has not made a difference. Can anyone please help me?

**Comment by ankitkumarr** [comment]
+ @maiqbal11 / @Hazhzeng

**Comment by emac11** [comment]
I fixed it, it was a bug in my code and I thought it was something with Azure Functions Core Tools. The error message was misleading but it was definitely my bug.
