### ISSUE TITLE
Cannot profile function app

### ISSUE THREAD

**Issue by ptzbguenter** [Azure/azure-functions-core-tools#1661]
I have a dotnet function app that I'm trying to profile for performance. Why is it that I cannot see the `func.exe` using dottrace? Is there a known reason for this?

**Comment by ahmelsayed** [comment]
When I try dotTrace 2019.2.3 I see this notification

![image](https://user-images.githubusercontent.com/645740/68998016-a4ebfb00-0861-11ea-94bc-06b02a1c9a69.png)


Current `func.exe` is dotnet core 2.2. When I try the preview 3.0 build ([here](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.1740)) it shows up in the list

![image](https://user-images.githubusercontent.com/645740/68998034-e2508880-0861-11ea-80bb-2fe08e984465.png)

**Comment by ptzbguenter** [comment]
Ack! You are totally right, I don't know how I missed that. Thanks so much!
