### ISSUE TITLE
Azure function startup derived from FunctionsStartup fails due to the following error: The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-functions-core-tools#1662]
We used VS 2019 Version 16.4.0 Preview 5.0 with dotnet core 3.1.100-preview3-014645 to create a simple Queue-triggered function. We failed to progress further due to the following error message:

> [2019-11-16 7:07:42 PM] Reading functions metadata
> [2019-11-16 7:07:42 PM] 1 functions found
> [2019-11-16 7:07:42 PM] Loading startup extension 'Startup'
> [2019-11-16 7:07:42 PM] Loaded extension 'Startup' (1.0.0.0)
> [2019-11-16 7:07:42 PM] Loading startup extension 'AzureStorage'
> [2019-11-16 7:07:42 PM] Loaded extension 'AzureStorage' (3.0.10.0)
> [2019-11-16 7:07:42 PM] A host error has occurred during startup operation 'fa50563c-55cd-4fdc-88be-108c79346c64'.
> [2019-11-16 7:07:42 PM] FunctionApp1: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.

[I created a github repo right here](https://github.com/Arash-Sabet/FunctionApp1) to be able to exhibit the problem. Would you please let us know what the solution or workaround is? Thanks.

/cc @miladghafoori @jeffhollan

**Comment by jeffhollan** [comment]
Thank you for providing a sample! First thing that jumps out is you are targeting 3.1. Our bits right now are targeting 3.0 and not sure if 3.1 would be supported or work until we do some more work

**Comment by Arash-Sabet** [comment]
@jeffhollan 
Yes I am targeting 3.1. so should I downgrade it to make it work? Hope this sample helps something in 3.1.

Thanks for the reply though.

@miladghafoori

**Comment by Arash-Sabet** [comment]
@jeffhollan 
I made the necessary changes in the project files and pushed them to the repo. Unfortunately, the problem still persists in 3.0. I tried it in both VS 2019 Preview and non-Preview. It's a roadblock.

/cc @miladghafoori

**Comment by Arash-Sabet** [comment]
@jeffhollan Just wondering, any ETA on when will this issue be addressed in .net core 3.0?
/cc @miladghafoori

**Comment by Arash-Sabet** [comment]
We can close this ticket because there was a misconfiguration in the function's csproj file that I fixed it per the following snippet:

```xml
<AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
```

[The history of the change can be found in the repo](https://github.com/Arash-Sabet/FunctionApp1). The V3 function works fine in .net core preview 3.1.

/cc @miladghafoori
