### ISSUE TITLE
Support Windows ARM64

### ISSUE THREAD

**Issue by wisesimpson** [Azure/azure-functions-core-tools#1680]
I just got Surface Pro X. It's a nice device except it's win-arm64 so I can't run Azure Functions Core Tools on it.
I wish I can develop Azure Functions on this beautiful device. Also there're other win-arm64 based devices out there.

**Comment by ahmelsayed** [comment]
We could investigate this for V3 if we plan on replacing our GRPC dependency to the grpc-dotnet rather than the native GRPC implementation we're using for V2. 

Otherwise we will have to maintain our own GRPC build for Windows ARM64, which I would rather completely avoid. However this will only work to enable dotnet functions.

**Comment by wisesimpson** [comment]
@ahmelsayed I'm using JavaScript. How long should I expect for the support?

**Comment by ankitkumarr** [comment]
@ahmelsayed, we are planning on migrating to the new gRPC library -- https://github.com/Azure/azure-functions-host/issues/5237

But I am not sure if that'd be enough. As all the language workers (node, python, etc) also use gRPC and may not have language native implementation.

**Comment by ahmelsayed** [comment]
It won't be enough. We will have to maintain our own build pipeline for grpc modules for language workers for Windows ARM64, which will not be easy. If we enable ARM it'll be for dotnet only

**Comment by ankitkumarr** [comment]
Ah! Sorry, I missed the part where you said - "However this will only work to enable dotnet functions". Thanks, makes sense.

@wisesimpson, I don't think we have a timeline at the moment for JavaScript functions.

**Comment by wisesimpson** [comment]
As a temporary solution can we install the x86 instead of x64? At least x86 version can be run in emulator.

Currently if I run `npm i -g azure-functions-core-tools --unsafe-perm true` on Surface Pro X, I got

`attempting to GET "https://functionscdn.azureedge.net/public/2.7.1948/Azure.Functions.Cli.win-x64.2.7.1948.zip"
[==================] Downloading Azure Functions Core Tools`

Why is the x64 version chosen for arm64 system?

**Comment by ahmedelnably** [comment]
Closing this, as we are blocked on node support on Windows ARM64, will revisit this once the blockers are resolved

**Comment by wisesimpson** [comment]
@ahmedelnably Actually node is not a show stopper here. I can get the "unofficial" build from their official website and runs smoothly.
https://unofficial-builds.nodejs.org/download/release/v12.13.1/

Can you consider at least loading the x86 instead of x64 version for Windows ARM64? I assume this fix won't take much developing time. Then at least we can try to run it through emulator.

Thanks

**Comment by michaelpeng36** [comment]
Reopening this issue to track work underway to support `win-arm64`: #3116

**Comment by mattchenderson** [comment]
Cleaning up an old item - this seems to have been resolved by the PR linked above having been closed.
