### ISSUE TITLE
Worker selection in CLI during function app creation

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-core-tools#1681]
The experience on Mac is picking a number for worker runtime, whereas on Windows is to use arrow keys. We can make it consistent across OS and/or clear. Eg. Instead of "Select a worker runtime" in Mac, we can say "Select a number for worker runtime". and similarly explicitly mention to use arrow keys to pick a runtime in Windows.

**Comment by ahmedelnably** [comment]
@kulkarnisonia16 thanks for the suggestion, we will be looking at it for a future milestone

**Comment by fabiocav** [comment]
@kulkarnisonia16 can you please provide the exact message you'd like to see on Windows?

**Comment by kulkarnisonia16** [comment]
@fabiocav @gzuber - "Use the up/down arrow keys to select a worker runtime"
