### ISSUE TITLE
Adding files to zip

### ISSUE THREAD

**Issue by arjo129** [Azure/azure-functions-core-tools#1685]
Hi, I'm trying to republish a function. Previously when I used azure to publish a function, all files including non-python json files (which used to be used as config files) would be packaged in the docker image. Now this doesn't happen anymore.

**Comment by ahmelsayed** [comment]
can you share the command you're using

**Comment by arjo129** [comment]
Hi,
Command I'm using is:
`func publish <FUNCTION_NAME> --build-deps-native`
The function in question is hosted here:
https://github.com/arjo129/LangCluster/tree/master/LangClusterBackend

**Comment by ankitkumarr** [comment]
Is there a `.funcignore` file in your function app project directory? If so, would you mind sharing the contents of that file.

**Comment by Hazhzeng** [comment]
Hey @arjo129,

I assume you're using `func azure functionapp publish <FUNCTION_NAME> --build-native-deps`.
I just tried publishing with the core tools (v2.7.1948) and it seems the package is complete.
https://cloudbuildlinux.blob.core.windows.net/function-releases/20191210201504-644668c3-94a3-40c9-bab9-c6417a1981e3.squashfs?sv=2018-03-28&sr=b&sig=aVQrdeTyPe2S08CGDfO3yBikkBEGeHNWg81rZJzcURk%3D&st=2019-12-10T20%3A11%3A14Z&se=2029-12-10T20%3A16%3A14Z&sp=r

One thing you may help us diagnose this issue, please go to your function app, check the app setting, and try downloading the file from the link in WEBSITE_RUN_FROM_PACKAGE. You may need **7zip** to inspect the package content.
