### ISSUE TITLE
Surface remote build logs

### ISSUE THREAD

**Issue by kulkarnisonia16** [Azure/azure-functions-core-tools#1694]

**Comment by Hazhzeng** [comment]
@ankitkumarr can refer to https://github.com/Azure/azure-functions-core-tools/blob/dab8daca606d1a6f398b01b6f29ce8f081c34ec9/src/Azure.Functions.Cli/Helpers/KuduLiteDeploymentHelpers.cs#L101 for Linux Consumption remote build log streaming

**Comment by Hazhzeng** [comment]
This is already done on March 3, 2020. Closing this issue.
