### ISSUE TITLE
Add latest project templates from template repository

### ISSUE THREAD

**Issue by maartenba** [Azure/azure-functions-core-tools#1699]
For some reason it looks like templates shipped are not the latest ones from https://github.com/Azure/azure-functions-templates/.

Missing the following PR contents in the latest binaries for core tools: https://github.com/Azure/azure-functions-templates/pull/891

**Comment by ahmedelnably** [comment]
cc/ @soninaren

**Comment by maartenba** [comment]
Looks like this was shipped?

**Comment by soninaren** [comment]
Yes, this has been shipped. Core tools should now be referring the latest templates.
