### ISSUE TITLE
Latest release on GitHub does not list any binary assets?

### ISSUE THREAD

**Issue by maartenba** [Azure/azure-functions-core-tools#1704]
Similar to #1471, but for [`3.0.1975`](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.1975).

The latest release is missing the compiled binaries, and only contains the source.

**Comment by maartenba** [comment]
@soninaren

**Comment by yojagad** [comment]
Please find the binaries here 
https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.1975
