### ISSUE TITLE
Tag 3.0.2 as latest on node package repository

### ISSUE THREAD

**Issue by nojaf** [Azure/azure-functions-core-tools#1717]
Both [npmjs.com](https://www.npmjs.com/package/azure-functions-core-tools) and [yarnpkg.com](https://yarnpkg.com/en/package/azure-functions-core-tools) list the 2.x version as the latest.
Please update this.

![image](https://user-images.githubusercontent.com/2621499/70863813-4b541a80-1f4c-11ea-8fc4-5600a80bd284.png)

![image](https://user-images.githubusercontent.com/2621499/70863818-58710980-1f4c-11ea-9bd8-3d36090173ae.png)

**Comment by ahmedelnably** [comment]
This is by design, we are going to switch the latest version to v3 early next year.
