### ISSUE TITLE
Func extensions install broken with dotnet v3.1

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-functions-core-tools#1741]
### Environment:
OS Name:     Windows
OS Version:  10.0.18363
Function core tools: 2.7.1948
Dotnet: .NET Core SDK 3.1.100

### Description
Command `func extensions install` will failed with dotnet 3.1, changed to dotnet 2.* and it works well

### Error messages

C:\Users\hanli\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.0\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(20,5): error : Metadata generation failed. Exit code: '-2147450730' Output: '' Error: 'It was not possible to find any compatible framework versionThe framework 'Microsoft.NETCore.App', version '2.0.0' was not found.  - The following frameworks were found:      3.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]You can resolve the problem by installing the specified framework and/or SDK.The specified framework can be found at:  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=win10-x64' [D:\test\test6\extensions.csproj]

### function.json
```
{
  "scriptFile" : "../harryfunc01-1.0-SNAPSHOT.jar",
  "entryPoint" : "com.Harryqueue.run",
  "bindings" : [ {
    "type" : "queueTrigger",
    "direction" : "in",
    "name" : "message",
    "queueName" : "myqueue-items",
    "connection" : "AzureWebJobsStorage"
  } ]
}
```

**Comment by ahmedelnably** [comment]
@soninaren to comment

**Comment by fabiocav** [comment]
@soninaren can you please take a look here?

**Comment by soninaren** [comment]
Have added a  PR fixing this issue.
