### ISSUE TITLE
Latest release on GitHub does not list any binary assets?

### ISSUE THREAD

**Issue by maartenba** [Azure/azure-functions-core-tools#1744]
Similar to #1704 and #1471, but for [`3.0.2009`](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2009)

The latest release is missing the compiled binaries, and only contains the source.

Could this be added as part of the release steps to ensure the binaries are present for future releases?

**Comment by ankitkumarr** [comment]
Sorry about that. That one's on me. I just added them.

We have automated most of the release process and should always have binaries attached. This was an ad-hoc release and I forgot to add the binaries.

**Comment by maartenba** [comment]
Thanks @ankitkumarr ! 🤗
