### ISSUE TITLE
STOP AUTO-COLLECTING TELEMETRY --OPT IN NOT OUT

### ISSUE THREAD

**Issue by JacksReacher** [Azure/azure-functions-core-tools#1747]
Get a fricken clue.

**Comment by dariagrigoriu** [comment]
We will look into options.

**Comment by apawast** [comment]
Closing this issue as there is a way to opt-out of telemetry collection: [https://github.com/Azure/azure-functions-core-tools#telemetry](https://github.com/Azure/azure-functions-core-tools#telemetry)
