### ISSUE TITLE
Azure Functions Host with http/2

### ISSUE THREAD

**Issue by OneCyrus** [Azure/azure-functions-core-tools#1752]
how can I run a function host locally with http/2 support? I would like to develop, test and run it OnPremise in http/2 mode. In the Portal we have the option to switch but I couldn't find a way with the core tools.

![image](https://user-images.githubusercontent.com/7747800/72070749-8dbe0c80-32ea-11ea-9371-62e91168e4e5.png)

**Comment by ahmelsayed** [comment]
I think the behavior might potentially be different from that on Azure. On Azure there is a reverse proxy that sits in front of the application that will always fallback to http1.1 for the upstream, as far as I know.

I do think it's still worth adding to the core-tools for local scenarios though.

**Comment by fabiocav** [comment]
Closing as answered, but let us know if you need more information.
