### ISSUE TITLE
Visual Studio automatic installation

### ISSUE THREAD

**Issue by Camios** [Azure/azure-functions-core-tools#1755]
When attempting to locally debug my Azure Function in Visual Studio, Visual studio shows a dailog that it is installing the Azure Functions CLI (i.e. Azure Functions core tools).

I'm behind a corporate proxy which appears to block the download (to some degree) and this process locks up Visual Studio (shows "not responding" in title).

We got around this by using a different network path, but somehow ended up with corruption?:
[8/01/2020 5:07:38 AM] A host error has occurred
[8/01/2020 5:07:38 AM] Microsoft.Azure.WebJobs.ServiceBus: Could not load type 'Microsoft.Azure.WebJobs.Host.Scale.IScaleMonitorProvider' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 

I didn't know how to fix this corruption and google search didn't come up with anything useful.
I deleted the solution directory, cloned from source and tried debugging again. I think the download ran again, succeeded and I was able to locally debug the Azure function this time successfully.

My colleagues are going to run into the same problem and we'd like some understanding of how to clean up corrupted installs/configs. 

Most importantly I'd also like to force Visual Studio to force the reinstall of Azure Functions Core tools (CLI) so the network team can whitelist. How can I do this?
I tried cloning the source to a different folder to see if it downloads on a per-solution/project basis, but Visual Studio thinks it is already installed (doesn't retry).

e.g. can I do uninstall/remove?
Where does Visual Studio install the Azure Functions CLI (core tools)? 
Is a package manager used by Visual Studio?

**Comment by Camios** [comment]
I downloaded the zip release and did a file search on my drive and located this folder: C:\Users\<username>\AppData\Local\AzureFunctionsTools\Releases\2.43.0\cli_x64

Would deleting this force Visual Studio to attempt to redownload/reinstall?

Also how does Visual Studio (or should I) update the tools to a new version?

**Comment by Camios** [comment]
Other than the download/install of core tools having a bad threading design which locks up Visual Studio's UI, I think I'm OK.

**Comment by fabiocav** [comment]
@soninaren can you please share instructions on manual Core Tools installation for VS?

We'll also follow up with the VS team to properly handle the scenario.

**Comment by fabiocav** [comment]
@Camios can you confirm you got the information you needed?

**Comment by Camios** [comment]
@fabiocav hmm sort of, the workaround suggested [here](https://github.com/Azure/azure-functions-core-tools/issues/1872#issuecomment-601541602) [direct SO link](https://stackoverflow.com/questions/58658348/visual-studio-2019-re-downloads-azure-function-cli-tools), does help. However why is this problem happening? Is tool which downloads the cli tools not using the system proxy or not reporting proxy problem properly? Can this be looked into please?

**Comment by soninaren** [comment]
@vijayrkn is it somehow possible for VS to use system proxy?

**Comment by apawast** [comment]
@Camios are you still experiencing this issue?
