### ISSUE TITLE
Failed to install core tools using homebrew on Mac

### ISSUE THREAD

**Issue by akaroml** [Azure/azure-functions-core-tools#1757]
Please see the logs below:

account@machine ~ `brew tap azure/functions`

account@machine ~ `brew install azure-functions-core-tools@2`

Error: No available formula with the name "azure-functions-core-tools@2" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by michael-watson** [comment]
see https://github.com/Azure/azure-functions-core-tools/issues/1769

**Comment by akaroml** [comment]
Thanks for the info. @michael-watson 

I tried `brew search azure-functions`, and seems v2 is no longer available.
Then someone needs to remove the v2 related contents from https://github.com/Azure/azure-functions-core-tools/blob/dev/README.md

**Comment by ankitkumarr** [comment]
Hi, this should be working now. We never really had `azure-functions-core-tools@2`. `azure-functions-core-tools` by default was v2 and there was `azure-functions-core-tools@3`.

We updated the documentation before actually releasing `azure-functions-core-tools@2` tag. However, this should be resolved now. Sorry about that.
