### ISSUE TITLE
Linux package repositories wildly out of date

### ISSUE THREAD

**Issue by jonny-powell** [Azure/azure-functions-core-tools#1758]
Can you please please update them.

**Comment by benc-uk** [comment]
Agreed. Ubuntu packages still at `2.7.1948-1`  😥
I want to upgrade to v3 without needing to manually get the zip, extract and mess with my PATH

**Comment by fabiocav** [comment]
Assigning this to the next sprint so we can have someone work with @ahmelsayed to add this step as part of the release flow.

**Comment by fabiocav** [comment]
@ankitkumarr to follow up with @ahmelsayed on this.

**Comment by ankitkumarr** [comment]
Had a chat with Ahmed offline. We need to have a new package name for v3 such as `azure-functions-core-tools-v3` and then update our packaging script to account for that.

The package script should create a file `azure-functions-core-tools-v3_<version>.deb`, then we can use the release process that we have today to upload them to the appropriate servers.

**Comment by benc-uk** [comment]
Why a different name? What happens when v4 or v5 comes out? Seems like you'll have a sprawl of packages and will confuse people

**Comment by ahmelsayed** [comment]
That's the only way to do proper versioning with breaking changes since .net has one every year.

**Comment by fabiocav** [comment]
@ahmelsayed is there a separate issue tracking this? Trying to understand if we should close this and assign the work in the proper repo.

**Comment by ahmelsayed** [comment]
I don't see any issues. @ankitkumarr is driving this as far as I know, right @ankitkumarr?

**Comment by ankitkumarr** [comment]
Sorry, I missed your ping earlier. I can get a PR for this today. Hadn't had a chance to prioritize this. But this should be quick, and seems to be a P1.

**Comment by ankitkumarr** [comment]
I have released `azure-functions-core-tools-3`. You should be able to try it. I am leaving this open as I need to add this to our Readme, and update the release pipelines to continue releasing this package.

**Comment by ankitkumarr** [comment]
Readme is updated. I am closing this. Linux packages should be up to date now.

Tracking item for enhancing release pipeline: https://github.com/Azure/azure-functions-core-tools/issues/1859

**Comment by jonny-powell** [comment]
Debian Buster has been left out in the cold here, is there any particular reason for this?

**Comment by ahmelsayed** [comment]
the `https://packages.microsoft.com/debian/10/prod` sources should have the latest core-tools. I'll add it to the README today

```
# make sure you have gnupg2 and apt-transport-https
sudo apt update
sudo apt install wget gnupg2 apt-transport-https

# add buster sources
echo "deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main" >> /etc/apt/sources.list

# add gpg key
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg

sudo apt update
sudo apt install azure-functions-core-tools
```

**Comment by jonny-powell** [comment]
Agreed, however it does not have azure-functions-core-tools-3.

**Comment by ankitkumarr** [comment]
@jonny-powell, we updated it recently. It should have `azure-functions-core-tools-3` now.

**Comment by jonny-powell** [comment]
Excellent, thanks!
