### ISSUE TITLE
TS project gets JS package.json

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-core-tools#1761]
We've had a report that on func create, a package.json for a JS project was found instead of the correct TS one. Need to investigate how, but a TS project should always get the right TS-specific package.json!

**Comment by dariagrigoriu** [comment]
@mhoeger is there a repro to reference for this issue?

**Comment by mhoeger** [comment]
@christopheranderson - I know this was during a hackathon, but do you have a repro or potential repro steps?

**Comment by fabiocav** [comment]
Closing this until we have more information to make it actionable.
