### ISSUE TITLE
Keda / Kubernetes deployment broken?

### ISSUE THREAD

**Issue by sebader** [Azure/azure-functions-core-tools#1765]
I just tried to deploy Function on Kubernetes (AKS) using [this ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda)tutorial with the Core Tools (2.7.1948).

All looks ok in the beginning and also my Function gets deployed and is running. However, the Keda pod itself does not run - and I assume without that one running the whole scale logic etc. is not really working?! In the log I can see, that it complains about invalid arg flags .You see --log-level in the screenshot. But if I change that one manually to --zap-level, the next error is about --secure-port. I assume something is wrong with the deployment that the Core Tools create?!
![image](https://user-images.githubusercontent.com/11445087/72598237-b314d100-390f-11ea-94fe-f9a975607fdc.png)

So, did anybody recently try to run this?

![image](https://user-images.githubusercontent.com/11445087/72598398-0a1aa600-3910-11ea-8b26-341fc2d4fe75.png)

**Comment by jxmoore** [comment]
I'm also having the same issue, it was previously working but when the container was redeployed it got hung up in this state. I have tried using different versions other than the latest but no luck yet. 

console output is identicle to the above : 
```
unknown flag: --log-level
unknown flag: --log-level
Usage of /usr/local/bin/keda:
      --kubeconfig string                Paths to a kubeconfig. Only required if out-of-cluster.
      --master --kubeconfig              (Deprecated: switch to --kubeconfig) The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
      --zap-devel                        Enable zap development mode (changes defaults to console encoder, debug log level, and disables sampling)
      --zap-encoder encoder              Zap log encoding ('json' or 'console')
      --zap-level level                  Zap log level (one of 'debug', 'info', 'error' or any integer value > 0) (default info)
      --zap-sample sample                Enable zap log sampling. Sampling will be disabled for integer log levels > 1
      --zap-time-encoding timeEncoding   Sets the zap time format ('epoch', 'millis', 'nano', or 'iso8601') (default )
```

has anyone gotten around this?
