### ISSUE TITLE
Function publish fails on newly created function app

### ISSUE THREAD

**Issue by mcopik** [Azure/azure-functions-core-tools#1766]
Hi!

When I try deployment to a new function app, immediately after creating it, the command `func azure functionapp publish ${NAME} --python --no-build` fails with an error stating that function app with provided name was not found. Curiously enough, the function app is visible in my storage account and I can publish the function after my script fails. Through trial and error I found out that ~30 second sleep between function app creation and publish is sufficient to ensure correct 

This seems like a race condition where for some reason the newly created resource is not always available after creation. To add a new function app, I'm using `az functionapp create`.

azure-cli: 2.0.80
azure-functions-core-tools: 2.7.1948
OS: Docker instance based on Debian 9.11.

**Comment by Erikvl87** [comment]
Is this related to my issue? https://github.com/Azure/azure-functions-core-tools/issues/1616

**Comment by mcopik** [comment]
@Erikvl87 Sounds about right. Recently I discovered that even 30 seconds sleep is not sufficient. Catching a failed command and repeating until success seems to be the only viable solution.

**Comment by andrew-velez-trusight** [comment]
Any update on this? While I can sleep for 30 seconds, that's a hack at best.

**Comment by balag0** [comment]
@mcopik Could you explain what you meant by function app is visible in storage account? Trying to understand how that is different from the publish workflow.

**Comment by Erikvl87** [comment]
I am still waiting for a solution as well since I haven't really got a satisfying answer to https://github.com/Azure/azure-functions-core-tools/issues/1616.

@balag0 My assumption would be (since that was the case for me) that the app is created properly (and thus can be seen in his Azure account). But since the caching mechanisms in ARM [are not yet up to date](https://github.com/Azure/azure-functions-core-tools/issues/1616#issuecomment-546036487), publishing fails, even though `func azure functionapp publish` returns `state: running` .

**Comment by mcopik** [comment]
@balag0 

These are the steps that I'm attempting. I'm running

```
az functionapp create --resource-group {resource_group} --os-type Linux --consumption-plan-location {region} --runtime {runtime} --runtime-version {runtime_version} --name {func_name} --storage-account {storage_account}
```

Then I'm doing:

```
func azure functionapp publish {name} --{language} --no-build
```

Which usually returns the error I mentioned in my first message. When I open the storage account associated with the function, I can find there a single container "scm-releases". When the publish operation succeeds, I see there three additional containers ("function-releases", "azure-webjobs-secrets", "azure-webjobs-hosts").

**Comment by apawast** [comment]
@mcopik are you still experiencing this issue?
