### ISSUE TITLE
Fail to install v2 of azure functions core tools on Mac

### ISSUE THREAD

**Issue by v-dantch** [Azure/azure-functions-core-tools#1769]
**OS**: Mac

**Repro Step:**
Install Azure Functions Core tools by "brew install azure-functions-core-tools@2".

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/72715992-76193a80-3bac-11ea-9869-dac0168875ec.png)

**Comment by andxu** [comment]
`brew install azure-functions-core-tools` to install version 2

**Comment by v-dantch** [comment]
@andxu , thanks a lot for your share. Now we can succeed to install the v2 of func. And we will close this bug.

**Comment by akaroml** [comment]
I tried `brew search azure-functions`, and seems v2 is no longer available.
Please remove the v2 related contents from https://github.com/Azure/azure-functions-core-tools/blob/dev/README.md
