### ISSUE TITLE
Error when trying to publish to v3 runtime

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-functions-core-tools#1770]
## Repro steps:
1) In Visual Studio Code, create a new function app with a JavaScript HTTP trigger.
2) Create a function app with the v3 runtime.  I use a Terraform template for this with `version = "~3"`
3) Verify (through Azure Portal) that the function app is actually v3 runtime.
4) `npm install --save-dev azure-functions-core-tools`
5) `node_modules/.bin/func azure functionapp publish appname`

## Expected:
The app is published.

## Actual:
Error message:

```
You're trying to publish to a v1 function app from v2 tooling.
You can pass --force to force update the app to v2, or downgrade to v1 tooling for publishing
```

## Dependencies:
`azure-functions-core-tools: 2.7.1948`

Node: 12.14.1
Attempted on Windows 10 build 19041 and MacOS Catalina 10.15.2

## Workaround
`func azure functionapp publish appname --force --javascript`

Once this is done, the regular publish command works just fine.  However, this downgrades the functionapp to v2 runtime.  (as a result, I'm using the v2 runtime right now)

**Comment by dariagrigoriu** [comment]
This looks like an issue with the error message which should be addressed. There is a tooling version mismatch, please see instructions for installing v3 here: https://github.com/Azure/azure-functions-core-tools/blob/dev/README.md.

**Comment by RufusJWB** [comment]
I have the same issue here. Is there a way to install the v3 version of the function core tools with chocolatey? The documentation only describes a way with NPM.

**Comment by anthonychu** [comment]
PR #1852 thanks @ankitkumarr
