### ISSUE TITLE
'func new' creates new project with encrypted setting

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#1771]
Repro:

1. Run `func new` without first running `func init`
1. Select any language and the default values.
1. View the local.settings.json file.

Issues:
+ `func new` succeeds without first calling `func init`.
+ Not all supported languages are shown as options, as they are in `func init`.
+ The `FUNCTIONS_WORKER_RUNTIME` value in local.settings.json is set to an encrypted value locally.

**Comment by khkh-ms** [comment]
It is probably already resolved.
