### ISSUE TITLE
Checksums for Azure.Functions.Cli.linux-x64.2.7.1948.zip don't match up and can't unzip file

### ISSUE THREAD

**Issue by ccwilkins** [Azure/azure-functions-core-tools#1774]
Recently went to upgrade to 2.7.1948 for Linux. That said, when docker went to unzip the contents it failed and indicated that the files had additional bytes. Ended up running sha2 against the file and compared to what is in the .sha2 file you provide. Things don't appear to match up. Checked the previous version and they do match up. It also looks like the style of the file has changed so not sure if I'm doing something wrong. Either way, can't seem to be able to fully unzip the contents of 2.7.1948 for linux.

Please advise.

File was downloaded from:
https://github.com/Azure/azure-functions-core-tools/releases/download/2.7.1948/Azure.Functions.Cli.linux-x64.2.7.1948.zip

Checksum downloaded from:
https://github.com/Azure/azure-functions-core-tools/releases/download/2.7.1948/Azure.Functions.Cli.linux-x64.2.7.1948.zip.sha2

I'm also curious what tool you guys are using to check these checksums.

**Comment by ahmelsayed** [comment]
It looks like the automation that was uploading the files to github screwed up somehow? It looks like all the files in that release are corrupted. @yojagad, @soninaren were there changes in that automation between that release and the current one?

@ccwilkins to answer your question, the sha2 is calculated here during build. It's using .NET's `System.Security.Cryptography.SHA256Managed` and be just the sha2 in the file.

**Comment by yojagad** [comment]
I updated the release with the correct files. You should be able to use the access those files now.

**Comment by ccwilkins** [comment]
Hi Ahmed,

Does this mean that the versions on apt-get are corrupt as well?

**Comment by ankitkumarr** [comment]
@ccwilkins, no they should be fine. It was only the Github release with this issue.

@yojagad, is the automated upload issue resolved, if so I will close this issue.

**Comment by yojagad** [comment]
Yeah, that's resolved. You can close this issue
