### ISSUE TITLE
Func init needs add a version (6 or 7) entry for the PowerShell function apps

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-core-tools#1787]
Func init needs add a version (6 or 7) entry for the PowerShell function apps

**Comment by Francisco-Gamino** [comment]
Func init needs add a version (6 or 7) entry for the PowerShell function apps.

cc: @anirudhgarg, @eamonoreilly, @AnatoliB

**Comment by eamonoreilly** [comment]
The core tools should add an entry FUNCTIONS_WORKER_RUNTIME_VERSION as a local.settings.json value with a default ~7 during creation of the PowerShell app. If customers need to downgrade to ~6 for some reason, they can change the value manually.

**Comment by Francisco-Gamino** [comment]
cc: @ankitkumarr for FYI

**Comment by brettsam** [comment]
Is this a dupe of https://github.com/Azure/Azure-Functions/issues/1604?

**Comment by anthonychu** [comment]
This is for Core Tools to create a local project that either PS6 or PS7. https://github.com/Azure/Azure-Functions/issues/1604 is for the az cli to create a PS7 app.

**Comment by Francisco-Gamino** [comment]
Yes, it is. I have already implemented the code change, but I have not submitted a PR yet. This change has a dependency on the clients Portal, Az CLI, and Az.Functions cmdlets to have the ability to create a PowerShell 7.0 function app.

**Comment by Francisco-Gamino** [comment]
This has been fixed, closing issue.
