### ISSUE TITLE
[v3] func init created project with netcoreapp3.0 not netcoreapp3.1

### ISSUE THREAD

**Issue by jongio** [Azure/azure-functions-core-tools#1792]
Run:

`func init jgfn11 --csharp --worker-runtime dotnet`

Then:

`func new --name func1 --template "Http Trigger"`

And you get this in your csproj - shouldn't this be netcoreapp3.1? According to this: https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions

Also shouldn't this use the latest version of the Sdk.Functions SDK, which is 3.0.3.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

```
C:\blog\jgfn11>func --version
3.0.2106

C:\blog\jgfn11>dotnet --version
3.1.101

C:\blog\jgfn11>node --version
v12.13.0
```

**Comment by ahmelsayed** [comment]
@soninaren can you update the v3 templates in this repo?

**Comment by soninaren** [comment]
Sure, will update the templates in the repo.

**Comment by gzuber** [comment]
Templates have been released, so this should be fixed in the next release. Thanks for letting us know!

**Comment by jongio** [comment]
@soninaren - I see that we are loading templates from CDN, i.e. https://functionscdn.azureedge.net/public/TemplatesApi/2.0.10344.zip

But I don't see a ref to netcoreapp in the templates.json file.

Is that file open sourced?

Do you have a link to the commit to show that it has been updated?

**Comment by soninaren** [comment]
@jongio, The file is hosted over here and it is open source. https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/ProjectTemplate/CSharp

We already have published a project template target netcoreApp3.1,  https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ProjectTemplates/3.1.1518. 

We are in the process releasing https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2245 that references the new project template. The release should complete before end of this week.

**Comment by jongio** [comment]
Great.  Thanks. I will verify later this week.

**Comment by jongio** [comment]
Thanks you @soniaang  and @gzuber  - I have verified that template is now netcoreapp3.1 and Microsoft.NET.SDK.Functions is 3.0.3

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Version 3.0.2245
