### ISSUE TITLE
Azure.Functions.Cli.osx-x64.3.0.2106 breaks publish with permission denied

### ISSUE THREAD

**Issue by bboh** [Azure/azure-functions-core-tools#1793]
The orignal upgrade was through homebrew. Then I verified with manual donwloads:
`wget https://functionscdn.azureedge.net/public/3.0.2009/Azure.Functions.Cli.osx-x64.3.0.2009.zip`
`wget https://functionscdn.azureedge.net/public/3.0.2106/Azure.Functions.Cli.osx-x64.3.0.2106.zip`

```
(master *) MacBook-Pro:sample xyz$ ~/Azure.Functions.Cli.osx-x64.3.0.2106/func azure functionapp publish sample-3-0-2160
Getting site publishing info...
Creating archive for current directory...
Creating archive for current directory...
Creating archive for current directory...
Permission denied
```

```
(master *) MacBook-Pro:sample xyz$ ~/Azure.Functions.Cli.osx-x64.3.0.2009/func azure functionapp publish sample-3-0-2160
Getting site publishing info...
Creating archive for current directory...
Uploading 1.32 KB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in sample-3-0-2160:
    HttpTrigger - [httpTrigger]`
```

**Comment by ankitkumarr** [comment]
Sorry about that, as soon as this is merged, your issue should be fixed -- https://github.com/Azure/homebrew-functions/pull/48

To mitigate, you can do something like `chmod a+x  /usr/local/Cellar/azure-functions-core-tools@3/3.0.2106/gozip`.

**Comment by bboh** [comment]
Thanks! For reference .. I didn't see a way to increase the verbosity of the func cli to file a better problem report. Is there a switch or env variable that I am missing?
