### ISSUE TITLE
Is dotnet still required or not?

### ISSUE THREAD

**Issue by ccwilkins** [Azure/azure-functions-core-tools#1794]
Currently in the latest Readme under known issues it indicates that dotnet is required in order to support extensions. However, if you click the requirements link it references (https://github.com/Azure/azure-functions-core-tools/issues/367) this particular piece of work is closed. It indicates that "extension bundles" now remove the need for dotnet. Can someone please clarify where we are at with this. If extension bundles remove the requirement for dotnet can you please clarify what that exactly is?

**Comment by soninaren** [comment]
@ccwilkins, Extension bundles does remove the requirement for dotnet for extension support. We have extension bundles documentation over here. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles

I am working on a wiki that explains extension bundle in more detail. Will add it to the repository as soon as it is ready.

**Comment by ccwilkins** [comment]
Thanks for the information. Look forward to the README updates. 

Is there an easy or automated way to switch from legacy extensions to extension bundles?

**Comment by anthonychu** [comment]
@ccwilkins Try these steps to switch an existing project to bundles. Ensure you've committed the current state of your project in git before starting in case you need to roll back:
1. Check that all extensions you are using are in [bundles](https://github.com/Azure/azure-functions-extension-bundles/blob/master/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json).
1. Delete the `bin` and `obj` folders. Delete the `extensions.csproj` file.
1. Modify your `host.json` file to include bundles:
    ```json
    {
        "version": "2.0",
        "extensionBundle": {
            "id": "Microsoft.Azure.Functions.ExtensionBundle",
            "version": "[1.*, 2.0.0)"
        }
    }
    ```
1. If using VS Code, there may be a reference to `extensions install` in your `.vscode/tasks.json` file. Remove it manually. Another option is to delete the `.vscode` folder and use the `Azure Functions: Initialize Project for Use with VS Code` command to regenerate it.

Test it to see if it works. If it does, it's safe to remove the .NET SDK from your machine.

As for why .NET was needed in the first place, triggers and bindings are installed into your function app as extensions. Extensions are .NET libraries that are distributed on NuGet. When you call `func extensions install`, behind the scenes `func` uses the .NET SDK to install the extension from NuGet. An artifact that's generated in the process is `extensions.csproj`; it's a .NET project file that keeps track of what extension packages you need so you can reinstall them (sort of the .NET equivalent of package.json in Node or requirements.txt in Python). When the packages are installed, `bin` and `obj` folders are created in your project.

The .NET SDK is only needed to install extensions; it is not required to run a function app. With extension bundles, we essentially take a set of commonly used extensions and put them in a zip file (a "bundle"). If `host.json` contains a reference to an extension bundle, we'll download it (the zip file) and use it.

As long as the extensions you require are in the bundle you reference, you don't need .NET. You also don't need the .NET artifacts (`extensions.csproj`, `bin`, `obj`). However, if you need to access an extension that isn't in a bundle (e.g., you need a version that's not in a bundle, you're using a custom extension, etc), you can't use bundles and need to go back to using `func extensions install` (and having the .NET SDK installed). You can't mix bundles with `extensions install`.

I'm sure @soninaren's wiki will provide a lot more details, including how bundles are versioned. But thought I'd give you a bit of context in the meantime.
