### ISSUE TITLE
Azure.Functions.Cli issue while using dependency injection in .NET Azure Functions

### ISSUE THREAD

**Issue by ThiruA1980** [Azure/azure-functions-core-tools#1806]
Trying out Azure.Functions.Cli.win-x64.2.0.1-beta.34 (downloaded from https://github.com/Azure/azure-functions-core-tools/releases?after=2.6.1064) to punch out Azurre function build for x64 platforms. 

Its working from for regular Azure function template but throwing run time exceptions when we incorporate dependency injection in .NET Azure Functions.

**Run time errors:**
_"A scripthost error occurred.
System.Private.CoreLib: Could not load type 'Microsoft.Azure.WebJobs.Hosting.IOptionsFormatter from assembly ''Microsoft.Azure.WebJobs.Host'"_

_P.S: dependency injection in .NET Azure Functions works as expected while we build project azure function using visual studio  tooling_

Any Suggestion?

**Comment by ThiruA1980** [comment]
Above issue encountered while trying with Azure function V2

**Comment by ThiruA1980** [comment]
Above issue encountered while trying with Azure function V2  with TargetFramework 'netstandard2.0' as well as 'netcoreapp2.1'

**Comment by Wyren** [comment]
I got this exception while opening the portal page of our function. We seem to be getting multiple type load exceptions in different regions for different types of resources. Might be related?

Error:

The function runtime is unable to start. Microsoft.Azure.WebJobs.ServiceBus: Could not load type 'Microsoft.Azure.ServiceBus.Management.ManagementClient' from assembly 'Microsoft.Azure.ServiceBus, Version=3.0.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c'.
Session Id: 2e81026ba0394a51bc98a6ade5013eba

Timestamp: 2020-02-06T12:51:41.539Z

**Comment by ThiruA1980** [comment]
Using Azure.Functions.Cli version 2.7.1724 resolved above issue

**Comment by ThiruA1980** [comment]
Using Azure.Functions.Cli version 2.7.1724 resolved above issue
