### ISSUE TITLE
Remote build failed!

### ISSUE THREAD

**Issue by SidBarker** [Azure/azure-functions-core-tools#1816]
Hi all,

I'am using core tools on my Azure DevOps agents. I got there several azure functions definitions, which are then build as artifact and used during release pipelines. 
Everything were working like a charm till last week when i realized that every try to build deploy new function finish with error like below:

```
2020-02-11T13:27:25.2799055Z Getting site publishing info...
2020-02-11T13:27:25.2917315Z Creating archive for current directory...
2020-02-11T13:27:25.2983088Z Performing remote build for functions project.
2020-02-11T13:27:26.6736767Z Uploading  []Remote build in progress, please waitdone
2020-02-11T13:27:26.6780277Z Remote build failed!
```

My definition of a stage which install core tools and publish function.
```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-get update

sudo apt-get install azure-functions-core-tools
func --version
```
Command used for publishing
```
func azure functionapp publish $(FunctionAppName) --python
```

**Comment by ankitkumarr** [comment]
@SidBarker, would you mind sharing your function app name and a time period when you saw the issue? We can take a look at our logs.
