### ISSUE TITLE
Install func tools task failing in Azure Devops pipeline

### ISSUE THREAD

**Issue by srini247** [Azure/azure-functions-core-tools#1817]
Hi - install func tools task is failing with the following error in the devops pipeline

##[error]Error: Failed to download func tools from location https://github.com/Azure/azure-functions-core-tools/releases/download/3.0.2106/Azure.Functions.Cli.win-x86.3.0.2106.zip. Error Error: Unexpected HTTP response: 404.

looks like the download path is change but not updated in Pipeline task.

**Comment by anthonychu** [comment]
The [Azure DevOps FuncToolsInstallerV0 task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/FuncToolsInstallerV0) checks [this feed](https://api.github.com/repos/Azure/azure-functions-core-tools/releases/latest) and downloads the Core Tools directly from GitHub releases. Looks like the 3.0.2016 release is missing the binaries in the assets. https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2106

Workaround is to try to explicitly use `3.0.2009` in the task until this is resolved.

@mhoeger @ankitkumarr

**Comment by ankitkumarr** [comment]
@srini247, what devops task are you using? 

Ideally artifacts should be downloaded from our CDN, and not Github releases. Example - https://functionscdn.azureedge.net/public/3.0.2106/Azure.Functions.Cli.win-x64.3.0.2106.zip

Either way, we should add the artifacts in the release.

**Comment by ankitkumarr** [comment]
We uploaded the release artifacts, and created this issue in the DevOps task https://github.com/microsoft/azure-pipelines-tasks/issues/12342

Ideally, the task should use `cli-feed-v3.json` to get the latest version. That said, we will try our best to ensure all releases have proper artifacts.
