### ISSUE TITLE
Add `func host stop` action

### ISSUE THREAD

**Issue by MarkTiedemann** [Azure/azure-functions-core-tools#183]
At the moment, I'm running `func host start` to start the host.

Then, to stop it:

```
taskkill /fi "imagename eq func.exe" /f
```
Would be nice if there was a `func host stop` action.

**Comment by lindydonna** [comment]
`func host start` opens a new command window, so you could simply close it.

**Comment by MarkTiedemann** [comment]
I would rather not close the command window by hand.

My use case is automated testing: I start the host, send some requests to the functions running on the host to test them, then stop the host, and all of that programmatically, of course.

The `taskkill` solution I posted above is not necessarily bad -- in fact, `taskkill` works quite well. I just feel like, if there's `start` command, there should be a `stop` command. :)

**Comment by lindydonna** [comment]
@MarkTiedemann thanks for clarifying the scenario.

**Comment by kevbite** [comment]
Had had the same problem when wrapping my code in some high level tests, had to search for the "func" process and kill them all.

Code can be seen here - https://github.com/dotnetsheff/dotnetsheff-api/blob/funcs/tests/dotnetsheff.Api.FunctionalTests/AzureFunctionsStartup.cs#L58

**Comment by ahmedelnably** [comment]
Closing as "Won't fix"
