### ISSUE TITLE
Azure Functions 3.x, func azure functionapp publish fails with Error: Permission denied

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#1831]
@ankitkumarr

**Comment by brandonmbanks** [comment]
I'm currently having this issue. Tried `az login` but still having the problem.
Looks like its related to deleting `.python_packages` dir for me.
``` bash
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Permission denied
```

**Comment by ankitkumarr** [comment]
@brandonmbanks, yes the issue was due to an executable missing permissions. v3 is updated and any new reinstalls should have the fix.

Leaving this issue open, until we release the next version everywhere so users don't have to reinstall the same version.

**Comment by ankitkumarr** [comment]
This is now fixed everywhere.
