### ISSUE TITLE
Print current AZURE_FUNCTIONS_ENVIRONMENT

### ISSUE THREAD

**Issue by mmulhearn** [Azure/azure-functions-core-tools#1834]
I'm finding that when running locally in VS 2019, functions runs as "Production", which is the opposite of what documentation says. When I try to set "AZURE_FUNCTIONS_ENVIRONMENT": "Development", I get the error "An item with the same key has already been added. Key: AZURE_FUNCTIONS_ENVIRONMENT."

Setup:
Azure Functions Core Tools (3.0.2106 Commit hash: 5431fca)
Function Runtime Version: 3.0.13107
.NET Core 3.1

**Comment by ahmelsayed** [comment]
It's always in Development when running locally. See https://github.com/Azure/azure-functions-core-tools/issues/1823#issuecomment-587966320

**Comment by mmulhearn** [comment]
Does it not log the environment?  Are we just to assume?
