### ISSUE TITLE
Cannot install azure-functions-core-tools version 3

### ISSUE THREAD

**Issue by jesperkristensen** [Azure/azure-functions-core-tools#1847]
I am trying to deploy an Azure Function using .Net Core 3.1.

From what I can read I need to use Runtime version ~3 and azure-functions-core-tools version 3.

But when I try to install using the instructions in the readme here the newest version I can get is 2.7.2184-1

I am using Ubuntu 18.04

wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
apt-cache policy azure-functions-core-tools

azure-functions-core-tools:
  Installed: 2.7.2184-1
  Candidate: 2.7.2184-1
  Version table:
 *** 2.7.2184-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.7.2100-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
     2.7.1948-1 500
        500 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
...

**Comment by anthonychu** [comment]
We're working on releasing packages for v3. Please refer to #1758 to track its progress. Thanks!
