### ISSUE TITLE
FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1 still sends telemetry

### ISSUE THREAD

**Issue by vladkosarev** [Azure/azure-functions-core-tools#1849]
core tools v2.7.2184
env (wsl/ubuntu/bash) shows
...
WSL_DISTRO_NAME=Ubuntu-18.04
FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1
....

and yet when I do func start I still get
ApplicationInsights:CorrelationIdManager [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443

I am blocking that domain so it throws an error but I would like to be able to actually opt out and reduce log spam.

Thanks.

**Comment by ankitkumarr** [comment]
Hi @vladkosarev, would you mind showing some logs before you see that error? I don't think core-tools telemetry would throw that error. That opt out setting should be honored properly. I am trying to identify where is that error coming from.

Also, do you see that error with every `func` command? Say, `func --version`, `func --help`, `func new` etc?
