### ISSUE TITLE
Finding out when Function Host is ready

### ISSUE THREAD

**Issue by MarkTiedemann** [Azure/azure-functions-core-tools#185]
After running `func host start`, I'd like to know when the host is ready to accept function calls.

I first tried polling `http://localhost:7071/` until I received `200 OK`, but it was unreliable.

I then tried reading the command output until I read `Debugger listening on [::]:5858`, and that was more reliable, but it doesn't seem like a solid solution.

Am I missing something? Is there perhaps some way for the host to ping me once it's all set?

**Comment by lindydonna** [comment]
CC @ahmelsayed

**Comment by ahmelsayed** [comment]
try `curl -XGET http://localhost:7071/admin/host/status` it should return a 200 with something like this 
```json
{
  "id":"e11995025ee9474e8f7d86f2306ae048",
  "state":"Running",
  "version":"1.0.11015.0"
}
```

Then check that it's 200 and `state === 'Running'`

**Comment by ahmelsayed** [comment]
There is also `curl -XGET http://localhost:7071/admin/functions/<functionName>/status` if you want to make sure a particular function is ready.

**Comment by MarkTiedemann** [comment]
Thanks a lot, @ahmelsayed!

**Comment by MarkTiedemann** [comment]
How can I query the `/admin/host/status` and the `/admin/functions/<functionName>/status` in Azure?

**Comment by ahmelsayed** [comment]
Sorry I've been out on vacation the past 2 weeks.

If you have access to the master key, you can do this

```bash
curl -XGET https://<yourApp>.azurewebsites.net/admin/host/status \
     -H "x-functions-key: <masterKey>"
```

or if you don't, then you can do

```bash
curl -XGET https://<yourApp>.scm.azurewebsites.net/api/functions/admin/token \
     -H "Authorization: Bearer <your Azure JWT Token>"

# That will return you another very short lived JWT token that you can then use to call any of the admin APIs

curl -XGET https://<yourApp>.azurewebsites.net/admin/host/status \
     -H "Authorization: Bearer <the token you got from above>"

# You can also exchange that short lived token with the master key if you want a longer living key.

curl -XGET https://<yourApp>.azurewebsites.net/admin/host/systemkeys/_master \
     -H "Authorization: Bearer <the token you got from above>"
```
