### ISSUE TITLE
The newest releases are not available from npm (2.7.2254, 3.0.2245)

### ISSUE THREAD

**Issue by ngg** [Azure/azure-functions-core-tools#1853]
These versions were released (at least here on Github) 7 days ago, but https://www.npmjs.com/package/azure-functions-core-tools?activeTab=versions still shows the previous versions.
Can you please publish those versions?

**Comment by yojagad** [comment]
I believe the release is still in progress. Will update this thread once it's published.

**Comment by yojagad** [comment]
Both 2.7.2254 and 3.0.2245 are in NPM now.
