### ISSUE TITLE
DevOps Release Pipeline: Create latest/[artifact] blob endpoints for release artifacts.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-core-tools#1873]
Currently the Core Tools release pipeline publishes the release artifacts to staging as blob endpoints with the following format:

```https://functionscdn.azureedge.net/public/[ver]/[artifact]```

Items such as the MSI files will be available from documentation via an aka.ms link. However, this link will need to be updated manually to point to the correct blob endpoint for each release. 

This could be avoided by pointing the aka.ms link to a stable blob endpoint which is overwritten once a version is GA'd, ex. 

```https://functionscdn.azureedge.net/public/latest/func-cli-x64.msi```

This link could also be provided in this repo or others' README. To do this we can update the core tools release pipeline to overwrite these blob endpoints.

Some considerations:
- should be a separate step from upload to staging
- should be done for all release artifacts
- should have the major version number in the endpoint somewhere
- should set CDN cache to clear for these endpoints hourly

**Comment by anthonychu** [comment]
Another option is to use the aka.ms API to update the link from the pipeline (needs approval, more details at aka.ms/akaFAQ).

**Comment by kashimiz** [comment]
Naren and I discussed that as an option. Our conclusion was that another API / external service / moving part to learn and manage was the less favorable option than the CDN, but happy to discuss!

**Comment by anthonychu** [comment]
The CDN route sounds good to me too! Just wanted to point out the API in case it wasn't already discussed.

**Comment by yojagad** [comment]
Added automated task and instructions to upload MSI, make it available in CDN and verify the same.
https://azfunc.visualstudio.com/Azure%20Functions/_releaseDefinition?definitionId=23&_a=definition-tasks&environmentId=115

https://github.com/Azure/azure-functions-core-tools/issues/1890 will ensure that only the signed MSIs are uploaded.
