### ISSUE TITLE
Register the cli with the Developer Command Prompt window.

### ISSUE THREAD

**Issue by leftler** [Azure/azure-functions-core-tools#188]
When you launch the "Developer Command Prompt" window it goes through each batch file in `%VS150COMNTOOLS%vsdevcmd\ext\` and executes them. Putting in a batch file in that directory for the CLI tool during the install that would add `func.exe` to the `%PATH%` variable while inside the developer command prompt would be appreciated.

**Comment by lindydonna** [comment]
In the meantime, you can just install the npm version of the package, which will add it to your path: https://www.npmjs.com/package/azure-functions-core-tools

**Comment by ahmelsayed** [comment]
Closing as obsolete.
