### ISSUE TITLE
Something like a hidden function cache?

### ISSUE THREAD

**Issue by konrad79** [Azure/azure-functions-core-tools#1880]
I'm developing simple azure function with VST 2019.
I'm using Azure Functions Core Tools as they are started every time I start my project.

The functions are time triggered and activity triggered.
Every time I start my project again, the Azure Functions Core Tools starts too - and now the wired is happening:

It looks like the functions are not only called once from the current runtime as expected - but also from old triggers, running still in the background.

If I set breakpoints and stop in one of the functions, it sometimes gets "old" data from runs of my projects from hours before.

I'm also getting warnings about unknown functions, I deleted or renamed in my projects dozen runs before.

I cleared the bin path of my project and searched for the string of the old functions that seems to be alive in something like a hidden cache or a hidden runtime of the azure tools.

What can I do? Is there a master stop or a master cleanup I can run before every new start of my project in the Azure Functions Core Tools?

And can it be, that this behavior also happens in the real azure environment - since I see time triggered functions there running in faster cycles as they should ran - maybe triggered by still running timers from published instances before?

**Comment by anthonychu** [comment]
@konrad79 Can you please clarify what trigger types you're using? Some samples of code and error messages will be helpful here. Thanks.
