### ISSUE TITLE
Sign the Windows MSI installer & binaries

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-functions-core-tools#1890]
I just downloaded the [latest version](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2358) of the MSI installer, and got a smartscreen warning when trying to run it.

After removing the mark of the web and clicking through the warnings to install, I noticed the instaleld binaries are also not signed.

The MSI installer and binaries should be signed.

**Comment by anthonychu** [comment]
@kashimiz Can you please take a look? Thanks.

**Comment by kashimiz** [comment]
Thank you for reporting this, @cocowalla. I'm investigating.

**Comment by kashimiz** [comment]
cc @yojagad and @soninaren 

Checked the Windows .zip files for the same release (3.0.2358); our binaries aren't signed in these either. Can you help troubleshoot?

**Comment by ankitkumarr** [comment]
@kashimiz, by default we only sign our `min` zip binaries. https://github.com/Azure/azure-functions-core-tools/blob/dev/build/Settings.cs#L105

If the msi needs full binaries to be signed explicitly, we would have to add that. That would mean adding to the [list of files](https://github.com/Azure/azure-functions-core-tools/blob/dev/build/Settings.cs#L131) we sign as well, as the full versions have additional binaries flowing through the workers.

**Comment by cocowalla** [comment]
@ankitkumarr sorry to chip in, and I've no clue what a "min" runtime is, but in the [file you linked](https://github.com/Azure/azure-functions-core-tools/blob/dev/build/Settings.cs#L115) some filenames are explicitly labelled as `authentiCodeBinaries` binaries - these too are not signed.

**Comment by ankitkumarr** [comment]
@cocowalla, as you can see in our [release artifacts](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2358), we publish binaries targeting different runtimes (win-x86, win-x64, etc).

At the moment, we only sign the binaries that are in `Azure.Functions.Cli.min.win-x64.<version>.zip` and `Azure.Functions.Cli.min.win-x86.<version>.zip` (notice the "**min**"). These are minified binaries that do not include experiences for some languages. They only work for dotnet, as those binaries are consumed by Visual studio. They are being signed as VS required them to. However, we should be signing all of them, the work just wasn't done for all yet.

The MSI contains the full set of binaries from the zip file `Azure.Functions.Cli.win-x64.<version>.zip` and `Azure.Functions.Cli.win-x86.<version>.zip`. We do not, at the moment, sign any of the binaries in those packages. We need to start doing that.

The other link I shared -- https://github.com/Azure/azure-functions-core-tools/blob/dev/build/Settings.cs#L105 shows the place where we specify only to sign the dlls in those packages. So the list of file that I linked are signed but only for the these not minified zip files.

I hope that makes sense.

**Comment by cocowalla** [comment]
> I hope that makes sense

Honestly, not much 😄

I don't really understand why you'd choose to only sign the binaries in the "minimal" zip package; I'd expect all Windows binaries coming out of Microsoft to be signed, but *especially* so for the MSI installer - it's kind of surreal downloading an MSI from Microsoft and getting a warning message about an unknown publisher 🤷‍♂ 

Anyway, glad to hear you're going to fix it 👍

**Comment by ankitkumarr** [comment]
I hope that the explanation of the current state made sense. :)

I am with you 100% that we should be signing all our binaries, and we will fix that as soon as possible. Thanks for bringing it up!

We were [supposed to do this](https://github.com/Azure/azure-functions-core-tools/issues/1241) earlier, but was overlooked. I apologize for that, and we will prioritize addressing this.

MSI is a super recent addition. The last release is the first one that we released the MSI for, and it hasn't been added to the official documentation yet. With MSI, as you said, this becomes even more critical, so I can assure that this will be addressed soon.

Once again, thank you!

**Comment by yojagad** [comment]
Chatted with @soninaren offline. We need to conditionally sign the MSI binaries during build of the release branch (release_3.0).

**Comment by fabiocav** [comment]
Resolved by https://github.com/Azure/azure-functions-core-tools/pull/2055
