### ISSUE TITLE
Default dockerfile for dotnet SDK is too old

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#1895]
On v3 when you do `--docker` or `--docker-only` for .NET it uses .NET SDK 3.0 to do the build. However our templates now target 3.1.  A simple 1 character change to use the 3.1 SDK image for the build stage would fix

// @ankitkumarr @ahmedelnably

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-functions-core-tools/commit/059abf0ece75f343794e8490729a784f032eb82d
