### ISSUE TITLE
Publish returns 401 unauthoried

### ISSUE THREAD

**Issue by mpalumbo7** [Azure/azure-functions-core-tools#1905]
I have been frustrated by the following error:

```bash
$ func azure functionapp publish myfunctionapp
Getting site publishing info...
Response status code does not indicate success: 401 (Unauthorized).
```

I've run with `CLI_DEBUG=1` and it shows successful login up until the above obscure error. I can run `func azure functionapp list-functions myfunctionapp` and there is no error. I logged in and out via `az login`. 

I am subscription administrator and have explicitly granted myself contributor rights on the resource.

```bash
$ az --version
azure-cli                          2.2.0
...
Python (Darwin) 3.8.2 (default, Mar 18 2020, 17:03:03) 
```

and 

```bash
$ func --version
3.0.2245
```

**Comment by mpalumbo7** [comment]
Same as #1101

Similar to #948, #778

**Comment by anthonychu** [comment]
@mpalumbo7 Can you share with us the function app name so we can look into it further? https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by mpalumbo7** [comment]
Sorry, priorities changed and had to delete the environment, so can’t debug this issue.
