### ISSUE TITLE
MethodNotFound when trying to call JsonResult ctor with JsonSerializerSettings

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-functions-core-tools#1907]
## Versions

- Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
- Function Runtime Version: 3.0.13139.0
- Function App: netcoreapp3.1
- Function App Version : v3

## Description

I have the following function in my function app:

```
        [FunctionName("record")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "record/{id:guid}")] HttpRequest req,
            Guid id,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            var record = ...;

            return new JsonResult(record, serializerSettings_) {
                StatusCode = StatusCodes.Status200OK,
            };
        }
```

When running locally, the following error is raised when calling the corresponding HTTP function:

```
[25/03/2020 17:23:58]  System.Private.CoreLib: Exception while executing function: record. FunctionApp: Method not found:
 'Void Microsoft.AspNetCore.Mvc.JsonResult..ctor(System.Object, Newtonsoft.Json.JsonSerializerSettings)'.
```

It seems that the `azure-functions-core-tools` runtime uses the following assembly:

- `Microsoft.AspNetCore.Mvc` version `3.1.2.0` but the latest version I can find on [NuGet.org](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/) is version `2.2.0`  dating back more than one year ? What am I missing ?

The [following document](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0) outlines this particular issue as a breaking change, when migrating from dotnet core 2.2 to 3.0 but I cannot find the latest corresponding AspNetCore assemblies to build my FunctionApp against ?

**Comment by anthonychu** [comment]
@fabiocav: @ankitkumarr and I were able to repro this. Do you know what might be happening?

**Comment by fabiocav** [comment]
@anthonychu will reach out offline to get your repro, but I'm assuming you have an explicit reference to the 2.2.x version, correct?

**Comment by springcomp** [comment]
FYI, [here](https://github.com/springcomp/AzureFunctionsCoreTools_issue1907) is a very simple and narrowly scoped repro case.

**Comment by anthonychu** [comment]
Hi @springcomp you can get around this by pulling in the Microsoft.AspNetCore.Mvc.NewtonsoftJson NuGet package:
https://github.com/anthonychu/test-jsonresult-20200326/commit/99e57fee2146b2118b97c5544b3d37f7cdfaff87

I think @fabiocav can provide more details or guesses on what might he happening here.

**Comment by anthonychu** [comment]
You can also add a reference to ASP.NET Core in your csproj:

```xml
<FrameworkReference Include="Microsoft.AspNetCore.App" />
```

We'll look into including this by default in the future.

**Comment by springcomp** [comment]
@anthonychu Yes, it works!
This solves my problem.
Thank you very much.
