### ISSUE TITLE
Choco is installing Azure Function Core Tools 2.7.2184 and not version 3.0.2245

### ISSUE THREAD

**Issue by ZeinSleiman** [Azure/azure-functions-core-tools#1908]
I was trying to debug a simple function that uses System.Text.Json and I followed the Readme to install the Azure Function Core Tools. I used Choco because I didnt have npm. I kept getting an error: 
System.Memory Version 4.2.0 was not found. I was using VS Code. 
I switched to visual studio and when I tried to debug I noticed that VS installed a different version. 

At that point I ran `func --version` to get 2.7.2184. 
I installed npm, installed the latest version and removed the version installed by choco and now I can debug in VS code.  Yay!

Please either update the package on choco or fix the documentation. 

Thanks and keep up the great work. ❤️ 

Azure Functions V3
Vs Code: 1.43.2
Azure Function Extension: 0.21.0 
.NET Core 3.1
Windows

**Comment by anthonychu** [comment]
We're tracking this with #1859. Thanks!

**Comment by ZeinSleiman** [comment]
Thanks, I didnt see the comments in that issue.
