### ISSUE TITLE
CS1061 'HttpRequest' does not contain a definition for 'RouteValues'...

### ISSUE THREAD

**Issue by ScottWolter** [Azure/azure-functions-core-tools#1909]
When debugging a Function locally in Visual Studio Enterprise 2019 (version 16.5.1) I can create a watch item that successfully evaluates to the route parameter passed to the Function. However, placing the same watch expression in the body of the Function's method results in the error included below.

CS1061 'HttpRequest' does not contain a definition for 'RouteValues' and no accessible extension method 'RouteValues' accepting a first argument of type 'HttpRequest' could be found (are you missing a using directive or an assembly reference?)

Steps to reproduce:

1. Create a new HTTP-triggered Function
2. Change the `Route` to  `"SampleRoute/{id}"`
3. Set a breakpoint inside the Function body
4. Start debugging
5. Using Postman - similar application - submit a request to the Function's endpoint. Be sure to include a route parameter
6. When the breakpoint is hit, open a watch window and add the following `req.RouteValues["id"]`. Press Enter. Does it evaluate to the route parameter passed in?
7. Stop debugging. No need to continue running the Function for test purposes.
8. In the Function body, near the beginning of the body, enter `var tmp = req.RouteValues["id"];`
9. Wait a few seconds and the error will appear.

Update: 
Language: C#
Azure Functions Core Tools 3.0.2245
Function Runtime Version: 3.0.13139.0

**Comment by anthonychu** [comment]
Can you add the following ASP.NET Core reference to your csproj?

```xml
<FrameworkReference Include="Microsoft.AspNetCore.App" />
```

Going forward we'll take a look at including this reference by default.

// @fabiocav

**Comment by ScottWolter** [comment]
Thanks, Anthony. That solution works.

Additional information can be found [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio#use-the-aspnet-core-shared-framework)
