### ISSUE TITLE
`func host start` stuck and not starting - connect ECONNREFUSED

### ISSUE THREAD

**Issue by pundergit** [Azure/azure-functions-core-tools#1910]
Hello, I'm having some problems trying to debug Python in VS Code with Azure Functions on Windows 10.

At first, after installing I had some problems because Powershell was not finding the command `func host start`. I had installed npm with nodist, but Powershell wasn't finding the command so I installed nvm-windows which didn't work either. I then fixed the problem by adding the PATH to `node_modules` in Enviroment variables. I got func starting and I was able to debug my application. But after the first run it didn't work again.

I tried everything I could: removing the PATH I created, uninstall and install azure-functions-core-tools 2 and 3, uninstall nvm and install Node.js, install .NET Core SDK  2.2, delete my functions project and create a new one, restarting VS Code, restarting Windows... nothing works.

When I start debugging here is what happens:

```
Executing task: .venv\Scripts\activate ; func host start

Found Python version 3.7.5 (python).

                  %%%%%%
                 %%%%%%    
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@  
         @@      %%%       @@  
           @@    %%      @@  
                %%
                %

Azure Functions Core Tools (2.7.2254 Commit hash: ae06bd1a6012aa6a0859b5f30d3077947267d2b6)
Function Runtime Version: 2.0.13017.0
```
It stays like this for 5 minutes or more, after I get this pop message:

![2020-03-28 13_30_11-Window](https://user-images.githubusercontent.com/16788378/77823046-711abf00-70f8-11ea-836a-1b0839c2d73e.png)

And terminal says:

```
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
That's all I have. It's really strange to me that I got it working once, and it never worked again.
 Hope you can help me, and sorry if I'm not very precise with my explanations. If I missed something about my problem please ask me. Thanks!

**Comment by anthonychu** [comment]
@pundergit Can you try activating the virtual env yourself and starting the function app?

```
.venv\Scripts\activate
func host start
```

And if that doesn't work, can you see if it works for a function app in another language? Thanks.

**Comment by pundergit** [comment]
@anthonychu thanks for the support
Activating the virtual env myself didn't work

I tried with a JavaScript function on my desktop and it worked ok. Then I tried again with a Python function on my desktop and it did work!

The problem seems to be related with the location of my project folder. I'm on a VMWare virtual machine with Windows 10 on both host and virtual machine. The project folder is a shared folder of my host mapped as a network drive on the virtual machine.

I reinstalled Python 3.7.5 but I wasn't asked to disable Path length limit as stated on: https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-01#visual-studio-code-python-and-the-azure-functions-extension
Could this be the problem? This is my working folder path: 
`Z:\HomeData1\programas\shurcondicionados-frontend-function`

**Comment by anthonychu** [comment]
@pundergit Do you get the same problem with a JS app on the mapped drive? Trying to understand if this is problem is limited to Python.

**Comment by pundergit** [comment]
@anthonychu Yes, I get the same problem with a JS app on the mapped drive.

**Comment by isa56k** [comment]
I'm seeing somethign similar to this on OSX 10.15.6 Python 3.7.5 in a virtual environment.

It worked on first run since then it doesn't:

`(.venv) ➜  azfunc2 func host start
Found Python version 3.7.5 (python3).
Azure Functions Core Tools (3.0.2881 Commit hash: fa9641ad925588192888bc977ff51d8a63536267)
Function Runtime Version: 3.0.14287.0`

**Comment by wirefusion** [comment]
you can try changing tasks.json 
"
{
			"type": "func",
			"command": "func host start",
			"problemMatcher": "$func-node-watch",
			"isBackground": true,
			"dependsOn": "npm install"
		}

"

**Comment by wirefusion** [comment]
@pundergit were you able to resolve it?

**Comment by pundergit** [comment]
> @pundergit were you able to resolve it?

No, I ended up programming on a virtual Linux machine connected from my Windows 10 VS Code. 
It's really easy to set up and you forget about all the Windows-related troubles.

**Comment by ilayn** [comment]
This is still an issue with everything updated. Before the weekend things were working. Today it's broken. I don't even know what VS Code updated. But issue still exists

**Comment by apawast** [comment]
@pundergit are you still experiencing this issue?

**Comment by pundergit** [comment]
> @pundergit are you still experiencing this issue?
No, I ended up programming on a virtual Linux machine connected from my Windows 10 VS Code.

**Comment by apawast** [comment]
I am closing this issue as @pundergit has found a workaround. However, if this issue keeps occuring for others, I'd be happy to reopen.
