### ISSUE TITLE
Error 404 Registry not found

### ISSUE THREAD

**Issue by heyyudao** [Azure/azure-functions-core-tools#1911]
Hi, I'm trying to install azure function-core-tools on my company computer using proxy however it returns the following error when I ran the command ,

npm i -g azure-functions-core-tools@3 --unsafe-perm true --force --trusted-host functionscdn.azureedge.net

npm ERR! 404 Not Found - GET https://registry.npmjs.org/functionscdn.azureedge.net - Not found
npm ERR! 404
npm ERR! 404  'functionscdn.azureedge.net@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

any one can help with this?

**Comment by anthonychu** [comment]
@heyyudao What issue are you having with the proxy that you are trying to get around?

**Comment by heyyudao** [comment]
Hi Anthony, thank you for reaching out to me

[Image]
When I try to download azure function core tools on to my company pc, It returns above error.

Can I know if it is because my company is actively blocking the server or there is some other issue. Thank you for your help

Regards
Yudao


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by heyyudao** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/files.pythonhosted.org - Not foundnd
npm ERR! 404
npm ERR! 404  'files.pythonhosted.org@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

 Hi another case of registry not found :(

**Comment by anthonychu** [comment]
@heyyudao The screenshot is missing from your previous comment.

Is there a reason you're using the `--trusted-host` flag?

**Comment by heyyudao** [comment]
PS C:\Users\heyudao\Desktop\BotDevelopment> npm i -g azure-functions-core-tools@3 --unsafe-perm true --force

npm WARN using --force I sure hope you know what you are doing.
C:\Users\heyudao\AppData\Roaming\npm\func -> C:\Users\heyudao\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\heyudao\AppData\Roaming\npm\azfun -> C:\Users\heyudao\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\heyudao\AppData\Roaming\npm\azurefunctions -> C:\Users\heyudao\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@3.0.2245 postinstall C:\Users\heyudao\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js
attempting to GET "https://functionscdn.azureedge.net/public/3.0.2245/Azure.Functions.Cli.win-x64.3.0.2245.zip"
using proxy server "http://proxy-web.XXXXX.com:X0/"
Error: unable to get local issuer certificate
+ azure-functions-core-tools@3.0.2245

updated 1 package in 3.545s

Hi when I run without the --trusted-host flag, it will give me Error: unable to get local issuer certificate

**Comment by anthonychu** [comment]
Take a look at this suggestion here to turn off strict SSL (note the comments regarding security). https://stackoverflow.com/a/46408398 You can turn it back on after installing.

**Comment by heyyudao** [comment]
hi, turn off SSL is not working for my case :( 
(npm config set strict-ssl false)

**Comment by heyyudao** [comment]
i think i'm behind corporate firewall, any workaround?

**Comment by anthonychu** [comment]
Can you try the MSI installer here? We recently added it and haven’t fully documented it yet. https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2358

**Comment by heyyudao** [comment]
hi thank you. seems like i installed successfully, but my vs code still prompt me to install it.?

**Comment by anthonychu** [comment]
Great. VS Code isn't aware of the MSI installer yet. Can you bypass that prompt?

/cc @fiveisprime @dariagrigoriu

**Comment by apawast** [comment]
@heyyudao are you still experiencing any issues in this area?
