### ISSUE TITLE
Checksum of deployment unit API

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-core-tools#1923]
If there are a lot of functions (each function represents a policy) inside a function app, and if there are services/workers that are constantly updating individual functions (policies) inside the function app, (typically these are cloud policy providers) it would make sense for these policy providers to make decisions on when to upload the entire function app as a zip again (if any policy changes) or not. 

In that case, if there is an API that can give the policy providers a calculated and reliable checksum of the function app - then providers can make decisions to not deploy a function app where no function(policy) has changed. Today any deployment of function app does not consider if contents of the app have changed or not.

**Comment by anthonychu** [comment]
@priyaananthasankar Can you provide an example where this would be useful for customers and how this would affect deploying functions from Core Tools?

**Comment by ahmelsayed** [comment]
If you are sure about your build reproducibility/consistency, then you can pull the zip file and byte compare it with the one you have. 

I don't think the platform should/could make that decision for you. It's also not at all possible for non Run-From-Package scenarios.
