### ISSUE TITLE
Value cannot be null. Parameter name: Provider error on func start

### ISSUE THREAD

**Issue by daxay** [Azure/azure-functions-core-tools#1924]
HI, First of all really thanks for this amazing tool.
But i am having little issue here.
I am using nodejs worker and typescript as language.

I am getting following errors.
- On **_func start_**  -  `Value cannot be null.
Parameter name: provider`
- On _**func new**_  -  `The operation was canceled.`

It seems to me the problem is with **extensionBundle** configurations in **host.json**
because If i remove **extensionBundle** from **host.json** then its working.

> "extensionBundle": { "id": "Microsoft.Azure.Functions.ExtensionBundle", "version": "1.1.1"}

Here is my system details:-
- Operation system - Ubuntu 16.04 64-bit
- Memory - 16 GB
- Nodejs - v10.15.3
- Typescript - 3.8.3
- Azure-functions-core-tools - 2.7.2184

Note:- Before running **_func start_** i already created build using **_npm run build_**.

**Comment by anthonychu** [comment]
Thanks. I can confirm that I can repro the `Value cannot be null. (Parameter 'value')` problem by doing the following (using Core Tools 3.0.2245):

```bash
mkdir myapp
cd myapp
func init --worker-runtime node --language typescript
func new
```

@ankitkumarr Any idea what could be happening here?

**Comment by nerdfiles** [comment]
Same issue

    Operation system - OS X Catalina
    Memory - 8 GB
    Nodejs - v12.x.x
    Azure-functions-core-tools - 2.7.2254

**Comment by anthonychu** [comment]
I was able to fix it by deleting the extension bundles cache.

On macOS, you should be able to find the cache folder with this search:

```bash
find /private/var -name "ExtensionBundles" -print 2>/dev/null
```

Mine is at `/private/var/folders/8z/8jgdqh2d34s_zl_0n0m_42640000gn/T/Functions/ExtensionBundles`. Delete the contents of this folder and run `func new` in the app folder again.

On Linux, I found the cache at `/tmp/Functions/ExtensionBundles`.

Looks like something in the cache may have been corrupted. @ankitkumarr do you know the cause? Perhaps we can get core tools to automatically take corrective action here.

**Comment by anthonychu** [comment]
@daxay @nerdfiles Let us know if deleting the bundles folder resolves it. Thanks!

**Comment by ankitkumarr** [comment]
I will take a look.

@soninaren as fyi.

**Comment by nerdfiles** [comment]
I was unable to discover the "Functions" folder or its contents ("ExtensionBundles") in `/private/var/**`. I'm not sure if my using `nvm` before install of the CLI tool would have anything to do with that.

**Comment by daxay** [comment]
@anthonychu Yes, you are right. The problem is with the cache.
Because after i deleted the `/tmp/Functions/ExtensionBundles` folder.
Its working now.
Thanks.

**Comment by nerdfiles** [comment]
Odd that `/tmp/Functions/ExtensionBundles` does not exist on my system. 🤔

**Comment by daxay** [comment]
@nerdfiles  I am using ubuntu 16.04.
I think your using macOS.
So use this command
`find /private/var -name "ExtensionBundles" -print 2>/dev/null`
and delete contents of that folder.

**Comment by anthonychu** [comment]
@nerdfiles Were you able to resolve your problem? If not, could you please set `CLI_DEBUG=1` before running the commands and let us know of any stack traces you see? Thanks.
