### ISSUE TITLE
Deploy With Remote Build Failed -- Central Directory Corrupt

### ISSUE THREAD

**Issue by bnm91** [Azure/azure-functions-core-tools#1925]
When deploying an azure function from the command line using the this command
`func azure functionapp publish my-azure-function-name  --build remote`
in version 2.7.2254 I received the following output
```
Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory
Uploading  [######################################################################################]
Remote build in progress, please wait...
Fetching changes.
Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/5e885b8f-4ebc-49fc-9f7d-b8efa1a300ff.zip (0.00 MB) to /tmp/zipdeploy/extracted
Central Directory corrupt.
Remote build failed!
```

I had deployed successfully using this exact command a few months ago.  
I reverted to version 2.7.1575 on the advice of this StackOverflow post https://stackoverflow.com/questions/60296003/central-directory-corrupt-deploying-python-azure-function

Version 2.7.1575 does not have this problem and worked fine

**Comment by anthonychu** [comment]
@ankitkumarr @Hazhzeng Could you please take a look?

**Comment by Hazhzeng** [comment]
Another customer 184131411 is also reporting this issue. Basically, the SCM site is assigned to a Linux Dedicated site rather than a Linux Consumption container.

We're still investigating this issue, will update you as soon as possible.

**Comment by AbdolrezaMadi** [comment]
I'm having the same issue when I use the latest version of azure-functions-core-tools. With version 2.7.1948 it's working fine.
It might be helpful to note that the zip file in the my local temp folder has size of 0.
I'm using function ver 2, and Linux Consumption plan.

**Comment by ankitkumarr** [comment]
It might be related to https://github.com/Azure/azure-functions-core-tools/issues/1867

@bnm91, @AbdolrezaMadi, do you happen to have a space in your path of the function directory?

I am taking at look at this, in the meanwhile, if you could confirm the space, we should be able to verify the issue and the fix.

**Comment by AbdolrezaMadi** [comment]
Yes, I got a space in the path.

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-functions-core-tools/commit/d3e47c1c5700dead61b3dbc30d566bb43943bd53

**Comment by bnm91** [comment]
@ankitkumarr Sorry i was slow in responding here. I **do not** have a space in the path of my function 


However, I have battled off and on since I started this project with a space in my in the path to my python.exe.  I have changed my PATH variable to point to a different python.exe and still get this issue but perhaps it is still relevant.
