### ISSUE TITLE
func host start fails with "Cannot access a disposed object" / "ECONNREFUSED"

### ISSUE THREAD

**Issue by moritzgloeckl** [Azure/azure-functions-core-tools#1942]
I'm trying to locally run and debug my Azure Function. I'm using the standard `HTTP trigger` project - nothing changed. When I press F5 to start the application the log output says:

```
Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
Function Runtime Version: 3.0.13139.0
Cannot access a disposed object.
Object name: 'IServiceProvider'.
The terminal process terminated with exit code: 1
```

Furthermore, an error window opens showing `Visual Studio Code` and `connect ECONNREFUSED 127.0.0.1:9091`. 

This also happens when running `func host start` from the Command Prompt (excluding the Visual Studio Code popup), no matter if running it as Administrator or not.

I've tried the various suggestions on here, like changing the port or killing processes that block the 9091 port. I've setup my shell from within Visual Studio too. I'm out of ideas now.

I'm using Windows 10 1903. I have an umlaut (Ö) in my user path which has caused problems with other tools before - maybe that could be an issue here.

Thanks!

**Comment by moritzgloeckl** [comment]
It seems that this is somewhat related to my Windows user name. 

I've set `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, this reveals a detailed error:

```
D0422 15:06:13.270355 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "C:\Users\MoritzGl?ckl\AppData\Roaming\nvm\v10.14.1\node_modules\azure-functions-core-tools\bin\grpc_csharp_ext.x64.dll"
```

As you can see, something, somewhere is setting my `Ö` to `?`. I think this may be causing troubles.

**Comment by moritzgloeckl** [comment]
It seems to be working when starting it from the PowerShell with this command:

`C:\Users\MoritzGlöckl\AppData\Local\AzureFunctionsTools\Releases\3.4.1\cli_x64\func.exe host start`

**Comment by apawast** [comment]
Hi @moritzgloeckl, what language and culture are you working with?

**Comment by moritzgloeckl** [comment]
Hi @apawast usually `de_AT` or `de`.

**Comment by apawast** [comment]
Hi @moritzgloeckl are you still experiencing this issue?
