### ISSUE TITLE
Run func kubernetes deploy without root access on container

### ISSUE THREAD

**Issue by tasb** [Azure/azure-functions-core-tools#1948]
I'm using a Dokcerbuild with this on last line
USER myuser

When I run func kubernetes deploy I get this error:
func : Error running docker exec -t bd215648b7c38a3cc0f33b3b9032e0a9b42cf635e776fa173fa5e01f170bffcb chmod +x 
/print-functions.sh.
At C:\Work\BCP.Channels.AzureFunctions\BCP.Channels.AzureFunctions\deploy.ps1:2 char:1
+ func kubernetes deploy --name channels-functions --registry cscm1nacr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error running d...t-functions.sh.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

output: chmod: changing permissions of '/print-functions.sh': Operation not permitted 

Seems to be because the container is not running with root access.

**Comment by anthonychu** [comment]
Can you try this workaround [here](https://github.com/Azure/azure-functions-core-tools/issues/1943#issuecomment-618044105) for the time being? You would need to build the image first and use `--no-docker`.

/cc @ahmelsayed
