### ISSUE TITLE
Add support for user secret file

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-core-tools#1970]

**Comment by anthonychu** [comment]
Is this the same user secret file as ASP.NET Core? How will it be used? .NET only or will it work for other languages without a .csproj?

**Comment by soninaren** [comment]
Yes, this is the same secret file as ASP.Net core. This would work along with local.settings.json file. User secrets file will very likely take precedence over the secrets in local.settings.json. Visual studio supports development leveraging the user secrets file and this work item was created for us to enable that user experience.

There hasn't been any discussion on how user secrets file support would work for non-dotnet languages. It can technically work for non-dotnet languages, we would either have to add .csproj file, encapsulate dotnet commands and require dotnet sdk ito be installed, or duplicate the functionality provided by dotnet and manage the user secret file entirely in core-tools.

**Comment by soninaren** [comment]
@gzuber can you please cherry pick changes to v2 - dev branch as well?
