### ISSUE TITLE
azure-functions-core-tools folder is created in current directory

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#1973]
Core Tools uses [`LocalApplicationData`](https://github.com/Azure/azure-functions-core-tools/blob/16b36f985ecffdd40ab4fb974f5f576593980284/src/Azure.Functions.Cli/Common/Utilities.cs#L163) to create a folder for telemetry. This uses the `XDG_DATA_HOME` environment variable on Linux, and it's not always set.

If `XDG_DATA_HOME` isn't set, the folder will be created where `func` is first run.

/cc @johnpapa

**Comment by johnpapa** [comment]
some notes ...

when I run `func start` in a functions app, it creates a `az func core tools/.telemetry` folder

when I stop the functions from running, it adds a file to that folder.

if I run `func start` in a non azure functions folder, it still adds the telemetry folder.

**Comment by bpossolo** [comment]
How do we configure the location where this folder gets created?
I'm on mac os 10.15 catalina using the java runtime + mvn `azure-functions-maven-plugin`.
I tried setting the XDG_DATA_HOME before running `mvn azure-functions:run` but the folder keeps getting generated in my project root folder
