### ISSUE TITLE
Core Tools V2 - recommend upgrading to V3 if using Python 3.8

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#1979]
Core Tools V2 currently complains that Python 3.8 is unsupported #1947. Show a message instead that recommends the user to upgrade to V3 and provide a link to instructions.

Check the behavior when running Node 12. It should also recommend upgrade.

**Comment by mhoeger** [comment]
@anthonychu - it looks like there's already code paths for python version checking in core tools but not node.

Do you think it makes sense to have the node error which comes from the node worker? the error would: 1. explicitly say what versions are expected and 2. suggest other versions with the version matrix? https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version (or the more straightforward solution of recommending functions from v2 node worker if node 12 is used)

**Comment by anthonychu** [comment]
@mhoeger Good points. I think it might make sense to keep the version check in the Node worker because it needs to run the same check when running outside of Core Tools, like on Azure or in a container.

I think Python is a little different in that we ship a different worker for each Python version, so something else (Core Tools) needs to perform the check.

> 1. explicitly say what versions are expected

Agree with this to address #1988

> 2. suggest other versions with the version matrix? https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version (or the more straightforward solution of recommending functions from v2 node worker if node 12 is used)

I think I'd be okay with just linking out to the matrix, as long as the message is clear that while we don't support the version of Node in *this* runtime version, other versions might.

Let me know what you think about a message like this:

"Incompatible Node.js version (v14.0.0). The version of the Azure Functions runtime you are using (v3) supports Node.js v10.x and v12.x. Refer to our documentation the Node.js versions supported by Azure Functions: <aka.ms link>"

The original error message also describes how to change versions in Azure. I'm not sure if that's needed. And I'm not sure if the guidance about `WEBSITE_NODE_DEFAULT_VERSION` applies to Linux.
