### ISSUE TITLE
[Azure CLI] Support key management commands in CLIs

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-core-tools#1980]
Currently, Function host and app keys can only be managed through ARM commands. See [Key management API](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Key-management-API). This issue is to track the feature of adding this functionality to either the Azure Functions Core Tools, the Azure CLI, or both.

**Comment by fabiocav** [comment]
@anthonychu just want to confirm that this is for the CLI only, right?

**Comment by anthonychu** [comment]
@fabiocav  That's correct. Thanks!

**Comment by fabiocav** [comment]
This was blocked on an issue. Moving to 79 to track

**Comment by fabiocav** [comment]
PR for this is out: https://github.com/Azure/azure-cli/pull/14465

@anthonychu and @apawast, can you both give us a green light on the comments (or let us know if you have any concerns)?

**Comment by fabiocav** [comment]
Just waiting on CLI merge/release.

**Comment by gzuber** [comment]
Resolved by https://github.com/Azure/azure-cli/pull/14465
