### ISSUE TITLE
Unable to publish function: "There is not enough space on the disk"

### ISSUE THREAD

**Issue by dstaley** [Azure/azure-functions-core-tools#1984]
I've successfully published my functionapp to Azure Functions. I modified the AuthorizationLevel property, and attempted to deploy again with the following command:

```
func azure functionapp publish myfunctionapp
```

The deployment failed, with the following output:

```
Microsoft (R) Build Engine version 16.6.0-preview-20222-04+b4f75bf75 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  MyFunctionApp-> C:\Users\Dylan\Desktop\myfunctionapp\bin\publish\bin\MyFunctionApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.54


Getting site publishing info...
Creating archive for current directory...
Uploading 373.95 MB [#############################################################################]
Creating archive for current directory...
Uploading 373.95 MB [#############################################################################]
Creating archive for current directory...
Uploading 373.95 MB [#############################################################################]
Error uploading archive (InternalServerError).
Server Response: {"Message":"An error has occurred.","ExceptionMessage":"There is not enough space on the disk.\r\n[...snip...]
```

<details>
<summary>Full error message</summary>
<pre><code>
Error uploading archive (InternalServerError).
Server Response: {"Message":"An error has occurred.","ExceptionMessage":"There is not enough space on the disk.\r\n","ExceptionType":"System.IO.IOException","StackTrace":"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)\r\n   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()\r\n   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)\r\n   at System.Web.HttpRawUploadedContent.TempFile..ctor()\r\n   at System.Web.HttpRawUploadedContent.AddBytes(Byte[] data, Int32 offset, Int32 length)\r\n   at System.Web.HttpBufferlessInputStream.EndRead(IAsyncResult asyncResult)\r\n   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.WebHost.SeekableBufferedRequestStream.<ReadAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.ByteRanges.HttpRequestMessageExtensions.<CopyToAsync>d__1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\ByteRanges\\HttpRequestMessageExtensions.cs:line 55\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Deployment.PushDeploymentController.<WriteSitePackageZip>d__19.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\PushDeploymentController.cs:line 446\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Kudu.Services.Deployment.PushDeploymentController.<PushDeployAsync>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\PushDeploymentController.cs:line 203\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Deployment.PushDeploymentController.<ZipPushDeploy>d__8.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Deployment\\PushDeploymentController.cs:line 95\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack 
trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}
</code></pre>
</details>

This function is on a consumption plan, and it's my understanding that I have 5TB of available storage to use, so 373 MB shouldn't be triggering an out-of-space error.

Trying to manually deploy a zip file also fails:

```
PS > az functionapp deployment source config-zip -g nameof-rg -n appname --src .\bin\publish\publish.zip
Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
Waiting SCM site to be updated with the latest app settings
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
Deployment endpoint responded with status code 500
```

I think this has something to do with the size of the deployment. My `publish` folder contains a folder with about 1 GB of binary assets. If I delete the folder, reducing the `publish` folder to about 2 MB, the function publishes without any issue.

**Comment by anthonychu** [comment]
@dstaley The storage capacity for consumption plan is 1GB. Looks like you might be hitting that. https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits

**Comment by dstaley** [comment]
Ah, I definitely saw that, but the footnote really confused me.

> The storage limit is the total content size in temporary storage across all apps in the same App Service plan. Consumption plan uses Azure Files for temporary storage.

I guess I got confused thinking that the available storage in my storage account is what mattered. Furthermore, the portal says the following:

> This App Service Plan (ASP) contains a Function app running on Consumption plan. Azure files are used for storage, please navigate to the Function app storage account to view usage.

This made me think even more that it was the storage of my storage account that really mattered.

As a potential action item, I think it'd be great if the CLI detected when the publish directory exceeds the maximum storage space for a given plan, and prints a nice, helpful error message along the line of:

> Deployment failed: Project directory is 1.2 GB which exceeds the maximum allowed storage for the consumption plan.

**Comment by milanm** [comment]
I got the same issue, while deploying Azure function (~250Mb zip) from the release pipeline. Some nicely formatted message would be good. Deployment just returns: 

> Error: Failed to deploy web package to App Service. Internal Server Error (CODE: 500)

**Comment by nathanjford** [comment]
I am also getting this error and cannot figure out what to do. I have a basic javascript azure function (rest api) which will not deploy through github actions. I don't know if I can increase the disk space on the App Service? The app is already pretty minimal (~500 Mb with node_modules), I don't think I can take anything out. What do I do?? Thanks

**Comment by WillFrasier** [comment]
I'm seeing this as well. We are seeing a massive file size of the azure core tools on disk. Over 600MB. I simply added this to our `.funcignore` and deployment worked fine again. Requiring users to upgrade to premium for this is not great. 

In `.funcignore` 
```
node_modules/azure-functions-core-tools
```

**Comment by louiealmeda** [comment]
> I'm seeing this as well. We are seeing a massive file size of the azure core tools on disk. Over 600MB. I simply added this to our .funcignore and deployment worked fine again. Requiring users to upgrade to premium for this is not great.
> In .funcignore
> 
> ``` 
> node_modules/azure-functions-core-tools
> ```

Oh wow thank you @WillFrasier! Just spent one full day figuring this out. 
I also needed to remove it before I publish the artifact in Azure Pipelines

```
rm -r node_modules/azure-functions-core-tools
```

**Comment by apawast** [comment]
@dstaley are you still experiencing this issue?
