### ISSUE TITLE
(Pre)release with DataProtection fix

### ISSUE THREAD

**Issue by petrce** [Azure/azure-functions-core-tools#1985]
Hi guys sorry to bug you, but me and my company we were waiting for this fix for 5 months... it was stopping us from upgrade .net core 3
https://github.com/Azure/azure-functions-host/issues/5447
since it is fixed now, would you mind releasing it atleast as a preview?
thanks

**Comment by anthonychu** [comment]
We should have a new version of Core Tools out in the next week or so.

**Comment by anthonychu** [comment]
Update: The Core Tools release is running about a week behind. Thanks for your patience.

**Comment by fabiocav** [comment]
Closing stale issue. This has been out for a little while.

**Comment by xperiandri** [comment]
Was its support released?

**Comment by fabiocav** [comment]
Yes, this should no longer be an issue but please let us know if you find any problems. This has been out for a bit, this issues was just not properly linked.
