### ISSUE TITLE
Using queueTrigger locally

### ISSUE THREAD

**Issue by jleck** [Azure/azure-functions-core-tools#1989]
Hi,

I have a queuetrigger and sendgrid function I want to use locally. When I start the local environment, I get:

```bash
The 'email' function is in error: The binding type(s) 'queueTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
```

I can see the metadata for the function, but when I try to post to it with data I get 404. Is there a way to use this function locally? The documentation says I should be able to POST to it.

**Comment by anthonychu** [comment]
Hi @jleck. Can you check if you have the extensions bundles defined in your host.json file?

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles

If not, please add it and see if that fixes the problem.

**Comment by jleck** [comment]
Hi @anthonychu , just got it working using v3 of .NET sdk (was on 2, so it didn't install). I'm using extensions.csproj, does host.json settings mean thats not required?

**Comment by anthonychu** [comment]
That's correct. You can switch to using extension bundles by adding that chuck of JSON to host.json. You can then remove extensions.csproj, bin/, obj/ from the project. And if that works well, you can even remove the .NET SDK from your machine if you don't need it.

**Comment by jleck** [comment]
Oh, thats great! Will try it out.

Might be worth adding a page somewhere or something about using queueTriggers etc and these extensions. When I did `func new` it added the extensions.csproj, so it was a bit confusing!
