### ISSUE TITLE
Updates to profile.ps1 to improve cold start

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-core-tools#2000]
Updates to profile.ps1 to improve in cold start:

* Invoking Disable-AzContextAutosave before Connect-AzAccount saves 2-4 seconds
* Remove unnecessary Get-Module call saves around ~2 seconds

profile template will look like this:

``` poweshell
if ($env:MSI_SECRET) {
    Disable-AzContextAutosave
    Connect-AzAccount -Identity
}
````

**Comment by anthonychu** [comment]
@Francisco-Gamino Will you be adding this? Thanks.

**Comment by Francisco-Gamino** [comment]
Yes @anthonychu, I will have a PR ready with this change today.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed on both dev and v3x.
