### ISSUE TITLE
Error: Cannot publish local code to function app

### ISSUE THREAD

**Issue by flaurida** [Azure/azure-functions-core-tools#2003]
Hi Azure team,

I am trying to publish my local code to a function app. It gets through the initial steps but fails on the `Syncing triggers...` step with the following error: `Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest)`. It was working earlier, the only difference is I switched to a premium plan. I am using Linux and Node.js. Please let me know if I can provide more information, thanks!

**Comment by balag0** [comment]
Can you share the function app name? Or the region of the function app and timestamp.

**Comment by flaurida** [comment]
The function app name is `spirit-api`. I am investigating if the storage account being in a different resource group is part of the problem. Thanks for the quick reply!

**Comment by flaurida** [comment]
I just tried moving the storage account to the same resource group and am seeing the same error.

**Comment by flaurida** [comment]
If it helps, the debug logs are showing `"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."`

**Comment by balag0** [comment]
Thanks. Looks like mounting the storage account is failing. The resource group of the storage account shouldn't matter. I am still investigating to see why it is failing and will update here when I have more.

**Comment by flaurida** [comment]
Hi @balag0 interesting...for what it is worth, I created a new function app and was able to publish to that one.

**Comment by balag0** [comment]
Glad you got it working. It might have been some transient networking issue if the same storage account works fine now.. Feel free to open a new issue if you have any other questions.

**Comment by flaurida** [comment]
Thanks!
