### ISSUE TITLE
How to get GET-AZ command to get Azure Function master and default App Keys .. Using AZ 3.8... Any quick response?

### ISSUE THREAD

**Issue by sanjay1913** [Azure/azure-functions-core-tools#2005]

**Comment by anthonychu** [comment]
@sanjay1913 Is this using the PowerShell module? @Francisco-Gamino can you help?

**Comment by Francisco-Gamino** [comment]
We do not have cmdlet to do this yet. I have opened an issue to add support for this in the Az.Functions cmldets. For more info, please see https://github.com/Azure/azure-powershell/issues/12005.
