### ISSUE TITLE
Local Debug for Azure Functions failing due to missing libraries

### ISSUE THREAD

**Issue by JADawson** [Azure/azure-functions-core-tools#2026]
Good morning - we have a Azure Function App in development running a series of Python based functions.

**Python - 3.7.7
azure-functions-core-tools@3.0.2534**

Until yesterday, this was running fine both in local debug (Attach to Python Functions) and when deployed to the function app in Azure.

As of yesterday (20200609) it started hitting a series of missing imports within the azure-functions-core-tools module - _azure-functions-core-tools\bin\workers\python\3.7\windows\x64\grpc\_init_.py_

- import grpc_tools
- import grpc_health
- import grpc_reflection

I added the following to requirements.txt

**
grpcio==1.29.0
grpcio-tools==1.29.0
grpcio-health-checking==1.29.0**

Which allowed the execution to progress, but now it's hitting an issue with "google.protobuf" in _azure-functions-core-tools\bin\workers\python\3.7\windows\x64\google\protobuf\internal\api_implementation.py_

` from google.protobuf import enable_deterministic_proto_serialization`

> Exception has occurred: ImportError
cannot import name 'enable_deterministic_proto_serialization' from 'google.protobuf' (xxx\venv\lib\site-packages\google\protobuf\__init__.py)

I'm really confused as this has been running locally just fine for weeks.

I've tried re-installing the azure-functions-core-tools, but that hasn't helped. I don't think adding more library imports to my venv is the right solution, it seems there is some bug in the azure-functions-core-tools package....

**Comment by zhenming91** [comment]
It looks like I am not the only one facing this particular issue with the modules. From yesterday, the local debug doesn't work as usual with the same error.

**Comment by JADawson** [comment]
Hi @zhenming91  - glad I'm not the only one, this was driving me crazy.

I did two more tests:
1) Created brand new Function App from Visual Code with simple HTTP trigger. Venv based on Python 3.7. Local Debug generated the same error.
2) Same as above with Python 3.8.3 venv - same error.

Obviously local debug is critical to ongoing development, please can you look at this asap?

**Comment by luabud** [comment]
This doesn't seem to be an issue in the Python extension, this can also be reproduced with other extensions such as CMake Tools and Docker. We're tracking the issue upstream in the VS Code repo here: microsoft/vscode#99699.

FWIW I can still reproduce the same issue when manually installing previous versions of the Python extension, so I'm not sure what is going on.

**Comment by anthonychu** [comment]
Interesting. I updated to v2020.5.86806 and debugging functions works again.

**Comment by aswin-limner** [comment]
Thank you @Hazhzeng, @anirudhgarg for the fix, the debug works fine now.

**Comment by coditmarc** [comment]
Reverted to version 2020.5.80290 and debugging is working again. Will check v2020.5.86806 now.

**Comment by coditmarc** [comment]
It appears that v2020.5.86806 is working for me as well. Thanks for the support!

**Comment by SamGinzburg** [comment]
I checked v2020.5.86806 as well - still broken for me



VScode info:
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Hazhzeng** [comment]
VSCode has just released the latest version (2020.5.86806) of Python Extension.
Please update the extension to the latest version and it will fix this issue.
