### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Kaushik27** [Azure/azure-functions-core-tools#2033]
When ever I am trying to execute the following command:
**npm install -g azure-functions-core-tools@3 --force,**
I am getting the following error:
**attempting to GET "https://functionscdn.azureedge.net/public/3.0.2534/Azure.Functions.Cli.win-x64.3.0.2534.zip"
using proxy server "http://******:*******@********.********.com"
Error: self signed certificate in certificate chain
+ azure-functions-core-tools@3.0.2534
updated 1 package in 2.189s**

Furthermore, 
I have already tried many available option suggested by node community like

- npm config set NODE_TLS_REJECT_UNAUTHORIZED=0
- npm config set strict-ssl false --global
- npm config set registry http://registry.npmjs.org/
- npm config set ca=""
- npm install npm -g --ca=null

While its working for some folks but for many its still an open issue.
Please look into this, this had  become a show stopper in Function App Design.

**Comment by anthonychu** [comment]
@Kaushik27 Can you try downloading the file from your browser? Does it give a similar error?

**Comment by Kaushik27** [comment]
@anthonychu, yeap I am able to download the zip file directly from the browser.
Its just not working when package manager tries to install it.
Let me know if you need anything else.

**Comment by angelcervera** [comment]
Same error here.

**Comment by anthonychu** [comment]
@angelcervera can you share more information about your environment.

**Comment by paulnara** [comment]
@anthonychu, please, any update on my problem? I can't use Azure Function without it.

**Comment by Kaushik27** [comment]
@apawast, I actually stopped looking into the issue after teams didn't responded in a while.

**Comment by apawast** [comment]
@paulnara are you still experiencing this issue? If yes, could you share some more details as we have not been able to reproduce this.
