### ISSUE TITLE
Local debugging in Visual Studio with managed+native

### ISSUE THREAD

**Issue by alantang-MSFT** [Azure/azure-functions-core-tools#2051]
It doesn't seem like debugging my functions project in Visual Studio respects the "Enable native code debugging" option in the project properties. When I hit F5, func.exe launches but only uses the CoreCLR debugger.

I can, however, launch func.exe manually from the command line, start my functions code and then go back to VS and attach to process with mixed mode debugging. That works but is really inconvenient.

I'm using VS Professional 2019 (16.6.2) with Azure Functions Core Tools (3.0.2534 Commit hash: bc1e9efa8fa78dd1a138dd1ac1ebef97aac8d78e) and Function Runtime Version: 3.0.13353.0.

Is there a way to enable mixed mode debugging with F5 in VS that I just missed?

**Comment by anthonychu** [comment]
@alantang-MSFT Is it possible to provide us with a simple repro so we can try this out ourselves? 

@soninaren Do you have any experience with this?

**Comment by alantang-MSFT** [comment]
[FunctionApp1.zip](https://github.com/Azure/azure-functions-core-tools/files/4886711/FunctionApp1.zip)

Make sure vcxproj builds x64. After building, I manually copy the FunctionApp1Native.DLL (and PDB) into the functions bin folder (could configure the build OutDir but I got lazy). Set breakpoint in the "Test" exported function.

In the functions csproj, enable native debugging. Then run and call the endpoint. The native code returns the magic number but you won't be able to hit the native breakpoint.

If you go into "Debug->Attach to process" in Visual Studio, you will see "func.exe" greyed out because it already has a debugger attached, but the debugger type is CoreCLR even though you enabled native debugging.

**Comment by soninaren** [comment]
I unfortunately do not, @vijayrkn , @fabiocav Any ideas on this one?

**Comment by vijayrkn** [comment]
Adding @Billhiebert - I think we pass the CoreCLR debugger while launching func.exe. We may be able to add a flag to support mixed mode.

**Comment by BillHiebert** [comment]
@vijayrkn - functions projects need to be unpdated to honor the "nativeDebugging" : true property in launchsettings.json.

**Comment by vijayrkn** [comment]
Internal bug to track this work on the VS side : [1153196](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1153196)

**Comment by apawast** [comment]
@alantang-MSFT are you still experiencing this issue? It looks like the internal bug @vijayrkn opened has been closed as completed.
