### ISSUE TITLE
func azure functionapp publish for Custom Handlers

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2053]
Parent: #1972 

Currently, we need to publish using func azure functionapp publish $functionAppName --no-build --force. Allow publishing without the extra flags.

```
func azure functionapp publish $functionAppName
```

Set `FUNCTIONS_WORKER_RUNTIME` to `custom`.

**Comment by yojagad** [comment]
The commit https://github.com/Azure/azure-functions-core-tools/commit/7dd097e1d7f5ce4d6ef5bd16f425ff0a5b83da4d already enables publish without the `--no-build` and `--force` flags. Was tested on canary portal.
