### ISSUE TITLE
The listener for function was unable to start

### ISSUE THREAD

**Issue by VladimirKochkinAtSpark** [Azure/azure-functions-core-tools#2058]
Hello!
I can't run my HttpTrigger function on my local machine. I have got the following error:
![Untitled](https://user-images.githubusercontent.com/57142748/85430283-9a78a900-b588-11ea-933e-c4cf3cdea9aa.png)

I saw the issue, but it doesn't help me.
https://github.com/Azure/azure-functions-core-tools/issues/357

My **local.settings.json**
```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet"
    }
}
```
My **host.json**
```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
}
```

But if I use real AzureWebJobsStorage, it's working.

My questions are Why I can't function locally using UseDevelopmentStorage=true and What I can do for it's working?

**Comment by anthonychu** [comment]
The error message suggests the storage emulator is returning an error. Can you try connecting to your local emulator using another application or with Azure Storage Explorer to confirm it is working?

**Comment by anthonychu** [comment]
Timer trigger requires a storage account, while http does not. If using a timer trigger, make sure the storage emulator is functioning correctly if it is configured to use it.

**Comment by VladimirKochkinAtSpark** [comment]
How can I make sure the storage emulator works correctly?

**Comment by anthonychu** [comment]
Can you try resetting the storage emulator? `.\AzureStorageEmulator.exe clear all`

More info here: https://stackoverflow.com/a/38331066
