### ISSUE TITLE
Provide a meaningful out of scope message for remote build

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-core-tools#2068]
For hosting environments where remote build is not supported Core Tools should present a meaningful out of scope message rather than an exception.

**Comment by fabiocav** [comment]
After a chat with @dariagrigoriu, we need to understand what environment information we can inspect in order to understand if we're running under one of those environments.

**Comment by anthonychu** [comment]
Probably didn’t mean to close. Reopening @fabiocav @dariagrigoriu

**Comment by ankitkumarr** [comment]
Fixed by https://github.com/Azure/azure-functions-core-tools/commit/2f5369afbdeb3e9ded70dccc93388f2b186b2093

**Comment by ankitkumarr** [comment]
Will be throwing an error sayin `--build <selected-option> is not supported for Windows Function Apps.`
