### ISSUE TITLE
Add MSI instructions for installing Core Tools

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2076]
Add instructions for installing Core Tools on Windows using MSI.

@ankitkumarr @fabiocav Are we ready to add this as the recommended method to acquire Core Tools on Windows?

**Comment by ankitkumarr** [comment]
I don't know of any blockers that would prevent us from doing so. Adding @kashimiz in case she's aware of any.

**Comment by fabiocav** [comment]
There shouldn't be any blockers at this point. The MSI will always be attached to all releases moving forward.

**Comment by anthonychu** [comment]
@ankitkumarr @kashimiz can one of you please share the CDN link? I can add the instructions to the readme as well as the docs. Thanks.

**Comment by fabiocav** [comment]
@anthonychu are you creating an aka link for this?

**Comment by anthonychu** [comment]
@fabiocav Yep I was thinking that in case the URL ever changes. Is that a good idea?

**Comment by fabiocav** [comment]
Yeah, that's what I was going to recommend 👍

**Comment by ankitkumarr** [comment]
Naren had shared with me these URLs that point to the latest MSIs --

x64 - https://functionscdn.azureedge.net/public/artifacts/v3/latest/func-cli-x64.msi
x86 - https://functionscdn.azureedge.net/public/artifacts/v3/latest/func-cli-x86.msi

**Comment by anthonychu** [comment]
Looks like we only have MSIs for v3? (not that that's entirely a bad thing)

**Comment by anthonychu** [comment]
Added fwlinks:

https://go.microsoft.com/fwlink/?linkid=2135274 x64
https://go.microsoft.com/fwlink/?linkid=2135275 x86
