### ISSUE TITLE
How do the azure function core tools execute the function runtime environment as well as allow for debugging the C# code?

### ISSUE THREAD

**Issue by ryancole** [Azure/azure-functions-core-tools#2082]
This question is not related to this project, but this project does something I'm wanting to perhaps do for my own project. I've got an AspNet Core web application that has some react components I'd like to have webpack sit and watch while I debug. So, if I modify the JS code, webpack would be running at the same time and would bundle it up for me.

In my goal, webpack could run similar to how the azure function host environment runs when you debug, I think?

I've been searching all around but can't seem to find out how to launch both webpack AND my project (into debug mode).

How do these azure function tools achieve this? Thanks!

**Comment by anthonychu** [comment]
@ryancole What editor are you trying to get this to work with?

**Comment by ryancole** [comment]
@anthonychu visual studio. When I debug, it launches the azure dev application as well as debugs the C# project

**Comment by anthonychu** [comment]
Hmmm... not sure if this is something we the functions team have expertise in. @vijayrkn Do you have any suggestions that could help @ryancole?

**Comment by vijayrkn** [comment]
@ryancole - Is this what you are looking for? https://docs.microsoft.com/en-us/visualstudio/debugger/debug-multiple-processes?view=vs-2019

You can debug your app and attach to additional processed if needed.

**Comment by ryancole** [comment]
I'll take a look. Thank you!
