### ISSUE TITLE
Warn about impending V3 upgrade if using V2 Core Tools

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2091]
Display a warning that customers should be using V3 in October. https://github.com/Azure/app-service-announcements/issues/266

Related #1855

**Comment by anthonychu** [comment]
@kashimiz @fabiocav LMK what you think of this message.

> You are using Azure Functions Core Tools 2.x. To ensure that you are using the latest version and your application is compatible with an upcoming platform upgrade, we recommend you upgrade to Azure Functions Core Tools 3.x. To learn more, see [shortlink]

Not sure how much work this adds, but are we able to detect how Core Tools is installed and display upgrade instructions?

As for where this should show, can we show it at the beginning of all commands? For `func start`, can we pause for 1 second after printing before continuing so it's obvious?

**Comment by kashimiz** [comment]
Re: detecting how Core Tools is installed, we could maybe do something with registry entries (for those who used the MSI on Windows) and install location, but that seems like a lot of work for a small convenience. The announcement already links to the upgrade wiki page; could we add instructions there instead? That way, it will be accessible to everyone and can be referenced later (without booting up core tools again.)

**Comment by kashimiz** [comment]
@soninaren @ankitkumarr  for the following from @anthonychu's message:

> As for where this should show, can we show it at the beginning of all commands? For func start, can we pause for 1 second after printing before continuing so it's obvious?

**Comment by soninaren** [comment]
> @soninaren @ankitkumarr for the following from @anthonychu's message:
> 
> > As for where this should show, can we show it at the beginning of all commands? For func start, can we pause for 1 second after printing before continuing so it's obvious?

that sounds good to me. Open to other suggestions as well.

**Comment by fabiocav** [comment]
@kashimiz moving this to sprint 86. Let me know if there are any problems with this item.

**Comment by pragnagopa** [comment]
@kashimiz  - pinging here to check if it is possible to get this change in with Sprint 86 release of Core Tools.
