### ISSUE TITLE
Environment Variable NodeJS

### ISSUE THREAD

**Issue by mrgenesis** [Azure/azure-functions-core-tools#2123]
Hello there!
I don't achiving set environment variable in my project. What I'm doing wrong? 
`// local.settings.json`
```json
{
  "keyName": {
      "keyName": "value"
    }
}
``` 
In `index.js` file the variable `process.env["keyName"]` return undefined.

**Comment by anthonychu** [comment]
Please refer to this [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#local-settings-file) for the proper format. It needs to have `IsEncrypted` and `Values`, and the environment variables go in `Values`.

You can also create the file by running `func init`.

**Comment by mrgenesis** [comment]
This is my local.settings.json file:

```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "",
    "RECAPTCHA": {
      "secret": "*****************"
    }
  }
}
```

**Comment by anthonychu** [comment]
Values cannot be nested like that. You’ll need to keep them at a single level.

**Comment by mrgenesis** [comment]
Working now!
\0/
