### ISSUE TITLE
Environment Variable NodeJS - Azure

### ISSUE THREAD

**Issue by mrgenesis** [Azure/azure-functions-core-tools#2124]
Hi.
This example below show how is settinged my `local.setting.json` file. This are working fine.
```json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsStorage": "",
    "GN_ID": "Client_Id_**************************",
    "GN_SECRET": "Client_Secret_*********************************",
    "ENVIRONMENT": "sandbox"

  }
}
```
```javascript
// working fine
process.env.GN_ID
```
I sent the project to Azure Functions and added it to Application settings in Azure portal. But don't working. What I'm doing worng?

![image](https://user-images.githubusercontent.com/32000025/88980345-857eec00-d291-11ea-9bcb-3596461e1c33.png)

Doc: https://docs.microsoft.com/pt-br/azure/azure-functions/functions-reference-node#environment-variables

**Comment by anthonychu** [comment]
@mhoeger Any thoughts on this? Looks like this should work.

**Comment by mrgenesis** [comment]
I'm sorry! I forgot save. This perfectly working. Thank you.

**Comment by mhoeger** [comment]
Have definitely done that myself haha. Thanks for the update! Closing issue
