### ISSUE TITLE
ConnectionStrings are not imported into local environment from local.settings.json

### ISSUE THREAD

**Issue by gunzip** [Azure/azure-functions-core-tools#214]
According to the docs here: 
https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-configure

> For PHP, Python, Java and Node applications, [ConnectionStrings] settings will be available as environment variables at runtime, prefixed with the connection type.  [...]
> For example, if a MySql connection string were named connectionstring1, it would be accessed through the environment variable MYSQLCONNSTR_connectionString1.
> [...]

But when running locally, *ConnectionStrings* variables are **not** imported into environment 
using local.settings.json:

```
UpdateEnvironmentVariables(getSecrets(), ...)

getSecrets() ->
var appSettingsFile = new AppSettingsFile(AppSettingsFilePath);
            return appSettingsFile.GetValues();
```

only the AppSettings -> Values part gets imported so using NodeJS you cannot access
```
process.env.<my connection strings>
```
from application code.

**Comment by ahmedelnably** [comment]
Closing as stale
