### ISSUE TITLE
Support KEDA 2.0 for func kubernetes commands

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#2144]
KEDA 2.0 will go into beta soon, with a 2.0 release planned for later this year.  There are some minor changes to the spec so the function core tools will need to be able to generate the latest one.  

https://keda.sh/docs/2.0/migration/

Ideally there could still be a flag for backwards compat to KEDA 1.0?  Or maybe we make people opt-in to keda 2.0?  `func kubernetes deploy --keda-version 2` or something?

Will just need live before like end of October

// @apawast @anirudhgarg @TsuyoshiUshio

**Comment by tomkerkhove** [comment]
Would be good to use 2.0 as default and provide capability to use 1.0 for backward compatibility maybe?

**Comment by anthonychu** [comment]
I think it might be safer for `deploy` to check which version is installed in the cluster and be smart about what to do. A `--keda-version` flag might still be needed when the version is unknown (like when using `--dry-run`).

**Comment by tomkerkhove** [comment]
Even better proposal!

**Comment by jeffhollan** [comment]
FYI - 2.0 is now in beta, scheduled to be default in coming months.  Just flagging in that we likely want to try to book the work for this before end of October

**Comment by tomkerkhove** [comment]
If I'm bored I can give it a try, but no promises!

**Comment by tomkerkhove** [comment]
RC is out - https://github.com/kedacore/keda/releases/tag/v2.0.0-rc

**Comment by TsuyoshiUshio** [comment]
It is a good idea! I agree with @anthonychu 's idea. I have a customer who wants to use v2 for the production as a backend of a service. However, My scalelogic prevent to use it, So I provide them a hotfix with branch and push keda image to dockerhub. Probably, if we operate it, these case happens, then we can easy to provide hot fix and customer can rollback old version if there is a problem for a new release.

**Comment by jeffhollan** [comment]
Just pinging here, looking for end of October / early November release for KEDA 2.0 and will start being default. Would be good to track these changes.  All the changes between 1 and 2.0 are covered here https://keda.sh/docs/2.0/migration/ - added to PM board for planning / prioritization

**Comment by tomkerkhove** [comment]
I'll pick this up in one of the coming days

**Comment by pragnagopa** [comment]
cc @fabiocav 
Tagging myself (@pragnagopa), @ankitkumarr , @gzuber  for reviews

**Comment by pragnagopa** [comment]
Closing as addressed in referenced PR.
