### ISSUE TITLE
Error calling sync triggers (BadRequest). Python runtime on Linux.

### ISSUE THREAD

**Issue by neckhaus** [Azure/azure-functions-core-tools#2163]
I am trying to publish my local code to a function app using VS Code. The code runs locally without issue in VS Code.

It gets through the initial steps but fails on the Syncing triggers...  I have had this working in the past for this function app, and have done this on other function apps.  After I see "Remote build succeeded!", I get the 6, "Syncing triggers..." messages before finally getting the "Error calling sync triggers (BadRequest). Request ID = 'a1045c31-ed9c-43fb-81c2-4c8dd702649c'." message.

I've found in #1885 that it could be the AzureWebJobsStorage string and verified they are the same in my local.settings.json and Azure Portal.

I've found in #996, and #1457 that it could be related to network or region problems, so I tried this over the past 3 days without any change.

I've found in #1415 that "The thing is SyncTriggers is the first call that is made on the Function App. So, it failing could mean a lot of things - function app is down, App didn't update, etc. Usually, we want to look at these issues on a case by case basis."

I've found in #2003 that it might work if I create a new function app and publish to that, but I'd rather understand what is happening and have it resolved so I have more confidence that this won't happen again.

Location: East US
Function App Name: fn-HBMonitor

**Comment by apawast** [comment]
@balag0  @Hazhzeng Can one of you take a look at this?

**Comment by neckhaus** [comment]
Updated VS Code to 1.48.2.  No change.  Still fails to publish with the same error.

**Comment by balag0** [comment]
@neckhaus I see the app is in stopped state. Could you start the app and try this again and share the timestamp if it is failing again?

**Comment by neckhaus** [comment]
@balag0 It worked this time.  Thank you.
