### ISSUE TITLE
lauch.json has error message

### ISSUE THREAD

**Issue by FunnyBlue** [Azure/azure-functions-core-tools#2164]
I am trying to follow this tutorial by using VS code
[Quickstart: Create a function in Azure using Visual Studio Code 
](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-python)
I have downloaded the latest Azure function core tools, python extension but I got this error message:
**Invalid message: "noDebug" is not supported for "attach"**(open lauch.json) when I try to run the sample code locally. 
my lauch.json looks like this:
```

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Python Functions",
      "type": "python",
      "request": "attach",
      "port": 9091,
      "preLaunchTask": "func: host start"
    }
  ]
}
```

I have tried to recreate a new project, reload my VS code, reinstall everything I could think of, but this error message still keep showing up. 
Anyone can give me some helps here?

**Comment by apawast** [comment]
@EricJizbaMSFT do you know what this error means?

**Comment by EricJizbaMSFT** [comment]
Not based on that info. Sounds like something coming from the Python extension.

@FunnyBlue Where exactly is that error happening? Are there any more logs?
