### ISSUE TITLE
PowerShell v7 in "func start" instead of 6.2.4

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-functions-core-tools#2168]
## Summary

I want to use PowerShell v7 for local testing with `func`. 

## Actual Result

* I installed `func` using `npm install --global azure-functions-core-tools`.
* When I run `func start`, the `func` tool uses PowerShell `6.2.4`, however I have `7.0.3` installed via Scoop package manager

## Expected Result

`func` uses `pwsh` that I already have installed locally

**Question**: How do I tell `func` to use PowerShell 7 that I have installed, instead of using its own separate installation of PowerShell 6?

Related: https://github.com/Azure/azure-functions-powershell-worker/issues/371

**Comment by apawast** [comment]
@Francisco-Gamino can you help with this?

**Comment by Francisco-Gamino** [comment]
Hello @pcgeek86 -- to use PowerShell 7 in Functions locally you have two options:

1) Download the latest version of the Azure Core Tools (https://github.com/Azure/azure-functions-core-tools#installing) and create a new PowerShell function app. By default, we set the PowerShell worker version to ~7.

Here is the version of the Azure Core Tools that I am using:
```powershell
PS E:\MyFunctions\PS7Demo1> func --version
3.0.2798
```

Create a new PowerShell function app. Notice that an entry is created in `local.settings.json` for the worker version, e.g., `"FUNCTIONS_WORKER_RUNTIME_VERSION": "~7"`
```powershell
PS E:\MyFunctions\PS7Demo1> func init
Use the up/down arrow keys to select a worker runtime:powershell
Writing profile.ps1
Writing requirements.psd1
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing E:\MyFunctions\PS7Demo1\.vscode\extensions.json
PS E:\MyFunctions\PS7Demo1> gc .\local.settings.json
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "powershell",
    "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}
```

2) Manually add the ` "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7"` entry in `local.settings.json`.

Please note that `func` will use `PowerShell` version `7.0.3` which ships with the Azure Core Tools.

**Comment by pcgeek86** [comment]
Hello @Francisco-Gamino, I used the Azure Functions extension for Visual Studio Code to create a new PowerShell function.

The `local.settings.json` file contains the following (unmodified):

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME_VERSION": "~7",
    "FUNCTIONS_WORKER_RUNTIME": "powershell"
  }
}
```

When I run `func start`, I see the following in the logs:

```
[8/27/2020 8:32:28 PM] System Log: { Log-Level: Information; Log-Message: Azure Functions PowerShell Worker version [3.0.283.0]. }
[8/27/2020 8:32:29 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[8/27/2020 8:32:29 PM] System Log: { Log-Level: Trace; Log-Message: Updating dependencies folder heartbeat for 'C:\Users\TrevorSullivan\AppData\Local\AzureFunctions\azure-functions-intro\ManagedDependencies\200827203229475.r''. }
[8/27/2020 8:32:29 PM] System Log: { Log-Level: Information; Log-Message: PowerShell version: '7.0.0'. }
[8/27/2020 8:32:29 PM] System Log: { Log-Level: Trace; Log-Message: First function load request completed in 688 ms. }
[8/27/2020 8:32:29 PM] System Log: { Log-Level: Trace; Log-Message: Installing function app required modules to 'C:\Users\TrevorSullivan\AppData\Local\AzureFunctions\azure-functions-intro\ManagedDependencies\200827203229475.ri' (installation mode: Required). }
[8/27/2020 8:32:31 PM] System Log: { Log-Level: Trace; Log-Message: Started installing module 'Az' version '4.6.0'. }
[8/27/2020 8:32:33 PM] Host lock lease acquired by instance ID '000000000000000000000000545DB49E'.
```

Do you know why it's using PowerShell version 7.0.0 instead of PowerShell 7.0.3 that I have installed via Scoop package manager? It seems like it's downloading its own separate version of PowerShell, instead of using the globally installed version of PowerShell for the system.

The same issue happens when I use `func init` to create a new Azure Functions project.

How do I make sure that Azure Functions is using the latest PowerShell Core runtime, that's installed on the system (`7.0.3`)?

Here's the PowerShell Core that's installed for the system, and here's the version of Azure Functions Core Tools I'm using:

![image](https://user-images.githubusercontent.com/466713/91492495-ff939800-e872-11ea-8312-566446b0d3d4.png)

**Comment by Francisco-Gamino** [comment]
> How do I make sure that Azure Functions is using the latest PowerShell Core runtime, that's installed on the system (7.0.3)?

Hi @pcgeek86 -- This is not a supported scenario. The version of PowerShell that runs in Azure Functions ships with the Core Tools. The way we update the PowerShell bits is as follows. First, we update the PowerShell worker to reference the latest version of the PowerShell SDK. From there, we update the Core Tools with the latest version of the PowerShell worker. 

Currently, the Azure Core Tools are running PowerShell 7.0.0. The next release should have 7.0.2. Here is the PR that updates the PowerShell worker to 7.0.2: https://github.com/Azure/azure-functions-core-tools/pull/2130.

**Comment by pcgeek86** [comment]
But you just told me this, in your earlier post:

> Please note that func will use PowerShell version 7.0.3 which ships with the Azure Core Tools.

Now you are telling me this:

> Currently, the Azure Core Tools are running PowerShell 7.0.0. The next release should have 7.0.2. Here is the PR that updates the PowerShell worker to 7.0.2: #2130.

These are two conflicting pieces of information. Which is correct?

**Comment by Francisco-Gamino** [comment]
Hi @pcgeek86 -- apologies for the confusion. The PowerShell worker repo references `7.0.3`, but this change has not been deployed yet. 

Currently, in the Azure Functions service we support PowerShell `7.0.2`, and the Core Tools support PowerShell `7.0.0`. In the next release of the Core Tools, the version will be updated to `7.0.2`.

cc: @stefanushinardi @AnatoliB @anirudhgarg

**Comment by AnatoliB** [comment]
To clarify the confusion, it is important to understand these two points:
1. By design, the PowerShell worker in Functions never uses the standalone PowerShell installed on the machine. The worker uses the PowerShell engine via the PowerShell SDK, not as a separate executable. The worker is self-contained and includes all the necessary PowerShell SDK binaries. The PowerShell version used is entirely determined by the PowerShell worker build. There is no supported way to tell it to use a different version.
2. The release cadences of the Functions Core Tools and the PowerShell worker are different. Normally, the worker is migrated to the latest LTS PowerShell version soon (days) after this version is officially released. However, it takes time (weeks) for a Core Tools release to pick up this PowerShell worker version.

If you _must_ use the latest PowerShell in Functions now and cannot wait for the corresponding Core Tools release, you can rebuild the worker from the source code (https://github.com/Azure/azure-functions-powershell-worker): take the code from the desired [release tag](https://github.com/Azure/azure-functions-powershell-worker/releases) or the `dev` branch, and follow the [instructions](https://github.com/Azure/azure-functions-powershell-worker#run--debug).
