### ISSUE TITLE
Investigate logging filter unit tests

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-core-tools#2174]
Tests: LoggingFilterHelperTests and GetHostJsonDefaultLogLevel_Test only fail in CI runs. Do not repro locally.

**Comment by pragnagopa** [comment]
Address comment : https://github.com/Azure/azure-functions-core-tools/pull/2186#discussion_r482128098

cc @brettsam

**Comment by pragnagopa** [comment]
Also add E2E tests that verify output with following host.json content:
1. 
```
{
	"version": "2.0",
	"logging": {
       "LogLevel": {
		"Default":"Trace"
        }
	},
	"extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
}
```

2. Add explicit log levels:
```
{
  "version": "2.0",
  "logging": {
       "LogLevel": {
		"Function.HttpTrigger":"Trace",
		"Host.Startup":"Debug",
                 "Microsoft.Azure.WebJobs.Script.WebHost.Middleware.SystemTraceMiddleware":"Debug"
        }
}
}

```

**Comment by pragnagopa** [comment]
Verify SystemLogs that VS Code depends on are emitted even when  default `LogLevel` is set to `None`

```json
{
	"version": "2.0",
	"logging": {
        "LogLevel": {
		"Default":"None"
        }
	},
	"extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
}
```

**Comment by pragnagopa** [comment]
Follow-up from https://github.com/Azure/azure-functions-core-tools/issues/2230#issuecomment-697656909

Update DateTime format in the logs.

**Comment by fabiocav** [comment]
Done.
