### ISSUE TITLE
system.provate.corelib value cannot be null (parameter 'key'}

### ISSUE THREAD

**Issue by mcgjoe** [Azure/azure-functions-core-tools#2175]
Getting the error below when I run blob trigger azure function.  I a having trouble finding any info on what may be causing this.

System.Private.CoreLib: Exception while executing function: Functions.BlobTrigger1. System.Private.CoreLib: Value cannot be null. (Parameter 'key').

Has anyone seen / solved this?  Any help would be appreciated.  Thanks.

**Comment by apawast** [comment]
Hi @mcgjoe, do you mind sharing repro steps for this issue?

**Comment by mcgjoe** [comment]
Hi @apawast   .  i am debugging this azure function locally.  this function is blob triggered as I upload file to blog this error occurs.  This function is not able to initiate past acknowledging trigger action

**Comment by mcgjoe** [comment]
when step through code last command I get to is :  (this is part of internal/ proprietary azure function processing not my function code)
self._grpc_resp_queue.put_nowait(resp)

of this code block:

async def dispatch_grpc_request(self, request):
content_type = request.WhichOneof('content')
request_handler = getattr(self, f'handle{content_type}', None)
if request_handler is None:
# Don't crash on unknown messages. Some of them can be ignored;
# and if something goes really wrong the host can always just
# kill the worker's process.
logger.error(f'unknown StreamingMessage content type '
f'{content_type}')
return

**Comment by mcgjoe** [comment]
sorry couldn't provide right info to push this forward.  I moved on to try different solution.  thanks for trying to help.
