### ISSUE TITLE
MSI installer doesn't include `func` in the PATH

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#2181]
After installing using the MSI installer, it doesn't automatically include the `func` executable in the path, so most CLIs and tooling don't know functions is there.  Ideally the MSI would append the path with the path of the install so that a new terminal would work

**Comment by anthonychu** [comment]
Looks like it does append to the path, but have to restart the PowerShell session to take effect. Perhaps the installer can let people know to do that.

If you're in VS Code, you might have to exit VS Code entirely. And if VS Code was launched from a PowerShell prompt, you might have to restart PowerShell and VS Code.

**Comment by jeffhollan** [comment]
Hmm I thought I tried a new powershell session and it still wasn’t picking it up.  I can check out the PATH it did create.  Not sure if I did anything that would throw it off - and possible I didn’t fully create a clean session.  I’ll confirm before we triage.  Thanks for the info though

**Comment by jeffhollan** [comment]
Yep - not sure what my problem was before but it's in the path and works fine
