### ISSUE TITLE
Null reference exception when debugging from VS

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-core-tools#2183]
Hi Guys,

I have installed Microsoft Visual Studio Enterprise 16.8.0 Preview 2.1 yesterday and now can't run Azure Functions locally.
![image](https://user-images.githubusercontent.com/5653381/91915862-c003fa80-ed0f-11ea-87a4-c04806faac3d.png)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=func
  StackTrace:
   at Azure.Functions.Cli.Utilities.LogLevelExists(IConfigurationRoot hostJsonConfig, String category) in D:\a\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 208
```

Azure Functions Core Tools (3.0.2852 Commit hash: d1c2c8e7dc10a94a399246dda94049a7dbf0383d)
Function Runtime Version: 3.0.14287.0

**Comment by DickSwart** [comment]
I have the same issue, did not install anything new. Just started happening today. 

Microsoft Visual Studio Professional 2019
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Version 4.8.04084

**Comment by jaliyaudagedara** [comment]
it's this line: https://github.com/Azure/azure-functions-core-tools/blob/674ea7a0dd605e6c61349839129596841c1a8f30/src/Azure.Functions.Cli/Common/Utilities.cs#L208
When host.json doesn't have the categoryKey, it's looking for, throws NRE. Should have checked if it exists before accessing?

**Comment by anthonychu** [comment]
@pragnagopa Could you please take a look?

@DickSwart @jaliyaudagedara Makes sense that there could be a null ref here, but I can't repro the error. Could you share your host.json?

**Comment by jaliyaudagedara** [comment]
@anthonychu, I am able to easily reproduce, just create a new Azure Function App using VS.

```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
```
These seems to be the missing keys,
```
      "Microsoft.AspNetCore.Server.Kestrel": "Information",
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Information",
      "Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory": "Information",
      "Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler": "Information",
      "Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager": "Information",
      "Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository": "Information",
      "Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver": "Information",
      "Microsoft.AspNetCore.DataProtection.TypeForwardingActivator": "Information",
      "Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory": "Information",
      "Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider": "Information",
      "Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor": "Information",
      "Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService": "Information",
      "Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcInitializationService": "Information",
      "Host.General": "Information",
      "Host.Startup": "Information",
      "Host.LanguageWorkerConfig": "Information",
      "Microsoft.Azure.WebJobs.Script.FunctionMetadataProvider": "Information",
      "Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator": "Information",
      "ProjectHelpers": "Information",
      "Host.Triggers.Warmup": "Information",
      "Microsoft.Extensions.Hosting.Internal.Host": "Information",
      "Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService": "Information",
      "Microsoft.Azure.WebJobs.Hosting.JobHostService": "Information",
      "Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager": "Information",
      "Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher": "Information",
      "Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer": "Information",
      "default": "Information"
```
But can be different based on the function type. Does the local function host pick the common host.json from the local installation?

**Comment by DickSwart** [comment]
```json
{
  "version": "2.0",
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  },
  "logging": {
    "applicationInsights": {
      "httpAutoCollectionOptions": {
        "enableHttpTriggerExtendedInfoCollection": false
      }
    },
    "logLevel": {
      "Function.v1-health-check": "Warning",
      "Function.v2-health-check": "Warning"
    }
  }
}
```

**Comment by pragnagopa** [comment]
Investigating.

**Comment by mpnow** [comment]
I'm having the exact same issue, just started today. I just ran a function app locally that was running fine yesterday. Saw that it briefly flashed "downloading core tools" when it started up, so obviously it updated them. Now my app won't run - I get the same error:

`at Azure.Functions.Cli.Utilities.LogLevelExists(IConfigurationRoot hostJsonConfig, String category) in D:\a\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 208`

This is with:

Azure Functions Core Tools (2.7.2855 Commit hash: 674ea7a0dd605e6c61349839129596841c1a8f30)
Function Runtime Version: 2.0.14248.0

Here is my host.json:

```
{
  "version": "2.0",
  "functionTimeout": "02:00:00",
  "extensions": {
    "serviceBus": {
      "sessionHandlerOptions": {
        "maxAutoRenewDuration": "00:05:00",
        "messageWaitTimeout": "00:00:10",
        "maxConcurrentSessions": 1,
        "autoComplete": true
      }
    }
  }
}

```

**Comment by pragnagopa** [comment]
Please note that there is a try ... catch  here

https://github.com/Azure/azure-functions-core-tools/blob/674ea7a0dd605e6c61349839129596841c1a8f30/src/Azure.Functions.Cli/Common/Utilities.cs#L206-L213

Until we release a fix for the null ref, when debugging - please select do not break on this exception.

**Comment by jaliyaudagedara** [comment]
Yes, that's what I am doing now. But I am wondering, how come this started happening suddenly?

**Comment by pragnagopa** [comment]
@jaliyaudagedara 

> But I am wondering, how come this started happening suddenly?

Core Tools version 3.0.14287.0 was just released and VS updates to the latest version automatically.

**Comment by mpnow** [comment]
>Until we release a fix for the null ref, when debugging - please select do not break on this exception.

Agreed, that works to get the function running, thanks.

> But I am wondering, how come this started happening suddenly?

As I mentioned, I saw the Core Tools run an update when I ran my app today. And:
![image](https://user-images.githubusercontent.com/2540658/91924998-1c303580-eca2-11ea-9f9e-74b7ff9f6e09.png)

**Comment by jaliyaudagedara** [comment]
Thanks @pragnagopa, that explains it!

**Comment by djmrky** [comment]
Same here, can't debug :-(

**Comment by Biboulin** [comment]
Same here, i solved this by running my function app without host.json and run it again with "version": "2.0" ...

Azure Functions Core Tools (3.0.2852 Commit hash: d1c2c8e)
Function Runtime Version: 3.0.14287.0

**Comment by djmrky** [comment]
It started working again on it's own

**Comment by zencondchaskar** [comment]
Temporary, copied all from AzureFunctionsTools/Releases/ 3.10.0 folder/files into the AzureFunctionsTools/Releases/ 3.11.0. 

![image](https://user-images.githubusercontent.com/68268154/91977727-b3e46100-ed40-11ea-9298-679e7fe7446a.png)

**Comment by mrpmorris** [comment]
I am having this now too.

**Comment by djmrky** [comment]
Well, after restarting the machine, it's not working again

**Comment by stephanruhland** [comment]
Same problem here, can only start functions without a debugger.

**Comment by stephenstroud** [comment]
Same problem - sad times....

**Comment by mrpmorris** [comment]
It seems even ignoring the exception is no good, my function app just hangs now.

**Comment by BoutemineOualid** [comment]
Same issue here

**Comment by humbertosantiago** [comment]
Same here

**Comment by pragnagopa** [comment]
cc @soninaren 

We are working on releasing new version with the fix.

Until we release a fix for the null ref, when debugging - please select do not break on this exception.

**Comment by pragnagopa** [comment]
Fix is merged with the linked PR. New version of core tools is released.
