### ISSUE TITLE
Request body with 'Content-encoding: gzip' is bein messed up

### ISSUE THREAD

**Issue by danigomez** [Azure/azure-functions-core-tools#2185]
Hello,
I'm currently working on and endpoint that should receive a gzipped body, and it seems that something in the buffer is being messed up

I'm deconding the gzipped body using this middleware
```typescript

const buffer: Buffer[] = [];

    request
      .on("data", (chunk) => {
        buffer.push(Buffer.from(chunk));
      })
      .on("end", () => {
        const concatBuff: Buffer = Buffer.concat(buffer);
        console.log(concatBuff);
        zlib.gunzip(concatBuff, (err, buff) => {
          if (err) {
            console.log("gunzip err", err);
            return next(err);
          }
          request.body = buff.toString();
          next();
        });
      });
```

And testing it with this curl command:

`cat webhook.txt | gzip | curl -v -i --data-binary @- -H "Content-Encoding: gzip" http://localhost:3334`
In this server, which uses **azure-function-express**, i'm getting this error:
```

[1/9/2020 22:36:21] gunzip err Error: incorrect header check
[1/9/2020 22:36:21]     at Zlib.zlibOnError [as onerror] (zlib.js:170:17) {
[1/9/2020 22:36:21]   errno: -3,
[1/9/2020 22:36:21]   code: 'Z_DATA_ERROR'
[1/9/2020 22:36:21] }
```
it seems that the error is caused because the header is not the "magical number" of a gzip file:

<Buffer **1f ef bf bd 08 00** ef bf bd ef bf bd 4e 5f 00 03 ef bf bd 5d 6d 73 db b8 11 ef bf bd ef b f bd 5f ef bf bd e1 97 bb 6b 7d 16 ef bf bd 77 ef bf bd 73 ef ... 4589 more bytes>

I also tried this with a common express app using exactly the same code and same curl and is working correctly.
So it seems that Azure functions doesn't handle the data in the same way that the express app.

Do you have any idea what can be causing this issue? So i can take a look a it more carefully.

**Comment by anthonychu** [comment]
azure-functions-express is a third party module that we don't officially support. That said, it works quite well for many types HTTP requests. It tries its best to map the HTTP trigger payload from a Node.js Azure Function invocation into an Express request. However, as the request goes through several layers before arriving at the Node worker, what the function trigger receives is a representation of the request that may be slightly different than the original request.

In this case, it's possible that the function host saw the content-encoding header and already decompressed the payload, and that's what was passed to the Node function.

@mhoeger might have more ideas about what's happening here.

**Comment by danigomez** [comment]
Hi guys,
I just found out that if you set '**Content-Type: application/octet-stream**" there is no issue when i try to gunzip the body.
However, if i set '**Content-Type: application/json** i got the error.
I also tried this deployed as an Azure Function, an i still got this error, so maybe is a config thing that i'm missing??

**Comment by mhoeger** [comment]
+1 to what Anthony said - there are some content-type headers that we automatically read and treat as bytes including `application/octet-stream` and `multipart/*`. Have you tried deploying to Azure Functions with `Content-Type: application/octet-stream`? Does that not work?

One workaround to make sure all requests have this content-type header is to add a proxies.json file like this:
```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "RequireContentType": {
            "matchCondition": {
                "route": "/api/HttpTrigger"
            },
            "backendUri": "https://proxy-example.azurewebsites.net/api/HttpTrigger",
            "requestOverrides": {
                "backend.request.headers.content-type": "application/octet-stream",
                "backend.request.headers.request-content-type": "'{request.headers.content-type}'"
            }
        }
    }
}
```

**Comment by danigomez** [comment]
That did the trick!
Thank you so much @mhoeger
