### ISSUE TITLE
Massively verbose console output since Core Tools 2.7.2855

### ISSUE THREAD

**Issue by acrov** [Azure/azure-functions-core-tools#2189]
Since Visual Studio updated Core Tools to 2.7.2855 I now have massively verbose console output.  Lots of dark cyan lines everywhere from just about every library I am using.  This was not the previous behaviour. Screenshot of example output below.

I get this verbose output with Information, Debug or Trace default log levels  I might have expected it with Trace although it didn't previously.  Would not expect it with Information.

App is also running much slower but this is presumably because of all the logging.

![image](https://user-images.githubusercontent.com/49073938/91997082-9cea4280-ed31-11ea-8a8b-ceb1aaff5c20.png)

**Comment by acrov** [comment]
Without any arguments
![image](https://user-images.githubusercontent.com/49073938/92001322-74b11280-ed36-11ea-8db7-279146cec043.png)

With `host start --verbose false`
![image](https://user-images.githubusercontent.com/49073938/92001477-a0cc9380-ed36-11ea-865a-6cf21d346a60.png)

With `host start --verbose true`
![image](https://user-images.githubusercontent.com/49073938/92001544-b6da5400-ed36-11ea-96e7-bd8db4e3ab8d.png)

The above screenshots are with loglevel Trace in host.json which is my usual setting.

Maybe the previous screen was just informational messages but I guess my point is that there was nowhere near this level of output before this release and it is slowing everything down and getting in the way of actual useful messages.  Here are some examples of output that was previously absent. Whether these are informational logs or not I can guarantee that they were not there prior to this release.
![image](https://user-images.githubusercontent.com/49073938/92002314-a2e32200-ed37-11ea-8f16-335f3c2ac961.png)
![image](https://user-images.githubusercontent.com/49073938/92002572-e8075400-ed37-11ea-9ad2-108e82c714b3.png)

**Comment by pragnagopa** [comment]
Thanks. Investigating. Can you please share `host.json`  as well?

**Comment by acrov** [comment]
Host.json for first screenshot is as in screenshot i,e.
`{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Information"
    }
  }
}`

host.json for most recent shots was

`{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Trace"
    }
  }
}`

**Comment by pragnagopa** [comment]
@acrov  - apologies I am having trouble reproing the issue. Can you please share a simple repro here or send it to pgopa@microsoft.com (without sharing any secrets)? Thanks!

**Comment by pragnagopa** [comment]
Running C# function app with default loglevel set to `Trace` shows following logs (copying sample output):

```
Considering key {708c5a13-1a81-495f-abec-23937298862f} with expiration date 2020-11-15 20:42:13Z as default key.
Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
Decrypting secret element using Windows DPAPI.
Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
Using key {708c5a13-1a81-495f-abec-23937298862f} as the default key.
Key ring with default key {708c5a13-1a81-495f-abec-23937298862f} was loaded during application startup.
```

Investigating if this a change of behavior from previous core tools versions

**Comment by acrov** [comment]
Hi again
Here's a default function app created by the new solution wizard in visual studio community 2019.  My only changes are to downgrade to functions V2 and netcore2.1 and to add "logLevel": {"default": "Trace"} to host.json
[FunctionApp2.zip](https://github.com/Azure/azure-functions-core-tools/files/5163541/FunctionApp2.zip)

Now change into this project and compare startup output of:
`%USERPROFILE%\AppData\Local\AzureFunctionsTools\Releases\2.54.0\cli_x64\func host start --verbose`
`%USERPROFILE%\AppData\Local\AzureFunctionsTools\Releases\2.53.0\cli_x64\func host start --verbose`

Also compare output when pinging http://localhost:7071/api/Function1

**Comment by pragnagopa** [comment]
@acrov  - Thanks. Sent a PR with the fix. Will plan for a release soon.

**Comment by pragnagopa** [comment]
Fix is merged and new version of core tools is released. @acrov  - please give it a try.

**Comment by acrov** [comment]
That's much better. Looks to be back to normal level of output and performance.  Still has the extra "Stopping the listener... " output on shutdown but that is not a problem at all.

Thank you very much.
