### ISSUE TITLE
Fix v1 build issue

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#2194]
Looks like signing is getting stuck -- see https://ci.appveyor.com/project/appsvc/azure-functions-cli/builds/34608160

**Comment by pragnagopa** [comment]
Flagging as P1 as this a release blocker.

**Comment by ankitkumarr** [comment]
This is now fixed. The issue was with the signing pipeline trying to validate strong name signing for every dll. I updated that to make sure it only validates for dlls with strong names.
