### ISSUE TITLE
Process: Remove CY19 H2 from Projects if you don't use Projects. (Minor)

### ISSUE THREAD

**Issue by jeroenhabets** [Azure/azure-functions-core-tools#2229]
Seems to me that an experiment was made to use Github's "Projects" but it makes a rather abandoned impression.

https://github.com/Azure/azure-functions-core-tools/projects

I'd suggest to clean it up. It would also remove the (1) alert counter I see next to the "Projects" tab.

**Comment by apawast** [comment]
Hi @jeroenhabets thanks for calling it out, we have closed the project.
