### ISSUE TITLE
Build native deps should check Azure Python version

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-core-tools#2236]
Assume on local devbox, user uses python 3.6 for development, when they deploy to a python 3.7 app, due to the python dependencies are resolved using the 3.6 images (e.g.  mcr.microsoft.com/azure-functions/python:2.0.12493-python3.6-buildenv), the app will not work.

We should at least add a warning message for this scenario.

https://github.com/Azure/azure-functions-core-tools/blob/55f206c9eb26cea0a801090284293d2334765841/src/Azure.Functions.Cli/Helpers/PythonHelpers.cs#L442-L453

cc: @ankitkumarr

**Comment by Hazhzeng** [comment]
@stefanushinardi

**Comment by ankitkumarr** [comment]
I wonder if even out of `--build-native-deps`, we should check if Python version locally doesn't match `FUNCTIONS_WORKER_RUNTIME_VERSION` and throw a warning when publishing to a Python function app. We should do this even for `--build remote` or other scenarios, to encourage consistency between local and Azure environment.

**Comment by stefanushinardi** [comment]
Hey @fabiocav, if you could take a look at this during sprint planning and possibly prioritize it for this sprint that would be great. Being pinged by DevDiv as they are tracking this in ML e2e review.
