### ISSUE TITLE
Building wheel for pyodbc (setup.py): finished with status 'error'

### ISSUE THREAD

**Issue by HenriqueMessa** [Azure/azure-functions-core-tools#2243]
Hello all,

I'm getting an error today deploying my local package to Azure.

Failed to build pyodbc
DEPRECATION: Could not build wheels for pyodbc which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

It was working last Friday.

**Comment by nxthm** [comment]
Started happening to me, too

Building wheel for pyodbc (setup.py): started
Building wheel for pyodbc (setup.py): finished with status 'error'
ERROR: Command errored out with exit status 1:

...


ERROR: Failed building wheel for pyodbc
Failed to build pyodbc
DEPRECATION: Could not build wheels for pyodbc which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

Using VS Code, Azure Functions 0.24.1 extension

Can no longer deploy my function.  Everything was working find last week

**Comment by bnm91** [comment]
This is also happening for me, and I also cannot deploy the function.  My output

[15:56:20+0000] Building wheels for collected packages: pyodbc
[15:56:20+0000]   Building wheel for pyodbc (setup.py): started
  ERROR: Command errored out with exit status 1:
   command: /tmp/oryx/platforms/python/3.6.12/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w44jhuyc/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w44jhuyc/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel 
-d /tmp/pip-wheel-xdu999by
[15:56:24+0000]   Building wheel for pyodbc (setup.py): finished with status 'error'

**Comment by HenriqueMessa** [comment]
Azure is being thru problems, I don't know If It is correlated. I will leave this item opened for te devs.
I upgraded my Azure App Function from Python 3.7 to 3.8 (server side) and redeployed all of my functions and that works. But, it's painful and sometimes it's impossible to redeploy everything.

**Comment by nxthm** [comment]
I, too, ended up upgrading the function to Python 3.8.5, and changed the runtime to version 3 and am now able to deploy.  Would still like to understand the root cause but I guess that will have to wait for another time

**Comment by Hazhzeng** [comment]
Thanks for reporting this issue.

We upgraded the pip version to 21.0 and enable dynamic install in the latest kudulite release (mcr.microsoft.com/azure-functions/kudulite:kudu-2.12a), which reduces the image size and lazily loading the python interpreters when the remote build starts.

The python3.6m, python3.7m and python3.8m libraries are required when building pyodbc wheels since it does not come with a manylinux distribution. https://pypi.org/project/pyodbc/#files. We're currently working on the fix.

**Comment by epmck** [comment]
So is there any work around for this yet? I just ran into this problem and it's killing me. I can't deploy any of my functions.

**Comment by Hazhzeng** [comment]
We start rollout out the fix for now. For mitigation, you can deploy with Azure Functions Core Tools,
`func azure functionapp publish <appname> --build-native-deps`.
This will resolve the native dependencies on your machine instead of using remote build.

**Comment by epmck** [comment]
> We start rollout out the fix for now. For mitigation, you can deploy with Azure Functions Core Tools,
> `func azure functionapp publish <appname> --build-native-deps`.
> This will resolve the native dependencies on your machine instead of using remote build.

I have tried this and it does not work. I get the same errors: 

3:22:32 PM : DEPRECATION: Could not build wheels for pyodbc which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
3:22:32 PM : [20:22:32+0000] Failed to build pyodbc

**Comment by zacmoody** [comment]
> We start rollout out the fix for now. For mitigation, you can deploy with Azure Functions Core Tools,
> `func azure functionapp publish <appname> --build-native-deps`.
> This will resolve the native dependencies on your machine instead of using remote build.

Is there an ETA that we should look at. We are facing similar deployment issues.
