### ISSUE TITLE
Suggestion: Do not add .gitignore when using func init --source-control false

### ISSUE THREAD

**Issue by hugo-paredes** [Azure/azure-functions-core-tools#2249]
This isn't a bug report, but a suggestion. 

When initializing a new function, using the command below, it would be good not to add the `.gitignore` file.

```bash
func init testFunction --source-control false --worker-runtime python
```

For example, when a function is initialized inside a sub-folder, it doesn't make sense to add the `.gitignore` file because it should be in the project's root folder.

Thanks.

**Comment by anthonychu** [comment]
Thanks for the suggestion. Based on what's currently in the .gitignore file, we feel that it's important to have it there even if git init is not run.
