### ISSUE TITLE
func start  non-verbose mode should hide dotnet build verbose logs

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-core-tools#2259]
## System information
- `func --version`
	3.0.2931
- `dotnet --version`
	3.1.402

## Steps
- Create an azure function v3 app with and reference 4-5 libraries.
- In each library's `*.csproj` file, add this snippet
```xml
    <LangVersion>8</LangVersion>
    <Nullable>enable</Nullable>
    <Features>strict</Features>
```
- We will notice, that running `func start` takes longer time due to the fact that `dotnet build` will produce a lot of `#nullable` warnings. This becomes more noticeable in electron based terminals where writing to terminal takes even longer which increases the time it takes `func start` to be ready.
```log
Functions/Hello.cs(43,23): warning CS8618: Non-nullable property 'TokenInfoUrl' is uninitialized. Consider declaring the property as nullable.
....
```
- This becomes more frustrating when there are multiple azure functions v3 apps in the solution and all of the projects take ~120 secs to start. 
- FYI, Visual Studio 2019 is able to circumvent this by building all projects in the solution at once and then `func start --no-build` for each function v3 app (which is faster).

## Desired Outcome
- `func start` should `dotnet build` in silent mode by default so CLI is able to host APIs faster

**Comment by apawast** [comment]
@prabh-62 Do you have a problem with the duration or that there is so much logging? Reducing the output may not make your function start faster. Also, which electron-based terminal are you using?

**Comment by prabh-62** [comment]
I use VSCode Integrated Terminal most of the time. Since, the build output generates a lot of noise, terminal has to print all the log lines and it takes forever. `func start` is usually quicker (around 10s) but the pre-requisite `dotnet build` takes around 1-2 mins on average. And having 10 azure functions projects makes it worse.

**Comment by apawast** [comment]
@prabh-62 the build output can be useful in a lot of cases, so at this time we are not looking to change the current behavior. I am closing this issue for now, but please feel free to reopen this issue if this problem arises for more people. Thank you!
