### ISSUE TITLE
Add warning when using V2 Core tools to upgrade to  V3 core tools

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-core-tools#2272]
cc @anthonychu @jeffhollan @fabiocav 
Once auto-upgrade to V3 completes, show following message when using V2 core tools

```we recommend upgrading to v3 of the function core tools unless you have pinned your application version to 2.0 http://aka.ms/coretools2```

related issue: #2248

**Comment by fabiocav** [comment]
There's already an issue tracking this and currently assigned to @kashimiz 

She mentioned she had the change done and was opening a PR

**Comment by pragnagopa** [comment]
Is this the issue: https://github.com/Azure/azure-functions-core-tools/issues/2091 ? should we close that as we will start upgrading a week from now?

**Comment by fabiocav** [comment]
I see you're referencing this other issue. Assuming this is just a verbiage update

**Comment by fabiocav** [comment]
@kashimiz can you please provide an update on that issue?

**Comment by pragnagopa** [comment]
> Assuming this is just a verbiage update

Yes, after upgrade we should update the message.

**Comment by fabiocav** [comment]
Debating whether the other work item still provides any benefit at this point

I guess it depends on how close we are to that. If we can add it to the current release, it would be great.

**Comment by jeffhollan** [comment]
Yeah I think it's just about timing. The initial work item was worded a bit more advance, this verbiage is a bit more of "this already happened" - so I suspect given that this will start in next week or two unless it is going out immenintely we may just convert to this one

**Comment by fabiocav** [comment]
We've upgraded the verbiage to be generic enough so this is no longer required.
