### ISSUE TITLE
Chocolatey packages do not correctly install x86/x64

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-core-tools#2290]
When installing Azure Functions Core Tools via Chocolatey using:
```
cinst azure-functions-core-tools-2 azure-functions-core-tools-3 -y
```

The package does not correctly point to the x64 version on 64-bit machines. Instead, it downloads and installs the 32-bit version of the tools

~~~
Installing the following packages:
azure-functions-core-tools-2;azure-functions-core-tools-3
By installing you accept licenses for the packages.
Progress: Downloading azure-functions-core-tools-2 2.7.2936... 100%

azure-functions-core-tools-2 v2.7.2936 [Approved]
azure-functions-core-tools-2 package files install completed. Performing other installation steps.

>>>>> PROBLEM HERE
Downloading azure-functions-core-tools-2
  from 'https://functionscdn.azureedge.net/public/2.7.2936/Azure.Functions.Cli.win-x86.2.7.2936.zip'
Progress: 100% - Completed download of C:\Users\Brandon\AppData\Local\Temp\chocolatey\azure-functions-core-tools-2\2.7.2936\Azure.Functions.Cli.win-x86.2.7.2936.zip (209.44 MB).
Download of Azure.Functions.Cli.win-x86.2.7.2936.zip (209.44 MB) completed.
>>>>>

Hashes match.

...

Progress: Downloading azure-functions-core-tools-3 3.0.2996... 100%

azure-functions-core-tools-3 v3.0.2996 [Approved]
azure-functions-core-tools-3 package files install completed. Performing other installation steps.

>>>>> PROBLEM HERE
Downloading azure-functions-core-tools-3
  from 'https://functionscdn.azureedge.net/public/3.0.2996/Azure.Functions.Cli.win-x86.3.0.2996.zip'
Progress: 100% - Completed download of C:\Users\Brandon\AppData\Local\Temp\chocolatey\azure-functions-core-tools-3\3.0.2996\Azure.Functions.Cli.win-x86.3.0.2996.zip (255.79 MB).
Download of Azure.Functions.Cli.win-x86.3.0.2996.zip (255.79 MB) completed.
>>>>>

Hashes match.
~~~

this causes issues w/ VSCode when debugging resulting in the error message:

![image](https://user-images.githubusercontent.com/20270743/98019409-92423d00-1db6-11eb-9dad-ccf0f5078636.png)

I believe the usage of [Install-ChocolateyZipPackage](https://chocolatey.org/docs/helpers-install-chocolatey-zip-package) is incorrect and a URL to the 64-bit zipfile is not being included.

**Comment by brandonh-msft** [comment]
I was able to _force_ an install of x64 using
```
cinst azure-functions-core-tools-2 azure-functions-core-tools-3 -y --package-parameters="'/x64:true'"
```
but this goes against the default behavior chocolatey; we should install the arch-matching version by default and only use package parameters to _override_ this behavior.

**Comment by ankitkumarr** [comment]
As @brandonh-msft said, you could install x64 version through `choco install azure-functions-core-tools-3 --params "'/x64'"` ([ref](https://github.com/Azure/azure-functions-core-tools#v3-2)).

Having it install 64 bit by default (on x86) would be -- 
a) a breaking change
b) cause inconsistency between Azure and local, as by default Azure runs a 32 bit Functions host process

Unless there's a very strong reason to change this behavior, I think we would want to avoid the breaking change and the inconsistency.

**Comment by apawast** [comment]
Closing as I believe @ankitkumarr answered the question. Please feel free to reopen if there's still an issue.

**Comment by JohnCarmichael3000** [comment]
On the Chocolately Azure Function Core Tools 3.0.3160 package page user Tyler Doerksen has helpfully noted about installing the 64-bit version in the discussion (see below). Imho, this would be even more helpful if it was in the "Description" field of the page, if anyone is reading that has modify access to it.

https://chocolatey.org/packages/azure-functions-core-tools-3#discussion
Tyler Doerksen • 4 months ago
To install the 64-bit version, which allows you to debug, you can use the command
choco install azure-functions-core-tools-3 --params="'/x64:true'"
