### ISSUE TITLE
Local Debug for Azure Functions failing due to missing libraries

### ISSUE THREAD

**Issue by shoaibazeemsiddique** [Azure/azure-functions-core-tools#2296]
Below issue came back in release 2020.10.332292344
https://github.com/Azure/azure-functions-core-tools/issues/2026#issuecomment-642168916

**Comment by apawast** [comment]
@Hazhzeng @vrdmr could you please take a look at this?

**Comment by vrdmr** [comment]
@shoaibazeemsiddique - Can you please try the latest version of the Python Extension - v2020.11.367453362?

I haven't been able to reproduce it yet on the newest version of the Python Extension. I'll try downgrading it and see if it reproduces. Please let me know.

/cc @stefanushinardi

**Comment by shoaibazeemsiddique** [comment]
My issue was resolved after deleting all the breakpoint issue, apologies for the late response.
