### ISSUE TITLE
Custom handler templates do not work

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2306]
```
func init --custom
func new
```

VS Code appears to be picking up the templates, but not working in Core Tools.

/cc @pragnagopa @yojagad

**Comment by yojagad** [comment]
Thanks for reporting this. I checked this out and it looks like core-tools picks up templates in the context of non-extension bundle. In other words, the below commands work

````
func init --no-bundle --custom
func new
````

In context of bundles, it looks the latest version on prod CDN is still only 2.0.0 https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index-v2.json . It looks like none of the later releases went to prod CDN yet 
https://azfunc.visualstudio.com/Azure%20Functions/_release?definitionId=24&view=mine&_a=releases

**Comment by pragnagopa** [comment]
Thanks for updating CDN @yojagad .  Initial testing looks good. @anthonychu - please reactivate if you see any other issues.
