### ISSUE TITLE
Outdated func warning breaks parsing of --version command

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-core-tools#2307]
If I run `func --version` on v2, I'm seeing this:

> You are using an outdated version of the Azure Functions Core Tools. For more information, please see: https://aka.ms/func-v2-upgrade
> 2.7.3023

Please print the warning to stderr (it's currently going to stdout) or just remove it for this command. VS Code fails to parse the version as-is, affecting a number of version-specific scenarios

**Comment by anthonychu** [comment]
Sorry we didn't consider this scenario. Let's see if we can get this fixed relatively quickly.

**Comment by fabiocav** [comment]
@soninaren is currently working on this. Change is in place, working on the build for release.

**Comment by soninaren** [comment]
This is released to tooling feed. Pending npm release.

**Comment by soninaren** [comment]
npm release is complete
