### ISSUE TITLE
Assemblies in Azure.Function.Cli fail to refresh

### ISSUE THREAD

**Issue by bnuckels** [Azure/azure-functions-core-tools#232]
About a week ago I began getting runtime errors in local debug, using VS2017 Preview 2 w/ latest Azure Functions extension at the time. The first error was complaining about func.exe, seemed like the file was corrupt. I eventually deleted func.exe from ~/AppData/Local/Azure.Functions.Cli/1.0.0 and ran and got past that error. I then began receiving errors about Newtonsoft.Json package version. Unable to load assembly Newtonsoft.Json ver 6.0.0.  I spent quite a lot of time trying to understand why. I figured out I did have a package, Microsoft.Azure.Keyvault, which had a dependency on Newtonsoft.Json v6. I downgraded this to a prior version which did not have the dependency. No luck. 

I used Modules to see what was loading and oddly, noticed that Newtonsoft.Json was coming from the Azure.Function.Cli directory and was version 9, even though my project was currently on version 10.0.3. I downgraded the project to Newtonsoft v9 to see if anything would happen. No change. So finally, I just decided to delete the Azure.Function.Cli/1.0.0 directory to see what would happen. I have no real understanding of how this directory is managed. But, that solved the problem. Rebuilding my project created that directory. 

Lastly, I decided to upgrade my packages again in my project. I upgraded Newtonsoft.Json to 10.0.3 and ran the app.  The DLL in the A.F.Cli folder remains v 9.0.1 but now in my Modules window I can see that v10 is also loaded.

Unfortunately I cannot reproduce this error but clearly something got corrupted and was preventing dependencies from properly resolving.

**Comment by ahmedelnably** [comment]
Closing this, please reopen if it still the case in the latest version
