### ISSUE TITLE
node js azure function fails on linux runtime. 'object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by dilin-MS** [Azure/azure-functions-core-tools#2322]
Hi, I am developing a customized azure functions binding. Have a node js function project and install our binding, the project can run correctly under windows runtime. However, under linux runtime, the `func host start` will encounter `object reference not set to an instance of an object` error. Any suggestions?

```bash
$ func start

Azure Functions Core Tools
Core Tools Version:       3.0.2996 Commit hash: c54cdc36323e9543ba11fb61dd107616e9022bba
Function Runtime Version: 3.0.14916.0


Functions:

        GET_POST_MODSReturnedWithCorrectResult: [GET,POST] http://localhost:7071/api/GET_POST_MODSReturnedWithCorrectResult

For detailed output, run func with --verbose flag.
[2020-12-04T01:35:04.737Z] Worker process started and initialized.
[2020-12-04T01:35:05.424Z] Executing 'Functions.GET_POST_MODSReturnedWithCorrectResult' (Reason='This function was programmatically called via the host APIs.', Id=ceba8fc5-8cb5-4a26-94d0-1665d90e04da)
[2020-12-04T01:35:05.580Z] Executed 'Functions.GET_POST_MODSReturnedWithCorrectResult' (Failed, Id=ceba8fc5-8cb5-4a26-94d0-1665d90e04da, Duration=180ms)
[2020-12-04T01:35:05.582Z] System.Private.CoreLib: Exception while executing function: Functions.GET_POST_MODSReturnedWithCorrectResult. Microsoft.Azure.WebJobs.Extensions.MODS: Object reference not set to an instance of an object.
[2020-12-04T01:35:09.609Z] Host lock lease acquired by instance ID '00000000000000000000000082964D2C'.
```
Deploying to azure functions has the same result.

Env:
```
$ func -v
3.0.2996

$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core run
```

I am having the same node, func, dotnet version in my local linux / windows enviroment, but the error only occurs on linux environment. Since my function binding is written in C# and my function project is javascript, I use ` func extensions install --package Microsoft.Azure.WebJobs.Extensions.MODS --version 0.1.3 --source "localNuget"` to install it.

Please help!

**Comment by apawast** [comment]
Hi @dilin-MS, could you please provide us with a repro and stack trace?

**Comment by dilin-MS** [comment]
Hi, I occasionally figured out the root cause.

We have a key-value settings `"AllowedAppIds": ""` in `local.settings.json` configuration file. When azure function reads this config (empty string) from this file, it behaves differently under linux / win. 

We have a `AllowedAppIdsStr.Split(';')` function inside our MODS extension. Under Win, the empty string is successfully read, but under Linux, the AllowedAppIdsStr gets `null`, which cause the `Split()` function to crush. We currently add nullOrEmpty checking before the `Split()` function to fix the issue. 

However, we still have no idea why the setting is read as empty string under Win but as null under Linux.
Do you have any idea?

Thanks!

**Comment by kepikoi** [comment]
Probably totally unrelevant but `Object reference not set to an instance of an object.` was once thrown at me while trying to install the function extensions via `func extensions install --typescript` The culprit was an empty `functions.json` in one of my functions

**Comment by anthonychu** [comment]
@dilin-MS This is known behavior for how environment variables currently work in Functions Core Tools. Sounds like you might have to add some logic to guard against this. Related: https://github.com/Azure/azure-functions-core-tools/pull/1384

**Comment by dilin-MS** [comment]
Thanks. We can close this issue.
