### ISSUE TITLE
'func host start' doesn't respect VSCode workspace virtual environment

### ISSUE THREAD

**Issue by fisherkuan** [Azure/azure-functions-core-tools#2329]
Started an Azure Functions project with the VSCode UI, following this [tutorial](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python).

In settings.json, "azureFunctions.pythonVenv": ".venv" is set. Python interpreter points to Python 3.8.6 64-bit ('.venv'). As I started to run with command 'func host start' (see attached image). I saw that the dependencies are installed in the .venv paths as expected, but then I got module-not-found errors because python didn't run on the virtual environment. I printed out the python path with print("running Python from: ", sys.executable) to be sure about the issue.
![Screenshot 2020-12-08 121329](https://user-images.githubusercontent.com/75672235/101477802-0345b900-3950-11eb-90dc-1c968ef8d5f1.png)

I followed this previously reported [issue](https://github.com/Azure/azure-functions-core-tools/issues/2242) but it didn't solve my problem.

**Comment by apawast** [comment]
@vrdmr @Hazhzeng could you please take a look at this?

**Comment by fisherkuan** [comment]
The problem was solved by uninstalling/reinstalling Python.
