### ISSUE TITLE
The remote server returned an error: (407) Proxy Authentication Required.

### ISSUE THREAD

**Issue by ashokpatel24** [Azure/azure-functions-core-tools#233]
Getting below error while Run Azure Function from Visual Studio
A ScriptHost error has occurred
Microsoft.ServiceBus: The remote server returned an error: (407) Proxy Authentication Required. TrackingId:283aa620-3972-4bc8-becd-a6ce08b597af, SystemTracker:messages, 
System: The remote server returned an error: (407) Proxy Authentication Required.

**Comment by ahmedelnably** [comment]
Closing. Please reopen if you still encountering the error with the latest version
