### ISSUE TITLE
Add Rust function templates

### ISSUE THREAD

**Issue by seeplusplus** [Azure/azure-functions-core-tools#2341]
Is this something that would be desirable to include? It looks like there's support for Azure functions in the Rust ecosystem,
https://docs.rs/azure-functions/0.11.0/azure_functions/index.html

If this is something worth including I wouldn't mind submitting a PR for it. (I am assuming that given the link above the only work to be done is simply adding the templates, but I could be wrong)

**Comment by anthonychu** [comment]
That's a great project but it's not an official Azure Functions project. It's no longer being maintained. For Rust, we recommend using our [custom handlers](https://docs.microsoft.com/en-ca/azure/azure-functions/create-first-function-vs-code-other?tabs=rust%2Clinux) feature. We do have templates support for scaffolding function.json files for custom handler projects.

You do bring up a good point. There's currently no way to plug in additional templates. Created an issue here to track: https://github.com/Azure/azure-functions-templates/issues/1003
