### ISSUE TITLE
Docs: clarify support for running from package in Linux Consumption

### ISSUE THREAD

**Issue by maximivanov** [Azure/azure-functions-core-tools#2356]
Just spent some time figuring out why my Terraform scripts and Azure Functions Core Tools try to override each other's output.

Terraform script which I use to provision Azure resources, creates a function app (Linux Consumption App Service plan) with `WEBSITE_RUN_FROM_PACKAGE=1` App Setting.
Later when I run `func azure functionapp publish ...` to upload function code to the Function App it overrides `WEBSITE_RUN_FROM_PACKAGE` to contain the url of a blob where the code is stored.

I've checked this:
- https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package
- https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies
- and (most helpfully) https://github.com/Azure/azure-functions-core-tools/issues/1086

And unless I'm missing something I conclude that Linux Consumption does not support deploying a package to the function host (`WEBSITE_RUN_FROM_PACKAGE=1`). 
It does support deploying a package to an external storage though, e.g. Azure Blob Storage (`WEBSITE_RUN_FROM_PACKAGE=<url>`).

The research was undoubtedly educational but I believe it's worth stating supported deployment methods explicitly in the docs. *Especially* considering `WEBSITE_RUN_FROM_PACKAGE=1` is recommended as a way to reduce cold start times which encourages people (myself included) to use it to deploy to Linux Consumption Function Apps.

**Comment by balag0** [comment]
@maximivanov Thanks for the feedback and this is a great point. I have openend the below issue to improve the docs
https://github.com/MicrosoftDocs/azure-docs/issues/67794
