### ISSUE TITLE
Optional route parameters throw exception when they are omitted

### ISSUE THREAD

**Issue by stevetayloruk** [Azure/azure-functions-core-tools#236]
Hi, 

It seems that this issue is fixed on Azure but when running locally the error still occurs:

https://github.com/Azure/azure-webjobs-sdk-script/issues/1216

Thanks

Steve

**Comment by jg11jg** [comment]
Agreee.  I get exactly this issue.
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "meals/{id1:int?}")]HttpRequest req, int? id1, TraceWriter log)
>Binding data does not contain expected value 'id1'.

**Comment by EvanMulawski** [comment]
I am experiencing this issue as well. 

- VS 2017 15.7.4
- Azure Functions and Web Jobs Tools 15.0.40617.0
- Microsoft.NET.Sdk.Functions 1.0.13 (Web Jobs 3.0.0-beta5)
- targeting netstandard 2.0

/cc @mathewc

**Comment by JohnReeson** [comment]
It has been solved according to this [merged PR](https://github.com/Azure/azure-functions-host/pull/3352). Issue can be closed.

**Comment by mathewc** [comment]
@fabiocav If your PR resolves this, can you please close?

**Comment by fabiocav** [comment]
Indeed, this has been fixed but the issue wasn't associated. Closing as resolved.
