### ISSUE TITLE
Outdated function warning [npm]

### ISSUE THREAD

**Issue by blitzmann** [Azure/azure-functions-core-tools#2363]
Hello,

I'm receiving the following warning when running functions locally:

> You are using an outdated version of the Azure Functions Core Tools. For more information, please see: https://aka.ms/func-v2-upgrade

it's odd because the output from `func -- version` does not match what I have in `packages.json`, and indeed is higher than the core tools that are released on npm

packages.json:
```
...
 "devDependencies": {
        "@azure/functions": "^1.2.2",
        "typescript": "^3.3.3",
        "azure-functions-core-tools": "^2.7.3188"
    }
```

```
> npm start
...
Azure Functions Core Tools
Core Tools Version:       2.7.3188 Commit hash: f5984038c7377e9437f71191bff1d5818dd1fa8d
Function Runtime Version: 2.0.14786.0

AZURE_FUNCTIONS_ENVIRONMENT: Development
...
```

```
> func --version
3.0.2534
```

Additionally, our Function App on Azure proper is using runtime version ~3 (but that bit of text above says that I'm running 2.0.14786.0)

![image](https://user-images.githubusercontent.com/3904767/102901933-39009c80-443c-11eb-82b4-0b8fdedc4391.png)

So it looks like I need to upgrade my runtime, but how would I do this?

I'm using VS Code and the various Azure extensions provided to build out and manage functions.

I can provide more details if requested, just let me know :)

**Comment by apawast** [comment]
Hi @blitzmann could you please try updating this line "azure-functions-core-tools": "^2.7.3188" to ""azure-functions-core-tools": "^3.0.3160"?

**Comment by blitzmann** [comment]
Thanks @apawast! That works!
