### ISSUE TITLE
Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by profatsir** [Azure/azure-functions-core-tools#2364]
I try to local debug the azure function, but got issue. Actually I just follow the instruction to build and tested with below link, but not work.
The instruction is here [Debug he Azure Functions Python code locally](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-04?tabs=powershell) , and I did not modified the code at all.
While I try to run debug in visual studio code, it pop up error.

> Executing task: .venv\Scripts\activate ; func host start

> Found Python version 3.8.6 (py).

> Azure Functions Core Tools Core Tools Version: 3.0.3160 Commit hash: 00aa7f43cc5c5f15241b5e6e5363256f19ceb990 Function Runtime Version: 3.0.14916.0

> **Value cannot be null. (Parameter 'provider')**

> Terminal` will be reused by tasks, press any key to close it.

I have no idea what's wrong after I search lots of topic in GitHub or stackoverflow. Finally I remove the azure function extensionBundle in the host.json and semes work. I also find some discussion that remove the temp file, but I can't find any temp folder in my windows machine. The similar issue also can be found here #2232 

below is my environment:
Windows 10
Python 3.8.6 
Function Core Tools Version:3.0.3160 
Python packages azure-functions 1.50

Anyone can provide the suggestion how to fix it?

**Comment by blitzmann** [comment]
Unsure if it's the same issue, but we're having something similar: #2365

**Comment by profatsir** [comment]
> Unsure if it's the same issue, but we're having something similar: #2365
> 
> We tried to remove the `extensionBundle` but the runtime complained about not having it.

Actually I have two machine with same setup. One remove the extensionbundle not work, show error that same like you...but the other one work. I don't know is there any magic here.

**Comment by apawast** [comment]
Hi @profatsir, could you please try setting the environment variable CLI_DEBUG=1 before running and sharing the output with us?

**Comment by dgvives** [comment]
@profatsir I tried to reproduce your error and haven't managed to. What kind of azure function did you create? 

```
> Executing task: .venv\Scripts\activate ; func host start <

Found Python version 3.8.6 (py).

Azure Functions Core Tools
Core Tools Version:       3.0.3160 Commit hash: 00aa7f43cc5c5f15241b5e6e5363256f19ceb990
Function Runtime Version: 3.0.14916.0


Functions:

        HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1

For detailed output, run func with --verbose flag.
[2021-01-08T12:09:13.621Z] Host lock lease acquired by instance ID '000000000000000000000000F4384D96'.
[2021-01-08T12:09:15.439Z] Worker process started and initialized.
[2021-01-08T12:09:52.355Z] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=f4b4edb6-903f-442b-a147-e2ca991834bb)
[2021-01-08T12:09:52.415Z] Python HTTP trigger function processed a request.
[2021-01-08T12:09:52.495Z] Executed 'Functions.HttpTrigger1' (Succeeded, Id=f4b4edb6-903f-442b-a147-e2ca991834bb, Duration=182ms)
```

**Comment by profatsir** [comment]
> Hi @profatsir, could you please try setting the environment variable CLI_DEBUG=1 before running and sharing the output with us?

Hi @apawast , finally I try to Explicitly install extensions as the work around, thanks for your info. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register

**Comment by profatsir** [comment]
> @profatsir I tried to reproduce your error and haven't managed to. What kind of azure function did you create?
> 
> ```
> > Executing task: .venv\Scripts\activate ; func host start <
> 
> Found Python version 3.8.6 (py).
> 
> Azure Functions Core Tools
> Core Tools Version:       3.0.3160 Commit hash: 00aa7f43cc5c5f15241b5e6e5363256f19ceb990
> Function Runtime Version: 3.0.14916.0
> 
> 
> Functions:
> 
>         HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1
> 
> For detailed output, run func with --verbose flag.
> [2021-01-08T12:09:13.621Z] Host lock lease acquired by instance ID '000000000000000000000000F4384D96'.
> [2021-01-08T12:09:15.439Z] Worker process started and initialized.
> [2021-01-08T12:09:52.355Z] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=f4b4edb6-903f-442b-a147-e2ca991834bb)
> [2021-01-08T12:09:52.415Z] Python HTTP trigger function processed a request.
> [2021-01-08T12:09:52.495Z] Executed 'Functions.HttpTrigger1' (Succeeded, Id=f4b4edb6-903f-442b-a147-e2ca991834bb, Duration=182ms)
> ```

Hi @dgvives , finally I try to Explicitly install extensions as the work around, thanks for your info. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register

**Comment by profatsir** [comment]
finally I try to Explicitly install extensions as the work around, thanks for your info. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register
