### ISSUE TITLE
Cannot connect to Service Bus locally (via emulator or on Azure) [TypeScript]

### ISSUE THREAD

**Issue by blitzmann** [Azure/azure-functions-core-tools#2365]
Hi there,

We're trying to get a function working for Azure Service Bus. We want to use the emulator using the VS Code extension Azurite, so that we can develop the queue locally and then deploy. However, we cannot seem to get the function to run with the emulator OR with connection string for the cloud Service Bus.

I have a demo repo available here: https://github.com/blitzmann/azure-func-test Please pull, npm install, and `npm start` to see what I'm talking about. 

When I run `npm start` I get the following error:
```
[12/22/2020 5:10:00 PM] A host error has occurred during startup operation '2af7ed63-b94d-40cf-847b-32373ae0fe94'.
[12/22/2020 5:10:00 PM] System.Private.Uri: Value cannot be null. (Parameter 'uriString').
[12/22/2020 5:10:00 PM] Stopping JobHost
Value cannot be null. (Parameter 'provider')
```

You should be able to see in the repo what the settings are, but for verbosity:
`function.json`
```
{
  "bindings": [
    {
      "name": "mySbMsg",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "myinputqueue",
      "connection": "AzureWebJobsStorage"
    }
  ],
  "scriptFile": "../dist/ServiceBusQueueTrigger1/index.js"
}
```

`local.settings.json`
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "node"
  }
}
```

I have the queue emulator running on `localhost:10001` and blob service running on `localhost:10000` (default settings via Azurite)

It is my understanding that using `UseDevelopmentStorage=true` should instruct the runtime to look at my emulator for the queue.

Additionally, if I replace `UseDevelopmentStorage=true` with the actual connections string to Azure `DefaultEndpointsProtocol=https;AccountName=myfunctionstorage;AccountKey=mysupersecretkey;EndpointSuffix=core.windows.net` I get the same issue:

```
[12/22/2020 5:16:45 PM] A host error has occurred during startup operation '8571f4b7-2db4-4372-afed-e231ec2679a1'.
[12/22/2020 5:16:45 PM] System.Private.Uri: Value cannot be null. (Parameter 'uriString').
[12/22/2020 5:16:45 PM] Stopping JobHost
Value cannot be null. (Parameter 'provider')
```

Here's a screenshot of my VSCode showing the emulators running:

![image](https://user-images.githubusercontent.com/3904767/102915644-22fcd700-4450-11eb-924d-e92c04e1c8f3.png)

Windows 10
VS Code
Typescript

**Comment by nnickd** [comment]
I am also having this issue, please help!

**Comment by blitzmann** [comment]
I think I'm coming to the realization that I'm confusing Service Bus and Queues. We were using a SB trigger, but creating queues. Apparently there is no service bus emulator for local development, if we wanted to go that route we would have to have a dev environment set up in azure

**Comment by blitzmann** [comment]
Going to close this issue as I believe it is user error, everything is now working fine with the distinction between SB and queues :D
