### ISSUE TITLE
Azure function v3 with blob trigger is using deprecated WindowsAzure.Storage library

### ISSUE THREAD

**Issue by harisubramaniam1** [Azure/azure-functions-core-tools#2371]
I tried creating an Azure function v3 project with .net core 3.1 and with blob trigger using Vs2019 and it seems to refer WindowsAzure.Storage 9.3.3. Isn't that storage library deprecated?

**Comment by apawast** [comment]
@fabiocav @brettsam do either of you know about this?

**Comment by fabiocav** [comment]
The latest major version of the storage extensions, 4.x, uses the Storage SDK 11.x https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/4.0.3

You can just update your storage reference to ensure you're on the latest version. We'll follow up to ensure the template is updated as well.
