### ISSUE TITLE
"Error calling sync triggers (BadRequest)" on Linux Elastic Premium

### ISSUE THREAD

**Issue by maximivanov** [Azure/azure-functions-core-tools#2375]
**App Service plan:** 
Linux Elastic Premium (EP1)

**Function App name:** 
`adauthfaapim-dev-function-app`

**Region:** 
East US

**Expected:** 
Publishing application code with Azure Functions Core Tools succeeds

**Actual:**
```
# func azure functionapp publish adauthfaapim-dev-function-app
Getting site publishing info...
Uploading package...
Uploading 9.08 KB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = 'd8cc727b-f7ff-4ec4-b16d-df6b0f509740'.
```

Running with `CLI_DEBUG=1` renders this:

```
{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}
```

Let me know if you need further details. Thanks.

**Comment by apawast** [comment]
Hi @maximivanov, what language are you using for this?

**Comment by maximivanov** [comment]
@apawast in this case it's a basic hello world Node.js application.

**Comment by maximivanov** [comment]
I managed to make it work but I would appreciate some clarification on the behaviour I see.

By reverse-engineering another Function App that is working correctly in a Linux EP plan, I figured 2 application settings had to be added for the sync triggers task to succeed:

```
"WEBSITES_ENABLE_APP_SERVICE_STORAGE" = true,
"FUNCTIONS_WORKER_RUNTIME" = "node",
```

Whenever I remove any of these from the app configuration, I get the same error during `func publish`.

I get how `FUNCTIONS_WORKER_RUNTIME` is required and that makes sense.

What I don't understand is the implicit requirement of `WEBSITES_ENABLE_APP_SERVICE_STORAGE`.

My online search didn't yield any result. The setting is usually mentioned in the context of container deployment which is not my case.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings does not even list it.

- Why is `WEBSITES_ENABLE_APP_SERVICE_STORAGE = true` required in the context of a non-containerized app deployed to a Linux Elastic Premium plan?
- Should the setting be mentioned on the App Settings page in the docs?
- If it is required, should there be some hint in the error message returned by the Functions Core Tools?

**Comment by maximivanov** [comment]
@apawast should we expect any update on this? Let me know if there's a better suited repository to open this issue. Thanks!

**Comment by balag0** [comment]
WEBSITES_ENABLE_APP_SERVICE_STORAGE
Set this to false if you are using a custom container that includes all your functions in the image directly.
Set this to true if you are using (a blessed functions image or your own custom container based on the blessed image) and the functions are deployed separately.

In this case, the value should be true since the functions are not part of the container being deployed.

**Comment by maximivanov** [comment]
Hi @balag0, not sure what you mean by a blessed functions image. To clarify, I'm not using Docker in my app (though I'm aware it's used by Azure behind the scenes to run it). 

I'm trying to deploy a non-containerized http-triggered nodejs function into a Linux EP1 hosting plan. Seems like a basic use case to me... This `WEBSITES_ENABLE_APP_SERVICE_STORAGE=true` requirement coming out of the blue is confusing. 

Can you confirm it has to be set to true in the case like above? I will open a new issue in the documentation repo then for it to be added to the docs.

**Comment by balag0** [comment]
I added some notes on this appsetting at 
https://github.com/Azure/Azure-Functions/wiki/When-and-Why-should-I-set-WEBSITE_ENABLE_APP_SERVICE_STORAGE

Could you please check if that answers your question. Setting it to true or not setting the appsetting should result in the same behaviour. In your case you shouldn't have to set this appsetting at all.

**Comment by maximivanov** [comment]
@balag0  thanks for creating the wiki page! It definitely helps. Please see my comments below.

1. From what I understand if the setting is `true` code deployment (e.g. ZIP deploy) will publish code to that shared directory.
Both existing and newly launched FA instances will automatically get access to the code via the mounted volume.
Out of curiosity, what would happen if the setting is `false` and I do a ZIP deploy? Will the code never be mounted into the container (effectively making the container useless)? To rephrase what's in the wiki, `WEBSITE_ENABLE_APP_SERVICE_STORAGE=false` makes sense ONLY if the container has the code packaged in, otherwise container has no way to see the code. Is that correct?

2. I tried to reproduce the issue once again and I couldn't. I was using the same Terraform template to provision the function app as previously; the same hello world nodejs function and the same `func` command to publish the code. Not sure if any of the underlying dependencies has changed or if I was unlucky originally. I guess we can close the issue.

**Comment by balag0** [comment]
Great.
1) If WEBSITE_ENABLE_APP_SERVICE_STORAGE=false and if you do a zipdeploy, the deployed contents will be stored in the local storage of a single instance. If/when that instance restarts the contents will be lost and also any other concurrent / new instances will never see those deployed contents. Yes. Correct.
2) It can sometimes take a little bit of time for the container to spin up if the app is new or if the image was updated recently. Looking at the error message (Service Unavailable), my guess is the container was still warming up and retries would have worked.

**Comment by maximivanov** [comment]
Got it. I will re-open if I see this issue in the future. Closing now. Thanks for the comments!
