### ISSUE TITLE
Add Support for Ubuntu 20.10 Groovy Gorilla 

### ISSUE THREAD

**Issue by rajeshr6r** [Azure/azure-functions-core-tools#2376]
Hi,

Is there a plan to extend support for Ubuntu 20.10 . The following URL contains information . However when I attempted to add the packages and install the tools , I get an error that the package couldnt be found . . This URL is not a part of the documentation yet and I guessed it  . 

https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb

**Comment by rajeshr6r** [comment]
Hello , thought of circling back on this to see if there's any hope for support for 20.10 ?

**Comment by dcat52** [comment]
@rajeshr6r I followed the instructions under **linux** on this page https://www.npmjs.com/package/azure-functions-core-tools

They worked for me with Kubuntu 20.10
So fart I have only tested installing to work (not using it) but its a start

**Comment by rajeshr6r** [comment]
Hello Davis, 
Thanks for this .Will check this and get back to  you .

**Comment by rajeshr6r** [comment]
> @rajeshr6r I followed the instructions under **linux** on this page https://www.npmjs.com/package/azure-functions-core-tools
> 
> They worked for me with Kubuntu 20.10
> So far I have only tested installing to work (not using it) but its a start

Hi Davis,

Thanks this worked . I'm now able to debug functions locally

**Comment by danelliottster** [comment]
> > @rajeshr6r I followed the instructions under **linux** on this page https://www.npmjs.com/package/azure-functions-core-tools
> > They worked for me with Kubuntu 20.10
> > So far I have only tested installing to work (not using it) but its a start
> 
> Hi Davis,
> 
> Thanks this worked . I'm now able to debug functions locally

Which set of instructions on this page worked for Ubuntu 20.10?

Thank you, dan

**Comment by rajeshr6r** [comment]
Hi

I used the option for Other Linux distributions for my Ubuntu 20.10
instance. It worked.

Thanks

Rajesh Rajamani
+91-9819937639
