### ISSUE TITLE
C# Http Triggered function stops after 2 requests on Azure

### ISSUE THREAD

**Issue by Pelago** [Azure/azure-functions-core-tools#240]
Hi,
I have a Azure Function running smoothly on local dev environment but as I deploy and run it on Azure it stops after 2 sequential request from test sender application with a timeout on HttpWebResponse. I do not even get a HttpWebResponse Statuscode, the connection just times out. 
My test application can send x times 96 requests but it does not matter which requests I comment out in the test application, the Azure function always times out after 2 sequential requests.
I can restart my test application and get the same scenario. This does not happen when I run the Azure function locally.

In Application insights on the Azure deployment I get a System.NullReferenceException on the following method “belokDataConnector.belokData+<Run>d__3.MoveNext”

Pleace Advice on how to understand this exception.

**Comment by Pelago** [comment]
Is this question posted in the wrong repository? Please advice on where to post it.

**Comment by ahmedelnably** [comment]
Closing this, it should be posted in Azure/azure-functions-host
