### ISSUE TITLE
How to set queueLength to KEDA ScaledObject?

### ISSUE THREAD

**Issue by xsoheilalizadeh** [Azure/azure-functions-core-tools#2400]
How to set `queueLength` for a KEDA trigger through `func` CLI or anything like host.json or local.settings.json?

PS. #1293 didn't solve my problem.

**Comment by apawast** [comment]
@xsoheilalizadeh are you saying you already tried changing it in the functions.json and it didn't work? 

Adding @ahmelsayed if that is the case.
