### ISSUE TITLE
KEDA V2 Helper Not Handling For Default Connection Variable Names

### ISSUE THREAD

**Issue by prqgdbc** [Azure/azure-functions-core-tools#2404]
Currently the KEDA V2 helper will not use the supported default connection variable names of AzureWebJobsStorage in the case of Blob or Storage queue triggers, or AzureWebJobsServiceBus in the case of Service Bus triggers.

These defaults are referenced here:
Service Bus: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#configuration

Blob Storage: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#configuration

Queue Storage: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger?tabs=csharp#configuration

Attempting to deploy any of these triggers to Kubernetes without specifying the connection variable name in the trigger results in:
`The given key 'connection' was not present in the dictionary.`

**Comment by tomkerkhove** [comment]
Sorry about that :/

**Comment by prqgdbc** [comment]
No problem at all! The defaults are a little weirdly documented, and not every trigger seems to have one. Very easy to miss.

**Comment by apawast** [comment]
@tomkerkhove are there any further action items required for this?

**Comment by tomkerkhove** [comment]
The PR looks good to me, afaik

**Comment by apawast** [comment]
Closed by PR #2405
