### ISSUE TITLE
func kubernetes deploy should deploy to the current namespace, not the default

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-functions-core-tools#2407]
`func kubernetes deploy` should deploy to the current namespace, not the default.

## Current behavior

Currently, `func kubernetes deploy` always specifies `namespace: default`. 

## Expected behavior

I would expect it to omit the namespace since it was not specified so that it uses the default namespace from `KUBECONFIG` instead.

## Other

I know `--namespace` allows you to specify a namespace but I would propose to leave out the namespace if it's not specified instead as it is confusing.

You can set a different namespace as following:
> k config set-context kubernetes-demos --namespace microservices-with-apim

Happy to contribute this if people agree.

**Comment by apawast** [comment]
@ahmelsayed can you please take a look at this?

**Comment by ahmelsayed** [comment]
I think it makes sense @tomkerkhove. Let me know if you still want to take a stab at it or if you'd like me to.

**Comment by tomkerkhove** [comment]
I'm happy to pick this up, but could be a few days; if OK

**Comment by ahmelsayed** [comment]
Sounds good. Thanks Tom!

**Comment by ahmelsayed** [comment]
Fixed in https://github.com/Azure/azure-functions-core-tools/pull/2434
