### ISSUE TITLE
Attaching a debugger to Azure Function app running in a container 

### ISSUE THREAD

**Issue by mygithubkas** [Azure/azure-functions-core-tools#2410]
Hi guys,

I'm totally stuck and can't figure this out.
I have the standard boiler-plate timer trigger function written in Python created as followed 

 **func init -docker**

Back in the editor I add the Docker compose files to my workspace.
Everything works fine including the normal F5 debug and I can step through code - All good.

When I run the container, I can't attach a debugger.

My steps are as follows:

1) Either,  I run the container with a Compose Up on Docker-Compose.debug or  from the command shell.

    command: ["sh", "-c", "pip install debugpy -t /tmp && 
    python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 mytrigger\__init__.py "]  ports:  5678:5678

2) Once the container is running I have considered 

   Attach using Process ID -  but which process ?  
   Attach to remote debug server.

Breakpoints just are not hit in any case.
What am I missing here ?

Thanks for your help,

**Comment by apawast** [comment]
@Hazhzeng can you please take a look at this?

**Comment by mygithubkas** [comment]
> @Hazhzeng can you please take a look at this?

I can provide further details to help if you require.

Thank you for your help

**Comment by anthonychu** [comment]
Closing in favor of #2416
