### ISSUE TITLE
Remote Debugging an 'Azure Functions timer trigger' 

### ISSUE THREAD

**Issue by mygithubkas** [Azure/azure-functions-core-tools#2416]
Hello, 
I hope somebody out there can help.

I have a Dev environment which is working perfectly, except for one small issue.
My script runs just once and then exits the container.
I was hoping it would run indefinitely - since it is a timer trigger. 

What am I doing wrong?  

**Docker-Compose.yml:**
```services:
  sfunc:
    image: sfunc
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --log-to-stderr --wait-for-client 
      --listen 0.0.0.0:5678  TimerTrigger/__init__.py "]
    ports:
      - 5678:5678
``` 

**Function.json:**
```{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "mytimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */1 * * * *"
    }
  ]
}

```

**Comment by anthonychu** [comment]
@mygithubkas Can you explain what you are trying to do?

Do you want to run a local dev environment in a container? If you are, are you using VS Code to attach the debugger?

Or are you building a production container for deployment somewhere, and you want to run the container locally?

**Comment by mygithubkas** [comment]
This is finally working, so please close this.

We managed to debug the function app container via Remote extensions, by opening the folder in a container, ensuring that extensions were installed in that container and then selecting 'Python: Current File' to run and hit a breakpoint.

**Comment by anthonychu** [comment]
Great. Was going to recommend using the remote extension. Glad it's working!
