### ISSUE TITLE
fetch-connection-string is wrong in doc

### ISSUE THREAD

**Issue by Tinathnath** [Azure/azure-functions-core-tools#242]
Hi team !
I just followed the tutorial on MS Doc [this one](https://docs.microsoft.com/fr-fr/azure/azure-functions/functions-run-local)

In the `Configure app settings` section, the command for fetching storage account's connection string is wrong. The doc says `func azure functionapp storage fetch-connection-string <StorageAccountName>` but it does not work. The correct command is `func azure storage fetch-connection-string <StorageAccountName>`

Good job with the CLI, thought !

**Comment by ahmedelnably** [comment]
Closing as Resolved
