### ISSUE TITLE
Azure Functions runtime is unreachable

### ISSUE THREAD

**Issue by mygithubkas** [Azure/azure-functions-core-tools#2422]
I see this error when I go to
My Function App > Functions

And there are no functions listed for this containerised function app.

Any ideas what is behind this ?

**Comment by balag0** [comment]
Are you using your custom image or one of the published function images? If it is a custom image can you check if you have the following appsetting 
WEBSITES_ENABLE_APP_SERVICE_STORAGE = false

**Comment by mygithubkas** [comment]
I have WEBSITES_ENABLE_APP_SERVICE_STORAGE = false. 

Is that correct for a custom image ?

**Comment by balag0** [comment]
Yes. Correct. Can you share the appname 
You can use https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately if required.

**Comment by mygithubkas** [comment]
sure: https://dockerfunc.azurewebsites.net/

**Comment by balag0** [comment]
Is the container starting up successfully locally? I see the following error from container logs
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by mygithubkas** [comment]
> Is the container starting up successfully locally? I see the following error from container logs
> standard_init_linux.go:211: exec user process caused "exec format error"

Locally the container runs fine and the func host starts the timer trigger.
Locally it runs with the Storage Emulator

**Comment by balag0** [comment]
Thanks. This thread lists some of the reasons for this error
https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error

If none of those apply, would you be able to provide a minimal repro docker file and the commands you are using to build the image to investigate further.

**Comment by mygithubkas** [comment]
this fixed it:

az acr update -n coinbase --admin-enabled true
