### ISSUE TITLE
Sync Web Apps Function Triggers  Encountered an error (ServiceUnavailable) from host runtime.

### ISSUE THREAD

**Issue by mygithubkas** [Azure/azure-functions-core-tools#2423]
This message appears in the Activity Log for the Function App when we deploy (through DevOps).

Anybody know what causes this ?

Cheers

**Comment by apawast** [comment]
@mygithubkas is this for the same app you are working on in #2422?

**Comment by mygithubkas** [comment]
> @mygithubkas is this for the same app you are working on in #2422?

Yes it is. Thank you

**Comment by apawast** [comment]
@mygithubkas apologies for the late response. Are you still experiencing this issue?
