### ISSUE TITLE
Use a Python virtual env (venv) of a parent folder?

### ISSUE THREAD

**Issue by andrejpk** [Azure/azure-functions-core-tools#2424]
I'd like to use a slightly different structure than the [standard Python folder structure for functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#folder-structure). 

``` text
 <project_root>/
| - .venv/
| - .vscode/
| - src/ 
| | - my_first_function/
| | | - __init__.py
| | | - function.json
| | | - example.py
| | - my_second_function/
| | | - __init__.py
| | | - function.json
| | - shared_code/
| | | - __init__.py
| | | - my_first_helper_function.py
| | | - my_second_helper_function.py
| | - .funcignore
| | - host.json
| | - local.settings.json
| | - requirements.txt
| - tests/
| | - test_my_second_function.py
| - Dockerfile
```

The difference here is that the functions code is in a /src folder, a folder deeper than the .venv. This works fine except in VSCode when I'm testing, `func host start` doesn't find the `.venv` because it's in the parent folder. It works in a command prompt when I start the virtual env manually then enter src/ and run `func host start`.

I want to keep tests separate so they don't ship with my production code and the structure mirrors the layout we'd like to use elsewhere in our Monorepo. 

Is there either a way when running `func host start` to specify a path for my virtual env or the root path of my function app?

**Comment by apawast** [comment]
@ejizba could please help with this?

**Comment by ejizba** [comment]
@andrejpk I think you can get it to work if you set `azureFunctions.pythonVenv` to `../.venv` in your `.vscode/settings.json` file. Here's a sample project that might be helpful: https://github.com/anthonychu/functions-python-durable-image-classifier

We also have a few issues tracking general python folder structure improvments:
https://github.com/microsoft/vscode-azurefunctions/issues/1970
https://github.com/microsoft/vscode-azurefunctions/issues/2041

**Comment by andrejpk** [comment]
I'll try it out, thanks!
