### ISSUE TITLE
Adding "AzureWebJobs" prefix to the queue connection app setting after azure function deploy

### ISSUE THREAD

**Issue by sivakumar715** [Azure/azure-functions-core-tools#2426]
The azure function is working in local but its failed in azure with the below error. Deployed azure function (v3) in kubernett stack and managed the connection string app settings in secrets-store via keyvault.

**Error:**
The 'TestQueueTrigger' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'TestQueueTrigger'. 
Microsoft.Azure.WebJobs.Extensions.Storage: Storage account connection string 'AzureWebJobsQueueConnectionString' does not exist. 
Make sure that it is a defined App Setting.

below is my sample azure function and its local.settings.json.

[FunctionName("TestQueueTrigger")]
		public async Task Run([QueueTrigger("%TestQueueName%", Connection = "QueueConnectionString")] string queueItem, ILogger log)
		{
			// logic
		}

{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "QueueConnectionString": "DefaultEndpointsProtocol=https;AccountName=test;AccountKey=xxxxxxxxxxxxx;EndpointSuffix=core.windows.net",
    "TestQueueName" : "test-queue"    
  }
}

please let us know if anyone come across this issue.

**Comment by apawast** [comment]
@sivakumar715 could you please share the yaml file? @ahmelsayed could you please help investigae?

**Comment by sivakumar715** [comment]
Thanks @apawast for looking. i have missed to add logic to include secrets-mounts in app configurations. the issue is fixed now since my azure function is able to read the app settings "QueueConnectionString".
