### ISSUE TITLE
Blob binding failed with SAS

### ISSUE THREAD

**Issue by lee212** [Azure/azure-functions-core-tools#243]
Hi,

This is not about a bug but I need some help connecting blob storage in Functions with SAS. 
I have a read only Shared access signature to a blob and I was trying to bind the blob storage by appsettings with signature token like:

 `publicBlob_STORAGE=BlobEndpoint=https://<blobname>.blob.core.windows.net;SharedAccessSignature=sr=s&amp;sig=<signature>&amp;sv=2017-04-17`

Unfortunately, my function failed with the error:
`2017-09-21T15:29:19.700 Exception while executing function: Functions.HttpTriggerPython31. Microsoft.Azure.WebJobs.Host: Failed to validate Microsoft Azure WebJobs SDK publicBlob_STORAGE connection string. The Microsoft Azure Storage account connection string is not formatted correctly. Please visit https://go.microsoft.com/fwlink/?linkid=841340 for details about configuring Microsoft Azure Storage connection strings.`

May I have some help in setting the connection string properly with SAS? Any comments or tips would be appreciated. I updated the settings according to this document: [configure connecting strings](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-for-an-azure-storage-account)

If you need further information or debugging messages, please let me know. Thank you.

**Comment by ahmedelnably** [comment]
Closing as stale, if this is still happening with the latest version of the core tools please open a new issue
