### ISSUE TITLE
System.Private.CoreLib: Exception while executing function: .... Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. System.Private.CoreLib: Cannot create an abstract class.

### ISSUE THREAD

**Issue by alexeymarkov** [Azure/azure-functions-core-tools#2444]
Hello,

I'm using Azure Functions v3 with Microsoft.NET.Sdk.Functions 3.0.3
In the code I'm using classes and interfaces like IActionResult from Microsoft.AspNetCore.Mvc
Today my VS updated to a new version which downloaded the newest version 3.0.3284 of Core Tools automatically.
Now my Function app does not work.
In HTTP triggers I get the exception:
System.Private.CoreLib: Exception while executing function: .... Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. System.Private.CoreLib: Cannot create an abstract class.

It says HttpRequest from Microsoft.AspNetCore.Http is an abstract class (which is a truth).
%LOCALAPPDATA%\AzureFunctionsTools\Releases\3.18.0 (3.0.3233) - works
%LOCALAPPDATA%\AzureFunctionsTools\Releases\3.20.0 (3.0.3284) - does not work

Please give an advice how to workaround this.

Regards,
Alexey

PS: some details
In the project I'm using a NuGet package which targets .NET Standard 2.0 and has a reference to Microsoft.AspNetCore.Mvc.Abstractions 2.2.0 (assume I can neither remove the package nor change it).

PSS: I found a workaround: in the function app project I added
```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```
although I do not reference AspNetCore directly. But currently this solves my problem.

**Comment by apawast** [comment]
@alexeymarkov could you please try updating your Microsoft.NET.Sdk.Functions to 3.0.11 and share your repro steps with us and the project file?

**Comment by mmeckes** [comment]
I had the same issue. @alexeymarkov your workaround of adding the framework reference worked for me, although also slightly baffled as to why that should affect this.


```
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```

**Comment by alexeymarkov** [comment]
> @alexeymarkov could you please try updating your Microsoft.NET.Sdk.Functions to 3.0.11 and share your repro steps with us and the project file?

I tried to decouple everything from my project but till now without success.

**Comment by AKomyshan** [comment]
Got the same issue. @alexeymarkov just question: are using Function Monkey too?

**Comment by alexeymarkov** [comment]
> Got the same issue. @alexeymarkov just question: are using Function Monkey too?

Yes. But this should not be a problem.
Probably the issue will go away if I update it and everything to the newest Functions SDK but I am not going to do this.
I will rather get rid of Function Monkey and migrate to .NET 5 with custom middlewares.

**Comment by apawast** [comment]
@alexeymarkov are you still experiencing this issue?
