### ISSUE TITLE
Azure functions console output overlaps

### ISSUE THREAD

**Issue by mlorbetske** [Azure/azure-functions-core-tools#245]
Azure functions console output overlaps

**Steps:**
1. Create a new HTTP Trigger Function
2. Run and Debug
3. Open the url in the browser
4. Hold down F5 to continually refresh the page

**Expected:**
Console output will not overlap

**Actual:**
Console output overlaps and does not appear to be thread safe Blocker day: 20-Azure Tools - HTTP Trigger Functions

This was originally reported on [Developer Community](https://developercommunity.visualstudio.com/content/problem/111710/azure-functions-console-output-overlaps.html)

**Comment by ahmedelnably** [comment]
Closing this as stale, if this is still happening with the new version please open a new issue
