### ISSUE TITLE
M1 Mac can't run Azure Functions Core Tool with VS Code: brew tap azure/functions FAILS

### ISSUE THREAD

**Issue by mrgithub** [Azure/azure-functions-core-tools#2468]
Using VS Code on M1 Mac to create Azure functions but it fails when it tries to install Azure Functions Core Tool:

The output is:

`5:16:09 PM: Running command: "brew tap azure/functions"...
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

5:16:19 PM: Finished running command: "brew tap azure/functions".
5:16:19 PM: Running command: "brew install azure-functions-core-tools@3"...
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
`

When I try to install Rosetta 2 I get a message saying it's not required for my mac.  Seems like the Azure Functions Core Tools need to be updated for M1 Macs.

**Comment by apawast** [comment]
@mrgithub unfortunately, we are currently waiting for the machine to be able to test this.

**Comment by Ayan-Kumar-Saha** [comment]
Is azure functions core tools now supported with the M1 chipset?

**Comment by mateuszdrab** [comment]
Still doesn't work for me

**Comment by gerardsimons** [comment]
Did you get a machine yet to fix this? 😋

**Comment by ejizba** [comment]
Consolidating M1 issues. Will use https://github.com/Azure/azure-functions-core-tools/issues/2834 for tracking in core tools
