### ISSUE TITLE
Error calling sync triggers (BadRequest)

### ISSUE THREAD

**Issue by RaleS** [Azure/azure-functions-core-tools#2484]
App name: coreenginedev0fndotnet5
Location: westeurope
App service plan

```
Getting site publishing info...
Creating archive for current directory...
Uploading 14,82 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = 'fc70e84c-091e-49c1-a269-776ebf495fea'.
```

Core Tools Version:       3.0.3331 Commit hash: 0b57b1647c5a385beb8f7d64fa0e534ad4c7555d
Function Runtime Version: 3.0.15371.0

**Comment by ankitkumarr** [comment]
@Rales, I noticed that you are using our .NET 5 support. What version of the preview packages are you on? Also, would you mind please sharing a repro function app code if possible?
