### ISSUE TITLE
Listen on all addresses

### ISSUE THREAD

**Issue by veccsolutions** [Azure/azure-functions-core-tools#2499]
I'm trying to integrate with a 3rd party systems web hooks and would like call the function directly from that system to debug my function. It looks like localhost is hardcoded into where it listens. Can this be made configurable or is it already and I'm missing it?

**Comment by fabiocav** [comment]
@ahmelsayed we bind to `0.0.0.0` [here](https://github.com/Azure/azure-functions-core-tools/blob/448a61d7a774280e932cfa678c8d4ec3d13bdc7a/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L479), wouldn't you expect this to bind to any/all IPv4 addresses on the local machine?

@veccsolutions how are you connecting and what failure are you seeing?

**Comment by veccsolutions** [comment]
This is what I see in the console when it start:
```
Functions:

        Trigger: [POST,GET] http://localhost:7071/api/Trigger
```
I try and connect using both my IP and host name and receive a connection refused. Most likely because it is only listening on the localhost.

Not sure if it matters, but according to these lines it is hard coded to listen on 127.0.0.1
Line:
https://github.com/Azure/azure-functions-core-tools/blob/6fd786fabcf15876e423b46b31b2164ed8a19e19/src/Azure.Functions.Cli/FunctionsLocalServer.cs#L50
and:
https://github.com/Azure/azure-functions-core-tools/blob/6fd786fabcf15876e423b46b31b2164ed8a19e19/src/Azure.Functions.Cli/FunctionsLocalServer.cs#L58

I got to that class by following the `program.cs`. It was the first class registered.
https://github.com/Azure/azure-functions-core-tools/blob/6fd786fabcf15876e423b46b31b2164ed8a19e19/src/Azure.Functions.Cli/Program.cs#L57

**Comment by veccsolutions** [comment]
I just tried it again. For about the 10th time and it's working. I was trying to get the output of netstat (which yesterday was only showing listening on 127.0.0.1 and not 0.0.00). Today it shows 0.0.0.0. The output still only shows localhost as I had posted though, but at least it can connect and receive requests as I would have expected.

**Comment by fabiocav** [comment]
The output will only state localhost, but I would expect the binding to happen to 0.0.0.0 

It's odd you encountered variation. I'll close this as resolved, but please feel free to open an issue and reference this if you run into this again. Thank you!
