### ISSUE TITLE
Azure core tools and Node 14

### ISSUE THREAD

**Issue by nojaf** [Azure/azure-functions-core-tools#2500]
Hi, I could find any tags with `-core-tools` and `node14` for https://hub.docker.com/_/microsoft-azure-functions-node.
Since I've read https://techcommunity.microsoft.com/t5/apps-on-azure/run-node-js-14-in-azure-functions/ba-p/2195063, I'm eager to try the `.mjs` syntax.
Will it be available in the near future?

**Comment by apawast** [comment]
@nojaf there is a full list of tags here: [https://mcr.microsoft.com/v2/azure-functions/node/tags/list](https://mcr.microsoft.com/v2/azure-functions/node/tags/list) and this should have node14. 

The core-tools image has not been published but we will be following up on this.

**Comment by apawast** [comment]
@TsuyoshiUshio @anthonychu is this planned or do we need to discuss further?

**Comment by nojaf** [comment]
It does seem to be listed here:
https://github.com/Azure/azure-functions-docker/blob/625f109c74cd76687aa291c3dbeef68cf4faf2ea/host/3.0/core-tools-publish.yml#L169-L234
