### ISSUE TITLE
customizing configuration source support?

### ISSUE THREAD

**Issue by jzhouw** [Azure/azure-functions-core-tools#2504]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources

```
[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]

namespace MyNamespace
{
    public class Startup : FunctionsStartup
    {
        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            FunctionsHostBuilderContext context = builder.GetContext();

            builder.ConfigurationBuilder
                .AddJsonFile(Path.Combine(context.ApplicationRootPath, "appsettings.json"), optional: true, reloadOnChange: false)
                .AddJsonFile(Path.Combine(context.ApplicationRootPath, $"appsettings.{context.EnvironmentName}.json"), optional: true, reloadOnChange: false)
                .AddEnvironmentVariables();
        }
    }
}
```

but using appsettings.Development.json with Core Tools still got a message saying local.settings.json not found.

(I found a history issue of renaming appsettings.json to local.settings.json https://github.com/Microsoft/vscode-azurefunctions/issues/327
but I like the naming appsettings.json because it's consistent with normal .net core app and lots of dev is familiar with this convention.)

**Comment by apawast** [comment]
@jzhouw could you please share the actual error output with us? Either way, this error should not prevent you from using your own configuration sources.

**Comment by jzhouw** [comment]
without local.settings.json in the output folder, the tools gave:

```
Azure Functions Core Tools
Core Tools Version:       3.0.3388 Commit hash: fb42a4e0b7fdc85fbd0bcfc8d743ff7d509122ae
Function Runtime Version: 3.0.15371.0

Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than httptrigger, kafkatrigger. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json.
Press any to continue....
```
I had to put a fake local.settings.json files in the folder with all `Values `configuration section to be correct, yes other configuration section in appsettings.Development.json can work. can we just juse appsettings.Development.json without local.settings.json?

**Comment by apawast** [comment]
@jzhouw local.settings.json is required for local development and they more closely replicate the environment configuration of app settings as opposed to configuration coming from local settings files. Closing this as this should answer this issue.
