### ISSUE TITLE
No function found in FSharp project running in isolated mode on Dotnet 5 

### ISSUE THREAD

**Issue by landy** [Azure/azure-functions-core-tools#2507]
Hello, I have encountered a problem when migrating Azure Functions to a new isolated mode on Dotnet 5. The issue is that no functions are found in the project written in F#. 

here is a repo with a sample project https://github.com/landy/functions-isolated

I'm using version **3.0.3388 of azure functions core tools** and **Dotnet version 5.0.201**

The project is based on the C# template. After running `func host start --verbose` I get 
```
No job functions found. Try making your job classes and methods public.

Initializing function HTTP routes
No HTTP routes mapped
```

**Comment by johlrich** [comment]
This appears to be related to F# template problems pointed out last year:

https://github.com/Azure/azure-functions-core-tools/issues/1963
https://github.com/Azure/azure-functions-templates/pull/954

Same workaround applies here from the pr and comments of changing Update -> Include in the fsproj for the json ItemGroup entries. Example:

https://github.com/Azure/azure-functions-templates/pull/954/commits/047ed376c117d1be77ff3142140d6e6d402662f8

**Comment by Dzoukr** [comment]
@johlrich Man, you just rock!!! THANK YOU!

**Comment by landy** [comment]
wow, Thanks!!! It works
