### ISSUE TITLE
Impossible to install the npm package behind a corporate proxy

### ISSUE THREAD

**Issue by ssougnez** [Azure/azure-functions-core-tools#251]
Hello,

I tried to install the package via the command

`npm i -g azure-functions-core-tools`

But the issue is that I'm behind a corporate proxy and the postinstall step of the package (the one downloading "https://functionscdn.azureedge.net/public/1.0.4/Azure.Functions.Cli.zip") is doing a get request that can't be proxied, so I'm unable to download the package. As a result, the whole installation fails and I'm not able to use the package.

**Comment by okelet** [comment]
Alternatively, while this issue is not fixed, you can use a wrapper like proxychains.

**Comment by ssougnez** [comment]
What's the status on this ?
