### ISSUE TITLE
Lost executable permission through deployment from Windows OS to Linux Function App

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-functions-core-tools#2510]
I'm trying to deploy functions with custom-handler using func@3.0.3388.

But the custom handler fails to launch with the following error.
![image](https://user-images.githubusercontent.com/4566555/111892470-1f70f000-8a3f-11eb-9b00-a5e7fa80cbd5.png)

I found that executable permission of binary file is lost only on deployment from Windows OS to Linux Function App on App Service Plan or Elastic Premium Plan as the following screenshots of SSH.

From WSL2 to Linux Function App:
![image](https://user-images.githubusercontent.com/4566555/111892232-dc158200-8a3c-11eb-87ba-bbd4cd95e491.png)
  -> the permission is kept and the app works fine.

From Windows OS to Linux Function App:
![image](https://user-images.githubusercontent.com/4566555/111892227-d455dd80-8a3c-11eb-9d8f-83d7c3683f2b.png)
  -> the permission is lost and the app fails to launch.

Could you please take a look at this behavior if this is not a known limitation?

Regards,

**Comment by anthonychu** [comment]
The host should try to change the executable bit  before running the binary. @pragnagopa @yojagad Do you know why this doesn’t appear to work on Linux dedicated?

**Comment by horihiro** [comment]
As a temporary workaround, using `func` with `--build remote` and App Setting `SCM_DO_BUILD_DURING_DEPLOYMENT=0`  seems to keep the executable bit.
But I'm not sure if this approach is appropriate.

**Comment by horihiro** [comment]
It was confirmed that this issue was reproduced when a zip package containing linux binary files was deployed from Windows OS to linux app service in which `WEBSITE_RUN_FROM_PACKAGE` is enabled.
So this might be an issue on App Service on Linux with Run-From-Package feature.

Could you please escalate to the appropriate repository/project?

**Comment by horihiro** [comment]
I will send an internal thread involving App Service team.

**Comment by pragnagopa** [comment]
> The host should try to change the executable bit before running the binary. @pragnagopa @yojagad Do you know why this doesn’t appear to work on Linux dedicated?

The issue was specifically addressed for Linux Consumption in the host - https://github.com/Azure/azure-functions-host/pull/5834

Tagging @ankitkumarr @ahmelsayed - to confirm if work around mentioned in the [comment](https://github.com/Azure/azure-functions-core-tools/issues/2510#issuecomment-803674642) above - is required to preserve execute permissions

**Comment by horihiro** [comment]
Thanks @pragnagopa 

Can we execute the binary file by https://github.com/Azure/azure-functions-host/pull/5834 even if the binary's permission cannot be changed?
It seems hard to change the permission because the files are mounted to `/home/site/wwwroot` as read-only by Run from package feature.

I'm contacting Linux App Service team regarding the read-only mount and involving you to the thread.

**Comment by ahmelsayed** [comment]
Regarding the change in Azure/azure-functions-host#5834, I was expecting that there will be a set or save call after updating the permissions on the file. Though after looking at the `UnixFileInfo` api, there doesn't seem to be one. I wonder if it's actually saving any of the updated values there. We might have to actually run a `new ProcessStartInfo { FileName = "chmod", Arguments = "+x /path/to/file" }`. 
_Note that this will only work for the executable the host is trying to launch through that code path. not any other executables you might have as part of the package that you might try to launch again within deno or your function_

`--build remote` will perform the build in a Linux container, so it'll preserve the executable permission. When deploying from a Windows file system there is no x bit on any file, so we can't tell. When deploying from WSL, the value is available from the file system, and core-tools should do the right thing.

**Comment by horihiro** [comment]
Thanks @ahmelsayed 

> Note that this will only work for the executable the host is trying to launch through that code path. not any other executables you might have as part of the package that you might try to launch again within deno or your function

`deno` in my package is executable for Custom Handler, which is specified in `host.json` as [this](https://github.com/anthonychu/azure-functions-deno-template/blob/main/host.json#L9).
Does Function Host try to add executable premission to `/home/site/wwwroot/bin/linux/deno` in this case?

And will this succeed for files on read-only volume?
If no, I think that this issue should be discussed on Linux App Service side regarding Run From Package feature on deployment from Windows OS, not on Azure Functions side.

**Comment by horihiro** [comment]
It is expected that https://github.com/Azure/azure-functions-core-tools/pull/2521 will fix this issue.

**Comment by horihiro** [comment]
I confirmed that executables deployed by pre-release version [3.0.3442](https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.3442), which contains PR #2521, worked nicely.

![image](https://user-images.githubusercontent.com/4566555/114111163-3efb8a00-9914-11eb-9c77-e422f0f1b692.png)
