### ISSUE TITLE
Cannot update vs code to latest version of tools. Various Modules not found.

### ISSUE THREAD

**Issue by CarsonPLS** [Azure/azure-functions-core-tools#2514]
running npm install -g azure-functions-core@3 fails due to not being able to locate modules.

if I install these modules globally by hand, that seems to fix things for that module, but then the "next" module just throws the same message.

It appears that it is looking for dependencies that are not being installed.

**Comment by apawast** [comment]
@CarsonPLS  can you please provide steps to reproduce this and the complete error output?

**Comment by CarsonPLS** [comment]
Sure

When prompted to update Azure Functions by VS Code, I select the update option.

[cid:d6a4d5ca-cfa3-4984-8acf-ae0bbb49cd68]

This is the output at the current moment:

[cid:1cc74331-aa02-4238-9f15-6a99496106a4]

This time is it saying 'rimraf' is the missing module, but there were about 4 other modules previously that I installed globally, to try to resolve this myself.

Once I got to this one, I concluded that the issue extended beyond specific dependencies, and created this issue.

________________________________

**Comment by CarsonPLS** [comment]
Sure

When prompted to update Azure Functions by VS Code, I select the update option.

![image](https://user-images.githubusercontent.com/27771299/113034502-26df7a00-9160-11eb-8eac-4fa4fd5c1b54.png)

This is the output at the current moment:

![image](https://user-images.githubusercontent.com/27771299/113034526-3068e200-9160-11eb-81de-b323df4e0c0b.png)

This time is it saying 'rimraf' is the missing module, but there were about 4 other modules previously that I installed globally, to try to resolve this myself.

Once I got to this one, I concluded that the issue extended beyond specific dependencies, and created this issue.

**Comment by apawast** [comment]
@CarsonPLS can you please run `npm i -g azure-functions-core-tools@3 --unsafe-perm true --verbose` in terminal and share the output?

**Comment by CarsonPLS** [comment]
@apawast , have I followed your instructions correctly?

**Comment by stemixreal** [comment]
Hi @apawast , I have a very similar issue. I've tried to update several times, first to 3.0.3388 from 3.0.2996 which completed without error but func --version still reported 3.0.2996.

After that I began to get the pop-up "Update your Azure functions Core Tools to ... (3.0.3442).."

Which I've tried but again, this completes as if successful however the update isn't installed and the next time I start vscode I am again prompted to update.

Here is the verbose output from inside vscode:

> npm verb cli [
> npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
> npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> npm verb cli   'i',
> npm verb cli   '-g',
> npm verb cli   'azure-functions-core-tools@3',
> npm verb cli   '--unsafe-perm',
> npm verb cli   'true',
> npm verb cli   '--verbose'
> npm verb cli ]
> npm info using npm@6.14.8
> npm info using node@v14.15.0
> npm verb npm-session 45e309dc7b8e0531
> npm http fetch GET 304 https://registry.npmjs.org/azure-functions-core-tools 304ms (from cache)
> npm timing stage:loadCurrentTree Completed in 784ms
> npm timing stage:loadIdealTree:cloneCurrentTree Completed in 3ms
> npm timing stage:loadIdealTree:loadShrinkwrap Completed in 79ms
> npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 152ms
> npm timing stage:loadIdealTree Completed in 295ms
> npm timing stage:generateActionsToTake Completed in 34ms
> npm verb correctMkdir C:\Users\dev\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
> npm verb makeCacheDir UID & GID are irrelevant on win32
> npm verb lock using C:\Users\dev\AppData\Roaming\npm-cache\_locks\staging-432dfbdaa402db9a.lock for C:\Users\dev\AppData\Roaming\npm\node_modules\.staging
> npm timing action:extract Completed in 138ms
> npm info lifecycle azure-functions-core-tools@3.0.3442~preuninstall: azure-functions-core-tools@3.0.3442
> npm info lifecycle azure-functions-core-tools@3.0.3442~uninstall: azure-functions-core-tools@3.0.3442
> npm verb unbuild rmStuff azure-functions-core-tools@3.0.3442 from C:\Users\dev\AppData\Roaming\npm\node_modules
> npm info lifecycle azure-functions-core-tools@3.0.3442~postuninstall: azure-functions-core-tools@3.0.3442
> npm timing action:unbuild Completed in 93ms
> npm timing action:remove Completed in 2005ms
> npm timing action:finalize Completed in 190ms
> npm timing action:refresh-package-json Completed in 360ms
> npm info lifecycle azure-functions-core-tools@3.0.3442~preinstall: azure-functions-core-tools@3.0.3442
> npm timing action:preinstall Completed in 4ms
> npm info linkStuff azure-functions-core-tools@3.0.3442
> npm verb linkBins [
> npm verb linkBins   {
> npm verb linkBins     func: 'lib/main.js',
> npm verb linkBins     azfun: 'lib/main.js',
> npm verb linkBins     azurefunctions: 'lib/main.js'
> npm verb linkBins   },
> npm verb linkBins   'C:\\Users\\dev\\AppData\\Roaming\\npm',
> npm verb linkBins   true
> npm verb linkBins ]
> C:\Users\dev\AppData\Roaming\npm\func -> C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
> C:\Users\dev\AppData\Roaming\npm\azfun -> C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
> C:\Users\dev\AppData\Roaming\npm\azurefunctions -> C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
> npm timing action:build Completed in 155ms
> npm info lifecycle azure-functions-core-tools@3.0.3442~install: azure-functions-core-tools@3.0.3442
> npm timing action:install Completed in 5ms
> npm info lifecycle azure-functions-core-tools@3.0.3442~postinstall: azure-functions-core-tools@3.0.3442
> 
> > azure-functions-core-tools@3.0.3442 postinstall C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> > node lib/install.js
> 
> attempting to GET "https://functionscdn.azureedge.net/public/3.0.3442/Azure.Functions.Cli.win-x64.3.0.3442.zip"
> [==================] Downloading Azure Functions Core Tools
> 
> Telemetry
> ---------
> The Azure Functions Core tools collect usage data in order to help us improve your experience.
> The data is anonymous and doesn't include any user specific or personal information. The data is collected by Microsoft.
> 
> You can opt-out of telemetry by setting the FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
> 
> npm verb lifecycle azure-functions-core-tools@3.0.3442~postinstall: unsafe-perm in lifecycle true
> npm verb lifecycle azure-functions-core-tools@3.0.3442~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\node_modules\.bin;C:\Users\dev\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\WINDOWS\System32\OpenSSH\;c:\gk;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Azure Functions Core Tools\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program 
> Files\PuTTY\;C:\Users\dev\AppData\Local\Microsoft\WindowsApps;C:\Users\dev\.dotnet\tools;c:\gk;C:\WINDOWS\system32;C:\Users\dev\AppData\Local\Programs\Fiddler;C:\Users\dev\AppData\Local\Microsoft\WindowsApps;C:\Users\dev\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\dev\AppData\Local\GitHubDesktop\bin;C:\Users\dev\.dotnet\tools;C:\Users\dev\AppData\Roaming\npm
> npm verb lifecycle azure-functions-core-tools@3.0.3442~postinstall: CWD: C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> npm timing action:postinstall Completed in 74393ms
> npm verb unlock done using C:\Users\dev\AppData\Roaming\npm-cache\_locks\staging-432dfbdaa402db9a.lock for C:\Users\dev\AppData\Roaming\npm\node_modules\.staging
> npm timing stage:executeActions Completed in 77417ms
> npm timing stage:rollbackFailedOptional Completed in 1ms
> npm timing stage:runTopLevelLifecycles Completed in 78553ms
> + azure-functions-core-tools@3.0.3442
> updated 1 package in 78.558s
> npm verb exit [ 0, true ]
> npm timing npm Completed in 79928ms
> npm info ok

**Comment by CarsonPLS** [comment]
This was resolved by running `npm uninstall -g azure-functions-core-tools` then `npm i -g azure-functions-core-tools@3`

hit the same issue if I tried running install again, so I suspect that future updates may need to be uninstalled first before the latest version is installed.

**Comment by Jack-Barry** [comment]
The fix by @CarsonPLS worked for me, however it's not a very ergonomic solution and doesn't solve the root cause of this issue
