### ISSUE TITLE
Azure Function triggered by Queue Storage not working with docker and node

### ISSUE THREAD

**Issue by JuanCarlosResser** [Azure/azure-functions-core-tools#2516]
I am trying to create a docker container of an azure function in node js with typescript triggered by an azure queue 
But I get the following error:
![image](https://user-images.githubusercontent.com/81269568/112232620-1fffb700-8bf6-11eb-9ff2-4d1815d035df.png)

My function.json looks like this:
![image](https://user-images.githubusercontent.com/81269568/112233045-ec715c80-8bf6-11eb-8d1f-404647440ac4.png)

Function runs correctly without docker. The problem is quite obvious, the function can't find the connection string for connecting to Azure Queue Storage however the connection string is provided in Docker environment variables. The name `AzureWebJobsAzureWebJobsStorage` requested by the function is also very weird.

**Comment by apawast** [comment]
@JuanCarlosResser can you try removing that connection property from function.json?
