### ISSUE TITLE
Remove Dependency on JAVA_HOME

### ISSUE THREAD

**Issue by opticyclic** [Azure/azure-functions-core-tools#2518]
This article says that we need an environment variable JAVA_HOME
https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-java?tabs=bash%2Cazure-cli%2Cbrowser#create-a-local-function-project

As long as java is on the PATH you should be fine.

This was also previously mentioned and allegedly fixed a couple of years ago: https://github.com/Azure/azure-functions-core-tools/issues/502

**Comment by opticyclic** [comment]
See this question on stackoverflow:
https://stackoverflow.com/questions/64032219/azure-function-in-java-does-not-work-locally

and this answer:
https://stackoverflow.com/a/64704084/1000011

**Comment by apawast** [comment]
Hi @opticyclic, the documentation is correct. To use Java 11, you must have the variable JAVA_HOME.
