### ISSUE TITLE
Error calling sync triggers (BadRequest). Node runtime on Linux

### ISSUE THREAD

**Issue by Stolz** [Azure/azure-functions-core-tools#2525]
Hello.

I'm trying to get a simple Node function working on Linux Consumption Plan at East Asia region. The app is created from the official template and it works locally. When I try to publish it the deployment step completes successfully. However the 'Syncing triggers' steps fails with BadRequest error and the app cannot be triggered via HTTP.

### Versions used

	func --version
	3.0.3388

	az --version
	azure-cli                         2.21.0
	core                              2.21.0
	telemetry                          1.0.6
	Python (Linux) 3.8.8 (default, Mar 22 2021, 00:58:40) [GCC 10.2.0]

### Steps to reproduce it

Create the app from template and test it locally

	func init demo-js --javascript
	cd demo-js
	func new --name HelloWorld --template "HTTP trigger" --authlevel "anonymous" --language JavaScript
	func start &
	curl 'http://localhost:7071/api/HelloWorld?name=localUser'
	Hello, localUser. This HTTP triggered function executed successfully.

Add storage account info in `local.settings.json`

	cat local.settings.json
	{
	  "IsEncrypted": false,
	  "Values": {
	    "FUNCTIONS_WORKER_RUNTIME": "node",
	    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName=redacted;AccountKey=redacted"
	  }
	}

Try to publish the app. It fails

	CLI_DEBUG=1 func azure functionapp publish func-demo-js
	(redacted for brevity)
	Deployment completed successfully.
	Syncing triggers...(repeats 6 times)
	Request:
	Method: POST, RequestUri: 'https://management.azure.com/subscriptions/redacted-my-subs-id/resourceGroups/rg-default/providers/Microsoft.Web/sites/func-demo-js/host/default/sync?api-version=2015-08-01', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
	{
	  Authorization: Bearer (redacted)
	  User-Agent: functions-core-tools/3.0.3388
	  Accept: application/json
	  x-ms-request-id: f8ea483f-df1b-4039-b3db-732f87e79520
	  Content-Type: application/json; charset=utf-8
	}
	null

	Response:
	StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
	{
	  Cache-Control: no-cache
	  Pragma: no-cache
	  Strict-Transport-Security: max-age=31536000; includeSubDomains
	  Server: Microsoft-IIS/10.0
	  X-AspNet-Version: 4.0.30319
	  X-Powered-By: ASP.NET
	  x-ms-ratelimit-remaining-subscription-writes: 1196
	  x-ms-request-id: a64834a0-9faf-4058-86c6-98f91e55fb92
	  x-ms-correlation-request-id: a64834a0-9faf-4058-86c6-98f91e55fb92
	  x-ms-routing-request-id: SOUTHEASTASIA:20210329T060310Z:a64834a0-9faf-4058-86c6-98f91e55fb92
	  X-Content-Type-Options: nosniff
	  Date: Mon, 29 Mar 2021 06:03:10 GMT
	  Content-Length: 346
	  Content-Type: application/json; charset=utf-8
	  Expires: -1
	}
	{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}

	Azure.Functions.Cli.Common.CliException: Error calling sync triggers (BadRequest). Request ID = 'a64834a0-9faf-4058-86c6-98f91e55fb92'.
	   at Azure.Functions.Cli.Helpers.RetryHelper.Retry(Func`1 func, Int32 retryCount, TimeSpan retryDelay, Boolean displayError) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\RetryHelper.cs:line 29
	   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.SyncTriggers(Site functionApp) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 442
	   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 432
	   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 171
	   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66

### Info about the provisioned resources
App Service plan info

	az appservice plan list
	- freeOfferExpirationTime: null
	  hostingEnvironmentProfile: null
	  hyperV: false
	  id: /subscriptions/redacted-my-subs-id/resourceGroups/rg-default/providers/Microsoft.Web/serverfarms/plan-functions
	  isSpot: false
	  isXenon: false
	  kind: functionapp
	  location: East Asia
	  maximumElasticWorkerCount: 1
	  maximumNumberOfWorkers: 0
	  name: plan-functions
	  numberOfSites: 1
	  perSiteScaling: false
	  provisioningState: null
	  reserved: true
	  resourceGroup: rg-default
	  sku:
	    capabilities: null
	    capacity: 0
	    family: Y
	    locations: null
	    name: Y1
	    size: Y1
	    skuCapacity: null
	    tier: Dynamic
	  spotExpirationTime: null
	  status: Ready
	  tags: {}
	  targetWorkerCount: 0
	  targetWorkerSizeId: 0
	  type: Microsoft.Web/serverfarms
	  workerTierName: null

Function App info

	az functionapp list
	- appServicePlanId: /subscriptions/redacted-my-subs-id/resourceGroups/rg-default/providers/Microsoft.Web/serverfarms/plan-functions
	  availabilityState: Normal
	  clientAffinityEnabled: false
	  clientCertEnabled: false
	  clientCertExclusionPaths: null
	  cloningInfo: null
	  containerSize: 1536
	  dailyMemoryTimeQuota: 0
	  defaultHostName: func-demo-js.azurewebsites.net
	  enabled: true
	  enabledHostNames:
	  - func-demo-js.azurewebsites.net
	  - func-demo-js.scm.azurewebsites.net
	  hostNameSslStates:
	  - hostType: Standard
	    ipBasedSslResult: null
	    ipBasedSslState: NotConfigured
	    name: func-demo-js.azurewebsites.net
	    sslState: Disabled
	    thumbprint: null
	    toUpdate: null
	    toUpdateIpBasedSsl: null
	    virtualIp: null
	  - hostType: Repository
	    ipBasedSslResult: null
	    ipBasedSslState: NotConfigured
	    name: func-demo-js.scm.azurewebsites.net
	    sslState: Disabled
	    thumbprint: null
	    toUpdate: null
	    toUpdateIpBasedSsl: null
	    virtualIp: null
	  hostNames:
	  - func-demo-js.azurewebsites.net
	  hostNamesDisabled: false
	  hostingEnvironmentProfile: null
	  httpsOnly: false
	  hyperV: false
	  id: /subscriptions/redacted-my-subs-id/resourceGroups/rg-default/providers/Microsoft.Web/sites/func-demo-js
	  identity: null
	  inProgressOperationId: null
	  isDefaultContainer: null
	  isXenon: false
	  kind: functionapp,linux
	  lastModifiedTimeUtc: '2021-03-29T06:02:45.906666'
	  location: East Asia
	  maxNumberOfWorkers: null
	  name: func-demo-js
	  outboundIpAddresses: (redacted)
	  possibleOutboundIpAddresses: (redacted)
	  redundancyMode: None
	  repositorySiteName: func-demo-js
	  reserved: true
	  resourceGroup: rg-default
	  scmSiteAlsoStopped: false
	  siteConfig:
	    acrUseManagedIdentityCreds: false
	    acrUserManagedIdentityId: null
	    alwaysOn: null
	    apiDefinition: null
	    apiManagementConfig: null
	    appCommandLine: null
	    appSettings: null
	    autoHealEnabled: null
	    autoHealRules: null
	    autoSwapSlotName: null
	    azureMonitorLogCategories: null
	    azureStorageAccounts: null
	    connectionStrings: null
	    cors: null
	    customAppPoolIdentityAdminState: null
	    customAppPoolIdentityTenantState: null
	    defaultDocuments: null
	    detailedErrorLoggingEnabled: null
	    documentRoot: null
	    experiments: null
	    fileChangeAuditEnabled: null
	    ftpsState: null
	    functionAppScaleLimit: null
	    functionsRuntimeScaleMonitoringEnabled: null
	    handlerMappings: null
	    healthCheckPath: null
	    http20Enabled: null
	    httpLoggingEnabled: null
	    ipSecurityRestrictions: null
	    javaContainer: null
	    javaContainerVersion: null
	    javaVersion: null
	    keyVaultReferenceIdentity: null
	    limits: null
	    linuxFxVersion: null
	    loadBalancing: null
	    localMySqlEnabled: null
	    logsDirectorySizeLimit: null
	    machineKey: null
	    managedPipelineMode: null
	    managedServiceIdentityId: null
	    metadata: null
	    minTlsVersion: null
	    minimumElasticInstanceCount: 0
	    netFrameworkVersion: null
	    nodeVersion: null
	    numberOfWorkers: null
	    phpVersion: null
	    powerShellVersion: null
	    preWarmedInstanceCount: null
	    publishingPassword: null
	    publishingUsername: null
	    push: null
	    pythonVersion: null
	    remoteDebuggingEnabled: null
	    remoteDebuggingVersion: null
	    requestTracingEnabled: null
	    requestTracingExpirationTime: null
	    routingRules: null
	    runtimeADUser: null
	    runtimeADUserPassword: null
	    scmIpSecurityRestrictions: null
	    scmIpSecurityRestrictionsUseMain: null
	    scmMinTlsVersion: null
	    scmType: null
	    tracingOptions: null
	    use32BitWorkerProcess: null
	    virtualApplications: null
	    vnetName: null
	    vnetPrivatePortsCount: null
	    vnetRouteAllEnabled: null
	    webSocketsEnabled: null
	    websiteTimeZone: null
	    winAuthAdminState: null
	    winAuthTenantState: null
	    windowsFxVersion: null
	    xManagedServiceIdentityId: null
	  slotSwapStatus: null
	  state: Running
	  suspendedTill: null
	  tags: {}
	  targetSwapSlot: null
	  trafficManagerHostNames: null
	  type: Microsoft.Web/sites
	  usageState: Normal

Function App Settings (I didn't set any of this. They all have been automatically created by the tools)

	az functionapp config appsettings list -n func-demo-js -g rg-default
	- name: AzureWebJobsDashboard
	  slotSetting: false
	  value: DefaultEndpointsProtocol=https;AccountName=redacted;AccountKey=redacted
	- name: AzureWebJobsStorage
	  slotSetting: false
	  value: DefaultEndpointsProtocol=https;AccountName=redacted;AccountKey=redacted
	- name: FUNCTIONS_EXTENSION_VERSION
	  slotSetting: false
	  value: ~1
	- name: WEBSITE_RUN_FROM_PACKAGE
	  slotSetting: false
	  value: https://redacted.blob.core.windows.net/function-releases/20210329065705-e1346884-3830-44ce-a9f8-1bb81176ba73.zip?sv=2018-03-28&sr=b&sig=ZHmZ3zOEqBDIh%2BR4AvEWlFXMZdSltB5YesOdvcxqWtQ%3D&st=2021-03-29T06%3A52%3A05Z&se=2031-03-29T06%3A57%3A05Z&sp=r
	- name: WEBSITE_MOUNT_ENABLED
	  slotSetting: false
	  value: '1'

I have tried setting the plan kind to Linux with identical results. The resources have been created with Terraform, using the default [example for creating a Function App in a Linux Consumption Plan](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#example-usage-linux)

**Comment by balag0** [comment]
Looks like the template defaults to ~1 for FUNCTIONS_EXTENSION_VERSION.
For new apps we recommend ~3 and for Linux consumption sku in particular anything below ~2 is not supported.
Could you try the same template but change the FUNCTIONS_EXTENSION_VERSION to use ~3

**Comment by Stolz** [comment]
Thanks @balag0 , setting version to 3 worked :)

For Linux viewers from the future, just run

    az functionapp config appsettings set -n my-app -g my-group --settings 'FUNCTIONS_EXTENSION_VERSION=~3'
