### ISSUE TITLE
CLI 2.0 Preview doesn't seem to work with EFCore 2.0

### ISSUE THREAD

**Issue by pauldalyii** [Azure/azure-functions-core-tools#253]
I'm trying to build a function app that leverages EF Core 2.0.  Since [EF Core 2.0 target's .NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/), I'm testing this out using the [CLI 2.0 Preview](https://github.com/Azure/azure-functions-cli/pull/218).

First, I installed this:
`npm i -g azure-functions-core-tools@2.0.1-beta.15`

Then when I try to run my function app (via `func host start --port 7071 --pause-on-error` in the `bin\Debug\net47` directory) I see this:
`Starting Host (HostId=<removed>, Version=2.0.11280.0, ProcessId=656, Debug=False, Attempt=0)`

I assume that the 2.0.11280.0 confirms that I'm running CLI 2.0

The function is recognized by the host and the host awaits a GET to `https://localhost:7071/api/Applications`

When I navigate my browser to `https://localhost:7071/api/Applications`, I get the following error:
````
[9/25/2017 6:01:32 PM] A ScriptHost error has occurred
[9/25/2017 6:01:32 PM] Exception while executing function: Applications. Service: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[9/25/2017 6:01:32 PM] Exception while executing function: Applications
[9/25/2017 6:01:32 PM] Exception while executing function: Applications. Service: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[9/25/2017 6:01:32 PM] Function completed (Failure, Id=2c2432cc-462b-4826-a86a-0df85bda2542, Duration=231ms)
[9/25/2017 6:01:32 PM]
[9/25/2017 6:01:32 PM] Executed 'Applications' (Failed, Id=2c2432cc-462b-4826-a86a-0df85bda2542)
[9/25/2017 6:01:32 PM] System.Private.CoreLib: Exception while executing function: Applications. Service: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[9/25/2017 6:01:32 PM]   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '2c2432cc-462b-4826-a86a-0df85bda2542'
[9/25/2017 6:01:32 PM] System.Private.CoreLib: Exception while executing function: Applications. Service: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
````

I've attached a [small sample solution](https://github.com/Azure/azure-functions-cli/files/1331104/PublishApps.zip) that repros this issue.  The solution consists of three projects: the function app, and two class libraries that contain "data access" logic.  In each project I updated:
- the target framework to 4.7
![image](https://user-images.githubusercontent.com/1781802/30820123-d53b8680-a1d5-11e7-9645-cc7e97b8d6b1.png)

- the language version to C# 7.1
![image](https://user-images.githubusercontent.com/1781802/30820108-cbb3ecb0-a1d5-11e7-9090-1b2d8c2c14cc.png)

Am I doing something wrong here?  Is this another example of the issue described here:
dotnet/standard#481?

**Comment by fabiocav** [comment]
Was `System.Net.Http.Formatting` deployed with your function (in `bin`) ?

With the new runtime, one easy thing to do here is eliminate that dependency altogether and use a model that relies on new abstractions like:

``` csharp
#r "Newtonsoft.Json"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static IActionResult Run(HttpRequest req, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request.");

    string name = req.Query["name"];

    string requestBody = new StreamReader(req.Body).ReadToEnd();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    return name != null
        ? (ActionResult)new OkObjectResult($"Hello, {name}")
        : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
}
```

**Comment by pauldalyii** [comment]
`System.Net.Http.Formatting` was deployed in the the `bin\Debug\net47\bin` folder.

When you suggest eliminating that dependency altogether, are you suggesting that I remove `Microsoft.NET.Sdk.Functions`, because that is what is transitively referring to `System.Net.Http.Formatting`?

![image](https://user-images.githubusercontent.com/1781802/30864018-56336346-a287-11e7-8086-6251cd330e5c.png)

I attempted to remove `Microsoft.NET.Sdk.Functions`, but found that I'd need to remove the `FunctionName` and `HttpTrigger` attributes:

![image](https://user-images.githubusercontent.com/1781802/30864726-58019ff6-a289-11e7-8271-d579852d9807.png)

I'm assuming this means I need to go back down the path of manually creating a function.json for each function within my function app?  I liked being able to use the attributes for project structure reasons.  Let's say I want to implement a get and a post for a route Applications.  My folder structure currently looks like this:

```
Applications\Get.cs
Applications\Post.cs
```

AFAIK, I can't do that if I need to have a `functions.json` file relative to each of those.  Now I'd need to do something like this:

```
Applications\Get\Get.cs
Applications\Get\function.json
Applications\Post\Post.cs
Applications\Post\function.json
```

Actually, I just came across an [article posted yesterday](https://blogs.msdn.microsoft.com/appserviceteam/2017/09/25/develop-azure-functions-on-any-platform/) that talks about this.  It sounds like you are already aware of the issue.

**Comment by pauldalyii** [comment]
I can confirm that EF Core 2.0 works after removing reference to `Microsoft.NET.Sdk.Functions` and manually generating the `function.json` files for each function.

**Comment by fabiocav** [comment]
@pauldalyii did you continue to see a problem if you kept the reference but updated the code to remove the dependency on the extension methods I mentioned? (e.g. by changing to HttpRequest/IActionResult)?

**Comment by pauldalyii** [comment]
Ahh, yes.  If I reference `Microsoft.NET.Sdk.Functions`, but change the signature of the function to leverage `HttpRequest` and `IActionResult`, then it generates the 'function.json' file.  I also do not get the runtime exception regarding `System.Net.Http.Formatting`.

Thanks again @fabiocav

**Comment by pauldalyii** [comment]
@fabiocav, although this has been working works fine using my local emulator since Sept 26th, it doesn't yet work when my function is deployed to Azure even with the beta switch flipped in the port.

Here's what I see that when I deploy my Function app to Azure:
![image](https://user-images.githubusercontent.com/1781802/32391917-f80ef73a-c090-11e7-847a-971d031fec08.png)
I assume that's the version of the CLI running in Azure.

However, when I run locally after installing azure-functions-core-tools@2.0.1-beta.20, I see this:
![image](https://user-images.githubusercontent.com/1781802/32393608-69fc3eba-c097-11e7-86cc-902aa00a4476.png)
I assume that these two versions both represent the CLI runtime version.

I have tried to explicitly define the 2.0.11353.0 version like this, but that still doesn't seem to work:
![image](https://user-images.githubusercontent.com/1781802/32394359-0c795ee6-c09a-11e7-9c03-e6a850dea11a.png)

I guess my question is:  When will newer versions of the CLI be deployed to Azure even if only to those customers willing to toggle the Beta runtime version switch?

**Comment by fabiocav** [comment]
We are due for a 2.0 deployment as there have been several bug fixes and enhancements. This will likely happen at the end of the current sprint (in about a week and a half), but we'll try to do it sooner.

**Comment by pauldalyii** [comment]
Thanks @fabiocav!  Looking forward to it!

**Comment by pauldalyii** [comment]
@fabiocav, I see a newer version of the runtime in the portal (`2.0.11370.0`).  Thanks!

![image](https://user-images.githubusercontent.com/1781802/32564284-a360699a-c468-11e7-8c03-ee3eb19f0641.png)

After seeing the updated version, I attempted to see if I could get my FunctionApp running with this newer version, however I get `FileLoadException`s when running in Azure that I don't see when running locally...

![image](https://user-images.githubusercontent.com/1781802/32564352-df78cc88-c468-11e7-8402-809041865b04.png)

I checked into the runtime version and it looks like I'm running an older version of the runtime.  I'm at `2.0.11353.0`, but the Azure portal is at `2.0.11370.0`.

I got `2.0.11353.0` by running `npm i -g azure-functions-core-tools@2.0.1-beta.20`  I assume that I'll need to upgrade to a newer version of azure-functions-core-tools, resolve those `FileLoadException`s and redeploy, but I don't see a newer npm package atm.

I'm assuming you're still probably rolling this out - just wanted to call this out in case.

This makes me think I should probably lock my functionapp into a specific runtime version...

Anyway... thanks again @fabiocav!

**Comment by pauldalyii** [comment]
@fabiocav, I saw that `azure-functions-core-tools@2.0.1-beta.21` was released this morning.

After installing and running the function app locally, I got a similar `FileLoadException` wrt Autofac above.
![image](https://user-images.githubusercontent.com/1781802/32634236-7a0cde50-c55f-11e7-8835-e0cc9a0b0a09.png)
Thinking I've run into some sort of binding redirect issue, I tried downgrading my project's reference to Autofac from `4.6.2` to `4.6.1`.  The function app started working locally again.

I deployed the functionapp to Azure to see if it would work there.  However, I still get the same `FileLoadException` after executing a function (see screenshot from my last post).  I verified that the Azure environment has been toggled to the `beta` runtime and is @ `2.0.11370.0`.

I'm not sure what to try next...

**Comment by mweinand** [comment]
I am experiencing the same issue when attempting to use Visual Studio to run a Microsoft.NET.Sdk.Functions 1.0.7 app and referencing EntityFrameworkCore 2.0.1.

**Comment by DOMZE** [comment]
@mweinand I am also experiencing the same error using the same versions (Microsoft.NET.Sdk.Functions 1.0.7 app and referencing EntityFrameworkCore 2.0.1)
I get: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

**Comment by ahmedelnably** [comment]
closing this as stale, please reopen if you still have the issue persisting
