### ISSUE TITLE
User secrets for functions aren't working as documented

### ISSUE THREAD

**Issue by samuelbcollie** [Azure/azure-functions-core-tools#2538]
I'm currently unable to load UserSecrets without adding the following line to my Startup.cs:

`builder.ConfigurationBuilder.AddUserSecrets(Assembly.GetExecutingAssembly());`

I've seen this step mentioned in unofficial tutorials but not on the [offical documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#using-aspnet-core-user-secrets). Is this a needed step, or is something going wrong here? Everything works fine if I use the "AddUserSecrets" method.

**Environment Info**
Azure Functions Core Tools
Core Tools Version:       3.0.3388 
Function Runtime Version: 3.0.15371.0

**Comment by samuelbcollie** [comment]
The app is not public. Is there other info I can give you such as the exact versions of certain NuGet packages? It's a v3 function targeting .NET Core 3.1.

**Comment by samuelbcollie** [comment]
I figured it out. I made a brand new function to see if I could repro it. The issue was that I didn't have the following in my local.settings.json:

`"FUNCTIONS_WORKER_RUNTIME": "dotnet"`

**Comment by apawast** [comment]
Thank you for your update. Closing as resolved.
