### ISSUE TITLE
Unable to find an Azure Storage connection string to use for this binding.

### ISSUE THREAD

**Issue by SergeyBoiko** [Azure/azure-functions-core-tools#2540]
Hi, I'm getting next error:

`Microsoft.Azure.WebJobs.Extensions.DurableTask: Unable to find an Azure Storage connection string to use for this binding.`

as I got it, workaround is to add "AzureWebJobsStorage" to the "Application settings", wondering why "Function Creator" wizard did not suggest me to select proper AzureWebJobsStorage...

**Question:**
If adding AzureWebJobsStorage is correct solution/workaround, what exact value I need to put there and from where I need to get it?

**Repro steps:**
1) Open any browser and use only UI (without any CMD commands)
2) Create Function App with next parameters:

Runtime stack: .NET 3.1
Hosting Plan: App service plan
Operating System: Windows
Region: North Europe
Shared infrastructure: 1 GB memory
Monitoring: Application Insights - Not enabled

3) Add DurableFunctionsHttpStart
4) Navigate to "Overview" tab and you'll see that error 
or
5) hit "Code + Test" button for DurableFunctionsHttpStart

Thanks.

**Comment by apawast** [comment]
@SergeyBoiko I just want to clarify some things. Did you use the Azure Portal, and it says that you have no azure storage connected at all? Portal is supposed to automatically add storage connection when you hit create at the end of the creation wizard. Are you able to reproduce the error consistently?

**Comment by SergeyBoiko** [comment]
@apawast 

> Did you use the Azure Portal, and it says that you have no azure storage connected at all?
exactly

>Portal is supposed to automatically add storage connection when you hit create at the end of the creation wizard
then it looks like a bug in creation wizard 

>Are you able to reproduce the error consistently?
yes, each time when I create function via Azure Portal (as described above)

just realized that it's not related with azure-functions-core-tools, because I've used only Azure Portal, i.e. current bug more for Azure Portal....

Thanks.

**Comment by apawast** [comment]
@SergeyBoiko are you still seeing this issue? If yes, is it still only happening in Portal? We may need to transfer this issue to the portal repo if that is the case.

**Comment by chrisevans9629** [comment]
I also got the same issue exactly as the author described.  I created a durable azure function http starter and got `Microsoft.Azure.WebJobs.Extensions.DurableTask: Unable to find an Azure Storage connection string to use for this binding.`.  This occurs for both Node.js and .Net Core
