### ISSUE TITLE
One or more errors occurred. (A task was canceled.)

### ISSUE THREAD

**Issue by suiwenfeng** [Azure/azure-functions-core-tools#2542]
``` shell
bash-5.0$ func new
Select a number for worker runtime:
1. dotnet
2. dotnet (isolated process)
3. node
4. python
5. java
6. powershell
7. custom
Choose option: 5
java
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing /home/low/Projects/azure/.vscode/extensions.json
One or more errors occurred. (A task was canceled.)

bash-5.0$ func --version
3.0.3388

bash-5.0$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

**Comment by apawast** [comment]
@suiwenfeng thank you for opening this issue! We are investigating this.

fyi @amamounelsayed

**Comment by ankitkumarr** [comment]
@suiwenfeng, showing java in the options was actually a bug. For creating new java Azure Functions, we ask customers to use our Maven tools. Here's the docs for that -- https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-java?tabs=bash%2Cazure-cli%2Cbrowser

We will fix the bug that started showing Java in `func init` and `func new` commands.

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-functions-core-tools/commit/177d7e8163a075443b6a0e93baf78e6480e489c3
