### ISSUE TITLE
Install azure-function-core-tools by homebrew is failed.

### ISSUE THREAD

**Issue by taejoon-bluebeaker** [Azure/azure-functions-core-tools#2548]
- os - mac
- problem - Cannot install azure-functions-core-tools.
- location - South Korea

Downloading https://functionscdn.azureedge.net/public/3.0.3442/Azure.Functions.Cli.osx-x64.3.0.3442.zip is failed.
Downloading same file via chrome is also failed.

I tried install it whole day with changing place.(The internet status is very fine).
I think "functionscdn.azureedge.net" has some problem to send the file.
Please, check the status to download the file.
"azure-functions-core-tools@2" and "npm i -g azure-functions-core-tools@3" are also same status.

<img width="761" alt="스크린샷 2021-04-14 오후 8 52 35" src="https://user-images.githubusercontent.com/79179822/114705993-5ea31000-9d63-11eb-8ffa-deb159ca03cf.png">

**Comment by apawast** [comment]
@taejoon-bluebeaker are you still having this issue? If yes, can you please share what error you're getting from chrome? Are you seeing this on multiple machines? We are unable to reproduce this at the time.

**Comment by taejoon-bluebeaker** [comment]
It is solved. I installed it today. Thanks!
