### ISSUE TITLE
Warning no Connection String when using managed identity - CLI

### ISSUE THREAD

**Issue by cachai2** [Azure/azure-functions-core-tools#2552]
For the new secretless triggers/bindings, they no longer use connection strings. However, our CLI will throw warnings when connection strings aren't used despite not being in a warning state. We should remove the warnings for secretless. This is a potential preview blocker for Track 2 sdk triggers.

Files to update:
line 426: https://github.com/Azure/azure-functions-core-tools/blob/6a070fb40308438c758ba8ab69399845bd698391/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs

line 120: https://github.com/Azure/azure-functions-core-tools/blob/6a070fb40308438c758ba8ab69399845bd698391/test/Azure.Functions.Cli.Tests/ActionsTests/StartHostActionTests.cs

**Comment by fabiocav** [comment]
Can you also clarify the priority on this? We're having a difficult time with the assignment

**Comment by cachai2** [comment]
This is a very high P2 for preview. P1 (blocker) for GA.

**Comment by fabiocav** [comment]
@karshinlin is this something you're expecting to pick up?

**Comment by fabiocav** [comment]
@cachai2 assigning this to sprint 102, but this is still pending assignment.

**Comment by fabiocav** [comment]
Moving to 105, PR in progress.

**Comment by fabiocav** [comment]
Work nearing completion, leaving this assigned to 105

**Comment by fabiocav** [comment]
@madelinegordon opening a PR as we're blocked on some test scenarios. Moving to 106 as we'll be iterating and merging the PR then.
