### ISSUE TITLE
List of available templates for func new?

### ISSUE THREAD

**Issue by danechitoaie** [Azure/azure-functions-core-tools#2553]
Looking at https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-javascript I see the `--template "HTTP trigger"` param.
Where can I find a list of all available templates?

**Comment by apawast** [comment]
@danechitoaie you can run `func new` without any parameters and it should give you the list of options.
