### ISSUE TITLE
func new doesn't work for GitBash (Mingu64)

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-core-tools#2561]
GitBash doesn't work. 

![image](https://user-images.githubusercontent.com/1390976/115304956-7212fa00-a11a-11eb-97c7-83a9c124b403.png)

CMD works. 

![image](https://user-images.githubusercontent.com/1390976/115305012-848d3380-a11a-11eb-9e01-839097c31e8f.png)

This issue is not severe, however, just share it as known issue. 
@pragnagopa

**Comment by kshyju** [comment]
@TsuyoshiUshio Is this still a valid issue with latest version of core tools?
