### ISSUE TITLE
How to use ScriptHost externally for test?

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/azure-functions-core-tools#2565]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C# ?

#### Question
I am a Azure Function extensions writer. I want to test my extension with functions written in different languages. It seems that to use `ScriptHost` is the most elegant way. So how can I reference the Microsoft.Azure.WebJobs.Script package?

I try to use `Install-Package Microsoft.Azure.WebJobs.Script -Version 3.0.15352 -Source https://www.myget.org/F/azure-appservice/api/v3/index.json` to install the package and add the following line to the `.csproj` file.
```csproj
<PackageReference Include="Microsoft.Azure.WebJobs.Script" Version="3.0.15352" />
```

When I build with `dotnet build`, I got error like this : "error CS8002: Referenced assembly 'Microsoft.Azure.WebJobs.Script, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name."

**Comment by apawast** [comment]
@Y-Sindo the azure-functions-host repo is probably the best example we have on how to do this.
