### ISSUE TITLE
MethodNotFound when trying to call JsonResult with JsonSerializerSettings

### ISSUE THREAD

**Issue by marjtecson07** [Azure/azure-functions-core-tools#2575]
Azure Functions Core Tools (3.0.3442)
Function App: netcoreapp2.1
Function App Version : v2

Error when testing the HTTP function:
System.Private.CoreLib: Exception while executing function: PostReport. http.functions.core: Method not found: 'Void Microsoft.AspNetCore.Mvc.JsonResult..ctor(System.Object, Newtonsoft.Json.JsonSerializerSettings)'.

There was a related issue [1907](https://github.com/Azure/azure-functions-core-tools/issues/1907) posted previously however, the suggested solution won't work in my case since I'm using netcoreapp2.1. Can someone direct me as to which version of `azure-functions-core-tools` is compatible with my function app?
![image](https://user-images.githubusercontent.com/83732048/117211957-40917280-ae2c-11eb-86b4-39917ee787f0.png)

**Comment by apawast** [comment]
@marjtecson07 are you hitting this issue locally or on azure online? Are you targeting to the ~2 or the ~2.0? Is there something preventing you from moving to Functions 3.0/.NET Core 3.1?

**Comment by marjtecson07** [comment]
I'm debugging locally. We can't move yet to netcore3.1 since it'll take time to regress the other existing functionalities. Anyway, I managed to resolve this by finding a copy of a lower version of cli tools and overriding the debug properties of my project. Not sure why VS downloaded an incompatible cli version in the 1st place. Thanks for replying!
