### ISSUE TITLE
In Alpine only the windows installation works, Is it OK?

### ISSUE THREAD

**Issue by CodePrC** [Azure/azure-functions-core-tools#2577]
npm i -g azure-functions-core-tools@3 --unsafe-perm true

**Comment by apawast** [comment]
@CodePrC if you are seeing in the docs that this is a windows specific command, that is not the case. Does that answer your question? If not can you please give more clarification of what you're looking for?

**Comment by CodePrC** [comment]
@apawast this commands work for alpine, & the ubuntu(apt-get) command does not work there

**Comment by apawast** [comment]
@CodePrC yes that is expected and we will update the documents to reflect that.
