### ISSUE TITLE
Azure Functions disappeared from Static Web Apps

### ISSUE THREAD

**Issue by josephh** [Azure/azure-functions-core-tools#2585]
We've been using Azure SWA to host Functions.  They've stopped showing today.  This has been reported elsewhere outside of our organisation - https://docs.microsoft.com/en-us/answers/questions/390580/swa-function-no-longer-appearing-in-39functions39.html?childToView=390753#answer-390753

Are any of the maintainers of this project aware of this problem and can you advise?

Mentioning @anthonychu - who helped previously re #2454 

thanks

**Comment by balag0** [comment]
It is possible this was due to an issue in West Europe region yesterday. Could you please try again.
