### ISSUE TITLE
Configuration value 'always' is not supported. Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by asharma-gh** [Azure/azure-functions-core-tools#2596]
Hello, we are using Visual Studio 2019 to develop our azure functions in C# and would like to have logs write to a file. We tried setting `fileLoggingMode` to `always` but run into the error in the title: 
```
[2021-05-18T16:03:02.621Z] Microsoft.Extensions.Logging.Configuration: Configuration value 'always' is not supported.
Value cannot be null. (Parameter 'provider')
```

the host.json is:
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "App": "Information",
      "fileLoggingMode": "always",
    },
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  }
}
```

Is there a way to have local logs write to a file? And if not, are there recommended settings for local azure function logging? (Particularly in VS2019 and C#)

**Comment by apawast** [comment]
@asharma-gh what is your scenario here? Why do you need local files?

**Comment by asharma-gh** [comment]
the scenario is to send logs across the team easily. 

Currently logs are found in the  VS debug output, func tools command prompt, and now in AppData thanks to the fileLoggingMode set to always

The logs in each of these sources is different, and ideally they would all be found in one place to make sending them across the team easier. Local files also have the advantage of being used with text editors so searching and copying text is easier

If it is possible we would like to have the logs from func tools specifically piped to files locally so they can be used with text editors, since these are more important for debugging, but if that is a limitation then it is understandable.

thanks!

**Comment by apawast** [comment]
@asharma-gh did my above suggestion for changing the configuration work for you?

**Comment by asharma-gh** [comment]
yes the solution above has worked, thank you!
