### ISSUE TITLE
Publishing on Mac does't warn about missing function app

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#260]
On Windows (v1.0.4) when I try to publish using `func azure functionapp publish funcappdoesnotexist`  I get a nice error:
   
    Can't find app with name "funcappdoesnotexist" in current subscription.

When I try the same thing on Mac (v2.0.0) I just keep getting a request to reauthenticate. This seems buggy and is misleading to users.

**Comment by ahmelsayed** [comment]
the re-authenticate issue is a separate bug. If you do `func azure subscriptions list` you'll see a list of your sub and the current subscription. the error is saying that the function app doesn't exist in the selected current subscription. I believe this should be similar to the behavior of the azure cli.

**Comment by ahmelsayed** [comment]
Closing as obsolete.
