### ISSUE TITLE
Microsoft Azure WebJobs SDK ServiceBus connection string 'MessageBusConnection' is missing or empty.

### ISSUE THREAD

**Issue by christcottrell** [Azure/azure-functions-core-tools#2609]
I have a function app where I am setting the value of MessageBusConnection from Key Vault.  I can go to the configuration and see the setting is there.  MessageBusConnection with a key vault reference. The other point is that this is in a deployment slot where the other slot is working. And yes, I did check the config for the deployment slot and the setting is there.  I also do have the identity enabled to access key vault for this function app. Is there some combination of slots + function apps that cause key vault references in the application Settings to not work? I've spent hours looking at this and trying different things.

Note that I have the exact same settings for both slots except for the secret name which does exist in the vault. I also see this when I look at this from our demo slot. I can also verify that it is referencing the right version even when it was defined like this within the value - @Microsoft.KeyVault(VaultName=donecloudcmpkeyvault;SecretName=MessageBusDev)

In the key vault reference details, I see this (leaving out the vault name). But I am not sure why it could not be resolved. Removing it and adding it back do not work. Also, these are added from an ADO pipeline. 

Thanks!

Secret Name
MessageBusDemo
Secret Version
682c8f37bd8c44b1a1193682fc01cf28)
Identity
System assigned managed identity
Status
OtherReasons
Error Details
Key Vault reference was not able to be resolved.

**Comment by christcottrell** [comment]
Update.. I removed and redeployed and the status now shows resolved, but it is still getting the error saying that MessageBusConnection is missing or empty..  It does have a value. 

![image](https://user-images.githubusercontent.com/53835198/120043656-fbe39c00-bfd1-11eb-9289-ce4d979055d7.png)

And here is showing that we have a value in that secret and you can also see that secret version. 
![image](https://user-images.githubusercontent.com/53835198/120043794-3e0cdd80-bfd2-11eb-8e45-8f2db0406b44.png)

**Comment by christcottrell** [comment]
Copying the code for the function to show the use of the MessageBusConnection..  Note that everything works in the dev slot, but the demo does not work.

[FunctionName("ValidationQueue")]
        public async Task Run([ServiceBusTrigger("cmp_validation", Connection = "MessageBusConnection")]string queueMessage, ILogger log)
        {
            log.LogInformation($"ValidationQueue trigger function processed: {queueMessage}");
            ApiRequestData apiRequestData = JsonConvert.DeserializeObject<ApiRequestData>(queueMessage);
            if (apiRequestData == null)
            {
                throw new ApplicationException("Format or data provided to validate is incorrect");
            }
            await validationService.Validate(apiRequestData);

        }

**Comment by christcottrell** [comment]
Here is a screenshot of the error..  I also know it is not running since it has not processed the item in the queue. Can also see the same error in App Insights. 

![image](https://user-images.githubusercontent.com/53835198/120044400-65b07580-bfd3-11eb-8716-f45b82067f46.png)

**Comment by christcottrell** [comment]
Just wondering if there are any updates on this? Funny how you will respond to these issues and then close them within a day if there is no response, but 11 days without a response on your side?  Each and every day I am planning my exit strategy for my apps to go to AWS. I just need reliable.

**Comment by christcottrell** [comment]
Yes. It does work when either the MessageBusConnection is in key vault.  And I'll explain.. We have a dev / demo key vault. They share a lot of the same values excluding the connection string to a database and also the message bus we connect to. So we use a key vault reference so that we can set MessageBusConnection to a MessageBusDev or MessageBusDemo. It is in East US 2 and the app name is dcmpAzureeastus2. Note that we have skipped deploying or using demo for now so I haven't  seen what state it is in lately.  Thanks!

**Comment by christcottrell** [comment]
I think I may contact Azure support on this, but I was hoping for some type of resolution here as I find reviewing past issues helpful in solving my own at times so it kind of contributes back if someone else is seeing the same. Oh, and there are multiple function apps that are doing the same, but the example above was just one of them. Thanks!

**Comment by apawast** [comment]
@christcottrell contacting azure support is probably your best option as this seems to be an issue affecting your specific environment.
