### ISSUE TITLE
publishing from command line tools does not support deployment slots

### ISSUE THREAD

**Issue by yehudamakarov** [Azure/azure-functions-core-tools#2610]
`func azure functionapp publish` should be able to publish to a certain deployment slot as per documentation. It doesn't seem like this is a capability.

**Comment by yehudamakarov** [comment]
despite https://github.com/Azure/azure-functions-core-tools/commit/9cc58db73732bf17364c151be822036f52c78cd4 closing https://github.com/Azure/azure-functions-core-tools/issues/227

**Comment by joshhighet** [comment]
This should work (albeit undocumented)

`func  azure functionapp publish fn_name --slot slot_name`

https://github.com/MicrosoftDocs/azure-docs/issues/69117

**Comment by yehudamakarov** [comment]
@joshhighet excellent! Thank you. maybe we can ping the documentation updaters?

**Comment by ggailey777** [comment]
It does sound like there's a code bug (https://github.com/Azure/azure-functions-core-tools/issues/2612) preventing the argument from printing in the help. I'll add `--slot` to the Core Tools article in the meantime.
