### ISSUE TITLE
Argument --slot not being printed for func azure functionapp publish 

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#2612]
As mentioned in https://github.com/Azure/azure-functions-core-tools/issues/2610 the `--slot` setting isn't being generated with the help output for `func azure functionapp publish`. Per @ahmelsayed, the [order of adding the arg and throwing the exception](https://github.com/Azure/azure-functions-core-tools/blob/v3.x/src/Azure.Functions.Cli/Actions/AzureActions/BaseFunctionAppAction.cs#L16-L32) is probably what’s causing it to not print out.

**Comment by ARMcK-hub** [comment]
Even though this is not currently supported, slot deployment is a feature of interest. Can we consider adding this feature to core tools?

**Comment by m1stermanager** [comment]
this would be a great one to see get fixed. definitely a time waster

**Comment by michaelpeng36** [comment]
Resolved by #2734
