### ISSUE TITLE
"azure functionapp publish" deploys Debug builds for net5

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#2628]
If we publish our net5 standalone function app via "azure functionapp publish" it gets build in Debug mode. This is a very very bad default for production deployments and also breaks all out `#if DEBUG` compiler directives

**Comment by forki** [comment]
Is there any news here? This is a quite dangerous bug

**Comment by fabiocav** [comment]
Adding this to triaged. The Core Tools command needs to be updated to pass the configuration flag. The workaround in the meantime is to build and deploy the project output.

**Comment by kshyju** [comment]
Fixed by #2711
