### ISSUE TITLE
Azure function deployment via func deployed without error but function not appearing

### ISSUE THREAD

**Issue by vishnu-anil** [Azure/azure-functions-core-tools#2634]
We have followed https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-python?tabs=azure-cli%2Cbash%2Cbrowser and used the func tool to deploy a python funtion via func cli.

* The deployment completes successfully
* Activity logs shows deployment
* Kudu show deployment successful

But no function is displayed in the portal.

When the same is deployed via Visual studio code, the function appears in the portal

**Comment by apawast** [comment]
@vishnu-anil can you share the deployment command you used?

**Comment by vishnu-anil** [comment]
Sorry it was a silly mistake. The deploy hd to be triggered from one folder ahead. It is resolved now. Thank you @apawast
