### ISSUE TITLE
dotnet-cli-params does not work with latest version of func CLI

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/azure-functions-core-tools#2648]
I'm trying to deploy a .NET-based Azure Function with additional dotnet CLI parameters to Azure by the following command:

```bash
func azure functionapp publish <function_name> --dotnet-cli-params -- "-c Release"
```

Unfortunately the command fails using Azure Functions CLI version 3.0.3568 with the following error:

```
Error parsing dotnet-cli-params. When publishing dotnet functions, the core tools calls 'dotnet build --output bin/publish'. Any parameters passed to this will be appended to the command line.
```

When I try the same with version 3.0.3477 it however works and deploys fine.

- Azure Functions CLI version 3.0.3568
- Platform: Windows 10

**Comment by anthonychu** [comment]
Looks like this is a regression. @fabiocav 

Related #2628

**Comment by fabiocav** [comment]
@anthonychu have you been able to repro? Have you also tried adding a space before the arguments? I recall @brettsam stating that was an odd behavior with that (e.g. func azure functionapp publish <function_name> --dotnet-cli-params -- " -c Release")

**Comment by anthonychu** [comment]
Actually, looking at the command that's being run, looks like it's incorrect. I believe it should be:

```
func azure functionapp publish <function_name> --dotnet-cli-params "-c Release"
```

@gastonmuijtjens can you please give that a try?
