### ISSUE TITLE
Add command to help install extensions

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-core-tools#265]
Essentially:
```
dotnet new classlib
dotnet add package Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator --version 1.0.0-beta2
dotnet add package Microsoft.Azure.WebJobs.Extensions.<extension> --version <version>
dotnet build -o ./bin
```

**Comment by sebastus** [comment]
Is this equivalent to using "func extensions ..."? Tried to use it, I keep getting the "usage" recommendation with no error message.

**Comment by mamaso** [comment]
It's basically equivalent, yep.  What is the specific error? And why not use `func extensions` directly?

**Comment by sebastus** [comment]
I am using ```func extensions``` directly. A few things:

1. ```func extensions``` by itself says I should do ```func extensions [context] <action> [-/--options]```. But it doesn't say what is a valid ```[context]```.
2. Similarly, ```func extensions functionapp``` tells me ```func extensions functionapp <action> [-/--options]```, but nothing about what's a valid ```<action>```.
3. And, ```func extensions function``` tells me ```func extensions function <action> [-/--options]``` and stops there as well.

I'm trying to use ```func extensions``` to install ```Microsoft.Azure.Relay``` for local testing with a CSX function. I use this command line:

```func extensions functionapp install -p Microsoft.Azure.Relay -v 1.0.0```

But like before, I only get a one-liner in response with nothing about what's wrong or how to fix it.

So - specific error == null.

**Comment by mamaso** [comment]
@sebastus If you run `func extensions`, you'll see the actions `install` and `sync` listed:

![image](https://user-images.githubusercontent.com/9870694/31567597-3273b6da-b025-11e7-8650-e74eeb8a58ae.png)

However, your scenario appears to be for installing a nuget package, not an Azure Functions Binding Extension nuget (https://mikhail.io/2017/07/authoring-custom-binding-azure-functions/), so you can just do this by adding a reference to your precompiled function or `csx`.

**Comment by ahmelsayed** [comment]
Closing as obsolete.
