### ISSUE TITLE
Issues with "deploySubpath"

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-functions-core-tools#2650]
Please add a link or link to the documentation as I was unable to locate this on web searches.  when using this in a dialog for publishing help, it would also be nice to include what it is before recommending it for those of us new to the extension.

I'm in a situation now where I deployed what appears, based on logs, the entire parent folder structure and I anticipated deploying to the configured subpath.  Also, considering, I chose that folder/files through the context menu to deploy expecting just that folder to deploy to my dismay.  When using the extension itself you pick the location, and using the file system on VS Code I expected the same behavior or at least be smart enough to know I only want this folder deployed.  

This experience or my lack of understanding just corrupted my entire functions service.  Could we improve this UX?

**Comment by anthonychu** [comment]
@ejizba @fiveisprime Can you please take a look? I don't have the permissions to transfer this to https://github.com/microsoft/vscode-azurefunctions/issues

**Comment by ejizba** [comment]
We don't have permissions to transfer either. @awentzel I would recommend you file a new issue on the VS Code extension with succinct repro steps and ideally some screenshots of what your workspace looked like when you ran into problems

https://github.com/microsoft/vscode-azurefunctions/issues/new

**Comment by apawast** [comment]
Hi @awentzel, per Eric's instruction it would be best if you open an issue in the VSCode repo.
