### ISSUE TITLE
"The selected folder is not a function project. Create new project?"

### ISSUE THREAD

**Issue by awentzel** [Azure/azure-functions-core-tools#2651]
This message is confusing and I'm not clear what the best way to create a project/function?  In particular, what folder selection? The File Explorer or Azure in VS Code.  I assumed if I clicked on 'function' tree view and then choose create function a new function would be created within the configured file system.  In my case, a change would commit to 'cloud/services/functions/' where I have a single functions project and multiple functions created.  

The same confusion has now rendered my Function corrupt and even though the files still exist in File Explorer within VS Code, I can't figure out how to deploy them, now that things are corrupted.  I don't really want to manually create in Azure Portal, I prefer a UI/UX whereby it's intuitive for the user to create a new project/function or add to an existing project or function.  Ideally, the focused folder in Explorer or Azure would be the folder to deploy, unless azureFunctions.deploySubpath has a value.

**Comment by anthonychu** [comment]
@ejizba @fiveisprime Can you please take a look? I don't have the permissions to transfer this to https://github.com/microsoft/vscode-azurefunctions/issues

**Comment by ejizba** [comment]
See https://github.com/Azure/azure-functions-core-tools/issues/2650#issuecomment-894445870

**Comment by apawast** [comment]
Hi @awentzel, per Eric's instruction it would be best if you open an issue in the VSCode repo.
