### ISSUE TITLE
Create func app doesn't add a start command to the package.json

### ISSUE THREAD

**Issue by diberry** [Azure/azure-functions-core-tools#2654]
I created the function app with 

```bash
npx func init --worker-runtime node --language typescript
```

Why didn't it add a "start" script to the package.json? 

If I run `npx func --version`, I get 3.0.3477.

**Comment by anthonychu** [comment]
It should. Can you share the package.json that it produced? This is the file that should be created: https://github.com/Azure/azure-functions-core-tools/blob/85caa2bf83cae49adbd967a939e1534ea4a98988/src/Azure.Functions.Cli/StaticResources/package.json
