### ISSUE TITLE
Update Readme - Azure Functions Core Tools can be installed via winget

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-functions-core-tools#2656]
![image](https://user-images.githubusercontent.com/74415662/126558960-34955c89-6b2e-43fa-b73c-06946f7bfd59.png)

Since we can now install the tools via winget, it would be great to have that in the instructions.

**Comment by apawast** [comment]
@charris-msft in order to update the readme with this we would have to update our release and test process to validate things works as expected with winget. Updating the readme would be dependent on that.
