### ISSUE TITLE
Core Tools warns even with valid identity-based connection

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-core-tools#2657]
#### What problem would the feature you're requesting solve? Please describe.
Using identity-based connections locally. Have a setting "MyStorageConnection__serviceUri" (actual suffix of "endpoint" for time being due to bug). Core Tools warns on host start:
> Warning: Cannot find value named 'MyStorageConnection' in local.settings.json that matches 'connection' property set on 'queueTrigger'...

#### Describe the solution you'd like
This warning should not occur as it is a valid configuration for this extension.

#### Describe alternatives you've considered
N/A

#### Additional context
CC @fabiocav who is plugged in on identity-based connections

**Comment by soninaren** [comment]
Looks like the work for this was completed by @madelinegordon

**Comment by soninaren** [comment]
Dup of https://github.com/Azure/azure-functions-core-tools/issues/2552
