### ISSUE TITLE
macOs Rider debug alternatively working, run works always

### ISSUE THREAD

**Issue by DaviehS** [Azure/azure-functions-core-tools#2668]
I have a proj using dotnet 5 on macOs big sur, most tries to run debug for debug/rerlease, it gets stuck in the middle and doesn't launch the service. normal Run works always.

When. trying debug:
`/Applications/Rider.app/Contents/lib/ReSharperHost/macos-x64/dotnet/dotnet exec /Applications/Rider.app/Contents/lib/ReSharperHost/JetBrains.Debugger.Worker.exe --mode=client --frontend-port=53203 --plugins=/Applications/Rider.app/Contents/plugins/rider-unity/dotnetDebuggerWorker
Service Starting!
Starting service
info: AWSSDK[0]
      Found AWS credentials for the profile default
info: AWSSDK[0]
      Found AWS credentials for the profile default
info: AWSSDK[0]
      Found AWS credentials for the profile default
`

and it gets stuck there, 

whereas when i click run it works and shows more logs that it lunched the swagger etc..
`/usr/local/share/dotnet/dotnet /Users/dsamokovlisky/Work/search-framework/services/srch-shared-context/src/app/SharedContext.Rest/bin/Debug/net5.0/Cornerstone.Search.SharedContext.Rest.dll
Service Starting!
Starting service
info: AWSSDK[0]
      Found AWS credentials for the profile default
info: AWSSDK[0]
      Found AWS credentials for the profile default
info: AWSSDK[0]
      Found AWS credentials for the profile default
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:9000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path:
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:9000/swagger/index.html - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:9000/swagger/index.html - - - 200 - text/html;charset=utf-8 263.8486ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:9000/srch-shared-context/swagger/v1/swagger.json - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:9000/srch-shared-context/swagger/v1/swagger.json - - - 200 - application/json;charset=utf-8 1169.5186ms`

In the Debug Output window i see bunch of "Pdb file for assembly was not found or failed to read"

I tried cancelling the debug symbols - under the prod -> properties -> debug -> debug symbols
Also disabled Preferences -> build,execute,deployment -> debugger -> "enable external source debug"
Latest Rider updated

Uploaded logs : Upload id: 2021_07_28_Q97JBppRW97XmFkB (file: Logs.zip)

**Comment by apawast** [comment]
@DaviehS could you please provide repro steps for this? And/or what exactly you are trying to debug and what project type this is?
