### ISSUE TITLE
Azure functions onpremise in production environments

### ISSUE THREAD

**Issue by goncrip** [Azure/azure-functions-core-tools#2675]
I understand that Core Tools applies to development and testing environments. I cannot use this tool in production.

What alternatives do I have to run Azure function onpremise in production?

I already reviewed this [documentation](https://docs.microsoft.com/en-us/azure/architecture/hybrid/azure-functions-hybrid) and it was clear to me that Core Tools is only for development so it does not confirm that there is an alternative for productive environments.

Could I use Kebernetes and Azure Functions in productive environments (onpremise)?

**Comment by anthonychu** [comment]
For Kubernetes, please see:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda
https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-arc-cli
