### ISSUE TITLE
ImportError - Wrong Architecture - M1 Apple Silicone

### ISSUE THREAD

**Issue by simon-tarr** [Azure/azure-functions-core-tools#2680]
I'm running on an M1 (Apple Silicone) Macbook and trying to develop some Azure Functions within a Django project. I require the following packages:
```
azure-common
azure-functions
azure-storage-blob
requests
```
When I start debugging mode to run functions for local development I get the error:
```
ImportError: dlopen(/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3477/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so, 2): no suitable image found.
Did find: /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3477/workers/python/3.9/OSX/X64/grpc/_cython/cygrpc.cpython-39-darwin.so: mach-o, but wrong architecture
```
I've been trying for hours to fix this - it must be some issue with x86 and arm64 builds of various libraries etc. but I've honestly no idea how to resolve.

Has anyone seen this before? If so, could any pointers be provided to I can successfully run debugging for Azure Functions?

**Comment by ejizba** [comment]
Consolidating M1 issues. Will use https://github.com/Azure/azure-functions-python-worker/issues/915 for Python work and https://github.com/Azure/azure-functions-core-tools/issues/2834 for core tools
