### ISSUE TITLE
The attempt to publish the ZIP file through https://---.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code ServiceUnavailable.

### ISSUE THREAD

**Issue by ghabre** [Azure/azure-functions-core-tools#2699]
When publishing our web apis on a Linux App Service in Azure, using a publish profile added through Visual Studio 2019, we are occasionally seeing the above issue.

The attempt to publish the ZIP file through https://---.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code ServiceUnavailable.

When this happens, both the app service as well as scm / kudu services show as service unavailable.

It stays like this for a while then after an hour maybe automatically recovers on its own.

This has been going on for some time the past couple of weeks and still happening today, and delaying / affecting our development team often when we want to publish our work, 

Exact error showing our URL:
The attempt to publish the ZIP file through https://mga-platform-services-l01-dev.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code ServiceUnavailable.

**Comment by balag0** [comment]
@ghabre Does browsing to the home page work for you
 https://mga-platform-services-l01-dev.azurewebsites.net/
and
 https://mga-platform-services-l01-dev.scm.azurewebsites.net/

@lappy4711 Could you share your app name 
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
