### ISSUE TITLE
Core Tools build and release pipeline fixes/improvements 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-core-tools#2700]
Fix MSI and signing the Core Tools build

Release pipeline 
https://azfunc.visualstudio.com/Azure%20Functions/_releaseDefinition?definitionId=23&_a=definition-tasks&environmentId=113
1) Update Upload to storage task to check with an exe to make sure that the binaries are signed
- verify the minfied zip files 
- verify the msi are present and signed
- verify the nuget package (Microsoft.Azure.Functions.CoreTools.<version>.nupkg) is present and signed 

2) Update the Core Tools pipeline -- make signing and MSI generation contingent on branch names that are defined as list in build variables populate with common ones (ex. release_3.0, etc) but folks will be able to add as needed for specific builds

**Comment by Francisco-Gamino** [comment]
cc @soninaren @kashimiz @michaelpeng36 @AnatoliB

**Comment by apawast** [comment]
Closing this issue as all points should be addressed.
