### ISSUE TITLE
debian 11 support

### ISSUE THREAD

**Issue by snodnipper** [Azure/azure-functions-core-tools#2702]
Hi folks, it would be great if we can use this software with the current (stable) version of debian given the number of docker images based on that.

Thanks.

**Comment by balag0** [comment]
Are you using core tools inside a container? which image are you using?

**Comment by snodnipper** [comment]
Hi @balag0, thanks for reaching out.  I was using the default [openjdk](https://hub.docker.com/_/openjdk) image to assist a customer in building their Java Azure Function based on the [Azure Functions Gradle Example](https://github.com/Azure-Samples/azure-functions-samples-java).  After an hour or so of debugging it turned out that their [Function Core Tools](https://aka.ms/azfunc-install) was out of date - no obvious message apparently.

I was, however, to eventually get the core tools working with openjdk:11-slim-buster.

Building such samples with docker helps avoid the dreaded "works for me" comments.  Thanks!

**Comment by aaronadamsCA** [comment]
I can't currently install Core Tools on Debian 11, because its package is not available in the official repository.

```sh
$ curl -s https://packages.microsoft.com/debian/10/prod/dists/buster/main/binary-amd64/Packages | grep -c azure-functions-core-tools
206
$ curl -s https://packages.microsoft.com/debian/11/prod/dists/bullseye/main/binary-amd64/Packages | grep -c azure-functions-core-tools
0
```

**Comment by nSwann09** [comment]
any update on this?

Bullseye has been the stable release since august, it would be great is MS could update support for Debian.

**Comment by RiaanVR** [comment]
Indeed it would be great to have this, 

For now, a workaround that hasn't caused problems for my team is to use the older package from Debian 10.. 

We are waiting on [this](https://github.com/Azure/azure-functions-docker/issues/578) issue to remove our workaround .

**Comment by michaelpeng36** [comment]
I have updated the relevant repository so that Core Tools V4 should be available on Debian 11. Let me know if any issues occur.
