### ISSUE TITLE
Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-functions-core-tools#271]
Simpler hello world code using VS2017, .net FX 4.7, Microsoft.Net.Sdk.Functions (1.0.5). This function failing with Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 

Is this a known issue or any known workaround?

`    public static class Hello
    {
        [FunctionName("Hello")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");
            return req.CreateResponse(HttpStatusCode.OK, "Hello World!!");
        }
    }`

**Comment by gianlucb** [comment]
I have the same issue with SDK 1.0.6

**Comment by taspeotis** [comment]
I have the same issue using the beta runtime: `Runtime version: 2.0.11390.0 (beta)`

**Comment by philous** [comment]
any workaround?

**Comment by jakzale** [comment]
This sort of error usually means that you are referencing an assembly that is already part of Azure WebJobs SDK, but you are trying to use a different/newer version.

For instance, you might be referencing a newer version of `Microsoft.AspNet.WebApi.Client` which depends on `System.Net.Http.Formatting`.

I had a similar error when I tried to use a newer version of `Microsoft.AspNet.WebApi.Client` as the latest available version is `5.2.3`, but `Microsoft.Azure.WebJobs.Extensions.Http` depends on `Microsoft.AspNet.WebApi.Client` at `5.2.2`.

Removing the package reference to `Microsoft.AspNet.WebApi.Client` version `5.3.2` solved the problem in my case.

**Comment by zhzoo** [comment]
Will Microsoft.AspNet.WebApi.Client be updated to >= 5.2.4 anytime soon?
The versions before 5.2.4 do not natively support .netstandard

**Comment by TsuyoshiUshio** [comment]
If you want to solve this problem, you can change the HttpTrigger code of the Azure Functions to the new Style.  This is my workaround. https://medium.com/@tsuyoshiushio/azure-functions-v-2-0-httptrigger-with-cosmosdb-client-tips-15d313cb1cbe

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still facing the same issue, please reopen
