### ISSUE TITLE
Function app is not deploying from azure cli

### ISSUE THREAD

**Issue by manishnm** [Azure/azure-functions-core-tools#2710]
Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments, compressed xattrs
        duplicates are removed
Filesystem size 1.10 Kbytes (0.00 Mbytes)
        54.52% of uncompressed filesystem size (2.02 Kbytes)
Inode table size 104 bytes (0.10 Kbytes)
        40.31% of uncompressed inode table size (258 bytes)
Directory table size 132 bytes (0.13 Kbytes)
        78.11% of uncompressed directory table size (169 bytes)
Number of duplicate files found 0
Number of inodes 8
Number of files 6
Number of fragments 1
Number of symbolic links  0
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 2
Number of ids (unique uids + gids) 1
Number of uids 1
        root (0)
Number of gids 1
        root (0)
Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
Resetting all workers for test-azure-function-app-1234.azurewebsites.net
Deployment successful.
Remote build succeeded!
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = 'eedf6c37-6caf-4c4c-a016-9118c4f45d1e'.

**Comment by balag0** [comment]
Are you creating the app using a custom template? Linux functions only supports V2 and above
Try setting FUNCTIONS_EXTENSION_VERSION to ~3 

You can also create an app using the Azure portal to get an idea of the recommended and supported configs and then customize your template.

**Comment by michaelpeng36** [comment]
@manishnm Did the above workaround help resolve your error?
