### ISSUE TITLE
Exit code of a failed command is still 0

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-core-tools#272]
Example repro steps:
Run `func host start` in a folder without a function app

Expected: Non-zero exit code
Actual: Zero exit code

This is just one example, but there are several cases where the cli command can fail and the exit code isn't being reported properly

**Comment by ahmelsayed** [comment]
This should be fixed. ExitCode should be 1 on error.

![image](https://user-images.githubusercontent.com/645740/44436020-c0d1f580-a567-11e8-8464-f0d0a148d405.png)


There are some code paths that just print to stderr and not throw, so the process terminates successfully. I'll try to have a pass at the code, but feel free to open an issue if you see some failure without proper exitCode.
