### ISSUE TITLE
Warn if proxies.json exists in v4

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2727]
V4 doesn't support proxies. Core Tools should warn if proxies.json is defined in a v4 app.

**Comment by anthonychu** [comment]
Should recommend Azure API Management

**Comment by ejizba** [comment]
@anthonychu any preferences on when this warning occurs? I was thinking `func start` and/or `func publish`

**Comment by JasonKleban** [comment]
Is there some background on this change?  Why isn't it supported?  Is there a migration guide?  

Thanks though.  This is basically the first I've found of why my app broke after upgrading Azure, .NET and various other dependencies.  Glad it's being added to the tools.

**Comment by ejizba** [comment]
@JasonKleban I see you created https://github.com/Azure/Azure-Functions/issues/2165. That'll be a better place to follow up, as I personally don't have much more information than what you've already linked to
