### ISSUE TITLE
Msg to update version not actually installed

### ISSUE THREAD

**Issue by GaryParr** [Azure/azure-functions-core-tools#2729]
I keep getting messages asking to update an older version of core tools than I actually have installed. Running the update won't stop the message from coming back.  Not sure where it is pulling the value from so will just uninstall/re-install to see if that fixes it, but wanted to post here first on the off chance anyone wants me to check into anything to see _why_ this is happening.

![act_update_notice](https://user-images.githubusercontent.com/43426386/135089869-4edfd0e7-fa6d-4437-89b7-94170d64cac1.png)

**Comment by apawast** [comment]
@GaryParr it's possible that you may have installed multiple versions one using npm and another using a different package manager. One way would be to uninstall the npm one and see if VSCode is still picking it up. You said you're going to try uninstalling/installing anyway, did you see a change?

**Comment by GaryParr** [comment]
I figured it out.  I've been working with Azure Static Web Apps lately and the CLI tool packages in the older version. I removed the global tools for now since I don't need them at the moment.  Thanks!
