### ISSUE TITLE
func kubernetes commands failing with Permission denied error

### ISSUE THREAD

**Issue by alstel** [Azure/azure-functions-core-tools#2749]
I'm getting denied when executing func kubernetes commands and I'm not sure how to troubleshoot it.

![image](https://user-images.githubusercontent.com/32969315/136436020-2700283c-fd8a-4b37-ab6e-71abba506fa5.png)

I've tried multiple functions core tools versions (2 & 3) on multiple cluster contexts and I get the same result. **I can execute other func commands without issue.** Any idea what's causing this?

Running Ubuntu 20.04 WSL2.

**Comment by alstel** [comment]
![image](https://user-images.githubusercontent.com/32969315/137981115-3f5abdd9-ab29-4236-8403-ed5776f953aa.png)

**Comment by alstel** [comment]
I do have kubectl installed:
![image](https://user-images.githubusercontent.com/32969315/137984166-299fd4f7-761b-4c59-b853-8cc8de58dbbe.png)

The dry-run command you gave above does install KEDA. What should I be doing going forward given the standard commands failing?

**Comment by apawast** [comment]
@alstel are you still having this issue?
