### ISSUE TITLE
Syncing triggers bad request StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:

### ISSUE THREAD

**Issue by vsalesa** [Azure/azure-functions-core-tools#2757]
When trying to deploy from azure devops it deploys perfectly but in the end throws that error with bad request

**Comment by apawast** [comment]
@vsalesa can you please provide us steps on how to repro this and tell us more about the app/environment you are working with?
