### ISSUE TITLE
Error calling sync triggers (BadRequest)

### ISSUE THREAD

**Issue by afelipe00** [Azure/azure-functions-core-tools#2767]
I am trying to deploy an existing azure function app in the cloud, but it throws me a synchronization error:

specs and features:
+ windows version: windows 10 20H2
+ func version: 3.0.3442
+ Region: EastUs

Log (and error) after running command: `func azure functionapp publish "name-app"`

> Getting site publishing info...
Creating archive for current directory...
Performing remote build for functions project.
Deleting the old .python_packages directory   
Uploading 161,41 KB [#############################################################################]
Remote build in progress, please wait...
Updating submodules.
Preparing deployment for commit id '7625561809'.
Repository path is /tmp/zipdeploy/extracted
Oryx-Build: Running kudu sync...
Command: kudusync -v 50 -f /tmp/zipdeploy/extracted -t /home/site/wwwroot -n /home/site/deployments/7625561809354ef4bdc4b76d5bc89427/manifest -p /home/site/deployments/1b66b9da5b69469d921cb5359671d14f/manifest -i ".git;.hg;.deployment;.deploy.sh"
Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
Running post deployment command(s)...
Triggering recycle (preview mode disabled).
Deployment successful.
Remote build succeeded!
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = '429e65e4-0de2-468e-a57a-466a0bba7265'.

when I run the command with `CLI_DEBU=1`:

> Response:
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Server: Microsoft-IIS/10.0
  X-AspNet-Version: 4.0.30319
  X-Powered-By: ASP.NET
  x-ms-ratelimit-remaining-subscription-writes: 1199
  x-ms-request-id: 6adde591-8dda-4be9-a8b6-954019b0c01a
  x-ms-correlation-request-id: 6adde591-8dda-4be9-a8b6-954019b0c01a
  x-ms-routing-request-id: CENTRALUS:20211015T002127Z:6adde591-8dda-4be9-a8b6-954019b0c01a
  X-Content-Type-Options: nosniff
  Date: Fri, 15 Oct 2021 00:21:26 GMT
  Content-Length: 346
  Content-Type: application/json; charset=utf-8
  Expires: -1
}
{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}],"Innererror":null}

**Comment by balag0** [comment]
@jimmytricks To make sure I understand , the app was stopped so requests were failing with forbidden and once it was started back, the request started succeeding? Isn't that the expected behavior?

**Comment by jimmytricks** [comment]
Hi @balag0 , apologies if I wasn't clear.

When I try to deploy the app, it fails with the above error if the app is currently in the 'stopped' mode. It works if you start it and then re-deploy. This feels like a bug. Just because the app is stopped shouldn't cause an error to redeploy to it, or that's how it feels to me. Cheers!
