### ISSUE TITLE
Update default bundle once bundle V3 is finalized

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-core-tools#2769]
_This is a tracking item for action to take once the V3 bundle exists in the main bundle ID._

The current bundle default in the v3.x branch is the V2 bundle:

https://github.com/Azure/azure-functions-core-tools/blob/d6dfa462c9b626a1c5a20a44725364a2d31f9107/src/Azure.Functions.Cli/StaticResources/bundleConfig.json#L1-L4

Once the V3 bundle is finalized, we should update it to use V3:

```json
{
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
}
```

The goal here is to make default experiences use the latest GA item. The work here likely needs to be against both the `v3.x` and `v4.x` branches.

**Comment by apawast** [comment]
@mattchenderson when can we expect the V3 bundle to be finalized?

**Comment by mattchenderson** [comment]
That is tracked by https://github.com/Azure/azure-functions-templates/issues/1119

**Comment by apawast** [comment]
Closing as this work is complete
