### ISSUE TITLE
Install creates workers/node dir, runtime expects workers/Node

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#277]
Appears to be a case sensitivity issue.  If I install on a blank linux machine via npm I get some /workers on my home path, one of which is `node`.  However when I do `func host start` and have some node workers needed I get a bunch of errors as it is looking for workers `Node`.  If I change the worker directory to `Node` it all works.

**Comment by pvandorp** [comment]
Yep, same here. Linux filesystem is case-sensitive. After changing $HOME/.azurefunctions/bin/workers/node to $HOME/.azurefunctions/bin/workers/Node it works like a charm.

**Comment by ahmelsayed** [comment]
this should be resolved by now.
