### ISSUE TITLE
Error when trying to setup local development for PowerShell / HttpTrigger

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-functions-core-tools#278]
"func new --language PowerShell --template HttpTrigger --name Deploy" results in:

"Can't find template "HttpTrigger" in "PowerShell""

**Comment by itpropro** [comment]
Azure functions cli does not support PowerShell. Only Javascript or C# is supported. Adding the PowerShell blocks to the templates.json files (e.g. with fiddler) will not help, as the cli is not able to handle .ps1 files.

**Comment by ahmelsayed** [comment]
Powershell isn't implemented in v2 yet. Closing this as external
