### ISSUE TITLE
Create New Function in Azure-Hosted Functions App

### ISSUE THREAD

**Issue by alohaninja** [Azure/azure-functions-core-tools#279]
Love this CLI - we use it to publish our function apps now. The issue we ran into though is that you can create the function app via the the CLI, but you still have to use the portal to create new functions within a function app hosted in Azure. 

[Locally you can use create function](https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs) using `func new`, why can't we create new functions in azure this way? Simply deploying the directory does not *create* a new function. How can we avoid this manual step if we already have a `function.json`, `index.js` etc.

**Comment by SteveALee** [comment]
Yeah, i rised this a while back. Its annoying and makes ci/cd difficult unless uou use ARM

**Comment by ahmelsayed** [comment]
Closing as obsolete.
