### ISSUE TITLE
v4: Blob Trigger -> too verbose logging

### ISSUE THREAD

**Issue by mariotebest** [Azure/azure-functions-core-tools#2798]
Since we upgraded our functions to the v4 runtime our blob triggers create very spammy logs.

Is there a way to disable logging every request & response to and from the blob storage service so it behaves like v3 - or at least log this as _trace_ and not _information_?

![image](https://user-images.githubusercontent.com/54019893/139247291-1a4349fc-868b-4d24-85d5-75598a016556.png)

Our host.json looks like this:

```
{
	"version": "2.0",
	"logging": {
		"fileLoggingMode": "debugOnly",
		"logLevel": {
			"default": "Information"
		},
		"applicationInsights": {
			"samplingSettings": {
				"maxTelemetryItemsPerSecond": 5,
				"isEnabled": true
			}
		},
		"aggregator": {
			"batchSize": 30,
			"flushTimeout": "00:01:00"
		}
	},
	"extensions": {
		"serviceBus": {
			"prefetchCount": 100,
			"messageHandlerOptions": {
				"autoComplete": false
			}
		}
	}
}
```

**Comment by michaelpeng36** [comment]
@mariotebest  Would you be able to create an issue on the `azure-sdk-for-net` repository?
