### ISSUE TITLE
Chocolatey package azure-functions-core-tools-3 has a v4 version

### ISSUE THREAD

**Issue by flcdrg** [Azure/azure-functions-core-tools#2807]
Just noticed that Chocolatey package [azure-functions-core-tools-3](https://community.chocolatey.org/packages/azure-functions-core-tools-3#versionhistory) has a new version - 4.0.3928

That doesn't seem right, surely this package should only contain v3 releases?

![image](https://user-images.githubusercontent.com/384747/139607920-7279fddd-d931-4c71-938f-b5ab93f1402f.png)

(FYI I'm also a Chocolatey Moderator and have re-submitted the two v3 versions - looks like the CDN timed out waiting to download the file)

David

**Comment by anthonychu** [comment]
Thanks for the heads up. @michaelpeng36 @brettsam please take a look.

**Comment by flcdrg** [comment]
Package versions can't be deleted, but they can be unlisted (click on the 'yes' in the Listed column) and change it to a 'no'

**Comment by jbpaux** [comment]
I just saw that too 😅 Would be great to fix that and have a new package for v4

**Comment by michaelpeng36** [comment]
@flcdrg thank you for letting us know about this issue! We have now unlisted the Core Tools V4 packages.
