### ISSUE TITLE
Option to not show function key after publish

### ISSUE THREAD

**Issue by sebader** [Azure/azure-functions-core-tools#2813]
We are using the function core tools in a CI/CD pipeline to publish some functions and would very much like to not have the function key (`code=...` ) shown as part of the logs in clear text.

Ideally add a switch to the publish command to show/not show the code or the entire URL. Neither is needed for CI/CD pipeline runs.

![image](https://user-images.githubusercontent.com/11445087/140537216-4b239d6b-2229-478a-977c-65f2c803c14f.png)

Function core tools version: 3.0.3785

Like here I guess :)
https://github.com/Azure/azure-functions-core-tools/blob/6a070fb40308438c758ba8ab69399845bd698391/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L364

**Comment by michaelpeng36** [comment]
This issue has been resolved by PR #2938 and #2941. By default, the function key should not be exposed now when publishing. If this behavior is desired, then the switch `--show-keys` has been included.
