### ISSUE TITLE
Azure Functions preview 4 using dotnet 6 RC2 throws "Grace.Core: Error loading native library error" on Apple Silicon.

### ISSUE THREAD

**Issue by daigok** [Azure/azure-functions-core-tools#2817]
I'm developing in-process Azure Function app using following environment.
OS: macOS Monterey 12.0.1
Machine: MacBook Pro M1, 2020
dotnet: 6.0.100-rc2.21505.57
Azure Functions Tools: 4.0.3780

When I start a function `func start`. It started fine however once a trigger function is launched it throws the error below.
`
[2021-11-07T13:30:00.063Z] Grpc.Core: Error loading native library. Not found in any of the possible locations: /*/bin/output/bin/libgrpc_csharp_ext.x64.dylib,/*/bin/output/bin/runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib,/*/bin/output/bin/../../runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib.
`

The above message, I've replaced path locations and function names with "*". I also noticed on ActivityMonitor the func process is not running as an Apple process but is Intel process. This is the reason the process can't find a Grpc.Core library.

**Comment by RichMercer** [comment]
After spending days on this I ended up compiling my own `func` targeting `osx-arm64`. It's the only way I ever managed to get it working. Has anybody got it working on Apple Silicone?

**Comment by ejizba** [comment]
Consolidating M1 issues. Will use https://github.com/Azure/azure-functions-core-tools/issues/2834 for tracking in core tools
