### ISSUE TITLE
Azure Function not able to debug locally  due to System.ArgumentNullException' in System.IO.FileSystem.dll

### ISSUE THREAD

**Issue by pravanjan1992** [Azure/azure-functions-core-tools#2818]
Hi 

Azure Function not able to debug in local env due to System.ArgumentNullException' in System.IO.FileSystem.dll
I had enabled the exception setting for the same its showing Appsetting.cs  is missing.

Core tool: 3.30.0
VS-2019

Errors: 

<img width="886" alt="Capture" src="https://user-images.githubusercontent.com/93904317/140745743-a6c7533c-6714-45ab-a498-b1fe41979551.PNG">

**Comment by apawast** [comment]
@pravanjan1992 does this work if you run `func start` from the command line instead of debugging through VS?
