### ISSUE TITLE
Kafka Dotnet function template option is not available while creating from core tools

### ISSUE THREAD

**Issue by shrohilla** [Azure/azure-functions-core-tools#2819]
While creating a function from core tools, if we select the option of dotnet, in the triggering option the Kafka trigger option is absent.

While the template is available in function template 3.x branch -- https://github.com/Azure/azure-functions-templates/tree/v3.x/Functions.Templates/Templates

![dotnet-template](https://user-images.githubusercontent.com/80326489/140788926-01293129-8afb-4efe-9e44-8c3c30fee897.png)

PFA of the image 

cc @pragnagopa @TsuyoshiUshio @fabiocav @lpapudippu

**Comment by pragnagopa** [comment]
@TsuyoshiUshio  - Please confirm if the dotnet templates already include Kafka template.  If yes, this issue can be scoped to updating templates version referred in Core Tools

cc @soninaren

**Comment by TsuyoshiUshio** [comment]
Code Pointer for func new azure-functions-core-tools/CreateFunctionAction.cs at dev · Azure/azure-functions-core-tools (github.com)

In this case, current func command reference the old template. 

For dotnet, we can find the template version in here. 
[azure-functions-core-tools/Settings.cs at v3.x · Azure/azure-functions-core-tools (github.com)](https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/Actions/LocalActions/CreateFunctionAction.cs)
It looks 3.1.1648. 

We can update it with new version listed in here. 
[Releases · Azure/azure-functions-templates (github.com)](https://github.com/Azure/azure-functions-core-tools/blob/v3.x/build/Settings.cs#L23-L27)

Latest looks include Kafka
[Release 3.1.1809 · Azure/azure-functions-templates (github.com)](https://github.com/Azure/azure-functions-templates/releases/tag/3.1.1809)

Then we need to release new version of the func command.

**Comment by michaelpeng36** [comment]
Closing, as this is fixed by PR #2862
