### ISSUE TITLE
If we have white space in a folder path adding extension is not working

### ISSUE THREAD

**Issue by gled4er** [Azure/azure-functions-core-tools#282]
Hello,

I am trying to enable Azure Cosmos DB trigger for functions in cross platform tools. 

**I have node with version v8.7.0 and dotnet core with version 2.0.2**

When I am executing 

**func extensions install -p Microsoft.Azure.WebJobs.Extensions.CosmosDB -v 3.0.0-beta4** 

in folder located for example **"C:\Users\myuser\Documents\Projects\test folder"** I got the following error:

Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>
**Please specify one package reference to add.**

Arguments:
  <PROJECT>        The project file to operate on. If a file is not specified, the command will search the current directory for one.
  <PACKAGE_NAME>   The package reference to add.

Options:
  -h, --help                                Show help information.
  -v, --version <VERSION>                   Version for the package to be added.
  -f, --framework <FRAMEWORK>               Adds reference only when targeting a specific framework.
  -n, --no-restore                          Adds reference without performing restore preview and compatibility check.
  -s, --source <SOURCE>                     Specifies NuGet package sources to use during the restore.
  --package-directory <PACKAGE_DIRECTORY>   Restores the packages to the specified directory.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: folder\functions-extensions\extensions.csproj

For switch syntax, type "MSBuild /help"

But if I execute the same command:

**func extensions install -p Microsoft.Azure.WebJobs.Extensions.CosmosDB -v 3.0.0-beta4**  

in the following location - **C:\Users\myuser\Documents\Projects\testfolder** everything works find and I got the expected output:

  Writing C:\Users\myuser\AppData\Local\Temp\tmp549F.tmp
info : Adding PackageReference for package 'Microsoft.Azure.WebJobs.Extensions.CosmosDB' into project 'C:\Users\myuser\Documents\Projects\testfolder\functions-extensions\extensions.csproj'.
log  : Restoring packages for C:\Users\myuser\Documents\Projects\testfolder\functions-extensions\extensions.csproj...
info : Package 'Microsoft.Azure.WebJobs.Extensions.CosmosDB' is compatible with all the specified frameworks in project 'C:\Users\myuser\Documents\Projects\testfolder\functions-extensions\extensions.csproj'.
info : PackageReference for package 'Microsoft.Azure.WebJobs.Extensions.CosmosDB' version '3.0.0-beta4' added to file 'C:\Users\myuser\Documents\Projects\testfolder\functions-extensions\extensions.csproj'.

Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  extensions -> C:\Users\myuser\Documents\Projects\testfolder\bin\extensions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.47

Thank you!

**Comment by TsuyoshiUshio** [comment]
This line might be a problem.  https://github.com/Azure/azure-functions-cli/blob/30228f0a7aa61c10b8dcdb3cf6873efa265ec560/src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs#L55

The line could have a path with space from here.
https://github.com/Azure/azure-functions-cli/blob/30228f0a7aa61c10b8dcdb3cf6873efa265ec560/src/Azure.Functions.Cli/Helpers/ExtensionsHelper.cs#L14

**Comment by jdneo** [comment]
met the same problem here.

**Comment by nzthiago** [comment]
We just lost quite a few minutes on this too, it's still happening on the latest core tools update

**Comment by jeffhollan** [comment]
@soninaren @ahmelsayed with VS Code now installing extensions for JavaScript by default would be good if we can get this sorted out before the next core tools release.

**Comment by pitelm** [comment]
Any workaround for this till the core-tools update?

**Comment by ahmelsayed** [comment]
This was fixed in 18b74fad93445ccbf17e7d75c5ecd63b1661a219, and should be fixed in releases >= 2.0.2.
