### ISSUE TITLE
Question: How to contribute this project?

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-core-tools#283]
I found a possible solution of this repo. I wanted to create a pull request, however, I don't know how to build / test this code in my local machine. 

https://github.com/Azure/azure-functions-cli/issues/282

I try to build using Visual Studio, however, I've got a lot of errors. 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ARMClient' could not be found (are you missing a using directive or an assembly reference?)	Azure.Functions.Cli.Tests	C:\Users\tsushi\Source\Repos\azure-functions-cli\test\Azure.Functions.Cli.Tests\ActionsTests\ResolveActionTests.cs	6	Active
```

And warnings something like this.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Microsoft.AspNet.WebApi.Client 5.2.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.	Azure.Functions.Cli	C:\Users\tsushi\Source\Repos\azure-functions-cli\src\Azure.Functions.Cli\Azure.Functions.Cli.csproj	1	

```

How can I build this project and test it?  Do we need some prerequisite?

**Comment by SteveALee** [comment]
I see a `build,cmd` for windows build.

But yes there should ideally be a CONTRIBUTING file or notes in the README.

**Comment by brandonh-msft** [comment]
FWIW I was able to build locally & run unit tests, but first catch is you have to set a `GITHUB_TOKEN` **environment variable** to a PAT for a GitHub account that can see this repo. Then the build will go through. Worth noting it adds another env variable `FUNC_PATH` which points to the `func.exe` built in the win-x86 output directory. This is used by the `init` tests in the test harness.

**Comment by ahmedelnably** [comment]
Closing this, will be tracked in #217
