### ISSUE TITLE
When will V4 come out of preview?

### ISSUE THREAD

**Issue by jesperkristensen** [Azure/azure-functions-core-tools#2837]
According to https://github.com/Azure/azure-functions-core-tools#installing Azure Functions Core Tools v4 is still in preview.

Given that Azure Functions 4.0 has been generally available in Azure for some time now (https://techcommunity.microsoft.com/t5/apps-on-azure/azure-functions-4-0-and-net-6-support-are-now-generally/ba-p/2933245), will the Core Tools v4 be released soon?

**Comment by anthonychu** [comment]
It’s not in preview anymore. We missed updating the readme when GA was announced. We’ll update that. Thanks for letting us know.
