### ISSUE TITLE
Could not load type 'System.Diagnostics.DebuggerStepThroughAttribute' 

### ISSUE THREAD

**Issue by kamlesh-nb** [Azure/azure-functions-core-tools#2838]
I am getting below error when trying to run the Azure Function with Event Hub Trigger locally in VS Code. I a using Azure Function v4 and .NET 6.0.  and VS Code Azure Function Extension v1.6.0

[2021-11-25T12:03:26.962Z] A host error has occurred during startup operation 'ba320ce1-bd77-4a1b-b583-fa7beae3196b'.

[2021-11-25T12:03:26.965Z] System.Private.CoreLib: Could not load type 'System.Diagnostics.DebuggerStepThroughAttribute' from assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Value cannot be null. (Parameter 'provider')

**Comment by michaelpeng36** [comment]
@kamlesh-nb Is this the full error message you are seeing? If not, could you include it? @fabiocav do you have an idea of what may be causing this?

**Comment by kamlesh-nb** [comment]
@michaelpeng36 Yes this is the full message that I see.

**Comment by kamlesh-nb** [comment]
@michaelpeng36 Can I expect some answer?

**Comment by dushrba** [comment]
@kamlesh-nb  Try installing Command line tools for Azure Functions
`npm i -g azure-functions-core-tools@4 --unsafe-perm true`

I had the same problem with VS Code , .Net6 and Azure Functions Extensions V1.6.0
[https://github.com/Azure/azure-functions-core-tools](url)

**Comment by kamlesh-nb** [comment]
@dushrba Thanks, I will give it a try.

**Comment by apawast** [comment]
@kamlesh-nb have you tried the above solution?
