### ISSUE TITLE
Building python func app doesnt work if requirements packages are local

### ISSUE THREAD

**Issue by leryss** [Azure/azure-functions-core-tools#2842]
I have the following pip requirements.txt

```
azure-functions
azure-servicebus
file:../my-package
```

Running the function from within vscode works normally but when I try to publish it with:
`func azure functionapp publish my-func-app --build local --build-native-deps`

I get:
```
Getting site publishing info...
Recommend using '--build remote' to resolve project dependencies remotely on Azure
Deleting the old .python_packages directory
Running 'docker pull mcr.microsoft.com/azure-functions/python:3.0.15066-python3.9-buildenv'....done
Running 'docker exec -t e83d43 chmod +x /python_docker_build.sh'..done
Running 'docker exec -t e83d43 /python_docker_build.sh'....done
Running 'docker kill e83d43'..done
Error running docker exec -t e83d4363eca342a4cbde88250324a3621c2d2c56155a9edefdbc00f8d2e544c7 /python_docker_build.sh.
output: Processing /my-package
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/my-package'
```

Remote build yields something similar, same for publishing from vscode directly

**Comment by michaelpeng36** [comment]
@leryss would it be possible for you to move `my-package` into the function app folder?

**Comment by leryss** [comment]
> @leryss would it be possible for you to move `my-package` into the function app folder?

Hi, sorry for the late answer, I fixed it by uploading the package to a private package manager

**Comment by jaymegordo** [comment]
I have this same issue. I'm developing an azure functions app which works fine, but then I split off some modules into a generic "utils" type package, which is now in a separate directory. Would be helpful to know how to include this with the docker build.

**Comment by apawast** [comment]
@leryss I am closing this issue as resolved since you have a workaround. @jaymegordo if you are still having this issue, could you please open a new issue and provide more details?
