### ISSUE TITLE
Error calling sync triggers (BadRequest).

### ISSUE THREAD

**Issue by orty** [Azure/azure-functions-core-tools#2843]
Hi,

When moving from `.Net Core 3.1/Azure Functions runtime v3` to `.Net 6/Azure Functions runtime v4`, we started encountering the following error when publishing our functions to Azure :
`Error calling sync triggers (BadRequest). Request ID = '80a42858-06a5-4a5e-9ea3-a477d4178cb8'.`

The function app itselfs shows the list of functions (in the portal and by JSON request), but the following alert shows up on the top of the functions list in the Azure portal :
`Azure Functions runtime is unreachable`

The endpoints seem to be correctly responding but there stil is some issues on the Host side, and we are not able to investigate any further on the root cause. 

May you tell us, using the provided `Request ID`, what can be the cause of such a behavior ? I stay available to give you any further information you might need to investigate.

Best regards.

**Comment by michaelpeng36** [comment]
@orty does this happen consistently or intermittently? Because this may be the result of multiple issues, would you be able to open a support ticket for this to receive the help you need?
