### ISSUE TITLE
Specify custom python binary path for "func start" terminal command?

### ISSUE THREAD

**Issue by aescolastico** [Azure/azure-functions-core-tools#2844]
Currently I have to set an alias for "python" if I want core tools to use a specific version. Is there a parameter I can feed the command or some value in the settings file I can use to achieve this? The reason being that I need to use a different version of python for az func development then I do for every day use. Modifying my alias' is quite inconvenient.

Thanks in advance and apologies if this has been asked before. Ive been searching for hours.

**Comment by aescolastico** [comment]
I tried setting the env variable based on comments in this file ("languageWorkers:python:defaultExecutablePath"):

https://github.com/Azure/azure-functions-core-tools/blob/6a070fb40308438c758ba8ab69399845bd698391/src/Azure.Functions.Cli/Helpers/PythonHelpers.cs#L136

```
  // If users are overriding this value, we will use the path it's pointing to.
  // This also allows for an escape path for complicated envrionments.
  string pythonDefaultExecutablePath = Environment.GetEnvironmentVariable(_pythonDefaultExecutableVar);
  if (!string.IsNullOrEmpty(pythonDefaultExecutablePath))
  {
      return await GetVersion(pythonDefaultExecutablePath);
  }
```

**Comment by michaelpeng36** [comment]
@aescolastico, what version of Python are you trying to use? Typically, we encourage users to use a virtual environment.

**Comment by aescolastico** [comment]
I have an rosetta x86_64 emulated install of python3 located in '/usr/local/bin/python3'
and an arm version installed in '/opt/homebrew/opt/python@3.9/libexec/bin/python'

Im running 3.9 for both. I need to use the emulated version in order to run func tools on my M1 mac. Arm python is not currently supported by this application.  

When func tools "finds" the python located at '/usr/local/bin/python3' (x86 emulated) it works without issue. But to do this I need to either uninstall the arm python, or remove all references of "python" or "python3" that point to that arm version. 

How would I use a virtual environment? I use func tools in the terminal and not with vscode if that helps.

**Comment by anthonychu** [comment]
@aescolastico I don't have an M1 Mac yet to test this but give this a try:

```bash
# create the virtual environment
/usr/local/bin/python3 -m venv .venv

# activate it
source .venv/bin/activate

# this should point to the python binary in your virtual environment
which python

# install dependencies in the virtual env
python -m pip install -r requirements.txt
```

Now when you use `func`, it should use the right binary.

M1 support is tracked here #2834

**Comment by aescolastico** [comment]
So this:
```
# install dependencies in the virtual env
python -m pip install -r requirements.txt
```
actually still pointed to my opt python "site-packages" directory (likely due to some hardcoded alias' in my bash_profile). I think that's what I was running into when I tried to use venvs the other day. Your use of which gave me that hint. 

when I manually specified the path to the binary in my venv, it worked. 
```
.venv/bin/python -m pip install -r requirements.txt
```
<img width="896" alt="image" src="https://user-images.githubusercontent.com/30540257/144154127-cc24199b-a1fc-4b14-be7e-8dc2f75fb643.png">

Thanks for your help @anthonychu 

For anyone else on M1 hardware. I had to do this in the Rosetta copy of my terminal editor and also had to install an intel emulated version of home-brew to get az func working.
