### ISSUE TITLE
v1.x not building?

### ISSUE THREAD

**Issue by Samx2015** [Azure/azure-functions-core-tools#285]
I had to use v1.x, but v1.x is not building, either in VS or by build.cmd.

With v2.0 dotnet core, app runs into an issue with System.Configuration.ConfigurationManager not being able to load,

 Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

same was reported by others here: 

https://github.com/pusher-community/pusher-websocket-dotnet/issues/34

**Comment by espray** [comment]
+1

**Comment by ahmelsayed** [comment]
That's odd, it has been building on the CI, I just never added a badge for it. https://ci.appveyor.com/project/appsvc/azure-functions-cli/history 

What errors are you getting on the v1.x branch? that should be the stable branch.

**Comment by ahmelsayed** [comment]
CI has been passing, so closing this old issue.
