### ISSUE TITLE
Unsupported Zip format or corrupted zip file

### ISSUE THREAD

**Issue by reflash** [Azure/azure-functions-core-tools#2856]
Hi!

I was trying to publish azure function app via cli to Azure, unfortunately it's not working as I expect

```
Azure Functions Core Tools: 3.0.3785-1
Host: Windows
Runtime: Node 12
FUNCTIONS_EXTENSION_VERSION: ~3
FUNCTIONS_WORKER_RUNTIME: node
WEBSITE_NODE_DEFAULT_VERSION: ~12
WEBSITE_RUN_FROM_PACKAGE: 1
```

Here's the output I'm gettings:
```
Getting site publishing info...
Creating archive for current directory...
Uploading 334.73 MB []Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Functions in ***-weur-prod-***:
```

In console I can find "FAILED TO INITIALIZE RUN FROM PACKAGE.txt" which contains:
Run From Package Initialization failed. Unsupported Zip format or corrupted zip file.
This could be a leftover from previous runs as I was trying to use core tools v4

When I got and check /home/data/SitePackages I can find my zip file and packagename.txt containning the file name
Checking the zip file with `unzip -t <filename>` gives the following
```
    ...
    testing: webhook/function.json    OK
No errors detected in compressed data of 20211203064756.zip.
```

Is there anything else I could check?

**Comment by michaelpeng36** [comment]
@reflash , could you open a support ticket via the Azure portal? This issue may require taking a look at your code.

**Comment by reflash** [comment]
> @reflash , could you open a support ticket via the Azure portal? This issue may require taking a look at your code.

Thank you! I have figured it out after some experiments 😄
It's a bit weird, but once I dropped the zip file size from 300mb to ~100mb, it suddenly started working normally
