### ISSUE TITLE
Homebrew install on Linux/WSL2 installs incompatible func binary

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-core-tools#2865]
This is running on WSL2 with Ubuntu. I know we have separate instructions for Ubuntu, but I prefer to use homebrew whenever possible as my package manager.

### Repro steps
1. brew tap azure/functions
2. brew install azure-functions-core-tools@4
3. func version

The result is the following error message:

> -bash: /home/linuxbrew/.linuxbrew/bin/func: cannot execute binary file: Exec format error

**Comment by ejizba** [comment]
Closing in favor of https://github.com/Azure/homebrew-functions/issues/95
