### ISSUE TITLE
choco install azure-functions-core-tools-4 not working (looks like it is not available in the feed)

### ISSUE THREAD

**Issue by kelps** [Azure/azure-functions-core-tools#2868]
I just tried to install azure-function-core-tool-4 using chocolatey, but it didn't work, saying the package was not found. I searched the packages there and in fact I couln't find v4.

the command I used was
```
choco install azure-functions-core-tools-4
```

I got that command from this readme file: https://github.com/Azure/azure-functions-core-tools/blob/dev/README.md

Either the file should be updated to represent what is actually available or the package should be published to Chocolatey. 

After failing from chocolatey, I tried installing from the msi and now I can't run ```func azure functionapp publish ....``` on my app, as the console says "func is not a recognized command...". I did remove the "azure-function-core-tool-3" before trying 4 installing .

**Comment by TroyWitthoeft** [comment]
@kelps Yeap.  I don't think chocolatey has an official v4 package right now? 

https://community.chocolatey.org/packages/azure-functions-core-tools-4
![image](https://user-images.githubusercontent.com/1102958/147956775-77c65108-6651-467d-8329-7534119f3649.png)

If you removed azure-function-core-tool-3 and the install of v4 failed, then you'll probably have to reinstall v3.  
FWIW, the npm way of installing v4 did work from me.  Just be sure to make sure that _wherever_ func.exe is installed, the install folder is part of your `%PATH%` environment variable.  Dropping into a shell and typing `where func` can help show you the folders where Windows things func.exe may be installed.  It will use the first one in the list.
