### ISSUE TITLE
Function startup fails when using System.Memory.Data 6.0.0

### ISSUE THREAD

**Issue by EvanMulawski** [Azure/azure-functions-core-tools#2872]
When attempting to start a v4 function app that uses **System.Memory.Data 6.0.0**, startup fails due to the following error:

```
[2021-12-14T19:33:56.629Z] A host error has occurred during startup operation 'd5f7db36-8721-4169-9c45-6fc51fc33530'.
[2021-12-14T19:33:56.638Z] App: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')
```

The version of **System.Memory.Data** delivered in Core Tools 4.10.1 is `1.0.2`. Replacing this DLL with a `6.0.0` version in the Core Tools CLI directory resolves this startup error.

(Replaced `%USERPROFILE%\AppData\Local\AzureFunctionsTools\Releases\4.10.1\cli_x64\System.Memory.Data.dll`)

**Comment by EvanMulawski** [comment]
This is also preventing startup when deployed to Azure.

![image](https://user-images.githubusercontent.com/1044791/146629247-86328375-8ae4-4821-8cea-a2ebda014df5.png)

**Comment by EvanMulawski** [comment]
Workaround: adding `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` to the project file.

**Comment by bartsokol** [comment]
Is there any update on this? We are experiencing the same issue when trying to make a call to blob storage on functions 4 / .NET 6. The workaround with `_FunctionsSkipCleanOutput` works, but it would be great to not be forced to use some workaround flags.

**Comment by bhehe** [comment]
Just ran into this myself; Is there a more broadly applicable fix to issues of this nature? 
Seems like it would be a problem any time there's a version mismatch regardless of which dependency it is.

**Comment by LeszekKalibrate** [comment]
Is this fixed yet?

**Comment by ravindrank** [comment]
I ran into this issue as well after upgrading some of the packages to newest. Workaround seems to work for now..

**Comment by Sergey-Nosov-CloudFit** [comment]
Also run into this issue. The workaround worked. How dangerous is the workaround?

**Comment by bishwaranjans** [comment]
I am facing the same issue even after adding  <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>

**Comment by Sergey-Nosov-CloudFit** [comment]
> I am facing the same issue even after adding <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>

Try making sure that you are not referencing the _System.Memory.Data 6.0.0_ package directly in any of the projects. I believe this version has been marked as vulnerable, so perhaps something is blocking access to it.

**Comment by Spartan-Hex-Shadow** [comment]
I can verify that the FunctionsSkipCleanOutput fix works. Make sure to add it in the PropertyGroup
```
 <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
```

**Comment by mattixittam** [comment]
I'm running into this problem running a NodeJS v4 function on the command line using the Core Tools cli (I have core tools 4.0.6280 and function runtime 4.834.3.22875).

```Azure.Core: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.```

The trigger seems to be the blobStorage trigger I'm using as an http/servicebus trigger works fine.

Is there a workaround in this situation?

**Comment by LearnVinod** [comment]
Is there any solution for above issue. I am also facing same issue with System.Memory.Data 6.0.0.0 which not directly referenced but from Azure.Storage.Blobs
None of above workaround works for me.

**Comment by mattixittam** [comment]
I have worked around the issue by introducing a Service Bus Queue and having our API put a message on there after it has uploaded the blob. The Function App then responds to this message instead.

This overcomplicates what should be a very basic scenario, though. I can't believe that this bug has existed for 2,5 years (with the fix seemingly being to just ship a different DLL, but I admittedly do not have the full picture) and nothing has been done.

**Comment by LearnVinod** [comment]
Hi @mattixittam,
Can you elaborate the work around with steps which you have used, As I am stuck for last 2 weeks due to this issue

**Comment by mattixittam** [comment]
Sure:

I have an API backend which uploads a blob into the storage container.

For the workaround, this API now also sends a message to a (new) Service Bus message queue, the message body containing the blob url. My original function app now has a service bus trigger instead of a blob trigger, reads the url from the message and retrieves the blob (using node-fetch in my case). From there the process works as if you had a working blob trigger.

**Comment by VelvetAndrea** [comment]
I also have this issue and need a fix asap.  

We are using an Azure Function App: using net8.0 In-Proc.  So far the workaround is only needed for 1 of our converted apps.  Others work fine without the workaround.  I haven't found a discernable pattern different between the 2 that are running fine and this problem app.  I'll keep my eyes open.

**Comment by Arash-Sabet** [comment]
Who is the program owner or project manager to have him/her escalate the priority of this issue. The workaround does not work at all.
@fabiocav : Would you please have someone suggest or come up with a solution for this problem?

**Comment by mattixittam** [comment]
I am about to put pressure from a different direction through a Support Request in the portal. Maybe that will help get things moving.

**Comment by Arash-Sabet** [comment]
@mattixittam Please share the URL so I can submit a similar request. This is not acceptable! I am wondering now many people have been stopped progressing by this issue!

**Comment by surgupta-msft** [comment]
This is a duplicate of issue - https://github.com/Azure/azure-functions-host/issues/10575. We can use that issue to capture discussion and progress.
