### ISSUE TITLE
Incorrect function.json generated for eventhubtrigger core runtime

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-core-tools#290]
**Microsoft.NET.Sdk.Functions version:** 1.0.6
**Eventhub nuget package:** Microsoft.Azure.WebJobs.Extensions.EventHubs

Repro steps
1. Create a function app
2. Use the following code to create a function

```C#
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Azure.WebJobs.ServiceBus;

namespace FunctionApp15
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([EventHubTrigger(eventHubName: "<EventhubName>", Connection = "conn")]string myEventHubMessage, TraceWriter log)
        {
            log.Info($"C# Event Hub trigger function processed a message: {myEventHubMessage}");
        }
    }
}
```

Here is the generated function.json
```
"bindings": [
    {
      "type": "eventHubTrigger",
      "path": "<EventhubName>",   // path was renamed to eventHubName for core runtime
      "connection": "conn",
      "name": "myEventHubMessage"
    }
  ]
```

**Comment by zhangr2** [comment]
I am curious about how do you create eventhub trigger function from CLI. Could you help me because I find there only 4 templates without EventhubTrigger.

**Comment by MikeWasson** [comment]
I have the same issue

Microsoft.Azure.WebJobs.ServiceBus 2.1.0
Microsoft.NET.Sdk.Functions 1.0.10
TargetFramework = net461

**Comment by soninaren** [comment]
This is fixed.
