### ISSUE TITLE
func run executes all functions in pre-compiled function

### ISSUE THREAD

**Issue by jaredcnance** [Azure/azure-functions-core-tools#291]
## Background
I am trying to execute each function in isolation for acceptance testing. I briefly describe the methodology here: https://github.com/Azure/azure-webjobs-sdk/issues/1390

## The Problem

When using a pre-compiled function (a .Net assembly that contains multiple functions), using `func run .` executes all functions, not just the function in the current directory. Consider the following directory structure:

```
Foo/
├── Bar/
│   ├── Bar.csproj
│   ├── Function1
│   │   ├── Function1.cs
│   │   └── function.json
│   └── Function2
│       ├── Function2.cs
│       └── function.json
└── Foo.sln
```

If I:
```
cd ./Foo/Bar/Function2
func run .
```

It will execute both Function1 and Function2.

**Comment by ahmelsayed** [comment]
to run individual functions you can do `func start --functions "{comma seperated list of functions to load}"`
