### ISSUE TITLE
func init creates the project structure and package.json contains @azure/functions 1.0.1-beta1

### ISSUE THREAD

**Issue by codestellar** [Azure/azure-functions-core-tools#2926]
I am using azure-function-core-tools@4, which I have installed today itself.
![image](https://user-images.githubusercontent.com/17561784/151003146-d0f637c7-07cd-4749-a7fe-2850ba7dd84f.png)

Steps to reproduce:
1. func init
2. choose node
3. choose typescript
4. check package.json

**Expected:** The @azure/functions should be using the latest stable version

**Actual** The @azure/functions version being used is 1.0.1-beta1
![image](https://user-images.githubusercontent.com/17561784/151003649-ec51d23b-c3d6-45fb-b933-efb2027c724a.png)

**Comment by ejizba** [comment]
Hi, this was fixed in https://github.com/Azure/azure-functions-core-tools/pull/2852 and will ship with the next version of core tools
