### ISSUE TITLE
PowerShell Durable Functions fail running locally - missing command definition

### ISSUE THREAD

**Issue by Nibushi** [Azure/azure-functions-core-tools#2937]
I've be using PowerShell Azure Durable Functions for a while now and never had a problem testing locally. However, since today I can no longer run the Azure Durable Functions locally and call them from Postman. When I try to call the functions I get a number of errors stating that the Azure Durable Function cmdlets such as Start-DurableOrchestration, New-DurableOrchestrationCheckStatusResponse, etc are not defined. This was working previously on this machine without any issues.

_[2022-02-01T14:05:55.680Z] Executing 'Functions.HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=fa0bfb1b-0be4-42c9-b735-1b9b6b33968f)
[2022-02-01T14:05:56.374Z] The Function app may be missing a module containing the 'Start-DurableOrchestration' command definition. If this command belongs to a module available on the PowerShell Gallery, add a reference to this module to requirements.psd1. Make sure this module is compatible with PowerShell 7. For more details, see https://aka.ms/functions-powershell-managed-dependency.
[2022-02-01T14:05:57.001Z] ERROR: The term 'Start-DurableOrchestration' is not recognized as the name of a cmdlet, function, script file, or operable program._

Even trying to run the example here results in the same issue:
https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-powershell-vscode

Azure Functions Core Tools installed: 4.0.3971
Azure Storage Emulator 5.10.0.0
Azure Functions Ext: v1.6.0
VS Code: v1.63.2

Expected behavior
Send request from Postman and receive statusQueryUrl and finally the result

Actual behavior
Errors in VSCode stating that a module might be missing and the Azure Durable Functions cmdlets are not defined.

I've tried this on three different machines were I was developing and testing Azure Durable Functions previously without any issues and both are producing the same behaviour.

I've tried installing and re-installing the core tools via a download and winget. I can see the module listed here with the commands but it is not being loaded when debugging in VS Code. 

This was working last week without any issues and I am not sure what has changed since then.

**Comment by Nibushi** [comment]
[AzFuncTroubleshooting.zip](https://github.com/Azure/azure-functions-core-tools/files/7981165/AzFuncTroubleshooting.zip)

I have tried again creating the project which can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-powershell-vscode

I've tried using a local storage emulator and an Azure based storage account. I've also included a txt file in the zip which contains the full error message when calling the starter function from Postman...

**Comment by davidmrdavid** [comment]
Hi @Nibushi,

I took the steps in the quickstart guide again and they worked for me, but I had some issues getting your `.zip`'ed project to run; they were not the same issues as you reported, just something strange about the "AuthorizationManager check" failing. I need to dig deeper into that.

In the meantime, something that stood out to me is that you report having version 4.x of coretools, but your attached `error.txt` file shows Core Tools Version `3.0.3233`. Could it be that you have conflicting Core Tools installations?

As a sanity check, what output do you get when you run `func --v` on your CLI? Also, can you try re-generating your `error.txt` trace? Does that still constain `Core Tools Version 3.x`? 
Thanks!

**Comment by Nibushi** [comment]
Hi @davidmrdavid ,

I managed to get some time to look into the issue this morning. I went back and basically tried to unpick the issues. The short story is I had to install azure-functions-core-tools-3 v3.0.3785 as v3.0.3233 psm1 file did not contain the following aliases for these renamed cmdlets. I only noticed the name discrepancy when I managed to get an older project to run:

Set-Alias -Name Wait-ActivityFunction -Value Wait-DurableTask
Set-Alias -Name Invoke-ActivityFunction -Value Invoke-DurableActivity
Set-Alias -Name New-OrchestrationCheckStatusResponse -Value New-DurableOrchestrationCheckStatusResponse
Set-Alias -Name Start-NewOrchestration -Value Start-DurableOrchestration

Long Version
----------------
When you mentioned about conflicting versions I went and checked which versions of the Azure Functions core tools I had installed. I forgot I had installed the azure-functions-core-tools-3 with Chocolately and then when the error started happening I tried to install azure-functions-core-tools-4 using an msi and then winget. So I removed azure-functions-core-tools-4. The issue still persisted.....but a lesson on using too many package managers :-)

I then started double checking some old projects as those ran without any issues. Started comparing files and then I tried changing the extensionBundle in one of the newer projects to "version": "[1.*, 2.0.0)". This gave a different error which outlined that the DurableClient type defined in the json for the Starter function wasn't valid in that extensionBundle. This then lead me to check the command names again and that's when I spotted the naming difference.

I upgraded to the latest version of azure-functions-core-tools-3 and this contained the aliases required to allow the functions to run locally.

I am not sure where the templates that VS Code uses to create the Durable Functions comes from, whether it is the Azure Core Tools or the Azure Functions extension. I'll need to go back and look at the other two machines where I am seeing the same issue but it seems like the issue was having version 1.6.0 of the Azure Functions extension and v3.0.3233 of the Azure Core Tools.

Thanks for looking into this with me I appreciate your help.

**Comment by davidmrdavid** [comment]
Thanks @Nibushi, I'm  glad to hear the issue was resolved.
And no worries, while developing for Azure Functions, I also have to use multiple package managers and things do get messed up on my local development enviroment from time to time :)

Please reach out again if you need any further help. I'll be closing this issue in the meantime.

@michaelpeng36: can you please mark this issue as resolved? Thanks!
