### ISSUE TITLE
Cannot use custom TimerSchedules in Release builds

### ISSUE THREAD

**Issue by Henningsson** [Azure/azure-functions-core-tools#294]
I'm using a custom TimerSchedule on a TimerTrigger for my Azure Function, which works fine when building and testing with Debug configuration.

When switching to Release configuration however, MSBuild fails to generate function metadata with the following exception:
`
System.NotImplementedException: Property 'ScheduleType' on attribute 'TimerTriggerAttribute' is not supported in Azure Functions.`

I am using Microsoft.NET.Sdk.Functions Version:1.0.6

**Comment by ahmedelnably** [comment]
Closing as stale
