### ISSUE TITLE
Update key generation logic to create "identifiable" secrets

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-core-tools#2944]
We need to apply the same key generation changes done in [this PR](https://github.com/Azure/azure-functions-host/pull/8071) to the key generation we have in this repo [here](https://github.com/Azure/azure-functions-core-tools/blob/6a070fb40308438c758ba8ab69399845bd698391/src/Azure.Functions.Cli/Kubernetes/FuncKeys/FuncAppKeysHelper.cs#L97).

The Functions Host exposes a [SecretGenerator](https://github.com/Azure/azure-functions-host/blob/60a669dc7a04ec360318151b6db14b4db496badd/src/WebJobs.Script.WebHost/Security/SecretGenerator.cs#L11) helper that tools can use to generate secrets in the same way that the host itself does. For both v3 and v4 tools, we'll want to update the Microsoft.Azure.WebJobs.Script.WebHost package to pull in the helper code:

- For v4, upgrade to **4.3.0-17820** or later
- For v3, upgrade to **3.6.0-17859** or later

**Comment by mathewc** [comment]
For v4 tools, package Microsoft.Azure.WebJobs.Script.WebHost 4.3.0-17820 has the required helper. Still need to add for v3 as well.

**Comment by michaelpeng36** [comment]
Resolved by #3040 and #3041
