### ISSUE TITLE
High CPU consumption when running azure-functions-cli

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/azure-functions-core-tools#295]
I have a problem when running azure-functions-cli 1.0.4 from a cmd on Windows 10. 4 of my 5 function apps takes up the entire CPU (probably 4 since I have 4 cores).

<img width="499" alt="cpu" src="https://user-images.githubusercontent.com/563206/32103724-f055fa12-bb21-11e7-9228-00f1a9051ed8.png">

What could be the issue here?

**Comment by aquiladev** [comment]
I have the same issue!
When I use: ```npm install -g azure-functions-cli``` process consumes ~0.5% CPU
```
Version:
Azure Functions Cli (1.0.0-beta.94)
Function Runtime Version: 1.0.10826.0
```

but in case ```npm install -g azure-functions-core-tools``` process consumes ~10% CPU

Yea, I'm running the same function

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
