### ISSUE TITLE
Add support for updating APIM policies using the AZ Cli

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-core-tools#2964]
Please add support to add/update policies in APIM at any level, using the az CLI. 
It would be great to be part of the az apim commands.
https://docs.microsoft.com/en-us/cli/azure/apim?view=azure-cli-latest

**Comment by michaelpeng36** [comment]
@sjuarezgx Do you mean the Az CLI or the `func` command for Core Tools? Could https://github.com/Azure/azure-cli be the repository you're looking for?

**Comment by sjuarezgx** [comment]
Yes, thanks a lot.
