### ISSUE TITLE
Update install instructions in portal to v4

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-core-tools#2968]
![70DAE031-09FF-47C3-9397-3CC132CEDA56](https://user-images.githubusercontent.com/3982077/155824216-48a31657-ce7a-4789-b898-fb5a3c311301.jpeg)

Repo: https://github.com/Azure/azure-functions-ux

**Comment by michaelpeng36** [comment]
@anthonychu Thanks for raising this. The issue should be resolved by [this PR](https://github.com/Azure/azure-functions-ux/pull/6539).
