### ISSUE TITLE
Python 3.6.x to 3.9.x is required for this operation. Please install Python 3.6, 3.7, 3.8, or 3.9 and use a virtual environment to switch to Python 3.6, 3.7, 3.8, or 3.9.

### ISSUE THREAD

**Issue by woeterman94** [Azure/azure-functions-core-tools#2979]
Please support versions higher then 3.9. Like python 3.10.2

**Comment by ejizba** [comment]
This is better tracked in the Python worker. See https://github.com/Azure/azure-functions-python-worker/issues/899

Looks like they've already done some work to support 3.10, just may not have released it yet
