### ISSUE TITLE
func start just hangs

### ISSUE THREAD

**Issue by macrozone** [Azure/azure-functions-core-tools#2981]
system: macOS 

`func start` sometimes stop working and only a full system restart seems to solve it.

calling `func start --verbose` just logs this and than hangs:

```
$ func start --verbose

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       4.0.3
```

I just updated to version 4 because of this problem (from some version 2), but it did not solve the problem.

**Comment by macrozone** [comment]
eventually after tons of retries, killing of processes, and letting just running for some 10min, it suddenly run and tried to re-run functions that i triggered manually for testing. It seems to me that some service hanged. Problem is, its not obvious what that that service is, where it is logging and how to restart it in case of a problem like this.

**Comment by michaelpeng36** [comment]
@macrozone Is 4.0.3 the version of Core Tools that it displays when running the `func --version` command? As far as I know, `4.0.3` does not seem to be a released version of Core Tools V4. Also do the functions you have included in your app require storage? If so, you may need to run Azurite in a separate process before `func start` works properly.
