### ISSUE TITLE
KeyVaultReferencesManager throws an error when provided a null config item

### ISSUE THREAD

**Issue by eejaysbaw** [Azure/azure-functions-core-tools#2989]
When KeyVaultReferencesManager attempts to match config items with the Key Vault Reference format it can result in a cryptic error being thrown
`Key Vault Reference format invalid:`

The following is an example from a newly created empty function app 

local.settings.json
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "test": null
  }
}
```
On Debug
```
Azure Functions Core Tools
Core Tools Version:       3.0.4378 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.4.2.0

[2022-03-17T01:43:06.010Z] Found C:\***\NullValueFunction\NullValueFunction.csproj. Using for user secrets file configuration.
Key Vault Reference format invalid:
Press any key to continue....
```

**Comment by eejaysbaw** [comment]
this was introduced with #2806

**Comment by ErosZZH** [comment]
Is there any workaround to get rid of this problem?

**Comment by jenyangk** [comment]
Can confirm that this is happening for me too. Also running on the same Core Tools and Function Runtime version.

Thanks @xagon for that quick fix.

**Comment by ejizba** [comment]
Thanks for the report folks, we'll get this addressed as soon as we can. I can repro the error behavior for both `null` and a valid keyvault string - I tested with the example [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#reference-syntax)
> @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/)

One question for @j0hnth0m - when you say "yes they were working before", I assume you just mean they didn't _block_ `func start`, right? AFAIK, core tools wouldn't actually _use_ keyvault references in the previous behavior

**Comment by j0hnth0m** [comment]
Yes, that's right, it wouldn't block.  I have a separate component that will resolve the keyvault reference later on.

**Comment by j03INTHECLOUD** [comment]
I do a similar thing and ya this has totally broken our code. It does work if you have the guid after the secret name, but no one wants to have keep track of the secret guid version, please roll this change back.......

**Comment by j03INTHECLOUD** [comment]
In the meantime is there an easy way to rollback to a version of the function core tools that does not have this issue?

**Comment by Going-Gone** [comment]
I log on today, and can't even run my function app locally because of this. On the first run, it wanted to download a new cli version, and ever since then i have this issue.

**Comment by aegpoadan** [comment]
Current workarounds would be:

Do not put a null value for an appsetting and/or include the version specifier for a KeyVault reference a la
"@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/versionIdentifier)"
or use the alternate key vault reference syntax:
"@Microsoft.KeyVault(VaultName=myvault;SecretName=mysecret)"

**Comment by aegpoadan** [comment]
If you are not using key vault references anywhere, then I suspect there's a null value in your appsettings. This PR: https://github.com/Azure/azure-functions-core-tools/pull/2991 should fix the issue

**Comment by Going-Gone** [comment]
> Current workarounds would be:
> 
> Do not put a null value for an appsetting and/or include the version specifier for a KeyVault reference a la "@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/versionIdentifier)" or use the alternate key vault reference syntax: "@Microsoft.KeyVault(VaultName=myvault;SecretName=mysecret)"

my local.settings.json file has no null values though, so would it be that i'm missing a setting somewhere that was previously needed?

**Comment by j03INTHECLOUD** [comment]
Looks like the [#2991](https://github.com/Azure/azure-functions-core-tools/pull/2991) build is failing

**Comment by Ovis** [comment]
In my environment, the same phenomenon occurred when the contents of ConnectionStrings are nested.

e.g.)
```json
  "ConnectionStrings": {
    "SqlDatabase": {
      "DatabaseConnectionString": "ConnectionString"
    }
  },
```

**Comment by Going-Gone** [comment]
> In my environment, the same phenomenon occurred when the contents of ConnectionStrings are nested.
> 
> e.g.)
> 
> ```json
>   "ConnectionStrings": {
>     "SqlDatabase": {
>       "DatabaseConnectionString": "ConnectionString"
>     }
>   },
> ```
> 
> In this case,I confirmed the operation by rewriting as follows:
> 
> ```json
>   "ConnectionStrings": {
>     "SqlDatabase:DatabaseConnectionString": "ConnectionString"
>   },
> ```

This was the fix for mine.

**Comment by ejizba** [comment]
Hi folks, we rolled back the change on this. If you're using a tool like Visual Studio, it should automatically change you back to the old version of core tools within the next few hours. I don't know the internals of VS, but my guess is you may need to restart VS to make this happen

**Comment by j0hnth0m** [comment]
No long having an issue with v3 however v4 is still experiencing the issue...

Azure Functions Core Tools
Core Tools Version:       **4.0.4385 Commit hash: N/A  (64-bit)**
Function Runtime Version: 4.1.3.17473

[2022-03-18T19:59:27.154Z] Found C:\work\sig\Azure\functionsapps\fa-config-test\xxx\xxx.ConfigTest.csproj. Using for user secrets file configuration.
**Key Vault Reference format invalid:** @Microsoft.KeyVault(SecretUri=https://***)

**Comment by j0hnth0m** [comment]
Still experiencing the issue.  What is the rolled back version?

Azure Functions Core Tools
Core Tools Version:       3.0.4378 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.4.2.0

[2022-03-21T15:59:23.973Z] Found ... Using for user secrets file configuration.
**Key Vault Reference format invalid: @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret)**
