### ISSUE TITLE
Issue Installing Bindings (aka the "Object reference not set to an instance of an object" issue)

### ISSUE THREAD

**Issue by martinpeck** [Azure/azure-functions-core-tools#299]
As mentioned here: https://github.com/Azure/azure-webjobs-sdk/issues/1404

Is the referenced issue (above) a deficiency in the current dotnet core/2.0 version of the functions cli, or are there some docs/instructions missing?

It feels like one of the following is missing:

1. functionality in the functions cli to make this work
2. docs/notes that explain how this works/is set up
3. docs/notes that explain that this isn't currently possible (and prevents people from going down this path)

**Comment by martinpeck** [comment]
related: https://github.com/Azure/azure-functions-cli/issues/288

**Comment by martinpeck** [comment]
related: https://github.com/Azure/azure-functions-cli/issues/281

**Comment by martinpeck** [comment]
The same issue is being see in the linked/related issues when creating bindings for...

- Service Bus
- Cosmos DB
- Event Hub

**Comment by swafa** [comment]
Hi,

I ran into this problem as well and we kind of have a pretty tight deadline. Does this mean that local development is not possible and I should just make do with developing my function on the Azure portal? 

Feedback would be greatly appreciated! I need advice

**Comment by wilsonge** [comment]
I believe that's the solution for now until these are implemented in the local runtime

**Comment by martinpeck** [comment]
@wilsonge I'm not 100% sure that it's impossible to do this with the local runtime. For example, after asking for better contribution docs here (https://github.com/Azure/azure-functions-microsoftgraph-extension/issues/20) you can see that the `dev` branch README.md suggests how local development can be achieved (https://github.com/Azure/azure-functions-microsoftgraph-extension/blob/dev/README.md)

... I just haven't managed to see this working...yet.

**Comment by swafa** [comment]
@wilsonge : Thanks for your reply. I think I'll write a simple Node.js wrapper to use during development though. I think developing my function on the Azure portal editor might be my cause of death. It's not ideal, of course but I believe it's the lesser of evils. 

If anybody has any other idea how to develop locally an Azure function that has a CosmosDB trigger or at least how to run one, please, let me know at any time. This unexpected discovery has unfortunately costed me a lot of time :(

**Comment by markmcgookin** [comment]
+ 1 Seeing this as well. Queue triggers (from a storage account) seem to work fine, but getting this to work with the service bus barfs on object reference. 

```
 <PackageReference Include="Azure.ServiceBus" Version="1.0.5814.23201" />
<PackageReference Include="Microsoft.Azure.NotificationHubs" Version="2.0.0-preview1" />
<PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="3.0.0-beta4" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.7" />
```

**Comment by ahmedelnably** [comment]
Closing as stale, please open a new issue if you see this happen in the latest version
