### ISSUE TITLE
Git continuous integration doesn't work with dotnet core 2.0 projects

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-functions-core-tools#300]
Someone else mentioned this here
https://github.com/Azure/azure-functions-cli/issues/230#issuecomment-332333995
and I also created an issue over here on the sample from your blog post. 
https://github.com/lindydonna/CSharpHttpCore/issues/1

Even after you set the runtime to 2.0 pushing to git will invoke kudui and build your project but then the UI will not actually show any function. My guess is that the build content isn't in a place that could be found since before there wouldn't be building and source was just taken at the root rather than from bin\release\netstanard2.0 but that's just guess. 

Not sure this is right place for this but couldn't find a better one. Feel free to point me to someone else.

**Comment by paulgmiller** [comment]
Ah it seems that if you just take the publish folder and check that into git then it works. This is a bit confusing because when you push your project up kudu takes off and seems to do the right thing (build and publish) but doesn't seem anyone knows where to look after that. It would be much more convient if git ci allowed us to just push up the dotnet core project rather than it's outputs. Still not sure if this is a kudu problem of a functions problem.

**Comment by ahmedelnably** [comment]
Closing as stale
