### ISSUE TITLE
Function deployment failed - Failed to sync triggers for function app '***'. Error: BadRequest - Encountered an error (ServiceUnavailable) from host runtime. (CODE: 400)

### ISSUE THREAD

**Issue by janisBerz** [Azure/azure-functions-core-tools#3008]
Hi team,
Ever now and then we have failed deployment from Azure DevOps with the following error:
```
Failed to sync triggers for function app '***'. Error: BadRequest - Encountered an error (ServiceUnavailable) from host runtime. (CODE: 400)
```
When re-running the deployment it goes through on the second attempt but this is annoying especially when we deploy in Production.

This is a Linux Consumption Plan function.

**Comment by michaelpeng36** [comment]
@janisBerz Would you be able to create a support ticket for this issue? You may do so through https://azure.microsoft.com/en-us/support/create-ticket/
