### ISSUE TITLE
Azurite - Ability to Configure Blob/Queue/Table ports

### ISSUE THREAD

**Issue by BadgerCap** [Azure/azure-functions-core-tools#3009]
Using Visual Studio 2022 to create a .NET 6 Azure Function that uses Storage Emulation for local development.  When the project is opened, I get the following error:

```
Ensuring Azure Functions Core Tools are up to date. This may take a few minutes...
Azure Functions Core Tools are up to date.
XX.XX: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\EXTENSIONS\MICROSOFT\Azure Storage Emulator\azurite.exe --location "C:\Users\XXXXX\AppData\Local\Temp\Azurite" --debug "C:\Users\XXXXX\AppData\Local\Temp\Azurite\debug.log"
XX.XX: Azurite Blob service is starting at http://127.0.0.1:10000
XX.XX: Azurite Blob service is successfully listening at http://127.0.0.1:10000
XX.XX: Azurite Queue service is starting at http://127.0.0.1:10001
XX.XX: Exit due to unhandled error: listen EACCES: permission denied 127.0.0.1:10001
```

This PC already has a service using 10001 that cannot be stopped.  I cannot find where I can configure starting up Azurite with a different port.  What I have found as a workaround is to start Azurite manually and give it a different port number for the Queue service (`azurite --queuePort 10011`).  With Azurite running this way, I will be able to debug properly.  However, you still get the following in Service Dependencies:

```
Ensuring Azure Functions Core Tools are up to date. This may take a few minutes...
Azure Functions Core Tools are up to date.
XX.XX: Azurite emulator cannot be started because port 10000 is already in use. Another instance of the Azurite emulator or Azure Storage emulator might be already running on your machine.
Unable to start dependency 'storage1'.
XX.XX: Azurite emulator cannot be started because port 10000 is already in use. Another instance of the Azurite emulator or Azure Storage emulator might be already running on your machine.
Unable to start dependency 'storage1'.
```

Is there a way that has not been documented anywhere I can find to configure the Azurite service dependency within Azure Function Core Tools to avoid already in-use ports?  The workaround is not a great experience and shouldn't be necessary with Azurite shipping with VS2022.

**Comment by michaelpeng36** [comment]
@BadgerCap Could you specify the port in the app setting AzureWebJobsStorage, as described [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#http-connection-strings)?
