### ISSUE TITLE
Unhelpful error message when uploading to azure

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#301]
I'm pushing 2 functions via `func azure functionapp publish myfunctions` and get "A task was canceled" - see below. That's not very helpful. How can I get more info?

![image](https://user-images.githubusercontent.com/57396/32363283-dd25db86-c06e-11e7-9877-d0941b2daef8.png)

On the server it seems that the functions are there.

**Comment by forki** [comment]
when I try to run the second function (it has HTTP trigger) I get 404

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/34868836-605f3b62-f785-11e7-81d1-e93751042a7a.png)

this is seriously annoying. How can I see what is going wrong?

**Comment by forki** [comment]
I now found in the logs that the functions runtime can't extract because the dll is still in use:

    The process cannot access the file &apos;D:\home\site\wwwroot\DeletePayment\DeletePayment.dll&apos; because it is being used by another process
    at Kudu.Core.Infrastructure.ZipArchiveExtensions.Extract

I thought Kudu would take care of this, but it seems to be broken on beta function app.
So currently I can't delete functions nor patch them.

@mikhailshilkov @fabiocav @davidebbo

**Comment by forki** [comment]
Ok I found the root cause.

in function app v1:

     The process cannot access the file &apos;D:\home\site\wwwroot\MyFunction\function.json&apos; because it is being used by another process.

in beta function app:

    The process cannot access the file &apos; ... MyFunction.dll&apos; because it is being used by another process.

so in both cases we have file locks - but on different files.

**Comment by janaagaard75** [comment]
I am experiencing the same problem, but with yet another file being the one that is locked,
`ARMClient.Authentication.dll`. Did you find a solution, @forki?

**Comment by forki** [comment]
@janaagaard75 I was told there is none

**Comment by janaagaard75** [comment]
I might have found what was causing my issue: I was using a locally installed version of `azure-functions-core-tools@core` and running it through run Yarn, that is `yarn func azure functionapp publish ...`. Installing `azure-functions-core-tools` globally seems to have fixed the issue. This is, at least, what I am experiencing on my Mac at home. The error was the except the file being used by another process was `Microsoft.AspNetCore.Cryptography.Internal.dll`.

**Comment by forki** [comment]
I don't think that's is the cause. It's more that this error is not 100
percent reproducible and you probably just were lucky here.

Am 20.02.2018 21:48 schrieb "Jan Aagaard" <notifications@github.com>:

**Comment by janaagaard75** [comment]
Reading up on you issue, I can see that what we are experiencing is not completely the same thing, so I've been posting in the wrong thread. I've also found an issue about the requirement that this package must be installed globally:
https://github.com/Azure/azure-functions-core-tools/issues/255, so I should have posted in there.

Sorry for the confusion.

**Comment by ahmedelnably** [comment]
Closing as stale
