### ISSUE TITLE
"func run" is not implemented in core branch

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-functions-core-tools#302]
`func run` doesn't seem to be supported in core runtime.
Any specific reason for that?

**Comment by cmatskas** [comment]
This has been replaced by `func host start`. The `func run` has been deprecated in v2 (cross-platform) core tools. You can find more info on the latest tools here:
https://blogs.msdn.microsoft.com/appserviceteam/2017/09/25/develop-azure-functions-on-any-platform/

**Comment by mikhailshilkov** [comment]
Well, `func host start` starts the hosts, while `func run` used to call a function, i.e. make an actual request to it. Not the same things...

**Comment by ahmedelnably** [comment]
Closing as stale
