### ISSUE TITLE
How to publish a single function?

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#303]
I have multiple functions in my repo and `func azure functionapp publish myfunctions` publishes them all.
Is there a way to let it only publish a single function?

**Comment by cmatskas** [comment]
Hi @forki, this is not available at the moment. The core tools operate on the function app level instead of individual functions so you need to architect your solution around this restriction. If you need to deploy individual Functions, you may want to place them in separate FunctionApps.

**Comment by forki** [comment]
Ok I figured it's not available right now. So please consider to add it.

Am 07.11.2017 23:22 schrieb "Christos Matskas" <notifications@github.com>:

**Comment by arichiardi** [comment]
Run against this, is this something that will be doable as some point? It would definitely be awesome to have it!

**Comment by ahmedelnably** [comment]
this is not possible and not planned. The deployment unit is a function project (function app)
Closing the issue
