### ISSUE TITLE
How Azure Function Worker 'AzureFunctionsRpcMessages' selects its port? Is it customizable

### ISSUE THREAD

**Issue by abd-shouman** [Azure/azure-functions-core-tools#3032]
I am running Azure Function locally on an Ubuntu machine using VSCode Azure Function Extension.

I created a local function, which runs on the default port `7071`.

However, I notice the following message indicating that another port is being used by what seems to be a python grpc

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://127.0.0.1:34447/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc
```

The port used here (`34447` in this case) keeps changing every time I run my function (also checked other issues here like #2894 and #2786 ) and I cannot seem to spot a pattern except that it probably falls in the range of Registered Ports (1024 to 49151).
I am wondering how the port is being selected? Is it customizable?

**_Appendix_: Why is this an issue for me?**

I am going to run Azure functions on a corporate machine where port access is restricted. Knowing which ports are needed in advance is a must for corporate I.T.

**Comment by apawast** [comment]
@abd-shouman port being selected is not customizable. Please note that this communication is scoped to the local host only.
