### ISSUE TITLE
Build for ubuntu 22.04

### ISSUE THREAD

**Issue by lara-ec** [Azure/azure-functions-core-tools#3037]
Hi,
when can we expect a build for Ubuntu 22.04? I'm worried that the build for previous versions won't work properly because of the switch to openssl 3
Thanks!

**Comment by apawast** [comment]
Hi @lara-ec thank you for opening this issue! We have added this issue to our backlog and should have a better idea of an ETA in a few weeks.

**Comment by khalistoo** [comment]
Hi, any update regarding support for ubuntu 22.04

Since the upgrade I am facing following error message when trying to run locally durable functions:

```
Azure Functions Core Tools
Core Tools Version:       3.0.4502 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.5.2.0

[2022-05-13T06:33:44.624Z] A host error has occurred during startup operation '75177db9-6ab0-4efb-8703-f08b2c35eb7c'.
[2022-05-13T06:33:44.624Z] System.Net.Http: The SSL connection could not be established, see inner exception. System.Private.CoreLib: The remote certificate is invalid according to the validation procedure.
Value cannot be null. (Parameter 'provider')
```
Which is likely caused, as mentioned earlier, by the move to openssl 3.

I can run simple functions locally by removing:

```
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
```

But this is not an option for dirable ones as binding will break.

Thanks.

**Comment by DCMattyG** [comment]
Hi @apawast, it's been a few weeks so was just checking if you've been able to come up with a better ETA for Ubuntu 22.04 support for the Azure Function tools? Thanks much!

**Comment by michaelpeng36** [comment]
@lara-ec, @DCMattyG, @khalistoo Apologies for the delay in getting back to you all on this. Could you please try the following?
```
wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt update
sudo apt install azure-functions-core-tools-4
```
Please let me know if you encounter any problems with installing or running Core Tools following these instructions.

**Comment by khalistoo** [comment]
Works like a charm. Thanks a lot

**Comment by michaelpeng36** [comment]
Closing this issue, as it has been resolved.
