### ISSUE TITLE
msi installer throws 'username' is no valid short filename and exits

### ISSUE THREAD

**Issue by BobStanneveld** [Azure/azure-functions-core-tools#3038]
Hello,

I've tried the version 3 and 4 MSI installer. I've downloaded the version 4 through the following page: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash

The MSI (both versions) throw the following error:
![MSI error](https://user-images.githubusercontent.com/21099369/165729177-2a2d0e43-aa38-4ccc-b724-d11231327e2c.png)
 
I've tried moving the MSI to different folders but it didn't have any effect. 

Best regards,
Bob

**Comment by apawast** [comment]
@BobStanneveld do you have any non-alphanumeric characters in the username? Or can you share your username?

**Comment by BobStanneveld** [comment]
Hi Apeksha Awasthi,

My username is 'bobstanneveld'. So there are no non alphanumeric characters in my username.


Best regards,
Bob

**Comment by BobStanneveld** [comment]
> @BobStanneveld do you have any non-alphanumeric characters in the username? Or can you share your username?

Hi Apeksha Awasthi,

My username is 'bobstanneveld'. So there are no non alphanumeric characters in my username.

Best regards,
Bob

**Comment by surgupta-msft** [comment]
I did not face this issue. Please reopen the issue if you are still facing it with the latest MSI.
