### ISSUE TITLE
local.settings.json not loading before pip install?

### ISSUE THREAD

**Issue by jbt-jaime** [Azure/azure-functions-core-tools#3054]
Hello,

I believe this is an issue with the Azure Functions Core Tools in VSCode, or perhaps it is a non-documented, unintuitive effect when locally debugging with F5. This is regarding Azure Functions written in Python and trying to install a private library (github), but it's a more general doubt about how `local.settings.json` gets loaded locally.

To confirm, once the function is running, there is no issue with `__init__.py` reading from `local.settings.json` as evidenced by my tests with `os.environ[<var_name>]`. However, it appears that when you hit the F5, the `local.settings.json` is not read until **after** the `pip install`. This is evidenced by the fact that a value such as `PIP_EXTRA_INDEX_URL` does not get read in time, since the `pip install` breaks.

If instead I set the env var in `tasks.json`, then the `pip install` works:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "func",
			"command": "host start",
			"problemMatcher": "$func-python-watch",
			"isBackground": true,
			"dependsOn": "pip install (functions)"
		},
		{
			"label": "pip install (functions)",
			"type": "shell",
			...
			"windows": {
				"command": "$env:PIP_EXTRA_INDEX_URL='https://<github_token>@raw.githubusercontent.com/<user>'; ${config:azureFunctions.pythonVenv}\\Scripts\\python -m pip install -r requirements.txt"
			},
			...
		}
	]
}
```
The reason I expect F5 to load `local.settings.json` before `pip install` is that in the Azure portal, if you set `PIP_EXTRA_INDEX_URL` as an Application Setting, the deploy is able to pip install using this value.

Perhaps my `tasks.json` workaround is actually the expected way to get this to work, but it'd be nice if the local F5 would work the same way as the env vars in Azure portal. That is, can we have the F5 automatically pre-load `local.settings.json` before the `pip install`?

Thanks

**Comment by ejizba** [comment]
I think this is by design. "local.settings.json" is unique to core tools and thus only applies during the `func start` command. Since "pip install" happen _before_ func start, you would have to set the env var elsewhere (and yes tasks.json is a good place).

cc @nturinski from the VS Code side in case he has any thoughts

**Comment by jbt-jaime** [comment]
Thanks @ejizba for confirming. We can wait on @nturinski's comment but it sounds like this issue can be closed.
