### ISSUE TITLE
VS code azure powershell function debugging issue - Omnisharp Json Rpc exception

### ISSUE THREAD

**Issue by lavibhatnagar** [Azure/azure-functions-core-tools#3076]
Environment:

VS Code version: 1.68.0
C# Extension version: 1.25.0
Azure Core tools: v4
Powershell version: 7

Error:

![image](https://user-images.githubusercontent.com/5319479/174056674-6903d1f9-bbc2-4967-9f42-9858df1bb058.png)

Steps to reproduce:

1. Create azure powershell function
2. Put a breakpoint anywhere and hit F5
3. See error

Things Tried:

1. uninstalling c# extension
2. installing c# extension
3. changed c# extension version
4. removed extensionBundle section from host.json

**Comment by apawast** [comment]
@lavibhatnagar can you share what happens when you type `func start` in the terminal?

**Comment by lavibhatnagar** [comment]
@apawast when i type func start, the function is executing successfully.
![Screenshot1](https://user-images.githubusercontent.com/5319479/175367720-f0339458-3deb-47fb-bb33-9f5bea69134f.png)

i am hitting the endpoint by postman, the issue is it is not hitting the breakpoint . if i press f5 i am getting the omnisharp json rpc extension exception as mentioned. Main issue is debugging the function when hitting the endpoint.

without breakpoint it is working fine. can you please try to debug the ps http function putting a breakpoint?

**Comment by lavibhatnagar** [comment]
https://stackoverflow.com/questions/72634272/vs-code-powershell-azure-function-debugging-omnisharp-exception/72644254?noredirect=1#comment128320249_72644254

**Comment by HariKrishnaRajoli-MT** [comment]
Function running successfully but debugger not hitting and that the OmniSharp Json Rpc exception dialogue box pops up - this is happening only in Azure Function - PowerShell Language. Need Quick Resolution!

We have tried the scenarios like

- Uninstalling and Re-installing the C# version in VS Code Extensions
- changing the C# version in VS Code Extensions
- Restarting the VS Code
- used the commands `func start` or `func host start` but debugger not hit.

But getting the same exception for us too.

**Comment by ejizba** [comment]
Looks like this was also filed on the VS Code extension: https://github.com/microsoft/vscode-azurefunctions/issues/3223

Since `func start` works fine by itself, this is probably not an issue with core tools and they're probably the better team to follow up

**Comment by HariKrishnaRajoli-MT** [comment]
Yes @ejizba, Same person @lavibhatnagar has raised the issue in both the repos for quick & better resolution.
