### ISSUE TITLE
How to refresh durable function key "durabletask_extension" using Az Cli

### ISSUE THREAD

**Issue by alessiofilippin** [Azure/azure-functions-core-tools#3080]
We are facing a strange issue with one of our Az Functions. We are using a durable functions which it does have several AppKeys configured, one of them is called "durabletask_extension".

We are trying to automate the refresh of the keys using Az Cli but apparently when we try to refresh the key - the shell gives an error like "Operation Returned an invalid status "NotFound" "

However, I can see from listing the keys that the key-name provided is supposed to be correct.

Kindly see images attached :)

is this a bug or am I doing something wrong?

** Refresh of default or master keys seems to be working just fine. **

![keylist](https://user-images.githubusercontent.com/47082128/175517032-bdd74c52-2348-4ec9-9cbf-902d21593a28.PNG)
![keyset](https://user-images.githubusercontent.com/47082128/175517038-9a7e8a19-ec4a-4bb1-b9ae-1cdb0598eec7.PNG)

**Comment by michaelpeng36** [comment]
@alessiofilippin This seems to be an issue with the Az CLI rather than with Core Tools. Here is the appropriate repository where you can raise this issue: https://github.com/Azure/azure-cli
