### ISSUE TITLE
Debugging multiple func projects causes incorrect local.settings.json to be loaded

### ISSUE THREAD

**Issue by MattHoneycutt** [Azure/azure-functions-core-tools#310]
Is doing debugging multiple Azure Function projects with Visual Studio supported?  I've configured 4 separate function projects to start up, and while it usually works now that I've forced each to use a different port, I sometimes see strange behavior, including func.exe seemingly picking up the wrong local.settings.json file.

For example, let's say I have functions A through D, and all four are set as startup projects for debugging in Visual Studio.

Sometimes when I start debugging, function D will seem to have settings from function A, even though it is running the code for function D.  

I also occasionally see errors like this:

Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Agent.Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

And like this:
Error updating ConfigurationManager.AppSettings

And a few other random errors that make me think there's somehow a race condition between the processes. 

Please let me know if there are any other details that I can provide.

**Comment by leftler** [comment]
I was just provided a workaround for issuet on the VS function app tooling repository for a similar issue https://github.com/Azure/Azure-Functions/issues/584 

To fix the issue add the command line switch `--nodeDebugPort 5859` to your launching of `func host` to set the port.

**Comment by MattHoneycutt** [comment]
Thanks, I'll give that a shot!

**Comment by HowardvanRooijen** [comment]
It would be really nice if --nodeDebugPort setting was added to the "Host" configuration setting, then at least we wouldn't have configuration sprinkled throughout the solution / IDE.

**Comment by ahmedelnably** [comment]
Closing, please try this in v2 or v3 version of the core tools
