### ISSUE TITLE
VSCode on MacOS net6.0 C# function doesn't debug

### ISSUE THREAD

**Issue by mpowney** [Azure/azure-functions-core-tools#3102]
I'm attempting to debug a net6.0 C# function v4 app with VS Code on MacOS.

* Azure Functions Core Tools version: 4.0.4629
* Azure Functions for Visual Studio Code extension version: 1.7.4
* VS Code version: 1.69.0
* OS: Darwin x64 21.5.0

Project:

* Target framework: net6.0
* Azure Functions Version: v4
* Package reference: Microsoft.NET.Sdk.Functions Version 4.1.1

When I run F5 debug in VSCode, here's the terminal output:

![Screen shot of VSCode Terminal window](https://user-images.githubusercontent.com/9955413/179340295-b7685be9-53c5-4508-b338-b6ff900f6e05.png)

The app compiles, and starts running, however the debugger does not attach to the func process. The VSCode status bar turns orange momentarily when the console output reaches the last line, but then returns back to a normal state. Any tips in getting debug mode working here?

Thanks!

Note: [Issue first raised here in MicrosoftDocs/azure-docs](https://github.com/MicrosoftDocs/azure-docs/issues/95828) but was directed to this repo instead

**Comment by mpowney** [comment]
Note the same csproj opened in VS2022 for Mac, the debugger attaches as expected.

**Comment by michaelpeng36** [comment]
@mpowney Thanks for raising this issue. It looks related to https://github.com/microsoft/vscode-azurefunctions/issues/3175 and https://github.com/microsoft/vscode-azurefunctions/issues/3030. The VS Code team should be better equipped to address this.

**Comment by nturinski** [comment]
There is a workaround in this issue: https://github.com/OmniSharp/omnisharp-vscode/issues/4903
