### ISSUE TITLE
Could not find DurableTask.AzureStorage.dll - message sent - Instance not terminated

### ISSUE THREAD

**Issue by HenryLGatesFoundation** [Azure/azure-functions-core-tools#3123]
When using the Core Tools 3.0.4669 (x64) I get the following message, although it appears to send the terminate message, I execute the following: 

func durable terminate --id 12345678901234567890 --reason "Excessive run-time"

I receive the following:

"Could not find DurableTask.AzureStorage.dll. The functions host must be running a Durable Functions app in order for Durable Functions CLI commands to work.
Sent a termination message to instance '12345678901234567890'. Waiting up to 30 seconds for the orchestration to actually terminate...
Instance did not terminate within the given timeout."

I receive what appears to be a minor error, it apparently sends the message, yet it never successfully terminates the instance.  

Any thoughts on this?  Any assistance you can provide is appreciated.

**Comment by HenryLGatesFoundation** [comment]
The results of my task termination attempts. are mixed  Here’s the synopsis:

Good:
Every termination request message was both received and recorded, 👍
Although the first task run failed, the second run was a complete success. **Somehow** it seems that my termination requests were honored...although much later.

Bad:
The termination requests were not honored by Azure Data Factory until almost 7 hours later.

Ugly:
The first task/process run [which was a new instance of the task I desired/needed to terminate] failed after running for a total time of 1:22:43.  That’s a significant loss of time.

![ADF Task-Termination Events Results-Annotated-Obscured](https://user-images.githubusercontent.com/59934454/184430841-1c696e80-5e76-4c19-a778-678ede55b3a6.png)

**Comment by michaelpeng36** [comment]
@HenryLGatesFoundation Were you able to resolve the first issue with the `Could not find DurableTask.AzureStorage.dll`?

**Comment by HenryLGatesFoundation** [comment]
> @HenryLGatesFoundation Were you able to resolve the first issue with the `Could not find DurableTask.AzureStorage.dll`?

Hello @michaelpeng36 .  No, feeling like a "nuisance" error/warning, I overlooked it, needing to focus on the more important facts of the command issuance.  

Namely, each time I submitted a termination command, it seems that ADF treated it as a "request" which it logged, versus an instruction which was meant to interrupt the processing of the current/specified task.  This is a real issue with very important implications regarding the running of daily pipelines with task instances which may overlap, considering that the terminate "command" is not behaving as expected.

Any assistance in this specific regard would be very much appreciated @michaelpeng36.

**Comment by HenryLGatesFoundation** [comment]
Just learned that our class is running in single-threaded mode and we'll be decorating it with the async keyword soon.  That should help decrease its unresponsiveness.

I submit that it would be a more appropriate design for the **platform** to be able to terminate/evict an aberrant-running constituent process, rather than for the aberrant process to be responsible for managing its own termination/eviction, when a such a termination request is issued.
