### ISSUE TITLE
nodeDebugPort should be setable from local.settings.json

### ISSUE THREAD

**Issue by leftler** [Azure/azure-functions-core-tools#313]
Currently there is no way to specify the port the debugger will use from within the `local.settings.json` file. The only way to specify it is by setting `--nodeDebugPort` as a command line switch.

I suggest that a node be added to the `local.settings.json` file to specify the local debugging port from within that file to make debugging with Visual Studio of multiple projects easier.

Related issue from https://github.com/Azure/Azure-Functions/issues/584

**Comment by johlrich** [comment]
+1 for this since it would have made it easier to work around the problem observed in https://github.com/Azure/azure-functions-cli/issues/346

**Comment by motowilliams** [comment]
I currently have a helper script per function project bootstrapping local functions for keeping http and node debug port collections in out solutions but some team members what this to be all 'Visual Studio-able' via local.settings.json

**Comment by ahmelsayed** [comment]
fixed in 7b1dc9154c1f96cca64735b887df7184c8a4abec

should be able to specify 

```json
{
   "NodeDebugPort": 1234
}
```

in `local.settings.json`. Command line will take precedent over the setting in the file.

**Comment by ahmelsayed** [comment]
and sorry for the delay :)
