### ISSUE TITLE
 Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by nunon** [Azure/azure-functions-core-tools#3139]
I'm trying to follow the tutorial to create an Azure function, as described [here](https://stackoverflow.com/questions/73503579/quickstart-create-a-function-in-azure-with-python-using-visual-studio-code-st).

Using the Visual studio code based version, upon running __init.py__, nothing happens.

When trying to run the same, using the cli version, upon trying to run the function locally with func start, I get the error:

[2022-08-29T11:24:19.931Z] A host error has occurred during startup operation '034b3411-4de9-4990-a271-80f1182eb192'.
[2022-08-29T11:24:19.933Z] Microsoft.Azure.WebJobs.Extensions.Http: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. O sistema não conseguiu localizar o ficheiro especificado.      
Value cannot be null. (Parameter 'provider')

**Comment by michaelpeng36** [comment]
@nunon Could you follow the steps detailed in #3115 and see if it resolves your issue? In particular, could you reinstall .NET 6 and reinstall Core Tools?

**Comment by nunon** [comment]
@michaelpeng36  actually, I reinstalled :NET but it didn't solve my problem.
After a lot of trial and error, I figured out that in order to activate the virtual environment, I can't follow the docs as is, but:
LocalFunctionProj\.venv\Scripts\activate.bat
And from here on all is good.

**Comment by michaelpeng36** [comment]
@nunon Would you be able to provide specific repro steps for this issue? What machine/architecture are you using, and what version of Core Tools and .NET are you using?

**Comment by nunon** [comment]
I don't know how to answer that. 
I only know how to develop the models and that is already complex.
Now I'm also discovering that deploying the models into azure functions is way more complex.

**Comment by apawast** [comment]
@nunon can you help provide the steps you took that caused the first error?

**Comment by nunon** [comment]
@apawast [these](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python) are the steps I've followed.
I've managed to fix the issue by following the [cli version]([url]https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python(url)), although, as described in my previous post, I figured out that in order to activate the virtual environment, I can't follow the docs as is, but:
LocalFunctionProj.venv\Scripts\activate.bat
