### ISSUE TITLE
func host start --script-root cannot handle absolute paths.

### ISSUE THREAD

**Issue by frozenbubble** [Azure/azure-functions-core-tools#314]
Environment: Arch linux x64
Tool version: 2.0.1-beta.21

When I try something like 
func host start --script-root /home/peter/Projects/CSharpHttpCore/HttpTriggerCore/bin/Debug/netstandard2.0

or 

func host start --script-root ~/Projects/CSharpHttpCore/HttpTriggerCore/bin/Debug/netstandard2.0
I get the error message:
Error parsing script-root. The path to the root of the function app where the command will be executed.

However, when I enter a relative path:
func host start --script-root ../../Projects/CSharpHttpCore/HttpTriggerCore/bin/Debug/netstandard2.0

it starts as expected.

**Comment by frozenbubble** [comment]
I couldn't get it to build on linux but I'm pretty sure if dir was used as is here

    Parser
        .Setup<string>("script-root")
        .WithDescription($"The path to the root of the function app where the command will be executed.")
        .SetDefault(".")
        .Callback(dir => {
            var fullDirPath = Path.GetFullPath(Path.Combine(Environment.CurrentDirectory, dir));
            ScriptRoot = ScriptHostHelpers.GetFunctionAppRootDirectory(fullDirPath);
    });

if Path.IsPathRooted(dir) was true the problem would be solved

**Comment by ahmelsayed** [comment]
sorry for the delay in responding to this @frozenbubble 
50323beaaef1ad61dd0d4c13d7fe606d7cfec51c should fix this. I should test more unix style paths though, so I'll keep this open until I do that

**Comment by ahmelsayed** [comment]
I haven't seen any unix paths issues with this code path since I made that fix. I tested few scenarios on linux and all seems good. I'll close this issue.
