### ISSUE TITLE
Unable to find an Azure Storage connection string to use for this binding

### ISSUE THREAD

**Issue by contactkanika12** [Azure/azure-functions-core-tools#3149]
I was able to run my azure function locally but recently i have started getting this issue
Unable to find an Azure Storage connection string to use for this binding. 

We are using Azure Storage emulator on local

this is my localsettings file
{

  "IsEncrypted": false,

  "Values": {

    "AzureWebJobsStorage": "UseDevelopmentStorage=true",

    "FUNCTIONS_EXTENSION_VERSION": "~3",

    "IsDevelopment": "true",

    "COSMIC_ENVIRONMENT": "Dev",

    "FUNCTIONS_WORKER_RUNTIME": "dotnet",

    "AzureWebJobsSecretStorageType":  "files"
  }

 }
 
 and my azure function has following configuration
 
 
![image](https://user-images.githubusercontent.com/40831239/189688380-e8727087-324d-4c39-9051-4c99532d5da9.png)
Please suggest what is missing?

**Comment by michaelpeng36** [comment]
@contactkanika12 The app settings you have on Azure should not affect the behavior of Core Tools if you are running your function app locally. Could you please attach the `function.json` files for each function in your app? Also could you attach the full error message you are seeing? To do so, you may need to set the environment variable `CLI_DEBUG=1`.
