### ISSUE TITLE
func azure publish should work atomic

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#316]
Currently https://github.com/Azure/azure-functions-cli/issues/315 shows that the azure functions can crash with 500 but the function code still gets updated. Publsih operations should be atomic. 

Also they should not leave old files like in the yellow warning:

![image](https://user-images.githubusercontent.com/57396/32790274-48e8b422-c95e-11e7-9934-21470b6d882f.png)

**Comment by ahmedelnably** [comment]
We have added a number of enhancements to this code path, closing this as resolved
