### ISSUE TITLE
Unable to load DLL 'kernel32.dll'

### ISSUE THREAD

**Issue by simonaco** [Azure/azure-functions-core-tools#317]
I am attempting to add a new setting using the cli and am running into a missing kernel32.dll exception. 
func settings add smth
Please enter the value: Unable to load DLL 'kernel32.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)

My env is OSX with dotnet core 2.0.2 installed.

**Comment by matiaswhyline** [comment]
I have the same issue. Can anybody help us?
