### ISSUE TITLE
Python -m v2 (new programming model) fails to do `func new` template operations

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-core-tools#3181]
I'm trying the new decorator based programming model.  I was very surprised to see `func new` throws errors.  To me, the new model simplifies the code in the template, but does not negate the need for templates or a func new experience.  I believe this is an experience regression that breaks the overall user model.  It also makes iterative development harder, where I want to easily add different kinds of Triggers and Bindings, or if I want multiple Functions (apps) in the same resource.  

Can we please revisit if `func new` in the python `-m v2` case can have alternate templates that have decorators and exclude functions.json file?  

Repro:
```console
 paulyuk@Pauls-MBP-2  ~/src/functions/trynewpythonmodel1  func init --worker-runtime python -m v2
Found Python version 3.9.6 (python3).
The new Python programming model is in public preview. Learn more at https://aka.ms/pythonprogrammingmodel
Writing requirements.txt
Writing function_app.py
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing /Users/paulyuk/src/functions/trynewpythonmodel1/.vscode/extensions.json

 paulyuk@Pauls-MBP-2  ~/src/functions/trynewpythonmodel1  func new
When using the new Python programming model, triggers and bindings are created as decorators within the Python file itself.
For information on how to create a new function with the new programming model, see https://aka.ms/pythonprogrammingmodel
Function not created! 'func new' is not supported for the preview of the V2 Python programming model.
```

**Comment by paulyuk** [comment]
@shreyabatra4

**Comment by shreyabatra4** [comment]
func new is now supported for the v2 programming model - closing this issue
