### ISSUE TITLE
Doc missing Ubuntu 22.04 installation instructions

### ISSUE THREAD

**Issue by grava** [Azure/azure-functions-core-tools#3197]
Just as a note, it works exactly as for any other ubuntu version. Just missing the 22.04 versions specs.

**Comment by mcraiha** [comment]
Should someone send PR for this?

**Comment by darwincr** [comment]
i tried following the steps in ubuntu 22.04 and i cant get 6.0 runtime to show up

$ dotnet --list-sdks
6.0.417 [/usr/share/dotnet/sdk]
8.0.100 [/usr/share/dotnet/sdk]

$ dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

my powershell core function is asking for the 6.0 runtime and it fails to run, in windows it works fine

**Comment by ltalirz** [comment]
Hehe, this one can then be closed as well... https://github.com/Azure/azure-functions-core-tools/pull/3727
