### ISSUE TITLE
Unable to perform func new XXXX & func start

### ISSUE THREAD

**Issue by voyager163** [Azure/azure-functions-core-tools#3208]
Hi,

Using the latest Azure Functions Core Tools (4.0.4895) and Azure Function runtime (4.13.0.19486), I am not able to perform func new XXX and func start.

In addition, I am not able to run the func templates list too. Looks like the whole core function tools have issues.

However, I can perform func init. In order to by pass this issue, I have to use the GUI method to create the Azure Functions.

![Screenshot 2022-11-27 134547](https://user-images.githubusercontent.com/4599055/204121185-782de4da-0fef-4860-ac2f-bdc9bc71112b.png)

Below is my computer specs.

Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎12/‎9/‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by surgupta-msft** [comment]
The latest version is working fine
