### ISSUE TITLE
New Programming Model feature requests( Python ) for Core Tools

### ISSUE THREAD

**Issue by shreyabatra4** [Azure/azure-functions-core-tools#3209]
Core Tools support for Python programming model (GA) and Node programming model (Preview)

https://microsoft-my.sharepoint.com/:p:/p/shbatr/EagStJUMN81El-neqxw156gBYi91FQDiTWBuuuQLqUwFWw?e=IMJyDd

High level checklist:

- [ ] - Support for `func new` (P0)
- [ ] - Defaulting updates (P0)
- [ ] - Error handling additions (P0)
- [ ] - Support for `func append` (P1)
- [ ] - Preview code support (P2)

**Comment by kshyju** [comment]
@shreyabatra4 Is this issue still valid/relevant?
