### ISSUE TITLE
Failed to run Azure Functions. Please checkout console output

### ISSUE THREAD

**Issue by slide** [Azure/azure-functions-core-tools#321]
When I run mvn azure-functions:run, I get the error in the subject. I ran with debugging mode turned on in Maven and got the following: 

```
[DEBUG] Executing command: cmd.exe /c func
[DEBUG] Process exit value: 0
[INFO] Azure Functions Core Tools found.
[INFO] Starting running Azure Functions...
[DEBUG] Executing command: cmd.exe /c cd /D C:\code\_external\_jenkins\hosting-checker\target\azure-functions\hosting-checker-20171117104441764 && func host start
...
[11/17/2017 5:47:39 PM] Host configuration file read:
[11/17/2017 5:47:39 PM] {}
[DEBUG] Process exit value: -1073741819
```

So, I ran `func host start` in the same directory and echo'd the exit code and it is indeed that same value, which in hex is 0xc0000005 (Access Violation).

This works fine on another machine, so I am not sure what to look for. Are there any logs created that can give further details?

**Comment by thieba** [comment]
Same here, got some issues with VS too : if I build the solution from VS no job function found, but if I build from cmd then launch from VS to debug, the job function are found but as soon as I trigger a function I got access violation.
I'm using Net Core 2.0 et the new Trigger Attribute.

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still facing the same issue with the latest version, please reopen
