### ISSUE TITLE
System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Http.Abstractions'

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-core-tools#322]
C:\Users\erics\AppData\Roaming\npm
`-- azure-functions-core-tools@2.0.1-beta.21
  +-- chalk@2.3.0
  | `-- ansi-styles@3.2.0
  |   `-- color-convert@1.9.1
  `-- unzipper@0.8.11
    `-- big-integer@1.6.26

![image](https://user-images.githubusercontent.com/5826764/33027574-1680e98a-cdd9-11e7-8802-2ed1a0dffa0d.png)

**Comment by kulibali** [comment]
I am also seeing this when trying to debug a new Functions project from a new install of VS2017 15.5.2.

**Comment by andymac4182** [comment]
I am getting the same error in `VS2017 15.5.2` It seems related to the fact that the cli loads a certain version of the dll then you try to reference a different version. I am having a similar issue with WindowsAzure.Storage 

Seems related to https://github.com/Azure/azure-functions-cli/issues/335 and https://github.com/Azure/azure-functions-cli/issues/253

**Comment by evgeny-n** [comment]
Same issue for me. Pre-conditions: 
C# function, 
.Net Standard 2.0, 
WindowsAzure.Storage 8.7.0

Could not load assembly WindowsAzure.Storage (or similar). Nothing worked, until I downgraded WindowsAzure.Storage to 8.6.0. This is a version I've seen when NPM was restoring dependencies for Functions SDK. Downgraded, cleaned, re-compiled - voila!

**Comment by corsjune** [comment]
Also had same issue with WindowsAzure.Storage 9.0 and 8.7. Had to downgrade to 8.6. Thanks for the workaround evgeny-n ! 

Did not have this issue with Azure functions V1 (.Net Framework). Occurred when I ported to V2 (.Net Standard 2.0)

**Comment by jrebagliatti** [comment]
Thanks @evgeny-n for your workaround. Updating the *Azure Functions and Web Jobs Tools* to the latest version might also help.

**Comment by jg11jg** [comment]
Am getting same error message when running azure functions project locally.  Targetting .net standard 2.0. 
 Using .net sdk functions 1.0.6 and it worked ok initially for the "Function1" freebie function.  Then added reference to Microsoft.AspNetCore.Authentication.JwtBearer and immediately get this error.

I also tried installing System.IdentityModel.Tokens.Jwt package [i just want to parse a jwt].  this works in local debugging but fails when I publish it to azure.

Is it just me or is version hell back with a massive vengeance in .net core space - possibly worse than ever before?

**Comment by SoulFireMage** [comment]
Just for fun, I get it on the actual Azure portal. The code is merely from the Azure samples.

![image](https://user-images.githubusercontent.com/2396080/39365687-c17f64fc-4a29-11e8-99a9-7dd47338b730.png)

**Comment by reddy6ue** [comment]
I am getting something similar, but for cosmosdb trigger functions. 

 `System.Private.CoreLib: One or more errors occurred. (Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)). Microsoft.Azure.DocumentDB.Core: Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

**Comment by Bubeee** [comment]
The similar issue for the prerelease version of Azure.KeyVault

`Could not load file or assembly 'Microsoft.Azure.KeyVault, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)`

![image](https://user-images.githubusercontent.com/5691429/39756382-0c29710e-52d2-11e8-9404-11bb1a55eaa2.png)

**Comment by johnkwaters** [comment]
Getting the same thing, after adding Microsoft.AspNetCore.Authentication.JwtBearer. VS 2017 15.7.1. Azure Functions and Web Jobs Tools 15.0.40502.0.

**Comment by espray** [comment]
Same issue with `<PackageReference Include="Microsoft.Extensions.Options" Version="2.0.1" />` down graded to `<PackageReference Include="Microsoft.Extensions.Options" Version="2.0.0" />` to resolve the issue

**Comment by apostrophe** [comment]
Updating "Azure Functions and Web Jobs Tools" extension fixed the issue for me, although I am only trying to get it to run locally.

Steps:
In Visual Studio
Go to Tools > Extensions and Updates 
In Extensions and Updates dialog, expand Updates > Visual Studio Marketplace
Choose Azure Functions and Web Jobs Tools
Select Update
Restart VS

**Comment by johnwc** [comment]
@apostrophe , fixed what exactly? I have the latest and greatest of what's in the "Extensions and Updates" and I still see this when trying to use anything above EF Core 2.0

I have 15.0.40502.0 installed of "Azure Functions and Web Jobs Tools"

**Comment by apostrophe** [comment]
> I have 15.0.40502.0 installed of "Azure Functions and Web Jobs Tools"

That's the same version I am have, but I'm not using EF Core.

**Comment by johnkwaters** [comment]
I was able to get further by downgrading some of the nuget references to be the same as used by the tools, but  only got so far down that path. Not able to reference EF Core without getting similar errors.

**Comment by daviburg** [comment]
Had this issue, got the updates (VS extension then Nuget then CLI tool then Storage emulator), issue stopped and function was working. Re-opened the project later in the evening, issue is back. No further update possible this time. Puzzling...

**Comment by espray** [comment]
I have not had this issue for some time now. Currently running on v36 all nugets on latested(EF, AzStorage and AzEventHub).
Using VS 2017 as well.

@daviburg
Double check the host version. Maybe the AzHost is npm installed global????

**Comment by maiqbal11** [comment]
A significant number of changes relating to Functions V2 GA have happened since this issue was originally opened and the underlying issue has been addressed. Anyone who is still experiencing issues should feel free to open separate issues.
