### ISSUE TITLE
Updating Azure Function

### ISSUE THREAD

**Issue by aardrasystems** [Azure/azure-functions-core-tools#3229]
Hi 

I am trying to update my function app to Version 4.
I am getting a number of errors and have been advised to update the code

This is my current version:
```
Azure Functions Core Tools
Core Tools Version:       4.0.3928 Commit hash: 7d1d4a32700695bbf290a871c7492fde84bb767e  (64-bit)
Function Runtime Version: 4.0.1.16815
```

How do I update my project to more recent version? I am using Visual Studio?

I have downloaded the lastest, but it seems my project is still running a older version.

**Comment by kemeshannaicker** [comment]
Having the same issue.

**Comment by aardrasystems** [comment]
@kemeshannaicker 

Ok, i managed to solve my issue by deleting the following folder 

C:\Users\Administrator\AppData\Local\AzureFunctionsTools 

It seems if you delete it, and you go to Vusial Studio and run build, Visual Studio automatically finds another version of Azure Functions Tools.

Let me know if this has worked for you as well
