### ISSUE TITLE
The function type name 'CancelReservation' is invalid.

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#324]
Function ($CancelReservation) Error: The function type name 'CancelReservation' is invalid.
Session Id: c9a26090b544491f99bbe9c70004d602

Timestamp: 2017-11-22T13:14:14.887Z
West-Europe

**Comment by forki** [comment]
Can someone please post the rules for the naming? I'm constantly running into this. And with is the azure function cli publishing functions with invalid name anyway?

**Comment by jfellien** [comment]
The only rule I found out is never start a function name with a number. But your name looks pretty good, like the names I use.

**Comment by jfellien** [comment]
I created a function successfully without the same behaviour of yours. Did you already created a function with this name, deleted it and now recreate it?

**Comment by forki** [comment]
In this case maybe. But it works with other recreated functions.

Also it happens to be related to the length of the name

**Comment by jfellien** [comment]
I used the same name like you in my test and it works. :( Bad for you now.

**Comment by forki** [comment]
fixed by deleting and recreating the function app
