### ISSUE TITLE
VSCode asks me to update to 4.0.4915, but update doesn't appear to take

### ISSUE THREAD

**Issue by marked23** [Azure/azure-functions-core-tools#3242]
In VSCode, when I use the Azure extension, I get a pop-up suggesting that I update.
![image](https://user-images.githubusercontent.com/732793/211419386-e1325a6a-c33d-4fd4-a036-7333b4ff5fa8.png)

I click Update, then I see Azure Functions output messages (in terminal area):

>2:17:14 PM: Running command: "npm install -g azure-functions-core-tools@4"...
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

>changed 48 packages, and audited 49 packages in 38s

>2 packages are looking for funding
>  run `npm fund` for details

>found 0 vulnerabilities
>2:17:54 PM: Finished running command: "npm install -g azure-functions-core-tools@4".

When I restart VSCode, I see the same pop-up, again. 

Is there something I can do to forcibly update this with some other installation technique?

**Comment by zbinden-z** [comment]
![image](https://user-images.githubusercontent.com/114276776/221400013-41f79458-958f-4df8-8630-0ae6b82d05be.png)

I am also afflicted.  Output/logs are the same.

**Comment by marked23** [comment]
I had multiple installs of Azure Functions Core Tools.  I uninstalled/deleted them all, and then let VSCode reinstall the one it will be happy with.

**Comment by surgupta-msft** [comment]
This should be fixed by https://github.com/Azure/azure-functions-core-tools/pull/3882
