### ISSUE TITLE
Unable to use https in local on MacOS 13.1

### ISSUE THREAD

**Issue by binoypatel** [Azure/azure-functions-core-tools#3243]
Hi there,

I am trying to run Azure functions locally using --useHttps parameter. When I launch the function URL in the chrome browser then I am getting:

![image](https://user-images.githubusercontent.com/4742252/210966893-61b496c9-1a8d-440e-be8f-6cab529a1fd6.png)

When I does the same in Postman then I am getting:

![image](https://user-images.githubusercontent.com/4742252/210967638-c3c201c2-33b9-4544-8294-a324b4395039.png)

I even tried generating self-signed cert manually using openssl but had no luck. Here are some environment details:

Azure Functions Core Tools
Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.14.0.19631

MacOS: 13.1 (Ventura)

Dotnet version: 7.0.100

Can someone please help what is wrong with my environment/setup? 

PS: http works fine (without using --useHttps switch)

**Comment by binoypatel** [comment]
Sorry I don't have windows PC that I can test with.

**Comment by bhagyshricompany** [comment]
@binoypatel  If you are running Azure Functions locally using the --useHttps parameter and you are encountering an error when trying to access the function URL in a web browser, there are a few things to check:

Verify that the correct certificate is being used: When using the --useHttps parameter, the Azure Functions runtime uses the certificate specified in the --cert parameter. Verify that the certificate being used is the correct one and that it is installed on your local machine.

Check for firewall or antivirus blocking: Some firewall or antivirus software may block the connection to the Azure Functions runtime. Disable any firewall or antivirus software temporarily and try again.

Check if the function app is running: Verify that the function app is running and that the host is up and running.

Check the URL: Verify that you are accessing the correct URL and that the URL is correct.

Verify the binding: Verify that the host.json and local.settings.json files are configured to use https.

Check logs: Check the logs of the functions runtime, if it is showing any error related to https

**Comment by bhagyshricompany** [comment]
@fabiocav  please validate on this
