### ISSUE TITLE
Vulnerabilities that need to be patched

### ISSUE THREAD

**Issue by nbjohnson** [Azure/azure-functions-core-tools#3244]
I recently ran a trivy scan and this tool showed up with having several fixable vulnerabilities, including a critical one.

azure-function-core-tools version: 4.0.4915

The trivy scan is providing me with the following list:

| package | installed | fixed | level |
| --------- | --------- | ----- | ----- |
| com.fasterxml.jackson:jackson-databind | 2.13.3 | 2.13.4.1 | high |
| com.fasterxml.jackson:jackson-databind | 2.13.3 | 2.13.4.1 | high |
| com.fasterxml.woodstox:woodstox-core | 6.2.7 | 6.4.0 | high |
| com.google.guava:guava | 26.0-jre | 30.0 | low |
| com.google.protobuf:protobuf-java | 3.19.4 | 3.19.6 | high |
| io.netty:netty-codec-http | 4.1.79.Final | 4.1.86.Final | low |
| org.apache.commons:commons-text | 1.9 | 1.10.0 | critical |
| org.yaml:snakeyaml | 1.31 | 1.32 | medium |

I would love for all vulnerabilities to be addressed, but if the high and critical ones could be made a top priority, that would be greatly appreciated.

**Comment by shanecoll3** [comment]
Hi, we too need this vulnerabilities resolved as they are producing critical vulnerabilities in our app. Is there a timeline on when there will be a new version release to patch these? Thanks
