### ISSUE TITLE
CLI doesn't work if node 9.x is installed 

### ISSUE THREAD

**Issue by Knaackee** [Azure/azure-functions-core-tools#326]
I try to run the function emulator on my mac but get the following error on start.
Any ideas ?

```
$ func host start

......

info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
      Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/Users/myUsername/.azurefunctions/bin/workers/node/grpc/src/node/extension_binary/node-v59-darwin-x64/grpc_node.node'
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
      module.js:544
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
          throw err;
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
          ^
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
      Error: Cannot find module './Worker.js'
```

**Comment by nagytech** [comment]
`npm i -g azure-functions-core-tools@core --unsafe-perm`

**Comment by Knaackee** [comment]
I did that already and did it again. I have to use `sudo` though.
Sadly, this changes nothing.

**Comment by Knaackee** [comment]
Found the problem. I had node version 9.2 installed. After downgrading to 8.9 its working now.

**Comment by compulim** [comment]
The tool looks pretty broken now. @ahmelsayed are you looking at this?

**Comment by nelak** [comment]
It looks like newer versions of node need a newer grpc extension, that's why going back to v8.9.0 is working. Node v9.2.0 would require `node-v59-darwin-x64/grpc_node.node` to work.

The Azure functions cli currently install only provides support for these extensions:
```
node-v48-win32-ia32
node-v57-darwin-ia32
node-v57-darwin-x64
node-v57-linux-ia32
node-v57-linux-x64
node-v57-win32-ia32
node-v57-win32-x64
```

**Comment by ahmelsayed** [comment]
Thank you @Knaackee and @nelak for find the root cause of the issue. I'll update package.json to set 8.x as the upper bound of node, though for actual support of node 9.x the issue should go on the runtime repo here https://github.com/Azure/azure-webjobs-sdk-script/issues

**Comment by jhealy** [comment]
Any timeline for when this will work with node 9.x?

**Comment by jhealy** [comment]
You can also fall back to the non-core version of cli by using the non-core version of node.
Install via "npm i -g azure-functions-core-tools" instead of "npm i -g azure-functions-core-tools@core".

**Comment by ntomsic** [comment]
Any update on this?

**Comment by PoisonousJohn** [comment]
@ntomsic  For linux as well

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2758
