### ISSUE TITLE
Unable to do post on azure function

### ISSUE THREAD

**Issue by rakeshchauhanngtech** [Azure/azure-functions-core-tools#329]
Hi Iam new to Azure functions i am using VS 2017 15.4 and running helloworld function app on local. i was able to do get request on this function but when i perform post on same uri it gives. 

mscorlib: Exception while executing function: HelloWorld. System.Net.Http.Formatting: No MediaTypeFormatter is available to read an object of type 'Object' from content with media type 'application/octet-stream'.

**Comment by ahmelsayed** [comment]
Please share more details about what you're trying to do, your code and how you're testing it.
