### ISSUE TITLE
Create a "-source" parameter to download extensions from alternate NuGet feeds

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-core-tools#330]
Currently `func extensions install` doesn't allow you to specify a package source. Ideally there would also be a `-source` switch where I could choose an alternate feed, like myget or a local nuget repository.

I would like to use this for testing preliminary releases of my extension using the CLI.

**Comment by mikhailshilkov** [comment]
You can achieve this by adding your local repository to `NuGet.config`. Is it not enough for your scenario?
