### ISSUE TITLE
Azure functions fails to start in Visual Studio 2017 if User folder has norwegian letters 

### ISSUE THREAD

**Issue by Velcrow81** [Azure/azure-functions-core-tools#332]
I recently tried azure functions in Visual Studio 2017, but I am unable to start it locally. When I tried to run the project I was prompted to install azure.function-cli since it was missing. The install works fine, but the start console crashes right after listing out HTTP functions with the following error:

```
module.js:471
   throw err;
   ^

Error: Cannot find module 
'C:\Users\\{UserName}\AppData\Local\Azure.Functions.Cli\1.0.7\edge\double_edge.js'
at Function.Module._resolveFilename (module.js:469:15)
...
```
See image for error message (crash closes window very fast, so I had to record a video and capture a screen from it to see the error message)
![image](https://user-images.githubusercontent.com/22069947/33609067-f748eadc-d9c6-11e7-80b5-f2de808aa05e.png)

In the error message I can see that Ø is not shown correctly (my name is Bjørn, but in the path it is shown as Bj{wierd symbol that does not look like Ø}rn, which leads me to think that the files are not found because of this. The files are on disk at the correct path, but the project cant find it.

**Comment by lofotr** [comment]
I have the exact same problem.

By doing some investigation, I found out that this is a problem with edge.js;
someone have proposed a pull request for this, however I don't think someone is working much on edge at the moment. [https://github.com/tjanczuk/edge/pull/555](url)

It's related to this issue, [https://github.com/Azure/azure-functions-cli/issues/134](url), that was closed in May.

@Velcrow81 Did you find any workaround?

**Comment by Velcrow81** [comment]
Nope. My workaround is that I don't run my functions locally :) I tried to change my user name, but after doing some regedit changes, my user disappeared so I rolled back and decided to wait and test i azure for now

Btw, your links are broken.

**Comment by nelak** [comment]
@Velcrow81 it sounds like you are trying to run javascript with azure functions, have you tried installing beta cli, with the `core` tag? The new runtime uses a worker model that uses nodejs directly instead of edgejs it might be worth a try.

**Comment by Velcrow81** [comment]
I created a C# azure function project in Visual Studio 2017.  When I ran the project, I was prompted to install the cli sine ut was missing. I accepted and it was installed in my user profile folder. If what was installed is related to JavaScript, then maybe this is another error?

**Comment by nelak** [comment]
Can't say for sure, v1 of the runtime used EdgeJS to run javascript, based on this I assumed you were trying to run a javascript function. Still you can try installing the beta cli running `npm install -g azure-functions-core-tools@core` and give that a try.

**Comment by lofotr** [comment]
@Velcrow81, I fixed the links :)

I managed to change the folder name, I think this is bad practice, but now it works. However what you can do instead, if you only want to test functions locally, is to move/make a copy of the cli folder somewhere outside the profile folder, and then run functions manually through the console; I've tried to find a way to start it from VS, but I've used to much time on this already so I gave up. 

@nelak Would what you propose work with Visual Studio? Of course I could always give it a try, but I'd rather ask first, I've spent to much time on this.

**Comment by nelak** [comment]
@lofotr No idea really, I'm using VSCode and the cli for testing my Azure Functions

**Comment by Velcrow81** [comment]
@ahmelsayed : Any progress on this? :)

**Comment by singstad** [comment]
@Velcrow81 I have had the same problem and used symbolic linking as a workaround. https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by Velcrow81** [comment]
@singstad : Thanks for the tip. Could you provide me with a sample on how you made this work? I tried mklink /J C:\Users\Bjørn\AppData\Local\Azure.Functions.Cli C:\Users\Bjorn\AppData\Local\Azure.Functions.Cli and the reverse but non worked. It still tries the path with Ø in it. At what level did you create the link? Local? Edge?

@ahmelsayed : Thanks for the update :)

**Comment by jeffhollan** [comment]
@Velcrow81 you can create v2 functions in Visual Studio 2017 today. I'm wondering if when you create a new function project and select .NET Standard Preview if you still see this issue pop up? As @ahmelsayed mentioned in v2 we call node.exe directly and also believe we provide flags for Visual Studio to not attempt to start the node process if only a .NET function app.

**Comment by singstad** [comment]
@Velcrow81 : It has been I while since I had this problem but try replacing your norwegian character with a questionmark "?". You only have to do this for the user folder so i guess 
mklink /J  "c:\Users\Bj�rn" "c:\Users\Bjørn" should work.

![image](https://user-images.githubusercontent.com/927731/40356051-50c19062-5db8-11e8-9d89-d7504fe2b280.png)

**Comment by Velcrow81** [comment]
Seems ? is an illegal character in folder names: 
C:\Users>mklink /J "c:\Users\Bj?rn" "c:\Users\Bjørn"
The filename, directory name, or volume label syntax is incorrect.

**Comment by jeffhollan** [comment]
Just trying to clarify - are you still seeing this issue for new V2 function apps using the latest version of VS tooling?

**Comment by Velcrow81** [comment]
I tried a new Azure Function project today and it works for V2 :) Then I have another reason to upgrade my V1 functions.

**Comment by TimNilimaa** [comment]
Justed filed a new issue on this, #768 Issue is that we must use v1 as we need support for Open API/Swagger.

**Comment by ahmelsayed** [comment]
Closing this issue as mentioned on #768. This issue is in the underlying dependencies of the core-tools, namely https://github.com/Azure/azure-functions-host which is using edgejs. I'd follow up on the host repo for any updates

**Comment by aquamoth** [comment]
Creating a juncion point with "mklink" as suggested above really saved the day for me. Thanks!
