### ISSUE TITLE
Update NewFunctions Host Version Before Azure Deployment

### ISSUE THREAD

**Issue by czb182** [Azure/azure-functions-core-tools#3328]
I ran into issue with newly deployed Azure Function Host 4.17.3 in production.  I never ran into issue locally because core-tools is using older version.  Checking now, core-tools is still using 4.16.5.  Instead of waiting for deployment to complete for Azure Functions Host to update core-tools, I think you updated core-tools a little before, at least when rollout starts for local testing.

It seems odd that development environment is running an older version than production, when I think it should be the reverse.

**Comment by czb182** [comment]
bump, even there is a way to opt-in to this would be helpful.

It should be easy to defend thought that developers should be hitting new azure functions host before it gets deployed to production.

**Comment by czb182** [comment]
I think 4.20.0 is rolling out now, can core-tools be updated to that version?

**Comment by czb182** [comment]
4.21.0 out now

**Comment by czb182** [comment]
i see now.
azurefunctions: 4.24.3.21050

Would like to update my identity.web library to newer version, as 4.23.3 supports identitymodel 6.31, but core tools is only at 4.24.0.

Please update to 4.24.3.

I still find it odd that production deployments long before we get them to developer machines

**Comment by khkh-ms** [comment]
We continuously update core tools with the latest version of host. The current version of core tools uses the latest host as well.
