### ISSUE TITLE
When installing Azure Functions Core Tools under latest Node.js version, the extracted files are corrupt

### ISSUE THREAD

**Issue by hajekj** [Azure/azure-functions-core-tools#3335]
Underlying issue: https://github.com/ZJONSSON/node-unzipper/issues/271

```
PS C:\Users\hajek> node --version
v18.16.0
```

The issue happens when https://github.com/Azure/azure-functions-core-tools/blob/v4.x/src/Azure.Functions.Cli/npm/lib/install.js is triggered.

**Comment by Charles-Gagnon** [comment]
Started hitting this in our pipelines earlier this week, which corresponds with the agents updating from Node [18.15](https://github.com/actions/runner-images/blob/win22/20230407.1/images/win/Windows2022-Readme.md#language-and-runtime) to [18.16](https://github.com/actions/runner-images/blob/win22/20230417.1/images/win/Windows2022-Readme.md#language-and-runtime)

This results in errors such as this when trying to run func.exe 

`System.ComponentModel.Win32Exception : An error occurred trying to start process 'C:\npm\prefix\node_modules\azure-functions-core-tools\bin\func.exe' with working directory '...'. The specified executable is not a valid application for this OS platform.`

**Comment by trentm** [comment]
I am getting the same in an ubuntu:20.04 Docker container. 
The symptom is that when attempting to run `func start` one gets:

```
/app/node_modules/azure-functions-core-tools/bin/func: 2: Syntax error: Unterminated quoted string
```

Repro:

```
% docker run -ti --rm ubuntu:20.04 /bin/bash

root@2b4ffd338a55:/# apt-get update
...
root@2b4ffd338a55:/# apt-get install -y curl file
...

root@2b4ffd338a55:/# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

root@2b4ffd338a55:/# export NVM_DIR="$HOME/.nvm"

root@2b4ffd338a55:/# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

root@2b4ffd338a55:/# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

root@2b4ffd338a55:/# nvm install 18
...
Now using node v18.16.0 (npm v9.5.1)

root@2b4ffd338a55:/# mkdir app

root@2b4ffd338a55:/# cd app

root@2b4ffd338a55:/app# npm init -y
...

root@2b4ffd338a55:/app# npm install azure-functions-core-tools
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
added 48 packages, and audited 49 packages in 22s
2 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.6.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.5
npm notice Run npm install -g npm@9.6.5 to update!
npm notice

root@2b4ffd338a55:/app# npm ls
app@1.0.0 /app
`-- azure-functions-core-tools@4.0.5095

root@2b4ffd338a55:/app# ./node_modules/.bin/func
/app/node_modules/azure-functions-core-tools/bin/func: 2: Syntax error: Unterminated quoted string

root@2b4ffd338a55:/app# file ./node_modules/azure-functions-core-tools/bin/func
./node_modules/azure-functions-core-tools/bin/func: data
```

**Comment by trentm** [comment]
It works when installed via Node.js v16. Continuing from the same ubuntu:20.04 container from my previous comment:

```
root@2b4ffd338a55:/app# apt-get install -y libicu-dev   # 'func' needs libicu

root@2b4ffd338a55:/app# rm -rf node_modules/ package-lock.json
root@2b4ffd338a55:/app# nvm install 16
...
Now using node v16.20.0 (npm v8.19.4)

root@2b4ffd338a55:/app# npm install azure-functions-core-tools
...

root@2b4ffd338a55:/app# ./node_modules/.bin/func

root@2b4ffd338a55:/app# ./node_modules/.bin/func
Azure Functions Core Tools
Core Tools Version:       4.0.5095 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.5.20396
Usage: func [context] [context] <action> [-/--options]
...
```

**Comment by Charles-Gagnon** [comment]
FYI - for anyone else hitting this I was able to fix it by pinning the Node version to 18.15, it seems 18.16+ is where things start breaking

https://github.com/Azure/azure-functions-sql-extension/pull/818

**Comment by KondzioSSJ4** [comment]
If you use `Azure Functions Core Tools` for Azure DevOps build
then you also need to change the path to node modules
because they are no longer in the `/usr/local/lib/node_modules` directory
but it's located in `/opt/hostedtoolcache/node/18.5.0`

so to summarize I needed to add a stage that "updates" npm to 18.5 version like:
```
- task: NodeTool@0
  displayName: 'Use Node 18.5.x'
  inputs:
    versionSpec: 18.5.x
```
and change the path from:
```
/usr/local/lib/node_modules/azure-functions-core-tools/bin/func.dll
```
to
```
/opt/hostedtoolcache/node/18.5.0/x64/lib/node_modules/azure-functions-core-tools/bin/func.dll
```

**Comment by Charles-Gagnon** [comment]
Yeah, that's an important note. You can get the node modules location by running `npm root -g` or `npm root` (depending on whether you're installing the tools globally or not). 

So what we do for our pipeline is run this and save the output in a var that we use later on when running func.exe

https://github.com/Azure/azure-functions-sql-extension/blob/main/builds/azure-pipelines/template-steps-build-test.yml#L44

This way we're always sure to get the "correct" location of the node modules without having to manually update it if we change the version of Node or the modules location changes for some reason. This is actually needed for hosted Windows agents because they already put the node_modules in a non-standard location by default.

**Comment by trentm** [comment]
The repro shown in https://github.com/Azure/azure-functions-core-tools/issues/3335#issuecomment-1516989124 still fails.  I guess we are waiting for a release of this package after this version: '4.0.5095': '2023-03-27T15:24:07.673Z'

**Comment by trentm** [comment]
Confirmed that azure-functions-core-tools@4.0.5148 fixes the issue for me. Thanks.
