### ISSUE TITLE
Add helper message to CLI when install fails due to non-valid OS

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#334]
Right now if you try to install azure-functions-core-tools on a Mac/Linux (without @core tag) just get a generic error that doesn't work with current os/arch.  Would be awesome if we could front this error with a friendly message that informs them to install via @core tag.  Not sure if that would require significant work, but would help guide users to success.  Open to other thoughts on how to guide users to success.  Already had a PR to update README which I think will help some #333

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still facing the same issue, please reopen
