### ISSUE TITLE
WinGet package ID is wrong

### ISSUE THREAD

**Issue by askor** [Azure/azure-functions-core-tools#3348]
This line and the one below: https://github.com/Azure/azure-functions-core-tools/blob/fd5626550da3e844bba56ca9000462726003bf97/README.md?plain=1#L84

Should be 

`winget install Microsoft.Azure.FunctionsCoreTools`

**Comment by c0g1t8** [comment]
Looks like there are multiple PRs addressing this issue: #3292, #3295, #3297, and now #3348.

**Comment by alexmg** [comment]
The PRs mentioned above remain open or have been abandoned due to lack of response. This is an annoying documentation bug that is wasting a lot of people's time and is super simple to fix.

**Comment by Gabriel-Iban** [comment]
It has been corrected.
