### ISSUE TITLE
Timer Triggers at wrong time

### ISSUE THREAD

**Issue by briglx** [Azure/azure-functions-core-tools#337]
I have a timer scheduled for every 12 hours at the 30 min mark. However, the timer is triggered as soon as I start a debug session

```
[FunctionName("BillingRequestFunction")]
        public static void Run([TimerTrigger("0 30 */12 * * *")]TimerInfo myTimer, TraceWriter log)
        {
```

![image](https://user-images.githubusercontent.com/1304774/34175540-fc94c2d8-e4b9-11e7-8189-1bb739f0276c.png)

**Comment by ahmelsayed** [comment]
Can you update to latest CLI (with runtime `1.0.11510.0` vs `1.0.11375.0` in the screen shot.

I can't repro this on the latest and it may have been fixed in the runtime between the 2. I'll close this but do let me know if you are still seeing issues.
