### ISSUE TITLE
Please update the docs by showing what is supported vs what is not

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-functions-core-tools#338]
Could you update the #github repo docs (https://github.com/Azure/azure-functions-cli …) by letting devs know what is the diff between runtime x1.0 vs x2.0 since upgrading will break existing non supported programming language functions! 

This happens since i am running python functions that stopped working after installing CLI 2.0 globally!!

Thanks.

**Comment by ahmedelnably** [comment]
the difference is available here
https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions
