### ISSUE TITLE
`func init --docker` generates old version of Dockerfile for C# isolated

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#3384]
Customers are reporting (and I've also verified) that `func init --worker-runtime dotnet-isolated --docker` is generating what seems to be an older Dockerfile:

~~~
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS installer-env

# Build requires 3.1 SDK
COPY --from=mcr.microsoft.com/dotnet/core/sdk:3.1 /usr/share/dotnet /usr/share/dotnet

COPY . /src/dotnet-function-app
RUN cd /src/dotnet-function-app && \
    mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot

# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0-appservice
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:3.0-dotnet-isolated5.0
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
~~~

The in-process version uses the correct base image, but both still reference `mcr.microsoft.com/dotnet/core/sdk:3.1` which I'm pretty sure is no longer supported.

This bug is affecting all customers using func.exe to generate Dockerfiles for their C# isolated worker process function apps.

**Comment by ggailey777** [comment]
Note that I get the same behavior with:
`func init --worker-runtime dotnet-isolated`
then
`func init --docker-only`

**Comment by khkh-ms** [comment]
The issue was addressed in the most recent code tools release.  Can you please upgrade to the latest version of core tools and try again. 

If you are still having the issue. Please run `func -v` on your machine and share the core tools version you are running. Thanks!

**Comment by ggailey777** [comment]
I'm running on 4.0.5148. What's the latest version?

**Comment by khkh-ms** [comment]
Please install the latest version which should be 4.0.5198.

**Comment by ggailey777** [comment]
Verified that 4.0.5.5198 fixes the issue. Thanks @khkh-ms I'll update the container docs to note the func.exe version requirement.
