### ISSUE TITLE
Ability to Publish _Only_ the Settings WITHOUT any Additional Project Dependencies

### ISSUE THREAD

**Issue by jboarman** [Azure/azure-functions-core-tools#339]
The functions cli provides an option to publish settings via a `--publish-local-settings -i` parameter when calling `func azure functionapp publish <FunctionAppName>`.  In Issue #157, this feature was extended to include a `-o --only-publish-settings` option (which remains undocumented except through the unit tests stored in the GitHub source).  However, it still requires some additional project dependencies beyond the settings file to deploy _only_ the settings.

Expected Behaviour
=============

1. The `only-publish-settings` option should be documented alongside the `publish-local-settings` option.
2. The **only** dependency for `only-publish-settings` should be a single `local.settings.json` file from my current folder.

Rational
=====

To better maintain a separation of duties, we need to allow admins a simple way to only deploy the settings that they maintain using their separately-secured version control for configuration management.  This should not have to be synced with the full project source as the whole point is to separate development files from our secrets stored in the config.  However, that separation doesn't mean one doesn't use some form of version control to track configuration.  To support the need for versioned configs, we need a **simple** way to deploy such configs that are stored separately from the source files (_some_ people, aka me, find ARM harder than it needs to be).

Repro
====

1. Create a folder with _only_ a validly-formatted `local.settings.json` file.
2. From that same folder, execute: `func azure functionapp publish <FunctionAppName> -o --only-publish-settings`
3. Check the app settings in the Azure Portal to confirm that they have NOT been updated.

Workaround
========

Perform the above steps from a folder that has the complete project source.  I'm not sure what exactly the dependency is, but that seems to work.  This, of course, is the problem as it defeats the point of separating these artifacts.

**Comment by SteveALee** [comment]
+1 to this see https://github.com/Azure/azure-functions-cli/issues/41

**Comment by jboarman** [comment]
Thanks @ahmelsayed!

Do you have access to update the related docs or readme or some way of documenting this command line option?

**Comment by ahmelsayed** [comment]
I'll update the README here and ask for an update for the docs. 

The CLI should print [this ](https://github.com/Azure/azure-functions-core-tools/blob/7b1dc9154c1f96cca64735b887df7184c8a4abec/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionApp.cs#L48)when running `func azure functionapp`

**Comment by ahmelsayed** [comment]
actually /cc @jeffhollan 

@jeffhollan do you have access to update the docs for the cli on azure.com?
