### ISSUE TITLE
Azure functions cli host doesn't honor content/type in response

### ISSUE THREAD

**Issue by bertique** [Azure/azure-functions-core-tools#340]
I have a function that returns xml.

When running the code in the functions cli localhost, the response header indicates text/plain:

_Date: Mon, 25 Dec 2017 18:03:47 GMT
**Content-Type: text/plain; charset=utf-8**
Server: Kestrel
Transfer-Encoding: chunked_

Once the same code is deployed, the function correctly returns text/xml:

_Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
**Content-Type: text/xml**
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Mon, 25 Dec 2017 18:03:51 GMT_

I'd expect for both places to return a proper text/xml response.

Code for reference:

```
module.exports = function (context, req) {
context.log('JavaScript HTTP trigger function processed a request.');

var xmlContent ='[xml content]';

context.res = {
        status: 200,
        body: xmlContent,
        headers: {
            'Content-Type': 'text/xml'
        },
        isRaw: true
    };
    context.done();
};
```

Any way to force the local functions host to properly return xml?

Edit: This is on
Azure Functions Core Tools (2.0.0)
Function Runtime Version: 2.0.11280.0

**Comment by ahmelsayed** [comment]
Sorry for the delay in replying. I'm unable to repro this on the latest build. 
```
Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0
```

can you update your cli and try it again. I believe there were some fixes in the runtime for javascript functions setting `isRaw` that may have fixed this scenario.
