### ISSUE TITLE
--runtime-version value not respected when creating new function with dotnet-isolated

### ISSUE THREAD

**Issue by pgbfnf** [Azure/azure-functions-core-tools#3406]
**az version
2.50.0**

When creating a new function app (using existing premium plan), I requested:
```
$runtime = "dotnet-isolated"
$runtimeversion = "6"

az functionapp create `
    --name $functionApp `
    --resource-group $resourceGroup `
    --storage-account $storage `
    --plan $premiumPlan `
    --app-insights-key $aikey `
    --functions-version 4 `
    --https-only true `
    --runtime $runtime `
    --runtime-version $runtimeversion `
    --tags $tags
```

Note -this config is listed as supported under  **az functionapp list-runtimes** :
```
      "runtime": "dotnet-isolated",
      "supported_functions_versions": [
        "4"
      ],
      "version": "6"
```

However, after creation, in the Azure Portal, the .NET Version is listed as ".NET Framework 4.8" and NOT ".NET 6 (LTS) Isolated"
I have to manually fix this after creation.

**Comment by sjuarezgx** [comment]
Have you got any news about this issue?

**Comment by AndreaPic** [comment]
I've the same issue with runtime version 8

**Comment by twisha** [comment]
I am having the same issue with runtime version 8

**Comment by Mar8x** [comment]
This is stil a problem since I have the same issue with `azure-cli 2.60.0`. A workaround is to run an addtional command: 
```sh
az functionapp config set  --net-framework-version '8' --resource-group $RESOURCE_GROUP --name $FUNC_NAME
```
However, during execution  it shows the yello text below (updated resource) which is not true since it updates the runtime version successfully:
```
Invalid version:  for runtime dotnet-isolated and os windows. Supported versions for runtime dotnet-isolated and os windows are: ['8', '7', '6', '.4.8']. Run 'az functionapp list-runtimes' for more details on supported runtimes.
```

**Comment by romlodihc** [comment]
Any update from the Microsoft team?

**Comment by surgupta-msft** [comment]
yes, the latest version fix the issue. Tried this with 2.66.0
