### ISSUE TITLE
Exclude files from deployment

### ISSUE THREAD

**Issue by skuntze** [Azure/azure-functions-core-tools#341]
Hi,

I am deploying Azure Functions from VSCode but I usually have files I do not want to be deployed (environment variables for development, linter, ...).

Can I exclude these files from the deployment? Maybe in one of the config files? host.json? function.json?

Project folder:
![1183723](https://user-images.githubusercontent.com/3451457/34407744-5381fbf8-ebc0-11e7-98d3-f76ce129a6e4.png)

Deployed files:
![1183722](https://user-images.githubusercontent.com/3451457/34407732-4e958ca4-ebc0-11e7-9a70-bfbeadcfc100.png)

Thanks in advance!

**Comment by ahmelsayed** [comment]
@skuntze 501144195ea6cccf2cd03576a6d82b74419a25cf adds support for a `.funcignore` file which has the same semantics as `.gitignore` and only takes effect in publishing.

**Comment by petmat** [comment]
The .funcignore file does not seem to work in the core version 2.x? Is there a chance to get it to work with that version at some point?

**Comment by aslanovsergey** [comment]
My .funcignore file doesn't work

I put the name of a class file with my Azure function which I want to exclude from publishing:
MyAzureFunc.cs

**Comment by oreporan** [comment]
is this still not possible??

**Comment by danpetitt** [comment]
My funcignore wasnt working when deploying from VSCode; but also is ignored if you setup a DevOps pipeline which is understandable ... but would be good to be able to set a task to delete the files/folders before creating archive articact

**Comment by slyons** [comment]
I can confirm it works from the command line at least. It's how I'm able to leave out my .python-version file.
