### ISSUE TITLE
CORS issues with POST requests for Azure CLI core (macOS)

### ISSUE THREAD

**Issue by amrfarid140** [Azure/azure-functions-core-tools#345]
## Description:

I am developing an SPA alongise a backend using Azure functions. On Windows, All works fine. On Mac I have CORS problems.
I run the functions app using 
`func host start --cors * `
However I always get this error 
`Failed to load http://localhost:7071/api/login: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`
This issue is only happening at POST requests. GET request worked fine after I explicity add 
`context.res.headers["Access-Control-Allow-Origin"] = context.req.headers.origin;`
## Steps to reproduce:
1.  Run Azure functions host using
`func host start --cors * `
2. Using a different development server running on the same maching make a POST request to and endpoint on the function app.
-------------------------
How can I fix that on my Azure functions app ?

**Comment by bordplate** [comment]
I am experiencing the same issue.

**Comment by roosi** [comment]
Same here.
```
Azure Functions Core Tools (2.0.1-beta.23)
Function Runtime Version: 2.0.11587.0
```

**Comment by ahmedelnably** [comment]
Closing this as stale
