### ISSUE TITLE
authlevel option not being recognized for python model v2 functions

### ISSUE THREAD

**Issue by v-lhoffmann** [Azure/azure-functions-core-tools#3470]
Issue: When creating a new Python function that is using model v2 the --authlevel flag seems to be ignored and asks to manually select an auth level. 

Ex:

func new --name httptest2 --template "HTTP trigger" --authlevel "ANONYMOUS"
Use the up/down arrow keys to select a Auth Level:
FUNCTION
ANONYMOUS
ADMIN

This flag still seems to be working for model v1.

Steps to repro:
Create a new function app using model v2 (now default).
Create a new HTTP trigger function.

Expected outcome: We should not have to select the auth level if it is provided in the command.

**Comment by crvillanueva** [comment]
I'm having the same problem, I tried changing the order of the flags and still the same.

![image](https://github.com/Azure/azure-functions-core-tools/assets/69276157/bc1bc584-2358-49a2-b41b-ae957d5dd00b)

> func --version                                                                               
> 4.0.5390

**Comment by frankbou** [comment]
Same thing here, flag --authlevel is ignored.

func --version
4.0.5441

**Comment by rkochar** [comment]
`--authlevel` is also ignored in v4.0.5455

**Comment by khkh-ms** [comment]
Fix has been merged and will be released on few weeks.
