### ISSUE TITLE
Unable to restart debugging in VS Code

### ISSUE THREAD

**Issue by jantanis** [Azure/azure-functions-core-tools#3518]
I'm able to start debugging a C# based Azure Functions project. But I can't restart debugging or stop/start debugging again.

VSCODE:
Version: 1.84.1 (Universal)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:37:18.666Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

**Comment by khkh-ms** [comment]
We need to transfer it to VS Code.

**Comment by shreyabatra4** [comment]
Transferred to VS Code, https://github.com/microsoft/vscode/issues/204776
