### ISSUE TITLE
[Question] Is it possible to see console log / error during deployment for Functions Node.js v4

### ISSUE THREAD

**Issue by knthmn** [Azure/azure-functions-core-tools#3523]
Currently during deployment the tool fails silently if the Javascript code throws and error. Is it possible to view console.log messages or thrown errors using the tool or on the Portal?

**Comment by ejizba** [comment]
Hi @knthmn, these docs might be helpful: https://learn.microsoft.com/en-us/azure/azure-functions/functions-node-troubleshoot?pivots=nodejs-model-v4#no-functions-found
