### ISSUE TITLE
When using Starlink `func start` is very slow and function endpoint returns 'endpoints_resolution_error: Endpoints cannot be resolved'

### ISSUE THREAD

**Issue by oshihirii** [Azure/azure-functions-core-tools#3524]
**Steps to reproduce:**

 - Be connected to Starlink 
 - Create a local development environment for Azure Functions
 - Create your functions 
 - Run `func start` 
 - Call a local function endpoint  

**Expected Behaviour:**

Local function endpoints start quickly.  

Calling a function endpoint runs my function code.  

**Actual Behaviour:**

Local function endpoints start slowly.  

Calling a function endpoint returns this error:

> endpoints_resolution_error: Endpoints cannot be resolved

**Workaround:**

If I connect to a VPN and run `func start`, it starts quickly and calling the local function endpoints returns no errors. 

I posted on the msal-node repo, as I thought it might be related to that library in particular:   

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6684

When I remove the code that requests a token, i get a successful response.  

As soon as I add the token request back, I get the error.  

But perhaps it is an issue with `azure-functions-core-tools`.  

**Environment:**

package.json:
```js
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "src/functions/*.js",
  "scripts": {
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "@azure/functions": "^4.0.0-alpha.1",
    "@azure/msal-node": "^2.5.1",
    "axios": "^1.6.0",
    "pino": "^8.16.1"
  },
  "devDependencies": {
    "azure-functions-core-tools": "^4.x"
  }
}
```
host.json:
```js
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}
```

Node.js:
```
$ node --version
v18.18.1
```

My function files generally have this structure:
```js
// import libraries, eg:
import { app } from '@azure/functions';
import axios from 'axios';

// add some helper functions here

app.http('MyPOSTHttpTriggerFunction', {
    methods: ['POST'],  
    authLevel: 'function',
    handler: async (request, context) => {

   // get a token to make graph api requests   
   // call some helper functions
   // return a response 

}
```

I am using the Azure Functions v4 programming model, Node.js and ES6 style module syntax etc.

**Comment by khkh-ms** [comment]
It is very difficult to reproduce the issue. It appears to be related to specific ISP as you mentioned that you don't see the issue after connecting to the VPN.
