### ISSUE TITLE
Azure Functions does not recognize Azure Functions Core Tool intallations.

### ISSUE THREAD

**Issue by JulianaRamayo** [Azure/azure-functions-core-tools#3527]
Hello, I'm having troubles trying to use Azure Functions, nonetheless, my system seems to not recognize the installation of Azure Functions Core Tools. I have tried many ways to do this, when I put the `func` in command line, it appears all the information of Azure Functions Core Tools, which means that I have it installed. But when trying to use it in VS Code, it says that I still do not have it. What can I do to solve this problem?
I'm working in Arch Linux, using Node JS 18.

**Comment by khkh-ms** [comment]
Should be transferred to VS Code repo.

**Comment by shreyabatra4** [comment]
Re-created this issue in the VS Code repo - please use that one to track. Thanks!
