### ISSUE TITLE
Unclear error message when creating a Python V2 function

### ISSUE THREAD

**Issue by hallvictoria** [Azure/azure-functions-core-tools#3529]
There are different supported templates for V1 vs. V2 python function apps:
V1:
- Blob trigger
- Cosmo DB trigger
- Durable Functions activity
- Durable Functions entity
- Durable Functions HTTP starter
- Durable Functions orchestrator
- EventGrid trigger
- EventHub trigger
- HTTP trigger
- Kafka output
- Kafka trigger
- Queue trigger
- RabbitMQ trigger
- Service Bus Queue trigger
- Service Bus Topic trigger
- Timer trigger

V2:
- Blob trigger
- CosmosDB trigger
- EventGrid trigger
- EventHub trigger
- HTTP trigger
- Queue trigger
- ServiceBus Queue trigger
- ServiceBus Topic trigger
- Timer Trigger

When running `func init az-functions`, a V2 function app is created. If I then try to create a function using a template that isn't supported yet for V2 apps e.g. `func new --template "Durable Functions orchestrator" --name myFunction`, I get this error:
<img width="731" alt="Screenshot 2023-11-21 163350" src="https://github.com/Azure/azure-functions-core-tools/assets/59299039/edfe569a-c1c1-470f-88d4-30128a2b3b5c">

It's not helpful -- can this be changed to say something like "Template X is not yet supported for the V2 programming model. Please try Y instead." 

**Steps to reproduce:**
1. Install Core Tools v4.0.5455
2. Run `func init az-functions`
3. Run `func new --template "Durable Functions orchestrator" --name myFunction`

**Expected Behaviour:**
Since this template is not yet supported for V2 functions, an error message explaining that would be expected.

**Actual Behaviour:**
An error message saying `Object reference not set to an instance of an object.`

**Comment by khkh-ms** [comment]
Thanks for reporting issue. We are looking into it.

**Comment by khkh-ms** [comment]
https://github.com/Azure/azure-functions-core-tools/pull/3669/files?diff=unified&w=0
