### ISSUE TITLE
func new --authlevel arguments couldn't not be recognized

### ISSUE THREAD

**Issue by roharon** [Azure/azure-functions-core-tools#3533]
When I try this command with `--authlevel`

```bash
func new --authlevel "anonymous" --template "Http Trigger" --name MyHttpTrigger
```

"Select a number for Auth Level" message was presented on Version 4.0.5455 

<img width="1250" alt="image" src="https://github.com/Azure/azure-functions-core-tools/assets/4939738/741b548b-7708-4d6a-8523-7fef73c15a47">

<img width="1250" alt="image" src="https://github.com/Azure/azure-functions-core-tools/assets/4939738/88ce4f5f-18cf-4e1d-975e-a4b2ad183e2d">

**Comment by khkh-ms** [comment]
Duplicated of https://github.com/Azure/azure-functions-core-tools/issues/3470

**Comment by khkh-ms** [comment]
Fix has been merged and will be released on few weeks.
