### ISSUE TITLE
[Function Core Tools] --dotnetIsolated doesn't exist as a worker runtime option to publish from function core tools  

### ISSUE THREAD

**Issue by Justrebl** [Azure/azure-functions-core-tools#3537]
Hello, 

**Context** 
The **_func azure functionapp publish_** command has 2 options to define the function worker runtime of the target Function App : 
- setting FUNCTION_WORKER_RUNTIME setting in local.settings.json in a local dev environment
- Defining the <language> option as a command parameter as _--csharp --typescript --custom_, etc.

**Issue**
Trying to publish a dotnet isolated function app from a github action isn't an option as we need to specify the FUNCTION_WORKER_RUNTIME to be set in the local.settings.json : _There doesn't seem to be any specific func azure functionapp publish_ <language> option for dotnetisolated (while **_--csharp will default to .Net in-process runtime_**, not .Net Isolated).

**Repro Steps**
1. Create a fresh dotnet isolated function app from the function core tools
2. Make sure the proper .gitignore is set (to avoid pushing local.settings.json with the function app code)
3. Push the function app code to a Github repository
4. Create a Github Action that will login to Azure 
5. Add a step to run the following command : func azure functionapp publish <function-app-name>
6. Running the Github action should fail at the func publish step with the following error : 
```
Your Azure Function App has 'FUNCTIONS_WORKER_RUNTIME' set to 'dotnet-isolated' while your local project is set to 'None'.
You can pass --force to update your Azure app with 'None' as a 'FUNCTIONS_WORKER_RUNTIME'
```

**Workaround we found**
Local.settings.json usually isn't versionned, ruling out the option to keep it in the repo next to the function app code.

While creating a github action to deploy the dotnet isolated function app code after IaC completes, we had no other option than copy a local.settings.json.template file (with only the FUNCTION_WORKER_RUNTIME value set to "dotnet-isolated") to a fresh local.settings.json as per github action step so that the dotnet isolated runtime is recognized by the func azure function app publish at run time. 

Feel free to route me to an article in case i missed it.
Kind regards

**Comment by mattchenderson** [comment]
I'm not aware of the command paramters being described for publish. That certainly doesn't show up when I do a `func azure functionapp publish -h` at least, which could be its own issue.

But this would be a pre-publish check where `--force` may be an alternate workaround. And FWIW I typically have `--dotnet-version` attached to the publish command if I'm using that. However, more commonly, I would just use `az functionapp deployment source config-zip` for my purposes, at least. That helps when also standing up the resources, getting that app setting set, etc. That command would not have the same type of pre-publish check.

**Comment by Justrebl** [comment]
Hello @mattchenderson, 
Thanks for your reply and suggestions on using the cli rather than function core tools : will definitely give it a try ! 

I'm wondering if the --force wouldn't impact the host destination as well :
The exception explicits the worker_runtime value change to `None` : It seems like local & AzFunc destination would see a worker_runtime value change.  

Az Function Core Tools publish --dotnet option would probably follow the lifecycle of dotnet in-process retirement and natively point at dotnet-isolated later on ? 

Thanks again, will dig deeper with the az cli option !

**Comment by morten-b** [comment]
I've been running into similar issue and have had success with publishing with:
func azure functionapp publish $name --dotnet-isolated

Though this does not seem to be documented anywhere

**Comment by ja-iris** [comment]
> I've been running into similar issue and have had success with publishing with: `func azure functionapp publish $name --dotnet-isolated`
> 
> Though this does not seem to be documented anywhere

Seems to have to be exactly as you suggest. Have to remove --csharp if you have that already as both together don't work.

**Comment by ikhemissi** [comment]
I also ran into this issue and it looks like `--csharp` will indeed force the runtime to be `dotnet` instead of `dotnet-isolated`.
Using `--dotnet-isolated` fixed the issue for me too but here is the list of options which can be used: https://github.com/Azure/azure-functions-core-tools/blob/fc93cca9640179f934cefb71f641f5e6243a1ac5/src/Azure.Functions.Cli/Helpers/GlobalCoreToolsSettings.cs#L40

**Comment by jhueppauff** [comment]
This behavior really needs improvement. 
If nothing is specified it will not show you the dotnet or dotnet-isolated option:
![image](https://github.com/Azure/azure-functions-core-tools/assets/20532954/1694e7ee-90e2-4362-9bb1-e56760bd5b2c)

And just from the error message you would think that --csharp is the correct option. 
`--csharp`
![image](https://github.com/Azure/azure-functions-core-tools/assets/20532954/4690a959-a3cd-4941-be29-2b22f68a009a)

Looking at the documentation, the language options seem to be also not really described here:
https://learn.microsoft.com/en-us/azure/azure-functions/functions-core-tools-reference?tabs=v2#func-azure-functionapp-publish

**Comment by satvu** [comment]
Closing as fixed in https://github.com/Azure/azure-functions-core-tools/pull/3615.
