### ISSUE TITLE
npm install -g azure-functions-core-tools@4 gives this warning - npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1.

### ISSUE THREAD

**Issue by SiddheshDesai06** [Azure/azure-functions-core-tools#3545]
I am trying to install **Azure Functions Core tools with this command**-  

```js
npm install -g azure-functions-core-tools@4
```

**But receiving this Warning:-**

```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
```

I also tried installing the required debug package to resolve the issue but the warning persists:-

```js
npm install -g debug@4.3.1
npm install -g debug@3.2.7
```

![enter image description here](https://i.imgur.com/nfQ3srL.png)

Note- There are mutliple Open Issues on the same but they are not been resolved- 
https://github.com/Azure/azure-functions-core-tools/issues/3436
https://github.com/Azure/azure-functions-core-tools/issues/3301
https://github.com/Azure/azure-functions-core-tools/issues/3242

**Comment by wells** [comment]
Found the dependency listed in the npm-shrinkwrap.json:
https://github.com/Azure/azure-functions-core-tools/blob/5f073f913376d3e589e1b2e3fcbdd76c67f83d58/src/Azure.Functions.Cli/npm/npm-shrinkwrap.json#L131-L139

Please patch this.

**Comment by svrooij** [comment]
@khkh-ms you seem to be the main contributor to this repository for the last year, can you please run `npm audit fix` next time you're creating an update? That would resolve this issue immediately.

**Comment by Third-party-cookies** [comment]
> Found the dependency listed in the npm-shrinkwrap.json:
> 
> [azure-functions-core-tools/src/Azure.Functions.Cli/npm/npm-shrinkwrap.json](https://github.com/Azure/azure-functions-core-tools/blob/5f073f913376d3e589e1b2e3fcbdd76c67f83d58/src/Azure.Functions.Cli/npm/npm-shrinkwrap.json#L131-L139)
> 
> Lines 131 to 139 in [5f073f9](/Azure/azure-functions-core-tools/commit/5f073f913376d3e589e1b2e3fcbdd76c67f83d58)
> 
>  "node_modules/debug": { 
>      "version": "4.1.1", 
>      "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz", 
>      "integrity": "sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==", 
>      "deprecated": "Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)", 
>      "dependencies": { 
>          "ms": "^2.1.1" 
>      } 
>  }, 
> Please patch this.





https://nodeer.space/questions/warning-for-optimal-performance-it-is-advised-to-update-to-versions-327-or-431-of-npm
