### ISSUE TITLE
Coretools not honoring the --authlevel param

### ISSUE THREAD

**Issue by gavin-aguiar** [Azure/azure-functions-core-tools#3555]
I tried created a python function app with the following command

` func new --name HttpExample --template "HTTP trigger" --authlevel "ANONYMOUS"`
 
and it prompted me to select the auth level

![image](https://github.com/Azure/azure-functions-core-tools/assets/80794152/3e54a9e3-5c6a-4f2c-a1f6-371bfa9e81bd)

Looks like the func new command is not parsing the `--authlevel` param

**Comment by ggailey777** [comment]
Can confirm this command works correctly for Node.js v4.

**Comment by khkh-ms** [comment]
Duplicate of https://github.com/Azure/azure-functions-core-tools/issues/3470

**Comment by khkh-ms** [comment]
Fix has been merged and will be released on few weeks.
