### ISSUE TITLE
Azure Tools outdated

### ISSUE THREAD

**Issue by Wangor** [Azure/azure-functions-core-tools#3563]
Are there any plany to release a new version? The current function host does not run propperly with isolated workers and seems to be fixed with 4.29...

**Comment by robjohnston-iw** [comment]
Support for deploying .NET 8 function apps was fixed around a month ago - it would be good to be able to using this.

See:
https://github.com/Azure/azure-functions-core-tools/issues/3541
https://github.com/Azure/azure-functions-core-tools/pull/3542

**Comment by khkh-ms** [comment]
Closing it because the issue has beeb resolved. It will be releasing in the upcoming core tools release.

**Comment by Wangor** [comment]
Is there a date for it?

**Comment by khkh-ms** [comment]
Let me find the date. I will update here. Thank you!
