### ISSUE TITLE
`NullReferenceException` when `TargetFramework` is only specified in `Directory.Build.props`

### ISSUE THREAD

**Issue by aelij** [Azure/azure-functions-core-tools#3565]
Exception when running `func azure functionapp publish`:

```
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.<RunAsync>d__66.MoveNext() in Azure.Functions.Cli.Actions.AzureActions\PublishFunctionAppAction.cs:line 179
```

**Comment by khkh-ms** [comment]
Thank you for raising it. We are adding the needed validations. At the moment, the target framework needs to be in the project file. We will prioritize on adding the support of `Directory.Build.props` in this scenario.

**Comment by khkh-ms** [comment]
Hi @shreyabatra4, this is a feature request.

**Comment by aelij** [comment]
Even without supporting D.B.props this should not be a NRE. The CLI can suggest specifying the framework version using a parameter.

**Comment by khkh-ms** [comment]
Thank you for suggestion @aelij . We are considering the option until `Directory.Build.props` is fully supported.

**Comment by aelij** [comment]
Here's a way you can get the computed target framework: `dotnet build -getproperty:TargetFramework`

**Comment by gukoff** [comment]
We're seeing the same issue. I took liberty to implement the trick by @aelij , please take a look.
