### ISSUE TITLE
The listener for function was unable to start. Why?

### ISSUE THREAD

**Issue by viveknuna** [Azure/azure-functions-core-tools#357]
I'm getting the following error when I run the azure function from visual studio.

> A ScriptHost error has occurred [1/19/2018 6:40:52 AM] The listener for function 'MyFunctionName' was unable to start. Microsoft.WindowsAzure.Storage: Server encountered an internal error. Please try again after some time.

When I run from the command prompt by running func host start command. I get the following warning. and then it gets stuck on the line 

> Host lock lease acquired by instance ID

.
Warning:

> No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

Azure function version: `azure-functions-core-tools@2.0.1-beta.22`.
I'm using Storage Accounts Blob containers and queues.
I have .net core sdk 1.1.0, 2.0.3, 2.1.2, 2.1.3, 2.1.4 installed on machine.

**Comment by jeffhollan** [comment]
Are you connecting to a development/local storage account? Can you ensure that the storage emulator is started if so?  If not confirming that you are using a general storage account connection string in `local.settings.json`

**Comment by viveknuna** [comment]
Hi @jeffhollan

I'm connecting to Development Storage account, Yes I have checked it that storage emulator is started.

```
{
  "IsEncrypted": false,
  "Values": {
    "ConnectionStrings:Default": "Server=.\\SQLEXPRESS; Database=TestDb; Trusted_Connection=True;",
    "ConnectionStrings:BlobStorageAccount": "UseDevelopmentStorage=true",

    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": "UseDevelopmentStorage=true",
  }
}
```

**Comment by viveknuna** [comment]
FYI.

It was working fine before, But I have got this message in Visual Studio.

>  your license has gone stale and must be updated. Check for an updated license to continue using this product

So I just deleted the %localappdata% and %temp%, then I tried to run Azure function and after this, I have started getting 

> The listener for function was unable to start error

So is it related to my visual studio subscription or I mistakenly deleted any required file? Or is this related to something else?

**Comment by viveknuna** [comment]
@jeffhollan Any updates on this?

**Comment by viveknuna** [comment]
I don't know the root cause of this issue, but I solved it by just copying the same code to a different location. I faced this issue many times and every time I have copied the project to the different location and it always works.

I hope it could help you in resolving the bug.

**Comment by jeffhollan** [comment]
The code sounds like the trigger / bindings / or extensions aren't correctly creating a function.json and not being seen by runtime.  Can you share the code or details on the triggers/bindings being used?

**Comment by pablit07** [comment]
This happens also if somehow our local.settings.json file gets converted to have unix line endings

**Comment by jeffhollan** [comment]
Ah that's very interesting @pablit07.  Do you have a repro? I know a code both on my mac (which I assume would be unix line endings) and windows and don't see this, but wondering if maybe the combo of unix line endings on windows that causes the grief?

**Comment by cocuba** [comment]
in local.settings.json change:

`"AzureWebJobsStorage": "{AzureWebJobsStorage}"`

for
`"AzureWebJobsStorage": "copy the string in the config function on azure"`

and works!
