### ISSUE TITLE
 Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.35.0.0,

### ISSUE THREAD

**Issue by nikvarma** [Azure/azure-functions-core-tools#3577]
It seems that after updating the NuGet package System.IdentityModel.Tokens.Jwt from version 6.30.0.0 to 6.35.0.0, the Azure Function could not load the latest package assembly. You mentioned that there is a need to update the System.IdentityModel.Tokens.Jwt package from 6.30.0.0 since all versions less than 6.33.0.0 have been marked as vulnerable.

I know as workaround adding below tag fix the issue but if there are any plans for a complete fix ?

<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>

```
 Executed 'FuncNameTask' (Failed, Id=3003424d-55e4-477d-bc18-1b27460cb901, Duration=210ms)
[2024-01-24T11:32:16.645Z] System.Private.CoreLib: Exception while executing function: FuncNameTaskFunc: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.35.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

```

**Comment by czb182** [comment]
the functions host has already been updated to resolved, they just need to take it into core tools.  Issue is I think they usually wait for wide rollout before updating core-tools.  It would be better if they could at least release a pre-release version of update core-tools, so can use if needed.  

https://github.com/Azure/azure-functions-host/releases/tag/v4.28.5

**Comment by satvu** [comment]
Closing as fixed with host rollout.
