### ISSUE TITLE
Cannot install azure-functions-core-tools@core behind proxy

### ISSUE THREAD

**Issue by fpaparoni** [Azure/azure-functions-core-tools#358]
Installing both with a Windows and Ubuntu machine I cannot complete the installation. For example on Ubuntu this is the output of installation

> 
> federico@work:~$ sudo npm install -g azure-functions-core-tools@core --unsafe-perm=true --allow-root
> /usr/bin/func -> /usr/lib/node_modules/azure-functions-core-tools/lib/main.js
> /usr/bin/azfun -> /usr/lib/node_modules/azure-functions-core-tools/lib/main.js
> /usr/bin/azurefunctions -> /usr/lib/node_modules/azure-functions-core-tools/lib/main.js
> 
> > azure-functions-core-tools@2.0.1-beta.22 postinstall /usr/lib/node_modules/azure-functions-core-tools
> > node lib/install.js
> 
> Error: connect ECONNREFUSED 93.184.221.200:443
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! azure-functions-core-tools@2.0.1-beta.22 postinstall: `node lib/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the azure-functions-core-tools@2.0.1-beta.22 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

If I try the installation of 1.0.7 version on Windows machine behind proxy there is no problem, with Ubuntu isn't possible because with this version isn't supported

**Comment by chandravd** [comment]
Hello, Are you able to resolve it? I am also facing same issue and wondering what could be options?

**Comment by wayoflife** [comment]
Still an Issue, [install.js]( https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/npm/lib/install.js) contains an http request without consideration for proxy settings

Proposed fix: Check for environment variables and add proxy if available

**Comment by SoucianceEqdamRashti** [comment]
Hello, do you know when this fix will be available? I tried this today and the issue is present. Makes it very hard to test azure core tools behind a corporate proxy.

**Comment by ssougnez** [comment]
Please, do you have any news on that one ? This is really a critical issue...

**Comment by watashiSHUN** [comment]
you can use [chocolatey](https://github.com/Azure/azure-functions-core-tools#windows) for windows and [apt-get](https://github.com/Azure/azure-functions-core-tools#linux) for ubuntu

**Comment by ssougnez** [comment]
Will chocolatey be able to magically use proxy?

**Comment by watashiSHUN** [comment]
based on what I read [here](https://chocolatey.org/docs/proxy-settings-for-chocolatey#system-proxy-settings), it should be:
![image](https://user-images.githubusercontent.com/6531400/39784848-c8350376-52ce-11e8-89a7-5271ada16bbf.png)
but if it didn't work, the doc also has details about how to setup explicitly, let me know if you run into troubles

**Comment by scuderig** [comment]
Hello, even after the changes referenced above, using a corporate proxy this still doesn't work very well, as the proxy replace the SSL certificate and the download attempted in the install.js doesn't work as you can see below:

`> azure-functions-core-tools@2.4.317 postinstall C:\Users\scuderig\AppData\Roami                                    ng\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.4.317/Azure.Funct                                    ions.Cli.win-x64.2.4.317.zip"
using proxy server "http://<myproxy_server>:8080"
Error: unable to get local issuer certificate
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@2.4.317 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@2.4.317 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                    ging output above.

npm ERR! A complete log of this run can be found in:
....`

**Comment by arscek** [comment]
Also having this issue behind a corporate proxy, I need to connect to a public wifi to be able to install it, I see in different threads that this issue is closed, however not sure why are we still having this problem

> Hello, even after the changes referenced above, using a corporate proxy this still doesn't work very well, as the proxy replace the SSL certificate and the download attempted in the install.js doesn't work as you can see below:
> 
> > azure-functions-core-tools@2.4.317 postinstall
> > C:\Users\scuderig\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> > node lib/install.js
> > attempting to GET "https://functionscdn.azureedge.net/public/2.4.317/Azure.Functions.Cli.win-x64.2.4.317.zip"
> > using proxy server "http://<myproxy_server>:8080"
> > Error: unable to get local issuer certificate
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! azure-functions-core-tools@2.4.317 postinstall: `node lib/install.js`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the azure-functions-core-tools@2.4.317 postinstall script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > npm ERR! A complete log of this run can be found in:
> > .... >

**Comment by cnin** [comment]
https://github.com/Azure/azure-functions-core-tools
you might follow the guide to download the executable files directly

**Comment by arscek** [comment]
> https://github.com/Azure/azure-functions-core-tools
> you might follow the guide to download the executable files directly

Thanks I was able to install it,  however when trying to to run a function that hits an azure endpoint, it shows the same error:
```
JavaScript HTTP trigger function processed a request.
[3/6/19 5:06:56 PM] Worker 61498363-6de6-4e13-bacb-5dbfb6a6b079 exited with code 1
[3/6/19 5:06:56 PM] [error] Worker 61498363-6de6-4e13-bacb-5dbfb6a6b079 uncaught exception:  Error: Error: unable to get local issuer certificate
```

Do I need to configure certificates?
