### ISSUE TITLE
Fix winget install Microsoft.AzureFunctionsCoreTools in Readme

### ISSUE THREAD

**Issue by arpadgal** [Azure/azure-functions-core-tools#3596]
Windows 11 
winget install Microsoft.AzureFunctionsCoreTools
No package found matching input criteria.

 winget install Microsoft.Azure.FunctionsCoreTools
 ok

**Comment by alunmj** [comment]
I came here to add this comment - please address this issue - a single "." is missing after "Azure" and before "Functions", otherwise this would be a very simple way to install the Azure Function core tools.

**Comment by reksc** [comment]
@arpadgal many thanks, you saved me a couple of hours!

**Comment by stan-sz** [comment]
See #3348

**Comment by Gabriel-Iban** [comment]
It has been corrected
