### ISSUE TITLE
Add a Contributing.md or instructions within Readme for potential contributors

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-functions-core-tools#360]
Hi Team,

Could you please provided guidance around how we can contribute and what the expectations are for aspiring future contributors? At the moment there's nothing that explains how to build and run the Core tools locally. Some step-by-step instructions would be great

Thanks for the excellent work btw!

**Comment by ahmelsayed** [comment]
@wilsonge added one in #365.
