### ISSUE TITLE
Add .NET Core debugging configuration in launch.json

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-functions-core-tools#361]
At the moment, the Core tools create a `launch.json` file that supports Node and Java debugging out to the box. Since the Core tools v2 support .NET Core and can run cross-plat, I think it's imperative that we added support for .NET Core debugging in `launch.json` out of the box. 

The suggested new `launch.json` should look like this

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Azure Functions",
      "type": "node",
      "request": "attach",
      "port": 5858
    },
    {
      "name": "Attach to Azure Functions (Java)",
      "type": "java",
      "request": "attach",
      "port": 5005
    },
    {
        "name": "Attach to Azure Functions (.NET Core)",
        "type": "coreclr",
        "request": "attach",
        "processId": "${command:pickProcess}"
    }
  ]
}
```

PR on its way....

**Comment by ahmelsayed** [comment]
PR merged
