### ISSUE TITLE
azure-functions-core-tools/releases/latest returns 3.0.* insted of 4.0.*

### ISSUE THREAD

**Issue by atanasTodorovMM** [Azure/azure-functions-core-tools#3629]
[api.github.com/repos/Azure/azure-functions-core-tools/releases/latest](https://api.github.com/repos/Azure/azure-functions-core-tools/releases/latest)

**Comment by victorfrye** [comment]
This is causing some fun issues.  Things like Az Pipelines FuncToolsInstaller@0 when using latest are now pulling the 3.0.5542 version.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/func-tools-installer-v0?view=azure-pipelines

**Comment by victorfrye** [comment]
Seems like this has been fixed now 😁

**Comment by rfontijn** [comment]
This one can be reopened again. Since today  FuncToolsInstaller@0 with 'latest' is not fetching the _real_ latest version.

Because of this:
![image](https://github.com/Azure/azure-functions-core-tools/assets/24569019/30fd5a2b-692f-4104-b1b4-621e3df0ce1c)

**Comment by pieroci** [comment]
Hello any news on it?

**Comment by qingshanJBHIFI** [comment]
Could we have a better way to handle this? It's not good for the v4 users if we have to specify the version in the build pipeline.

**Comment by khkh-ms** [comment]
Closing it as [api.github.com/repos/Azure/azure-functions-core-tools/releases/latest](https://api.github.com/repos/Azure/azure-functions-core-tools/releases/latest) returns 4.x.
