### ISSUE TITLE
Issue during creation of javascript http function

### ISSUE THREAD

**Issue by valereColleville** [Azure/azure-functions-core-tools#363]
I work with the function CLI for few mounths now and everything was fine. But somehow now I am not able to create a new javascript function with the CLI anymore. This is very anoying because I have to teach all the team how to manage and develop this in azure. I absolutly need to create function CLI to be sure that everyone manages the creation in the same way.

Here's my command line:
`func new --language JavaScript --template HttpTrigger --name FUNC_NAME`

That's the CLI return:
```
Select a language: JavaScript
Select a template: HttpTrigger
I can't find template "HttpTrigger" in "JavaScript"
```

Has something changed since I have started to use the CLI? Am I doing something wrong?

**Comment by ahmelsayed** [comment]
Yep, it looks like the template names changed in this PR https://github.com/Azure/azure-functions-templates/commit/624c76d53d234cf8f14e030c367da342cd99b57f#diff-2ee0b71cd67db09e4bb3e06f27321b27 

 so I guess the command now should be 

```
 func new --language JavaScript --template "Http Trigger" --name FUNC_NAME
```

The cli pulls the templates based on a feed, that's based on that templates repo, so changes in the template names would cause a break here.
