### ISSUE TITLE
Your app is currently in read only mode because Elastic Premium on Linux requires running from a package. Click to learn more.  

### ISSUE THREAD

**Issue by kedzior-io** [Azure/azure-functions-core-tools#3633]
Running Azure Functions on EP plan on Linux (.NET 7).

We get this message in Azure Portal:

> Your app is currently in read only mode because Elastic Premium on Linux requires running from a package. Click to learn more.

`Click to learn more` - there is no link in Azure Portal. 

```
FUNCTIONS_WORKER_RUNTIME = dotnet-isolated
WEBSITE_RUN_FROM_PACKAGE = 1
FUNCTION_APP_EDIT_MODE = readwrite
```

Tried both deployment from zip and without through Azure Pipelines. 

Any idea?

**Comment by satvu** [comment]
@kedzior-io Are you still seeing this issue? Can you share a screenshot? We will share this with the portal team.
