### ISSUE TITLE
[V2] remove dependency on ./dotnet from the CLI

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-core-tools#367]
The only scenario that requires `dotnet` executable to be on the machine is that of installing extensions because we just launch [`dotnet add extensions.csproj package <extension> --version <version>`](https://github.com/Azure/azure-functions-cli/blob/89ada273881bc42da7a1f32f496f8e6a552a5c3c/src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs#L55)

this is the only command that would prevent building a self-contained cli

**Comment by mpseidel** [comment]
Any ETA on when this dependency can be removed? 

Running azure functions via node container and need to install extensions so I ran into this.

**Comment by ahmedelnably** [comment]
closing as resolved by extension bundles
