### ISSUE TITLE
Functions not compiled in way ready for local run

### ISSUE THREAD

**Issue by dsyme** [Azure/azure-functions-core-tools#370]
This might be driver error, but I tried to run the Azure Functions in https://github.com/mikhailshilkov/tictactoe locally on OSX.  After compiling 

    cd TicTacToe.Functions
    dotnet build

we have the expected:

```
bin/Debug/netstandard2.0/publish/Landing/function.json
bin/Debug/netstandard2.0/publish/Leaderboard/function.json
bin/Debug/netstandard2.0/publish/Play/function.json
bin/Debug/netstandard2.0/publish/Start/function.json
bin/Debug/netstandard2.0/publish/bin/TicTacToe.Functions.dll
```
and I did this:

    func start --debug VSCode --script-root bin/Debug/netstandard2.0/publish

However the load of the functions failed with complaints about "scriptFile" not being set correctly in the generated scriptFile files.  For example ``tictactoe/TicTacToe.Functions/bin/Debug/netstandard2.0/publish/Start/function.json`` contained

    "scriptFile": "bin/TicTacToe.Functions.dll",

in the functions.json but this path seems to be interpreted locally from the location of ``functions.json``.  Adjusting the generated entry to 

    "scriptFile": "../../bin/TicTacToe.Functions.dll",

seems to progress things.  

If someone on the Azure Functions team could briefly sanity check whether they expect ``functions.json`` scriptFile to be a path relative to the root or relative to the ``functions.json`` that would be helpful.

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still seeing this issue with the latest version of the tools please open a new issue
