### ISSUE TITLE
CDN Zip file missing `https://functionscdn.azureedge.net/public/4.0.1/Azure.Functions.Cli.linux-x64.4.0.1.zip`

### ISSUE THREAD

**Issue by kf6kjg** [Azure/azure-functions-core-tools#3708]
```
$ npm i -g azure-functions-core-tools@4
...
npm error path /usr/local/share/npm-global/lib/node_modules/azure-functions-core-tools
npm error command failed
npm error command sh -c node lib/install.js
npm error attempting to GET "https://functionscdn.azureedge.net/public/4.0.1/Azure.Functions.Cli.linux-x64.4.0.1.zip"
npm error Error downloading zip file from https://functionscdn.azureedge.net/public/4.0.1/Azure.Functions.Cli.linux-x64.4.0.1.zip
npm error Expected: 200, Actual: 404
```

EDIT: Workaround: `npm i -g azure-functions-core-tools@4.0.5801`

**Comment by kf6kjg** [comment]
Looks like a build version issue:
![image](https://github.com/Azure/azure-functions-core-tools/assets/1157224/5155ccb6-3426-4466-b555-d484b38c442e)

**Comment by kf6kjg** [comment]
Looks like a build version issue:
![image](https://github.com/Azure/azure-functions-core-tools/assets/1157224/5155ccb6-3426-4466-b555-d484b38c442e)

**Comment by wpurnahitachi** [comment]
Facing the same error. Any workarounds?

**Comment by kf6kjg** [comment]
Workaround: `npm i -g azure-functions-core-tools@4.0.5801` - also adding to OP.

**Comment by aaronrac** [comment]
looks like this is fixed now

**Comment by kf6kjg** [comment]
Agreed now that latest is 4.0.5858.
![image](https://github.com/Azure/azure-functions-core-tools/assets/1157224/1f76e7cb-b790-4e95-bc23-c8a5b481f869)
