### ISSUE TITLE
.NET8 func start fails when running on Linux host

### ISSUE THREAD

**Issue by fbraam** [Azure/azure-functions-core-tools#3713]
The below check doesn't work, because it is searching for `func.exe`. However on a Linux host, this should be `func`, without the `.exe` part.

https://github.com/Azure/azure-functions-core-tools/blob/69dabe1d59b714159d7ec142cbeddc89978603e9/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L499

**Comment by kshyju** [comment]
Thanks for reporting this issue @fbraam We will try to get a fix out. I will post an update about the progress here.

**Comment by kshyju** [comment]
@fbraam The new version of core-tools has the fix. Please let us know if you run into any other issues. Thanks for your patience.
