### ISSUE TITLE
Version 4.0.5858 has reference with Microsoft.IdentityModel.Tokens Version=7.1.2.0 and my function host can't start

### ISSUE THREAD

**Issue by JSCProjects** [Azure/azure-functions-core-tools#3715]
I've been automatically updated to 4.0.5858, but when running my function host it gives the following error.

[2024-06-24T12:19:41.079Z] Error configuring services in an external startup class.
[2024-06-24T12:19:41.081Z] Error configuring services in an external startup class. System.Private.CoreLib: Could not load type 'Microsoft.IdentityModel.Json.JsonObjectAttribute' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2024-06-24T12:19:42.268Z] A host error has occurred during startup operation '0ab8afa3-1de5-4d45-993b-d936340e3075'.
[2024-06-24T12:19:42.270Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. System.Private.CoreLib: Could not load type 'Microsoft.IdentityModel.Json.JsonObjectAttribute' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Value cannot be null. (Parameter 'provider')
Press any key to continue....

I had to revert back to version 4.0.5801 and it works again.

**Comment by janharders** [comment]
> I've been automatically updated to 4.0.5858, but when running my function host it gives the following error.
> 
> [2024-06-24T12:19:41.079Z] Error configuring services in an external startup class. [2024-06-24T12:19:41.081Z] Error configuring services in an external startup class. System.Private.CoreLib: Could not load type 'Microsoft.IdentityModel.Json.JsonObjectAttribute' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. [2024-06-24T12:19:42.268Z] A host error has occurred during startup operation '0ab8afa3-1de5-4d45-993b-d936340e3075'. [2024-06-24T12:19:42.270Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. System.Private.CoreLib: Could not load type 'Microsoft.IdentityModel.Json.JsonObjectAttribute' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Value cannot be null. (Parameter 'provider') Press any key to continue....
> 
> I had to revert back to version 4.0.5801 and it works again.

Same here. Very annoying. Previous runtime was using 6.35.x version of this assembly and there are breaking changes to 7.1.2.x.

How can I roll back to 4.0.5801 (or basically any specific version)?

**Comment by gpict** [comment]
This broke us as well.

Spent a significant amount of time trying to find how we got 7. packages into our solution as that is a breaking change from 6.

Some warning about breaking changes like this would be greatly appreciated.

**Comment by JSCProjects** [comment]
@janharders I located the location where func.exe is stored, made a backup of the files and did a simple xcopy deployment in the same directory

**Comment by janharders** [comment]
> @janharders I located the location where func.exe is stored, made a backup of the files and did a simple xcopy deployment in the same directory

@JSCProjects: Thx. I figured out that (on windows) that there is a file '...\AppData\Local\AzureFunctionsTools\Tags\v4\LastKnownGood-v2167102' that points to the actual version of the local runtime to be used. I changed the content from '4.82.0' to '4.75.1' (which I still had installed in '...\AppData\Local\AzureFunctionsTools\Releases\4.75.1'). Worked for me.

**Comment by janharders** [comment]
@kshyju I can see this was introduced in #3680 as the reference to Microsoft.IdentityModel.JsonWebTokens and System.IdentityModel.Tokens.Jwt changed from 6.35.0 to 7.1.2. Unfortunately this breaks existing projects (.NET6 / in-process) in my case.

I was able to also update the packages in my solution and that solved the issue. But that might be not an option for other projects.

**Comment by mrebuffet** [comment]
We are also impacted by this in our local development environment.
Thanks for raising this issue and providing a temporary fix @janharders & @JSCProjects. 

Hey Azure team, any chance that this change also starts impacting our hosted Functions Apps? 
We have planned to upgrade all of them to .NET8 in the next few weeks. 
Is there any official documentation about upcoming changes we could follow to prevent this in the future?

**Comment by sec** [comment]
Also affected by this. Can't find any info how to target specific runtime version while doing local work - don't want to mess up with folders.

Is there any way to overcome this or when is fix planned?

Hope this won't get rolled out to Azure without proper fix :D

**Comment by Derek-Frazier** [comment]
I'm also affected by this. Is there a way to specifically target 4.75.1 locally?

**Comment by janharders** [comment]
> > @kshyju I can see this was introduced in #3680 as the reference to Microsoft.IdentityModel.JsonWebTokens and System.IdentityModel.Tokens.Jwt changed from 6.35.0 to 7.1.2. Unfortunately this breaks existing projects that are using previous versions of theses packages (.NET6 / in-process) in my case.
> > I was able to also update the packages in my solution and that solved the issue. But that might be not an option for other projects.
> 
> I wouldn't advise you to go from 6 -> 7 without any proper tests and testing! There is a lot changed in 7 which isn't visible directly. You WILL get in trouble at runtime is my experience. My kata is leave all version 7 packages OUT of my assemblies and when I got the time I migrate directly to v8 host per host.

@JSCProjects: We did not do any updates in our solutions. I have a running .NET6 function that was just breaking due to the updated assemblies in the local function runtime. There is nothing I could do about it (except actually _doing_ a change an update my packages to also use the Microsoft.IdentityModel.JsonWebTokens in V7.x.

**Comment by gpict** [comment]
> I'm also affected by this. Is there a way to specifically target 4.75.1 locally?
@Derek-Frazier 

The tools being referenced will live here:
Users\[you]\AppData\Local\AzureFunctionsTools

In the tags folder you will find a file under v4 named: LastKnownGood-xxxxxxx

If you open that file you will likely see 4.82

Replace that number with the number you want to run.  Don't delete the 4.82 folder in releases otherwise Visual Studio will download it again and overwrite the number in the tags folder.  

On opening Visual Studio appears to do a check to see if there are any new tools and if so will update the number in that file with the newest version.  All to say, if you break again, this is likely what happened.

Hopefully the team here fixes the code as this is a very frustrating developer experience.

**Comment by fabiocav** [comment]
Thank you for reporting this.

An update to address this issue will be out as soon as possible.

To alleviate some of the concerns above, this will not have any impact on hosted applications. The impact here is to the local (Core Tools) experience only.

Thank you for the patience as we get a hotfix out.

**Comment by ShanQincheng** [comment]
as **janharders** mentioned above, change the version number from 4.82.0 to 4.75.1, solved my problem as below. Thanks a lot!


> Error while attempting to validate token: System.AggregateException: One or more errors occurred. (IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0/.well-known/openid-configuration'. Will retry at '27/06/2024 1:36:27 AM +00:00'. Exception: 'System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx'.

**Comment by CrazyTim** [comment]
I spent half a day trying to rollback to `4.0.5801` on macOS using Rider or homebrew with no luck. Anyone figure that out how to do it in macOS?

**Comment by mattchenderson** [comment]
[Version 4.0.5907](https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.5907) is out and should address this.

If using Visual Studio, it should update automatically upon startup, but in case anyone needs the instructions to force that:

1. Navigate to **Tools > Options**, choose **Azure Functions** under **Projects and Solutions**.
1. Select **Check for updates** and install updates as prompted.

**Comment by fabiocav** [comment]
As mentioned by @mattchenderson , the fix has been released.

Thank you again for reporting and for the patience while we got a fix out!
