### ISSUE TITLE
func.exe output window doesn't update unless I press a key...

### ISSUE THREAD

**Issue by elucidsoft** [Azure/azure-functions-core-tools#373]
For some reason I noticed the output window stops updating unless I press space-bar or some key in it, then it starts updating again.  For instance, if I have a timer function that is set on a 15 second interval, sometimes I will see it run the timer every 15 seconds. Other times I will see it run it once, then appear to do nothing, on closer inspection if I hit a key it appears to keep going.  

Why is it pausing like this?

**Comment by ahmelsayed** [comment]
I'm not sure what could cause that. by any chance do you have something highlighted in the console? windows console would block stdout if you have anything highlighted
