### ISSUE TITLE
FunctionApps in .net will not build, start or publish after the first build 

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-core-tools#3742]
Now that I am using the new Core Tools v `4.0.5801` plus .NET 8, I'm finding that you can only build once, and after that `func start` and `func publish` will no longer work due to what looks like a dotnet build error.  

Error:
`Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2`

Workaround:
delete /bin and /obj in the folder

I feel this is a **regression** in behavior because I never experienced this with prior core tools and .NET 6.

Repro:
1. clone this very simple [.NET 8 Function sample](https://github.com/paulyuk/securefunction101)
2. follow steps 1-3 in the readme to establish valid local.settings.json and `func start`
3.  `func start` a second time

Error:
`Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2`

Impact:
This is impacting a number of inner loop flows, samples, `azd package` and `azd up` and CI flows.  It's unreasonable to have to delete /bin and /obj after every build or start IMO.  

Other notes:
what is strange to me is `dotnet build` never hits this issue.  Usually I think of a `func start` functionally doing a `dotnet build` first, and I use that to rule out underlying build problems on dotnet side.

**Comment by paulyuk** [comment]
Looks similar to [#3594](https://github.com/Azure/azure-functions-core-tools/issues/3594)

**Comment by paulyuk** [comment]
Please feel free to close this and dupe it to original issue https://github.com/Azure/azure-functions-core-tools/issues/3594

**Comment by satvu** [comment]
Closing as duplicate
