### ISSUE TITLE
Add parameter for authorization level to "func new"

### ISSUE THREAD

**Issue by snobu** [Azure/azure-functions-core-tools#375]
I believe it would be handy to have an `--authlevel` to control `authLevel` as it's written to `function.json`.

For example:

```bash
$ func new --language JavaScript --template HttpTrigger \
           --name HttpTriggerJavaScript --authlevel anonymous
```

produces

`function.json`:
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
 ...
```

An extra neat touch would be to mention  _function and admin level have no effect when running locally_ in the usage output (when running `func` with no parameter):

```
$ func
                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0
Usage: func [context] [context] <action> [-/--options]

...
Actions:
new     Create a new function from a template. Aliases: new, create
    --language [-l]    Template programming language, such as C#, F#, JavaScript, etc.
    --template [-t]    Template name
    --name [-n]        Function name
    --authlevel [-a]   Authorization level (anonymous, function, admin)
                       [!] Note that authorization level has no effect when
                       running the function locally.
```

**Comment by ggailey777** [comment]
@snobu I agree that this is totally needed, especially for our quickstart documentation. 
@ahmelsayed how to we get this feature work prioritized?

**Comment by snobu** [comment]
I can take a shot at this.

**Comment by jeffhollan** [comment]
@ggailey777 I agree this is a really important thing. Was just an ask that when we do this we add a blurb similar to the VS Code one so folks know doing it this way will make it anonymous and link to somewhere they know how to opt back in.

**Comment by snobu** [comment]
I have already completed some work on implementing `--auth`, seems to work out fine (hooks in before function.json is written to disk and changes authorization property on the fly),

however...

Every line of code i'm writing seems to be all kinds of wrong since i'm mixing template specifics with tooling internal logic, which in my opinion should not mix (separation of concerns and all that).
Secondly, authLevel only applies to HTTP trigger templates, which is what, one per language? Should we really have code in that deals with edge cases?

Maybe we should just have a second HTTP trigger template for anonymous authorization instead?

Not sure if i should continue this path. Need some input.

**Comment by ggailey777** [comment]
+ @anthonychu for awareness.

**Comment by fabiocav** [comment]
Adding to sprint 81 for assignment

**Comment by anthonychu** [comment]
@ggailey777 I think we can start updating the quickstarts with this now.
