### ISSUE TITLE
Permission denied when running "func start" on .NET 8 in-process Function on Ubuntu 24.04

### ISSUE THREAD

**Issue by gabrielweyer** [Azure/azure-functions-core-tools#3766]
- .NET SDK: 8.0.107
- Azure Function Core Tools: 4.0.5907
- Ubuntu 24.04 (WSL but same issue was experienced using GitHub Actions)

When I run `func start` I get the below error:

```plaintext
Failed to start the in-process model host. An error occurred trying to start process '/usr/lib/azure-functions-core-tools-4/in-proc8/func' with working directory '/home/gabriel/MyProjFolder/bin/output'. Permission denied
```

Steps taken:

1. `func init MyProjFolder --worker-runtime dotnet`
2. `cd MyProjFolder/`
3. `func new --template "Http Trigger" --name MyHttpTrigger`

I added `FUNCTIONS_INPROC_NET8_ENABLED` to `local.settings.json`:

```json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet",
        "FUNCTIONS_INPROC_NET8_ENABLED": "1"
    }
}
```

I updated the project to target .NET 8:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.4.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

I'm able to run an in-process .NET 8 on Windows using the Azure Function Core Tools and on a Windows Function App.

**Comment by vfrrjq** [comment]
I have the same problem with the same versions of .NET and Azure Function Core Tools on my Mac.

Any luck funding solution to this anyone?

**Comment by qng5150** [comment]
same here

**Comment by kshyju** [comment]
Thanks @gabrielweyer We will investigate and share an update on this thread.
.

**Comment by mmowry-accuity** [comment]
Same here

**Comment by melvinvandenbout** [comment]
same here.

**Comment by RickDMyers** [comment]
Using chmod on in-proc8/func helped get past the permissions problem.  However, my visual studio code fails to attach.

Now that it compiles and runs, how do you debug?

**Comment by joserhonFA** [comment]
I was able to fix the permissions problem as well using `chmod +x`, but the function never starts now. When I use `func host start` I don't get any error message it just exits execution:
<img width="631" alt="Screenshot 2024-08-15 at 15 14 02" src="https://github.com/user-attachments/assets/cd3472fa-a83f-4bc0-b9c4-d26f46741b35">

When I start the debugger (f5), it builds, but the nothing happens until I get a timeout error saying: "Failed to detect running Functions host within 60"seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting." 

**This behavior is even happening with new functions I created to test .net8 using the in-process model**

I have Sonoma 14.5 macOs and I'm using:
- NET SDK: 8.0.303
- Azure Function Core Tools: 4.0.5907

**Comment by essmd** [comment]
@joserhonFA 
i have exactly the same behavior. i got it to build successfully using chmod but i get exactly the same result and output. Like a simple build only.

- .NET SDK 8.0.400 (latest)
- Azure Function Core Tools (4.x, latest, clean download and installed)
- MacBook Pro, M3, Sonoma

**Comment by Doo-Santi** [comment]
> @joserhonFA i have exactly the same behavior. i got it to build successfully using chmod but i get exactly the same result and output. Like a simple build only.
> 
> * .NET SDK 8.0.400 (latest)
> * Azure Function Core Tools (4.x, latest, clean download and installed)
> * MacBook Pro, M3, Sonoma

what worked for me was changing the local.settings.json file. Try having only 
{
    "IsEncrypted": false,
    "Values": {
      "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    }
}

**Comment by essmd** [comment]
@Doo-Santi We want to run the functions as „in-process“ (dotnet). Using your settings will run the functions in „isolated“ mode (dotnet-isolated). I will try it anyway, to confirm it still works in isolated mode. Thanks!

**Comment by joserhonFA** [comment]
> > @joserhonFA i have exactly the same behavior. i got it to build successfully using chmod but i get exactly the same result and output. Like a simple build only.
> > 
> > * .NET SDK 8.0.400 (latest)
> > * Azure Function Core Tools (4.x, latest, clean download and installed)
> > * MacBook Pro, M3, Sonoma
> 
> what worked for me was changing the local.settings.json file. Try having only { "IsEncrypted": false, "Values": { "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated" } }

This doesn't work. My function use the **in-process** model and I migrated to .net8 but still using the in-process model

**Comment by essmd** [comment]
I got it working for me, its a very inconvenient workaround but it works. Maybe it helps anybody in the meantime.
I am using a MacBook Pro M3, Sonoma 14.3

1. Checkout the source code for core tools.
2. Build and publish the source (command has been copied from repo build script, but -f net8.0 was required to add due to an error)
3. Use the manually built core tools cli to run your functions project

```
cd your-dev-folder
gh repo clone Azure/azure-functions-core-tools
cd azure-functions-core-tools

dotnet publish src/Azure.Functions.Cli/Azure.Functions.Cli.csproj -f net8.0 --runtime osx-arm64 --output /tmp/cli

cd your-functions-project-root
/tmp/cli/func start
```

**Comment by RickDMyers** [comment]
I tried the suggested workaround on my MacBook Pro M2 Somona 14.6.1

It worked, I started 'tmp/cli/func start' then used the command pallet to "Debug: Attach to .Net 5+ or .NET core process" and selected the running "func" application.

To make debugging easier, I updated my Visual Studio Code Configuration and set the "Azure Function Func Cli Path"
setting to "/tmp/cli/func".  Visual Studio Debug with then work from "Run/Start Debugging" menu.

**Comment by despian** [comment]
I managed to get this working by re-signing the func binary using the codesign utility after updating the permissions.

First you need to generate a self-signed cert for code signing (details [here](https://www.jpatrickfulton.dev/blog/2023-07-08-fix-csharp-macos-debugging/)) then:

```
cd /opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.6280/in-proc8
chmod +x func
codesign --remove-signature func
codesign -s my-codesign-cert func
```
@kshyju the latest release doesn't seem to include this hotfix. When will it be released?

**Comment by RHangal** [comment]
> I managed to get this working by re-signing the func binary using the codesign utility after updating the permissions.
> 
> First you need to generate a self-signed cert for code signing (details [here](https://www.jpatrickfulton.dev/blog/2023-07-08-fix-csharp-macos-debugging/)) then:
> 
> ```
> cd /opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.6280/in-proc8
> chmod +x func
> codesign --remove-signature func
> codesign -s my-codesign-cert func
> ```
> 
> @kshyju the latest release doesn't seem to include this hotfix. When will it be released?

This solution worked for me, thank you

**Comment by jvmlet** [comment]
Getting the same error when running `func` in docker image (based on `ubuntu:20.04`) with installed   `4.0.6610`  core tools :

````
Failed to start the inproc8 model host. An error occurred trying to start process '/usr/lib/azure-functions-core-tools-4/in-proc8/func' with working directory '/azp/_work/1/s/MY_PORJECT/bin/Release/net8.0'. Permission denied 
````

**Comment by gabrielweyer** [comment]
Same issue is happening on **Ubuntu 22.04** as well since the release of `4.0.6610`. Luckily the above mentioned fix applies:

```shell
sudo chmod +x /usr/lib/azure-functions-core-tools-4/in-proc8/func
```

**Comment by despian** [comment]
Just updated to func tools 4.1.0 on MacOS, and it seems the executable flag issue is back (or perhaps the fix is still not merged).

**Comment by mfamphlett** [comment]
On 4.5.0 now, and this is still a problem. I have to manually change the executable permission and re-sign the bin every time I update.
