### ISSUE TITLE
Low speed du to dryIoc

### ISSUE THREAD

**Issue by bhugot** [Azure/azure-functions-core-tools#3772]
### Version

All versions

### Description

Due to the usage of dryIoC the performance are really bad when function need to inject dependency (more dependency lead to less request per second).

Since https://github.com/Azure/azure-functions-host/commit/f293bbe066a68eb40e8395161f2935e50344f4de , dryIoc is no more used and performance are improved I did a test went from 20 request/s to 4000 request/s

Any ETA on using last version of Microsoft.Azure.WebJobs.Script.WebHost.

Regards

### Steps to reproduce

- run `winget install k6 --source winget` in a non-elevated shell
Create an http function like this:

```csharp
public class PerfTests
{
    public PerfTests(
        /* Add all the dependencies relevant for your test here. */)
    {
    }

    [FunctionName("PerfTest")]
    public void Run([HttpTrigger("get", Route = "perfs")] HttpRequest req)
    {
    }
}
```
Create a script.js file
```js
import http from 'k6/http';
import { sleep } from 'k6';

export default function () {
  http.get('http://localhost:7071/perfs');
}

```
run the test
```cmd
k6 run --vus 20 --duration 5s script.js
```

**Comment by kshyju** [comment]
@bhugot Active work is ongoing to support the functions host runtime version, which utilizes .NET 8 and the .NET dependency injection system. While we don't have a specific ETA to share at the moment, we are aiming for a release within the next couple of weeks.

**Comment by fabiocav** [comment]
@bhugot as @kshyju mentioned, this work is in progress and the updated host will be brought to Core Tools, carrying that change along.

Since this is a host dependency and the work is tracked for the update, I'll close this as it doesn't apply to changes in Core Tools, but don't hesitate to let us know if you have questions/concerns/
