### ISSUE TITLE
func host start stuck and not starting - connect ECONNREFUSED

### ISSUE THREAD

**Issue by clay4megtr** [Azure/azure-functions-core-tools#3778]
### Version

![image](https://github.com/user-attachments/assets/eefedb4c-6e42-4523-ab08-46800aa6fc72)

### Description

![image](https://github.com/user-attachments/assets/56a6ed07-df12-47fa-a958-e4f4c529c984)

### Steps to reproduce

just run `. .venv/bin/activate && func host start `

**Comment by clay4444** [comment]
it works after waiting for a long time...

**Comment by slgray** [comment]
![image](https://github.com/user-attachments/assets/f5a0c7c0-13f1-48b6-88ed-5ade22c2469a)
same here, just create a demo app and run, it sucks forever.

**Comment by surgupta-msft** [comment]
Closing as duplicate - https://github.com/Azure/azure-functions-core-tools/issues/3821
