### ISSUE TITLE
Can't Launch a Remote Debugger: Error parsing debug. Attach a debugger to the host process before running the function

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-functions-core-tools#378]
Hello,
     I'm trying to run the Azure Command-Line tools at the command prompt to then attach a debugger. I am running the latest version of azure-functions-core-tools (1.0.8).

If I run:
func run --debug

Everything runs, but the debugger isn't started. This can be seen by the output:
`Starting Host (HostId=a219990aebcf40e9a7c95cc677b8c872, Version=1.0.11510.0, ProcessId=15280, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)`

If I look up the latest syntax of this command and instead run:
`func run --debug VSCODE`

It errors out with:
`Error parsing debug. Attach a debugger to the host process before running the function`

Can someone please advise on the proper way to use this now in order to attach a remote debugger? This used to work with prior versions of the Azure Functions Command Line Tools, but I'm not sure on the exact version since I just updated to a new laptop.

The way it used to work allowed it to work in various different IDE's. 

e.g. We use WebStorm:
https://stackoverflow.com/questions/41688100/azure-functions-how-to-debug-in-webstorm

**Comment by ggailey777** [comment]
Try running this command then attaching the debugger in VS Code:

    func host start --debug vscode

**Comment by IainColledge** [comment]
> func host start --debug vscode

Same as above Debug=False

**Comment by ahmedelnably** [comment]
Closing as stale, if the error still persist with v2 or v3 of the core tools please open a new issue
