### ISSUE TITLE
Enable create experience for Python functions

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#380]
## Resources
- [Authoring and testing v2 language workers](https://github.com/Azure/azure-functions-host/wiki/Authoring-&-Testing-Language-Extensions)
- [Setting up the development environment](https://github.com/Azure/azure-functions-python-worker/wiki/Setting-up-development-environment)
- [Python Templates](https://github.com/Azure/azure-functions-templates/pull/644)

## User Experience
(func_env) > $ func init app_name

```bash
Writing .gitignore
Writing host.json
Writing local.settings.json
Created launch.json
Initialized empty Git repository in /path/to/app_name/.git/

Select a language:
1. C#
2. JavaScript
3. Python
Choose option: 3
```
(func_env) > $ cd app_name
(func_env) > $ func new
```bash
Select a template:
1. BlobTrigger
2. HttpTrigger
3. QueueTrigger
4. TimerTrigger

Choose option: 2
HttpTrigger
Function name: [HttpTriggerPython]

Writing /path/to/app_name/HttpTriggerPython/__init__.py
Writing /path/to/app_name/HttpTriggerPython/sample.dat
Writing /path/to/app_name/HttpTriggerPython/function.json
```

## Create workflow

On `func init <app_name> --language Python`:

1.  Determine if Python 3.6 or up is installed. 
    _If yes_, print Python version number and proceed.    
    _Else_, prompt the user to install Python 3.6.4 or above to continue.

2. Determine if a virtual environment is currently active. 
    _If yes_, continue. 
    _Else_, prompt the user to create a virtual environment and activate it.

3. Install the python worker and azure functions package.
    ```bash    
    pip install git+git: https://github.com/Azure/azure-functions-python-worker/tree/dev/azure
    ```

**Comment by asavaritayal** [comment]
Revising the issue to fit the new model.  \cc @ahmelsayed

**Comment by ahmelsayed** [comment]
This is done
