### ISSUE TITLE
Dotnet build fails because of WorkerExtensions.csproj in obj folder

### ISSUE THREAD

**Issue by anotherRedbeard** [Azure/azure-functions-core-tools#3811]
### Description

This is related to issue Azure/azure-functions-dotnet-worker#2605 

Description
When I do a `dotnet restore` of a newly created dotnet function the WorkerExtensions.csproj is placed in the obj folder. Then when I attempt to deploy this using `func azure functionapp publish <func-name>` I get the following error:

```bash
Can't determine Project to build. Expected 1 .csproj or .fsproj but found 2
```

### Steps to reproduce

Steps to reproduce
- Remove bin/obj folders
- Perform `dotnet restore`
- Notice that the `WorkerExtensions.csproj` file is put in the `obj` folder.

**Comment by kshyju** [comment]
@anotherRedbeard The latest version of core tools addresses this issue. Please upgrade to that version. Thanks for your patience.

https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.6280

**Comment by anotherRedbeard** [comment]
> @anotherRedbeard The latest version of core tools addresses this issue. Please upgrade to that version. Thanks for your patience.
> 
> https://github.com/Azure/azure-functions-core-tools/releases/tag/4.0.6280

Thanks @kshyju I'll check it out and close the issue!

**Comment by anotherRedbeard** [comment]
Hmmm...looks like I can't get the latest with brew?

```sh
| => brew install azure-functions-core-tools@4
Warning: azure/functions/azure-functions-core-tools@4 4.0.5907 is already installed and up-to-date.
To reinstall 4.0.5907, run:
  brew reinstall azure-functions-core-tools@4
```

**Comment by anotherRedbeard** [comment]
Looks like it must have been a timing issue on getting the latest. I am now on the latest and it's working as expected. Thanks for the quick turnaround!!

```
=> func --version
4.0.6280
```

**Comment by anotherRedbeard** [comment]
Looks like it must have been a timing issue on getting the latest. I am now on the latest and it's working as expected. Thanks for the quick turnaround!!

```
=> func --version
4.0.6280
```
