### ISSUE TITLE
Create a custom .NET host which will launch the appropriate func exe, for visual studio use case

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-core-tools#3814]
### Description

Build a custom .NET host, similar to the .NET isolated placeholder, that uses local.settings.json and the value defined in `FUNCTIONS_WORKER_RUNTIME` to select the appropriate version of the func executable.

The package will include two versions: .NET 8 in-process and .NET 6 in-process func executables. 

Only 64-bit scenarios will be supported, enabling the use of AOT for building the custom host. The func exes should not be self-contained.

**Comment by mattchenderson** [comment]
This work was completed in https://github.com/Azure/azure-functions-core-tools/pull/3831
