### ISSUE TITLE
VS tooling feed update & validation of custom host

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-core-tools#3815]
### Description

The tooling feed should be updated to move .NET 6 apps to use the in-proc hosts (V0), so those runs are handled by the custom host tracked by #3814

**Comment by mattchenderson** [comment]
Closing in favor of https://github.com/Azure/azure-functions-tooling-feed/issues/563 and https://github.com/Azure/azure-functions-tooling-feed/issues/565. These changes will occur in that repo and may be split across releases.
