### ISSUE TITLE
Update Core Tools to detect unsupported in-proc workloads

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-core-tools#3816]
The Core Tools version using the OOP host should be updated to detect unsupported in-proc scenarios and provide information about the required SDK version (recommend update to latest) if that is triggered.

**Comment by mattchenderson** [comment]
This work should follow https://github.com/Azure/azure-functions-vs-build-sdk/issues/657

**Comment by mattchenderson** [comment]
Specifically, this should be for the versions distributed to VS which are used by the isolated worker model as well. This change should not be present in the versions that are in-proc only. It is also not needed for scenarios in which the Core Tools is to be run via the command line or in Visual Studio Code, for example. In those cases, we can use the standard probing logic and launch the right version as a new process.

The message should include a short link which will be updated to point at the documentation tracked by #3817. Proposed: https://aka.ms/functions-core-tools-in-proc-sdk-requirement

This detection could be introduced into the current Core Tools structure, and it likely should be from a release tactics perspective. We will need to make sure it is preserved going into the new structure (#3744), though.
