### ISSUE TITLE
Python Azure Functions cannnot be run on M1 Mac OS with ESET installed.

### ISSUE THREAD

**Issue by IkeuchiRyuto** [Azure/azure-functions-core-tools#3820]
### Version

4.0.5907

### Description

When I install ESET(Security Tool) on M1 MacOS PC, the "func start" command fails locally.
This only occurs with Python. It works fine With JavaScript.

Since I installed ESET(Security tool), I thought it might be something network-related that was blocking it, but based on the content of the error and the fact that it works with JavaScript, that doesn't seem to be the case.

Once I uninstalled ESET, it works fine locally.

### Steps to reproduce

# Environment
・Python 3.11.3
・azure-functions-core-tools 4.0.5907（brew install）

# Setup
1 . python -m venv .venv
2 . source .venv/bin/activate
3 . pip install -r requirements.txt
4 . func start

<img width="1088" alt="スクリーンショット 2024-09-12 1 46 46" src="https://github.com/user-attachments/assets/c66bb11f-074d-4bc6-bb05-537efdecb1e5">

**Comment by surgupta-msft** [comment]
@vrdmr can you help with this issue?

**Comment by IkeuchiRyuto** [comment]
The problem was solved after updating the Mac OS.
