### ISSUE TITLE
Wrong error message when publishing

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-core-tools#3822]
### Version

```
PS E:\> func --version
4.0.6280
```

### Description

I've tried to publish using the latest version of the Core Tools. Here is error message with the issue:

```
Your Azure Function App has 'FUNCTIONS_WORKER_RUNTIME' set to 'dotnetIsolated' while your local project is set to 'None'.
You can pass --force to update your Azure app with 'None' as a 'FUNCTIONS_WORKER_RUNTIME'
```

The issues are the following:
1) We should not force 'None' as a valid value
2) 'dotnetIsolated' should be 'dotnet-isolated'

### Steps to reproduce

Please note that I did not have a `local.settings.json` file.

command: `func azure functionapp publish <AppName>`

**Comment by fabiocav** [comment]
@mattchenderson will provide additional details on this

**Comment by umangsriv** [comment]
@fabiocav @mattchenderson Could you please provide an update on the above query?
