### ISSUE TITLE
Can't set headers on response (2.0.1-beta.22)

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-functions-core-tools#386]
azure-functions-core-tools@2.0.1-beta.22
JavaScript HttpTrigger 
Local function emulator on Windows 10 x64

I am trying to set a response header in order to flag the length of the result set to our front end code.

This method throws an error:

```
context.res = {
  "headers" : { "length": response.length },
  "body": response
};
```

> invocationResponse.outputData.data.http.headers: string{k:string} expected

This method doesn't throw an error, but adds no header to the response:

`context.res.setHeader('length', response.length);`

**Comment by pilot4u** [comment]
I'm struggling with this issue as well, has anyone managed to overcome this issue?

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2768
