### ISSUE TITLE
Use of IConfiguration instead of System.Configuration?

### ISSUE THREAD

**Issue by MV10** [Azure/azure-functions-core-tools#387]
Will Functions config eventually migrate to the `Microsoft.Extensions.Configuration` namespace and related extensions? (Better yet, have I overlooked a V1-Functions-friendly way to get `IConfiguration` today?)

We have numerous netstandard2.0 libraries that set themselves up by accepting (or injecting) `IConfiguration` so this would be important to us for consistency reasons. Additionally, we depend on third-party libraries that expect `IConfiguration`. 

Consequently we'll end up writing our own package to obtain and cache our settings this way, but we want to be on the lookout if this is somewhere on the horizon for Functions.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2437
