### ISSUE TITLE
Azure Function .NET CORE (Application Insights Custom Telemetry Support)

### ISSUE THREAD

**Issue by tsmccartan** [Azure/azure-functions-core-tools#391]
What is the support for Application Insights with Azure Functions and .NET CORE?  I have created an Azure Function for .NET Core, I did configure it to Application Insights and it is gathering telemetry.  But when I try to create my own metrics using the below code, it always throws an error saying it could not load file or assembly.

Is the below supported, or is it just basic integration using log.info("Message....");  <-- This works

I have added all the nuget packages for ApplicationInsights 2.5.1

Code that causes the errro:
var telemetryClient = new TelemetryClient();
telemetryClient.InstrumentationKey = Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY");

Exception:
FileLoadException: Could not load file or assembly &#x27;Microsoft.ApplicationInsights, Version=2.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&#x27;. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

**Comment by krlm** [comment]
@tsmccartan try to downgrade Application Insights to 2.4.0, I've encountered the same problem and downgrade solved it for me.

**Comment by ahmelsayed** [comment]
This should be fixed in the latest dotnet core cli. Please give it a try
