### ISSUE TITLE
Disabled property not honored locally

### ISSUE THREAD

**Issue by ssougnez** [Azure/azure-functions-core-tools#396]
Hello,

I have the following function:

```
{
    "disabled": true,
    "bindings": [
        {
            "name": "CalculateDonationPoints",
            "type": "timerTrigger",
            "direction": "in",
            "schedule": "0 * * * * *"
        }
    ]
}
```

However, when I launch `func host start` locally, this function gets executed despites the `disabled` flag. 
I'm using the following version of the package:

Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2767
