### ISSUE TITLE
Cannot install extensions on 2.0.1-beta.23 on Windows

### ISSUE THREAD

**Issue by lucaslra** [Azure/azure-functions-core-tools#397]
Hi,

I have this version installed on my machine (Windows 10 Pro - Insider Preview):

>Azure Functions Core Tools (2.0.1-beta.23)
>Function Runtime Version: 2.0.11587.0 

And whenever I try to install an extension I get this error:

>func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 1.1.0-beta2
```
Value cannot be null.
Parameter name: stream
```

Any Idea what could be causing this issue?
I tried other extension (Graph Extension) and the result was exactly the same...
I have no clue on what is going on.

**Comment by lucaslra** [comment]
I found the cause and created a [PR](https://github.com/Azure/azure-functions-core-tools/pull/398)

I am not sure if the change that caused the issue was intentional, but I think it was not.

**Comment by Bomret** [comment]
This is needed as its currently not possible to install extensions.

**Comment by ahmelsayed** [comment]
Sorry about that. the beta.23 release had to happen from an older fork because the accompanying runtime package was a similar hotfix and master in here had moved ahead. sorry for missing that part, and thanks @lucaslra for fixing that. I'll prepare a new release and let you know once it's out

**Comment by Bomret** [comment]
@ahmelsayed, @lucaslra thank you! 🙏

**Comment by ahmelsayed** [comment]
I just pushed a new update. Sorry for the delay, I was trying to automate the publishing process. But since there seem to be more reports of this issue I ended up just pushing this update.
