### ISSUE TITLE
2.0.1-beta.23 is broken

### ISSUE THREAD

**Issue by snobu** [Azure/azure-functions-core-tools#401]
Probably already a known issue, `2.0.1-beta.23` is broken.

macOS/Linux, Node **8.9.x**:

```
$ func

internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at main (/usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js:12:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/azure-functions-core-tools/lib/main.js:21:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I suggest removing **.23** from `npm` for now to minimize impact.

**Comment by ahmelsayed** [comment]
as mentioned on SO 

`beta.23` does have an issue but `@core` tag should be on `beta.23-1` which should have that issue fixed. 

Try running `npm -g list azure-functions-core-tools` to verify the version you have it should be 

    /usr/lib
    └── azure-functions-core-tools@2.0.1-beta.23-1 

and **not**

    /usr/lib
    └── azure-functions-core-tools@2.0.1-beta.23


Alternatively you can fix `beta.23` by running `sudo chmod 755 $(which func)` 


I'm also preparing a new release due to this [issue](https://github.com/Azure/azure-functions-core-tools/issues/397) and will be released shortly

**Comment by ahmelsayed** [comment]
btw, did you explicitly run `npm i -g azure-functions-core-tools@beta.23`? or how did you end up with 23 and not 23-1?

**Comment by ahmelsayed** [comment]
also I can't unpublish something from npm, but I did add a deprecation message when installing that bad version.

**Comment by ahmelsayed** [comment]
And btw, if you're running on Debian/Ubuntu/Mint, we now have a deb package in the microsoft sources. 
so you can add that and run `apt-get install azure-functions-core-tools` instead of npm. [The instructions are in the README](https://github.com/Azure/azure-functions-core-tools#linux)

**Comment by snobu** [comment]
Hmm.. it is pulling `23-1`, but something's still broken for me,

```
% sudo npm install -g azure-functions-core-tools@core --unsafe-perm true

[==================] Downloading Azure Functions Cli
+ azure-functions-core-tools@2.0.1-beta.23-1
updated 1 package in 11.394s


% func                                                                                                                          ~
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^
Error: spawn EACCES
    at _errnoException (util.js:1022:11)
  ...


% npm -g list azure-functions-core-tools                                                                                    ~
/usr/local/lib
└── azure-functions-core-tools@2.0.1-beta.23-1
```

There could be something screwed up on my Mac from all the install/remove i did.

**Later edit**:
The brew install way works great:

```
% func                                                                                                                          ~
....
Azure Functions Core Tools (2.0.1-beta.23)
Function Runtime Version: 2.0.11587.0
```

Thanks for taking care of this.

**Comment by ahmelsayed** [comment]
hmmm, something is not right. I just tested it on a mac I have at home (at work I usually just test on Windows and Linux) and while it just worked, the resulting file is not what I'm expecting. 
After install is done, [I `chmod 755 /func` executable under the bin folder](https://github.com/Azure/azure-functions-core-tools/blob/c56625ca9ddb2899c5f81ee492cd946424f1c9f1/src/Azure.Functions.Cli/npm/lib/install.js#L47-L51). However running this on my mac

```bash 
> ls -al /usr/local/lib/node_modules/azure-functions-core-tools/bin/func
--wxrw--wt  1 root  wheel  123596 Mar 11 11:05 /usr/local/lib/node_modules/azure-functions-core-tools/bin/func
```

and on linux

```bash
ls -al /usr/lib/node_modules/azure-functions-core-tools/bin/func
--wxrw--wt 1 root root 97408 Mar 10 12:31 /usr/lib/node_modules/azure-functions-core-tools/bin/func
```

while I'd expect it to be 

```bash
-rwxr-xr-x  .....
```

Tbh, first time I learn about `t` permission in file system, I need to read up on that, as well as figure out why it doesn't work on your machine as that's pretty odd to me. 

But at least homebrew works! thanks for confirming that. I would expect more people would be using homebrew for mac, but I'd like to have both distribution channels working eventually.

**Comment by snobu** [comment]
Look at this crazy thing:

```
% sudo node
> var installPath = '/usr/local/lib/node_modules/azure-functions-core-tools/bin'
> fs.chmodSync(`${installPath}/func`, 755)
undefined
// undefined expected - https://nodejs.org/api/fs.html#fs_fs_chmodsync_path_mode


% cd /usr/local/lib/node_modules/azure-functions-core-tools/bin
% ls -l func
--wxrw--wt  1 root  admin  123596 Mar 13 03:16 func
```

The chmodSync has no effect!

**Comment by snobu** [comment]
Ah, the zero is not implicit, `755` is not read as octal that's why you get the sticky bit (t) and the bizarre chmod result.

```
fs.chmodSync(`${installPath}/func`, 0o755);
```
produces:

```
-rwxr-xr-x  1 root  admin  123596 Mar 13 03:16 func
```

Horrible notation and horrible handling of non-leading zero. Sorry Node, but this isn't very Linux...
https://nodejs.org/api/fs.html#fs_file_modes

I'll send a PR.

**Comment by ahmelsayed** [comment]
That's an interesting behavior. Definitely not what I expected looking at the method sig. Thanks @snobu! that explains it to me.

**Comment by ahmelsayed** [comment]
fixed in #403. And I just pushed beta.24

**Comment by cfe84** [comment]
Happened to me again on 2.4.419 in WSL ubuntu 18.04. Fix was to manually `chmod 755 /home/$USER/.nvm/versions/node/`node-v`/lib/node_modules/azure-functions-core-tools/`

**Comment by davidpodhola** [comment]
Same here. Fix:

`chmod 755 /home/$USER/.npm-global/lib/node_modules/azure-functions-core-tools/bin/func`
