### ISSUE TITLE
2.0.1-beta.24

### ISSUE THREAD

**Issue by trevorwang** [Azure/azure-functions-core-tools#404]
Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/Users/trevorwang/.config/yarn/global/node_modules/azure-functions-core-tools/bin/workers/node/grpc/src/node/extension_binary/**_node-v59-darwin-x64_**/grpc_node.node'

But only v57 folders are found in that directory

<img width="404" alt="screen shot 2018-03-14 at 11 44 46 pm" src="https://user-images.githubusercontent.com/121966/37413332-c64835aa-27e1-11e8-9f57-e9b0accf0bd3.png">

**Comment by ahmelsayed** [comment]
What version of node are you running?

**Comment by trevorwang** [comment]
```
node -v
v9.8.0
```

**Comment by ahmelsayed** [comment]
Thanks @trevorwang. I think this is the same as #372. currently only node 8.x would work. I'll leave this open until we have the grpc module for node 9.

**Comment by ahmelsayed** [comment]
Tracked in https://github.com/Azure/azure-functions-host/issues/2758
