### ISSUE TITLE
func azure set-publish-username fails on MacOS

### ISSUE THREAD

**Issue by bedej** [Azure/azure-functions-core-tools#406]
MacBook-Pro:MiscellaneousServices bedejordan$ func azure get-publish-username
Publishing user is not configured. Run func azure set-publish-username <userName> to configure your publishing user
MacBook-Pro:MiscellaneousServices bedejordan$ **func azure set-publish-username bedej**
Enter password for "bedej":
**Unable to load DLL 'kernel32.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)**

Looks like leftover win32 dependencies.

**Comment by ahmelsayed** [comment]
@watashiSHUN I believe this is already done. You can just verify on a linux or mac machine

**Comment by watashiSHUN** [comment]
verified on mac
