### ISSUE TITLE
No app content for custom image on Linux

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#409]
![image](https://user-images.githubusercontent.com/8435148/37561001-ad3f87b8-2a00-11e8-882a-a1681c246e02.png)

`Download app content` downloads an empty zip file, for a custom image on Linux. 

### Repro Setps
I followed the instructions here - [https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image) without any modification.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-ux#2469
