### ISSUE TITLE
Function host slows down localhost considerably

### ISSUE THREAD

**Issue by ethanroday** [Azure/azure-functions-core-tools#410]
Steps to reproduce:
1. Create a new local project with `func init`, then create a sample HTTP-triggered function with `func new`.
2. In the project directory, run `func host start`.

With the function host running, all calls to localhost - no matter the port - seem to be delayed considerably. For example, when I statically serve a directory using `http-server` on, say, port 8080, navigating to `localhost:8080` in a browser - which should be nearly instantaneous - takes several seconds.

I'm running version 1.0.9 of the core tools on Windows 10.

**Comment by ahmedelnably** [comment]
https://github.com/Azure/azure-functions-core-tools/issues/501
