### ISSUE TITLE
Should npm package contain Azure.Functions.Cli.dll?

### ISSUE THREAD

**Issue by SayusiAndo** [Azure/azure-functions-core-tools#414]
Hi All,

Just a quick question because it is not clear. I bumped into [this ](https://github.com/Azure/Azure-Functions/issues/625#issuecomment-355453557) workaround, but I don't have `Azure.Functions.Cli.dll` under the `c:\Users\username\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\` directory where the npm package is stored. However, I assume, Visual Studio installed Azure.Functions.V2.Cli something into the `c:\Users\username\AppData\Local\Azure.Functions.V2.Cli\2.0.1-beta.22` directory where I can find Azure.Functions.Cli.dll file.

  - Is it right this way?
  - Why the workaround assumes Azure.Functions.Cli.dll is part of the npm package?

Thanks

**Comment by ahmelsayed** [comment]
`Azure.Functions.Cli.dll` has been renamed to `func.dll` in 58898f5bf3705df55f5cb9845a0d962b28589d5c
