### ISSUE TITLE
'publish' command hanging

### ISSUE THREAD

**Issue by DavidLudwig** [Azure/azure-functions-core-tools#417]
I have a function app that I've started publishing code to, via the "func" command, as run on MacOS.  It was working for a while, however, it'll now get indefinitely-stuck on its "Uploading archive..." phase.

I am using the following:
- azure-functions-core-tools@2.0.1-beta.24
- MacOS 10.13.3 (High Sierra)
- server runtime: 2.0.1.0 (beta), on Linux host(s)

The command I am running is: ```func azure functionapp publish NAME_OF_APP```

The output looks like the following:
```Publish <path of local project> contents to an Azure Function App. Locally deleted files are not removed from destination.
Getting site publishing info...
Creating archive for current directory...
Uploading archive...
```

Observed behavior: the app sits there, indefinitely.  I typically press Control + C to exit out of it, after a while, sometimes after hours have passed.  No further diagnostic information is displayed, on-screen.

This bug happens to me 100% of the time.  

Publishing to different function apps, including Linux ones, seems to work fine.

I have tried restarting the function app (via the Azure Portal), to no avail.

I've tried running the command with Wireshark running.  Some communication does seem to occur with Microsoft servers, albeit opaquely + encrypted.

Any idea(s) on what's up, or on how to further diagnose this?

Might there be a way to get more diagnostic information from the 'publish' sub-command's execution?

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
