### ISSUE TITLE
Azure Function Using .NET 8 Isolated Worker Fails to Load Functions with func.exe Command

### ISSUE THREAD

**Issue by martinHornacek** [Azure/azure-functions-core-tools#4208]
### Version

Core Tools Version: 4.0.6610
Function Runtime Version: 4.1036.1.23234

### Description

When attempting to run a .NET 8 isolated worker Azure Function using func.exe from the command line, the functions fail to load, even though the application works flawlessly when started through Visual Studio.

My goal is to implement code that programmatically starts an Azure Function locally for integration testing purposes using C#. However, I encountered a roadblock when trying to launch the Azure Function project using the Azure Functions CLI tools (func.exe).

While the function starts up perfectly via Visual Studio's "Start Debugging" (F5), it fails to initialize with the `func start `command. I'm unsure what's missing or misconfigured in the CLI setup.

Please refer to the sample code project published on my GitHub linked in the Steps to reproduce.

Any insights or suggestions to resolve this would be greatly appreciated!

### Steps to reproduce

See my sample project published on GitHub here: https://github.com/martinHornacek/pactflow-azure-function-provider.

Operating system: Windows 11 Enterprise, 64-bit operating system, x64-based processor

1. Create a sample Azure function project using .NET 8 isolated worker model (C# language) with a HttpTrigger endpoint using Visual Studio 2022.
2. Run the Azure function locally on default port 7071 > Start Debugging (F5)
3. The Azure function starts up without any issues, loading the HttpTrigger endpoint.

![Image](https://github.com/user-attachments/assets/604977dc-63bf-4c18-b740-eef8023ef08a)

4. Close the process and open Command Prompt.
5. Change directory to the root folder of the Azure function C# project.
6. Invoke the func.exe located in "C:\Program Files\Microsoft\Azure Functions Core Tools\func.exe" with the following arguments `start --no-build true --port 7071 --functions "GetSampleData"`
7. ISSUE: No functions are loaded. Received message:  **No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).**

![Image](https://github.com/user-attachments/assets/a6a4776c-a042-4225-95b4-68b9a2ea5670)

**Comment by martinHornacek** [comment]
Just to add further details, the local.settings.json file does have the FUNCTIONS_WORKER_RUNTIME set to dotnet-isolated.

![Image](https://github.com/user-attachments/assets/4c0273e3-3d2a-46a5-bf22-74033ee43720)

**Comment by kshyju** [comment]
Can you confirm if everything works as expected when you remove the `--no-build true` option from the `func start` command?

**Comment by martinHornacek** [comment]
Yes, setting the `--no-build` option to `false` or omitting the option completely, builds and runs the function as expected.

Note that this works for me only in the Core Tools version 4.0.6610. I was attempting to start up the function with `--no-build` set to false on the previous version of the Core Tools, but that lead to [this ](https://github.com/Azure/azure-functions-core-tools/issues/3594) issue which is already solved.

So, with the build enabled, it works.
But I don't understand why it doesn't work with  `--no-build` set to true. Even if I run a Rebuild of the whole Visual Studio solution and then run the `func start` from the cmd line with `--no-build` set to true, I get the error.

**Comment by liliankasem** [comment]
The reason is because when `--no-build = false`, we build and set the `CurrentDirectory` to output path of the build (bin/output)

https://github.com/Azure/azure-functions-core-tools/blob/3e421ca6c547c5f35ea61e8ef5a53fb4ef641541/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L678-L680

https://github.com/Azure/azure-functions-core-tools/blob/3e421ca6c547c5f35ea61e8ef5a53fb4ef641541/src/Azure.Functions.Cli/Helpers/DotnetHelpers.cs#L220

When `--no-build = true`, this step is skipped and so the CurrentDirectory never changes, running the host from the root of wherever you are running the `func start` command, so it does not find the job functions.

You can either run func start from `bin/output`

```
dotnet build
cd bin/output
func start --no-build
```

Or, use --prefix to set the output path:

```
dotnet build
cd bin/output
func start --no-build --prefix bin/output
```

**Comment by DavidKessler80** [comment]
You guys really need to document this out on [Azure Functions Core Tools reference](https://learn.microsoft.com/en-us/azure/azure-functions/functions-core-tools-reference?tabs=v2). We probably spent 15 man-hours yesterday wondering why this was happening when "--no-build" was specified. Not until calming down overnight, coming in with a fresh mind, rationlizing what was going on, yanking this source code and digging through everything did I find the condition that blocks the change directory command which was pointed out previously in this thread.
