### ISSUE TITLE
Does the `func new` CLI experience support custom templates ?

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-functions-core-tools#4210]
### Description

If so, how would one author and register a new custom template ?

I would like to promote best practices in my company.
I already implemented a set of `dotnet new` templates that can be instantiated with either Visual Studio or using the CLI.
I would like to use `func new` to add new specific functions in my project.

**Comment by liliankasem** [comment]
We do not currently support custom templates for 'func new'; will flag this for something to consider as we work on refactoring and upgrading Core Tools next year
