### ISSUE TITLE
[Question] - Update VS to latest core tools

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-functions-core-tools#422]
For several reasons, my dev env is broken and I need to work in the latest version, which as the time of posting this is 2.0.1-beta.25.

it works if using npm package and by manually starting the host and attaching to the func.exe process in VS. 

Great, but obviously it's not the most fluid workflow. 

Tried to copy paste contents from 2.0.1-beta.22 to 2.0.1-beta.25 and it does not work.

So my question is. How can I update the tooling without waiting for the update to come to visual studio users?

Cheers!

**Comment by andreujuanc** [comment]
@ahmelsayed Nice try, but it's not working. :(

As soon as I start debugging everything inside  beta.22 folder gets deleted and replaced by the beta22 version of content.

So maybe those files are located somewhere else and VS is replacing them? some sort of fast hash check or something.

Thanks!

**Comment by Mike-EEE** [comment]
I am getting the same thing.  Delete the files and they magically reappear like witchcraft.  I thought MSFT was staying away from this sort of black magic, people.  srsly. 😛

**Comment by Mike-EEE** [comment]
Looks like it's copying from the zip found at `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools Azure\WebJobs\CLI\v2\2.0.1-beta.22`.

Posted a workaround here:
https://github.com/Azure/Azure-Functions/issues/745#issuecomment-378482304

Also, @ahmelsayed ... it appears that Visual Studio is unzipping that file each and every time an F5 is made.  It's a 57MB zip file, so it's pretty considerable?  Can you please verify this and see if it might be possible to NOT do this, as it adds to the overall F5 launch time.

**Comment by Mike-EEE** [comment]
FWIW @ahmelsayed the latest Azure Functions Tools seems to be working as expected now.  The zip file/unzipping process I was experiencing only happens on the first launch.  Subsequent launches appear to not perform this process, so this is a non-issue.  

This new VSIX appears to be RTM as the `beta` folders that were created under the `Azure.Functions.V2.Cli` folder no longer exist, and in fact get wiped out altogether, making `Azure.Functions.V2.Cli` the root/application folder.

In any case, great work, all. 👍

**Comment by andreujuanc** [comment]
Haven't try it yet, but I would love to know what's the update strategy that the tooling is going to have for now on?

Things need to stay in-sync between SDKs and tooling. At least for example not advertising a new version feature without first releasing it's tooling for VS.  That's how I got my initial issue going on.

**Comment by ahmedelnably** [comment]
VS should have the latest versions of the core tools
Closing as fixed
