### ISSUE TITLE
Unhandled exception when starting VS using --debug 

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-core-tools#427]
When I run the following command to start VS debugging on Windows I get an unhandled exception:

    func host start --debug vs

![image](https://user-images.githubusercontent.com/1388263/38471170-5682206a-3b22-11e8-937b-035302256968.png)

In the previous version (2.0.1-beta.23), if I ignored the unhandled exception, I was still able to attach the debugger from VS and it worked. Now in the current version (2.0.1-beta.25) I am not able to attach at all as the exception shuts down func.exe.

In version 1.0.10, I get the same behavior as 2.0.1-beta.23--continuing the unhandled exception and it still works.

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
