### ISSUE TITLE
Package issue: npm keeps falling back to beta1.15

### ISSUE THREAD

**Issue by willmorgan** [Azure/azure-functions-core-tools#429]
We've got azure-functions-core-tools installed as a devDependency:

```json
  "devDependencies": {
    "azure-functions-core-tools": "^2.0.1-beta.25",
```

Running an install for any other package seems to downgrade it to `2.0.1-beta1.15`

Is this a semver/package publishing issue?

I'm using `npm` 5.8.0 on macOS.

**Comment by willmorgan** [comment]
It seems if I use `"azure-functions-core-tools": "core"`, the issue is mitigated somewhat.

**Comment by ntomsic** [comment]
Hit this myself.

using `npm ci` to install also mitigates the issue.

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
