### ISSUE TITLE
Can I force publish to first remove all existing files?

### ISSUE THREAD

**Issue by petmat** [Azure/azure-functions-core-tools#432]
I've been having cold-start issues with my Node.js functions and the problem was having too many node_modules directories and files inside them. I removed the directories and files and published to Azure but the problem is that the publish does not remove any of the old files in the Function App.

Is there a configuration or option for the publish so that it would automatically remove all the files before it starts uploading the new files?

**Comment by ahmelsayed** [comment]
No, there isn't a force update

The publishing API has been [updated](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file) to remove files on the destination that are removed from local files. However, it won't affect files that are already there, only new ones. 

You can delete everything there one time manually then moving forward publishing will do the right thing, or you can try [Run-From-Zip](https://github.com/Azure/app-service-announcements/issues/84) (basically set `WEBSITE_USE_ZIP` app setting to 1, and publish again.
