### ISSUE TITLE
Unable to genereate self-signed certificate

### ISSUE THREAD

**Issue by s-KaiNet** [Azure/azure-functions-core-tools#436]
I have really strange issues with cli (v1) on my machine: 
> Windows Server 2012 R2 Standard Version	6.3.9600 Build 9600   

I have installed cli using npm and through VS2017 azure functions add-in as well. Both behave similarly.    
When I try to run `func host start --useHttps` it shows `The host is taking longer than expected to start.`.  
I've tried to generate self-signed cert and received error: 

> Unable to cast COM object of type 'System.__ComObject' to interface type 'CERTENROLLLib.CX509PrivateKey'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{728AB362-217D-11DA-B2A4-000E7BBB2B09}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).  

I checked out the code from this repo and tried to run it on my environment. Surprisingly after rebuild I was able to generate and install certificate, however even after that it shows `The host is taking longer than expected to start.` in console forever (when running the code I built from this repo. I just copied ready-to-use func in bin/debug directory. Without `useHttps` it works just fine).

**Comment by s-KaiNet** [comment]
I aslo found very strange behaviour with certificate generation. Check out   
`public static X509Certificate2 CreateSelfSignedCertificate(string subjectName)`  
There is a line `cert.NotBefore = DateTime.Now;`. In my time zone (UTC+3) it generates a certificate which is valid starting from my local time + 3 hours (so it thinks that my local time is UTC+0). As a result, I have a certificate which is valid in future.

**Comment by watashiSHUN** [comment]
For the 1st issue, it seems to be related to https://stackoverflow.com/questions/33001983/issues-compiling-in-windows-10

**Comment by watashiSHUN** [comment]
For the 2nd issue, did you set up your connection string? https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file
