### ISSUE TITLE
Error parsing configPath. path of the directory containing extensions.csproj file

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-functions-core-tools#445]
Hi,

I'm using the snapshot build of [2.0.1-beta.26](https://ci.appveyor.com/api/buildjobs/a9tkpxcydn4k1a5i/artifacts/deploy%2FAzure.Functions.Cli.osx-x64.zip) on Mac.

When I trigger the command: `func extensions install -c /Users/neo/Desktop/function-demo`, I got:
`Error parsing configPath. path of the directory containing extensions.csproj file`.

I have no idea what should I do with this message.

**Comment by ahmelsayed** [comment]
looks like [this issue](https://github.com/fclp/fluent-command-line-parser/issues/87).

Try this as a work around
```
func extensions install -c -- /Users/Desktop/function-demo
```

**Comment by jdneo** [comment]
@ahmelsayed Thank you for the reply. 

Just tried this on Mac and Windows, both of them are working well.

So is it safe to calling this command with the additional `--` for all the platform? (Windows, Linux, Mac)

**Comment by ahmelsayed** [comment]
yes it's safe to use `--` for all platforms

**Comment by ahmelsayed** [comment]
Let's keep it open. I'd like to remove that requirement

**Comment by jdneo** [comment]
@ahmelsayed Thank you for fixing that. Will this change break the commands that contain `--`?

**Comment by ahmelsayed** [comment]
No, both (with and without `--`) will work.

**Comment by jdneo** [comment]
@ahmelsayed Great, thank you

**Comment by sinistram** [comment]
This workaround will nor work for the cases when we need to pass two args starting with '/'. 
Any ideas how to handle that case?
