### ISSUE TITLE
CosmosDB binding silently fails while connecting to CosmosDB Emulator

### ISSUE THREAD

**Issue by jacktho** [Azure/azure-functions-core-tools#450]
CosmosDB extension: 3.0.0-beta7.
Node: 8.11.1
azure-functions-core-tools: 2.0.1-beta.25

- 'func host start' shows the extension successfully loads.
- No errors or warnings are seen in the console or log files.
- It does not matter if the connection string is correct or not.
- Removing the connection string altogether does produce a warning.
- The same local.settings.json and function files are able to connect to the emulator when using core tools v1.

I'm not sure what else to provide as I'm in the dark as to what the problem is.

Thanks.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2766
