### ISSUE TITLE
support AzureWebJobsScriptRoot in the cli

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-core-tools#452]
AzureWebJobsScriptRoot env variable on the machine is not overridden in time. This causes runtime to fail because it is looking for binaires in the AzureWebJobsScriptRoot path instead of the bin folder of the actual function.

CLI version: 2.0.11737.0

Repro:
1. Set up AzureWebJobsScriptRoot environment variable to a path
2. Create a eventhub template in VS, set required configuration
3. Press F5

**Comment by ahmelsayed** [comment]
how are you setting AzureWebJobsScriptRoot?

**Comment by soninaren** [comment]
Have set it as an environment variable from the Windows system settings.

**Comment by ahmelsayed** [comment]
I see, I think that env is probably just ignored in the CLI https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L198

**Comment by kshyju** [comment]
@soninaren Is this still a valid/relevant issue?
