### ISSUE TITLE
CLI should display inner exceptions

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-core-tools#456]
Currently, when an unhandled exception is thrown, the CLI only displays the top-level exception and none of the inner exception details, if any exist. We should be printing the full exception information to make debugging problems like the one encountered by [this user on StackOverflow](https://stackoverflow.com/questions/50127370/cant-debug-azure-function-visual-studio-2017) easier.

**Comment by ahmelsayed** [comment]
I can't repro the issue in the SO link. Do you have a repro? 
It'll depend on who is printing that message, and I can't easily tell. 

The CLI will indeed only print the message of the exception unless if `CLI_DEBUG=1` env var is set. Then it'll print the full exception
