### ISSUE TITLE
Worker issue on 2.0.1-beta.25

### ISSUE THREAD

**Issue by ssougnez** [Azure/azure-functions-core-tools#458]
Hello,

I just updated azure-functions-core-tools@core to the version 2.0.1-beta.25 and since then, nothing works anymore. The first issue concerns the environment variable JAVA_HOME:

> [5/7/2018 5:09:49 PM] Unable to configure java worker. Could not find JAVA_HOME app setting.
> [5/7/2018 5:09:49 PM] Could not configure language worker Java.

Now, the biggest issue I have is:

> [5/7/2018 5:09:49 PM] Couldn't require bundle, falling back to Worker.js. Error: Cannot find module 'C:\Users\ssoug\AppData\Local\Yarn\config\global\node_modules\azure-functions-core-tools\bin\workers\node\grpc\src\node\extension_binary\node-v64-win32-x64\grpc_node.node'
> [5/7/2018 5:09:49 PM] internal/modules/cjs/loader.js:573
> [5/7/2018 5:09:49 PM]     throw err;
> [5/7/2018 5:09:49 PM]     ^
> [5/7/2018 5:09:49 PM] Error: Cannot find module './Worker.js'
> [5/7/2018 5:09:49 PM]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
> [5/7/2018 5:09:49 PM]     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
> [5/7/2018 5:09:49 PM]     at Module.require (internal/modules/cjs/loader.js:626:17)
> [5/7/2018 5:09:49 PM]     at require (internal/modules/cjs/helpers.js:20:18)
> [5/7/2018 5:09:49 PM]     at Object.<anonymous> (C:\Users\ssoug\AppData\Local\Yarn\config\global\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js:8:14)
> [5/7/2018 5:09:49 PM]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [5/7/2018 5:09:49 PM]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [5/7/2018 5:09:49 PM]     at Module.load (internal/modules/cjs/loader.js:589:32)
> [5/7/2018 5:09:49 PM]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [5/7/2018 5:09:49 PM]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [5/7/2018 5:09:49 PM] Worker encountered an error.
> [5/7/2018 5:09:49 PM] Worker process with pid 19660 exited with code 1.

When I looked into the folder "C:\Users\ssoug\AppData\Local\Yarn\config\global\node_modules\azure-functions-core-tools\bin\workers\node\grpc\src\node\extension_binary\", I indeed have no folder named "node-v64-win32-x64". The folder I have are v48 and v57.

I'm using node v10.0.0 and dotnet 2.1.300-preview2-008530.

**Comment by ahmelsayed** [comment]
Only node 8 will work today. 
That limitation is not from this project, but rather from dependencies. Please follow these 2 issues for updating to latest node versions 
https://github.com/Azure/azure-functions-nodejs-worker/issues/65 
https://github.com/Azure/azure-functions-host/issues/2747

**Comment by arichiardi** [comment]
I have faced this behaviour in the actual function engine and I was wondering what setting I need to use for working around the bug, see also https://github.com/Azure/azure-functions-nodejs-worker/issues/101
