### ISSUE TITLE
Unable to run Post Install Script on Windows 7 behind Proxy

### ISSUE THREAD

**Issue by vnextcoder** [Azure/azure-functions-core-tools#459]
NPM version  5.6.0
Node version v8.11.1

NPM Proxy is set as below and it is able to download the NPM package. However, when it tries to run the Post Install script, it fails to download the Windows Binaries. 

NPM Proxy Settings

    proxy=http://corpproxy.mycompany.com:8080/
    https_proxy=http://corpproxy.mycompany.com:8080
    https-proxy=http://corpproxy.mycompany.com:8080

Below is Error shown while installing the package. 

````shell
C:\>npm install -g azure-functions-core-tools
C:\node-v8.11.1-win-x64\azfun -> C:\node-v8.11.1-win-x64\node_modules\azure-functions-core-tools\lib\main.js
C:\node-v8.11.1-win-x64\func -> C:\node-v8.11.1-win-x64\node_modules\azure-functions-core-tools\lib\main.js
C:\node-v8.11.1-win-x64\azurefunctions -> C:\node-v8.11.1-win-x64\node_modules\azure-functions-core-tools\lib\main.j
s

> azure-functions-core-tools@1.0.12 postinstall C:\node-v8.11.1-win-x64\node_modules\azure-functions-core-tools
> node lib/install.js

Error: connect ETIMEDOUT 152.199.20.1:443
npm WARN rollback Rolling back azure-functions-core-tools@1.0.12 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'C:\node-v8.11.1-win-x64\node_modules\azure-functions-core-tools\lib'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! azure-functions-core-tools@1.0.12 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the azure-functions-core-tools@1.0.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

````

After Debugging the Install Script. I am able to diagnose that Node is not following the NPM Proxy settings and simply trying to reach to the  path https://functionscdn.azureedge.net/public/1.0.12/Azure.Functions.Cli.zip.  
So I downloaded Azure.Functions.Cli.zip using my Browser and installed it in the bin folder inside azure-functions-core-tools.  

So my full bin folder path looks like 
~/node_modules/azure-functions-core-tools/bin

This looks like a Bug in Post-Install script to ignore NPM Settings or there needs to be a way to force ````http```` to use the NPM Proxy.

**Comment by Johnz86** [comment]
I have the same issue right now. I am behind corporate proxy and my local environment setup is not taken into account. Post install steps fails.

**Comment by watashiSHUN** [comment]
Can you try using chocolatey?: https://github.com/Azure/azure-functions-core-tools/issues/358#issuecomment-387549226

**Comment by Johnz86** [comment]
Chocolate installation works with proxy settings.

**Comment by ahmelsayed** [comment]
@watashiSHUN This has been fixed, right? Please reopen if not.
