### ISSUE TITLE
'func host start' exiting without error

### ISSUE THREAD

**Issue by cparker4486** [Azure/azure-functions-core-tools#462]
I haven't found any pattern to it, but sometimes the running host will simply exit and stop running after it finishes executing a function. When I start the function host again, `func host start`, it might work fine for a long time. But _sometimes_ it will exit without warning.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/1189638/39890038-70d70d8c-544e-11e8-947f-19954b6bc8be.png)

**Comment by ahmelsayed** [comment]
Can you try running it under a debugger and see what kind of exception is being thrown? 

The problem is that if an exception is thrown in the background, inside a function or the runtime, the cli is unable to catch it. Another place you can try looking into is `Event Viewer -> Windows Logs -> Application` and see if anything is logged there from func.exe

**Comment by cparker4486** [comment]
> Can you try running it under a debugger and see what kind of exception is being thrown?

I'm afraid I don't know how to do that.

> The problem is that if an exception is thrown in the background, inside a function or the runtime, the cli is unable to catch it.

Since I posted my issue I have noticed that it seems to most often happen when I don't return a response from the function. Usually, that's unintentional.

I'll see what I can find in the `Application` log next time this comes up.

**Comment by ahmelsayed** [comment]
interesting, I'll try that. Assuming you mean no body, right? also I forgot to ask what language are is your function? I assumed it was C#, but just want to make sure. 

Also to attach a debugger you can do `func host start --debug vs`, this will launch VS for you attached to the process (If you have VS)

**Comment by ahmedelnably** [comment]
Closing as stale, please open a new issue if the error is still happening on the latest version
