### ISSUE TITLE
Azure Function Crashes when CORS and SSL is enabled

### ISSUE THREAD

**Issue by StfBauer** [Azure/azure-functions-core-tools#464]
I currently develop a local azure function to test. I have enabled HTTPS and CORS but when the first access happens the azure function crashes with the following error.

```
func(5503,0x7000099c8000) malloc: *** error for object 0x7fb4f3101180: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Any suggestion or is this a general bug?

**Comment by ahmelsayed** [comment]
what version are you using? v1 or v2?

**Comment by ahmelsayed** [comment]
Also OS you're using if v2 would be very helpful

**Comment by StfBauer** [comment]
thank you for your response @ahmelsayed 

Azure Functions Core Tools (220.0.0-beta.0)
Function Runtime Version: 2.0.11651.0
OSX 10.13.4

Any other information I can provide you?

**Comment by ahmelsayed** [comment]
Thanks! That's perfect for now. I'll try to get a repro and get back to you.

**Comment by ahmelsayed** [comment]
I'm unable to repro this on my mac (10.13.4) 

Can you share the command and request you're sending? Here is what I tried 

```
func start --useHttps --cert cert.pfx --password 'password' --cors '*'
```
then 
```
curl -k -H "Origin: https://another.com" -XGET https://localhost:7071/api/HttpTriggerCSharp
```

works fine with 200 for me.

**Comment by StfBauer** [comment]
@ahmelsayed Jep, found the problem I haven't had password as ```'password'``` and the same happend with --cors switch.

I called it like this:

```
func start --useHttps --cert cert.pfx --password password --cors *
```

**Comment by StfBauer** [comment]
I retried this steps again today and it works perfectly @ahmelsayed I guess I can close it now. Thank you very much for your help.
