### ISSUE TITLE
Reflect the Cosmos DB template for func new in Python

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#467]
https://github.com/Azure/azure-functions-templates/pull/679

**Comment by ahmelsayed** [comment]
@soninaren  that template is still not in `templateApiZip`. I'll move this issue to the template repo. Feel free to open another one here once that's updated.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-templates#699

**Comment by soninaren** [comment]
Re-opening this one, have updated the template api zip in the cli feed.
https://functionscdn.azureedge.net/public/TemplatesApi/2.0.0-beta-10205.zip
