### ISSUE TITLE
Update deb package to include dotnet prerequisites for ubuntu

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#468]
_From @arerlend on April 30, 2018 19:47_

Running with bash via Ubuntu 16.04 subsystem for Windows.

Followed instructions here: https://github.com/Azure/azure-functions-docker-python-sample/wiki/Getting-started-using-Functions-Core-Tools.

Downloaded linux zip file from https://ci.appveyor.com/project/appsvc/azure-functions-cli/build/2.0.1.294/artifacts

Upon using binaries to run `func init . --worker-runtime python` (or any other call to `func`), I get the following errors:
`Failed to load X{z, error: libunwind.so.8: cannot open shared object file: No such file or directory`
`Failed to bind to CoreCLR at '/mnt/c/Users/Administrator/dev/soh-local/func_venv_bash/linux_functions/libcoreclr.so'`

Fixed by running `apt-get install libunwind8`

_Copied from original issue: Azure/azure-functions-docker-python-sample#10_

**Comment by asavaritayal** [comment]
@ahmelsayed

**Comment by ahmelsayed** [comment]
there are few dependencies for self contained dotnet apps on Ubuntu. https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#ubuntu 

@watashiSHUN we should add these prerequisites to the deb package to match what dotnet package does. 

If you're downloading the binaries directly you should install the prerequisites

**Comment by watashiSHUN** [comment]
libunwind is removed from dotnet core 2.1: https://github.com/PowerShell/PowerShell/pull/6964, so using azure-functions-core-tools >= `beta.29` should resolve this issue
