### ISSUE TITLE
 HTTP triggered python functions with 401 unauthorized errors. 

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#469]
_From @priyaananthasankar on May 9, 2018 21:55_

When trying to get the admin key from /api/functions/admin/masterkey they got an error that looks like the host wasn't generating the API keys. With the latest function core tools installation, this error can be reproduced. Simple HTTP Trigger.

_Copied from original issue: Azure/azure-functions-docker-python-sample#17_

**Comment by ahmelsayed** [comment]
not sure what that path (`/api/functions/admin/masterkey`) is supposed to be. Authentication is turned off in the cli
