### ISSUE TITLE
Docker Compose - Microsoft.VisualStudio.Docker.Compose.targets -- Value cannot be null.

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-core-tools#477]
@ahmelsayed  @davidebbo @bala16

I am getting an error when building docker-compose  with an AzFunc v2 project

used `func init --docker` to create an Azure Function project.
Then I manually added a docker-compose project.
Build the docker-compose project.
I get the below error.

<CreateComposeVsGeneratedFiles DockerComposeProjectPath="$(DockerComposeProjectPath)"
                                   DockerDevelopmentMode="$(DockerDevelopmentMode)"
                                   DockerVsDbgPath="$(DockerVsDbgPath)"
                                   DockerMsVsMonPath="$(DockerMsVsMonPath)"
                                   DockerOneCoreMsVsMonPath="$(DockerOneCoreMsVsMonPath)"
                                   ServiceReferences="@(DockerServiceReferences)" />

The error was: Object reference not set to an instance of an object.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Value cannot be null.
Parameter name: stream	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	294

**Comment by espray** [comment]
`docker-compose build` is successfully
Visual Studio Professional 15.7.1

Is this a Visual Studio issue?

**Comment by espray** [comment]
@ahmelsayed @davidebbo @bala16 
Any update on this issue?

FYI Logged an issue with Visual Studio as well
[docker-compose build error: "Value cannot be null. Parameter name: stream](https://developercommunity.visualstudio.com/content/problem/254807/docker-compose-build-error-value-cannot-be-null-pa-1.html)

Visual Studio Professional 2017
15.7.1

When I build my docker-compose I get the below error. 'docker-compose build' runs successfully

- Used Azure Functions CLI 'func init --docker' to generate the Dockerfile
https://github.com/Azure/azure-functions-core-tools
- Then manualy added docker-compose project to the solution.


Severity Code Description Project File Line Suppression State
Error Value cannot be null.
Parameter name: stream docker-compose C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets 294 

LN:294
<CreateComposeVsGeneratedFiles DockerComposeProjectPath="$(DockerComposeProjectPath)"
DockerDevelopmentMode="$(DockerDevelopmentMode)"
DockerVsDbgPath="$(DockerVsDbgPath)"
DockerMsVsMonPath="$(DockerMsVsMonPath)"
DockerOneCoreMsVsMonPath="$(DockerOneCoreMsVsMonPath)"
ServiceReferences="@(DockerServiceReferences)" />

**Comment by MagoDopado** [comment]
Im running into the same thing, as you closed the issue, have you found a way to solve this?

**Comment by shannoncarver** [comment]
i'm also running into the same issue.  what is the solution?
