### ISSUE TITLE
Error creating a local Functions project

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-core-tools#478]
_From @nahue97 on May 13, 2018 20:17_

When I execute this command: "func init MyFunctionProj" I should get an output like this:
Writing .gitignore
Writing host.json
Writing local.settings.json
Created launch.json
Initialized empty Git repository in D:/Code/Playground/MyFunctionProj/.git/

But I get this output:
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing C:\Users\nahue\dev\MyFunctionProj\.vscode\extensions.json
El sistema no puede encontrar el archivo especificado

Note: My Windows is in Spanish. That message means "File not found" or "The System couldn't find the specified file".
What should I do now? I've already followed the instructions and I cannot continue...

_Copied from original issue: Azure/azure-functions-host#2843_

**Comment by paulbatum** [comment]
_From @nahue97 on May 14, 2018 2:10_

Update: I followed the instructions in my brother's computer and it worked. Could it be related to an installation of Visual Studio 2015 I made months ago? I still cannot make it work in my computer.

**Comment by JohnReeson** [comment]
Hi @paulbatum , issue can be closed. It is related to [System Cannot Find the File Specified](https://www.easeus.com/resource/the-system-cannot-find-the-file-specified.html) and solved by updating windows. See [so thread](https://stackoverflow.com/questions/50319740/azure-functions-file-not-found/50322391).
