### ISSUE TITLE
Instrument CLI with opt-in anonymous telemetry

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-core-tools#48]
Implementation will probably use App Insights client

**Comment by lindydonna** [comment]
Opt-out behavior should be the same as .NET Core CLI tools. @lindydonna to update with details.

**Comment by ahmelsayed** [comment]
@watashiSHUN let's sync up about this when you get around to it

**Comment by ahmedelnably** [comment]
Tracked by https://github.com/Azure/azure-functions-core-tools/issues/1360
