### ISSUE TITLE
grpcio use binary wheels in docker install

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#480]
_From @kapilt on May 16, 2018 9:29_

for some reasons i'm getting grpcio compile from source behavior when getting the docker build, which is quite time consuming and cpu intensive to do per publish. it seems grpc is required for azure functions (ugh.), so at minimum consuming binary wheels would result in massive time improvement for publish clock time.. which at the moment for me is over 10m for me... (azure vm 2core/4gb)

```
$ time func azure functionapp publish dev-func-123
...
Creating archive for current directory...
Uploading archive...
Upload completed successfully.

real    11m6.456s
user    0m2.462s
sys     0m0.962s
```

_Copied from original issue: Azure/azure-functions-python-worker#125_

**Comment by ahmelsayed** [comment]
@kapilt what cli version are you using?

**Comment by asavaritayal** [comment]
This should now be fixed.
