### ISSUE TITLE
Normalize --language in func new to accept language name aliases

### ISSUE THREAD

**Issue by ltouro** [Azure/azure-functions-core-tools#481]
Trying to create a new Javascript function is not working.

It asks for a Template, but no option is given. Trying to type the template name does not work either, making it unusable.

![image](https://user-images.githubusercontent.com/5283919/40326870-3477c198-5d17-11e8-925d-d7db0a3eb0b9.png)

Trying to create the same function in C# actually works fine:

![image](https://user-images.githubusercontent.com/5283919/40326941-71fcc720-5d17-11e8-8fc4-29772b907db7.png)

**Comment by JohnReeson** [comment]
@ltouro , try to use `javascript` instead of `js`.

**Comment by ltouro** [comment]
@JohnReeson It works with "javascript". 

Think we need some validation for the language informed by the user. Or something like this: https://github.com/Azure/azure-functions-core-tools/blob/d3b278faccd93ce2af6f9cb238bebf390d5e3d10/src/Azure.Functions.Cli/Helpers/WorkerRuntimeLanguageHelper.cs#L20
