### ISSUE TITLE
Enhance new user onboarding

### ISSUE THREAD

**Issue by ltouro** [Azure/azure-functions-core-tools#482]
**Expected:** 

As an onboarding user, I expect to install the CLI and use it to test a function locally.

**Current:**

After installing the CLI and trying to use it, I'm informed that there is yet another depedency to install:

```
The listener for function 'Functions.test' was unable to start. System.Private.CoreLib: One or more errors occurred. (Please verify that the Azure Storage Emulator is running.). Microsoft.Azure.WebJobs.Host: Please verify that the Azure Storage Emulator is running. Microsoft.WindowsAzure.Storage: An error occurred while sending the request. System.Private.CoreLib: An error occurred while sending the request. System.Private.CoreLib: Uma conexão com o servidor não pôde ser estabelecida.
```

**Proposed Solution:**

Either inform all dependencies that has to be installed locally upfront or remove the dependency to an storage emulator.

**Comment by ahmelsayed** [comment]
Closing old issue. Please open another one if you're still running into any issues.
