### ISSUE TITLE
Missing tag error while deploying functions with core tools

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#484]
_From @priyaananthasankar on May 21, 2018 18:56_

Followed instructions from:

and when executing func azure functionapp publish pypreviewapp, got the following error.

Running docker exec -t c042b8fecca82e433ecf220fff4794de4cca89d918e2c09d026d2e9b8ebdc7ba /python_docker_build.sh
Obtaining azure_functions_python from git+https://github.com/Azure/azure-functions-python-worker.git@549f40b8be07388fedbc5b706db6d14e5179bc6e#egg=azure_functions_python (from -r requirements.txt (line 1))
  Cloning https://github.com/Azure/azure-functions-python-worker.git (to "549f40b8be07388fedbc5b706db6d14e5179bc6e") to ./worker_venv/src/azure-functions-python
  **Could not find a tag or branch "549f40b8be07388fedbc5b706db6d14e5179bc6e", assuming commit.**

and it doesn't move forward from here.

Workaround: Change the tag from "549f40b8be07388fedbc5b706db6d14e5179bc6e" to "dev" in requirements.txt.

_Copied from original issue: Azure/azure-functions-python-worker#128_

**Comment by asavaritayal** [comment]
_From @aluong on May 21, 2018 19:1_

This looks like this issue that I filed: https://github.com/Azure/azure-functions-core-tools/issues/476

**Comment by asavaritayal** [comment]
@priyaananthasankar  Is this a warning or an error? 

@ahmelsayed It seems that the GUI is referencing a commit. Is this by design?

**Comment by asavaritayal** [comment]
_From @priyaananthasankar on May 21, 2018 21:7_

This seems like an error and it doesn't proceed after this. As Andy says, if the label in requirements.txt is changed to dev it works. So I suspect the func core tools that adds the venv.

So basically when I create a venv using func tools and perform a pip freeze, it adds this label here.

"-e git+https://github.com/Azure/azure-functions-python-worker.git@ **"549f40b8be07388fedbc5b706db6d14e5179bc6e"**  #egg=azure_functions_python"

**Comment by ahmelsayed** [comment]
Please use the latest publicly released cli. I can't repro this with the latest version `2.0.1-beta.28`
