### ISSUE TITLE
Cannot use a custom TypeConverter in a V2 function app

### ISSUE THREAD

**Issue by Liversage** [Azure/azure-functions-core-tools#489]
After my .NET Core tools were upgraded from 2.0.1-beta.27 to 2.1.0 I have a problem where a custom `TypeConverter` (for JSON serialization) stops working. I have managed to reproduce the issue in a very simple project (V2):

```CSharp
public class Custom { }

public class CustomTypeConverter : TypeConverter { }

public static class Function1
{
    [FunctionName("Function1")]
    public static void Run([TimerTrigger("*/5 * * * * *")] TimerInfo myTimer, TraceWriter log)
    {
        TypeDescriptor.AddAttributes(
            typeof(Custom),
            new TypeConverterAttribute(typeof(CustomTypeConverter)));
        var converter = TypeDescriptor.GetConverter(typeof(Custom));
        log.Info(converter.GetType().Name);
    }
}
```

The `converter` retrieved by `TypeDescriptor.GetConverter(typeof(Custom))` is supposed to be of type `CustomTypeConverter` (it was added in the previous line). This is how <text>JSON.Net</text> applies a custom `TypeConverter` during serialization so it is important that this call returns the configured `TypeConverter`.

However, when I execute this function using tools version 2.1.0 a `TypeConverter` instance is returned instead of the expected `CustomTypeConverter` instance.

If I use tools version 2.0.1-beta.27  the expected `CustomTypeConverter` instance is returned. (This is also the case when the same type of code is used in console application.)

I also tested the function in Azure and here I get the same (unexpected) behavior as when I use the 2.1.0 tools so in a way this is not a bug in the tools. However, not being able to use a custom `TypeConverter` in a function app is a serious limitation.

I have tried to further understand the source of the problem. In my real project a `FileNotFoundException` is thrown (and caught) in the call to `TypeDescriptor.GetConverter()` and it seems that the file that cannot be found is the assembly where the custom `TypeConverter` is defined. This is surprising as `typeof(CustomTypeConverter)` appears in the previous line so the type must be loaded into the process. However, in this simplified example the exception that is thrown (and caught) is `TaskCancelledException`. I don't know if that has anything to do with this issue.

Please allow me to configure a custom `TypeConverter` in a function app or at least clearly document why that is not possible.

**Comment by fabiocav** [comment]
This issue was moved to Azure/azure-functions-host#2898
