### ISSUE TITLE
Remove dependency on JAVA_HOME

### ISSUE THREAD

**Issue by brunoborges** [Azure/azure-functions-core-tools#502]
Unless strictly necessary, the runtime for Java functions should not depend on the environment variable JAVA_HOME. The executable `java` should be found in PATH, and that should be used by default. If JAVA_HOME is set, then the runtime should use that instead.

// @jeffhollan

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2920

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#2921
