### ISSUE TITLE
Local debug abnormal behaviour when debug tab is open on MacOS

### ISSUE THREAD

**Issue by neptunian0** [Azure/azure-functions-core-tools#504]
I've recently upgraded azure-functions-core-tools to 2.0.1-beta.28 where a previous issue I had faced with the debugger failing to attach has been resolved from 2.0.1-beta.26. I'm working with a blob storage trigger using Node on VS Code for local development. I've now got my debugger attaching and the program is stopping at my assigned breakpoints.

However, if I have the debug tab open, I cannot see any of the local variables, and when I hit "Resume" for the program, I can see the output from the terminal continue (i.e. the program has resumed) but the debugger is still showing as paused on the most recent breakpoint. It will no longer stop at the breakpoint in the future. 

The debugger will work as expected as long as I don't open the debug tab. I've noticed that the "Local" and "Global" variable tabs are stuck with loading wheels when debugging. I'm running on MacOS. I've attached a screen shot of the loading wheel I see when I have the debug tab open.
![screen shot 2018-05-31 at 11 27 15](https://user-images.githubusercontent.com/20815527/40777392-a2f959e6-64c5-11e8-8482-97b78fdcfa5c.png)

**Comment by neptunian0** [comment]
After some investigating, it appears that the issue is due to the size of the blob being uploaded to storage. I don't suppose there'd be a plan to better handle large blob files while debugging on VS Code?

**Comment by ahmelsayed** [comment]
/cc @EricJizbaMSFT

I'm not too familiar with vscode debugger limitations. Hopefully @EricJizbaMSFT could chime in.

**Comment by EricJizbaMSFT** [comment]
What size is the blob? I'm not aware of any strict size limits, but I can try to repro the issue myself.

cc @nturinski

**Comment by ahmedelnably** [comment]
Closing this as stale, if the behavior still repro, please open a new issue
