### ISSUE TITLE
Support for Anaconda environment

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#509]
_From @priyaananthasankar on June 1, 2018 16:12_

Existing Anaconda environment with Python version 3.5/3.6
BYOC/BYOF instructions fail unless Anaconda path is removed.

While using the BYOF functions tools, the tools does not support a conda environment by itself. Supports only virtual environments. Conda support is useful for machine learning scenarios and in general python environment support.

(minor) This solution requires the user to use virtualenv and does not support Conda (from Andy's notes)

_Copied from original issue: Azure/azure-functions-python-worker#136_

**Comment by asavaritayal** [comment]
@1st1 @elprans Is this a limitation of the language worker or core tools?

**Comment by asavaritayal** [comment]
_From @elprans on June 4, 2018 18:24_

@asavaritayal The worker itself does not assume anything about its environment. This is a core tools issue.

**Comment by jiata** [comment]
+1

**Comment by asavaritayal** [comment]
+1 , to represent request from another customer on this

**Comment by ahmelsayed** [comment]
I'm still not seeing any repro steps. Please feel free to re open the issue once you have actual 1, 2, 3 repro steps.

**Comment by charleswm** [comment]
+1

This would be a really useful feature. @ahmelsayed, maybe I'm misunderstanding, but I don't think this is a bug. It's just missing functionality. What do you need in terms of repro steps to reopen?

## Steps to reproduce

I'm on mac running High Sierra 10.13.6.

I've created a new conda environment with a python 3.6 environment.

`conda create -n func-apps-env python=3.6`

Then I activate it using `conda activate func-apps-env `
(in conda version 4.5.11)

In earlier versions of conda it would be `source activate func-apps-env`

I've used brew to install  `azure/functions/azure-functions-core-tools` 2.2.70 per the [Azure docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#install-the-azure-functions-core-tools)

Then I try to create a new function app inside the activated conda env.

```
$ func init MyFunctionProj
Select a worker runtime:
1. dotnet
2. node
3. python
Choose option: 3
python
For Python function apps, you have to be running in a venv. Please create and activate a Python 3.6 venv and run this command again.
```

What this message suggests to me is that I have to use virtualenv for this to work, which is not ideal. It would be great to be able to use conda here.

Any thoughts on this?

**Comment by charleswm** [comment]
While not an ideal solution, I was able to get this running inside of conda by creating a new conda environment and then creating a virtualenv inside of that. This at least ensures that your building off of a clean python installation.

I had to manually pip install a few of the azure tools for some reason, but I got the http requests functions working locally from inside an activated conda environment.

**Comment by priyaananthasankar** [comment]
Customer wanted to use fbprophet library for forecasting and fbprophet installs best with conda which knows the right gcc options to install pystan library. This did not work with pip install or virtual environment - gives a bad developer experience for the data scientists who start preferring docker instead. fbprophet can be used as a sample to experiment conda support.

**Comment by PostlMC** [comment]
+1 Just hit this too -- would love to see it resolved for both work and personal projects.

**Comment by asavaritayal** [comment]
Closing issue as a dupe of https://github.com/Azure/azure-functions-core-tools/issues/1031
