### ISSUE TITLE
Can't upgrade asp.net core to 2.1 because Newtonsoft deps issue

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-core-tools#510]
![image](https://user-images.githubusercontent.com/57396/40956996-4f7aa7f8-6893-11e8-946f-9d39d62ec403.png)

**Comment by espray** [comment]
beta29 might fix this. 
commit 1333bab - Upgrading to .NET Core 2.1

https://github.com/Azure/azure-functions-core-tools/releases/tag/2.0.1-beta.29

**Comment by forki** [comment]
ping. this is still an issue.

**Comment by forki** [comment]
beta29 is not on nuget...

**Comment by ahmelsayed** [comment]
@forki sorry I don't understand where the error is coming from. CLI releases are not published to nuget in general. Are you using VS? VS is still stuck on beta.26 due to the dotnet 2.1 requirements for > 26. it should get beta.30 next week though once VS is updated to use self contained builds of this repo

**Comment by forki** [comment]
The error is a simple package version conflict. Your package https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions depends on Newtonsoft.Json 9.0.1 and requires exactly that version. This is incompatible with what asp.net 2.1 requires. Paket does tell exactly that in the screenshot above.

The fix would be for Microsoft to release a new version of the sdk functions package with >= 9.0.1 as restriction on Newtonsoft.Json

**Comment by ChristianWeyer** [comment]
This should have been resolved with the latest package(s), no? @forki

**Comment by forki** [comment]
Dunno. Are there new packages? I can check on Tuesday

**Comment by ChristianWeyer** [comment]
Currently, it is 1.0.14 (with dep on Newtonsoft 10.0.3) for the SDK and beta.31 for the Core Tools.
I have several ASP.NET Core 2.1 related projects running.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/43060361-f0a72e2a-8e50-11e8-8320-53f7e168fc58.png)


@ChristianWeyer see: they have newtonsoft pinned on 9.0.1 for net461 - this is bad for multi-target

**Comment by ChristianWeyer** [comment]
#TrueStory . I was only looking at the v2 part.

**Comment by fabiocav** [comment]
Closing this as resolved in the latest packages. A non-beta release of the SDK with those changes is also going out today.
