### ISSUE TITLE
Unable to install function extensions on Mac with United Kingdom region

### ISSUE THREAD

**Issue by martinpeck** [Azure/azure-functions-core-tools#519]
Running `func extension install` for any extension fails with an MSBuild error. With assistance from @nzthiago and @simonaco we tracked the failure down to the fact that my MacBook was using *United Kingdom* regional settings. When I switched to US the install works fine (no failure).

At present, when I use the default region for my machine (United Kingdom) I'm prevented from installing any extensions.

In the attached output.txt logs, you can see...

```
Expression: [Recursive resource lookup bug]

Description: Infinite recursion during resource lookup within System.Private.CoreLib.  
This may be a bug in System.Private.CoreLib, or potentially in certain extensibility 
points such as assembly resolve events or CultureInfo names.  
Resource name: ArgumentNull_Generic` 
```

... which gave the clue that this is region related.

Logs of error: [output.txt](https://github.com/Azure/azure-functions-core-tools/files/2080646/output.txt)

Context:

- functions v2
- running on Mac OS

Repro Steps:

On a MacBook, with Region set to United Kingdom, open Terminal and...

1. create new folder
2. cd into new folder
3. run `func init` and create a new node (or dotnet) function project
4. run `func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta7` to install the CosmosDB extentions (or any other extension you want...it doesn't matter)

Expected:
- extension is installed without errors

Actual:
- MSBuild error is seen 

```
Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(20,5): error : Metadata generation failed. [/Users/martinpeck/dev/cheese4/extensions.csproj]
```

5. Change region to 'US'
6. Open a new terminal window
7. Repeat steps 1 to 4
8. No errors occurred.

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

$  func --version
2.0.1-beta.28
```

**Comment by martinpeck** [comment]
Related https://github.com/NLog/NLog.Web/issues/210

**Comment by martinpeck** [comment]
Related issue seen elsewhere: https://github.com/dotnet/coreclr/issues/14033

**Comment by igorkovalchuk** [comment]
I have the same issue on Linux (uk_UA.utf8 locale).
I change the locale and it works!!!
Thank you!!!

**Comment by ahmelsayed** [comment]
@fabiocav @paulbatum 

This seems to be an issue with `ExtensionsMetadataGenerator` on unix with non-US locale. I couldn't find a repo for that generator. Not sure which repo that is in.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#3525
