### ISSUE TITLE
Enable Python debug port

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#521]
For VS Code to use /cc @nturinski @fiveisprime

**Comment by pragnagopa** [comment]
@ahmelsayed - I am working on updating the functions host to parse languageWorker.{language}.arguments instead of specifically looking for woker.{language}.Debug. This will allow CLI to pass other commandline options as well.
Instead of hard coding the debug ports, can we take that as an input? for example VS Code can pass the debug port to CLI

**Comment by ahmelsayed** [comment]
as mentioned on email, this is the syntax that vscode needs to pass in 

```bash
# for node
func ... --language-worker -- "--inspect=<port>"
 
# for java
func ... --language-worker -- "<port>"
 
# for python
func ... --language-worker -- "<port>"
 ```
 
 
The CLI will have the following mapping:
 
```js
{
    node: "languageWorkers:node:arguments={languageWorker}", // in this example {languageWorker} is "--inspect=<port>"
    java: "languageWorkers:java:debug={languageWorker}", // in this example {languageWorker} is "<port>"
    python: "languageWorkers:python:debug={languageWorker}" // in this example {languageWorker} is "<port>"
}
```

**Comment by ahmelsayed** [comment]
I have this PR for this change https://github.com/Azure/azure-functions-core-tools/pull/546 

Please let me know if the mapping above is correct and I'll merge it

**Comment by ahmelsayed** [comment]
@asavaritayal  please make sure to follow up with vscode to pass the new parameters starting with beta.30

**Comment by pragnagopa** [comment]
@jdneo  - Please see sample above for setting the debug port for java

**Comment by jdneo** [comment]
@pragnagopa Thanks for the information.
