### ISSUE TITLE
Proxies not working in CLI for 2.1.0

### ISSUE THREAD

**Issue by enternet** [Azure/azure-functions-core-tools#526]
When starting the host, this error is thrown:

> Microsoft.Azure.AppService.Proxy.Runtime: Error parsing policy (Tenant, 1). 
> Autofac: An error occurred during the activation of a particular registration. See the inner exception for details. 
> Registration: Activator = ForwardRequestPolicy (ReflectionActivator), Services = [Microsoft.Azure.AppService.Proxy.Common.Policies.IPolicy], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. 
> Registration: Activator = DefaultServiceRequestExecutor (ReflectionActivator), Services = [Microsoft.Azure.AppService.Proxy.Common.Contracts.IServiceRequestExecutor, Microsoft.Azure.AppService.Proxy.Common.Contracts.IServiceRequestExecutor2], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. 
> Registration: Activator = FixedBufferManager (DelegateActivator), Services = [Microsoft.Azure.AppService.Proxy.Common.Contracts.IBufferManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Configuration system failed to initialize (See inner exception for details.) (See inner exception for details.) (See inner exception for details.). 
> Autofac: An error occurred during the activation of a particular registration. See the inner exception for details. 
> Registration: Activator = DefaultServiceRequestExecutor (ReflectionActivator), Services = [Microsoft.Azure.AppService.Proxy.Common.Contracts.IServiceRequestExecutor, Microsoft.Azure.AppService.Proxy.Common.Contracts.IServiceRequestExecutor2], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. 
> Registration: Activator = FixedBufferManager (DelegateActivator), Services = [Microsoft.Azure.AppService.Proxy.Common.Contracts.IBufferManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Configuration system failed to initialize (See inner exception for details.) (See inner exception for details.). 
> Autofac: An error occurred during the activation of a particular registration. See the inner exception for details. 
> Registration: Activator = FixedBufferManager (DelegateActivator), Services = [Microsoft.Azure.AppService.Proxy.Common.Contracts.IBufferManager], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Configuration system failed to initialize (See inner exception for details.). 
> System.Configuration.ConfigurationManager: Configuration system failed to initialize. 
> System.Configuration.ConfigurationManager: Unrecognized configuration section system.serviceModel. 
> (C:\Users\user\AppData\Local\AzureFunctionsTools\Releases\2.1.0\cli\func.dll.config line 204).
> 

There is a temporary solution: remove section system.serviceModel from C:\Users\user\AppData\Local\AzureFunctionsTools\Releases\2.1.0\cli\func.dll.config

**Comment by JohnReeson** [comment]
This proxy issue is resolved on cli `2.0.1-beta.28` and latest version 29. But these versions are not available for VS yet,  cli in VS is still `2.0.1-beta.26`(aka 2.1.0 specified by VS).  

So just wait for the update or you can download [new version](https://github.com/Azure/azure-functions-core-tools/releases/tag/2.0.1-beta.29) manually.

**Comment by ahmelsayed** [comment]
@enternet I'm closing this assuming the issue has been resolved. Please feel free to reopen if I misunderstood.
