### ISSUE TITLE
core tools (2.0.1~beta.25-1) won't run in WSL (using dotnet 2.1.300)

### ISSUE THREAD

**Issue by polarapfel** [Azure/azure-functions-core-tools#528]
The func binary fails to run on WSL (Ubuntu 16.04):

Failed to load 8.∟☻, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/usr/lib/azure-functions-core-tools/libcoreclr.so'

**Comment by ahmelsayed** [comment]
Tracked with https://github.com/Azure/azure-functions-core-tools/issues/468
