### ISSUE TITLE
Regression Issue about function extensions install in 2.0.1-beta.29

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-functions-core-tools#531]
When I am using 2.0.1-beta.28 and calling `func extensions install -c <path>`. The function cli will help me install all the extension dlls into a `bin/` folder in the current working directory and save the `extensions.csproj` under the `<path>`.

But in `2.0.1-beta.29`, both the `bin/` and `extensions.csproj` will be generated under `path`.

**Comment by pragnagopa** [comment]
@ahmelsayed - Can you please take a look?

**Comment by ahmelsayed** [comment]
yes I'm looking at this now

**Comment by PinakiIT** [comment]
I am facing the same issue here. Any way to automate the build script to copy the bin folder to target directory?
