### ISSUE TITLE
azfun and azurefunctions doesn't work on MacOS

### ISSUE THREAD

**Issue by fetis** [Azure/azure-functions-core-tools#532]
Azure Functions Core Tools (2.0.1-beta.28)
MacOS
ProductName: Mac OS X
ProductVersion: 10.13.5
BuildVersion: 17F77

Original issue: https://github.com/MicrosoftDocs/azure-docs/issues/10138

**Comment by ahmelsayed** [comment]
I'm assuming you're using homebrew, right?

**Comment by fetis** [comment]
@ahmelsayed yes, I do
```
Homebrew 1.6.8
Homebrew/homebrew-core (git revision 12b51; last commit 2018-06-13)
```

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
