### ISSUE TITLE
Runtime fails with 2.0.1-beta.29 on mac

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-functions-core-tools#535]
After upgrading to .Net Core 2.1 on Mac and installing the Beta 29 of the core tools, the runtime is failing on an existing function of mine with the following error message:

```An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WebScriptHostManager (DelegateActivator), Services = [Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> Device not configured (See inner exception for details.)```

I'm not sure how to get more details on what specifically is failing. I can create and successfully run a test HttpTrigger template function.

**Comment by ahmelsayed** [comment]
can you share a repro?

**Comment by travisnielsen** [comment]
[azuretagsync](https://github.com/travisnielsen/azuretagsync)

When I run ```func host start```, the runtime somehow is unable to load. I tried re-installing but that didn't help.

![image](https://user-images.githubusercontent.com/3196834/41777892-86fee7a4-75f2-11e8-9604-5c5b15ae99b4.png)

![image](https://user-images.githubusercontent.com/3196834/41778008-e4418f70-75f2-11e8-905f-c9c69bef76cb.png)

**Comment by travisnielsen** [comment]
I got this working by re-cloning my repo into a different directory and running from there. So the issue must be something on my end. Closing.
