### ISSUE TITLE
How to configure Azure Functions (v2) listening Host / Domain ?

### ISSUE THREAD

**Issue by TonyHenrique** [Azure/azure-functions-core-tools#537]
Suppose this scenario:

**Develop a Xamarin Application using the real Phone and a Windows PC with Visual Studio + Azure Functions.**

> We run the Azure Functions, Debugging it, but the phone can not connect to it because the Azure Functions is hardcoded listening only on localhost.
> 
> How to configure Azure Functions (v2) listening Host / Domain ?

On ASP.Net Core we could use (.UseUrls("http://+:7071")): 
`Now listening on: http://[::]:7071`
But on Azure Functions we are locked to localhost. We can configure the port by specifying the func host command in the debug arguments and using the -p switch, but the hostname is hardcoded to localhost, as can be seen in the [source code](https://github.com/Azure/azure-functions-core-tools/blob/91481cb48afcfda415ad5e4a350d203de5ece421/src/Azure.Functions.Cli/FunctionsLocalServer.cs#L45) 

![image](https://user-images.githubusercontent.com/6307623/41563985-c70bb9b2-7327-11e8-8b0a-a56cc8b02838.png)

See:
https://stackoverflow.com/questions/49267438/how-to-accept-connections-from-local-network-on-azure-functions-v2/

Related GitHub issue:
https://github.com/Azure/azure-functions-core-tools/issues/174

Related code:
https://github.com/Azure/azure-functions-core-tools/blob/91481cb48afcfda415ad5e4a350d203de5ece421/src/Azure.Functions.Cli/FunctionsLocalServer.cs#L45

**Comment by ahmelsayed** [comment]
Closed in 1cb84009f480cd218b07f286bb88126a100b60d4
