### ISSUE TITLE
Proxies Not working in CLI

### ISSUE THREAD

**Issue by adamreed90** [Azure/azure-functions-core-tools#538]
Marked Closed by #102 however when attempting to test proxies using my new project (Visual Studio 2017 Enterprise Preview), they are ignored. 

\AzureFunctionsTools\Releases\2.1.0
Visual Studio Ext Version: 15.8.2027.0

**Comment by ahmelsayed** [comment]
@adamreed90 do you have a repro steps I can follow? Otherwise @safihamid  would know more. 

Also please share the version printed in the output when you run your app

**Comment by ahmelsayed** [comment]
tracked with https://github.com/Azure/azure-functions-core-tools/issues/526
