### ISSUE TITLE
Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0'

### ISSUE THREAD

**Issue by travisnielsen** [Azure/azure-functions-core-tools#540]
I have a [Function that uses Azure Resource Manager APIs to automate resource tagging](https://github.com/travisnielsen/azuretagsync). After upgrading to .Net Core 2.1 and Functions Core Tools 2.0.1-beta 29 I get the infamous 'Could not load file or assembly' error that others have reported in other scenarios (like #473). I'm having trouble finding the magic Nuget package versions to correct this.

```
Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Azure.Management.ResourceManager.Fluent, Version=1.0.0.60, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

Here are my current references:
```
<PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.1.0-preview" />
<PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.11.1" />
<PackagageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.11.1" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13" />
```
I tried various downgrades and other combinations but to no avail. Does anyone have suggestions on how I can get past this?

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#3043
