### ISSUE TITLE
Azure function dependency conflicts

### ISSUE THREAD

**Issue by mo-abbas** [Azure/azure-functions-core-tools#541]
We were using in our Azure function projects Autofac 3.5.0 with for a while. When we decided to upgrade it to 4.8.1 we got the exception:
```
System.MissingMethodException : Method not found: 'Void Autofac.Extensions.DependencyInjection.AutofacRegistration.Populate(Autofac.ContainerBuilder, System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.DependencyInjection.ServiceDescriptor>)'.
```

I tried to replace the Autofac.dll file in the Azure Functions CLI folder with the newer version and update the func.exe.config accordingly, and it started working again.

I think this is the same issue here https://github.com/Azure/azure-functions-core-tools/issues/141 

I reproduced this issue in a small project by doing the following:
- Create a new Function App with visual studio targeting .Net framework 4.6.1
- Add the nugets: 
     - Autofac 4.8.1
     - Autofac.Extensions.DependencyInjection 4.0.0
     - Microsoft.Extensions.DependencyInjection 1.1.0
- Add an HttpTrigger function with the following body
```C#
[FunctionName(nameof(Test))]
public static void Test([HttpTrigger] HttpRequestMessage req)
{
    var builder = new ContainerBuilder();
    builder.Populate(new ServiceCollection());
}
```

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-host#3042
