### ISSUE TITLE
macOS X homebrew installation is broken

### ISSUE THREAD

**Issue by Trosky** [Azure/azure-functions-core-tools#551]
The installation of azure-functions-core-tools seems to be broken due to a SHA256 mismatch.

MacOS X Version: 10.13.5 (17F77)
```
brew -v
Homebrew 1.6.9
Homebrew/homebrew-core (git revision fc526; last commit 2018-06-26)
``` 

```
brew install azure-functions-core-tools  
==> Installing azure-functions-core-tools from azure/functions
==> Downloading https://functionscdn.azureedge.net/public/2.0.1-beta.30/Azure.Functions.Cli.osx-x64.2.0.1-beta.30.zip
Already downloaded: /Users/iteratec/Library/Caches/Homebrew/azure-functions-core-tools-2.0.1-beta.30.zip
Error: SHA256 mismatch
Expected: 9161e6ea0abce04e16f18167e1bb8c75bc1c6caa61a3f47ba5f776a03c717ad6
Actual: 0f9113ee398288548110a18e02f6bb03132364441ce4b044751a870dc2303886
Archive: /Users/iteratec/Library/Caches/Homebrew/azure-functions-core-tools-2.0.1-beta.30.zip
To retry an incomplete download, remove the file above.
```

**Comment by travisnielsen** [comment]
I had the same issue and was able to get around it by setting the SHA256 checksum on the local Homebrew recipe in ```/usr/local/Homebrew/Library/Taps/azure/homebrew-functions/Formula```. I created a pull request to get this fixed: https://github.com/Azure/homebrew-functions/pull/4

**Comment by ahmelsayed** [comment]
Sorry about that. I put in the windows package sha2 by mistake. I'm working on a beta.31 release to address an issue in the Windows builds. The mac builds shouldn't be affected, but I'll update them to the latest anyway

**Comment by ahmelsayed** [comment]
oh and thanks @travisnielsen for the PR!
