### ISSUE TITLE
func CLI should not sync triggers when using zipdeploy

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-core-tools#554]
It's redundant since zipdeploy takes care of it.

**Comment by ankitkumarr** [comment]
Hi @davidebbo,

Just to confirm, `api/zipdeploy` in scm takes care of syncing triggers `api/functions/synctriggers`? 
So, we should only sync when we are publishing for RunFromZip?

**Comment by davidebbo** [comment]
That's correct. More specifically, when publishing for RunFromPackage using an external URL. When using [RunFromPackage via the zipdeploy API](https://github.com/Azure/app-service-announcements/issues/110), it's taken care of.
