### ISSUE TITLE
HTTP Link Broken

### ISSUE THREAD

**Issue by ljtill** [Azure/azure-functions-core-tools#561]
When creating a new Function App, a link is provided if the dotnet SDK isn't located however this link doesn't work.

Command
`func init --worker-runtime dotnet`

Response
`dotnet sdk is required for dotnet based functions. Please install https://microsoft.com/dotnet`

**Comment by ahmelsayed** [comment]
Fixed in https://github.com/Azure/azure-functions-core-tools/commit/ed13074afceb712d6f42594292a4d3c3297251ec. Thanks for the report @ljtill!!

**Comment by ljtill** [comment]
Heads up, this is link is broken again, seems that it's reverted to the previous https://microsoft.com/dotnet.
