### ISSUE TITLE
Azure functions app broken when running on 64 bit Azure App Service (Function Runtime Version: 2.0.11888.0)

### ISSUE THREAD

**Issue by hiraldesai** [Azure/azure-functions-core-tools#565]
I had an Azure Functions V2 project deployed to an Azure App Service. It completely broke with the recent changes to runtime. The UI won't show functions list and the platform features -> functions app settings won't load the details. Kudu console starts showing 503 so you can't do pretty much anything.

I changed it to 32 bit and it's working now, just thought I should report.

Azure Functions Core Tools (2.0.1-beta.31)
Function Runtime Version: 2.0.11888.0

**Comment by JohnReeson** [comment]
[This announcement](https://github.com/Azure/app-service-announcements/issues/117) has pointed out the breaking change about 64-bit platform.

**Comment by hiraldesai** [comment]
Oh - thank you for pointing that out.
