### ISSUE TITLE
Azure Functions CLI Tools 2.2.2 - Unable to Debug Azure Functions from VS2017

### ISSUE THREAD

**Issue by prawin2k** [Azure/azure-functions-core-tools#568]
We are unable to debug the Azure Functions (we tried Timer, HTTP & Cosmos DB) locally in VS 2017 after the 2.2.2 CLI Tools got downloaded . Everything was working perfect before that.

![2 2 2-downloading](https://user-images.githubusercontent.com/10738750/42179075-370c0e10-7e22-11e8-88ca-b0793d5defe1.png)

Below is the screen capture of the releases.

![versionfolder](https://user-images.githubusercontent.com/10738750/42179081-3b63005e-7e22-11e8-8668-2a2c7e626829.png)

Environment summary
VS 2017
CLI Tools 2.2.2
Azure Functions Runtime 2.0
Target Framework: .NET Standard 2.0

**Comment by ahmelsayed** [comment]
What are you seeing exactly?

**Comment by ahmelsayed** [comment]
Thanks for the update @prawin2k 
closing this issue.
