### ISSUE TITLE
Please deprecate 2.0.1-beta1.15 on npmjs.org

### ISSUE THREAD

**Issue by Tjeerd-menno** [Azure/azure-functions-core-tools#570]
When using the 2.0.1 beta branch.

Currently the 9 month old version 2.0.1-beta1.15 keeps showing up as "wanted" when running npm -g outdated. 

If you would deprecate that package the actual latest beta version should show up as wanted and fix the usage of npm update -g.

https://www.npmjs.com/package/azure-functions-core-tools

**Comment by ahmelsayed** [comment]
done. Thanks for the heads up, I didn't notice it before.
