### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by kamransadique** [Azure/azure-functions-core-tools#571]
Process:               func [47112]
Path:                  /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.31/func
Identifier:            func
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        sh [47096]
Responsible:           Terminal [47094]
User ID:               501

Date/Time:             2018-07-04 19:24:09.834 -0700
OS Version:            Mac OS X 10.11.6 (15G21013)
Report Version:        11
Anonymous UUID:        A91AF47F-6822-0C35-70EA-5C4D5F1E8348

Sleep/Wake UUID:       5B2DAD75-260B-46C9-86F4-98C94699602F

Time Awake Since Boot: 1000000 seconds
Time Since Wake:       3400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.31/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by kamransadique** [comment]
Running func on the command line generates the following error on OSX El Capitan 10.11.6:

mimacbook:~ kamran$ func
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.31/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.31/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

**Comment by yilazius** [comment]
Running into this problem as well on the latest Azure.Functions.Cli.osx-x64.2.0.1-beta.35.zip :
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.35/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/azure-functions-core-tools/2.0.1-beta.35/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

fish: 'func' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
Is there a specific version I can downgrade to in order to fix it or do I really have to upgrade my Mac?

Thanks!

**Comment by yilazius** [comment]
I ended up upgrading to MacOS High Sierra. 
After that I needed to install the xcode command-line-utils to fix
```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing; `git config --local --replace-all homebrew.analyticsmessage true` exited with 1.
==> Installing azure-functions-core-tools from azure/functions
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing; `git config --local --replace-all homebrew.private true` exited with 1.
```
Which can be done with `xcode-select --install`

**Comment by zavr-1** [comment]
Is it not possible to support el capitan? on macbook late 2008 it's not possible to install anything after it?

**Comment by ahmedelnably** [comment]
Closing as stale
