### ISSUE TITLE
Cannot launch V2 function from Visual Studio

### ISSUE THREAD

**Issue by sanderaernouts** [Azure/azure-functions-core-tools#574]
# Problem
When I try to debug a V2 function from Visual Studio the launched process exits immediately. There is no error visible the console just comes up very briefly and exits again and I cannot find any log files. I ran with `fusionlog` enabled and I do not see any assembly binding errors as well.

I tried running it using `func.exe` from the function cli by installing `azure-functions-core-tools 2.0.1-beta31` using chocolatey, I am able to run the function using `func host start` 

I noticed a message this morning when running my function saying the CLI needed to update itself, looks like it stopped working after that.

# Repro
[FuntionApp.zip](https://github.com/Azure/azure-functions-core-tools/files/2180251/FuntionApp.zip)

# Workaround
Set a specific version of the functions CLI in project properties:
![image](https://user-images.githubusercontent.com/6184673/42510952-caccf6c6-8450-11e8-9c60-4cc3133b3984.png)

# Visual Studio versions:
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.8.0 Preview 3.0
VisualStudio.15.Preview/15.8.0-pre.3.0+27825.0
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise
....
Azure App Service Tools v3.0.0   15.8.03047.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.8.03047.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.9.0-beta4-63012-01. Commit Hash: a247597aa0b2459ac9551677edeeead6c6e08ba3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.2
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10518.2
...
Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by dlalex83** [comment]
You should now be able to only have the actual arguments in there (e.g. "host start --port 7070) without the path to the dll. That fixed it for me.

Cheers

**Comment by JohnReeson** [comment]
Probably the same [issue](https://github.com/Azure/azure-functions-core-tools/issues/559).

**Comment by ahmelsayed** [comment]
Closing old issue. Please open another one if you're still running into any issues.
