### ISSUE TITLE
Unable to setup HTTPS for Azure Function project within Visual Studio

### ISSUE THREAD

**Issue by sirjameswood** [Azure/azure-functions-core-tools#578]
**Problem**

I am unable to setup HTTPS for an Azure Function project within Visual Studio. When running within Visual Studio the message `The host is taking longer than expected to start` is repeatedly displayed.

Related to [How to run Azure Function locally within Visual Studio on HTTPS?](https://stackoverflow.com/questions/51269657/how-to-run-azure-function-locally-within-visual-studio-on-https/51274883)

**Reproduction Steps**

1. Open Visual Studio.
2. New Azure Functions project (C#), 
3. Select Azure Functions v1 (.NET Framework).
4. Select Http Trigger.
5. Open PowerShell as Administrator, run:
```
$cert = New-SelfSignedCertificate -Subject localhost -DnsName localhost -FriendlyName "Functions Development" -KeyUsage DigitalSignature -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.1")

Export-PfxCertificate -Cert $cert -FilePath certificate.pfx -Password (ConvertTo-SecureString -String password -Force -AsPlainText)
```
6. Copy certificate.pfx into project root.
7. Open project properties, open debug tab, enter the following as Application Arguments, save.

```
host start --port 7112 --useHttps --cors * --cert certificate.pfx --password password
```
8. Start project from with Visual Studio (e.g. F5).
9. Azure Functions Cli loads up to `Job host started`, then the message `The host is taking longer than expected to start` is repeatedly displayed (seemingly forever).

**Versions**

```
Microsoft Windows 10 Pro - 10.0.17134 Build 17134

Azure Functions Cli - 1.0.12

Microsoft Visual Studio Enterprise 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03056

Visual C++ 2017  
Microsoft Visual C++ 2017
Application Insights Tools for Visual Studio Package   8.12.10405.1
ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET Core Razor Language Services   15.7.31476
ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
Azure App Service Tools v3.0.0   15.0.40608.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.3.3000.2
Azure Functions and Web Jobs Tools   15.0.40608.0
Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
C# Tools   2.8.3-beta6-62923-07. 
Common Azure Tools   1.10
Fabric.DiagnosticEvents   1.0
GhostDoc   5.5.17070.0
GitHub.VisualStudio   2.2.0.10
JavaScript Language Service   2.0
JavaScript Project System   2.0
Microsoft Azure HDInsight Azure Node   2.3.3000.2
Microsoft Azure Hive Query Language Service   2.3.3000.2
Microsoft Azure Service Fabric Tools for Visual Studio   2.2
Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Microsoft Azure Stream Analytics Node   1.0
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2
Microsoft Continuous Delivery Tools for Visual Studio   0.3
Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0
Microsoft Visual C++ Wizards   1.0
Microsoft Visual Studio Tools for Containers   1.1
Microsoft Visual Studio VC Package   1.0
Node.js Tools   1.4.11027.3
NuGet Package Manager   4.6.0
ProjectServicesPackage Extension   1.0
Redgate ReadyRoll   1.14.17.5347
Redgate SQL Prompt   8.2.5.2924
ResourcePackage Extension   1.0
SQL Server Data Tools   15.1.61804.210
ToolWindowHostedEditor   1.0
TypeScript Tools   15.7.20419.2003
Visual Basic Tools   2.8.3-beta6-62923-07. 
Visual F# Tools 10.1 for F# 4.1   15.7.0.0. 
Microsoft Visual F# Tools 10.1 for F# 4.1
Visual Studio Code Debug Adapter Host Package   1.0
Web Compiler   1.11.326
```

**Comment by pragnagopa** [comment]
I cannot repro this issue. I tried both with VS 2017 and VS Code. 
```
Microsoft Visual Studio Enterprise 2017 
Version 15.7.5
VisualStudio.15.Release/15.7.5+27703.2042
Microsoft .NET Framework Version 4.7.03056
Azure Functions and Web Jobs Tools   15.0.40617.0
```

Can you please check if you have latest version of [AzureFunctionsandWebJobsTools](https://marketplace.visualstudio.com/items?itemName=VisualStudioWebandAzureTools.AzureFunctionsandWebJobsTools)?
Also, by default VS 2017 still using 1.3.0 version of Azure Functions CLI. Are you manually updating func.exe used by VS?

**Comment by ferantivero** [comment]
@sirjameswood just in case it helps in your scenario, I've faced some issue trying to customize the port where the host is not being able to start nor shutdown. Most probably in my case it was a conflict with the ports numbers I was trying to use... 

Just in case you want to give a try with another port or just let this to use the default one...

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
