### ISSUE TITLE
--docker flag unsupported for Java 

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#585]
![image](https://user-images.githubusercontent.com/8435148/42923408-2fc916d8-8ada-11e8-8ab3-a284d18129ab.png)

`func init` with `--docker` flag should not be supported for Java, since no Linux image is available at the moment.

**Comment by asavaritayal** [comment]
I was thinking don't show Java if the `--docker` option is specified.

**Comment by Pamir** [comment]
Hi 
Is there any way to put custom azure functions jar file into a container, which is generated by maven archtype?.

**Comment by kshyju** [comment]
Closing since we have docker support for java today. If you encounter any problems with the latest version of the core tools, please open a new issue.
