### ISSUE TITLE
Customizing the azurefunctions config file

### ISSUE THREAD

**Issue by OrRosenblatt** [Azure/azure-functions-core-tools#59]
The current .azurefunctions configuration file is created with the default setting:
```
{
  "DisplayLaunchingRunServerWarning": true
}
```
I would love a way to set these settings from an external location (perhapse func.exe argument) since we are using several build servers to test azure functions locally and it's impossible to change the settings manually.

**Comment by ahmelsayed** [comment]
yep, I need to add that, just never got around to actually doing it.

**Comment by OrRosenblatt** [comment]
Seems that it's still not fixed. 

The build server image recently changed and the error started recurring. It's a **major issue** since part of the CI runs automatic tests on the function before pushing it to production and this setting needs to be treated manually every time.

**Comment by ahmelsayed** [comment]
Closing obsolete issue since v2 doesn't use any global config files.
