### ISSUE TITLE
Remove hard coding of -azurefunc from Name of generated container image

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-functions-core-tools#595]
It is likely that the name of the project being created will denote that it is a function or serverless. First go at this yeilded `tryingfunctionsinaks-azurefunc` as my image name; having no idea where it came from.

https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/DeployActions/DeployFunctionAction.cs#L106

**Comment by ahmelsayed** [comment]
@yaron2 is this okay with you?

**Comment by yaron2** [comment]
Yes.
