### ISSUE TITLE
func new func (Mac) doesn't use 2.0 of runtime

### ISSUE THREAD

**Issue by alexjamesbrown** [Azure/azure-functions-core-tools#597]
If I run 
> func new func

And complete the wizard, the generated files are amongst other things, run.csx

... not a class lib?

Is there a way to select this, or have I not got it installed?

Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0

**Comment by ahmelsayed** [comment]
you need to update to `>= 2.0.1-beta.29`, The current release is `2.0.1-beta.33`. Just update your core tools version and then 

```
mkdir functions
cd functions
func init . --worker-runtime dotnet
func new
```

That should generate a csproj for you and `func new` will create a `.cs` function that needs to be compiled. To run it you'll have to either do 

```bash
dotnet build
func start --prefix Debug/netstandard2.0/ # or where ever the output is
```

or do 

```
func start --build
```

Which will take care of the building and running
