### ISSUE TITLE
How to set Run configuration to consume new version cli in Visual Studio for Mac?

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-core-tools#599]
I want to run my azure function with new function cli, as VS for Mac still leverages old version.

I download cli 2.0.1-beta.33 to desktop and do run configurations as below, but it doesn't work. Functions still run on old version cli. 

Have I done something wrong? Do I have to use VS Code so that I don't need to run `func` manually in output directory?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/6LFZo.png

**Comment by ahmelsayed** [comment]
@jeffhollan do you know who from VS for Mac can answer this?

**Comment by JohnReeson** [comment]
Closed as I can update VS to consume new cli right now and it actually doesn't block the development.
