### ISSUE TITLE
Incorrect Proxy Endpoint Shown

### ISSUE THREAD

**Issue by JamesRandall** [Azure/azure-functions-core-tools#602]
Proxies are having "api" inserted into their paths when displayed in the CLI tools on startup. For example I have a proxy defined as:

"OpenApiProviderProxy": {
    "matchCondition": {
        "route": "/openapi/{name}",
        "methods": [
            "GET"
        ]
    },
    "backendUri": "https://localhost/api/OpenApiProvider?name={name}"
}

When the local environment starts up it is shown as:

OpenApiProviderProxy: http://localhost:7071/api/openapi/{name}

Although it is available on the correct endpoint of http://localhost:7071/openapi

Can confirm this occurs on beta-31 and beta-33.

**Comment by safihamid** [comment]
The fix is merged and should be available on next release of functions core tools cli

**Comment by JohnReeson** [comment]
occurs on beta-34 also.

**Comment by JohnReeson** [comment]
Confirm fixed in beta-35.
