### ISSUE TITLE
Node version error is not accurate

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-core-tools#604]
I see the following in my logs when debugging a JavaScript function:
> Your Function App is currently set to use Node.js version v8.11.3, but the runtime requires a 10.x version.
> For deployed code, please change WEBSITE_NODE_DEFAULT_VERSION in App Settings. On your local machine, you can change node version using 'nvm' (make sure to quit and restart your code editor to pick up the changes)

But that's inconsistent with the docs here https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version-and-package-management, plus I'm just assuming LTS would be supported. Everything seems to work for me.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-nodejs-worker#107
