### ISSUE TITLE
Red text should be reserved for errors

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-core-tools#605]
When I start debugging in VS Code, it looks like I have a bunch of errors::
![screen shot 2018-07-30 at 2 11 57 pm](https://user-images.githubusercontent.com/11282622/43423916-8d386cf2-9402-11e8-98d2-3d21fd72d1c4.png)

But I believe this text is just informational:
> Debugger listening on ws://127.0.0.1:5858/4a669756-4fc5-4461-9420-d1e18479ecb3
> For help see https://nodejs.org/en/docs/inspector

And the other red text shouldn't be an error at all (See https://github.com/Azure/azure-functions-core-tools/issues/604)

**Comment by pragnagopa** [comment]
Issue https://github.com/Azure/azure-functions-host/issues/3187 is tracking fixing logs.
