### ISSUE TITLE
macOS X homebrew installation is broken (2.0.1-beta.34)

### ISSUE THREAD

**Issue by rpus** [Azure/azure-functions-core-tools#609]
... mismatched SHAsum as in #551 it seems:

```
==> Upgrading 6 outdated packages, with result:
azure/functions/azure-functions-core-tools 2.0.1-beta.32 -> 2.0.1-beta.34, azure-cli 2.0.42 -> 2.0.43, libpng 1.6.34 -> 1.6.35, gdbm 1.16 -> 1.17, yarn 1.7.0 -> 1.9.2, node 10.7.0 -> 10.8.0
==> Upgrading azure/functions/azure-functions-core-tools 
==> Downloading https://functionscdn.azureedge.net/public/2.0.1-beta.34/Azure.Fu
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 44082FD0B056E8ED546B7515C60DDE829952A6D63EED5CA4E009002396329C22
Actual: 44082fd0b056e8ed546b7515c60dde829952a6d63eed5ca4e009002396329c22
Archive: /Users/khalidkhan/Library/Caches/Homebrew/azure-functions-core-tools-2.0.1-beta.34.zip
To retry an incomplete download, remove the file above.
```

**Comment by beraybentesen** [comment]
Expected: 44082FD0B056E8ED546B7515C60DDE829952A6D63EED5CA4E009002396329C22
Actual: 44082fd0b056e8ed546b7515c60dde829952a6d63eed5ca4e009002396329c22

**Comment by pas725** [comment]
Getting same error!

Error: SHA256 mismatch
Expected: 44082FD0B056E8ED546B7515C60DDE829952A6D63EED5CA4E009002396329C22
Actual: 44082fd0b056e8ed546b7515c60dde829952a6d63eed5ca4e009002396329c22

**Comment by GloriousRedLeader** [comment]
Same error!

$ brew install azure-functions-core-tools
==> Installing azure-functions-core-tools from azure/functions
==> Downloading https://functionscdn.azureedge.net/public/2.0.1-beta.34/Azure.Functions.Cli.osx-x64.2.0.1-beta.34.zip
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 44082FD0B056E8ED546B7515C60DDE829952A6D63EED5CA4E009002396329C22
Actual: 44082fd0b056e8ed546b7515c60dde829952a6d63eed5ca4e009002396329c22
Archive: /Users/arthur_olliff/Library/Caches/Homebrew/azure-functions-core-tools-2.0.1-beta.34.zip
To retry an incomplete download, remove the file above.

**Comment by amlaakso** [comment]
You can fix it by copying the lower case version of the SHA256 into the `/usr/local/Homebrew/Library/Taps/azure/homebrew-functions/Formula/azure-functions-core-tools.rb` file as @travisnielsen suggests in the comments of #551.

**Comment by rpus** [comment]
@amlaakso That's a useful unblocker to learn about; thanks for the direction.

I'll wait until the developers make repairs though, especially since #551 was caused by the wrong artefact's SHAsum getting used, whereas the present issue indicates a different problem/process worth fixing at source, as it's a *case* difference in what would otherwise be the right string.

**Comment by beraybentesen** [comment]
@amlaakso We shouldn't fix like that.

I had to stop local development due to this problem. Publishing library even without testing on platform does not make sense, especially for Microsoft.

**Comment by ahmelsayed** [comment]
Should be fixed now.

**Comment by johnpapa** [comment]
I am seeing this same issue now. 

Should I be? What' is the solution?

**Comment by johnpapa** [comment]
Thanks. It seems fixed now ... what was the fix?
