### ISSUE TITLE
Attempt error reporting for zip file uploads

### ISSUE THREAD

**Issue by cfjedimaster** [Azure/azure-functions-core-tools#611]
While using zip uploads 

    az functionapp deployment source config-zip -g myResourceGroup -n <app_name> --src <zip_file_path>

I noticed an odd issue. The first time I tried it, I zipped it from a parent directory. So if foo was the folder with my function app, I zipped from the parent foo. This created a zip file where the *root* was a foo folder and not the contents of foo. (Obviously those contents were in there, just not at root.)

When I deployed, the CLI reported no issue with the zip. It took me a while to realize that I was zipped incorrectly. But the CLI never reported anything weird or wrong with the zip. If it had done so, it would have saved me quite a bit of time.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-cli#7072
