### ISSUE TITLE
func host start - v1.x wont run with version 9.0 of newtonsoft.json

### ISSUE THREAD

**Issue by xairrick** [Azure/azure-functions-core-tools#627]
When trying to run a Azure Function from Visual Studio  I'm getting the following error;

```
An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = WebScriptHostManager (DelegateActivator), Services = [Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> The type initializer for 'Microsoft.Azure.WebJobs.Script.Utility' threw an exception. (See inner exception for details.)
```

If re-compile the Azure.Functions.Cli  with the latest version of newtonsoft.json(11.0.2) and replace the content of the `C:\Users\<YOURNAME>\AppData\Local\AzureFunctionsTools\Releases\1.3.0\cli`  with new build it works.   

See also -> https://github.com/Azure/azure-functions-host/issues/2780

**Comment by ahmelsayed** [comment]
This is by design in V1. I don't think this will change. See [this](https://github.com/Azure/azure-functions-host/issues/992) for more details

**Comment by xairrick** [comment]
At the very least the inner exception should be aloud to bubble to the user so they have a clue to what the issue.
