### ISSUE TITLE
Kubernetes Deployment doesnt work with private registries

### ISSUE THREAD

**Issue by swgriffith** [Azure/azure-functions-core-tools#632]
In order to use a custom registry, like Azure Container Registry you need to tell kubernetes the registry login info via a docker credential secret and then need to reference that secret in the pod definition as an imagePullSecret. Need to update to allow users to pass in the image pull secret and then include that image pull secret in the deployment template. I'll try to get it updated locally and will submit a PR if it works.

**Comment by jmo808** [comment]
I usually do this with attaching the imagepullsecret to a namespace service account. See below:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by yaron2** [comment]
Closed via #1137
