### ISSUE TITLE
v1 CLI shows proxy name instead of route

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-core-tools#639]
Use proxies.json as below.
```
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "proxy1": {
      "matchCondition": {
        "route": "mock/getwelcomemessage",
        "methods": [
          "GET"
        ]
      },
      "backendUri": "http://localhost/api/AnotherFunction"
    }
  }
}
```

The cli(v1.0.14) output shows `proxy1: http://localhost:7071/api/proxy1` while the route `http://localhost:7071/mock/getwelcomemessage` does work as expected.

I also found in v2 cli(2.0.1-beta.35) output, it shows proxy route.

**Comment by ahmelsayed** [comment]
closed in #645
