### ISSUE TITLE
func start not copying local.settings.json to output

### ISSUE THREAD

**Issue by unsafecode** [Azure/azure-functions-core-tools#643]
That happens since `<CopyToPublishDirectory>Never</CopyToPublishDirectory>` is set in the generated `.csproj` file. However, this prevents application settings from working properly during development.

**Comment by ahmelsayed** [comment]
Fixed in https://github.com/Azure/azure-functions-core-tools/commit/f6cb723ed2aad39cc521b00df33e22370b146b03
