### ISSUE TITLE
Unable to specify Types in Azure Table Storage when written by a Javascript Function

### ISSUE THREAD

**Issue by jon-shipley** [Azure/azure-functions-core-tools#648]
I have a function that reads from a queue and writes to table storage.  The issue is that nearly all fields are written as `String` fields, and attempting to type hint them to DateTime, or GUID does not work.

E.g.
```
data = {
  partitionKey: 'abcdefgh',
  rowKey: '1234',
  myDate: new Date()
}
```

The DateTime is NOT inferred dynamically and dates are written as Strings.

Attempting to use the [information provided](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cosmos-db/table-storage-how-to-use-nodejs.md#add-an-entity-to-a-table) results in a String being written:

E.g.
```
data = {
  partitionKey: 'abcdefgh',
  rowKey: '1234',
  myDate: {'_': new Date(), '$': 'Edm.DateTime'}
}
```

Results in `myDate` having a date set to string type with the value `{  "_": "2018-08-21T11:49:52.404Z",  "$": "Edm.DateTime"}` 

Expected output would have the field set to DateTime type with the date as the value.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1858
