### ISSUE TITLE
Error message outdated? `Must specify extension package name and verison`

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-core-tools#655]
I tried doing `func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB` and got an error message `Must specify extension package name and verison`. I think this is outdated, since I really just needed to do `func extensions install Microsoft.Azure.WebJobs.Extensions.CosmosDB`

https://github.com/Azure/azure-functions-core-tools/blob/14021106de7764fd3b2c0feaee4c3858823e2eb4/src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs#L89

**Comment by ahmelsayed** [comment]
`func extensions install Microsoft.Azure.WebJobs.Extensions.CosmosDB` is not a valid command. or at least the `Microsoft.Azure.WebJobs.Extensions.CosmosDB` part is ignored. Doing `func extensions install` will install all the extensions based on your bindings in `functions.json`

If you want to install a specific extension like `Microsoft.Azure.WebJobs.Extensions.CosmosDB`, then you'll have to specify both `--package Microsoft.Azure.WebJobs.Extensions.CosmosDB` and `--version`
