### ISSUE TITLE
System.InvalidOperationException: 'Please verify that the Azure Storage Emulator is running.'

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-functions-core-tools#657]
Hi,

I m running an .Net Core 2.1.2 WebJob on localhost with these Settings:

		"AzureWebJobsDashboard": "UseDevelopmentStorage=true",
		"AzureWebJobsStorage": "UseDevelopmentStorage=true",

Here is Program.cs:

        public static IConfigurationRoot Configuration { get; set; }

        private static ConnectionStringsSettings _connectionStringsSettings;
        private static ConnectionStringsSettings ConnectionStringsSettings
        {
            get
            {
                return _connectionStringsSettings ?? (_connectionStringsSettings = Configuration
                    .GetSection("ConnectionStrings")
                    .Get<ConnectionStringsSettings>()
                );
            }
        }

        public static async Task Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureAppConfiguration((_, configuration) =>
                {
                    configuration.AddJsonFile("appsettings.json", optional: true);
                    configuration.AddJsonFile("appsettings.Development.json", optional: true);
                    configuration.AddEnvironmentVariables();

                    if (args != null)
                    {
                        configuration.AddCommandLine(args);
                    }

                    Configuration = configuration.Build();
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddOptions();
                    services.Configure<ConnectionStringsSettings>(hostContext.Configuration.GetSection("ConnectionStrings"));
                    services.Configure<AzureStorageSettings>(hostContext.Configuration.GetSection("AzureStorage"));
                    services.AddApplicationInsightsTelemetry(hostContext.Configuration);
                    services.AddSingleton<IVideosQueueService, VideosCompressorQueueService>();
                })

                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddConsole();
                })
                .Build()
                .EnsureQueueExists();

            var jobHostConfiguration = new JobHostConfiguration
            {
                JobActivator = new JobActivator(host),
                DashboardConnectionString = ConnectionStringsSettings.AzureWebJobsDashboard,
                StorageConnectionString = ConnectionStringsSettings.AzureWebJobsStorage
            };

            var webjob = new JobHost(jobHostConfiguration);
            webjob.RunAndBlock();
        }

        public static IHost EnsureQueueExists(this IHost host)
        {
            var videosQueueService = host.Services.GetRequiredService<IVideosQueueService>();
            videosQueueService.EnsureQueueExistsAsync().Wait();
            return host;
        }

JobActivator.cs:
    public class JobActivator : IJobActivator
    {
        private readonly IHost _host;

        public JobActivator(IHost host)
        {
            _host = host;
        }

        public T CreateInstance<T>()
        {
            return _host.Services.GetService<T>();
        }
    }

And QueueFunctions.cs:
    public class QueueFunctions
    {
        private readonly IOptions<AzureStorageSettings> _azureStorageSettings;
        private readonly ILogger<QueueFunctions> _logger;

        public QueueFunctions(
            IOptions<AzureStorageSettings> azureStorageSettings,
            ILogger<QueueFunctions> logger
        )
        {
            _azureStorageSettings = azureStorageSettings;
            _logger = logger;
        }

        public async Task ProcessAsync([QueueTrigger(Constants.Queues.Videos)] string text)
        {
            Console.WriteLine(text);
        }
    }

When I run it I have this error:
![image](https://user-images.githubusercontent.com/1764519/44534044-ddd00b00-a6c4-11e8-9ca4-16309b5724a6.png)

Is there a problem with the new Host Builder added in .Net Core 2? And most probably did I miss something in my code?

**Comment by ranouf** [comment]
To make it work, I needed to update to pre-release version for:
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta5" />

Now Every thing work correctly

**Comment by ahmelsayed** [comment]
I'm assuming you're not using the core tools, since you have your own `Main` method, right? This probably belong in https://github.com/Azure/azure-functions-host
