### ISSUE TITLE
Add "clientCertEnabled" support for core tools

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#663]
Per this [UserVoice item](https://feedback.azure.com/admin/v3/suggestions/31401418/activity)

**Comment by ahmelsayed** [comment]
`clientCertEnabled` is a platform feature, not a functions feature. It's handled on the frontEnd

If you want to be able to use that locally, we'll have to implement that in the runtime itself.

**Comment by shurane** [comment]
Since it's on the runtime, should an issue be made on https://github.com/Azure/azure-functions-host instead, @jeffhollan?

**Comment by ahmelsayed** [comment]
What’s the goal here? Currently we don’t have any auth providers enabled locally because all auth in Azure comes from the platform itself. We should discuss authentication in general in the context of local development, not just client cert.

**Comment by shurane** [comment]
In the original [feedback link](https://feedback.azure.com/forums/355860-azure-functions/suggestions/31401418-add-clientcertenabled-support-for-local-developm), it is for debugging and unit-testing locally. It seems like it falls under 'nice to have'.

Isn't accepting client certificates a little different than having an auth provider like AAD? And what does authentication for local development look like?

**Comment by ahmelsayed** [comment]
There is no auth at all for local development at the moment.

**Comment by shurane** [comment]
Is the best way to test an authentication provider to deploy to an Azure resource and go from there? That is, not rely on local development for any authentication scenarios.
