### ISSUE TITLE
Unable to install azure-functions-core-tools via HTTP_PROXY on Windows 10

### ISSUE THREAD

**Issue by yoshiomura** [Azure/azure-functions-core-tools#665]
Hi, 

I am unable to install azure-functions-core-tools via HTTP_PROXY.

npm -g config set proxy "http://127.0.0.1:808"
npm -g config set https-proxy "http://127.0.0.1:808"
npm -g config set registry "http://registry.npmjs.org/"
npm install azure-functions-core-tools@core

npm ERR! code E418
npm ERR! 418 I'm a teapot: azure-functions-core-tools@core

Would you help me to install the tool via Proxy ?

Node: v9.3.0
npm: 5.5.1
OS: Windows 10

Thanks

**Comment by yoshiomura** [comment]
Hi
I was able to install Node.js v6.14.4 and npm 3.10.10. 
Please let me know and close if it is known issue.

**Comment by yoshiomura** [comment]
Hi,

I was able to install by downgrading Node.js and npm.

Node.js: v6.14.4
npm: 3.10.10

Please let me know if it is known issue.
Thanks

**Comment by ahmelsayed** [comment]
try  setting your registry to https instead of http
```
npm -g config set registry "https://registry.npmjs.org/"
```


Also keep in mind if you're writing javascript function, you have to use node 8 at minimum.
