### ISSUE TITLE
Update the CLI to use the latest templates

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-core-tools#667]
Adding cosmosDbTrigger installs extensions  without user needing to run 
```
func extensions install
```
Since storage moved to extensions, we should do the same for Queue and Blob triggers

**Comment by pragnagopa** [comment]
@soninaren - Can you please look into this?

**Comment by ahmelsayed** [comment]
this should be part of the template, right?

**Comment by soninaren** [comment]
Yes this is part of template. I already have the template update ready, will update the CLI to use the latest templates. Changing the issue title

**Comment by ahmelsayed** [comment]
This is done I believe
