### ISSUE TITLE
Build in release mode when publishing

### ISSUE THREAD

**Issue by janaagaard75** [Azure/azure-functions-core-tools#670]
How can I make the `publish` command build in release mode? I would have expected a command line option to be able to select configuration, similar to `dotnet`'s `--configuration` option.

    # How to make this compile in release mode?
    func azure functionapp publish {name-of-my-function-app}

**Comment by ahmelsayed** [comment]
with  2288298 you have 2 options. 

1. You can build your project with your own command line using something like 

```bash
dotnet build --output /tmp/output --configuration Release ....
cd /tmp/output
func azure functionapp publish {appName} --no-build
```

2. or you can pass additional params to dotnet cli using 

```bash
# --dotnet-cli-params  When publishing dotnet functions, the core tools calls 'dotnet build --output bin/publish'. Any parameters passed to this will be appended to the command line.


func azure functionapp publish {appName} --dotnet-cli-params -- "--configuration Release"

# the extra -- are needed to escape the `--` in the value. 
# for example in this case the cli will run 
# dotnet build --output bin/publish --configuration Release
# You can see all the commands the cli runs behind the scene is you set CLI_DEBUG=1
```

Let me know if you have any questions.

**Comment by janaagaard75** [comment]
Thanks a lot for clarifying this. No further questions. :)
