### ISSUE TITLE
Add ability to get HTTP-triggered Function's URL

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-core-tools#678]
after using `func azure functionapp publish` it'd be great if I could then interrogate the functions that were published and get back the trigger URLs for the HTTP-Triggered ones.

I'm thinking something like:
~~~
C:\Users\hurlburb\Projects\GitHub\serverless-big-data-map-reduce [brandonh/redux ≡]> func azure functionapp list-functions myfuncappv2
Functions in myfuncappv2:
    Begin - [orchestrationTrigger]
    GetFileListAsync - [activityTrigger]
    StartAsync - [httpTrigger - https://myfuncappv2.azurewebsites.net... ]
    WriteToBlob - [activityTrigger]
~~~

or even target a specific function and ask for it with a  new CLI command like `func azure functionapp get-url myfuncappv2 StartAsync`

I played with both Functions CLI and Azure CLI and couldn't readily see a way to get this.

**Comment by ankitkumarr** [comment]
Hi @brandonh-msft, I believe running `func azure functionapp list-functions <func-name>` lists the functions with URLs (where present). Let me know if that's not what you are looking for.

I do agree that it would be nice to also have that information show up right after publishing. I will make a PR to make that happen.

**Comment by brandonh-msft** [comment]
nah, it doesn't:
![image](https://user-images.githubusercontent.com/20270743/45466769-73077200-b74e-11e8-9cc8-b7cb6fe4a491.png)

**Comment by ankitkumarr** [comment]
I believe you are using pre-release v2.0.1-beta.35 or older. Version 2.0.1-beta.36 onward shows the URLs.

**Comment by brandonh-msft** [comment]
aha you are correct however I just had something quite odd happen:

~~~
C:\WINDOWS\system32> func azure functionapp list-functions [redacted]
Functions in [redacted]:
...
    StartAsync - [httpTrigger]
...

C:\WINDOWS\system32> func

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.0.1-beta.38)
~~~
notice the lack of a URL despite me running beta 38

I then ran the same command again immediately:
~~~
C:\WINDOWS\system32> func azure functionapp list-functions [redacted]
Functions in [redacted]:
...
    StartAsync - [httpTrigger]
        Invoke url: https://[redacted].azurewebsites.net/api/StartAsync
...
~~~

that time it showed up. very weird.
Worth noting the first time I ran the `list-functions` command, it took quite a long time to come back; possible there was a failure in the request and so it bailed in trying to determine the URL?

Despite this, **there's still a bug here** because the *actual* URL for `StartAsync` includes a functionkey code because I've implemented Function-level authentication:
![image](https://user-images.githubusercontent.com/20270743/45468714-ae0ea300-b758-11e8-83dd-f0606a608bd1.png)

**Comment by ankitkumarr** [comment]
That does sound odd. I haven't been able to reproduce it and looking at the code, nothing jumps out that could cause this. Ideally, if you do see the template name (`httpTrigger`), you should see the url as well (as the request to the server was successful). Let me know if something like that happens again @brandonh-msft.

Speaking of not showing the functionkey in the URL, yes, that seems like a bug. I will update my PR to address that. Thanks!

**Comment by brandonh-msft** [comment]
Sounds good I'll let you know if I'm able to find a way to faithfully reproduce this.
