### ISSUE TITLE
Show Function URLs on publish

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#682]
When publishing an HTTP triggered function that uses function key auth, it is impossible for the user to figure out the function url without having to go to the portal. It'll be great if we could print the URLs to the console.

**Comment by ankitkumarr** [comment]
Hi @asavaritayal, If you mean showing the URL for any HTTP triggered function, I think the PR for https://github.com/Azure/azure-functions-core-tools/issues/678 (PR link - https://github.com/Azure/azure-functions-core-tools/pull/707) should solve this problem.

Please let me know if you are talking about something specific to function that uses function key auth.

**Comment by asavaritayal** [comment]
Yes, the PR should resolve this issue. Thanks for looking into it.
