### ISSUE TITLE
Publish 2.0.1-beta.36 on NPM

### ISSUE THREAD

**Issue by ltouro** [Azure/azure-functions-core-tools#685]
The  `azure-functions-core-tools` package on NPM was not updated with the .36 beta release yet.

```sh
λ npm i -g azure-functions-core-tools@2.0.1-beta.36
npm ERR! code ETARGET
npm ERR! notarget No matching version found for azure-functions-core-tools@2.0.1-beta.36
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by ahmelsayed** [comment]
this should be updated to the latest (`2.0.1-beta.37`) now. Sorry there were few cli specific issues that I wanted to be part of this release, so it didn't quite align with the runtime release. 

it should be updated now.
