### ISSUE TITLE
Lacking Azure Powershell cmdlet to deploy function apps

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-core-tools#686]
There are things we can do with Azure PowerShell that we can't do with Azure CLI - for instance, [create Application Insights resources](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-powershell) in Azure.

This means to automate the deployment of a Function app + Application Insights, I've got to use two different CLIs; Azure PowerShell and Azure CLI. If Functions were deployable with Azure PowerShell, we could do this all within one environment and, more importantly, **one login prompt**.

If this is possible today, then we need to have instructions [in our docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli) on the necessary commands to make it happen.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-powershell#7133
