### ISSUE TITLE
Choco should support 64 bit install of cli

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-core-tools#693]
As of today, choco only seems to include the x86 version of the functions cli: https://chocolatey.org/packages/azure-functions-core-tools
![screen shot 2018-09-04 at 9 48 10 am](https://user-images.githubusercontent.com/11282622/45045401-ae57c180-b027-11e8-9149-0e4d70c4ade1.png)

However, VS Code only supports debugging 64 bit processes (see https://github.com/OmniSharp/omnisharp-vscode/issues/1716) so it would be very helpful if you also added 64 bit :)

**Comment by andreasblueher** [comment]
What is the current status on this issue? I can't debug my azure functions and this is suboptimal at best.

**Comment by Arnavion** [comment]
As of today, the only workaround is to install using npm / yarn instead.

**Comment by cgillum** [comment]
For those who prefer to stay away from npm/yarn, here is a workaround that worked for me (copied from [this StackOverflow answer](https://stackoverflow.com/a/55120037/2069)):

1. Run `choco uninstall azure-functions-core-tools`
2. Download nupkg file from [here](https://chocolatey.org/packages/azure-functions-core-tools) (see the _Download_ link)
3. Open the nupkg in [Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and edit the `tools\chocolateyinstall.ps1` script (change `x86` to `x64` in the package URL)
4. Run `choco install azure-functions-core-tools -source . --ignore-checksums` in the folder where edited nupkg file is.

This installed the x64 version of the Azure Functions Core Tools. After I did this, debugging .NET code in VS Code started working for me.

**Comment by gep13** [comment]
@EricJizbaMSFT I work for Chocolatey, and will happily help to get this package working again.  Do you know who is behind the account here on chocolatey.org: https://chocolatey.org/profiles/nugetazurefunctions  It would be good to work with them to get this package updated.

**Comment by ahmedelnably** [comment]
@EricJizbaMSFT as part of the v3 release of the core tools to choco, we will default to x64 of the tools (all other installers are x64 only). v2 will stay on x86, to minimize any chance of breaking users.
@gep13 thanks for offering help, @fabiocav and @ahmelsayed own the package

**Comment by gep13** [comment]
@ahmedelnably thanks for getting back to me, I appreciate it, and am happy to help, so feel free to reach out if you have any questions.  

One thing that would be great to do would be to add additional metadata into the nuspec file for the package to indicate where the package source files reside (ideally a direct link to the folder in the GitHub repository where the packaging files reside) that makes it easier to find the files and to make suggestions/improvements to the package.

**Comment by ankitkumarr** [comment]
We discussed this offline. We will not be changing the default of our package installer to install 64-bit version, to avoid a breaking change. However, as part of this work item, we will add an option to install 64-bit as well.

I am thinking of using a switch in `--params` param such as `--x64`, that we could handle in our powershell script `chocolateyinstall.ps1`., and download the right binaries. 
@gep13, if there's a different recommended way in chocolatey to do this, I would love to hear that :).

**Comment by jeroenhabets** [comment]
@ankitkumarr, @madelinegordon shouldn't this new option be mentioned or rather recommended in the azure-functions-core-tools/README.md? Especially as I understand it will not become the default.

**Comment by ankitkumarr** [comment]
@jeorenhabets, we will add it to the readme once we merge the change in, do a release and have it available for users.

**Comment by DenisBalan** [comment]
@ankitkumarr as per last update of package in choco repo (Last Update: 04 Feb 2020)

x64 flag is present, therefor in this repo readme should be specified that for debugging in vscode, install of azure-functions-core-tools should be done with x64 params explicitly specified.
```
choco install azure-functions-core-tools --params "'/x64:true'"
```

**Comment by ankitkumarr** [comment]
@DenisBalan, yes I will do that when I get a chance. Or, we welcome any contribution as well. If be you'd like to assist with that, please feel free to make a PR :)

**Comment by DenisBalan** [comment]
PR #1813 adds information about x64 installing from choco in README file.
fyi @jeroenhabets , @ankitkumarr please have a look :)

**Comment by jeroenhabets** [comment]
@DenisBalan I cannot test (yet) but the new #### Notice is nice!
