### ISSUE TITLE
Bug when deploying large files

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-core-tools#696]
![deploybug](https://user-images.githubusercontent.com/7645687/45116604-1e3d7900-b108-11e8-8bf4-459c64941670.png)

**Comment by ahmelsayed** [comment]
There are 2 distinct issues here:

1. I'm loading the full zip into memory before sending it. This can cause the out of memory exception if the file is large than 2GB with a 32bit func.exe.

2. reusing a disposed stream.  This is fixed by d563a2c

I still need to look at #1
