### ISSUE TITLE
Core tools not recognised as installed after beta38 update

### ISSUE THREAD

**Issue by GBBBAS** [Azure/azure-functions-core-tools#705]
I updated to Beta38 in vS Code. However, when I try to run “func” commands in terminal or start debugging, VS code States that core tools is not installed and do I want to install. If I say yes, it installs and then when it try’s to build it says that the core tools are not installed and asks to install again? Feels like something is needed in the Path environment variable?

**Comment by ahmelsayed** [comment]
What is your OS?

**Comment by bryceba** [comment]
Windows 7

**Comment by madhavsharmaagra** [comment]
any update to this issue?? I am also falling in to the same pit here...my OS is Windows 10

**Comment by bretheren** [comment]
I think I've just made some progress by adding the below to my Path Environment Variable:
"C:\Users\<Your User Name>\AppData\Roaming\npm;"

**Comment by ahmedelnably** [comment]
Closing as stale, please open a new issue if this is still happening in the latest version of the tools
