### ISSUE TITLE
File path seems to break `func extensions install`

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#722]
When running `func extensions install` I get the following error:

> Please specify one package reference to add.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

> ...

> MSBUILD : error MSB1008: Only one project can be specified.
Switch: 2018\serverless-workshop\Module

The file path to extensions.csproj is:
`E:\Development\Ignite 2018\serverless-workshop\Module 2 - CosmosDB data\extensions.csproj`

When I move to a folder that doesn't have this name (`C:\myApp`) it installs just fine.

**Comment by brandonh-msft** [comment]
dupe of #282

**Comment by jeffhollan** [comment]
Thanks!
