### ISSUE TITLE
Failure to deploy with local node module dependencies installed

### ISSUE THREAD

**Issue by semchev** [Azure/azure-functions-core-tools#736]
**Issue:** When using local modules as libraries via the `"local-module": "file:<path>"` syntax, the deploy will fail due to failure to make a directory.

**Repro steps:**
**Note:** I am using the VS Code extension for this, though I do not think this is relevant based on the error logs, but could be wrong.

1. Create a function app and add a function.
2. Create a folder in the root of the function app for common code (`lib` for example).
3. Create a directory in the lib, and run `npm init`.
4. Create an `index.js` with an export.
5. In the function, declare this lib as a dependency (e.g. `npm install --save ../lib/module-name`)
6. Run `func start`. The app should work as expected.
7. Deploy the function app (again, I am using the VS Code extension).
8. After uploading the source, the deploy should fail.
9. Observing the log files, you should find an error similar to the following:

```
3:08:34 PM repro-local-modules: Creating zip package...
3:08:35 PM repro-local-modules: Starting deployment...
3:08:38 PM repro-local-modules: Fetching changes.
3:08:39 PM repro-local-modules: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\asdf0tsx.zip (1.29 MB) to D:\local\Temp\zipdeploy\extracted
3:08:40 PM repro-local-modules: Cannot create "D:\local\Temp\zipdeploy\extracted\ReproLocalModulesIssue\node_modules\module-name" because a file or directory with the same name already exists.
3:08:49 PM repro-local-modules: Waiting for long running command to finish...
Error: Deployment to "repro-local-modules" failed. See output channel for more details.
```

This does not seem to happen when several functions share a dependency on an externally hosted node module, as the extracted directory is function-specific. However, when using local modules, it appears to cause this issue consistently. When logging into the console and exploring, I deleted `D:\local\Temp\zipdeploy\extracted\ReproLocalModulesIssue\node_modules\module-name`. While the command was running I ran an `ls` and the module appeared. Seconds later, the deploy failed with the above error, implying it is attempting to create this directory again after it already exists.

The app will successfully deploy if the node_modules directory is removed first, however then the app will fail for lacking the required module.

**Comment by ahmedelnably** [comment]
Is this issue still happening?

**Comment by semchev** [comment]
This was 15 months ago. I was unable to use reasonably move forward with Azure Functions for the project in question because of this issue and have not used it since, so I am unaware if it is still an issue.

**Comment by ahmedelnably** [comment]
@semchev we are sorry for the bad experience, if you decide to give Azure Functions another try we are here to support you.
