### ISSUE TITLE
.gitignore file doesn't include Python venv folders

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-core-tools#737]
I think it needs:

```
.python_packages
env
__pycache__
```

**Comment by davidebbo** [comment]
Unfortunately, `env` is an arbitrary name, so we probably can't bake that in the `.gitignore`.

**Comment by ankitkumarr** [comment]
For now, I added the common possible `venv` directories to gitignore.

Should we create separate gitignores for different languages in worker-runtime? For python, we could have a comprehensive gitignore like https://github.com/github/gitignore/blob/master/Python.gitignore

cc/ @ahmelsayed

**Comment by ahmelsayed** [comment]
> Should we create separate gitignores for different languages in worker-runtime?

I think that's a good idea.

**Comment by ankitkumarr** [comment]
I can make a PR for that this week.
