### ISSUE TITLE
Deployment to minikube waits for external IP forever

### ISSUE THREAD

**Issue by krancour** [Azure/azure-functions-core-tools#742]
Using version 2.0.3...

This is because the `Service` resource that gets created is of type `LoadBalancer` and in a minikube cluster (or bare metal cluster), provisioning of an external load-balancer is a no-op.

This could be resolved by giving the option to provision a service of a different type and then _not_ waiting for an external IP if the type isn't `LoadBalancer`. In the minikube scenario, using `NodePort`, for instance, makes a lot of sense.

fwiw, even if running in AKS or on some other managed k8s-aaS, there could still be compelling reasons _not_ to want a `Service` of type `LoadBalancer` for every HTTP-triggered function. For instance, on some cloud providers, you pay per load balancer or for the public IPs used by those load balancers. It's not uncommon to prefer having a single load balancer in front of an `Ingress` controller and then using that to route traffic to `Service`s of type `ClusterIP`.

```
$ func deploy --platform kubernetes --name getmessages --registry krancour
Building Docker image...
Running 'docker build -t krancour/getmessages /Users/kent/kentssecondserverlessapp'...done
Pushing function image to registry...
Running 'docker push krancour/getmessages'.............done
Deploying function to Kubernetes...
Deployment successful
Waiting for External IP...
```

**Comment by scottrudy** [comment]
It's great that the intention is to make deployment easier, but the downside is when hiding all of that is how to continue. I'm stuck here and about to abandon my efforts to get this running. Is there a workaround?
