### ISSUE TITLE
add --resource-group flag for commands like fetch-app-settings

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-core-tools#748]
This was pointed out in another issue (#738) by @VolodymyrLavrenchuk

When using the ARM to get functionapp in commands like `fetch-app-settings`, allow the users to pass in `--resource-group` flag in order to limit the query results.

**Comment by andreasgrimm** [comment]
any news regarding this?

**Comment by ahmedelnably** [comment]
@ankitkumarr I don't think this is needed any more after the change you did on how we query for apps
