### ISSUE TITLE
Feature request: Helm support

### ISSUE THREAD

**Issue by krancour** [Azure/azure-functions-core-tools#754]
Instead of deploying directly to k8s, it would be an excellent feature if I could generate (and push) Docker images (without deploying) and _also_ generate a Helm chart, which can then be deployed later by an already-ubiquitous tool for installing and managing software on k8s.

**Comment by anthonychu** [comment]
Would also like to see `func kubernetes` generate and use helm charts that can be source controlled with the function app. This allows customization of the kubernetes deployment and makes it easier to deploy to multiple environments in a CI/CD pipeline.

**Comment by SpicySyntax** [comment]
I completely agree, this would be very helpful

**Comment by RichiCoder1** [comment]
This would be great! A lot of CD providers have native support for Helm, but trying to make them work with `func` would be a lot more awkward.
