### ISSUE TITLE
Cost calculator

### ISSUE THREAD

**Issue by davidtme** [Azure/azure-functions-core-tools#76]
I'm currently experimenting with Azure functions locally while I try and put a usercase forward to switching. It would be a great help if you could output/log the GB/s of execution. executions count, memory size etc,  so this could be used with the cost calculator.

**Comment by yochay** [comment]
@davidtme  this is a nice idea to add to the local dev tooling experience. We'll take it into consideration.

**Comment by ahmedelnably** [comment]
Closing this, as this is out of the scope of the Core Tools
