### ISSUE TITLE
Distribute Azure Functions Tooling as a Dot Net Global Tool

### ISSUE THREAD

**Issue by GavinOsborn** [Azure/azure-functions-core-tools#760]
Now that functions v2 has hit GA I was wondering if there is any appetite to make this tooling available as a [.NET Core Global Tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)?

The main benefit that I can see is a unified cross-platform distribution experience for developers.
```
dotnet tool install -g azure-functions-core-tools
```

Best I can tell you [already](https://github.com/Azure/azure-functions-core-tools/blob/836f70d0a965766f09b72f7ba699945fe82208a2/src/Azure.Functions.Cli/Azure.Functions.Cli.csproj#L4) have a [dependencies](https://github.com/Azure/azure-functions-core-tools/blob/836f70d0a965766f09b72f7ba699945fe82208a2/src/Azure.Functions.Cli/Actions/LocalActions/SyncExtensionsAction.cs#L59) on [.NET Core 2.1](https://github.com/Azure/azure-functions-core-tools/blob/70a58c530991f3fa50725dfbd314a08f3c11fed8/src/Azure.Functions.Cli/Actions/LocalActions/InstallExtensionAction.cs#L116) anyway, so perhaps it makes sense to make it distributed using the same platform, rather than npm.

**NB** - I've tried to do my homework before posting but apologies if I'm way off base here :-)

**Comment by benc-uk** [comment]
I don't think you're way off base, currently the tools come with a thin Node/NPM wrapper to make them easily installable but this was before .NET Core supported global tools, so I don't see why we still need to use NPM

**Comment by GavinOsborn** [comment]
Thanks @benc-uk, that was my understanding also.
What about the existing distribution methods, would you deprecate them or continue to support them also?
 - npm
 - brew
 - apt-get

**Comment by joeyaiello** [comment]
@paulbatum we discussed this briefly a few weeks back. I'd love to be able to tell PowerShell users on Windows that they can drop Node/npm as a dependency for getting up and running (especially since they already need the .NET Core SDK in order to work PowerShell in Functions).

**Comment by fabiocav** [comment]
Closing this in favor of #2071
