### ISSUE TITLE
Verify LinuxFxVersion while publishing 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-core-tools#762]
When publishing to dedicated Linux apps, we could verify that the image matches the desired framework. 

Currently the core tools only verifies FUNCTIONS_WORKER_RUNTIME, but that still leaves the image to potentially not match. 

Our images are 
```
- microsoft/azure-functions-base
- microsoft/azure-functions-dotnet2.0
- microsoft/azure-functions-node8
- microsoft/azure-functions-python3.6

- mcr.microsoft.com/azure-functions/base
- mcr.microsoft.com/azure-functions/dotnet
- mcr.microsoft.com/azure-functions/python
- mcr.microsoft.com/azure-functions/node
```

**Comment by tylerl0706** [comment]
And the PowerShell image 👍
