### ISSUE TITLE
apt-get Installs Out of Date Version

### ISSUE THREAD

**Issue by abramjstamper** [Azure/azure-functions-core-tools#764]
I'm not sure the cause of this issue (as I am very new to Azure Functions). However, it appears to me on Ubuntu 16.04 that the version available from apt-get is out of date. I performed an `apt-get update` this morning, and then a fresh install of `azure-functions-core-tools`. It installed version `2.0.1~beta.31-1`, which is out of date according to [the releases page](https://github.com/Azure/azure-functions-core-tools/releases). Any idea when apt-get will be updated to be in line with the releases page, or at least out of beta. Any assistance is appreciated!

**Comment by ahmelsayed** [comment]
This should be updated now. Sorry I was only updating artful and bionic. I added xenial to the list.
