### ISSUE TITLE
"dotnet" functions template start not intuitive

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-core-tools#765]
The normal flow of getting a function to start doesn't work for the "dotnet" create experience. The normal flow of events is `func init` => `func new` => `func host start`. It feels unintuitive to have to do `dotnet build` and `func host start` from the build output.

**Repro steps:**
 - `func init`
    - Choose `dotnet`
 - `func new`
    - Create any function (example: HttpTrigger)
 - `func host start`

Output is `No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).`

**To get function to run:**
 - Run `dotnet build`
 - Change directory to be debug directory
    - `cd bin/Debug/netstandard2.0`
 - `func host start`

**Comment by benc-uk** [comment]
You have to run `func host start --build` with Dotnet, which I do agree is really not intuitive at all, and it caught me out too
