### ISSUE TITLE
Debug doesn't work for C# and Node with VSCode with func command. 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-core-tools#766]
I tried to create Debug environment, some people said that the feature doesn't work for node and C#. 

However, when I investigate the issue, I feel like it is a problem of the documentation. 

# Summary.

If we create a debug enviornment of C#,  you can do like following if you use func command. 

This is obviously not good experience, However, if you use Azure Functions Plugin of VSCode, 
it works fine. The same thing happens on javascript, if we generate `launch.json` with `func host start --debug VSCode` then it generate wrong `launch.json` . However, if you use Azure Functions Plugin of VSCode, it also works well.  

# This is the example someone try to use func command to set up debug for VSCode

## preparation

```
func init
func new (choose HttpTrigger and give name interactive)
```

## build app

```
dotnet build 
```

## start function

```
cd bin/Debug/netstandard2.0
func host start --debug VSCode
```
It creates `launch.json` however, it is under the `bin/Debug/netstandar2.0/.vscode/launch.json`
then  copy the `launch.json` to the `.vscode/launch.json`

## Start debug

Click the debug button, it requires which process to attach. find `func` then start debugging.

**Comment by ahmelsayed** [comment]
That flag was meant for v1 and it was carried over to v2 just by virtue of being there. I'll close this one in favor of #767  to discuss what needs to be done for this flag to work with vscode
