### ISSUE TITLE
[Discussion] Modify "--debug VSCode" experience on "func host start"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-core-tools#767]
Motivated by original issue by @TsuyoshiUshio here https://github.com/Microsoft/vscode-azurefunctions/issues/670

If you run `func host start --debug VSCode`, you get this out of date and not ideal 'launch.json':
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Azure Functions",
      "type": "node",
      "request": "attach",
      "port": 5858,
      "processId": null
    },
    {
      "name": "Attach to Azure Functions (Java)",
      "type": "java",
      "request": "attach",
      "port": 5005,
      "processId": null
    },
    {
      "name": "Attach to Azure Functions (.NET)",
      "type": "coreclr",
      "request": "attach",
      "port": 0,
      "processId": "${command:pickProcess}"
    }
  ]
}
```

Based on discussion here: https://github.com/Azure/azure-functions-core-tools/issues/394, we removed that launch.json file from `func init` so that the VS Code extension could handle the debug configuration directly.

So my question now - what is the purpose of the `--debug` flag? It doesn't seem that helpful for VS Code. Does it help for VS? Should we remove the flag or improve it somehow?

cc @fiveisprime

**Comment by ahmelsayed** [comment]
@ankitkumarr I think we should just remove the --debug flag, it's quirky and probably doesn't work well as it was just inherited from v1 work.

**Comment by ankitkumarr** [comment]
@ahmelsayed Sounds good. I will create a PR this week to address this.
