### ISSUE TITLE
WSL (Ubuntu) - tmux - func cli displaying incorrectly

### ISSUE THREAD

**Issue by ljtill** [Azure/azure-functions-core-tools#769]
The CLI isn't rendering correctly in the UI when using tmux sessions per screenshot below.
Arguments which are normally in grey don't show.

**Versions:**
- Distributor ID: Ubuntu
- Description: Ubuntu 18.04.1 LTS
- Release: 18.04
- Codename: bionic
- Azure Functions Core Tools (2.0.3)
- Functions Runtime Version: 2.0.12115.0

*non-tmux session*

![image](https://user-images.githubusercontent.com/158992/46251207-65224400-c412-11e8-9afa-8c7a5854c05c.png)

*tmux session*

![image](https://user-images.githubusercontent.com/158992/46251194-e0cfc100-c411-11e8-9af2-92f5ee283a00.png)

**Comment by ahmelsayed** [comment]
Seems likes a tmux configuration issue. Check https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-a-256-colour-terminal and verify your tmux terminal colors settings

**Comment by ljtill** [comment]
@ahmelsayed that did the trick! Thanks a lot!
