### ISSUE TITLE
Can't find app with name

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-core-tools#770]
I am following instructions on the following page https://github.com/Azure/azure-functions-python-worker/wiki/Create-your-first-Python-function to set up a Python function on the Linux preview. I am able to run the HttpTrigger function locally but am not able to publish it.  Running the "func azure functionapp publish maiqbalPythonTest" command shows "Can't find app with name "maiqbalPythonTest". 

I have verified that the correct subscription antps33 is set and the function app exists in resource group maiqbal-linux-preview.

**Comment by ahmelsayed** [comment]
I think this is a dup of #738 which can happen if your subscription has more than 999 apps in it. You can try one of the builds here https://ci.appveyor.com/project/appsvc/azure-functions-cli/build/679/artifacts and see if that works for you. The fix for #738 will go out with the next update
