### ISSUE TITLE
Add --platform ACI to Functions CLI 

### ISSUE THREAD

**Issue by odaibert** [Azure/azure-functions-core-tools#780]
For Dev Test scenario it will be simple to deploy the containerized Azure Function to ACI. Something like this: 

**func** **deploy** --**platform** **_**aci**_** --**name** myfunction2 --**registry** odaibert --**resourcegroupname** FunctionsACI --**containergroupname** FunctionsACI --**subscriptionid** SUBSCRIPTIONID --**location** eastus --**port** 80 --**containermemory** 1 --**containercpu** 2 --**ostype** linux 

Make sense?

**Comment by ahmelsayed** [comment]
as I mentioned on the PR, I'm not in favor of this change. I'd rather not do azure management operations in this cli. All management operations for Azure should be in the az cli instead. This only requires building a docker image and pushing it to the right registry, then all the commands to deploy to ACI should be the same as in `az`.
