### ISSUE TITLE
Proxy create command from v1 needs to be ported to v2

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-core-tools#793]
The following command for proxies is missing in v2.
`Function proxy create --name <yourproxyname>`

**Comment by ErickWendel** [comment]
Any response about this issue guys?

**Comment by ahmedelnably** [comment]
@soninaren is this still valid?

**Comment by soninaren** [comment]
@ahmedelnably, i think this is still valid. I don't see a command related to proxy in core tools.

**Comment by TroyWitthoeft** [comment]
Bumping this.  Just found a need to have this work. It seems like we don't have a good local development solution for an Azure function using a proxy.

**Comment by kshyju** [comment]
@soninaren Is this still valid/relevant?
