### ISSUE TITLE
Duplicate tip of local IP and exit command

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-core-tools#813]
A simple recommendation, can the duplicate be removed or it's retained for some purpose?

```
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...

```

**Comment by ahmelsayed** [comment]
It should be easy to remove [this line](https://github.com/Azure/azure-functions-core-tools/blob/master/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L221)
