### ISSUE TITLE
deploying azure function to k8s - never ends

### ISSUE THREAD

**Issue by LirazRom** [Azure/azure-functions-core-tools#817]
running 
`func deploy --platform kubernetes --name MyFunctionProject --registry <registry>`

from macos
gives the output of

> Building Docker image...
Running 'docker build -t <registry>/myfunctionproject /Users/<registry>/work/testAzureFunc/testScale'...done
Pushing function image to registry...
Running 'docker push <registry>/myfunctionproject'...........done
Deploying function to Kubernetes...
Deployment successful
Waiting for External IP...

but it never ends

**Comment by VenkateshSrini** [comment]
Hi,
I'm facing the same issue in Kubernetes on Docker for Windows. When I launched the web dash board and get the details I get the following details How to resolve it

> Killing container with id docker://azurefuncdocker-deployment:Need to kill Pod 
> kubelet docker-for-desktop 
> spec.containers{azurefuncdocker-deployment}
> 
> 
> failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io) 
> horizontal-pod-autoscaler 
> 
> unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io) 
> horizontal-pod-autoscaler 
>

**Comment by scottrudy** [comment]
It's great that the intention is to make deployment easier, but the downside is when hiding all of that is how to continue. I'm stuck here and about to abandon my efforts to get this running. Is there a workaround?

**Comment by scottrudy** [comment]
I ran into this same issue. I noticed when the script runs it uses a converts the image name to lowercase. So I changed the case of the `--name` parameter to be lowercase and it worked. Seeing the initial post from @LirazRom , I suspect that could also be the problem.

**Comment by yaron2** [comment]
Are you trying to deploy using Minikube?

**Comment by VenkateshSrini** [comment]
Hi,
No I'm using Docker for windows desktop latest version.
