### ISSUE TITLE
VSCode debug "cannot find module ./.vscode"

### ISSUE THREAD

**Issue by olliejm** [Azure/azure-functions-core-tools#819]
I am trying to run the following command to debug a function with the local functions host:

```bash
func host start --debug VSCode
```

However it gives me the following error:

```
[22/10/2018 09:39:35] Worker was unable to load function myfunction: 'Error: Cannot find module 'C:\Users\Administrator\function-repo\.vscode''
```

If I delete the `.vscode` folder, `func host start` works fine, but with `.vscode` and a `launch.json` the debug command nor the regular `host start` will work, both producing the above error.

Functions version: 2.1.725
Node version: v8.12.0
OS: Windows Server 2016

**Comment by ahmedelnably** [comment]
Closing as stale, if you are still experiencing the same error with the latest version of the Core Tools, please open a new issue
