### ISSUE TITLE
'func deploy --platform kubernetes' command fails with Forbidden error on RBAC enabled Azure Kubernetes Service cluster

### ISSUE THREAD

**Issue by atverma** [Azure/azure-functions-core-tools#833]
The command to deploy function to Kubernetes fails with Forbidden error on RBACK enabled AKS clusters. I have couple of AKS clusters however only one has RBAC enabled. I am able to deploy functions to cluster which doesn't has RBAC enabled however for deployment fails with 'Forbidden' error.

**Comment by yaron2** [comment]
I can't reproduce.

Can you create a new AKS RBAC enabled cluster and test?

**Comment by ahmelsayed** [comment]
closing stale issue.
