### ISSUE TITLE
Unable to use EFCore in Azure Functions

### ISSUE THREAD

**Issue by PankajPatro** [Azure/azure-functions-core-tools#835]
Created a new Azure Functions App .NetCore 2 App and referenced EFCore. The Function fails with issue

System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Versions 

VS 2017 15.8.8. All Extensions Updated.
Azure Function .Net Standard 2.0
Microsoft.EntityFrameworkCore 2.1.4
Microsoft.EntityFrameworkCore.SqlServer 2.1.4
Microsoft.NET.Sdk.Functions 1.0.23
NETStandard.Library 2.0.3
Newtonsoft.Json 11.0.2

OS - Window 10

**Comment by kshyju** [comment]
Can you try again with the latest version of core tools?
