### ISSUE TITLE
Updated Azure Functions to v2; core tools automatically installed and now debug is broken

### ISSUE THREAD

**Issue by jasonshave** [Azure/azure-functions-core-tools#837]
When attempting to run a debug locally of my Azure Function I'm now getting the following error:

![image](https://user-images.githubusercontent.com/28457536/47810307-a4d99580-dd08-11e8-8897-7a557a5d62cf.png)

I had updated the SDK NuGet package along with the .csproj file so that my functions would be recognized as v2 and would work with GitHub CI/CD on Azure. Shortly after this it looks like the newer CLI tools were automatically downloaded to my system and now I can't debug.

**Where does Visual Studio hold the reference to 'func.exe'?**

**Comment by ahmedelnably** [comment]
Closing as stale
