### ISSUE TITLE
Console logging is hardcoded to only write Information and above

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-core-tools#841]
This should be using the host.json config but right now there's an explicit filter being pushed into the ColoredConsoleLoggerProvider. Logging this so I can come back and fix for next release.

**Comment by eamagdalena** [comment]
Is there also any way to see the logs generated by the runtime? For example if the body of a servicebus topic arrives to the function as undefined, to see on the logs the raw message received and why potentially the body was rejected?
