### ISSUE TITLE
Node version not set on func azure functionapp deploy

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-core-tools#846]
Created a new function app from the cli:

`az functionapp create`

Immediately after tried to publish a v2 function app:

`func azure functionapp publish`

For VS and VS Code I believe they set the "WEBSITE_NODE_DEFAULT_VERSION" App setting to 8.11.1 if set to a v2 version.  Would be good for func to do this too.

**Comment by jeffhollan** [comment]
Related issue: azure/azure-cli#7749

**Comment by ggailey777** [comment]
We also have a customer trying to update the CLI quickstart because of this issue: https://github.com/MicrosoftDocs/azure-docs/pull/17529/files 

I will do a proper fix in the article, which we can remove after this issue gets addressed.

**Comment by ErickWendel** [comment]
Guys, I found this PR related with this issue, but I don't know if this change is already in production, Today I created a new project and the Node.js default version still 6.x

https://github.com/panchagnula/azure-cli/commit/782470ec5df192bf79796b985be394a5a8df8870

**Comment by ahmedelnably** [comment]
We have already updated the node version set by the Az CLI
If this still an issue please open a new issue
