### ISSUE TITLE
OPTIONS method does not work on Azure funtion 

### ISSUE THREAD

**Issue by abhinav-jain09** [Azure/azure-functions-core-tools#848]
Hi Guys, I am trying to deploy spring boot application with Azure function. When I send the request with OPTIONS it does not work and send the 500 status from the server. Please help .

**Comment by ahmelsayed** [comment]
Can you please share more context about what you're trying to do? Is this locally or on Azure? If locally, how are you running the CLI? and if on Azure, please share your app name either directly or [indirectly](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by abhinav-jain09** [comment]
@ahmelsayed  I wrote a simple spring boot application with spring boot Azure cloud adaptor. the code is as follows 

spring boot 

```
@SpringBootApplication
public class SpringBootGrapqlExampleApplication {
	@Autowired
	GraphQLService graphQLService;
	public static void main(String[] args) {
		SpringApplication.run(SpringBootGrapqlExampleApplication.class, args);
	}
	@Bean
	public Function<String, ExecutionResult> queryHippoContent( ) {

	return	bar -> graphQLService.getGraphQL().execute(bar);

	}
```
Spring boot adaptor with handler

```
public class BookHandler extends AzureSpringBootRequestHandler<String, ExecutionResult> {
	
	@FunctionName("queryHippoContent")
	public ExecutionResult run(
			@HttpTrigger(name = "req", methods = {
					HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS)String bar ,
			ExecutionContext context) {
	   	return	handleRequest(bar, context);
	}


}
```

if I deploy this application on azure function then and call with OPTIONS then it says bad request.

Also, I have enabled cors on the Azure function to "* " now everything is allowed. but still, OPTIONS does not work.
If I run azure function locally in my computer then it give 404 ,

Do I have to write some CORS code to respond application for OPTIONS ? or Azure function work out of the box

**Comment by ahmelsayed** [comment]
When you run functions locally you need to pass `--cors *` for CORS to work. I don't think the tooling will do that by default for you. If you're using vscode, you should be able to edit `tasks.json` and update the run command from `func host start` to `func host start --cors *` or whatever cors domain you want. 

In Azure, you need to make sure that `*` is the only value in the list for your app. Remove all the default `functions.azure.com` from that list and it should work there.

**Comment by abhinav-jain09** [comment]
if I run the function with ``` func host start --cors * ``` then I get output 
```
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
```
this means that the function server is running without any application. 

I am not using vscode I am working with Java on Azure functions where I can find task.json.

I also specified * in the cors on azure portals removed all other url but still it does not work.

**Comment by ahmelsayed** [comment]
how are you running your functions locally? whoever is running the functions needs to add that to the command line used. 

For Azure, please share your app name either directly or [indirectly](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)
