### ISSUE TITLE
HTTP OPTIONS 404 error

### ISSUE THREAD

**Issue by jschmold** [Azure/azure-functions-core-tools#854]
I have an Azure Functions project as an API for an Angular app. We're trying to call a `POST` route, and the cors preflight is returning a 404. If I'm not wrong, shouldn't the Azure Functions CLI handle this sort of request? All routes have this issue where they 404 instead of handling the cors issues. The error occurs when doing local development, on Mac and Windows, even if we run `func host start --cors *`.

I've already written a considerable amount of the API without paying attention to CORS because I had assumed it would be taken care of by Azure. 

Is this a bug? I thought half of the point of the `function.json` files was to handle CORS.

Example `function.json` file.

```
{
  "disabled": false,
  "scriptFile": "../dist/controllers/auth.controller.js",
  "entryPoint": "loginRoute",
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "auth/login", 
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

**Comment by ahmelsayed** [comment]
What does that preflight request look like? Are you testing it from a browser? I tried using CURL and it looks like it's returning a successful status code (204, which surprised me a bit as I thought it should return 200 but 204 should also be fine for CORS response)

![2018-11-06_17-18-58](https://user-images.githubusercontent.com/645740/48104385-26896180-e1e8-11e8-8734-9aa1e6fab85c.gif)
