### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by JasonKleban** [Azure/azure-functions-core-tools#856]
Related to https://github.com/Azure/azure-functions-core-tools/issues/475

There's no mention of how to log in for a publish operation.  I had this working for a long time and up until ~a month ago (I thought, but this should have expired many months ago).  But now when I try to publish, I get:

```
ERROR: Get Token request returned http error: 400 and server response: 
{"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS70008: The 
refresh token has expired due to inactivity.áThe token was issued on 2017-12-31T04:03:23.4384920Z and 
was inactive for 90.00:00:00.
```

My vscode tools are authenticated fresh.  I gather from the linked issue that the login credentials aren't shared between, I guess, the vscode extension and func cli.  But I'm not even sure I'm reading that right and I don't know what to do.  I found no helpful google hits on the error message, `func publish authenticate`, etc.  If func cli requires special login procedure, that ought to be documented/more prominently, right?

**Comment by JasonKleban** [comment]
`az login` from the command line is the answer, I guess.  It's the same general procedure as the vscode extension does.

**Comment by ahmelsayed** [comment]
Glad you found it. The core tools relies on the `az login` command. I added that to the error message to make it clearer.
