### ISSUE TITLE
Allow user to specify TypeScript as App Language

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-core-tools#859]
When a developer creates a new Function app, they should be prompted to specify whether they prefer TypeScript or JavaScript, which will end up in a different folder structure. Exact gesture TBD.

**Comment by ColbyTresness** [comment]
Gesture we solidified on in the short term:

Function App Create currently prompts for Stack: .NET, Node. We'll append to this an option like "Node (TypeScript)". This needs to be on App creation since the folder structure and contents of package.json change depending on whether you're using TS.

**Comment by ankitkumarr** [comment]
@ColbyTresness @mhoeger Should this be closed by https://github.com/Azure/azure-functions-core-tools/pull/1070

**Comment by mhoeger** [comment]
Yeah :)
