### ISSUE TITLE
version 2.1.725 not available in ubuntu 18.04 apt package. Still latest version is 2.0.3

### ISSUE THREAD

**Issue by mosharafMS** [Azure/azure-functions-core-tools#868]
Latest version available for 18.04 package is 2.0.3 not 2.1.725

**Comment by ahmelsayed** [comment]
how are you installing it? can you remove any old apt sources and use the instructions in the README?

![2018-11-13_11-34-37](https://user-images.githubusercontent.com/645740/48438173-2a613a80-e738-11e8-8469-5baa36552d1d.gif)
