### ISSUE TITLE
Ignore the Python worker, library and related dependencies when publishing to Azure

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#871]
This is related to https://github.com/Azure/azure-functions-docker/issues/53 aka maintaining a version of the language worker in the cloud that we can update and maintain on behalf of the user.

Specifically, we want to ignore the following set: 

```
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.11.0
```

/cc @ahmelsayed

**Comment by fabiocav** [comment]
Moving this to sprint 44 for validation, as this work may no longer be relevant.

**Comment by ankitkumarr** [comment]
Closing this issue because issue https://github.com/Azure/azure-functions-core-tools/issues/1023 takes care of the problem highlighted here.
