### ISSUE TITLE
Azure function HTTP Trigger with Authorization.Level=Function/System/Admin in Docker

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-functions-core-tools#881]
I would like to create a HTTP trigger with AuthorizationLevel as "Function"/"System"/"Admin and run the same in docker. I'm using Azure function 2.0 with .NET standard. Can you please provide me some insights on how to get the API Key or generate an API key and set it to a function so that I can pass the same during function call when running the Azure function in docker

**Comment by ahmelsayed** [comment]
What is your expected behavior of these keys? If you're testing with a set of keys when running your container locally, do you expect them to still work regardless of where you run the container? Or do you expect the keys to depend on the hosting environment/machine of the container

**Comment by VenkateshSrini** [comment]
I would like the key to first test it locally in the docker with these keys.

Now that Azure functions on docker is new one, in production, we would like to have it the same treatment that .NET core 2.1 HTTPS certificate are given. It would be good if you could give any or all option

1)Use a already generated key. Storage of the key and safeguarding is not Azure function responsibility
2) I need to have a pipeline module in which I can retrieve a key from any store like Hashi corp vault, database, redis cache etc;- then validate that key for that function in the pipeline and before reaching the actual function I need to tell it whether it was an authorize call.

**Comment by blackbaud-brandonstirnaman** [comment]
This is a pretty critical gap when running inside a docker container currently.

If it comes down to having to implement a key provider of some kind, thats fine too. Just need the extensibility points to do this.

**Comment by adrianrbezzina** [comment]
Left a comment about the same functionality here: https://github.com/Azure/azure-functions-core-tools/issues/29#issuecomment-450485557

In summary, require a way to access the function via code query parameter (or http header).

**Comment by monteledwards** [comment]
Is there any way to even get the key for the function when you're running in Docker? I do not see the output of this key anywhere... seems like switching to anonymous is the only option?

**Comment by hamdyghanem** [comment]
> Is there any way to even get the key for the function when you're running in Docker? I do not see the output of this key anywhere... seems like switching to anonymous is the only option?

The output in the \runtime\secrets\host.json

**Comment by VenkateshSrini** [comment]
Check this please https://github.com/Azure/azure-functions-host/issues/4147

**Comment by ahmedelnably** [comment]
Closing this as a workaround is available, an additional discussion about this currently happening, we will update everyone once we have a solution
