### ISSUE TITLE
Automatically enable App Insights on create

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#890]

**Comment by ahmelsayed** [comment]
That should happen on app creation not through the core-tools.

**Comment by asavaritayal** [comment]
@ahmedelnably can you suggest the right location for this issue?

**Comment by ahmedelnably** [comment]
Here are the different scenarios:
1- The user disabled App Insights -- We should not enable it
2- The user doesn't have App Insights -- We should not create one, guide the user with a good message on how to create and enable App Insights

HTH

**Comment by ahmedelnably** [comment]
@asavaritayal we already working on adding AI support when you create a new functionapp. this is tracked here https://github.com/Azure/azure-cli/issues/7890
Last time I tried it, the portal it is off by default, and the user has to enable the support by him/herself. Our goal is the same here, to have a consistent behavior between our management interfaces, but we have to honest to ourselves that not everything the portal can do; can be done in cmd line

Closing this issue, as it is in the wrong repo

![image](https://user-images.githubusercontent.com/7810433/50318874-dead5980-0478-11e9-8ea3-5d9853227693.png)
