### ISSUE TITLE
publish got an error message, "Error uploading archive (Conflict)."

### ISSUE THREAD

**Issue by RudyLu** [Azure/azure-functions-core-tools#903]
After I tried to deploy my functions with this command,
`func azure functionapp publish func-app-name`

I got this error message:

```
Getting site publishing info...
Creating archive for current directory...
Uploading archive...
Creating archive for current directory...
Uploading archive...
Creating archive for current directory...
Uploading archive...
Error uploading archive (Conflict).
```

I have these dependencies in my package.json
```
"devDependencies": {
    "eslint": "^5.9.0",
   "eslint-config-airbnb-base": "^13.1.0",
   "eslint-plugin-import": "^2.14.0",
   "eslint-plugin-prettier": "^3.0.0",
    "prettier": "^1.15.2"
   }

The error message should be more clear and let the user know to resolve it.

**Comment by bherila** [comment]
I agree, this is currently blocking me from deploying my function app. Is there a workaround to publish the site manually or using a different tool?

**Comment by RudyLu** [comment]
The simple workaround here is to remove the dependencies introduced by eslint, including
```
   "eslint": "^5.9.0",
   "eslint-config-airbnb-base": "^13.1.0",
   "eslint-plugin-import": "^2.14.0",
   "eslint-plugin-prettier": "^3.0.0",
```

**Comment by JohnReeson** [comment]
The same thing happens when I use `func azure functionapp publish func-app-name --nozip` with 2.3.148 Cli, have installed some dependencies as well.

**Comment by Shell32-Natsu** [comment]
Same error here. I am publishing a Python functions, with options --build-native-deps --nozip. The tool uploaded three times and then failed.

**Comment by ErickWendel** [comment]
For me, I was installed by the azure tools by npm. So I removed an installed again using home brew. now it works perfectly

**Comment by marshallford** [comment]
I'm seeing the same issue as @Shell32-Natsu, but just occasionally. I also see `Error uploading archive (BadGateway)` once in a while. I'm trying to publish a python v2 function with the follow command: `func azure functionapp publish app-name --build-native-deps --no-bundler`.


```
~
➜ func --version
2.4.498

~
➜ docker --version
Docker version 18.09.3, build 774a1f4

~
➜ dotnet --version
2.1.505

~
➜ npm --version
6.9.0

~
➜ node --version
v10.15.3

~ 
➜ source ~/Development/python-env/bin/activate

~ via python-env 
➜ python --version
Python 3.6.7
```

**Comment by roalexan** [comment]
I just saw this myself. I first did an upload that appeared to hang, so I click CTRL-C. Now all subsequent uploaded attempts show: Error uploading archive (Conflict).

**Comment by dmitrysmirnovfinnair** [comment]
Same issue, python app, keeps failing with `Azure.Functions.Cli.Common.CliException: Error uploading archive (Conflict).`

**Comment by ahmedelnably** [comment]
Closing this as stale, if you are facing a similar error please open a new issue
