### ISSUE TITLE
Wildcard CORS not working on Mac

### ISSUE THREAD

**Issue by JamesRandall** [Azure/azure-functions-core-tools#904]
Using the following version of the tools wildcard CORS does not seem to work on the Mac.

**Tools Version**

Azure Functions Core Tools (2.2.70 Commit hash: 1f1f77a71c5517b00401aa0ebf00a4f16857a94c)
Function Runtime Version: 2.0.12175.0

**Steps to Reproduce**

For a functions project using C# run the command:

dotnet /usr/local/lib/node_modules/azure-functions-core-tools/bin/func.dll start --cors *

And call a Function (in my example it was a proxy being called that was mapped to a function in the same project) from a browser and you'll get a CORS failure.

Close the host and run it with a specific domain as below and it works:

dotnet /usr/local/lib/node_modules/azure-functions-core-tools/bin/func.dll start --cors http://localhost:3000

I'm running the same project on Windows using wildcards for debug purposes.

Suggest either fixing or if there is a broader issue either removing wildcard CORS support for all platforms in favour of consistency or at a minimum validate the input on the CLI and provide a sensible message.

**Comment by ahmelsayed** [comment]
I'd have expected this to work the same way on mac as it does on Windows. We just pass the CORS setting value to ASP.NET host. 

Are you using zsh by any chance? zsh tries to expand * for globbing, though I just tried it on a linux machine with zsh and it seems to work fine there, so I'm not sure. we may have have to test `--cors *` on a mac machine explicitly. /cc @ankitkumarr

**Comment by ankitkumarr** [comment]
@ahmelsayed, I just tried it in my mac machine and was able to reproduce this issue (wildcard not working) with both bash as well as with zsh.

**Comment by ankitkumarr** [comment]
Seems like it works when you do `--cors "*"` in mac vs `--cors *`. It might just be a shell thing as @ahmelsayed suggested. I will look more.

**Comment by JamesRandall** [comment]
Hi, yes I can confirm putting it in quotes works for me too. A shell thing I guess - probably more obvious to someone who uses bash more often!

Thanks for investigating - much appreciated 👍
