### ISSUE TITLE
Create csharp script function in subfolder

### ISSUE THREAD

**Issue by TyMac** [Azure/azure-functions-core-tools#908]
I'm trying to add another csharp function to a functionapp that was originally created in the Azure portal and then put under source control. The func command does not seem to give the ability to create a new csx function, only a standard csharp - this command: 

`func new --name random008\run`

Results in a run.cs file with no function.json file accompanying it. Is it possible to add this functionality?

**Comment by ahmelsayed** [comment]
to create `.csx` based functions you need to pass `func new --csx`
