### ISSUE TITLE
Publish Pre-Release Build with dist-tag @next

### ISSUE THREAD

**Issue by PramodValavala-MSFT** [Azure/azure-functions-core-tools#909]
I see that there is a Pre-Release version available in [releases](https://github.com/Azure/azure-functions-core-tools/releases) for people to try out.

I think it would be great for it be available via a [dist-tag](https://docs.npmjs.com/adding-dist-tags-to-packages) `@next` on NPM too, making it easier for people wanting to live on the edge. 😄

**Comment by ahmelsayed** [comment]
we don't have pre-release versions
