### ISSUE TITLE
cli 1.6 executes my function twice

### ISSUE THREAD

**Issue by tsahi** [Azure/azure-functions-core-tools#914]
since func.exe was updated to version 1.6 recently, I started seeing lines line these in the terminal window:

    [12/5/2018 7:39:34 AM] Executing 'messages' (Reason='This function was programmatically called via the host APIs.', Id=d51d1a03-1050-4dc1-861a-3b3b79788371)
    [12/5/2018 7:39:34 AM] Executing 'messages' (Reason='This function was programmatically called via the host APIs.', Id=5952a64b-d217-46ec-a62d-f711f52fb55c)

This is an HTTP triggered function, based off the Functions Bot template of the Bot Service Azure resource, with many modifications.

This causes a problem, because I'm using [AzureFunctions.Autofac](https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/issues) for dependency injection, and the double-execution cases a `System.ArgumentException: 'An item with the same key has already been added.'` exception thrown from an internal dictionary this package has, where the function name is a key.

this happens roughly 50% of the times I start a debug session.
using Visual Studio 2017 15.9.3.

To repro:
1. Create a new function project (HTTP triggered in my case, not sure if this is required)
1. add the AzureFunctions.Autofac 3.0.2 package
1. configure some injections

result: every so often, the above lines show in the func.exe console, and `DependencyInjection.Initialize()` from AzureFunctions.Autofac throws an ArgumentException.

**Comment by tsahi** [comment]
@vandersmissenc

**Comment by vandersmissenc** [comment]
@tsahi I am having a difficult time trying to reproduce this issue. I followed your repro steps and created an HTTP triggered function with the latest version of AzureFunctions.Autofac, Function CLI 1.6.0, and VS 2017 15.9.3 Professional.

Can you provide some additional information around how you are testing this? Do you see this issue when running locally or deployed or both?

If possible sharing a project where the issue occurs might provide us an easier time in finding a resolution.

Thanks!

**Comment by tsahi** [comment]
I see this locally. I didn't deploy to production yet (I deployed to a test slot, but hadn't tried much)
Microsoft.NET.Sdk.Functions 1.0.14
.NET Framework (Functions v1)

**Comment by vandersmissenc** [comment]
Can you try upgrading to Microsoft.NET.Sdk.Function 1.0.24 and see if you are still having issues?

**Comment by tsahi** [comment]
I couldn't repro after upgrading Microsoft.NET.Sdk.Function to 1.0.24, but today I didn't do many real debug sessions. Either close and I'll reopen if this happens again, or leave open and I'll close if this doesn't happen again in a few days.

**Comment by ahmelsayed** [comment]
@tsahi I'll close the issue per your last comment. feel free to reopen it if you get a repro again.
