### ISSUE TITLE
Chocolatey version behind

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-core-tools#916]
Version [on chocolatey.org](https://chocolatey.org/packages/azure-functions-core-tools) is not in sync w/ the one [on npm](https://www.npmjs.com/package/azure-functions-core-tools).

cc @jeffhollan

**Comment by ankitkumarr** [comment]
@brandonh-msft, we are aware of the inconsistency and are working on deployment changes. We haven't been able to push the updates yet, but are working on it.

Thanks for reporting!

**Comment by moonmeister** [comment]
@ankitkumarr Is this also why Debian/Ubuntu packages are way behind the current version? Thanks.

**Comment by ankitkumarr** [comment]
@moonmeister, yes! Currently npm and homebrew have the latest version while Debian and chocolatey are one version behind.

**Comment by ahmelsayed** [comment]
all package managers should be up to date now.
