### ISSUE TITLE
Create a new `func up` command

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-core-tools#919]
Details TBD

**Comment by ankitkumarr** [comment]
@ahmedelnably, if the user does not provide information like the region of the functionapp/storage account, would you want us to add a prompt for users to select the location? Doing so may mean that we would have to maintain a list of the regions Functions are supported in.
Unless there's a default location that we could perhaps use?

**Comment by ahmedelnably** [comment]
@ankitkumarr I believe there is an API to get the regions Functions are available in.
If the user don't provide a location let's try and create the Function App in a location near her/him, but clearly print in the output the location of the newly created Function app
