### ISSUE TITLE
Proper support for proxies in local environment

### ISSUE THREAD

**Issue by azarboon** [Azure/azure-functions-core-tools#921]
Hi. I'm using Core Tools v2.3.148 on my macOs High Sierra. Despite what[ this announcement](https://blogs.msdn.microsoft.com/appserviceteam/2017/11/15/azure-functions-proxies-is-now-generally-available/) claims, I don't see any proxy option on my cli. Also upon first publish, Function App turns into Read Only mode. So, the way to create proxies in local env, is to manually create a proxies.json in local and then publish the app. It would be great if cli would enable creation of proxies.

More importantly: currently proxies are partly supported in local environment. That is, `func host start` recognise there are proxies however proxies point to real backend functions (not simulated ones). This makes the proxies (in dev environment) require authentication (if it's set on Azure, and normally it's set). This is confusing. It would be great if automatically or easily proxies refer to simulated functions or real backend functions. Because currently, for every change (which must be done locally), user have to update proxies.json manually.

**Comment by PramodValavala-MSFT** [comment]
The announcement was for Core Tools v1. #793 tracks this migration.

As for local development, check out this [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies#reference-localhost) which talks about using `localhost` in your `proxies.json` like this
```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "proxy1": {
      "matchCondition": {
        "methods": ["GET"],
        "route": "/api/test"
      },
      "backendUri": "https://localhost/api/HttpTrigger"
    }
  }
}
```

If your function is not anonymous, you could either use your function key
1. Directly in your request like, `/api/test?code=<code>`
2. In this JSON, so backendUri will be like, `/api/HttpTrigger?code=<code>`

**Comment by azarboon** [comment]
Hi. Thank you. Yes, this way I can point to local functions but I have to manually replace my backendUris or the proxies.json, whenever I want to do local development. Is there any way to dynamically change the proxies.json (e.g. by changing an environmental variable)?

**Comment by PramodValavala-MSFT** [comment]
With this, you don't have to 😄

You can have it as `localhost` for both when working on them locally and when deploying them as well.

**Comment by azarboon** [comment]
ok. thanks. I will try it out and will mentioned the results in here.

**Comment by ahmelsayed** [comment]
I'm closing this as a dup of #793
