### ISSUE TITLE
func azure functionapp publish <app_name> returning "The handle is invalid"

### ISSUE THREAD

**Issue by rdlucas2** [Azure/azure-functions-core-tools#927]
Context: I'm trying to publish a python function app from a build agent in an Azure Devops Build/Release Pipeline. I'm able to recreate this error locally by running the func azure functionapp publish command from inside a powershell job. I followed this [tutorial](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python) to set up the function app.

Powershell Deployment Script (when running in the build agent only using the part inside the script block):
```
$j = Start-Job -ScriptBlock {
  cd $workingDirectory
  py -3.6 -m venv .env
  .env\scripts\activate
  az login -u $user -p $pass
  az account set -s $subId
  func azure functionapp publish <app_name>
}
Receive-Job -Job $j -Wait
```

```
Output:
Getting site publishing info...

...

Preparing archive...
The handle is invalid
    + CategoryInfo          : NotSpecified: (The handle is invalid:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : localhost
```

When running from the build agent, the only error received is "The handle is invalid" and not the other part below that from above.

I can run this locally fine when not inside a Powershell job, and if I remote into the agent and run it from there. I'm guessing this is some sort of authentication issue with the az login not persisting properly in the job? Any help would be appreciated, thanks!

**Comment by ahmelsayed** [comment]
I actually think it might be the console APIs used in printing the progress. We should catch any console API errors and just opt-out from printing the progress.

**Comment by rdlucas2** [comment]
A quick workaround was sending the output to a file using `> log.txt` at the end of the publish command. Thanks!
