### ISSUE TITLE
Running Azure CLI command func azure functionapp in Azure Government tries to connect to public cloud instead of Government cloud, resulting in 401

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-functions-core-tools#931]
Running func azure functionapp publish YourFunctionApp (where YourFunctionApp is the name of a created Function App in the Government subscription) returns 401/Unauthorized.

Running this command in debug mode shows that it is trying to make an ARM call to the public cloud endpoint (management.azure.com ) instead of to the Government cloud endpoint (eg management.usgovcloudapi.net) and is returning 401 because the endpoint is expecting a public cloud token audience instead of the Government token audience that is provided. See sample request below for further details.
This occurs even with current Function Core Tools (2.3.148) and CLI (2.0.52)

Running non-func CLI commands from the same Government account connects to the Government cloud endpoint and works as expected (az functionapp create, az storage account create, and  az group create the respective resources ok).

Request/Response when using func azure functionapp publish:
Request:
Method: GET, RequestUri: 'https://management.azure.com/subscriptions?api-version=2018-09-01', Version: 2.0, Content: <null>, Headers:
{
  Authorization: Bearer  {snipped}
User-Agent: functions-cli/2.0
  Accept: application/json
  x-ms-request-id: 8a334eb8-c971-41fd-be82-2292dfee4945
}

Response:
StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  WWW-Authenticate: Bearer authorization_uri='https://login.windows.net/', error='invalid_token', error_description='The access token is from wrong audience or resource.'
  x-ms-failure-cause: gateway
  x-ms-request-id: df87e089-fb76-461f-9c73-f2225f5f2426
  x-ms-correlation-request-id: df87e089-fb76-461f-9c73-f2225f5f2426
  x-ms-routing-request-id: EASTUS:20181211T203228Z:df87e089-fb76-461f-9c73-f2225f5f2426
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Date: Tue, 11 Dec 2018 20:32:28 GMT
  Connection: close
  Content-Type: application/json; charset=utf-8
  Expires: -1
  Content-Length: 378
}
{'error':{'code':'InvalidAuthenticationTokenAudience','message':'The access token has been obtained for wrong audience or resource 'https://management.core.usgovcloudapi.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.'}}

**Comment by paulbatum** [comment]
It looks like core tools is missing support for sovereign clouds, see:
https://github.com/Azure/azure-functions-core-tools/blob/d1a792e79640bf6192d6fbe9b06d32403c8e8ec8/src/Azure.Functions.Cli/Arm/ArmUriTemplates.cs#L12

**Comment by ankitkumarr** [comment]
@gabesmsft, do you still need this functionality, if so I can provide you artifacts from my PR to test?
