### ISSUE TITLE
Have better integration with KeyVault for automatic retrival of connection string and secrets 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-core-tools#933]
This is pending on https://github.com/Azure/azure-functions-host/pull/3791

**Comment by cosin2008** [comment]
I saw PR #3791 has been merged for months. But it seems in VSCode/VS2019 local debugging environment, azure function still not translating @Microsoft.KeyVault to real secret value. Anything blocking or requires additional configuration?

**Comment by Areson** [comment]
I second this. References do not work during local development.

**Comment by tomkerkhove** [comment]
We are blocked by this as well when we are doing deployments.
Any update on this @ahmelsayed?

**Comment by Vivihung** [comment]
+1 for KeyVault reference syntax support in local.settings.json.
It is mentioned in [this ](https://github.com/Azure/azure-functions-core-tools/issues/1810) thread, too.
Is there any other place where the team is tracking requests that we can vote for this feature?

**Comment by anthonychu** [comment]
#2258 should address this. @fabiocav is planning to review it soon.

**Comment by michaelpeng36** [comment]
Resolved by #2806 and #2924.
