### ISSUE TITLE
Runtime keeps assemblies locked when using CLI

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-core-tools#94]
In Azure, we now have shadow copying to solve this. But locally this doesn't work, making the workflow more painful when using VS and compiled binaries. i.e. each time you want to make a change and rebuild, you have to first stop the runtime, compile and then restart it.

@fabiocav knows why this doesn't work, which relates to how shadow copying is set up on the AppDomain.

**Comment by fabiocav** [comment]
Happy to look at this item. If we can set a priority, relative to the other items in the script repo, that would help, but I'd like to do this ASAP

**Comment by ahmedelnably** [comment]
@fabiocav is this still relevant?

**Comment by fabiocav** [comment]
I don't think this is something we should be tracking anymore. The workflow has changed since this was opened. 

Let's close and we can reevaluate later if needed.
