### ISSUE TITLE
There misses three activities after creating a C# project with func cli  

### ISSUE THREAD

**Issue by v-xuanzh** [Azure/azure-functions-core-tools#943]
**Version**: 1.31.0-insider (user setup)
**Commit**: d85a16f2e4354f2850b4171f84fe0c94b0cea338
**Date**: 2018-12-18T06:20:40.432Z
**Electron**: 3.0.10
**Chrome**: 66.0.3359.181
**Node.js**: 10.2.0
**V8**: 6.6.346.32
**Func cli:** 2.3.148

**Repro Steps:**
1. Create a JavaScript project with the following command '**_func init --worker-runtime node_**' -> Check the log message.
2. Create a C# project with the command '**_func init --worker-runtime dotnet'_** -> Check the log message.
3. Compare these two generated log messages.

**Expect:**
The generated log messages are consistent.

**Actual:**
1. The generated log messages are inconsistent.
2. There message misses 3 activities for the created C# project.
![logmessage](https://user-images.githubusercontent.com/34729022/50142944-454e3e00-02e6-11e9-97aa-5420d4dadf43.png)

**Comment by ahmedelnably** [comment]
Closing as stale
