### ISSUE TITLE
Login via PowerShell module `Az` version 1.0 not working

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-functions-core-tools#952]
`Az.Profile` was renamed to `Az.Accounts` and now you can't use `Az` to login for core tools. Originally @markekraus found this issue.

We need to update the constant here:
https://github.com/Azure/azure-functions-core-tools/blob/1f1f77a71c5517b00401aa0ebf00a4f16857a94c/src/Azure.Functions.Cli/Actions/AzureActions/BaseAzureAction.cs#L20

opening this in case @Francisco-Gamino or someone else wants to pick up this low hanging fruit.

**Comment by ahmedelnably** [comment]
@Francisco-Gamino Is this still valid?

**Comment by TylerLeonhardt** [comment]
Looks like I made this change a year ago. 

https://github.com/Azure/azure-functions-core-tools/commit/d7733ab0ab8e401e314ff08eebb5ea1dae0801c9

**Comment by TylerLeonhardt** [comment]
If you folks have telemetry hooks, it'd be interesting to see how many folks use Azure PowerShell to login.

Surely not as much as Az CLI since most of your docs recommend CLI (which should really be fixed... Since Azure offers both) but it'd be really good data.

**Comment by ahmedelnably** [comment]
@TylerLeonhardt will close this, I don't think we have the data on which tool is being used for login
@ankitkumarr adding login provider to our telemetry would be great for future improvements
