### ISSUE TITLE
Cannot connect to logstream of Linux Consumption Function App

### ISSUE THREAD

**Issue by aluong** [Azure/azure-functions-core-tools#953]
pyfunc12345 was created using these [steps](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python). I am able to fetch information about the functionapp with other commands.

(venv) $ func azure functionapp list-functions  pyfunc12345
Functions in pyfunc12345:
    QueueTrigger - [queueTrigger]

(venv) $ func azure functionapp logstream pyfunc12345
**Invalid URI: The hostname could not be parsed.**

**Comment by ankitkumarr** [comment]
Right now, log streaming is not supported directly in Linux Consumption App. You could use Azure App Insights for logging.

I will fix the error to show the appropriate message.
