### ISSUE TITLE
Trying to publish Function App with --build-native-deps access to the path is denied

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-core-tools#965]
_From @TecumsehSamp on January 8, 2019 16:32_

#### Investigative information

Please provide the following:

- Timestamp: 08/01/2019
- Function App name: awinningstrat
- Function name(s) (as appropriate): TimerTrigger

#### Repro steps

Provide the steps required to reproduce the problem:

Trying to publish a function app with --build-native-deps flag immediately exists with a "access to the path 'C:\Users\{myfullname}\AppData\Local\Temp\tmp777Etmp' is denied". 

The local AppData directory it's trying to access is for the same user as the context of the terminal it's trying to run in and they do have access when trying it themselves in file explorer. 

The only difference I can tell is the error message for the path shows {mynamehere} without the period between my first name and last name. The correct path is actually:

C:\Users\{firstname.lastname}\AppData\Local\Temp\tmp777Etmp

#### Expected behavior

The function app is published

#### Actual behavior

Publishing of the function app fails.

#### Known workarounds

None as of now

#### Related information 

Provide any related information 

* Links to source
* Bindings used
* Dependencies

adal==1.2.0
asn1crypto==0.24.0
astroid==2.1.0
azure==4.0.0
azure-common==1.1.16
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
azure-nspkg==3.0.2
azure-storage-common==1.4.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
colorama==0.4.1
cryptography==2.4.2
Flask==1.0.2
grpcio==1.14.2
grpcio-tools==1.14.2
idna==2.8
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
lazy-object-proxy==1.3.1
MarkupSafe==1.1.0
mccabe==0.6.1
protobuf==3.6.1
pycparser==2.19
PyJWT==1.7.1
pylint==2.2.2
python-dateutil==2.7.5
requests==2.21.0
six==1.12.0
typed-ast==1.1.1
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.10.11

_Copied from original issue: Azure/azure-functions-python-worker#275_

**Comment by ahmelsayed** [comment]
@TecumsehSamp looks like this https://github.com/Azure/azure-functions-core-tools/commit/9ec27ce168ff5aa462ba185f37b40d352a062ce5 which should be fixed in 2.3.199 which is the current release. What version of func do you have? You can get the version by `func --version` or by just typing func, it'll be at the very top.

**Comment by ankitkumarr** [comment]
@ahmelsayed, I think we missed [this](https://github.com/Azure/azure-functions-core-tools/blob/4fbdca7dd153513fbc4dee346c43f4ea01ad9e62/src/Azure.Functions.Cli/Helpers/PythonHelpers.cs#L248) one. I am surprised we didn't catch that.
