### ISSUE TITLE
Testing core-tools scenarios for Python

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-core-tools#971]
We need to have a set of tests that pull the latest version of the Python Language Worker and test the various deployment options that the user has. This is in lieu of the manual validation that we are undertaking today. These scenarios, as I understand them, fall into the following categories with some combinations as well:

1. --build-native-deps
2. --no-bundler
3. Bundling with PyInstaller 

We can do this as part of the nightly builds where the latest worker and library are pulled from their respective repos. 

1. https://github.com/Azure/azure-functions-python-worker 
2. https://github.com/Azure/azure-functions-python-library

We have had breaks before where we did not fully account for the interaction between our Python worker and core tools. Ideally, the core tools would be agnostic to the structure of the Python worker, which is the eventual goal, but currently we should have tests that ensure that we are not breaking deployment scenarios.

**Comment by maiqbal11** [comment]
cc @asavaritayal @ankitkumarr @ahmelsayed

**Comment by maiqbal11** [comment]
Tracking under https://github.com/Azure/azure-functions-python-worker/issues/274.

**Comment by ankitkumarr** [comment]
This is closed by https://github.com/Azure/azure-functions-python-worker/pull/332
