### ISSUE TITLE
Allow specification of assets with PyInstaller

### ISSUE THREAD

**Issue by jaycle** [Azure/azure-functions-core-tools#977]
Many projects have static assets which could be bundled by PyInstaller for zip deployment. However, there is no way to specify through the current CLI or through modification of the `python_bundle_script.py` (because it's built into the binary) where assets are and so they are not bundled. This feature _is_ however supported by PyInstaller through `--add-data`. I'm aware we can workaround with `--no-bundler` but then users pay a startup penalty.

Could we specify assets through either:

1. Convention (standardized folder structure)
2. CLI option (i.e. `--assets=<dir(s)>`)
3. Config file (like, but not necessarily `function.json`)

I'm not sure the mechanism matters as much as just having the support somehow for python projects in Azure functions.

**Comment by ankitkumarr** [comment]
@jaycle, I will be working on a change to update the script to include any/all data present in the dependencies using `--add-data` (likely by the end of the week), like we do for hidden-imports.

That should solve the missing data issues. If the problem still persists, maybe we can look into specifying assets. But, unless necessary, we want to keep the process abstract so users don't necessarily have to understand all the parameters by Pyinstaller.

**Comment by jaycle** [comment]
@ankitkumarr, That's great. Thank you! In my use case I'm just wanting to serve swagger/coreAPI to go along with my function. I'm not super familiar with PyInstaller but I know that data ends up under `sys._MEIPASS` ([reference](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file-and-sys-meipass)) so some path-prefixing needs to happen. If this will be the case the documentation should probably reflect that.

I'm looking forward to a release with this feature!

**Comment by ankitkumarr** [comment]
@jaycle, just to throw an update-
Apologies for the delay here! We are trying to work out a more permanent solution to the cold start and that's why haven't worked out this ask yet.
I will have an update soon.

**Comment by ankitkumarr** [comment]
Closing this issue because we have decided to stop using Pyinstaller for bundling. With the next release, we are stopping support for bundling.

**Comment by jaycle** [comment]
Any doc links you could provide, @ankitkumarr? Curious if this will break what I'm currently doing.

**Comment by ankitkumarr** [comment]
@jaycle, Apologies for the delay. Announcement got posted today https://github.com/Azure/app-service-announcements/issues/169
