### ISSUE TITLE
"Server encountered an internal error. Please try again after some time."

### ISSUE THREAD

**Issue by riverar** [Azure/azure-functions-core-tools#994]
## Repro steps
1. Open Visual Studio 2017 15.9.5
2. Create new Azure Functions v2 project (empty)
3. Add durable function orchestrator
4. F5 project and note failure

## Expected
Function to be available on local machine for debugging

## Actual
A host error occurred
Microsoft.WindowsAzure.Storage: Server encountered an internal error. Please try again after some time.

![image](https://user-images.githubusercontent.com/475132/51433910-aed5ab00-1c0a-11e9-97aa-4d71560b3c76.png)

## Environment
Azure Functions Core Tools (2.4.249)
Function Runtime Version: 2.0.12265.0
Windows 10 1809

Azure Storage Emulator logs attached
[Logs.zip](https://github.com/Azure/azure-functions-core-tools/files/2776148/Logs.zip)

// Related: #357 
cc: @jeffhollan

**Comment by jeffhollan** [comment]
per linked issue was due to a bad version of the storage emulator.
